### ISSUE TITLE
RestEasy/JAX-RS has no useful hooks

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1016]
There is no easy way to integrate with the RestEasy extension. The single build step accepts a bunch of annotations and spits out servlets.  There should be at least one intermediate step introduced, so that extensions can produce REST handlers that can take advantage of type mapping & etc. via build items.

The first use case for this was @evanchooly's Lambda extension.  I anticipate that there will be more.

**Comment by emmanuelbernard** [comment]
is that still a thing? cc @patriot1burke

**Comment by patriot1burke** [comment]
@emmanuelbernard I implemented this as part of a larger brach, but never merged the changes for this.  Keep the issue open please.  I had the ability to pass around a ResteasyDeployment object that could be added to and the creation of this deployment with a recorder rather than having Undertow do it.

**Comment by stuartwdouglas** [comment]
Should this still be open?
