### ISSUE TITLE
MicroProfile metrics and Graphite

### ISSUE THREAD

**Issue by overthetop** [quarkusio/quarkus#10525]
Currently in v1.5.2 in Quarkus I don't see a way to export MicroProfile metrics to Graphite. The only guide that I've found is this https://quarkus.io/guides/microprofile-metrics which requires you to have a Prometheus monitoring system at hand. We are using grafana and graphite for our monitoring in production and I don't see a way to make this work with Quarkus. I'm looking for something similar to what we have with Spring Boot https://micrometer.io/docs/registry/graphite . I'm pretty sure that will come really handy to all of you who try to integrate Quarkus into their ecosystem

**Comment by jmartisk** [comment]
There is ongoing discussion that MP Metrics could potentially "turn" into Micrometer with a future release, in which case you would get Graphite support OOTB.
There is an experimental Micrometer extension as well with which it should be possible - https://github.com/ebullient/quarkus-micrometer-extension (use purely at own risk ;) )
Not sure if it makes sense under these circumstances to introduce support for Graphite with our current MP Metrics implementation.. MP Metrics are Prometheus-focused and it might not even be practically possible due to very different architecture compared to Prometheus.

**Comment by overthetop** [comment]
Thx @jmartisk Hope that will be impl soon

**Comment by ebullient** [comment]
Just an update for those following along / finding this later. The micrometer extension is officially in core, and there is a graphite extension in quarkiverse: 
```
<dependency>
    <groupId>io.quarkiverse.micrometer.registry</groupId>
    <artifactId>quarkus-micrometer-registry-graphite</artifactId>
</dependency>
```
