### ISSUE TITLE
Allow injecting parameters and body in reactive routes

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#10596]
**Description**
The idea behind this improvement would be to support the injection of request parameters and body as argument of the reactive route method:

```java
@Route(path="/")
public void (RoutingContext rc, @Param("name") String name, Person body)
```

Parameter injection need to be annotated with a specific annotation (maybe reuse the jax-rs one) to indicate which parameter need to be injected.
Optionaly might be a good idea too (`Optional<String>`). Type conversion also. Multiple parameter (List) might also be a nice plus.

For the body, we should support Buffer, JsonObject/JsonArray and object (mapped from body using `bodyAsBuffer().toJson().mapTo(Person.class)`
I don't believe a specific annotation is required for the body. But I may be wrong.

**Comment by mkouba** [comment]
> Parameter injection need to be annotated with a specific annotation (maybe reuse the jax-rs one)

I'd rather not reuse the JAX-RS annotations because that would mean a dependency on the JAX-RS API. Also JAX-RS distinguishes `@javax.ws.rs.QueryParam` and `@javax.ws.rs.PathParam` whereas we should simply map to `io.vertx.core.http.HttpServerRequest.getParam(String)`.

I'm not sure about type conversion. Sometimes it's useful but sometimes it just complicates things unnecessarily. For now I would simply mimic the `HttpServerRequest.getParam(String)` method, i.e. only support `java.lang.String`.

`Optional<String>` is a good idea.

> For the body, we should support Buffer, JsonObject/JsonArray and object (mapped from body using bodyAsBuffer().toJson().mapTo(Person.class)

We should probably cover all `RoutingContext.getBody*()` methods.

> I don't believe a specific annotation is required for the body.

It's probably not mandatory but it might make sense to introduce `@Body`. It's consistent and extensible.

We could also try to mimic `javax.ws.rs.HeaderParam`. Except that the type should be only `String`.

**Comment by cescoffier** [comment]
Ah yes, supporting headers is a great idea!

**Comment by mkouba** [comment]
WIP is here: https://github.com/mkouba/quarkus/tree/issue-10596
