### ISSUE TITLE
Improve the doc-related PR builds

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#10702]
I've broken a `documentation` build with this PR, https://github.com/quarkusio/quarkus/pull/10653#issuecomment-657671432, but the PR build did not detect it, both the PR build and myself were doing only `doc` builds :-).

Proposal: have both `doc` and `documentation` built

**Comment by sberyozkin** [comment]
I've checked the CI runs on my new branch and they fail - not sure why there was a Merge button was activated when I was merging #10653, will keep this issue open for now
CC @gastaldi

**Comment by loicmathieu** [comment]
@sberyozkin I'm the one that created the doc CI build that should detect such issue so i'm partialy the one to blame ;)

I notice that the build failed with this error:
```
[ERROR] Failed to execute goal org.asciidoctor:asciidoctor-maven-plugin:2.0.0:process-asciidoc (output-pdf) on project quarkus-documentation: Found 92 issue(s) of severity WARN or higher during conversion -> [Help 1]
```

The doc CI build only do a standard doc, but the regular CI seems to generates PDF (it uses `-Ddocumentation-pdf`) and it appears the issue was during PDF generation.

So we need to update the doc CI build to also generates the PDF.

**Comment by sberyozkin** [comment]
Hi @loicmathieu It is only my fault :-), but yeah, lets add that `-Ddocumentation-pdf`, please create a PR, or I can do it ?

**Comment by loicmathieu** [comment]
You can do it

**Comment by gastaldi** [comment]
I tested locally and indeed this flag fails the build when the generation fails. I opened #10734 :wink:
