### ISSUE TITLE
Improve errors on attempt to run a Quarkus application packaged as a WAR type

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#10807]
**Description**
Following up on user's troubles reported on #10789

Could we raise a nicer, more explicit error message? Question for @stuartwdouglas / @aloubyansky

**Comment by cpoels** [comment]
As the original reporter of the issue I want to make a proposal for such a explicit error message:

When building a normal (non-Quarkus) WAR Maven will fail the build when no web.xml is provided and you can disable this behaviour via the ```<failOnMissingWebXml>``` property.
Maybe the Quarkus plugin can implement something similar: Failing the build if packaing type is not default or set to something different to JAR. We just don't need the "disable property" here because as stated by @famod the WAR type is unnecessary/misleading.
