### ISSUE TITLE
Native app won't come up

### ISSUE THREAD

**Issue by ravirajb** [quarkusio/quarkus#10861]
**Describe the bug**
The native app won't start the application

**Expected behavior**
The web app should be reachable 

**To Reproduce**
1. Take a spring boot app.
2 Add the Quarkus dependencies
3. Build the native image
4. Run the runner.
5. It starts the app, but unable to reach the URL.

Log: 
_```
Ravis-MacBook-Pro:ysn-proj ravi$ target/ysn-core-api-0.0.1-SNAPSHOT-runner 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2020-07-20 21:46:28,054 INFO  [io.quarkus] (main) ysn-core-api 0.0.1-SNAPSHOT native (powered by Quarkus 1.6.0.Final) started in 0.118s. Listening on: http://0.0.0.0:8080
2020-07-20 21:46:28,055 INFO  [io.quarkus] (main) Profile prod activated. 
2020-07-20 21:46:28,055 INFO  [io.quarkus] (main) Installed features: [cdi]
```_

**Comment by ravirajb** [comment]
Possibly because currently we don't support reflection in Java? Not sure.

I really don't wish to refactor the spring-boot project. 

Is there an easier way to port the boot project to quarkus?

**Comment by Sanne** [comment]
You shouldn't expect that just adding the Quarkus dependencies to an existing Spring project will make it a Quarkus project.

Many APIs are very similar, but even when you use the Spring APIs in Quarkus, these are meant only as a facilitator: they are meant to make it easy for you to write a new application if you have Spring experience, they are not meant to port an existing application without any effort from your part.
The configuration properties are also different, and I would recommend you check our guides.

Reflection is not a problem when you use the Quarkus extensions. But sure, it will be a problem if you use the Spring libraries instead of the Quarkus extensions.

I don't think we have a migration guide from Spring yet; maybe you could help writing one?

I'll close this as this isn't a bug - this is expected. Thanks!
