### ISSUE TITLE
quarkus-jdbc-mssql brings in a version of adal4j that doesn't work with Azure SQL Server AD Password Authentication

### ISSUE THREAD

**Issue by jamesobrooks** [quarkusio/quarkus#11324]
Version 1.6.3 of adal4j causes a 'String cannot be cast to List' exception while attempting to parse the token while connecting to Azure SQL Server via AD Password Authentication.

**Expected behavior**
The token should be parsed properly and user should Authenticate or not correctly.

**Actual behavior**
The token fails to parse and health/ready check responds with the following:
```
{
    "status": "DOWN",
    "checks": [
        {
            "name": "Database connections health check",
            "status": "DOWN",
            "data": {
                "default": "Unable to execute the validation check for the default DataSource: Failed to authenticate the user *** in Active Directory (Authentication=ActiveDirectoryPassword)."
            }
        }
    ]
}
```

Stack Trace:
```
ERROR [com.mic.aad.ada.AuthenticationContext] (pool-8-thread-1) [Correlation ID: 97ba0eb4-4951-40fb-8d0f-76e0116cdd10] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.: java.lang.ClassCastException: class java.lang.String cannot be cast to class java.util.List (java.lang.String and java.util.List are in module java.base of loader 'bootstrap')
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101)
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159)
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85)
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70)
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38)
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

WARN  [io.agr.pool] (Agroal_4742868021) Datasource '<default>': Failed to authenticate the user *** in Active Directory (Authentication=ActiveDirectoryPassword).
```

**To Reproduce**
1. Set up Azure SQL Server database with the JDBC (Active Directory password authentication) connection string.
2. Set quarkus.datasource.mssql.db-kind to mssql.
3. Import quarkus-jdbc-mssql (1.6.1.Final) [and gson 2.8.6?].
4. Start service and hit /health/ready

**Configuration**
```properties
"%dev":
  quarkus:
    datasource:
      jdbc:
        url: jdbc:sqlserver://example.database.windows.net:1433;database=db_name;user=user@example.com;password=****;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;authentication=ActiveDirectoryPassword
      hibernate-orm:
      log:
        sql: true
    log:
      console:
        enable: true
        level: DEBUG
        color: true
    oidc:
      auth-server-url: url
      client-id: application
  application:
    baseUrl: http://localhost:8080/application
"%dev-deploy":
  quarkus:
    datasource:
      jdbc:
        url: similar
    oidc:
      auth-server-url: url
"%test-deploy":
  quarkus:
    datasource:
      jdbc:
        url: similar
    oidc:
      auth-server-url: url
"%prod-deploy":
  quarkus:
    datasource:
      jdbc:
        url: similar
    oidc:
      auth-server-url: url
quarkus:
  datasource:
    db-kind: mssql
    health:
      enabled: true
  http:
    root-path: /path
  oidc:
    client-id: application
application:
  name: Application
```

**Corrected By**
```
        <dependency>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-jdbc-mssql</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.microsoft.azure</groupId>
                    <artifactId>adal4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>adal4j</artifactId>
            <version>1.6.5</version>
        </dependency>
```

**Environment (please complete the following information):**
 - Output of `uname -a`: MINGW64_NT-10.0 WINX-21937 2.11.2(0.329/5/3) 2018-11-10 14:38 x86_64 Msys
 - Output of `java -version`: JAVA_PACKAGE=java-11-openjdk-headless (not technically output of 'java -version')
 - GraalVM version (if different from Java): using jvm in this example
 - Quarkus version or git rev: 1.6.1.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Maven home: C:\Progra~1\apache-maven-3.6.3

**Comment by gsmet** [comment]
@Sanne do you think we could consider upgrading Adal4j in Quarkus?

**Comment by Sanne** [comment]
I'm not sure, we should explore this.

I had to severely trim the dependency tree of this driver - knowingly disabling Azure specific integrations - to make it work in native image.

We could have a second look as supposedly things could be simpler now after nearly 2 years of GraalVM improvements, but the amount of dependencies of this driver also concerns me in terms of dependency convergence: we'd need to manage a significant amount of dependenencies in the primary BOM, and some of these dependencies are popular projects so there's going to be a high degree of pain.

The better solution is likely to reach out to the MSSQL team and hope for better modularization of the driver. I have good hopes for this as it seems the driver is otherwise very well maintained and nicely designed, but it's going to take time.

**Comment by Sanne** [comment]
cc/ @n1hility ^

**Comment by diodfr** [comment]
I am also impacted by this issue since [Managed System Identity] (https://docs.microsoft.com/en-us/sql/connect/jdbc/release-notes-for-the-jdbc-driver?view=sql-server-ver15#active-directory-managed-identity-msi-authentication) does not work either.
The mssql-jdbc used here seems a little bit outdated [7.2.2.jre8](https://github.com/quarkusio/quarkus/blob/d7048f35ee1be0b53edac621e13a79a93a91ab34/bom/application/pom.xml#L126). 
https://github.com/microsoft/mssql-jdbc
https://search.maven.org/artifact/com.microsoft.sqlserver/mssql-jdbc
```
<dependency>
  <groupId>com.microsoft.sqlserver</groupId>
  <artifactId>mssql-jdbc</artifactId>
  <version>9.2.1.jre8</version>
</dependency>
```

It seems that there is a new way to use ActiveDirectoryAuthentication as described [here](https://github.com/microsoft/mssql-jdbc#azure-key-vault-and-azure-active-directory-authentication-dependencies)

Any chance that you would reconsider the integration of these ?
Is there an easy way for me to try it ?

Thank you for your work.

**Comment by jamesobrooks** [comment]
Looks like adal4j is no longer in the dependency tree for `quarkus-jdbc-mssql`.
