### ISSUE TITLE
Support for Integer parameters in quarkus-vertx-web

### ISSUE THREAD

**Issue by rodolfodpk** [quarkusio/quarkus#11481]
Hello, I noticed just the first method works. Integer support parameter would be nice.

```
import io.quarkus.vertx.web.Param;
import io.quarkus.vertx.web.Route;
import io.quarkus.vertx.web.RouteBase;
import io.vertx.core.http.HttpMethod;
import org.eclipse.microprofile.openapi.annotations.tags.Tag;
import javax.enterprise.context.ApplicationScoped;

@ApplicationScoped
@RouteBase(path = "/v3/customer", produces = "application/json")
@Tag(name = "customer", description = "Data about customer")
public class CustomerResource3 {
  static class Customer {
    public String name;
  }
  @Route(produces = "application/json", path = "/works/:customer_id", methods = {HttpMethod.GET})
  Customer get1(@Param("customer_id") String customerId) {
    Customer c = new Customer();
    c.name = "customer-" + customerId;
    return c;
  }
  /* TODO comment out bellow method to see the error
  @Route(produces = "application/json", path = "/error/:customer_id", methods = {HttpMethod.GET})
  Customer get2(@Param("customer_id") Integer customerId) {
    Customer c = new Customer();
    c.name = "customer-" + customerId;
    return c;
  }
  */
}
```

**Comment by mkouba** [comment]
Currently, we intentionally don't support any kind of automatic conversion of parameters. The idea is to keep the API as simple as possible. And since `@Param` is just a shortcut for `routingContext.request().getParam(name)` we only support `String`, `Optional<String>` and `List<String>`.

That being said, it should be really straightforward to add param injectors for some other basic types (`Integer`, `Long`, etc.). On the other hand, we should consider if it's worth it and if so whether we should add some SPI to make it extensible.

**Comment by rodolfodpk** [comment]
Since it seems straightforward to  implement and it just works with quarkus-resteasy + openapi, I think it's worth to have quarkus-vertx-web + openapi on same developer's experience level.
