### ISSUE TITLE
Should be able to call a method annotated with @Startup

### ISSUE THREAD

**Issue by survivant** [quarkusio/quarkus#11710]
and I have a main controller with

```java
@Startup(0)  // I used 0 because I want to be the first class to startup
public class MainController {

@Inject
Instance<ICodec> codecs; // Codecs auto-discovery

@PostConstruct
void init() throws Exception {
// loop in codecs list
for(ICodec codec : codecs){
   ....
}
....
}
```

Because it's looping the ICodec list... there @PostConstruct will be called

something like

```java
@Override
@PostConstruct
protected void init() throws Exception {
    // if already initialized, do nothing
    if (initialized.getAndSet(true)) {
        return;
    }

    super.init();


}
```

so far.. everthing OK.  

I added @Startup  on a method to execute after that MainController @PostConstruct complete

```java
@Startup
private void install() throws Exception {
....
}
```

that method will do some installating stuff after that MainController is completed.. but the method is not called.    

```java
@Target({ElementType.TYPE, ElementType.METHOD, ElementType.FIELD})
@Retention(RetentionPolicy.RUNTIME)
public @interface Startup {
    int value() default 2500;
}
```

I didn't call the install method from the @PostConstruct init, because I have a reference to MainController, but because the Codec is created by the @InjectInstance, it doesn't have to reference to MainController yet.  I though that I could add @Startup on any method that could be executed at launch .

```
Ladislav is correct ;-)

The annotation javadoc states:

"This annotation can be used to initialize a CDI bean at application
startup."

and

"In fact, a synthetic observer of the StartupEvent is generated for each
bean annotated with this annotation."

METHOD and FIELD targets are only useful for producers. And the producer
must be @Dependent, because it's not possible to declare a lifecycle
callback there.

Being able to invoke an arbitrary method on startup is an interesting
idea though. Would you care to create an enhancement issue ;-).

Thanks,

Martin
```

**Comment by mkouba** [comment]
Let me give some background information. Right now, `@Startup` can only be used to initialize a CDI bean at application startup, i.e. the contextual instance is created and, eventually, `@PostConstruct` lifecycle callbacks are invoked. 

It could be also useful to be able to annotate one or more arbitrary business methods with `@Startup` with the following semantics: 
1. Create a contextual instance of the declaring bean
2. Call `@PostConstruct` lifecycle callbacks
3. Call the annotated methods

So that instead of:
```java
class Starter {
   void onStart(@Observes StartupEvent event) {
      LOG.info("The application is starting...");
   }
}
```
or even:
```java
@Startup
class Starter {
   @PostConstruct
   void init() {
       LOG.info("The application is starting...");
   }
}
```
the following syntax could be used:
```java
class Starter {
   @Startup 
   void onStart() {
      LOG.info("The application is starting...");
   }
}
```

There would be some diffferences though. E.g. the observer method can inject dependencies whereas the `@Startup` method cannot do this.
