### ISSUE TITLE
OIDC: User-Info for type `service` 

### ISSUE THREAD

**Issue by wicksim** [quarkusio/quarkus#12227]
**Description**
I need to have additional user-info from OIDC. There is `quarkus.oidc.authentication.user-info-required`, but this only works for type `web-app`. But I've type `service`. Maybe it is against spec to implement this, I don't know.

**Implementation ideas**
I think functionality for this is already implemented in `OidcIdentityProvider` (`getUserInfo`), but in my case, parameter `opaqueAccessToken` is null.

**Comment by sberyozkin** [comment]
@wicksim the reason it has not been added for the `service` but only for `web-app` is because  a user info endpoint is about returning more information about the user authenticated via the code flow, in case when the ID token does not have enough user-related claims.
I suppose, there maybe nothing wrong with the downstream services which are only seeing the bearer token trying to access the user info endpoint, as long as the bearer token has the right scope it should work...
CC @pedroigor

**Comment by wicksim** [comment]
Exactly my problem. I'm getting an access-token from the user. Our OIDC-system doesn't put `preferred_username`-claim in the access-tokens, so I'm missing the "real username", which I need for some reasons.

If this would be implemented, would the preferred username be available in the `SecurityIdentity`?

**Comment by sberyozkin** [comment]
Right now it is `io.quarkus.oidc.UserInfo` bean which will be available and you can check that attribute.

**Comment by wicksim** [comment]
That would be fine too...
