### ISSUE TITLE
0.0.0.0:8080 does not resolve on windows

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#12246]
**Describe the bug**
on linux and osx you can just click the link printed in console: 0.0.0.0:8080 and the browser will figure it out - but on windows that gives an error: Can't reach this page.

**Expected behavior**
that users can copy/paste/click the urls shown in console to open browser

**Actual behavior**
broken on windows.

...could we convert 0.0.0.0:8080 to 127.0.0.1:8080 on windows or would that be misleading as its technically bound to any of the interfaces on the machine.

just wondering if there is a way to make the links work on windows.

**Comment by belu** [comment]
@maxandersen 

A ping to 0.0.0.0 on Linux actually resolves to 127.0.0.1. Under windows this address is not pingable.

IMHO it would be more concise to show 127.0.0.1 in the console to click on. That should work locally for all operating systems.
And non-locally the 0.0.0.0 does not work for any OS :-)

**Comment by maxandersen** [comment]
I think that's what I suggest - convert 0.0.0.0 to 127.0.0.1 on console print. 

Btw. 127.0.0.1 doesn't work anywhere but locally thus not sure what you mean by non-locally.

**Comment by belu** [comment]
I would print 127.0.0.1 instead of 0.0.0.0 for all operating systems. Not just for windows. That 0.0.0.0 is redirecting to 127.0.0.1 on Linux seems to be a hack.

In my comment I said that 0.0.0.0 (and not 127.0.0.1) does not work remotely. Therefore, for remote access you don't gain anything if you display 0.0.0.0 in the console (and e.g. copy it).

Conclusion: as I am forced to use Windows at work I would be happy to see a link in the console that is working. Every co-worker that starts with Quarkus just wonders why this link that you see there is not working out-of-the-box. And you know: the first impression is the most important one.

**Comment by geoandri** [comment]
Hi @maxandersen ,

do you happen to know who should I ping for a review on this PR?

**Comment by maxandersen** [comment]
Pinged on the pr! Thanks!

**Comment by geoand** [comment]
Seems like this has since been fixed, so I'll close it
