### ISSUE TITLE
Support OIDC hybrid application type

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#12297]
**Description**
We have discussed it at #12254 with @canidae.
The same endpoint should be able to authenticate both the clients sending the bearer tokens and human users. We already have a multi-tenancy mechanism in place where a custom resolver would choose, based on whether token is available or not which application type (`service` or `web-app` => either Bearer or CodeAuth mechanism) to use.
The minor downside there is that, if the tenants are configured statically, then effectively, there are 2 nearly identical tenant configuration blocks (the only diff is `service` vs `web-app` type). This can be be completely isolated into `TenantConfigResolver`.

But having an option just to say `application-type=hybrid` with a single (default) tenant configuration would improve a user experience a bit.  

**Implementation ideas**
`OidcAuthenticationMechanism`, when choosing either Bearer or CodeAuth mechanism, will check, if the application type is `hybrid`, if the token is available, if yes - it is Bearer one, otherwise - CodeAuth.

The only concern here is that the bearer path will be inconsistent with the normal `service` when dealing with missing tokens - in the normal case it would be `401`, with `hybrid` - redirect to authenticate

CC @pedroigor @stuartwdouglas

**Comment by sberyozkin** [comment]
Actually, I've realized it won't really work, a single Keycloak realm can't represent both `service` and `web-app` Quarkus applications (which `hybrid` implies), is it correct ?

**Comment by sberyozkin** [comment]
Reopening for @canidae to experiment

**Comment by canidae** [comment]
This took me all evening as I had to figure out quite a lot of things. I could not get Keycloak to import the realm after I modified it (as explained in the guide below), and learning the test system of Quarkus would take me several more hours, so I can't easily make a demo where you just can press "play".
I've tried to make this guide as simple as possible to demonstrate that a single client in a single realm that can both be used as "web-app" and "service" at the same time. It shouldn't take many minutes going through this guide to verify it yourself.
I've used one of the quickstart projects to demonstrate this, it can be found here: https://github.com/canidae/quarkus-quickstarts/tree/master/security-openid-connect-web-authentication-quickstart (all changes done in a single commit, referenced just above this comment).

**Keycloak setup (I tried exporting the realm, but got an error when attempting to reimport it, thus this setup guide):**
1. Execute `docker run --rm --name keycloak -e DB_VENDOR=H2 -e KEYCLOAK_USER=admin -e KEYCLOAK_PASSWORD=admin -e "TZ=Europe/Oslo" -p 8180:8080 quay.io/keycloak/keycloak:10.0.1`.
   Remember to set correct timezone for your location, otherwise tokens may be invalid.
2. Login to http://localhost:8180/auth with admin/admin.
3. Add realm and import `quarkus-realm.json`.
4. Go to client "frontend" (this link will likely work: http://localhost:8180/auth/admin/master/console/#/realms/quarkus/clients/0ac5df91-e044-4051-bd03-106a3a5fb9cc).
5. Change "Access Type" from "public" to "confidential".
6. Set "Service Accounts Enabled" and "Authorization Enabled" to "ON".
7. Click "Save" at bottom of page.
8. Go to tab "Service Account Roles" and add role "user".
9. Go to tab "Credentials", copy the Secret value then paste it in the following two places:
   Line 19 in BearerTokenTest.java: .param("client_secret", "<paste secret here>")
   Line 3 in application.properties: quarkus.oidc.credentials.secret=<paste secret here>

When this is done you can first test that bearer token authentication works by executing test class BearerTokenTest.
This should print:
```
Token: <bearer token>
Response code with token: 200
Response code body: <html><body><ul><li>scopes: email profile</li></ul></body></html>
Response code with invalid token: 401
```
Attempting to visit http://localhost:8080/tokens with a browser will obviously give you a 401 response, as your request then have no Authorization header.

Then you can uncomment `#quarkus.oidc.application-type=web-app` in application.properties and revisit http://localhost:8080/tokens with a browser. This will take you to a login page, and if you log in as alice/alice you'll be returned to the page, displaying about the same basic data as returned by BearerTokenTest.
Attempting to execute the BearerTokenTest class with `application-type=web-app` cause the login page to be returned instead of the basic data, as expected.

What we've done here is access a protected resource, using a single client on a single realm. We've done it using Authorization header (when application-type was "service") and with cookie (when application-type was "web-app").
This is why I desire either a "hybrid" (service+web-app) application-type, or another way to access the same path where client either supplies an Authorization header or a cookie. My attempts at the latter using multi-tenancy has so far caused blocked threads (see discussion here for details: https://github.com/quarkusio/quarkus/issues/12254).

**Comment by canidae** [comment]
I realized that even while a single client can be used both as "web-app" and "service", it is in fact irrelevant.
Instead of using client "frontend" in BearerTokenTest I created a new client (leaving the "frontend" client with access type "public"). So in application.properties I used client "frontend", and in BearerTokenTest I used the newly created client "test". When "application-type" is set to "web-app" I can access http://localhost:8080/tokens using the browser with cookie authentication. Setting "application-type" to "service" I can access http://localhost:8080/tokens using header authentication.

The issue is that I can't access http://localhost:8080/tokens with cookie authentication or header authentication at the same time.

**Comment by sberyozkin** [comment]
@canidae I appreciate you spending the time and trying to prove it can work with Keycloak (same client id, same realm) but let me tell you again that the multi-tenancy in your case is equals `hybrid`, Quarkus would do pretty much the same you'd do in your custom resolver. It is difficult to do anything about the fact that the demo hangs after you update it because this demo realm is not updated. If it can work in principle then the custom resolver will work. 
So you have it working right ? So lets avoid creating `OidcTenantConfig` manually, in your working application create the default tenant configuration with a type service, and a `tenant-web-app` for `web-app`, and have a simpler `CustomTenantResolver` which only returns tenant id. if Authorization header is there - return null (=> default configuration) or else return "tenant-web-app". 
What will happen now ?
Thanks

**Comment by canidae** [comment]
> So you have it working right ? So lets avoid creating `OidcTenantConfig` manually, in your working application create the default tenant configuration with a type service, and a `tenant-web-app` for `web-app`, and have a simpler `CustomTenantResolver` which only returns tenant id. if Authorization header is there - return null (=> default configuration) or else return "tenant-web-app".
> What will happen now ?

Admittedly I did test CustomTenantResolver already, the reason it failed earlier was because I was under the impression that you had to have `{tenant}` somewhere in the `@Path` (as shown by the examples). This assumption turned out to be false, and finally I'm successful at accessing the same path using either cookie authentication or header authentication.
I appreciate the time & effort you've put into helping me resolve this problem, thank you.

I'll add my current CustomTenantResolver and application.properties for anyone else who may encounter this issue in the future:
**CustomTenantResolver**
```
import javax.enterprise.context.ApplicationScoped;

import io.quarkus.oidc.TenantResolver;
import io.vertx.ext.web.RoutingContext;

@ApplicationScoped
public class CustomTenantResolver implements TenantResolver {

    @Override
    public String resolve(RoutingContext context) {
        return context.request().getHeader("Authorization") == null ? "webapp" : null;
    }
}
```

**application.properties:**
```
quarkus.oidc.auth-server-url=http://localhost:8180/auth/realms/quarkus
quarkus.oidc.client-id=frontend
quarkus.oidc.credentials.secret=b5a662fb-9729-435c-9e28-f0450300d6b6
quarkus.oidc.roles.source=accesstoken

quarkus.oidc.webapp.auth-server-url=${quarkus.oidc.auth-server-url}
quarkus.oidc.webapp.client-id=${quarkus.oidc.client-id}
quarkus.oidc.webapp.credentials.secret=${quarkus.oidc.credentials.secret}
quarkus.oidc.webapp.roles.source=${quarkus.oidc.roles.source}
quarkus.oidc.webapp.application-type=web-app
```

I'll leave https://github.com/quarkusio/quarkus/issues/12268 open for you to decide as inheritance would mean you can skip 4 configuration values in the example above. While I still feel a "hybrid" application-type would be more user friendly (no need for neither the CustomTenantResolver nor the duplicated config), I understand why you're reluctant to add such a feature. For my part this issue can thus be closed.

**Comment by sberyozkin** [comment]
@canidae thanks, I'm looking at it anyway, as there could be a connection saving achieved with `hybrid`

**Comment by sberyozkin** [comment]
The only main requirement which every tenant must meet is that `quarkus.oidc.auth-server-url` is set and `client-id` is set. We probably should've enforced the client always sets some secret/etc but some tests just use simple clients, and may be some deployments protected deployments might use a client id only. 
Inheriting other properties will be messy, especially given that some properties have the default values, some may make sense for the default tenant but not for the other tenant.
Now that #12320 is opened, there will be 2 ways to make it optimal (another one - custom `TenantConfigResolver`). The case where the same realm and client id/secret are used for the bearer/code flow is rare, and it will be covered very well, esp, with #12320.
So I'll close this one for now

**Comment by sberyozkin** [comment]
@canidae sorry I'm a;; over the place, I meant to close the config inheritance issue :-)
