### ISSUE TITLE
Vault guides are missing from the website

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#12583]
**Describe the bug**
Vault guides have disappeared from https://quarkus.io/guides/
They are accessible with the direct url (e.g. https://quarkus.io/guides/vault), but they are not listed in the main page.

**Expected behavior**
There should be 4 guides

**Comment by gsmet** [comment]
I think I removed them when @sberyozkin worked on having an entry point for everything security here https://quarkus.io/guides/security .

**Comment by gsmet** [comment]
But I agree it's probably not a very good idea now that we have the search engine.

**Comment by sberyozkin** [comment]
Yes, `security.adoc` is meant to be an entry page into everything about Quarkus security.
Should the website have a Quarkus Security reference ?

**Comment by vsevel** [comment]
we can have both the security page plus some of the specific guides.
for vault, I would include only the main one if we want to save some space on the website (i.e. vault.adoc), because in this main vault guide I make some references to the others (transit, auth and ds).

**Comment by sberyozkin** [comment]
Hi Vincent @vsevel and Guillaume @gsmet  
What happens now, is that when I type `Quarkus Security` it immediately brings me/the users to this central security `dashboard` which is security.adoc.

So IMHO it can work if we have the website will also reference `Quarkus Security`, in fact it is already referenced. May be the description should be enhanced a bit, instead of:
```
This guide is the entry point to everything security in Quarkus. 
```
have
```
This guide is the entry point to everything security in Quarkus: authentication, authorization, secret engines such as Vault, etc  
```
something like that. We can think about a compact enough but informative sentence.

I've also been planning to add a `Vault` subsection here, https://quarkus.io/guides/security#secret-engines, once Google Secret engine is added, https://github.com/quarkiverse/quarkiverse-google-cloud-services/pull/3#issuecomment-704341447, and we also have a pending Amazon Secret Engine PR...

I think if we start moving some more references back to the website, then we have to pick all of the references from `security.adoc` as opposed to `Vault` only, so as to represent the complete picture, similarly to `Data` etc...

What do you think ?

**Comment by vsevel** [comment]
@sberyozkin if all guides were organized that way (e.g. data, web service, ...), I would say yes.
but the website has some very focused guides (e.g. apache cassandra guide). so there is an expectation that all guides will be there.
my personal experience was that I typed "Vault" in the search box and could not find them. so I tried to find them with the browser feature, and I assumed it had been dropped. if I had not known that they were there, I would have thought that there was no support. I don't believe I would have assumed that it was security, so the right place to search for them was in the security guide. may be that is just me.
extensions are selling points. it would be sad it somebody left the page thinking that there was no Vault support, or Google Secret engine, ...

**Comment by gsmet** [comment]
Yeah I think we probably need to bring back the main Vault guide. @vsevel could you write a short description covering what's covered in it (including the subguides)?

**Comment by vsevel** [comment]
@gsmet the [ain vault guide](https://quarkus.io/guides/vault) has something like this:

> HashiCorp Vault is a multi-purpose tool aiming at protecting sensitive data, such as credentials, certificates, access tokens, encryption keys, …​ In the context of Quarkus, several use cases are supported:
> 
> mounting a map of properties stored into the...

would that work?
