### ISSUE TITLE
Quarkus can't consume a soap web service

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#12757]
Consider code1:

> URL url = new URL("http://www.dataaccess.com/webservicesserver/numberconversion.wso?WSDL");
> NumberConversionSoapType port = new NumberConversion(url).getNumberConversionSoap();
> System.out.println(port.numberToWords(BigInteger.valueOf(12301L)));

And code2:

> URL url = new URL("http://www.learnwebservices.com/services/hello?wsdl");
> HelloEndpoint port = new HelloEndpointService(url).getHelloEndpointPort();
> HelloRequest helloRequest = new HelloRequest();
> helloRequest.setName("max johnson");
> System.out.println(port.sayHello(helloRequest).getMessage());

The web service classes are generated with cxf-codegen-plugin:wsdl2java plugin.

When executed in Java SE main class, the web services are consumed just fine.

When executed inside Quarkus application, the following exceptions are thrown:
code1: javax.xml.ws.soap.SOAPFaultException: Fault occurred while processing
code2: javax.xml.bind.UnmarshalException: unexpected element (uri:"http://www.dataaccess.com/webservicesserver/", local:"NumberToWordsResult"). Expected elements are <{}NumberToWordsResult>

**To reproduce**
Use https://github.com/AmsterdamFilho/quarkus-soap-client-test

Steps to check the code failing in Quarkus:
1. Compile the quarkus application with mvn:compile
2. Run the application in dev mode
3. Open the swagger-ui
4. Execute the endpoints

Steps to check the code working in Java SE:
1. Compile the application with mvn:compile
2. Run the main class

**Comment by AmsterdamFilho** [comment]
If someone could take a look and provide at least a workaround, it would be much appreciated.

I already have an application in Quarkus using reactive Kafka and Postgres, and the only thing missing is consuming a legacy web service.

**Comment by shumonsharif** [comment]
For reference:  https://github.com/shumonsharif/quarkus-cxf/issues/8#issuecomment-710134800

**Comment by famod** [comment]
We do include CXF in our multimodule Maven Quarkus app (without a CXF extension) and so far we did not have any major problems in JVM mode.
If I find some time I can post some details about our integration approach.
One first heads-up: Have you tried `quarkus-jaxb`?

**Comment by AmsterdamFilho** [comment]
@famod If you could share your integration approach, at least the pom.xml, it would be of great help. Just adding quarkus-jaxb did not solve for me.

**Comment by AmsterdamFilho** [comment]
@famod @shumonsharif I rewrote the issue and the reproducer in a much more specific way.

**Comment by shumonsharif** [comment]
@AmsterdamFilho All the services in the reproducer are passing fine for me (both javase and quarkus), see images.  I'm suspecting this may be due to consuming the third party web services across the internet, possibly;  perhaps the network traffic is getting routed differently based on where the web services are invoked from?  Given we have no control over the third party web services, may be worthwhile to look into recreating these issues using a self-contained, local web service.

<img width="1680" alt="hello-success" src="https://user-images.githubusercontent.com/13334073/97169578-a9eb4700-1760-11eb-9ce6-6d97474e149d.png">
<img width="1680" alt="number-conversion-success" src="https://user-images.githubusercontent.com/13334073/97169579-a9eb4700-1760-11eb-90c7-06a86fd20af5.png">
<img width="1678" alt="place-lookup-success" src="https://user-images.githubusercontent.com/13334073/97169581-aa83dd80-1760-11eb-913c-947c683b7f02.png">

**Comment by shumonsharif** [comment]
@AmsterdamFilho So I connected to a VPN server in Brazil, but was still unable to recreate the failures.  At this point, my best guess is that there may be a race condition as you mentioned in https://github.com/shumonsharif/quarkus-cxf/issues/8#issuecomment-710820398 ; and curious if anyone else may be facing a similar issue.

**Comment by ppalaga** [comment]
Please report all CXF related issues under [Quarkus CXF](https://github.com/quarkiverse/quarkus-cxf/issues)
