### ISSUE TITLE
OIDC with REST-endpoint using "code" query-parameter fails

### ISSUE THREAD

**Issue by haraldatbmw** [quarkusio/quarkus#12756]
**Describe the bug**
My service uses OIDC (type=web-app) and has a REST-API /hello?**code**=abc.
The **Query-Parameter code** conflicts with the OIDC authorization code flow.

```
DEBUG [io.qua.oid.run.CodeAuthenticationMechanism] (vert.x-eventloop-thread-13) The state cookie is missing after a redirect from IDP
```

**Expected behavior**
I can use any query-parameter name in my REST API without conflicting with OIDC extension.

**Actual behavior**
The REST API returns wrong response status code.

**To Reproduce**
Follow the steps in the README.md of
https://github.com/haraldatbmw/oidc-code-query-parameter

**Environment (please complete the following information):**
 - Quarkus version or git rev: 1.8.3.Final

**Comment by sberyozkin** [comment]
It is a tricky one. The only way for us to assume that a `code` is a custom query parameter is when a code flow `state` cookie is missing so instead of failing the authentication we can issue a challenge. The problem with this solution is that there were a lot of redirect loops reported earlier when a state cookie was lost due to the wrong cookie path/etc, and also we can hide a CSRF attempt.
I've spent virtually half a day peering into the code trying to find some workaround and I failed so far :-)

I suspect we may have to introduce a property - something like `quarkus.oidc.authentication.challenge-without-state-cookie` (as opposed to current 401) - this should be all right - if the cookie paths are set up properly then the proper state cookie will never be lost, and if it is lost then the worst what will happen is the browser failing the request due to the redirect loop - as Quarkus will be challenging; and all will work fine during the initial authentication, and we will be able to drop the check assuming that if `code` is present then it must be a redirect...
CC @pedroigor

**Comment by haraldatbmw** [comment]
@sberyozkin That sounds complicated. I was wondering why the `code` and `state` query-parameter are not only relevant for my configured static redirect-path: `quarkus.oidc.authentication.redirect-path=/api/oidc/callback`.

**Comment by sberyozkin** [comment]
@haraldatbmw I agree it sounds complicated but from the user perspective it will be an extra single property only in the configuration :-). I have a test working now.

`code` (and `state`) are special query parameters in the code flow, they are set by IDP on redirecting the user back to Quarkus.
The problem you are facing is not happening when the user is redirected back, but on the the initial request - where given the presence of `code` we assume it is in fact a redirect from IDP.  The only differentiator is that during the initial request no `state` cookie is available (Introducing cookies like `code_flow_in_progress` would just duplicate the `state` cookie). So we need to decide what to do if the state cookie is missing - by default, given the presence of `code` (with the assumption being it is the redirect from IDP) we fail the authentication - which in your case proves a problem since it is the very first request. Therefore we need a user permission to challenge for the re-authentication if the state cookie is missing.

**Comment by sberyozkin** [comment]
@haraldatbmw I've opened a PR but in  meantime you may also want to consider the  browser frontend always starting from some specific authentication path, such as `/login`, etc, once the login is done, and the session is established, the custom `code` and `state` parameters will be accepted without any problems.

**Comment by haraldatbmw** [comment]
@sberyozkin In my current project all OIDC endpoints are static. My frontend calls `/api/oidc/login` to start the flow. My redirect url is always `/api/oidc/callback`. My fontend calls `/api/oidc/logout` for logging-out. And I configured a post-logout endpoint for `/api/oidc/post-logout` which redirects to the start-page. So in my case the `code` and `state` query-parameters of the OIDC flow are relevant only for the URL `/api/oidc/callback`.

Because I set the property `quarkus.oidc.authentication.xhr-auto-redirect=false` calls to my other protected entpoints do not cause the redirection to the IDP but returns 499http- status-code.

**Comment by sberyozkin** [comment]
@haraldatbmw OK, so in this issue description you mention ` /hello?code=abc.` At what point this call is executed ?

**Comment by haraldatbmw** [comment]
@sberyozkin This is a protected endpoint of my application which uses the query-parameter code because our business-entity attribute is named code (has nothing to do with OIDC code). It is called after the login. So the user is already authenticated. But if called without authentication before it should return 499.

**Comment by sberyozkin** [comment]
@haraldatbmw If it is a protected endpoint, then the `code` must not be interfering after the authentication. It can only interfere after the authentication if the session cookie is not detected so if you rename it to `id` and it all starts working then my best guess is that the user is auto-redirected to IDP, and silently re-authenticated, and it may be happening on every request.
Can you please check [here](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/CodeAuthenticationMechanism.java#L92) what happens after the authentication has been completed and you attempt to access a protected resource ? If the session cookie is detected then no custom `code` parameter will interfere
thanks

**Comment by haraldatbmw** [comment]
@sberyozkin Just look at my reproducer project and there the unit-test. The conflict is only at accessing the endpoint without any authentication before. It results 401 instead of 499.

**Comment by sberyozkin** [comment]
@haraldatbmw Oh I see, it is quite confusing, the description says the wrong code is returned, but what you expect is 499 on the very 1st request or perhaps, when the session has expired in which case the flow starts again. It does not matter what is expected, 401 or 499 then.

In this case the PR I provided is the reasonable workaround IMHO.

**Comment by haraldatbmw** [comment]
@sberyozkin Sorry for confusion!

**Comment by sberyozkin** [comment]
@haraldatbmw No problems :-), the PR should not only allow the custom code/state on the first or re-auth requests, but also let users select the way they want to handle the case where a state cookie is missing, so it is not in vain :-), and I'd definitely would not consider tat enhancement without you opening this issue :-)

**Comment by sberyozkin** [comment]
@haraldatbmw sorry, have to close this issue - in some cases we just can't avoid the ambiguity with the code query parameter, we've had a long discussion with @pedroigor about it.
