### ISSUE TITLE
Infinispan version is null

### ISSUE THREAD

**Issue by karesti** [quarkusio/quarkus#1322]
Infinispan version is displayed as null 
2019-03-07 17:14:12,787 INFO  [org.inf.cli.hot.RemoteCacheManager] (main) ISPN004021: Infinispan version: null

**Comment by wburns** [comment]
This has to be fixed in Infinisipan directly. The issue is that we are invoking at runtime `RemoteCacheManager.class.getPackage().getImplementationVersion()` and this is always null in native mode. The Infinispan code should be changed to use `Version.printVersion()` method instead as this uses a staticly defined instance that is written at build time.

**Comment by karesti** [comment]
@wburns is there a jira related ?

**Comment by wburns** [comment]
https://issues.jboss.org/browse/ISPN-10488

**Comment by wburns** [comment]
This is fixed in ISPN 10.0.0 Final with https://issues.jboss.org/browse/ISPN-10488
