### ISSUE TITLE
The configuration file is allowed to be overwritten, but the written file is not allowed to have attributes that are not available under the original resources

### ISSUE THREAD

**Issue by a943915349** [quarkusio/quarkus#13354]
After quarkus packaging, the configuration file is allowed to be overwritten, but the written file is not allowed to have attributes that are not available under the original resources, such as multiple Hibernate-ORm. If only one hibernate-ORm was configured in the original, and several Hibernate-orm were added in the configuration file after finishing the package, an error will be reported...

**Comment by Sanne** [comment]
Hi, this is by design. In Quarkus there's a distinction between "build time" and "runtime" configuration properties.

The "runtime" configuration properties can be changed after having built it (or "packaged", like you say). But only those.

All other configuration properties have deeply structural implications in actually how the application is packaged; please refer to this table:
 - https://quarkus.io/guides/all-config

You'll see the "build time" configurations have a lock icon. Those can not be changed after having built the application: our recommendation is to setup your build pipeline to create a new package whenever you need to make such changes.

Some configuration are allowed at runtime; for example the database name, credentials, and similar.. as these are typically going to be needed to be injected as variables.
