### ISSUE TITLE
Extend gRPC @Blocking support

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#13358]
**Description**

Initially, the `@Blocking` annotation was limited to methods.
With the extension to classes, we need to update the extension to handle this case.

**Comment by Sgitario** [comment]
About this issue, I'm annotating my gRPC method with `Blocking`, see example:

```java
@Singleton
public class HelloService extends GreeterGrpc.GreeterImplBase {

    @Override
    @Blocking
    public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
        // ....
        service.doSomething(); -> This method internally uses UniBlockingAwait.await
    }
}
```

The above code fails with this exception:

```
io.grpc.StatusRuntimeException: UNKNOWN: java.lang.IllegalStateException - The current thread cannot be blocked: vert.x-eventloop-thread-3
	at io.grpc.Status.asRuntimeException(Status.java:533)
	at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:478)
	at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:413)
``` 

The problem is that the Infrastructure.canCallerThreadBeBlocked() call returns false.

Am I doing something wrong or is this a defect? If so, it should be tracked separately?
Thanks in advance,

**Comment by cescoffier** [comment]
@Sgitario do you have a reproducer?

**Comment by Sgitario** [comment]
> @Sgitario do you have a reproducer?

Hello @cescoffier , I've created a small reproducer. See [this test](https://github.com/Sgitario/beefy-scenarios/blob/baa02201b1b327c0ee9262544e945d34c23d1f31/009-quarkus-infinispan-grpc-kafka/src/test/java/io/quarkus/qe/greeting/GreetingServiceTest.java#L18).

How to reproduce?
- git clone https://github.com/Sgitario/beefy-scenarios
- cd 009-quarkus-infinispan-grpc-kafka
- mvn clean test -Dtest=GreetingServiceTest#testBlockingGreetingResource

The problem is when using a bean annotated with `@RequestScoped`, for example:

```java
@RequestScoped
public class SomeService {
    public String checkBlocking() {
        return "Can be blocked? " + BlockingOperationControl.isBlockingAllowed();
    }
}
```

For injecting this service in our gRPC service, we need to use the `@ActivateRequestContext` annotation:

```java
@Singleton
public class BlockingHelloService extends GreeterGrpc.GreeterImplBase {

    @Inject
    SomeService service;

    @ActivateRequestContext
    @Blocking
    @Override
    public void sayHello(HelloRequest request, StreamObserver<HelloReply> responseObserver) {
        responseObserver.onNext(HelloReply.newBuilder().setMessage(service.checkBlocking()).build());
        responseObserver.onCompleted();
    }
}
```
If you run the test, it will return that the thread can't be blocked. The expected result is that it should be able to be blocked because I'm annotating the method with `@Blocking`. 

It seems that there must be an incompatibility between the `@Blocking` and `@ActivateRequestContext` annotations. If I don't use the annotation `@ActivateRequestContext`, it returns that can be blocked as expected.

**Comment by cescoffier** [comment]
Oh, yes! I'm working on activating the request context automatically. I need to restart working on this.

**Comment by cescoffier** [comment]
This has been fixed.
