### ISSUE TITLE
Workaround graal#3003 by passing IncludeResources via AutomaticFeature instead of command line argument

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#13472]
https://github.com/oracle/graal/issues/3003 makes our ResourcesITCase fail on GraalVM 20.3.0
A workaround is possible to pass the IncludeResources via AutomaticFeature instead of command line argument. 
The workaround would unblock the upgrade to GraalVM 20.3.0.

A PR follows.

**Comment by gradinac** [comment]
Hey @ppalaga! Thank you very much for this contribution!
After looking at the new and previous changes, @olpaw and I had a discussion on how to best move forward on this. In order to reduce the complexity of this part of native-image, we've decided on taking a completely different approach to argument passing from the native-image driver to the builder JVM.
The new approach has been integrated in: https://github.com/oracle/graal/commit/e54f5cfb0dcc21c777bafec9bcba02be2208afd5
In the new system, we pass the JVM arguments through the command line, while passing the native-image arguments through a custom file. This greatly reduces the complexity of this part of Native Image, while also working for Java 8.
Sorry for putting you through the trouble of writing this PR! However, it has been very useful in helping us decide how to tackle this.
Please let me know if the new changes work for you, if you hit any errors or if you have any concerns/questions about the new implementation.

**Comment by zipper01** [comment]
@ppalaga can you kindly elaborate how to do it? In my case, I put a private key file in the resource folder and use `Thread.currentThread().getContextClassLoader().getResourceAsStream(keyPath)` to read it. This is OK in when running `java -jar`; but in the generated native image it returns null. I tried both `-H:IncludeResources=".*/ssl/.*$"` and `-H:ResourceConfigurationFiles=/path/to/resource-config.json` following the [reference manual](https://www.graalvm.org/22.1/reference-manual/native-image/Resources/), non of them worked.
