### ISSUE TITLE
LazyInitializationException accessing Many-To-Many even when using @Transactional and modified child collection not updated after reloading

### ISSUE THREAD

**Issue by mklueh** [quarkusio/quarkus#13604]
**Scenario**

The scenario of my [reproducer](https://github.com/mklueh/quarkus-panache-repository-returns-old-entity-state) project is having a simple user entity who can follow others or be followed by others.

In my QuarkusTest I´m loading some entities from a PanacheRepository in the @BeforeEach.

Each tests performs operations on the child entity collections, such as following and unfollowing users. 

**Issues**

**1. My core issue: **Modified Child Collection not up-to-date after being modified and reloaded from PanacheRepository****

```

    @Test
    @Transactional // does not matter
    void testRemoveFollowingWithReloadBeforeAccessingCollection() {
        userService.follow(userA.id, userB.id);

        userA = userRepository.findById(userA.id);

        assertEquals(1, userA.getFollowing().size());
        assertEquals(1, userService.getFollowingCount(userA.id));

        userService.unfollow(userA.id, userB.id, true);

        /*
         * Reloading the user after changes made
         */
        userA = userRepository.findById(1L);

        /*
         * This call performs a native select and succeeds - the database has been updated
         */
        assertEquals(0, userService.getFollowingCount(userA.id)); // succeeds

        /*
         * This call fails - the Panache Repository has not loaded the changes made to the database
         */
        assertEquals(0, userA.getFollowing().size());
    }

```

I´m performing follow and an unfollow operation. The follow operation creates the reference successfully, but the unfollow does partially. The entry get´s removed from the database but if I reload the entity from the PanacheRepository, it still has the entity reference.

**Am I doing something wrong here or is this a bug?**

**2. LazyInitializationException**

This occurs (I think) because the entities are loaded in the setup method of the test in a transaction and used in some tests - outside of the original transaction. However annotating the test methods with **Transactional** does not help, nor do a few other things I´ve found accross the internet, such as:

2.1 Using Hibernate.initialize
```
    /**
     * LazyInitializationException
     */
    @Test
    @Transactional
    void testNoFollowersExistByCollectionHibernateInitialize() {
        Hibernate.initialize(userA.getFollowers());
        assertEquals(0, userA.getFollowing().size()); //fails
    }
```

2.2 Refreshing the entity

```
    
   /**
    * Entity not managed
    */
   @Test
    Transactional
    void testNoFollowersExistWithSession() {
        entityManager.unwrap(Session.class).refresh(userA);
        assertEquals(0, userA.getFollowing().size()); //fails
    }
```

And a few others.

**What am I doing wrong here?**

**3. The Transactional annotation must be on the teadDown, not on the cleanFollowerTable**

As I´m using TestContainers with PostgreSQL and not H2 I need to clean up all my inserts before and after I run my tests. Therefore I´ve created a **cleanFollowerTable** method. Annotating this method with Transactional and calling it from my setUp and tearDown method won´t work. Instead I need to annotate both methods with **Transactional** and not the **cleanFollowerTable** itself. **Why is that the case**?

```

    @BeforeEach
    @Transactional
    void setUp() {
        cleanFollowerTable();
        userA = userRepository.findById(1L);
        userB = userRepository.findById(2L);
    }

    @AfterEach
    @Transactional
    void tearDown() {
        cleanFollowerTable();
    }

    //@Transactional no effect
    @SuppressWarnings("SqlWithoutWhere")
    private void cleanFollowerTable() {
        entityManager
                .createNativeQuery("delete from followers")
                .executeUpdate();
    }
```

**To Reproduce**

https://github.com/mklueh/quarkus-panache-repository-returns-old-entity-state

I´m again totally stuck and I´m not sure if this issues are bugs or if I´m misunderstanding Hibernate. I´d appreaciate any help.

**Comment by Sanne** [comment]
Hi,
it's a bit late here, but let me try clarify some things; if there's still something wrong I should have a better look tomorrow.

2#

## _Hibernate.initialize_

You can only use this helper when the object is managed by a Session which is still open. We can't otherwise load its state, as the transaction to which this object relates to is already terminated - the object might no longer exist, or having been mutated in such a way that it is no longer possible to reconcile its state with the in-memory state you have in your entities.

It helps to consider that the whole lifecycle of your business operations "using" the entity should start - and finish - within the same Transaction.

## testNoFollowersExistWithSession

For the same reasons as in the previous point, the detached entity should be discarded. Don't use its state to try to continue a conversation with the database - this is only possible via the "merge" operation, which has specific semantics..

## merge

Your code does:

        entityManager.merge(userA);
        entityManager.unwrap(Session.class).refresh(userA);

but one of the specific aspects to be careful about the "merge" operation, is that you should use the object **it returns** .
This is because we might be unable to "fix" its state, so you need to reassign it:


        userA = entityManager.merge(userA);
        entityManager.unwrap(Session.class).refresh(userA);

# Transactional annotation

We can't properly intercept a method which is being invoked by the same class.

HTH

**Comment by mklueh** [comment]
> Hi,
> it's a bit late here, but let me try clarify some things; if there's still something wrong I should have a better look tomorrow.
> 
> 2#
> 
> ## _Hibernate.initialize_
> You can only use this helper when the object is managed by a Session which is still open. We can't otherwise load its state, as the transaction to which this object relates to is already terminated - the object might no longer exist, or having been mutated in such a way that it is no longer possible to reconcile its state with the in-memory state you have in your entities.
> 

Thanks for the explanation. If the session is still open, why do I need this call then and can´t just access the collection like **user.getFollowers()**?


> It helps to consider that the whole lifecycle of your business operations "using" the entity should start - and finish - within the same Transaction.


Great thing to know. That means in case of having a queue in your application where entities are processed asynchronously by a scheduler for example, involving multiple database operations in each stage of the process, you would just reload the whole entity in a new transaction by it´s ID? 


> 
> ## testNoFollowersExistWithSession
> For the same reasons as in the previous point, the detached entity should be discarded. Don't use its state to try to continue a conversation with the database - this is only possible via the "merge" operation, which has specific semantics..
> 
> ## merge
> Your code does:
> 
> ```
>     entityManager.merge(userA);
>     entityManager.unwrap(Session.class).refresh(userA);
> ```
> 
> but one of the specific aspects to be careful about the "merge" operation, is that you should use the object **it returns** .
> This is because we might be unable to "fix" its state, so you need to reassign it:

Also good to know :) so I was at least close to something that might have worked.

> 
> ```
>     userA = entityManager.merge(userA);
>     entityManager.unwrap(Session.class).refresh(userA);
> ```
> 
> # Transactional annotation
> We can't properly intercept a method which is being invoked by the same class.
> 
> HTH

Got it, I think I know something similar from the Spring `@Cacheable` annotation. Would be nice to have some telling log output to make it clear.

Thanks for your advice, it was really helpful and 2/3 of my questions are resolved.

**Comment by Sanne** [comment]
> Thanks for the explanation. If the session is still open, why do I need this call then and can´t just access the collection like user.getFollowers()?

you're right, if the Session is still open that would be good enough. In fact, I rarely ever need Hibernate#initialize : I'm not suggesting to use it.

> Great thing to know. That means in case of having a queue in your application where entities are processed asynchronously by a scheduler for example, involving multiple database operations in each stage of the process, you would just reload the whole entity in a new transaction by it´s ID?

Probably. It depends if you need the data to be "fresh" as in just loaded? Especially if you then need to write it back,you might want to open the transaction, load the data, make changes, commit.  If you don't need to make such changes, you might want to copy the data when it was loaded out of managed objects - or ensure all lazy loading already happened - so to not need to reload anything at all.

> Got it, I think I know something similar from the Spring @Cacheable annotation. Would be nice to have some telling log output to make it clear.

Yes I wish we could do something about it. But since we can't intercept, it's also hard to spot the problem :)
Maybe some bytecode analysis magic could do it - I'll think about it. @stuartwdouglas maybe?

**Comment by gavinking** [comment]
Well if we're already processing bytecode at build time, it would be rather easy to make `@Transactional` work for self-invocations. Except that it's specifically defined to _not_ work that way. So I'm not quite sure how I feel about that.

**Comment by yrodiere** [comment]
Hey @mklueh , is this still a problem?

> Transactional annotation
> 
> We can't properly intercept a method which is being invoked by the same class.

I was surprised by this assertion, so I tested it: https://github.com/yrodiere/quarkus-playground/tree/i13604-transactional-self-interception

Turns out we can, and we do interecept method calls on `this`, *but* only for public methods; private methods are not intercepted for some reason. Probably because we don't go through the hassle of modifying the bytecode of the declaring class to make that method protected, so that it can be intercepted by the proxy subclass.

If you put an intercepting annotation on a private method, you will get a warning in logs, though. Obviously, like all warnings, it's pointless and nobody will see it. In order to get a proper exception, you have to set [`quarkus.arc.fail-on-intercepted-private-method`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.fail-on-intercepted-private-method) to `true`. Looks like a prime candidate for switching to stricter defaults, where we would fail by default... I think @gavinking will agree?

**Comment by yrodiere** [comment]
@mklueh Thanks. Then I believe Sanne explained everything, and there is no problem to work on, so I'll close this issue.

I created a thread on the quarkus-dev mailing list to discuss the way forward regarding interceptors on private methods, though: https://groups.google.com/g/quarkus-dev/c/ukQEujtlRbs

**Comment by yrodiere** [comment]
See also #30438
