### ISSUE TITLE
RESTEasy Reactive: investigate JSON streaming

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#13663]
There are several existing competing mime types / RFCs for streaming JSON in requests/responses.

We should investigate them and possibly support one or more.

**Comment by FroMage** [comment]
@gytis this is what @geoand talked to you about.

**Comment by FroMage** [comment]
Note that for the "response streaming" part this may depend on #13661

**Comment by gytis** [comment]
Great! I'm happy to take this one. Feel free to assign me.

**Comment by FroMage** [comment]
Great!

**Comment by FroMage** [comment]
Apparently Kubernetes API server (https://kubernetes.io/docs/reference/command-line-tools-reference/kube-apiserver/) uses `application/json;stream=watch` and streams.

**Comment by geoand** [comment]
WTF if that `stream=watch` thing :)

**Comment by FroMage** [comment]
One option is http://ndjson.org/

**Comment by ntrp** [comment]
Just to add ndjson is the default streaming method of Spring WebFlux Multi responses

**Comment by ntrp** [comment]
I could start implementing a solution to support Ndjson on JaxRS endpoints if anybody can point me in the right direction. I have seen the SSE provider in JaxRS core but I think this one can be much simpler. I am still missing all the links to understand fully what is necessary to make it happen. Did a quick and dirty 10 min PoC with a custom provider but the provider receives a list of objects instead of receiving single Multi emits of course.

**Comment by geoand** [comment]
Currently the JSON handling for SEE can be found in https://github.com/quarkusio/quarkus/blob/main/independent-projects/resteasy-reactive/server/runtime/src/main/java/org/jboss/resteasy/reactive/server/handlers/PublisherResponseHandler.java

**Comment by ntrp** [comment]
Ah cool, I did not find that one yet hehe. That's a really good entry point, thanks!
