### ISSUE TITLE
Allow cross origin requests on health endpoints

### ISSUE THREAD

**Issue by sc3n** [quarkusio/quarkus#13935]
**Description**
Cross origin requests on a health endpoint such as `/health/ready` fail as the response does not contain the required CORS headers.

This is the error message from console in chrome: `Access to XMLHttpRequest at 'https://...' from origin 'https://...' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

This was supported in thorntail. See https://github.com/thorntail/thorntail/pull/745

**Implementation ideas**
Add required CORS headers by default or introduce a new configuration property which, when true, allows cross origin requests on health endpoints.

**Comment by jmartisk** [comment]
Hey @sc3n , it turns out that there is a general CORS filter in Quarkus that can be used for this.
It can be applied by adding a few config properties, most importantly `quarkus.http.cors=true`. See https://quarkus.io/guides/all-config for more info, search the page for "quarkus.http.cors" and its subproperties
I think this should cover your use case. If not, feel free to reopen and we can discuss it further.
