### ISSUE TITLE
Use MariaDB4j for MariaDB integration tests

### ISSUE THREAD

**Issue by vorburger** [quarkusio/quarkus#1431]
@Sanne I by chance noticed your work in #1427 #535 #264 and was wondering if would be interested in using (my) https://github.com/vorburger/MariaDB4j project to run MariaDB integration tests for this project? Just an idea, go for it if any interest (and shout if any Qs / support required re. MariaDB4j, happy to help); close if for any reason this would not add any value.

**Comment by Sanne** [comment]
Hi @vorburger thanks for the link, that project looks awesome.. I wish I had known it earlier :)

But I am a bit skeptical about not using docker for this; I've had experience using a similar solution for MongoDB in the past and we often had platform specific issues wasting our time. At least docker gives us strict consistency - assuming people installed Docker.

Generally speaking I'm not happy that working on a project requires to have Docker installed first, but since that's unavoidable and we need it for many other modules (and databases) I guess we need to minimise the diversity across tools.

Not sure if others agree? Happy to keep this open a bit more as I'm torn, it certainly looks tempting.

Great tool though, I'll certainly use it on other projects.

**Comment by ctomc** [comment]
On similar note there are is also embedded postgres that works great for testing.

In my book anything that prevents docker requirement for simple scenarios is a good thing.

**Comment by vorburger** [comment]
> At least docker gives us strict consistency - assuming people installed Docker. but since that's unavoidable and we need it for many other modules (and databases) I guess we need to minimise the diversity across tools.

I'm strategically / architecturally actually 101% aligned with this... MariaDB4j is "old" and from back in the pre-container (say "container" not "docker" :smiling_imp: ) era. Just mentioned this as an option in case it would be of interest help to avoid having to have DB containers for easy local builds and in CI; absolutely no offense at all taken if you close this issue.

**Comment by Sanne** [comment]
Ok let's close this. Thanks for the pointers though!

Hi @ctomc ! Glad to see you around too :+1:
