### ISSUE TITLE
Incorrect behaviour for @ApplicationScoped lifecycle events

### ISSUE THREAD

**Issue by jpechane** [quarkusio/quarkus#1433]
To `application-lifecycle-events/src/main/java/org/acme/events/AppLifecycleBean.java` add methods
```
    public void init (@Observes @Initialized(ApplicationScoped.class) Object init) {
        LOGGER.info("Init");
    }

    public void shutdown(@Observes @Destroyed(ApplicationScoped.class) Object init) {
        LOGGER.info("Shutdown");
    }
```

The result of quickstart is
```
2019-03-12 15:31:42,224 INFO  [ListenerBean] (main) Shutdown
2019-03-12 15:31:42,224 INFO  [ListenerBean] (main) Init
2019-03-12 15:31:42,368 INFO  [ListenerBean] (main) Shutdown
2019-03-12 15:31:42,368 INFO  [ListenerBean] (main) Init
2019-03-12 15:31:42,369 INFO  [ListenerBean] (main) The application is starting...hello
```
Please note that both shutdown and init methods were called multiple times and shutdown was call even before the application was started.

**Comment by mkouba** [comment]
Hi @jpechane and thanks for the report! The problem was that `javax.enterprise.context.Initialized` and `javax.enterprise.context.Destroyed` qualifiers were not part of the application index and thus ArC didn't know about these qualifiers. As a result, both the observer methods are registered without any qualifier and therefore are notified for any event whose event type was assignable to the observed event type (`java.lang.Object` in our case) -> i.e. for `StartupEvent` and `@Initialized(ApplicationScoped.class)`.

I'll send a PR with a fix in a moment.

BTW I would not recommend to use `@Observes @Initialized(ApplicationScoped.class)` in Quarkus because it's always fired during `STATIC_INIT` phase which means that it's fired during native image generation (if the target runtime is Substrate VM).

Also it's not a good idea to declare a `@Destroyed(ApplicationScoped.class)` observer on an application scoped bean as this event should be fired after the app context is destroyed. I'd recommend to use `@BeforeDestroyed(ApplicationScoped.class)` instead.
