### ISSUE TITLE
mp-metrics: Try to initialize as many application metrics as possible at build

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#1435]
Currently the registration logic for application metrics is delegated to SmallRye Metrics, which means it is lazy (all annotated metrics in a bean are initialized when the bean is first constructed). Some metrics (the ones from annotations) could potentially be initialized at build though.

One problem with this is that scanning and registering the annotated metrics in Quarkus will mean a lot of logic duplication from SmallRye, and that will be fragile with respect to potential changes in future versions of SmallRye. 

Another problem is that currently the annotation scanning is performed on a Jandex index rather than as a CDI extension, so I'm not sure how to properly constuct metric's origins (that is instances of `AnnotatedElement` or `InjectionPoint` where the metric is declared) to be stored with the metadata to be able to correctly enforce (non)reusability.

**Comment by jmartisk** [comment]
I'm currently working on getting this fixed on the SmallRye Metrics side, targeting its 2.0 release. It will be cleaner than doing this in Quarkus.

**Comment by jmartisk** [comment]
So an update to the previous comment, this will be done by reading the Jandex index during STATIC_INIT and eagerly initializing annotated metrics that are found in it. It will require some enhancements for SmallRye Metrics so that it will be possible to initialize Metrics using Jandex data (currently SR-M only allows this from `java.lang.reflect` and CDI constructs, which we can't obtain in Quarkus' STATIC_INIT). I have a working prototype implementation for SR-M 2.0 and Quarkus upgraded to SR-M 2.0-SNAPSHOT. If it is deemed necessary, it could probably be backported to SR-M 1.1.x, but I would prefer doing this together with upgrading Metrics in Quarkus to SR-M 2.0 after it gets released (which should be a matter of a few weeks, I hope).

**Comment by mkouba** [comment]
@jmartisk In fact, we can obtain `java.lang.reflect` constructs in STATIC_INIT and we already do this for example in SmallRye Reactive Messaging integration. See also the [processor](https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-reactive-messaging/deployment/src/main/java/io/quarkus/smallrye/reactivemessaging/deployment/SmallRyeReactiveMessagingProcessor.java#L104-L128) and the [template](https://github.com/quarkusio/quarkus/blob/master/extensions/smallrye-reactive-messaging/runtime/src/main/java/io/quarkus/smallrye/reactivemessaging/runtime/SmallRyeReactiveMessagingTemplate.java#L18-L33). But it would be reasonable to add some abstraction so that it would be possible to replace the reflection completely and use Jandex instead.
