### ISSUE TITLE
WebFilter for routing unknown routes to frontend does not work when running *-runner.jar

### ISSUE THREAD

**Issue by almyy** [quarkusio/quarkus#14426]
**Describe the bug**
I have a quarkus app serving a create-react-app with client side routing (react-router-dom) built for production. To make sure the client side routes are redirected to the frontend, I have created a `@WebFilter` as described [here](https://quarkus.io/blog/quarkus-and-web-ui-development-mode/). Running with `./gradlew quarkusDev` serves the react-app on localhost:8080, and accessing e.g. localhost:8080/about also works.

However, when building with `./gradlew build` and running the app with `java -jar build/*-runner.jar`, only root (localhost:8080/) serves the frontend, while any subroute (e.g. localhost:8080/about) returns a 404 Not Found.

I might be doing something wrong here, but I don't understand how, so I assume this is a bug.

**Expected behavior**
I expect the `@WebFilter` to work, i.e. reroute unknown routes to the frontend, both when running the app with `./gradlew quarkusDev` and when building (`./gradlew build`) and running the built .jar (`java -jar build/*-runner.jar`).

**Actual behavior**
When building with `./gradlew build` and running the app with `java -jar build/*-runner.jar`, only root (localhost:8080/) serves the frontend, while any subroute (e.g. localhost:8080/about) returns a 404 Not Found.

**To Reproduce**

Link to repro: https://github.com/almyy/quarkus-react-repro

I used gradle, as that is what I know and that's what I'm using in my app.

1. Run `./gradlew quarkusDev`
2. Access localhost:8080/ and see the frontend. (it works)
3. Access localhost:8080/about and see the frontend. (it works)
4. Stop the server
5. Run `./gradlew build`
6. Run `java -jar build/*-runner.jar`
7. Access localhost:8080/ and see the frontend. (it works)
8. Access localhost:8080/about and see that you get a 404. This is what is not working

**Environment (please complete the following information):**
 - `uname -a`: Linux martin-manjaro 5.9.16-1-MANJARO #1 SMP PREEMPT Mon Dec 21 22:00:46 UTC 2020 x86_64 GNU/Linux
 - `java -version`: 
   openjdk version "1.8.0_265"
   OpenJDK Runtime Environment (build 1.8.0_265-b01)
   OpenJDK 64-Bit Server VM (build 25.265-b01, mixed mode)
 - GraalVM version: n/a
 - Quarkus version or git rev: 1.10.3.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): gradle version 6.7

**Comment by stuartwdouglas** [comment]
Because the original request had called sendError() when the request returns to the container the container attempts to do an error dispatch (sendError does not actually send the error immediatly, it just queues it to be sent, which sounds odd but it matches the behaviour of other containers). Because the dev mode error handling is different to prod mode this happens to work in dev mode but fails in prod. The simple fix is to just call response.getOutputStream().close() after the forward call. 

I don't know if I want to change the current behaviour, from what I remember this behaviour is the way it is because the TCK and various other things expect it to work that way, and this seems a bit of a corner case.
