### ISSUE TITLE
QuarkusSecurityIdentity#checkPermission returns wrong results

### ISSUE THREAD

**Issue by albert0815** [quarkusio/quarkus#14472]
**Describe the bug**
I am working on an application which is using the keycloak policy enforcement. Beside enforcing permissions based on resource URIs with scope based permissions (using http-method-as-scope). When implementing additional permission checks programmatically with different scopes the checkPermission method of the security identify returns wrong results. It seems that the authorization context contains only the scopes of the http method even though there might be more scopes defined on the resource.

**Expected behavior**
checkPermission method should actually check the permission of the user, not only the ones which have been retrieved earlier.

**Actual behavior**
checkPermission returns false even though the user actually has the permission.

**To Reproduce**

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific): https://github.com/albert0815/keycloak-authorization-reproducer

1. clone repo
2. run mvn clean verify

The test case will fail but should be fine. The reproducer contains one resource which the user needs an authorization for the GET operation (based on the keycloak realm settings). On that resource there are two scopes defined (GET and TEST). The quarkus keycloak authorization enforcer takes care of enforcing the GET scope. In the resource there is a check of the TEST scope using the checkPermission method. The checkPermission reports the user is not authorized for that scope which is not true. The same issue happens if one checks for a different permission (something like checkPermission(new AuthPermission("resource2")).

**Configuration**
```properties
# Add your application.properties here, if applicable.
quarkus.keycloak.policy-enforcer.enable=true
quarkus.keycloak.policy-enforcer.http-method-as-scope=true
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [Version 10.0.17763.1577]
 - Output of `java -version`: openjdk version "11" 2018-09-25
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.11.0.Final
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)

**Comment by sberyozkin** [comment]
Hi Pedro, @pedroigor, let me assign this one to you :-)

**Comment by pedroigor** [comment]
@albert0815 What is the Keycloak version you are using? It seems related to https://github.com/quarkusio/quarkus/issues/9057.

**Comment by albert0815** [comment]
We are using 11.0.3 (please take a look at the reproducer if possible).

**Comment by pedroigor** [comment]
@albert0815 Currently, we don't do any call to the server when invoking `checkPermissions` but just iterate over the permissions previously granted.

The policy enforcer basically works in two modes, depending on the bearer token you are using. If the token already holds the permissions (if the client obtained a token before like this https://www.keycloak.org/docs/latest/authorization_services/#_service_obtaining_permissions) the policy enforcer won't make a call to Keycloak but use whatever permission is in the token. However, if the token is a regular access token (no permission on it) then it will call Keycloak to exchange the token with another one with the permissions.

The use case here is related to the second case, and when the exchange happens, the policy enforcer only asks for the scopes you defined for the path you are protecting. In this case, only `GET` (due to the `http-method-as-scope` property), but never all the scopes associated with the resource. Hence the cause why your `checkPermissions` call always returns false.

If you want to get all scopes associated with the resource, you can try removing the `http-method-as-scope` property.

Maybe we could support a hybrid approach, where you can still have the `http-method-as-scope` defined while configuring the enforcer to also query all scopes for the resources.

**Comment by albert0815** [comment]
Hi Pedro,

Thanks for checking this and your explanation. Somehow I don't exactly understand though, why you state this is not a bug. At least I can't find any documentation about the mentioned behaviour. Actually the guide "USING OPENID CONNECT AND KEYCLOAK TO CENTRALIZE AUTHORIZATION" mentions that it is possible to check user authorization using the checkPermission method. And its API documentation mentions that it checks the permission of the user. So for me this still feels like a bug, as the checkPermission does not actually check the permission of the user but does something different.

I understand that it is related to the use of http-method-as-scope property and that it might behave different when not using it. I'll try to explain my use case and how we planned to use this: The authorization of the user is initially checked using the http method (e.g. whether a user is allowed to create a specific entity). If the user is allowed to create entities, it still might depend on some specific settings within the application what exactly the user of the servive may do, which I wanted to check using programmatic security. But differentation between GET and POST requests using http-method-as-scope allows for differentiation of read and write access rights pretty easily. If I now need to deactive the http-method-as-scope as I am not able to use programmatic security then a lot of additional configuration or implementation is needed to achieve the same result.

I checked setting http-method-as-scope to false - I can see that the checkPermission method is then able to evaluate permissions for different scopes for the same resource. Still if I try to evaluate multiple resources it fails for all but the first call. I think this is not easy to understand as well.

So regardless whether this is a bug or an enhancement. Would you be planning for implementing something like the hybrid approach? Or maybe you can suggest a different workaround?


Thanks

**Comment by pedroigor** [comment]
Hi @albert0815, it is not clear in docs and the only reason I changed to an RFE is that, by design, permissions are calculated based on the permissions associated with a particular request. If they were fetched as a result of a token exchange (when you send a regular access token with no permissions) or as a result of looking at the permissions within the token (it might not need to do any exchange at all), that method will never invoke the server for additional permissions.

We can do that very easily though, and I think your use case justifies the change.

By default, we would keep the same behavior, and we could have an additional method to indicate that in case of a "permission miss", the code should try to fetch the permissions from the server.

**Comment by pedroigor** [comment]
Actually, we would need a specific type of permission type, maybe using a `FeatchablePermission` (or a better name), that indicated this intention. Change `SecurityIdentity` is not really an option, IMO.

**Comment by albert0815** [comment]
I would be happy with that approach!

**Comment by albert0815** [comment]
Hi Pedro! Just one question: Is it possible to somehow issue a refresh of the token so that the policy enforcer will retrieve the permissions from Keycloak? It would be helpful to somehow implement a workaround for now to continue.

**Comment by pedroigor** [comment]
@albert0815 Implementation-wise you just need to invoke the token endpoint to obtain permissions. See here https://www.keycloak.org/docs/latest/authorization_services/#_service_obtaining_permissions.

The access token you would use in the token request can be obtained from the security identity.

I'm not sure though how you would get the OIDC configuration so that you don't need to duplicate it in your code. Maybe, the @sberyozkin new OIDC Client can help?

**Comment by sberyozkin** [comment]
Hi @pedroigor Sorry, have missed it. Yes, it should help,
@albert0815 can you please try https://quarkus.io/guides/security-openid-connect-client ?

**Comment by michalvavrik** [comment]
closing as we never got answer. feel free to re-open if problem holds, thanks
