### ISSUE TITLE
Allow further configuration of Elasticsearch RestClient through custom HttpClientConfigCallback

### ISSUE THREAD

**Issue by eAybars** [quarkusio/quarkus#14754]
**Description**
Please consider providing more control over the configuration of the Elasticsearch RestClient with a user pluggable HttpClientConfigCallback implementation in the elasticsearch-rest-client extension. 

**Why**
Form my case, I need to set a SSLContext (as described [here](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/_encrypted_communication.html)) to enable me to use self signed certificates generated by Elasticsearch kubernetes operator with a native image build. Currently one needs to provide these certificates at native image build time which is kind of more difficult and hard to maintain and much less flexible. 

**Implementation ideas**
One way to achieve this is to have a no op (i.e. empty), @Singleton scope @DefaultBean implementing HttpClientConfigCallback and inject a HttpClientConfigCallback in the ElasticsearchRestClientProducer and pass it along with the ElasticsearchConfig parameter to the RestClientBuilderHelper. createRestClientBuilder method. ElasticsearchRestClientProducer.createRestClientBuilder method than can call this instance on top of its current configuration. Since DefaultBean implementation does nothing, this will change nothing for anyone. But if a user provides an implementation, overriding the noop default, they can have the opportunity to provide custom configuration.

**Comment by yrodiere** [comment]
Sounds like an important feature indeed. Would be useful in Hibernate Search too (though in the case of Hibernate Search, configuration APIs are missing).

Regarding the implementation, I'm a bit concerned about the future if we simply use the first bean we find in the CDI context that implements `HttpClientConfigCallback`. When we'll introduce support for multiple clients (#10905), it will be hard to support backward compatibility *and* allow users to apply a config callback to only one client, because the "legacy" behavior will be "if there's a bean, use it". 

So I'd be in favor of at least requiring some kind of qualifier on the config callback in order for it to be used in the REST client? Something like `@ElasticsearchClientConfig`, that could later evolve into `@ElasticsearchClientConfig("clientName")`?

**Comment by eAybars** [comment]
Hi Yoann, thanks for the quick response. I was not aware of the multiple client support issue so thank you for pointing that out as well, however your proposal seams to address it perfectly if you ask me. 

Additionally maybe you may do something like `@ElasticsearchClientConfig  Instance<HttpClientConfigCallback> configCallbacks` (or with `@ElasticsearchClientConfig("clientName")` ) and invoke all available configurators in a cascading manner if you do not want to rely on a single instance? But this might be a little bit over engineering of course

**Comment by eAybars** [comment]
So, how do we proceed with this, should I be creating a pull request conforming to your suggestion or what is the procedure to follow from this point? Thanks

**Comment by yrodiere** [comment]
> should I be creating a pull request conforming to your suggestion

That would be great, yes, thank you!


If you've never contributed to Quarkus, be sure to check out [this file](https://github.com/quarkusio/quarkus/blob/master/CONTRIBUTING.md).

I believe `io.quarkus.elasticsearch.restclient.lowlevel.runtime.ElasticsearchRestClientProducer#restClient` is where you should look at first. You can use `Arc.container().select(...).handles()` to get beans annotated with `ElasticsearchClientConfig`.

**Comment by yrodiere** [comment]
By the way, yes, your suggestion to allow multiple beans makes perfect sense.
