### ISSUE TITLE
[Mongo Panache Extension] Dynamically select database 

### ISSUE THREAD

**Issue by ch3rub1** [quarkusio/quarkus#14789]
**Description**
A few month ago, I've submitted an issue regarding the implemention of multitenancy within quarkus mongo panache extension (see https://github.com/quarkusio/quarkus/issues/5183).   
It seems that quarkus mongo panache extension now support some kinds of multitenancy implementations like [multiple mongo client](https://quarkus.io/guides/mongodb#multiple-mongodb-clients) or database selection through [@MongoEntity annotation](https://lordofthejars.github.io/quarkus-cheat-sheet/#_mongodb_panache).  
However, it seems not possible to implement multitenancy by using a database by tenant (on the same cluster).  
For example : 
* A service receive a request triggering some database operations.
* The targeted tenant name is contained by a HTTP header or a JWT claim.
* We need to select mongo database matching the tenant name.

I managed to implement this scenario only with mongo client extension by :
* Creating a request scopped producer which produce an injectable Tenant object, created from the RoutingContext.
* Creating a request scopped producer which produce an injectable MongoDatabase object, based on the injected Tenant object.
* Injecting the MongoDatabase object into a request scopped repository. The repository then use this injected database to perform operations to it.

Does this solution can be considered as "good" ? Or do you recommend another approach ?  

Is it possible, today, to have similar feature with mongo panache extension ? Or this require an evolution of it ?

**Implementation ideas**
I saw that some extensions, like oidc or hibernate, offer the possibility to implement a TenantResolver interface. Having such a possibility to configure the mongo client will likely allow to implement this kind of multitenancy.

**Comment by loicmathieu** [comment]
Yes, dynamic selection of MongoClient / MongoDatabase is not possible at the moment.

Having a way to resolve it dynamically, as you proposed with your `TenantResolver`, could be a good addition but it needs to be designed with care as it needs to interact gracefully with the existing features of MongoDB with Panache. We can inspire ourself with the way tenants works in Hibernate but I'm not even sure it is compatible with Hibernate with Panache.

**Comment by ch3rub1** [comment]
To facilitate the feature integration, we can also imagine a `MongoDatabaseResolver` instead of a `TenantResolver`.  
With this, developpers could simply provide an implementation of this interface to determine which database will be used by Mongo Panache. These mongo databases can be on the same cluster, on different clusters... developers have the liberty to implement any kind of multitenancy whitout introducing a tenant notion to Mongo Panache extension.   

It's just another implementation idea 😃

**Comment by m4k4veli** [comment]
> I managed to implement this scenario only with mongo client extension by :
> 
> * Creating a request scopped producer which produce an injectable Tenant object, created from the RoutingContext.
> * Creating a request scopped producer which produce an injectable MongoDatabase object, based on the injected Tenant object.
> * Injecting the MongoDatabase object into a request scopped repository. The repository then use this injected database to perform operations to it.

Hi, i was wondering if you could provide a code example on how to implement resolving mongodb database name based on tenant information. I'm currently working on a proof of concept, where having different db is mandatory for each tenant. I'm struggling implementing a solution. Therefore i would be very grateful if you could provide some more information.

**Comment by ch3rub1** [comment]
> I'm currently working on a proof of concept, where having different db is mandatory for each tenant using panache.

@m4k4veli I managed to implement this kind of multitenancy only with the mongodb client extension, not with panache.  
I'll be glad to provide you a code example but it it'll not help you if you absolutly want to use panache for your proof of concept.
Do you still want it ?

**Comment by ch3rub1** [comment]
@m4k4veli I written a sample quarkus app with mongo multitenancy implemented.  
You can find it [here](https://gitlab.com/ch3rub1/quarkus-mongo-mutitenant)

**Comment by NicolasChazeau** [comment]
Hi ! We encountered the same difficulties, is there any news on this issue ?
We need multi tenancy with 1 tenant <=> 1 database.
We removed Panache and used your repository for the moment @ch3rub1, thank you very much !

**Comment by pedroh-pereira** [comment]
I also have more ideas in mind.
Maybe could exists a way to insert a collection prefix dinamically, because some companies implement multi-tenancy in this way.
For example:
ClientA and ClientB. They will use the same database and the collections could be something like: ClientA.users and ClientB.users

Another approach that I wasn't able to reproduce is mongo client name dynamic selection, we need to pass a fixed database for each MongoEntity. So maybe a MongoClientNameResolver could be implemented too, maybe we can follow the same approach of the PR and on processor we can check if there is a MongoClientNameResolver implementation, all the application.properties connections configs should be added to be lazily produced

**Comment by evanchooly** [comment]
IMO, multitenancy should absolutely not be a concern for quarkus/panache.  These are ODM concerns and we (well, I ...) really don't want panache to slowly accrete ODM functions when there are functional ODMs out there already.

**Comment by pedroh-pereira** [comment]
@evanchooly I understand your point. So how about do we have at least the capability to dynamically select the database?
I think it’ll be sufficient for the most common cases as mine, for example me and my team are developing some POCs to replace the Spring and win all the amazing features and benefits from Quarkus, currently we are providing a multi-tenancy product, certainly we can provide it using the mongo client, but would be great to use Panache and have something in an out box way. Today, If I’m going to use Panache, I’ll need to create a new extension creating a layer over panache and provide BasePanacheMongoEntity and BasePanacheMongoRepository, because these classes are using a singleton final instance from mongo operations, so we can’t provide a custom MongoOperations implementation.
If the idea is not to bring features like this to panache itself, the possibility to providing a custom MongoOperations implementation may be would be enough.
I know it’s a different case compared to JPA that already have a hibernate supporting it behind the scenes, but maybe it can help many people as me.
What do you think about that?
Thanks for the answer!

**Comment by loicmathieu** [comment]
We want MongoDB with Panache to keep it simple, but if we can have some kind (not all kind) of multi-tenancy with low cost it's OK for me. Your proposed PR seems to be simple enhought.
But maybe the multi-tenancy should be at MongoDB client side directly (like multi-tenancy is done at Hibernate ORM side not Hibernate with Panache side) as it would also be usable for people using MongoDB without Panache.

@evanchooly I usually agree for advanced features to be for an ODM solution, but multi-tenancy IMHO is not such feature as it is a low level feature to select wich cluster/database/... to use dynamically. 
I think it should be supported, at least at the client and/or database side, at the collection side (like prefixing it) it seems more like an ODM feature.

**Comment by evanchooly** [comment]
The PR itself seems reasonably non-invasive though I do agree that it would probably be better to do at the mongo-client level instead.  However, we don't really deal with databases there but just the clients themselves so this is probably only really doable inside panache.  At a minimum it offloads any "unwanted" complexity to users' code.  I left some questions on the PR.

**Comment by pedroh-pereira** [comment]
@loicmathieu @evanchooly I think I've cover all points and the requested changes on the PR

**Comment by pedroh-pereira** [comment]
@gsmet @evanchooly @loicmathieu could we proceed with this change?

**Comment by loicmathieu** [comment]
Fixed by https://github.com/quarkusio/quarkus/pull/29665
