### ISSUE TITLE
Qute does not invoke getters generated by Hibernate Panache

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#14918]
**Describe the bug**
Because Qute accesses properties using the public field access, lazy loading is never triggered when Qute templates are rendered.

**Expected behavior**
When iterating a lazy (default) `@OneToMany` relationship, the entities should be queried from the DB (implemented in Panache when the getter method is invoked).

**Actual behavior**
Lazy collections in `@OneToMany` associations are never triggered

**To Reproduce**
Run the following project: 

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/5947031/code-with-quarkus.zip)

And hit http://localhost:8080/fruits. You should see `Apple`.

Go to the `Fruit` entity an uncomment the getter + private field and hit the URL again. You'll see `Apple` and two worms

**Comment by mkouba** [comment]
OK, so Panache generates a getter that looks like:
```java
@JsonProperty
public List<Bug> getBugs() {
   return this.$$_hibernate_read_bugs();
}

public List $$_hibernate_read_bugs() {
   if (this.$$_hibernate_getInterceptor() != null) {
      this.bugs = (List) this.$$_hibernate_getInterceptor().readObject(this, "bugs", this.bugs);
   }
   return this.bugs;
}
```
However, Qute does not read the modified bytecode but the Jandex index that obviously does not reflect this transformation.

I think that the easiest (not the most correct) solution would be to always pretend there is a getter if a class extends `PanacheEntity`. It should be really straightforward. I can try to prepare a PR so that we can evaluate this solution.

**Comment by mkouba** [comment]
Here it is: https://github.com/quarkusio/quarkus/pull/14937
