### ISSUE TITLE
@PreDestroy method seems to not be invocked when ExecutorManager is being used.

### ISSUE THREAD

**Issue by wmedvede** [quarkusio/quarkus#15026]
In the following project test-executor project

https://github.com/wmedvede/test-executor-issue.git

I have the silly component below.

All right, when I execute my application in dev mode, with mvn clean compile quarkus:dev

In can see that the created MyRunnable is executing, etc, as expected.
When I stop the application with "CTRL+C" the application stops gracefully, i.e. the @PreDestroy method is executed, the MyRunnable instance is stopped etc.

BUT, when I execute same application with

java -jar target/test-executor-1.0.0-SNAPSHOT-runner.jar (or with the generated native image)

There's no way to stop the application, i.e., the "CTRL+C" seems to simply do nothing in that particular scenario, and the @PreDestroy isn't invoked.

note: The @Observes ShutdownEvent works in all cases

`
@ApplicationScoped
@Startup
public class MyService {

    class MyRunnable implements Runnable {

        private AtomicBoolean exit = new AtomicBoolean(false);

        public void exit() {
            exit.set(true);
        }

        @Override
        public void run() {
            while (!exit.get()) {
                try {
                    Thread.sleep(2000);
                    System.out.println("MyRunnable is working!");
                } catch (InterruptedException e) {
                    Thread.currentThread().interrupt();
                    exit.set(true);
                }
            }
            System.out.println("MyRunnable has finished it work!");
        }
    }

    @Inject
    ManagedExecutor managedExecutor;

    MyRunnable myRunnableInstance;

    @PostConstruct
    void startService() {
        myRunnableInstance = new MyRunnable();
        managedExecutor.execute(myRunnableInstance);
    }

    /**
     * When we stop the application with CTRL+C this method is only invoked when
     * the application is started in dev mode. But not in native or if we execute the java runner.
     */
    @PreDestroy
    void destroyService() {
        System.out.println("Destroying the service!");
        if (myRunnableInstance != null) {
            System.out.println("Destroying the runnable!");
            myRunnableInstance.exit();
        }
    }

    /*
    This variant is always invocked
    void onShutDownEvent(@Observes ShutdownEvent ev) {
        System.out.println("SHUT DOWN EVENT is executed!!!!");
        if (myRunnableInstance != null) {
            System.out.println("Destroying the runnable!");
            myRunnableInstance.exit();
        }
    }
    */
}
`

**Comment by Ladicek** [comment]
Out of curiosity, I took a look at this in a debugger, because I thought perhaps that might be some easy bug, but no. What seems to happen is: shutdown is properly initiated, the shutdown task created by `ExecutorRecorder.createShutdownTask` runs, asks the executor to shut down and waits for it to finish. That obviously doesn't happen, because there's a task still running (the `MyRunnable` one). That task would be properly finished by the `@PreDestroy` method, but that method is only called during ArC container shutdown, and that is scheduled to happen _after_ the executor shutdown. (That is because ArC is started before the executor is started, and shutdown tasks are executed in reverse order.)

And it works fine in dev mode, because the executor is kept running between application reloads. So, executor shutdown isn't scheduled to application shutdown, but to JVM shutdown -- which is _after_ ArC shutdown, so it works fine. I think this one is for @stuartwdouglas :-)
