### ISSUE TITLE
There are no timeout defaults on the declarative rest client

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#15056]
**Description**
For declarative rest clients created by ResteasyClientBuilderImpl under io.quarkus.restclient.runtime.RestClientRecorder there are no default timeouts.  A connect and read timeout can be set via properties.  I could not find a good reference that this is expected behavior.  If it is, the quickstart or other places should call out that they need set.

Environment:
Quarkus version 1.11.0.Final
Maven info:
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Java version: 11.0.9.1, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-11-openjdk-11.0.9.11-9.fc32.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.10.7-100.fc32.x86_64", arch: "amd64", family: "unix"

**Comment by geoand** [comment]
cc @michalszynkiewicz

**Comment by FroMage** [comment]
It appears that MP-REST doesn't really specify a default, or at least it's not in the javadoc, but `0` means forever.

This is passed on to RESTEasy Client, which defaults to `-1` for "unset".

Which is then passed on to Apache HttpClient, which sets anything `<= 0` to `0`. So in practice it appears to default to `forever`.

Frankly this sounds wrong, especially from the PoV of Quarkus where we don't want worker threads blocked on blocking IO forever just because something is dragging our socket, so we should force a sensible default.

**Comment by geoand** [comment]
I completely agree with ^

**Comment by FroMage** [comment]
According to https://quarkus.io/guides/all-config we have a plethora of defaults to pick from, since we're VERY consistent:

- `quarkus.datasource.jdbc.acquisition-timeout`: 5 (5 minutes, 5 seconds, 5 years, who knows?)
- `quarkus.dynamodb.sync-client.connection-timeout`: 2S
- `quarkus.dynamodb.sync-client.apache.connection-acquisition-timeout`: 10S (that's another Apache HTTP client, so perhaps applicable?)
- `quarkus.dynamodb.async-client.connection-timeout`: 10S
- `quarkus.dynamodb.async-client.read-timeout`: 30S
- `quarkus.iam.sync-client.connection-timeout`: 2S
- `quarkus.http.read-timeout`: 60S
- `quarkus.openshift.liveness-probe.timeout`: 10S (is it dead, Jim?)

Interestingly I don't see timeout config for the Vert.x http client either.

**Comment by geoand** [comment]
Right, when I moved Consul to the vert.x client, I used custom fields: `quarkus.consul.agent.read-timeout` and ``quarkus.consul.agent.connection-timeout``

**Comment by FroMage** [comment]
Vert.x client appears to use a `60s` connect timeout default, but I can't find its read/write timeout.

**Comment by michalszynkiewicz** [comment]
I agree, there should be a default, finite read timeout. 
I modified RestEasy Reactive client to default to 30s in my changes.

**Comment by FroMage** [comment]
Well, read and connect too, right? What keys do you use?

**Comment by michalszynkiewicz** [comment]
do you mean configuration property keys?
I currently have `io.quarkus.rest.client.connect-timeout` and `io.quarkus.rest.client.read-timeout` (15 and 30 seconds).

**Comment by FroMage** [comment]
Sounds good. I wonder if we should have another set of properties `io.quarkus.connect-timeout` and `io.quarkus.read-timeout`, which every other timeout would default to?

So it would be global, and would be used by `io.quarkus.rest.client.connect-timeout` unless overridden, this allows each client to be configured, but also use a global default. WDYT?

I also wonder why we didn't go with `...timeout.connect` and `...timeout.read`?

**Comment by geoand** [comment]
> Sounds good. I wonder if we should have another set of properties `io.quarkus.connect-timeout` and `io.quarkus.read-timeout`, which every other timeout would default to?
> 

I am absolutely in favor of this

**Comment by michalszynkiewicz** [comment]
> I also wonder why we didn't go with `...timeout.connect` and `...timeout.read`?
Do you mean why I didn't name them that way?

A global default, overridable separately for different extensions sounds good to me too.

**Comment by FroMage** [comment]
@michalszynkiewicz so if we have defaults now, we can close this, right?

**Comment by geoand** [comment]
Indeed, let's close this

**Comment by pkumar72** [comment]
client = ClientBuilder.newBuilder()
            .connectTimeout(httpConnectTimeout, TimeUnit.MILLISECONDS)
            .readTimeout(httpReadTimeout, TimeUnit.MILLISECONDS)
            .build();
