### ISSUE TITLE
Allow for pass-through values on Compounds

### ISSUE THREAD

**Issue by ambition-consulting** [quarkusio/quarkus#15100]
Basically we need @AliasFor in Quarkus/MicroProfile, I think. This will help a lot with annotation cluttering.

**Comment by gsmet** [comment]
I have absolutely no idea what you're talking about :).

Could you give a bit more context in the description about the feature you're referring to? Thanks!

**Comment by geoand** [comment]
I assume we are talking about https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/core/annotation/AliasFor.html.

If that is indeed the case, I personally don't see much point

**Comment by ambition-consulting** [comment]
Yes, it helps in reducing annotation cluttering. Personally I have found a
workaround when using java immutables an Jackson, which allows
customisation differently

Georgios Andrianakis <notifications@github.com> schrieb am Mi., 17. Feb.
2021, 14:11:

**Comment by geoand** [comment]
Can you add an example of such cluttering and how `@AliasFor` reduces it?

**Comment by gsmet** [comment]
I'm closing this one. If you want us to consider this, we need a full description and a proper explanation of why it is useful.

**Comment by pipinet** [comment]
@gsmet  need it too.
@AliasFor is very useful in spring project，provides annotation override capabilities， just like override method.

**Comment by www-wanglong** [comment]
@gsmet  I also need

**Comment by caolf** [comment]
@gsmet @geoand  need it too. look forward to be supported.

**Comment by fengwangjie2** [comment]
@gsmet  i think this feature is very important for us

**Comment by AlbinGuo** [comment]
@gsmet @geoand 
need it too. this is a extremely important annotaion.

**Comment by geoand** [comment]
I am aware of the annotation in Spring, but I never found it really useful.

If someone shows me some examples where it really helps make things simpler, we can reconsider

**Comment by 13546106348** [comment]
I really need it in development.

**Comment by faskan** [comment]
@gsmet @geoand 
This is indeed a great feature in Spring that significantly reduces annotation clutter and verbosity in the code. Here's a simple but impactful use case:

To indicate a required field in my schema, I currently prefer to use `required = true` in individual fields rather than specifying it at the schema level with `requiredProperties`. This approach avoids ambiguity and results in code like the following:

```java
record InternetLine(
    @Schema(required = true, description = "Installation address to be displayed in UI")
    String installationAddress,
    @Schema(required = true, description = "Name of the plan")
    String planName,
    @Schema(required = true, description = "Speed of the internet line")
    int speed) {
}
```

However, if there were support for something like `@AliasFor` in Quarkus, the code could be much cleaner and more maintainable. For instance:

```java
record InternetLine(
    @MandatoryField(description = "Installation address to be displayed in UI")
    String installationAddress,
    @MandatoryField(description = "Name of the plan")
    String planName,
    @MandatoryField(description = "Speed of the internet line")
    int speed) {
}

@Schema(required = true)
public @interface MandatoryField {
    @AliasFor(annotation = Schema.class, attribute = "description")
    String description() default "";
}
```

This enhancement allows for a custom annotation that eliminates redundancy while preserving clarity. Additionally, there are more complex scenarios where most fields share constant values, except for one or two. Without `@AliasFor`, we are forced to repeat the entire annotation, making the code unnecessarily verbose.

Adding support for `@AliasFor `or a similar mechanism in Quarkus would greatly simplify such use cases and enhance the developer experience.

**Comment by geoand** [comment]
Thanks a lot for taking the time to write down your use case
