### ISSUE TITLE
Introduce some more Hibernate batch settings

### ISSUE THREAD

**Issue by AlexKovynev** [quarkusio/quarkus#15169]
**Description**

Add possibility to set that options:

hibernate.order_inserts   = true 
hibernate.order_updates   = true

**Comment by gsmet** [comment]
@Sanne @yrodiere would it make sense to add this? If we don't think it's a good idea, we can explain and close.

**Comment by Sanne** [comment]
I think we'll eventually want to enable these by default.

Today they are not enabled as some issues had been reported; AFAIR they are all fixed now but if we're to enable them without any way for users to turn them off that will need some extra caution.

I'm not a big fan of adding such toggles for the long term, but it would be useful to have such "feature flags" to allow some gradual phase-in of such changes.

Simplest way to do so is to include them among the regular options, and then remove them in some months time. Perhaps there's a general need to express such flags in a better way?

**Comment by yrodiere** [comment]
Closing because:

* `hibernate.order_inserts` will eventually be `true` by default in Quarkus, but currently cannot be because it is buggy.
* `hibernate.order_updates` is already `true` by default in Quarkus ([code](https://github.com/quarkusio/quarkus/blob/8816386b87e145ade6ef55aa0d7572f20c6eec21/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/FastBootMetadataBuilder.java#L271-L273))

[Source](https://github.com/quarkusio/quarkus/issues/19129#issuecomment-891088427)

In the meantime, you can set `order_inserts` to `true` through [`quarkus.hibernate-orm.unsupported-properties`](https://quarkus.io/version/main/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key) if you want to experiment.

**Comment by gavinking** [comment]
@Sanne i feel like it's a bit dangerous to diverge too much from the default behavior of regular Hibernate for stuff like this. For example, it means unit tests might not detect problems with statement ordering and constraint violations.

**Comment by Sanne** [comment]
Yes I recognize the risk in test coverage; but the whole point of not exposing these as supported properties is to limit the possible permutations of "lesser tested" properties; so while these are tested only partially in ORM upstream, all test in Quarkus (and by Quarkus users) are consistently using these - my goal would be to change the defaults in ORM upstream as well.

**Comment by Sanne** [comment]
@gavinking BTW it's really tricky to operate a non-trivial application in which ordering isn't applied consistently - very easy to get into deadlocks. So that's why I believe these should be enabled by default, possibly removing the properties upstream (but not rushing that).
Also it's my understanding that this was disabled by default as it came with significant in-memory processing costs, but I believe that's no longer the case - or at least something we can easily improve on. Certainly better to have a little more processing in the middleware layer than amplifying contention points on the database.

**Comment by gavinking** [comment]
I mean, if it's a better default, then we should change the default in a minor release of Hibernate, not as an ad hoc thing in Quarkus, IMO.

**Comment by mikethecalamity** [comment]
Any updates on this?

**Comment by yrodiere** [comment]
See #41698.
