### ISSUE TITLE
Virtual host support for amqp 1.0

### ISSUE THREAD

**Issue by Alwaysgone** [quarkusio/quarkus#15229]
Hello everyone,

we are currently trying to migrate our microservices to quarkus and have been using RabbitMQ with amqp 0.9 as a messaging broker. The goal here would be to be able to use smallrye reactive messaging with amqp 1.0 and the RabbitMQ amqp 1.0 plugin with the same setup we have right now. This includes the usage of various virtual hosts so we only have to maintain a single internal RabbitMQ cluster for development.

I'm currently using quarkus 1.11.3.Final and after a bit of fiddling I got a connection to work and could publish/subscribe using the RabbitMQ amqp 1.0 plugin and the fix described in https://github.com/smallrye/smallrye-reactive-messaging/issues/474.
However I might be missing something but I did not see any configuration option to set the virtual host, so any connection just uses / as default.

* Is this intended behaviour or simply not yet implemented?
* Are we supposed to setup a new RabbitMQ environment per customer for inhouse development, meaning is this now the preferred way to utilize an amqp 1.0 messaging environment?
* Is there a way to customize the amqp uri to simply insert the virtual host before a connection is made? A short code analysis of smallrye-reactive-messaging-amqp:2,7.1 suggests no.

I would be grateful for any input on this as this is kind of a blocker to use all the amazing features quarkus could offer us.

**Comment by cescoffier** [comment]
@gemmellr Are virtual hosts something defined in AMQP 1.0? I can't find anything relevant in the spec.

**Comment by gemmellr** [comment]
Virtual hosts arent explicitly mentioned in the spec @cescoffier I dont think (as thats more about a specific server-behaviour model, which 1.0 doesnt define, instead being more about message transfer between less constrained 'things'). Hostnames are mentioned however, and so the same sort of ability can be achieved using the hostname field in the connection Open frame: http://docs.oasis-open.org/amqp/core/v1.0/os/amqp-core-transport-v1.0-os.html#type-open

The spec mainly defines these values to be the DNS hostname being connected to if set, likely matching the TLS SNI value likely also sent, already allowing for multiple hostnames to be supported by a given messaging server, which some do and some dont. The spec does also allow for possibility that the hostname field value might differ from a previously known value for the connection, e.g. the SNI, though specifies it is undefined what behaviour it gives if it does. This essentially allows for doing the old 'virtual host' type behaviour from AMQP 0-x.

Ability to control the Open frame hostname is exposed in vertx-proton in a couple of ways. The first way is for the application code to simply set the value by calling connection.setHostname(host), before calling connection.open() to open it. The second way is with the Virtualhost client option, which makes it explicitly set both the SNI value and Open hostname values to the one given, instead of the default behaviour of letting SNI happen implicitly (by SSLEngine, if an FQDN is used to connect to) and not populating the Open hostname. Note the SNI value can be overridden itself using the SniServerName option too.

**Comment by cescoffier** [comment]
Thanks @gemmellr! 

I've to say that it's a bit embarrassing... as the Vert.x AMQP Client (which I did a few years ago) has a `virtual-host` attribute, configuring the connection hostname. 

Basically, the only thing missing was exposing that attribute in the connector. I just opened https://github.com/smallrye/smallrye-reactive-messaging/pull/1075 doing exactly this.

**Comment by Alwaysgone** [comment]
Thank you very much for the detailed explanation and the quick fix. Can this be expected to make it into the next release?

**Comment by cescoffier** [comment]
We will try, but I'm a bit behind schedule and releasing reactive messaging before 1.13.0 (next week) might be challenging.

**Comment by Alwaysgone** [comment]
No worries, we'll just keep a lookout for when it's available.
