### ISSUE TITLE
nonstandard behavior for bean discovery

### ISSUE THREAD

**Issue by gavinking** [quarkusio/quarkus#1525]
ArC has apparently made a decision to only support the CDI `"annotated"` bean discovery mode. That is, only classes with an explicit scope type annotation, or a stereotype, are considered beans and thus injectable.

It seems that in #124, it was realized that this just wasn't a good approach, since it would mean that even things like static producer methods weren't discovered. So scanning for `@Produces` was added, and thus the current behavior of ArC is to do something idiosyncratic, and non-compliant with the spec.

However, even this idiosyncratic approach to bean discovery robs CDI of useful functionality. The default behavior defined by the CDI spec allowed the injection of beans defined for use with *any* framework making use of the `@Inject` annotation. For example, it allowed CDI to instantiate and inject beans written for Guice or Spring, without the need to add any additional annotations to those beans. (Yes, there was a reason behind the original design!)

The concern here seems to have been performance. Namely, the concern is that sometimes CDI containers are required to treat some classes as beans even if they were not intended by the author of the class to be used in that way. It seems to me that we shouldn't need to be very worried about this:

1. It's only a problem when you have a single archive which contains both a handful of CDI beans and a whole lot of other classes with default constructors that aren't beans. Obviously that's going to be very rare in a new project, and even in larger projects, it's quite likely that you have beans in a separate archive or at least a separate package within the archive.
2. In the context of ArC, we do all this work at compile time! There is no runtime cost to taking additional classes into consideration. This is a closed-world situation where we can already identify all the `@Inject`ion points, and their types, and quickly discard any "beany" class that doesn't have a bean type matching any `@Inject`ion point.

I highly doubt that there is a significant cost to simply having ArC support the default spec-defined behavior of `bean-discovery-mode="all"` for most projects. In cases where a problem does arrive (i.e. slow builds), CDI provides an easy method of filtering packages with `<exclude>`, that should quickly resolve the issue.

So I think we should at least experiment with making ArC just do the standard thing.

**Comment by bender316** [comment]
Any news on this topic?

The current behavior of ArC leads to a lot of extra effort if used libs rely on `bean-discovery-mode=all`.

**Comment by radcortez** [comment]
+1

**Comment by gsmet** [comment]
@mkouba ?

**Comment by mkouba** [comment]
So the current simplified approach is highly optimized for our primary goals. But it probably doesn't fit all the use cases we'd like to support. I'm going to add some comments and leave the discussion open so that we could potentially revisit the bean discovery in quarkus 1.1+.

> That is, only classes with an explicit scope type annotation, or a stereotype, are considered beans and thus injectable.

Not really. The final set of bean defining annotations also contains annotations registered by quarkus extensions (e.g. `@Path` from JAX-RS). Moreover, an extension is allowed to declare additional discovery rules; for example if a class declares a method annotated with `@Scheduled`, `@Dependent` is added automatically.

> since it would mean that even things like static producer methods weren't discovered

In fact, static producers are not supported ATM and so far there was no complaint about that. I've created https://github.com/quarkusio/quarkus/issues/5513 to track this feature request.

> the current behavior of ArC is to do something idiosyncratic, and non-compliant with the spec

Sure. There are many things we're trying to do differently and many spec features we deliberately skip.

> In the context of ArC, we do all this work at compile time! There is no runtime cost to taking additional classes into consideration.

1. Yes, it's a build time cost which is also important, esp. in the dev mode where file modifications result in a new build "at runtime".
2. If we don't remove the unused beans the memory consumption will increase noticeably (we have experience from Weld).

> This is a closed-world situation where we can already identify all the @Injection points, and their types, and quickly discard any "beany" class that doesn't have a bean type matching any @Injection point.

We do have an optimization called **unused beans removal** - see https://quarkus.io/guides/cdi-reference#remove_unused_beans. However, it is definitely not for free (the time increases with the number of beans) and has drawbacks - for instance we can't detect the programmatic lookup of beans via `CDI.current()` and `BeanManager`. And yes, `CDI.current()` was IMHO rather a mistake and shouldn't be used in apps but the reality is a bit different.

> I highly doubt that there is a significant cost to simply having ArC support the default spec-defined behavior of bean-discovery-mode="all" for most projects.

So the bean discovery mode of the application modules (`src/main/java` and other modules in the project) is probably not a problem because the developer controls the classes and I highly doubt that she/he will mix spring/guice components there.

The main problem are **third-party dependencies**. This is the reason why I think we should potentially revisit the bean discovery.

> CDI provides an easy method of filtering packages with <exclude>, that should quickly resolve the issue.

Unsupported in quarkus. The contents of `beans.xml` is just ignored.

**Comment by mkouba** [comment]
I'm going to close this issue because ArC is aligned with [CDI 4.0 Lite](https://jakarta.ee/specifications/cdi/4.0/jakarta-cdi-spec-4.0.html#bean_archive) where `annotated` is the default and `all` is not supported at all.
