### ISSUE TITLE
unnecessary warning was shown resteasy-reactive

### ISSUE THREAD

**Issue by gechoi-ahunga** [quarkusio/quarkus#15400]
**Describe the bug**
I got the message when resteasy-reactive project.

(build-70) [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] null: Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. I used quarkus-resteasy-reactive-jackson with below dependency.

```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>
```
In my understanding if I added resteasy-reactive-jackson, then it includes automatically .

```
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny</artifactId>
</dependency>
```

So, I don't need add "quarkus-resteasy-mutiny" extension, although I use Uni/Multi.

I think that is happened when I add two dependencies
quarkus-keycloak-admin-client and quarkus-smallrye-jwt for other purpose.

Could you please let me know to remove this "WARN", when I see RestEasyCommonProcessor" code, it is checked RESTEASY_MUTINY for capability, but seems like need to check other way which can be used for smallrye reactive.

I suspect that warning is because "quarkus-keycloak-admin-client" use resteasy class

**Expected behavior**
if there is below dependency for mutiny in quarkus-resteasy-reactive-jackson
<dependency>
    <groupId>io.smallrye.reactive</groupId>
    <artifactId>mutiny</artifactId>
</dependency>

the warning message should not be shown.

(build-70) [io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor] null: Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. I used quarkus-resteasy-reactive-jackson with below dependency.

(Describe the expected behavior clearly and concisely.)

(Describe the actual behavior clearly and concisely.)

**To Reproduce**
Add this two dependency, then this warning was shown.

```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-resteasy-reactive-jackson</artifactId>
</dependency>
```

    <dependency>
      <artifactId>quarkus-keycloak-admin-client</artifactId>
      <groupId>io.quarkus</groupId>
    </dependency>

Link to a small reproducer (preferably a Maven project if the issue is not Gradle-specific).

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java):  GraalVM 11
 - Quarkus version or git rev: 
 - Build tool (ie. output of `mvnw --version` or `gradlew --version`): 

**Additional context**
(Add any other context about the problem here.)

**Comment by thuringia** [comment]
@geoand Has this been also fixed for 1.13?
I get this warning message on every 1.13 release and request handling is indeed quite weird at the moment

**Comment by geoand** [comment]
It should be part of 1.13.

What exactly are you seeing?

**Comment by thuringia** [comment]
If we only include `quarkus-resteasy-reactive-jackson`, or both `resteasy-reactive` and `resteasy-reactive-jackson` as a dependency, then Gradle logs
```
Apr 28, 2021 11:49:55 AM io.quarkus.resteasy.common.deployment.ResteasyCommonProcessor setupProviders
    WARN: Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. Reactive REST endpoints in your application that return Uni or Multi will not function as you expect until you add this extension. Endpoints that need Mutiny are:
```
and the deployment appears to be inconsistent as our unit tests and test system react in unexpected ways.
Incidently, if I change it to use `resteasy`, `resteasy-jackson` and `resteasy-mutiny`, it is working

**Comment by geoand** [comment]
You can't use ``quarkus-resteasy-reactive-jackson` along with the `quarkus-resteasy`, `quarkus-resteasy-jackson` or `quarkus-resteasy-mutiny`

**Comment by thuringia** [comment]
I know, I have to switch out the extensions to the non-reactive `resteasy` and then add `resteasy-mutiny`.
Any of the `resteasy-reactive-*` extensions causes the build issue.

From my understanding, the `resteasy-reactive` extension is just the `resteasy` + `resteasy-mutiny` extensions anyways

**Comment by geoand** [comment]
> I know, I have to switch out the extensions to the non-reactive `resteasy` and then add `resteasy-mutiny`.
> Any of the `resteasy-reactive-*` extensions causes the build issue.
> 

Like I said, you need to be using `quarkus-resteasy-reactive*`

> From my understanding, the `resteasy-reactive` extension is just the `resteasy` + `resteasy-mutiny` extensions anyways

No, that is not correct. See https://quarkus.io/blog/resteasy-reactive-faq/#how-does-it-compare-to-resteasy-classic-with-mutiny

**Comment by thuringia** [comment]
Then I can only conclude that the extension is broken...
I'd like to be more helpful, but at this point I modified our code to be exactly like the guides describe it, and it keeps throwing Gradle warnings and unit tests don't even make calls to our wiremock.

Otherwise it could only be some kind of incompatibility between the RESTeasy stuff and lower level Vertx (Vertx web client with the `quarkus-vertx` extension), which we use to call APIs, or the MongoDB client extension and the AWS SDK.
Our Mutiny based scheduled jobs using the same code are working though, so from my/our perspective this is an issue on the RESTeasy side.

**Comment by geoand** [comment]
> Then I can only conclude that the extension is broken...

That's rather unlikely given how many people already use it.

If you have an example application that exhibits the behavior you mention, add it to github please and I can take a look

**Comment by FroMage** [comment]
If you show us your `pom.xml` it will already go a long way towards validating where the issue is.

**Comment by thuringia** [comment]
Here's the build configuration of the service in question:
<details>
<summary>gradle.properties</summary>
<code>
quarkusPluginVersion=1.13.2.Final
quarkusPlatformArtifactId=quarkus-universe-bom
quarkusPluginId=io.quarkus
quarkusPlatformGroupId=io.quarkus
quarkusPlatformVersion=1.13.2.Final
kotlinPluginVersion=1.4.31
</code>
</details>

<details>
<summary>settings.gradle.kts</summary>
<code>
pluginManagement {
    val quarkusPluginVersion: String by settings
    val quarkusPluginId: String by settings
    val kotlinPluginVersion: String by settings

    repositories {
        mavenLocal()
        mavenCentral()
        gradlePluginPortal()
    }
    plugins {
        kotlin("jvm") version kotlinPluginVersion
        kotlin("plugin.allopen") version kotlinPluginVersion
        id(quarkusPluginId) version quarkusPluginVersion
    }
}
rootProject.name = "libra"
</code>
</details>

<details>
<summary>build.gradle.kts</summary>
<code>
plugins {
    kotlin("jvm")
    kotlin("plugin.allopen")
    id("io.quarkus")
    id("com.diffplug.spotless") version "5.11.1"
}

repositories {
    mavenLocal()
    mavenCentral()
}

val quarkusPlatformGroupId: String by project
val quarkusPlatformArtifactId: String by project
val quarkusPlatformVersion: String by project

dependencies {
    implementation(kotlin("stdlib-jdk8"))

    implementation(enforcedPlatform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))

    // implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-amazon-sns")
    implementation("software.amazon.awssdk:netty-nio-client")
    implementation("io.quarkus:quarkus-container-image-jib")
    implementation("com.fasterxml.woodstox:woodstox-core")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
    implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-logging-json")
    implementation("io.quarkus:quarkus-micrometer")
    implementation("io.micrometer:micrometer-registry-cloudwatch2")
    implementation("io.micrometer:micrometer-registry-prometheus")
    implementation("io.quarkus:quarkus-mongodb-client")
    implementation("io.quarkus:quarkus-oidc-client")
    implementation("io.quarkus:quarkus-oidc-client-filter")
    // this set of extensions compiles without Gradle warnings:
    // implementation("io.quarkus:quarkus-resteasy")
    // implementation("io.quarkus:quarkus-resteasy-jackson")
    // implementation("io.quarkus:quarkus-resteasy-mutiny")
    // end
    // this is what we want/should use but causes a Gradle warning:
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    // end
    implementation("io.quarkus:quarkus-scheduler")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-vertx")
    implementation("io.netty:netty-transport-native-epoll:linux-x86_64")
    implementation("io.netty:netty-transport-native-kqueue:osx-x86_64")
    implementation("io.vertx:vertx-lang-kotlin")
    implementation("io.smallrye.reactive:smallrye-mutiny-vertx-web-client")

    implementation("io.cloudevents:cloudevents-json-jackson:2.0.0")

    // de.otto.prada.product
    implementation("org.apache.commons:commons-compress:1.20")
    implementation("com.google.guava:guava:30.1.1-jre")
    implementation("net.jcip:jcip-annotations:1.0")

    testImplementation("io.quarkus:quarkus-junit5")
    testImplementation("io.quarkus:quarkus-junit5-mockito")
    testImplementation("io.rest-assured:rest-assured")
    testImplementation("com.github.tomakehurst:wiremock-jre8:2.27.2")
    testImplementation("org.awaitility:awaitility")
}

group = "de.company"
version = "1.0.0-SNAPSHOT"

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

allOpen {
    annotation("javax.ws.rs.Path")
    annotation("javax.enterprise.context.ApplicationScoped")
    annotation("io.quarkus.test.junit.QuarkusTest")
}

tasks.withType<org.jetbrains.kotlin.gradle.tasks.KotlinCompile> {
    kotlinOptions.jvmTarget = JavaVersion.VERSION_11.toString()
    kotlinOptions.javaParameters = true
}

tasks.withType(JavaCompile::class) {
    options.compilerArgs.add("-Xlint:unchecked")
    options.compilerArgs.add("-Xlint:deprecation")
}

spotless {
    java {
        toggleOffOn()
        importOrder()
        removeUnusedImports()
        googleJavaFormat("1.10.0")
    }

    kotlin {
        toggleOffOn()
        ktlint("0.41.0")
    }

    kotlinGradle {
        target("*.gradle.kts")
        toggleOffOn()
        ktlint("0.41.0")
    }
}
</code>
</details>

This results in the following Gradle output:
<details>
<summary> ./gradlew build -Dquarkus.package.type=uber-jar</summary>
<code>
> Task :quarkusGenerateCode
preparing quarkus application

> Task :quarkusGenerateCodeTests
preparing quarkus application

> Task :quarkusBuild
building quarkus jar

Quarkus detected the need for Mutiny reactive programming support, however the quarkus-resteasy-mutiny extension was not present. Reactive REST endpoints in your application that return Uni or Multi will not function as you expect until you add this extension. Endpoints that need Mutiny are: de.company.#{io.smallrye.mutiny.Uni<de.company.#Response> startImport(de.company.#Request body)}
Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
        - com.google.common.collect.Multimap (sources: JacksonProcessor > de.company.#, JacksonProcessor > de.company.#$Builder)
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.
Duplicate entry codegen-resources/examples-1.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/service-2.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/paginators-1.json entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry codegen-resources/customization.config entry from software.amazon.awssdk:sns::jar:2.16.19(runtime) will be ignored. Existing file was provided by software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)
Duplicate entry META-INF/maven/io.netty/netty-transport-native-epoll/pom.properties entry from io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime) will be ignored. Existing file was provided by io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)
Duplicate entry META-INF/maven/io.netty/netty-transport-native-epoll/pom.xml entry from io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime) will be ignored. Existing file was provided by io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)
Duplicate entry javax/xml/bind/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/xml/bind/helpers/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/xml/bind/util/Messages.properties entry from org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime) will be ignored. Existing file was provided by jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime)
Duplicate entry javax/el/PrivateMessages.properties entry from jakarta.el:jakarta.el-api::jar:3.0.3(runtime) will be ignored. Existing file was provided by org.glassfish:jakarta.el::jar:3.0.3(runtime)
Dependencies with duplicate files detected. The dependencies [com.sun.activation:jakarta.activation::jar:1.2.1(runtime), jakarta.activation:jakarta.activation-api::jar:1.2.1(runtime)] contain duplicate files, e.g. javax/activation/ActivationDataFlavor.class
Dependencies with duplicate files detected. The dependencies [jakarta.xml.bind:jakarta.xml.bind-api::jar:2.3.3(runtime), org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec::jar:2.0.0.Final(runtime)] contain duplicate files, e.g. javax/xml/bind/Validator.class
Dependencies with duplicate files detected. The dependencies [io.netty:netty-transport-native-epoll:linux-x86_64:jar:4.1.49.Final(runtime), io.netty:netty-transport-native-epoll::jar:4.1.49.Final(runtime)] contain duplicate files, e.g. io/netty/channel/epoll/EpollChannelConfig$1.class
Dependencies with duplicate files detected. The dependencies [jakarta.el:jakarta.el-api::jar:3.0.3(runtime), org.glassfish:jakarta.el::jar:3.0.3(runtime)] contain duplicate files, e.g. javax/el/BeanELResolver$BPSoftReference.class
Dependencies with duplicate files detected. The dependencies [org.jboss.logging:commons-logging-jboss-logging::jar:1.0.0.Final(runtime), commons-logging:commons-logging::jar:1.2(runtime)] contain duplicate files, e.g. org/apache/commons/logging/impl/SimpleLog$1.class
Dependencies with duplicate files detected. The dependencies [software.amazon.awssdk:sns::jar:2.16.19(runtime), software.amazon.awssdk:cloudwatch::jar:2.16.19(runtime)] contain duplicate files, e.g. codegen-resources/paginators-1.json
Dependencies with duplicate files detected. The dependencies [org.jetbrains.kotlin:kotlin-reflect::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib-jdk7::jar:1.4.31(runtime), org.jetbrains.kotlin:kotlin-stdlib-jdk8::jar:1.4.31(runtime)] contain duplicate files, e.g. META-INF/versions/9/module-info.class

BUILD SUCCESSFUL in 4m 1s
18 actionable tasks: 14 executed, 4 up-to-date
Time: 0h:04m:04s
</code>
</details>

In addition, I attached the result of `./gradlew -q dependencies` so that you can check for classpath collisions.
[dependencies.txt](https://github.com/quarkusio/quarkus/files/6392539/dependencies.txt)

**Comment by FroMage** [comment]
I can see `org.jboss.resteasy:resteasy-core` and `io.quarkus:quarkus-resteasy-common` are imported. Probably transitively. Could you open a new issue, since this one has actually been fixed, and include the previous comment's information as well as a tree view of your dependency graph please? So we can find the culprit?

**Comment by thuringia** [comment]
I'll be happy to, what do we want to call the new issue, so that we can properly separate it from this one?
Otherwise I'd call it "resteasy-reactive extension imports non-reactive versions transitively",

Also, a really big thank you for your quick help. I, and everyone on my team, really appreciates it.

**Comment by FroMage** [comment]
I think it could be named "Unexpected transitive import of resteasy when using resteasy-reactive". Thanks to you for reporting :)
