### ISSUE TITLE
Rollback DB changes when using RESTassured to test an endpoint

### ISSUE THREAD

**Issue by vc-void** [quarkusio/quarkus#15436]
**Description**
I was hoping that @TestTransaction could also rollback any database changes when calling an endpoint using RESTassured. Is this feasible?

**Comment by famod** [comment]
Right now this is a "non-goal" of `@TestTransaction`, so to say.

Frankly, with a serious ammount of effort something _could maaaybe_ be implemented so that the test framework can the app to roll back the next transaction, but chances are that it's not possible or too hacky/fragile.
And what if you have multiple calls in a test method? Normally, you would expect a regular commit so that the second request can see the result of teh first one, no?

I suggest to take a look at #14240 which has some ideas on how to reset a DB for tests.

/cc @geoand @stuartwdouglas
