### ISSUE TITLE
Avoiding app.quarkus.io annotations

### ISSUE THREAD

**Issue by ppatierno** [quarkusio/quarkus#15473]
Hello,
as per Kubernetes extension documentation, some "app.quarkus.io" annotations are added by default but it seems it's not possible to avoid them. Am I wrong? Would it be possible to make that generation optional?

**Comment by gsmet** [comment]
@ppatierno why are they a problem for you? /cc @iocanel too

**Comment by geoand** [comment]
Is there a specific reason why you don't want these annotations?

Keep in mind that they are annotations, not labels

**Comment by ppatierno** [comment]
They are just poisoning my YAML when I don't need them. 
I know that they are annotations but why not providing the choice to have them or not?
I mean, I would like to have control over what I want on the generated deployment. It's useful that Quarkus generates stuff for me but having more control is much better.
I also don't know the reason why the vcs-url is generated with an old URL when the repo was moved.

**Comment by geoand** [comment]
I personally don't see the problem, but if someone else wants to implement this in a backward compatible way, I won't object.

**Comment by iocanel** [comment]
I don't mind adding a flag to enable / disable them. The thing is that I don't want to have a flag for every single optional thing we do have in our manifest.

Some possible approaches:

# Have a config option where the user can add one or more optional metadata kinds to be added

I am wondering if we could have an option like:

    quarkus.kubernetes.metadata=labels, version, annotations

The presence of `labels` means that recommended labels will be added. 
The presence of `version` means tha the version labels will be added.
The presence of `annotations` means that the annotations will be added.

# Full control over the exact labels / annotations to ignore

Another option is to give more fine grained control over labels or annotations that will be removed.

    quarkus.kubernetes.ignore.labels=app.kubernetes.io/name, app.kubernetes.io/version
    quarkus.kubernetes.ignore.annotations=app.quakrus.io

Possibly instead of `ignore` we could use `hide`, `remove` or `skip`.

**Comment by ppatierno** [comment]
I was trying to do something like this

`quarkus.kubernetes.annotations."app.quarkus.io/commit-id"=`

but of course I got an error that it cannot be empty. It could be a way for allowing people to select what they want.
I would be for the more fine grained control you proposed.

**Comment by lburgazzoli** [comment]
A reason to have an option to turn on/off those additional annotations is that if you want to included the generated resources in your vcs, then any build will trigger some changes to those resources and generates unwanted changes. Most problematic annotations for our use case are:

    app.quarkus.io/commit-id: ...
    app.quarkus.io/build-timestamp: ...

**Comment by geoand** [comment]
Is this still something we want?

**Comment by iocanel** [comment]
> Is this still something we want?

Absolutely.

I think that we need a flag that makes the generation idemptent. When this falg is enabled we should remove these properties and also use a static image repository / group instead of using the username.
