### ISSUE TITLE
Vert.x Routes Not Working when using Void methods

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#15470]
**Describe the bug**
Having the next route:

```java
@Route(methods = HttpMethod.GET, path = "/method-return-empty/:first_param")
    void validateMethodWithEmptyResponse(@Param("first_param") String param) {
        // do nothing
    }
```

When we call this route via CURL, it fails with `Read timed out`. 

**Expected behavior**
The service should return 204 No Content.

**Actual behavior**
The servide hangs to return anything.

**Environment (please complete the following information):**
 - Quarkus version or git rev: 999-SNAPSHOT

**Comment by mkouba** [comment]
Hi @Sgitario, this behavior is expected. In fact, the build should fail if a similar `@Route` method is found. We should improve the validation logic - currently, it only fails if a method that return `void` does not declare any parameters. This logic is not valid since quarkus 1.7 where `@Param`, `@Body` and others non-`RoutingContext` params were added.

For the record - a `@Route` method must either (a) return non-void result or (b) end the response via one of the `HttpServerResponse.end()` methods.
