### ISSUE TITLE
Test webjar support

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#1606]
We should test if we currently support webjars (in JVM mode and native).

A good test for that might be to deploy the Swagger-UI webjar in an application.

@geoand wondering if you might be interested in this one?

**Comment by geoand** [comment]
@gsmet Sure thing! I'll give it a shot over the weekend

**Comment by geoand** [comment]
I tested how well we do with webjar by simply using angularjs from webjars for the `hibernate-orm-resteasy` starter.
So all I had to do was add:

```
        <dependency>
            <groupId>org.webjars</groupId>
            <artifactId>angularjs</artifactId>
            <version>1.4.8</version>
        </dependency>
```

and change the UI to use `/webjars/angularjs/1.4.8/angular.min.js` instead of `//ajax.googleapis.com/ajax/libs/angularjs/1.4.8/angular.min.js`.

AngularJS only worked properly when running in plain JVM mode. Using devmode or native does not work (this I was expecting because we aren't including the resources in any way). 
I should not that in devmode the classpath manifest properly included the `webjars` dependency so I'm not sure what exactly is going on
