### ISSUE TITLE
CLI: consider defaulting to `dev` command when in a quarkus project

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#16155]
ATM it lists the available commands, but there's already `qs --help` for that.

It could be a nicer default to default to `qs dev` if the current CWD is a quarkus project, no?

And bonus points: open browser on the DEV UI?

**Comment by maxandersen** [comment]
How do you quickly decide a project is a Quarkus project ?

**Comment by maxandersen** [comment]
Open browser on dev/UI  I'm not following...what if it's a command mode or pure websocket there is no devui...should be a better thing devmode itself in Quarkus would do that...?

**Comment by FroMage** [comment]
> How do you quickly decide a project is a Quarkus project ?

Well you already do that, don't you? Since I've seen the CLI fire up gradle or mvn.

> Open browser on dev/UI I'm not following...what if it's a command mode or pure websocket there is no devui...should be a better thing devmode itself in Quarkus would do that...?

Perhaps, true.

**Comment by maxandersen** [comment]
> Well you already do that, don't you? Since I've seen the CLI fire up gradle or mvn.
> 

that happens because user explicit asks for a command to execute.

That said I'm not really against the idea as another thing I would like to add is #11516 so you can just run `qs build` or `qs dev` in any subdirectory of a project. having that then "qs" anywhere would bring you into devmode.

which I guess isn't a bad thing - but for me getting help printed is just the default experience I have with other clis...lets me discover what it can do more.

maybe if we did something like print a single line info in this default case:

```
$ qs
No command found, running devmode. Run qs --help for more options.
[INFO] Scanning for projects...
[INFO]
[INFO] ---------------------< org.acme:code-with-quarkus >---------------------
[INFO] Building code-with-quarkus 1.0.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
```

wdyt?

**Comment by FroMage** [comment]
> for me getting help printed is just the default experience I have with other clis...lets me discover what it can do more.

Sure, but other CLIs don't really have any logical default action, perhaps? This sorta feels like one of those "oh you know what I mean" when you type it.

```
$ qs
No command found, running devmode. Run qs --help for more options.
```

That looks perfectly fine to me :)

**Comment by ebullient** [comment]
hmmm. maybe.. if there was no other output that would scroll the buffer so you would know what happened.. maybe. but I could just as easily see the default action as a one-and-done build (rather than dev).. if you are already in a quarkus project sonewhere..

**Comment by maxandersen** [comment]
doing `quarkus dev` is not that hard vs being a noob trying out quarkus for the first time possibly in a directory with a pom/build.graadle/etc. around from something non-quarkus your first quarkus experience is a fail rather than a friendly guidance of quarkus cli help text letting you know what you can do.

Thus for now closing this.
