### ISSUE TITLE
Quarkus OpenShift plugin should have option to deploy using Deployment instead of DeploymentConfig

### ISSUE THREAD

**Issue by wtrocki** [quarkusio/quarkus#16547]
## Describe the extension
 
 Using deployment config is particularly problematic with SBO use cases as it requires to roll new deployment to see bindings etc. This way many people will be forced to use kubernetes plugin that is somewhat limited (doesn't expose routes etc.).
 
 It will be great to be able to use openshift features but have option to still use Deployment.
Deployment is also recommended for Openshift so no issues here.

That is probably more decorate issue (CC @iocanel ) but logging in quarkus for more discussion

**Comment by geoand** [comment]
I think we've heard this request in the past as well, right @iocanel?

It does sound useful to me

**Comment by iocanel** [comment]
Yeah, this is something that has been requested quite a few times in the past and eventually we will have to address this request.

My biggest concern is that I am not comfortable adding an additional option into the mix (which will translate to at least 4 new major combinations), before we short out our CI around kubernetes/opesnhift.

**Comment by wtrocki** [comment]
I see this architecture as different things. 

Instead of kuberentes and openshift as targets quarkus properties should control what additional objects will be included into spec. 

So instead of Openshift.yml or kubernetes.yaml - there could be app.yaml - with deployment (kubernetes concept), route openshift concept etc. This way people could also add their own extensions in the future if they need concept of stateless sets etc. Decorate will be less black boxy and things will be much easier to document in the quarkus. 

Initially when learning about deployment in quarkus you need to navigate a lot between build models (docker, jib etc), kuberentes guide (which is bare and still have template in it) and OpenShift (the most refined one but also blackboxy).

If decorate works with per resource model then all of that could have been composed to one guide with chapter for openshift specific DeploymentConfig, ImageStream etc.

This is very opiniated take, but for newcomers that would be much easier to succeed.
In my mind I should not make choice between OpenShift deployment or Kuberentes deployment. 
OpenShift is Kubernetes with some additional CR's and better UI :D

**Comment by iocanel** [comment]
Hi @wtrocki.

Thanks for sharing your thoughts. The documentation could need some love as its currently easy to get lost into the maze of different configuration possible.

Please find some comments inline:

> So instead of Openshift.yml or kubernetes.yaml - there could be app.yaml - with deployment (kubernetes concept), route openshift concept etc.

I like having a platform agnostic name, however this means that we will no longer be able to let users generate manifests for multiple platforms in a single step and then decide were to deploy. Is this a feature that is used in practice by our users? I honestly don't know, but it is a nice to have, that I wouldn't easily give up just for the shake of having a platform agnostic name.


> This way people could also add their own extensions in the future if they need concept of stateless sets etc. 
The name of the file has nothing to with ability of adding additional extensions in the future that would convert the `Deployment` to a `StatefulSet`.

> Decorate will be less black boxy and things will be much easier to document in the quarkus.
I can see things being easier to document, since we will be using everywhere the name `app.yml` vs something platofrm specific.  Is there anything more to it?
 
> Initially when learning about deployment in quarkus you need to navigate a lot between build models (docker, jib etc), kuberentes guide (which is bare and still have template in it) and OpenShift (the most refined one but also blackboxy)
You are right! We expose way to many details to newcomers. We need to do a better job and start with a more opinionated take on how things should be done, but also provide a full references for people that need to deviate from that.

> If decorate works with per resource model then all of that could have been composed to one guide with chapter for openshift specific DeploymentConfig, ImageStream etc.

The good thing is that we have control in quarkus on how these resources will be generated, so it should be fairly trivial to organize the generated resources as we see fit. In other words, there are no technical reasons that binds us to the dekorate way of generating files.

> This is very opinionated take, but for newcomers that would be much easier to succeed.
This is highly appreciated and thanks for taking the time to share. I totally agree with the sentiment (we do need to document things better, we need to provide the simplest possible experience to the user, we need to eliminate the number of choice to the minimum), but I am not 100% convinced that the `app.yml` approach is the way to go.

> In my mind developers trying quarkus should not make choice between OpenShift deployment or Kuberentes deployment.
> OpenShift is Kubernetes with some additional CR's and better UI :D

I agree. Maybe it worth mentioning that manifests generated for kubernetes, do work for Openshift too (after all you said yourself Openshift isa Kubernetes). Still there are some details that might need to be highlighted:
- `Ingress` are converted to `Route` by openshift, but this only works if host is provided on the `Ingress`.
- In case of Openshift builds the image will end up in the internal registry, which will have to be explicitly specifed for the `Deployment` to pick it. (there is room for improvement here).

Maybe we should start by properly documenting this.

**Comment by geoand** [comment]
@iocanel this is now something we need to get done because Service Binding is becoming important in Quarkus

**Comment by iocanel** [comment]
Yeah, we get that a lot, so we need to do this asap

**Comment by maxandersen** [comment]
Just to be clear here - reason we need(ed) is that rhoas bind did not support DeploymentConfig but that is being added in https://github.com/redhat-developer/app-services-cli/issues/589.

If that is done what are the reasons to make openshift extension have option for using Deployment ?

**Comment by wtrocki** [comment]
Considering complexity and little end user value I think this issue can be closed (at least from my perspective)

**Comment by Sgitario** [comment]
I think this issue is already done and hence can be closed. See https://quarkus.io/guides/deploying-to-openshift#using-deployment-instead-of-deploymentconfig

//cc @iocanel @geoand

**Comment by geoand** [comment]
It has yes! Thanks for spotting this old issue
