### ISSUE TITLE
IDE integration for `application.properties`

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#1655]
It would be nice to have some kind of IDE integration/support around `application.properties`, to provide things like tab completion and quick documentation, as well as validation.

**Comment by sebastienblanc** [comment]
+1
That would be really nice and would enhance considerably the developer experience, I admit I appreciate this feature in intellij when I work with Spring Boot apps. 
For Intellij, at least, I think it's a matter of generating some meta-data in the META-INF that can be processed then by Intellij's Annotation processor. https://blog.rufer.be/blog/knowledge-base/Configuration-properties-meta-data-support-in-IntelliJ.html

**Comment by rquinio** [comment]
For Eclipse there is a spring-boot support plugin with same feature: https://github.com/spring-projects/sts4/wiki/Boot-Properties-Editor (can be installed at https://spring.io/tools3/sts/all)

If nobody has started working on this yet, I'm willing to give a try.

Is it OK to introduce a dependency from quarkus-extension-processor to org.springframework.boot:spring-boot-configuration-processor:2.1.6 (note: it has no transitive dependencies), to re-use the metadata object model and JSON marshalling ?

My understanding is that each extension would generate a file META-INF/spring-configuration-metadata.json (format: https://docs.spring.io/spring-boot/docs/current/reference/html/configuration-metadata.html#configuration-metadata-format ) with:

- the groups from `@ConfigGroup` and `@ConfigRoot` annotated types
- the properties from `@ConfigItem` annotated types, with the name, type, defaultValue, as well as description set from the Javadoc of the field (already generated today into quarkus-javadoc.properties)
- the hints would not be used

**Comment by dmlloyd** [comment]
Sure, that's probably OK, just be aware that these are not public SPIs so the format of the metadata may change without much notice.

**Comment by rquinio** [comment]
Here's the output of my attempt:

Eclipse:
![eclipse-quarkus-config](https://user-images.githubusercontent.com/1886883/60401974-778c0280-9b89-11e9-8bcb-980e6e71218f.jpg)

IntelliJ:
![idea-quarkus-config](https://user-images.githubusercontent.com/1886883/60402244-3e559180-9b8d-11e9-8c34-8cc03c89edad.jpg)

Limitations seen:

1) spring-boot IDE integration only works for **runtime configuration**, since it is based on Maven/Gradle classpath with extensions runtime jars (and extension-deployment jars are bootstraped by quarkus).  This is a big limitation when 90% of Quarkus config applies at build time ! Maybe the priority should be more about IDE support for #3012 ?

2) Testability of the extension processor is problematic:

- To compile code with the config annotations you need to introduce a dependency cycle between quarkus-extension-processor and quarkus-core ...
- I tried https://github.com/google/compile-testing framework, in-memory compilation doesn't work well due to Quarkus using java.nio (https://github.com/quarkusio/quarkus/blob/master/core/processor/src/main/java/io/quarkus/annotation/processor/ExtensionAnnotationProcessor.java#L148 ), and compile-testing doesn't have a built-in in-memory NIO FileSystem.

3) Code duplication: it basically means re-writting io.quarkus.deployment.configuration.ConfigDefinition , but using annotation processor API.

4) For Eclipse the spring plugin is free and works out-of-the-box. But for IntelliJ spring application.properties editor requires the ultimate (commercial) edition and also activates only if spring-boot is actually in the classpath (provided scope is OK)...

5) Support for Collection and Map values that are also ConfigGroups are not built-in the spring-boot meta-data itself, but depend on IDE extra processing (IntelliJ handles it, but not Eclipse).

Based on these, I'm not fully convinced spring-boot metadata is the right path.
Instead how about some page on http://localhost/config to edit the application.properties based on ConfigDefinition ?

**Comment by xorye** [comment]
> Based on these, I'm not fully convinced spring-boot metadata is the right path.
> Instead how about some page on http://localhost/config to edit the application.properties based on ConfigDefinition ?

Hi, could you explain in a bit more detail about how this approach works? Our team is very interested in implementing application.properties completion support via a language server and would really benefit from a way to have some sort of metadata about config settings from build time and run time.

**Comment by rquinio** [comment]
@xorye My vague idea related more to https://github.com/quarkusio/quarkus/issues/447 and [this early discussion](https://groups.google.com/forum/#!searchin/quarkus-dev/starter.quarkus.io%7Csort:date/quarkus-dev/-Iyg2PkAbU4/AObdcyqHAAAJ) about the capabilities of a starter.quarkus.io deployed via quarkus:dev - i.e. to be able to edit application.properties from a UI

The idea of quarkus:dev acting as a language server for application.properties is exotic though :)

**Comment by xorye** [comment]
@rquinio thank you for getting back to me!

> The idea of quarkus:dev acting as a language server for application.properties is exotic though :)

That's quite interesting, we actually haven't really explored that option.

I should have explained in more detail, we are interested in creating a VSCode extension for Quarkus development, where VSCode connects to a language server (that we'd implement ourselves) that provides `application.properties` completion and other useful features. We are in early stages at the moment. If there was a maven/gradle plugin that we could invoke, that dumped all the metadata into a file, that would be very helpful.

> This is a big limitation when 90% of Quarkus config applies at build time !

Does this mean 90% of the Quarkus config are from runtime scoped dependencies, that the classpath at build time doesn't have access to?

**Comment by fbricon** [comment]
Here's a Quarkus LS in action in Red Hat's upcoming [vscode-quarkus](https://github.com/redhat-developer/vscode-quarkus/blob/master/CONTRIBUTING.md):

![vscode-quarkus](https://user-images.githubusercontent.com/148698/63166320-5ba3c980-c02e-11e9-82af-55dabf350d73.gif)


Because quarkus (extensions) have no metadata to read -yet-, we basically index the jars with JDT (via a jdt.ls/vscode-java extension).

This is very much WIP, but if you want to try it and give some feedback, you can install the vsix from https://download.jboss.org/jbosstools/vscode/snapshots/vscode-quarkus/?C=M;O=D (HTTP server is misconfigured so `save link as...`)

**Comment by maxandersen** [comment]
I consider this done as relased in vscode and will be in other IDE's shortly. reopen if not :)

**Comment by angelozerr** [comment]
@maxandersen even if we have managed Quarkus properties with JDT LS, I think it should be very good if each extension could provide those properties because:

 * it will avoid scanning classes from JAR to collect Quarkus properties and will improve performance: reading a JSON file from a JAR should be more performant than scanning classes from JAR.
 * we have re-developed the Quarkus properties generation name in JDT LS. If Quarkus change their strategy to generate name, JDT LS Quarkus extension will outdated.

Now we have implemented all features for managing Quarkus properties (completion, validation, go to definition) we have a clear idea what we need. Here a JSON sample file that we use to collect Quarkus properties https://github.com/redhat-developer/quarkus-ls/blob/master/quarkus.ls/com.redhat.quarkus.ls/src/test/resources/com/redhat/quarkus/services/all-quarkus-properties.json

```json
{
			"propertyName": "quarkus.datasource.driver",
			"type": "java.util.Optional\u003cjava.lang.String\u003e",
			"docs": "The datasource driver class name",
			"extensionName": "quarkus-agroal",
			"location": "C:/Users/azerr/.m2/repository/io/quarkus/quarkus-agroal/0.21.1/quarkus-agroal-0.21.1.jar",
			"source": "io.quarkus.agroal.runtime.DataSourceBuildTimeConfig#driver",
			"required": false,
			"phase": 2
		}
```

`location` could be omitted. The other information are important to manage correctly completion, validation, hover and find definition.

So please reoepn this issue.

**Comment by dmlloyd** [comment]
Yet another descriptor eh?

I was thinking we could probably replace 80% or more of extension descriptor metadata by using Jandex instead...

**Comment by angelozerr** [comment]
@dmlloyd you mean that our jdt ls extension should use jandex? If it that how to do that? I have not found some index files in the quarkus extension jar?

Thanks for your help!

**Comment by dmlloyd** [comment]
Not at all.  It was purely a side-band comment to @gsmet and @maxandersen.

**Comment by maxandersen** [comment]
@angelozerr I'm not sure I follow what your collection of metadata has to with open this issue - aren't you talking about a new feature suggestion in your comment ? 

On first glance I'm not sure why the extensions would have that json info bundled as you already can locate the info and can cache the data. 

@dmlloyd if I missed we actually have the metadata stored somewhere else do tell - I hate unnecessary redundancy ;)

**Comment by angelozerr** [comment]
> @angelozerr I'm not sure I follow what your collection of metadata has to with open this issue - aren't you talking about a new feature suggestion in your comment ?

No I'm talking about metadata required by IDE to manage completion, hover, validation and go to definition feature inside an IDE.  

> On first glance I'm not sure why the extensions would have that json info bundled as you already can locate the info and can cache the data.

Indeed we have done that with JDT LS extension, but it requires to scan all classes from all JAR of the classpath (the first time before caching it) and the thing which is very annoying is that we have re-develop the generation of Quarkus property generation from a given class and field. 

In IJ context , they need to re-develop this Quarkus property generation.

If we could just loop for each JAR of classpath and load just a simple JSON file which contains the Quarkus properties which belong to the JAR it should be very nice.

**Comment by maxandersen** [comment]
a jandex  approach here might not be a bad idea for you to share code, but please open an issue and lets discuss that in isolation/separation from this already done issue.
