### ISSUE TITLE
Add the ability to change the scope (and maybe other attributes) of beans

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#16572]
## Description

Parts of the build may for some reason want to change the scope of a bean. 
Currently there is no built in way to do this - one would need to manually hack together some annotation transformer related changes

**Comment by glefloch** [comment]
I saw the code in the `quarkus-junit5-mockito` module that replace `@Singleton` by `@ApplicationScope` for mocked bean and saw the reference to this issue.
 
I was thinking of introducing a new `MultiBuildItem` that would reference the class of the bean to convert, the scope to remove and the expected scope. Then in a build step, get all those build items and applying transformation using an `AnnotationsTransformerBuildItem` what do you think of that implementation?

**Comment by manovotn** [comment]
Are you looking for a bean attribute change that would happen later down the line (e.g. standard CDI can either manipulated annotated types or later on Bean objects themselves)? Otherwise it just sounds like a twist on annotation transformation meaning that other transformations coming after yours might still override your changes.

> I was thinking of introducing a new MultiBuildItem that would reference the class of the bean to convert, the scope to remove and the expected scope. Then in a build step, get all those build items and applying transformation using an AnnotationsTransformerBuildItem what do you think of that implementation?

From a user perspective, what's the difference between writing that and an annotation transformer?
Note that bean has more types - is the class you suggest to reference a type of bean (and therefore potentially altering multiple beans) or is it a bean created from that specific type?

**Comment by glefloch** [comment]
Right, I think the initial use case was to replace a `@Singleton` scope by `@ApplicationScoped` in order to be able to mock that bean in tests. 
As you mentioned, it can be done using an annotation transformer, here the goal could be to include that transformer in quarkus to avoid having to rewrite it.

**Comment by geoand** [comment]
I think we can close this as it sounds to powerful to put in users hands in the general case. An extension can easily do it if necessary

**Comment by manovotn** [comment]
If Quarkus, once on EE 10 deps, decides to support CDI Lite extension model, all of this can be done in a standardized way. However, it still entails some form of an extension :)
