### ISSUE TITLE
Native compilation doesn't like space in project directory

### ISSUE THREAD

**Issue by jcordes73** [quarkusio/quarkus#1673]
When creating a project directory with a space in it, native compilation fails, see steps to reproduce below:

mkdir "dir with space"
cd dir\ with\ space/
mvn io.quarkus:quarkus-maven-plugin:0.12.0:create \
    -DprojectGroupId=quarkus.io \
    -DprojectArtifactId=space-quickstart \
    -DprojectVersion=1.0-SNAPSHOT \
    -DclassName="io.quarkus.SpaceResource"
mvn compile quarkus:dev
mvn package -Pnative

The following fixes the issue:

mv dir\ with\ space/ dir_with_space/

**Comment by dmlloyd** [comment]
This seems related to #1402/#1607/#1438/#1030/etc.

**Comment by rsvoboda** [comment]
The first error is `Error: Class initialization failed: io.quarkus.undertow.runtime.graal.URLResourceSubstitution$ResourceInfo`
Caused by: `java.io.FileNotFoundException: /Users/rsvoboda/tmp/dir%20with%20space/target/lib/io.smallrye.smallrye-config-1.3.5.jar (No such file or directory)` in my case.

I see same error when the root directory is named:
 * app dir ect ory
 * app#dir
 * žluťoučký-kůň
 * app!@#%dir ect ory
 
For the following cases I have successful run of compilation + dev mode + native build
 * app@dir 
 * app(dir)ectory

With `app?dir` case I don't get through package phase
```
14:55:46 [INFO] 
14:55:46 [INFO] --- quarkus-maven-plugin:999-SNAPSHOT:build (default) @ space-quickstart ---
14:55:46 [INFO] ------------------------------------------------------------------------
14:55:46 [INFO] BUILD FAILURE
14:55:46 [INFO] ------------------------------------------------------------------------
14:55:46 [INFO] Total time: 7.579 s
14:55:46 [INFO] Finished at: 2019-03-27T14:55:46+01:00
14:55:46 [INFO] ------------------------------------------------------------------------
14:55:46 [ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:
  build (default) on project space-quickstart: Failed to build a runnable JAR: 
  Failed to build a runner jar: URI has a query component -> [Help 1]
```

**Comment by dmlloyd** [comment]
Again it's going to be wrong URI handling somewhere.

Here's the rules for class paths:

* A `MANIFEST.MF` `Class-Path` is a list of relative URIs.  A relative URI is *not* a relative directory, it's a URI without a scheme (see [the RFC](https://tools.ietf.org/html/rfc3986#section-4.2)).
* Since it's a space-separated list, the "raw" URI must be used (see [the JavaDoc for `URI.toAsciiString()`](https://docs.oracle.com/javase/10/docs/api/java/net/URI.html#toASCIIString()) as this will URI-encode and UTF-8 encode the whole URI).
* The JDK forbids usage of URIs that are not in the `file` scheme.  Some JDKs don't allow URIs with *any* scheme including `file`.  Make sure the URI is relative before encoding it.  I think that simply using [the *raw* path](https://docs.oracle.com/javase/10/docs/api/java/net/URI.html#getRawPath()) will just about always suffice.
* When emitting URIs, use [`Path.toUri()`](https://docs.oracle.com/javase/10/docs/api/java/nio/file/Path.html#toUri()).  If you're just pulling the raw path, no further conversion is necessary.
* When decoding URIs back to `Path`, use [`Paths.get(URI)`](https://docs.oracle.com/javase/10/docs/api/java/nio/file/Paths.html#get(java.net.URI)).  Nice and easy.
* When you need a `File`, use [`Path.toFile()`](https://docs.oracle.com/javase/10/docs/api/java/nio/file/Path.html#toFile()).

If you are not adhering to these rules, *please* include copious documentation explaining your rationale!

I'll update all related issues to reference this comment.

**Comment by machi1990** [comment]
> This seems related to #1402/#1607/#1438/#1030/etc.

Can this issue be closed? Looks like all the related issues have been closed.

**Comment by dmlloyd** [comment]
Yes, I think so.  Thanks.
