### ISSUE TITLE
Being able to fix the Postgres listening port property with DevServices

### ISSUE THREAD

**Issue by agoncal** [quarkusio/quarkus#16768]
## Description

When you use DevServices in Dev and Test mode to startup a Postgres database, the listening port is random and you get a different one each time you startup or execute the tests (eg. `localhost:55046/default`, `localhost:55048/default`, etc.). But in development mode, it's sometimes useful to access the database. And to get the port, you need to check the Dev UI to know this random port.

Having a random port in test, is fine, but in dev it would be nice to have to fix the port number (using a property).

* Zulip Discussion : https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Fix.20the.20Postgres.20listening.20port.20property.20with.20DevServices

**Comment by maxandersen** [comment]
Not sure what the good way would be here. 

With contionous testing you wouldn’t want random ports as otherwise there would be conflicts. 

So it would only be the first one that would be “fixed”.

**Comment by agoncal** [comment]
I'm more interested in having a fix port in `%dev`. Like all the `devservices` property, it won't be available in production, and then you could have either `%dev%.quarkus.datasource.devservices.port=5432` only for dev, but if you have the property for `%test`, then, as you say, only the first one would be fixed.

**Comment by gsmet** [comment]
@stuartwdouglas I don't know if you have seen this one but I think it makes a lot of sense? If you agree it does, I can work on it.

**Comment by stuartwdouglas** [comment]
Because we are using testcontainers this is not as simple as it sounds, even though it makes sense, as testcontainers always picks a random port. I think the best you could do is open a socket on the 'fixed' port, and just use it to manually port forward to the underlying instance. 

We may end up needing to do our own stuff rather than continuing to use testcontainers, another use case I have that they don't support is persistent containers, where you create a container with a specific name (based on the project and datasource), leave it running and just re-connect to it if it is already started.

**Comment by gsmet** [comment]
Something like https://github.com/testcontainers/testcontainers-java/blob/master/core/src/main/java/org/testcontainers/containers/FixedHostPortGenericContainer.java wouldn't work?

**Comment by stuartwdouglas** [comment]
Looks like you probably could do it if you override the configure() method in PostgreSQLContainer and add a call to addFixedExposedPort.
