### ISSUE TITLE
Kafka / Avro class loader issue

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#16810]
## Describe the bug

Suddenly beefy-ts/reactive-kafka stop working. Looks that we have a problem related to class loading order.

[Scenario](https://github.com/quarkus-qe/beefy-scenarios/tree/main/301-quarkus-vertx-kafka)
**How to reproduce:** `mvn clean test -pl 301-quarkus-vertx-kafka`
**Quarkus Version:** Upstream
**Error message:** `class io.quarkus.qe.kafka.StockPrice cannot be cast to class org.apache.avro.specific.SpecificRecord`

Patch: Add the following property to your application.properties `quarkus.test.flat-class-path=true`

**Comment by Ladicek** [comment]
This is because when locating the Avro schema of the generated class, Avro tries to load the generated class first from the class loader that loaded Avro itself. Only if that fails does Avro consult the TCCL. In the Quarkus architecture, Avro is loaded by the Quarkus base CL, which has the JDK app CL as a parent -- so it can always find the generated classes, because they are on the JVM classpath. Which means that when Avro tries to load the generated class, which is an application class, it is loaded by the Quarkus base CL, instead of the Quarkus application CL.

The generated class is also loaded by the Quarkus app CL, as part of the regular application. So we have it loaded twice, in two different class loaders.

More discussion: https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Avro.20vs.2E.20continuous.20testing
