### ISSUE TITLE
Keycloak Devservices

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#17217]
We should add support for Keycloak devservices in 2.0, but we need to figure out exactly how this should work. 

Requirements:
- It should be possible to use keycloak with zero config for dev and tests. This will have a default realm with an admin and a normal user. 
- dev/test users and roles can be specified in application.properties for simple use cases
- keycloak json file can be used for a custom realm configuration
- Defaults should align with RH SSO?

What else do we need to consider? Ideally users will be able to just add the extension and start using OIDC straight away.

**Comment by stuartwdouglas** [comment]
CC @sberyozkin @pedroigor

**Comment by sberyozkin** [comment]
@stuartwdouglas This set of requirements looks complete for a start - we'd use a KC Admin API to prepare a default realm with users/clients/roles/etc.
- At the Quarkus level we support SPAs acquiring KC tokens and sending them to Quarkus as bearer tokens
- User authentication using the code flow

So, perhaps we can follow up with
- Have a JWT token test console - a token is requested from KC and pasted for the user to try sending it to Quarkus
- Let users sign in to Quarkus via Keycloak - in this case nothing would need be done, it should just work 

I need to finish a few open issues so unlikely I can do something for Alpha3 but will prioritize to get at least the initial set of requirements done for .Aplha4/etc. I'll likely need some UI expert support - I can only do HTML combo boxes :-)

**Comment by pedroigor** [comment]
@stuartwdouglas @sberyozkin The requirements look good. Some additional comments:

* Clients. The client is necessary to enable the app to access Keycloak. Depending on the `oidc` configuration, we create either a public or confidential client. Here, I think we should be able to infer both the client id and secret from the config. In the case, of multi-tenancy, the same thing but iterating over all tenants config.

* Users. Perhaps we just create a `myuser` with some fixed password and let people create additional ones via admin console? My point being that a basic user should be more than enough to get started and additional config (like roles) to the user is better done through the admin console. Which I think is easier enough to do.

* KC Features. In KC, you can enable/disable features that are in tech-preview/experimental. We should probably have some setting to bootstrap the container and enable features.

* Keycloak.X. Perhaps use Keycloak.X image to run the container?

* RH-SSO. The same we do for KC should be fine for RH-SSO.

/cc @stianst.

**Comment by stuartwdouglas** [comment]
I think we need more than one fixed use. We can't rely on the admin console for anything, as KC is restarted when Dev mode is restarted, so any changes would be lost.

**Comment by sberyozkin** [comment]
I'd probably leave the multi-tenancy out of it for now - IMHO we can look at it once a default tenant mode is supported well. 

But as Pedro said, should we just have an initial OIDC client(s) and user(s) created ? Let a user enter a 1) realm name 2) client id, secret 3) user name/roles - and we'd create it in KC, generate correct `application.properties`.

What will be created in the admin console can be exported as the realm properties so what Stuart suggested (optional realm configuration input) would ensure those admin console settings are available after a restart - i.e when the Dev Services start, `realm.json` input will be checked. The user would need to make sure the realm is exported from the admin console - but it is a basic KC console action. Otherwise we'd need to have Dev Service Keycloak console support what KC Admin console can do and it is not quite realistic.

**Comment by pedroigor** [comment]
@sberyozkin @stuartwdouglas I'm OK supporting JSON file, although we can't expect people writing their one because our schema is just insane :) But use export to get one. And that means a few additional steps before using dev services. Perhaps not the quickest way to get started on quarkus-oidc to protect an application.

That said, I would then agree with you to create roles too based on the application properties. Most people do RBAC.

**Comment by sberyozkin** [comment]
@pedroigor Sure, makes sense. It would start without `realm.json`, definitely, but the users would be advised to save whatever they have followed up with in the KC Admin console with via an export action. But having `realm.json` would not be a pre-requisite

**Comment by stianst** [comment]
We'll quickly get into a situation where users will need to configure something more than just a plain client and a user. A realm export/import is far from ideal right now, but probably the best we can do right now. It's something we need to improve in Keycloak regardless. Another option may also be to let folks configure it with code and KC admin client.

**Comment by sberyozkin** [comment]
FYI, I've started prototyping some initial code (by copying it from the Redis client and also Vault Dev Services PRs) - at the moment I'm doing it similarly to those PRs inline with `quarkus-oidc` - but I think we'd eventually need to have a dedicated `dev-services-keycloak` extension as indeed it would be 100% focused on making it optimal for the KC users with the extra dependencies required such as KC Authz Client, etc. It would be similarly how Stuart did for the specific databases
