### ISSUE TITLE
gRPC - generate a Mutiny service class to simplify UX

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#17229]
Currently, a gRPC service is defined as a CDI bean (annotated with `@GrpcService`) and the bean class must extend a generated implementation base class, e.g. `public class HelloService extends GreeterGrpc.GreeterImplBase {}` or the Mutiny version: `public class HelloService extends MutinyGreeterGrpc.GreeterImplBase {}`. However, it's not very clear (esp. for a beginner) which class needs to be extended. Note that the impl base is a nested static class of the generated `Grpc` class.

It might make sense to generate a _top-level_ class like this:
```java
public abstract class GreeterService implements BindableService {

    public abstract Uni<HelloReply> sayHello(HelloRequest request);

    @Override
    public final ServerServiceDefinition bindService() {
        // TODO code copied from examples.MutinyGreeterGrpc.GreeterImplBase.bindService()
        return null;
    }
}
```
or even 
```java
public abstract class GreeterService extends MutinyGreeterGrpc.GreeterImplBase { }
```
That way we can instruct user to extend a class named `{YourServiceNameFromTheProtoFile}Service`.

**Comment by mkouba** [comment]
CC @Ladicek

**Comment by Ladicek** [comment]
I thought about generating an interface because that would make it super straightforward to understand what you need to implement. We could then wire it with the generated superclass in some way.

(For example, if the user-written class doesn't extend anything, we could just transform its bytecode to extend the generated superclass, which should be fine, as the interface would prescribe the same methods the superclass has :-) )

**Comment by mkouba** [comment]
Well, if we choose option 1 - `class GreeterService implements BindableService` - then it's also very clear because you need to implement the abstract methods. Of course we could do all kinds of magic but I'd rather avoid this kind of class transformation...

**Comment by Ladicek** [comment]
There a couple of options how to wire things. Another one is, in the generated class, look up the implementation of the interface and forward method invocations to it.

What I'd be more interested in is, how to provide the best user experience :-)

**Comment by mkouba** [comment]
> What I'd be more interested in is, how to provide the best user experience :-)

In my opinion, we should not try to hide everything from the user (aka "too much magic may hurt"). It should be clear 1) what class/interface to extend/implement, 2) which service methods to implement. In fact, since we control the `MutinyGrpcGenerator` we could just rename the `MutinyGreeterGrpc.GreeterImplBase` and extract it to a top-level class and be done.

**Comment by cescoffier** [comment]
An interesting thing in gRPC: implementations do not have to implement all the methods.... gRPC has a specific error for this case. Now, I'm would not mind not supporting this rather odd case, or make the user explicitly throw an `UnsupportedOperationException` (which we would map to the gRPC error). 

In terms of user-friendliness, I would go for an interface. First, it allows implementing multiple ones, and it looks more common than extending an abstract class.

**Comment by Ladicek** [comment]
Right. I wanted to add one more thing. When I said "the best user experience", I wasn't talking about magic (though my previous implementation suggestion definitely was "magic" -- though I acknowledged that it isn't universal, so it's basically useless, because another one needs to be devised anyway). I was talking about proper abstraction. Inheriting from an abstract class that exposes a ton of implementation details -- that is not an abstraction I'd myself like to use. Also, I personally believe that frameworks should never require subclassing a framework-provided class. Inheritance is scarce, you can only have one parent. If we required implementing an interface, that would give users the freedom to inherit from their own class, which is always nice.

(One other thing. I personally like contract-first development, or at least the idea :-), but if we wanted code-first too, maybe we could use Infinispan's Protostream. Too bad there's virtually zero documentation for it.)

**Comment by Ladicek** [comment]
I don't know what's `BindableService`, but assuming it's nothing users have to implement, can you, instead of transformation, _generate_ a bean that would delegate to the user-provided bean, and implement this nonsense? :-) It could also catch the `UnsupportedOperationException` that @cescoffier describes above for non-implemented RPCs? Sorry if I'm making it more complex than it has to be, I didn't have time to play with gRPC myself yet.

**Comment by mkouba** [comment]
> _generate_ a bean that would delegate to the user-provided bean, and implement this nonsense?

That's also an option, although a bit more difficult to implement ;-).  It could be something like:
```java
// generated grpc interface
public interface GreeterService {
    Uni<HelloReply> sayHello(HelloRequest request);
}

// generated grpc bean used by grpc internals
@Singleton
public class GeeterBindableService extends MutinyGreeterGrpc.GreeterImplBase implements BindableService {
 
  @Inject
  GreeterService greeterService;

  public Uni<HelloReply> sayHello(HelloRequest request) {
     try {
        return greeterService.sayHello(request);
      } catch (UnsupportedOperationException e) {
         throw new io.grpc.StatusRuntimeException(io.grpc.Status.UNIMPLEMENTED);
      }
  }
  
  @Override
  public final ServerServiceDefinition bindService() {
        // TODO code copied from examples.MutinyGreeterGrpc.GreeterImplBase.bindService()
        return null;
  }
}

// user-defined grpc bean, I'm not sure what name convention should we use here...
@GrpcService
public class Greeter implements GreeterService {

  Uni<HelloReply> sayHello(HelloRequest request) {
     throw new UnsupportedOperationException();
  }
}

```

> Sorry if I'm making it more complex than it has to be, I didn't have time to play with gRPC myself yet.

That's OK. We should come with the best possible API so that we don't need to change it for quarkus 3.0 :D.

**Comment by Ladicek** [comment]
If `MutinyGreeterGrpc.GreeterImplBase` already includes an implementation of `bindService`, we would just inherit it?

I'm thinking ideally we would get rid of the `MutinyGreeterGrpc.GreeterImplBase` stuff (which we control, right?), but that would be a breaking change I guess. (Not actually get rid of it. Just generate the bean directly.)

**Comment by michalszynkiewicz** [comment]
So we'd create/register as a bean the `GreeterBindableService` only if user defined `Greeter`?

We could have default implementations for all interface methods, that throws `UnsupportedOperationException`, this way the users would just omit stuff they are not interested in.

**Comment by Ladicek** [comment]
That would certainly be an option, but wouldn't you in 99.9% of cases want to implement all of the interface's methods?

**Comment by mkouba** [comment]
> If `MutinyGreeterGrpc.GreeterImplBase` already includes an implementation of `bindService`, we would just inherit it?

You're right, I missed this fact yesterday but realized this before I fell asleep ;-)

> I'm thinking ideally we would get rid of the `MutinyGreeterGrpc.GreeterImplBase` stuff (which we control, right?), but that would be a breaking change I guess. (Not actually get rid of it. Just generate the bean directly.)

Yes, that would be a breaking change so -1.

**Comment by mkouba** [comment]
> We could have default implementations for all interface methods, that throw `UnsupportedOperationException`, this way the users would just omit stuff they are not interested in.

I wouldn't do that because as @Ladicek mentioned in most cases a user wants to implement all methods.
