### ISSUE TITLE
import.sql does not seem to be listen to for creation and change

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#1734]
```
mvn quarkus:add-extension -Dextensions="quarkus-jdbc-postgresql,quarkus-hibernate-orm-panache"
```

```
quarkus.datasource.url: jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver: org.postgresql.Driver
quarkus.datasource.username: sarah
quarkus.datasource.password: connor

# drop and create the database at startup (use `update` to only update the schema)
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
```

```
@Entity
public class HelloMessage extends PanacheEntity {
    public String message;
    public String lang;

    public static HelloMessage findByLang(String lang) {
        return find("lang", lang).singleResult();
    }
}
```

```
mvn compile quarkus:dev
```

Then add `import.sql` with 

```
DELETE FROM HelloMessage
INSERT INTO HelloMessage (id, message, lang) VALUES (1, 'Hola', 'es')
```

And see `HelloMessage.find("lang", "es").singleResult();` crash

Then stop and restart `mvn compile quarkus:dev` and change import.sql

```
DELETE FROM HelloMessage
INSERT INTO HelloMessage (id, message, lang) VALUES (1, 'Hola', 'es')
INSERT INTO HelloMessage (id, message, lang) VALUES (2, 'Bonjour', 'fr')
```

and see `HelloMessage.find("lang", "fr").singleResult();` crash

**Comment by Sanne** [comment]
Ok so this works now, but we're in trouble with other "flavours" of the same issue:

# Deleting the file
If the `import.sql` existed initially, but then it's deleted: the last content of the script keeps being applied for subsequent imports in the same "dev" session as it's actually never removed from the target.

# Non-standard named files
So Guillaume fixed this by registering _specifically_ the `import.sql` resource name so that Quarkus:dev will be watching for this specific file. However we also support different file names, so it won't work for alternative file names, and won't work either if someone switches to a different resource name on the fly.

I think both cases could be solved but they'd be fairly more complex.
