### ISSUE TITLE
Adding @Gauge annotated method in ApplicationScoped bean causing error in bean instantation

### ISSUE THREAD

**Issue by volalex** [quarkusio/quarkus#1742]
When I tried to add `@Gauge` metric to my app, it failed to start with 

```
Caused by: java.lang.NoSuchMethodError: WorkerProvider_Bean: method <init>()V not found
	at io.quarkus.arc.setup.Default_ComponentsProvider.getComponents(Unknown Source)
	at io.quarkus.arc.ArcContainerImpl.<init>(ArcContainerImpl.java:95)
	at io.quarkus.arc.Arc.initialize(Arc.java:34)
	at io.quarkus.arc.runtime.ArcDeploymentTemplate.getContainer(ArcDeploymentTemplate.java:43)
	at io.quarkus.deployment.steps.ArcAnnotationProcessor$build5.deploy(Unknown Source)
````

But this class definetly have a no-args constructor

When I remove `@Gauge` annotated method application starts without any issue

**Comment by geoand** [comment]
I can reproduce this, it's actually very simple to do so. Simply create a project with the maven plugin, add the `quarkus-smallrye-metrics` dependency and annotation the method of the `hello` method with `@Gauge`.

Note that things work as expected when `@Timed` or `@Counted` is used.

I believe that the route case is the fact that the `@Gauge` annotation is not meta-annotated with `@Inherited` - which cases Arc to not include it as part the `BeanDeployment`'s `interceptorBindings` (both `@Timed` and `@Counted` are properly meta-annotated with `@Inherited`). 

@kenfinnigan @jmartisk do you have further insights on this?

**Comment by jmartisk** [comment]
The problem occurs if you have a bean (it doesn't need to be ApplicationScoped) which contains a `@Gauge` as the only metrics annotation. If you add any other metric annotation (like `@Counted`) anywhere in the class, it will start working. This can be used as a workaround.

I think the problem stems from the fact that adding a `@Gauge` annotation binds a `MetricInterceptor` to only the constructor of the bean that contains it, and `ComponentsProviderGenerator` contains a check for an empty list of `interceptedMethods` which stays empty if only the constructor is being intercepted (if you add any other metric annotation on a method, that method will become intercepted so the list will not be empty). The check should not ignore beans which have only their constructor intercepted.

I sent PR https://github.com/quarkusio/quarkus/pull/1784 which should fix it

**Comment by geoand** [comment]
@jmartisk do you not think that the `@Gauge` annotation itself is problematic like I described above?

**Comment by jmartisk** [comment]
@geoand No, I don't think it has anything to do with it. The fact that a Gauge annotation is not inherited is a design decision in the MP Metrics spec. And there is no class inheritance needed to reproduce this issue.

**Comment by geoand** [comment]
I could obviously be wrong @jmartisk since this is not my wheelhouse, but when I was debugging this issue I saw that https://github.com/quarkusio/quarkus/blob/master/independent-projects/arc/processor/src/main/java/io/quarkus/arc/processor/BeanDeployment.java#L351 was not picking up the interceptor bindings for `@Gauge`, while it was for the other MP Metrics annotations - and my guess is that that happens because of the lack of the `@Inherited` annotation.

**Comment by jmartisk** [comment]
@geoand that's because a gauge doesn't have its own interceptor binding annotation (unlike the others), it is bound to the lifecycle of the bean using the vendor-specific `io.smallrye.metrics.interceptors.MetricsBinding`. Look into https://github.com/eclipse/microprofile-metrics/tree/1.1.1/api/src/main/java/org/eclipse/microprofile/metrics/annotation see the `@Gauge` annotation itself it not an interceptor binding, unlike for example `@Counted`

**Comment by geoand** [comment]
Got, thanks for the explanation @jmartisk!
