### ISSUE TITLE
Continuous Testing fails when reading file

### ISSUE THREAD

**Issue by kwakiutlCS** [quarkusio/quarkus#17543]
## Describe the bug
When using continuous testing, reading some expectation data from a file results in failed test, while the test succeeds with mvn verify.

### Expected behavior
Continuous test has the same test results as mvn verify, when running mvn quarkus:dev and mvn quarkus:test

### Actual behavior
mvn quarkus:dev and mvn quarkus:test result in failed tests.

## To Reproduce
https://github.com/kwakiutlCS/vigilant-funicular

1. run mvn verify (test should pass)
2. run mvn quarkus:test (test fail with FileNotFoundException)
3. checkout to last but one commit (no data read from file) mvn quarkus:test succeeds

### Quarkus version or git rev
2.0.0.CR2, but behaviour is the same with previous 2.0.0 releases

**Comment by geoand** [comment]
Thanks for reporting!

This is due to the fact that during continuous testing, the dev/test jar is run from inside `target` while in surefire it is run from the project root.
@stuartwdouglas how would you like to handle this? 
I don't think that running the jar from the project root is an option, I am afraid various dev-mode things would break.
Perhaps we could should provide some kind of utility for reading file system files in tests?

**Comment by stuartwdouglas** [comment]
I don't think there is anything we can do about this, I would suggest just loading it from the ClassPath rather than using Paths.get() as a workaround/more reliable way to handle this.

**Comment by kwakiutlCS** [comment]
Thank you for explaining it.
