### ISSUE TITLE
Adjust destroy and beforedestroy events for transactional context to fit better with CDI spec

### ISSUE THREAD

**Issue by ochaloup** [quarkusio/quarkus#17658]
The `@Transactional` context lifecycle events `@Destroyed` and `@BeforeDestroyed`are currently fired at time before and after transaction manager calls `commit/rollback`. This is more or less good but it's not what the spec says - https://jakarta.ee/specifications/cdi/2.0/cdi-spec-2.0.html#builtin_contexts
Especially for the `@BeforeDestroyed` event there is said that it should be fired `an event with qualifier @BeforeDestroyed(X.class) when a custom context is about to be destroyed`. But when it's fired at before the `Transaction.commit` is executed then there is quite a bit of time when transaction is still active - https://github.com/eclipse-ee4j/jta-api/blob/initial-contribution/src/main/java/javax/transaction/TransactionScoped.java#L31 - i.e. the transaction manager processes the commit which takes tame. The before destroy event should be better emitted at time just before the context is really destroyed.

With this change it would be good to apply adjustment which was brought by PR https://github.com/quarkusio/quarkus/pull/17544 to handling of events for the core CDI contexts. The standard CDI event activates the request context always. For the events that activate/deactivate the context is such request context activation unwanted and it should not be activating the request context at time being fired (https://github.com/quarkusio/quarkus/pull/17544/files#diff-06bb4f2eae4445212128b4f566fc42949f578c01b721589280cf9991a59ffb13R177)

/cc @manovotn

**Comment by mkouba** [comment]
> With this change it would be good to apply adjustment which was brought by PR #17544 to handling of events for the core CDI contexts.

We have to think about it. Like I mentioned in https://github.com/quarkusio/quarkus/pull/17544#issuecomment-851371920 the only problematic part is probably `@Initialized(ApplicationScoped.class)` (and obviously `@Initialized(RequestScoped.class)`). It shoud not be a problem for other contexts. I know that it's not very consistent but the spec is IMO not very consistent either. E.g. the request context must be active during notification of an _asynchronous_ observer method, but not during a notification of a _sync_ observer... most probably because it was expected that the request context is always active there. Moreover, it must be active during `@PostConstruct` callback of any bean. Likewise, it's not guaranteed that an `@Initialized(X.class)` event will only be fired by relevant context impl, it's a regular event, can be fired by anyone at any time...

**Comment by manovotn** [comment]
> We have to think about it. Like I mentioned in #17544 (comment) the only problematic part is probably @Initialized(ApplicationScoped.class) (and obviously @Initialized(RequestScoped.class)). It shoud not be a problem for other contexts. 

Actually, it was me who told @ochaloup to include this change.
I think we should be consistent and behave equally for all `@Initialized/@Destroyed` events. And I think @Ladicek was of the same opinion :)

**Comment by Ladicek** [comment]
Agree we should be consistent about how we activate the request context for `@Initialized`/`@BeforeDestroyed`/`@Destroyed` events.

Furthermore, I beg to differ re

> I know that it's not very consistent but the spec is IMO not very consistent either. E.g. the request context must be active during notification of an asynchronous observer method, but not during a notification of a sync observer... most probably because it was expected that the request context is always active there. Moreover, it must be active during @PostConstruct callback of any bean.

The spec is quite explicit about all active contexts being propagated to sync observers, and actually across all method invocations that occur on the same thread (notification of sync observers is just that, a bunch of method calls that for inevitable reasons cross the CDI container code). That is, if request context is not active at the time the event is fired, it shouldn't be active in the observer. Which IMHO makes complete sense.

On the other hand, for methods (such as `@PostConstruct` callbacks or async observers) invoked by the CDI container, there is no set of active contexts that could possibly propagate. With some poetic license, I'd say that these invocations just happen out of the blue. The CDI spec has to come up with some "sensible default". I may like it or not, but that doesn't make it comparable to the previous case. They are just very different beasts by nature.

**Comment by mkouba** [comment]
> I think we should be consistent and behave equally for all `@Initialized/@Destroyed` events. And I think @Ladicek was of the same opinion :)

I'm aware of this and still tend to disagree ;-). Some of the reasons are mentioned above. But I'm open for further discussions...

**Comment by mkouba** [comment]
> That is, if request context is not active at the time the event is fired, it shouldn't be active in the observer. Which IMHO makes complete sense.

How does it correspond to the fact the request context must be always active for async observers?

> On the other hand, for methods (such as @PostConstruct callbacks or async observers) invoked by the CDI container, there is no set of active contexts that could possibly propagate.

Not really. The `@PostConstruct` callbacks can be invoked "with active contexts" (as defined by the spec, i.e. active with respect to the current thread), e.g. for all `@RequestScoped` beans created for an HTTP request in a web app. AFAIK this "exception" was invented because it was practical to activate the request context for  `@PostConstruct` callbacks of `@ApplicationScoped` beans...

> They are just very different beasts by nature.

I tend to disagree. They have quite a few things in common, e.g. both can be invoked with and without active contexts in the background and for both of them it might be practical to activate the request context...

**Comment by Ladicek** [comment]
> How does it correspond to the fact the request context must be always active for async observers?

It doesn't, because I tend to think that async observers are very much different from sync observers. (I also tend to think that async observers should have never been added to CDI in the first place, but that's a different story :-) )

> The `@PostConstruct` callbacks can be invoked "with active contexts" (as defined by the spec, i.e. active with respect to the current thread), e.g. for all `@RequestScoped` beans created for an HTTP request in a web app. AFAIK this "exception" was invented because it was practical to activate the request context for `@PostConstruct` callbacks of `@ApplicationScoped` beans

I admit I got lost here, but I trust your understanding of CDI more than my own :-)

I guess the difference I'm trying to make is: code called directly or indirectly by application vs. code called purely by the CDI container. (Disregarding users that call code they shouldn't call, such as lifecycle callbacks or observer methods etc.) In the first case, there already is a set of active contexts, so the container shouldn't intervene. In the second case, the container has to invent something.

I of course realize that application code is typically also called by some container, so the difference isn't as clean as it should be, but hopefully you see what I mean. But if you say that this difference is artificial and doesn't really make sense in the overall CDI bigger picture, I'll trust your judgement :-)

**Comment by mkouba** [comment]
> I also tend to think that async observers should have never been added to CDI in the first place, but that's a different story :-)

Hehe, yes it's disputable...

> I admit I got lost here, but I trust your understanding of CDI more than my own :-)

Hey, this is great I don't need to use arguments anymore! :D

> In the first case, there already is a set of active contexts, so the container shouldn't intervene. In the second case, the container has to invent something.

Well, define the code called "purely by the CDI container". There is always some "entry point" (user request, scheduled method, etc.). And even this code runs in the set of active contexts (application, singleton, custom contexts, ...).

> but hopefully you see what I mean. But if you say that this difference is artificial and doesn't really make sense in the overall CDI bigger picture, I'll trust your judgement :-)

Yup, I guess that I get what you mean. Let's give it some time and continue with discussion...

**Comment by Ladicek** [comment]
> define the code called "purely by the CDI container"

Since there's no non-blocking crap in the picture, that is rather easy: code is called purely by the CDI container when there are no application stack frames on the call stack :-)

Yea I understand that this concept is somewhat hazy, because application code usually doesn't activate any contexts anyway, so why should there be a difference. I'll ponder over it some more, let's see if I can figure it out at least for myself :-)

**Comment by ochaloup** [comment]
After investigation of the current behaviour I tend to close this issue as not implementable.
The longer discussion on that the current place is not the perfect one but it's a feasible and the "only" possible is at PR: https://github.com/jbosstm/narayana/pull/1843#discussion_r639760178

The issue of the transaction processing is that the transaction context is a lazy created. When no transaction scoped bean exist then it's not created. When a transaction scoped bean is injected it's only attached to the current transaction in `get` method.
I.e. there is no explicit creation of the scope object at start of the transaction. This means that empty transaction context does not create any scope object. The events need to be fired for empty scope as well, when transaction is started/finished.

From the JTA perspective I tend to leave the events to be emitted where they are now.

I'm not sure how to understand the outcome of the discussion of the request scope while I consider that it should be left as it is.

If it so I will close this issue without a fix.
