### ISSUE TITLE
Handle @Any qualifier with MicroProfile Config bulk properties

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#17695]
## Description
While using `org.eclipse.microprofile.config.inject.ConfigProperties` in order to function properly while we @Inject configuration we need to append `javax.enterprise.inject.Any` qualifier annotation as well. Otherwise, we get an error:

Error example
```
Unsatisfied dependency for type io.quarkus.qe.config.AntagonistConfiguration and qualifiers [@Default]
        - java member: io.quarkus.qe.GreetingResource#antagonist
        - declared on CLASS bean [types=[java.lang.Object, io.quarkus.qe.GreetingResource], qualifiers=[@Default, @Any], target=io.quarkus.qe.GreetingResource]
        The following beans match by type, but none have matching qualifiers:
                - Bean [class=io.quarkus.qe.config.AntagonistConfiguration, qualifiers=[@org.eclipse.microprofile.config.inject.ConfigProperties(prefix = "antagonist"), @Any]]
```

It would be more convenient to leverage this for Quarkus to handle. In fact, I'm not sure if this can be an issue and/or if it should be resolved by Microprofile Config

## To reproduce
run: `mvn clean verify` in module
https://github.com/kshpak/beefy-scenarios/tree/feature/bulkprops/022-quarkus-properties-config-all

## Quarkus version
999-SNAPSHOT

**Comment by mkouba** [comment]
Well, the `org.eclipse.microprofile.config.inject.ConfigProperties` is a CDI qualifier so it makes sense that you need to declare `@Any` or `@ConfigProperties` (value is ignored because it's annotated with `javax.enterprise.util.Nonbinding`) on the injection point. In fact, you can do `@ConfigProperties AntagonistConfiguration antagonist`  in Quarkus, i.e. skip the `@Inject`.

Also the spec mentions this explicitly: https://github.com/eclipse/microprofile-config/blob/master/spec/src/main/asciidoc/configexamples.asciidoc#inject-the-bean-annotated-with-configproperties

Closing this issue. @kshpak Feel free to create a [MP spec issue](https://github.com/eclipse/microprofile-config/issues) to address your concerns.

CC @radcortez

**Comment by radcortez** [comment]
Like @mkouba said, MP `@ConfigProperties` is a Qualifier, so you need to use it at the injection point. If you prefer, you can use `@ConfigMapping` and only use `@Inject`.

Feel free to open an issue in MP Config, but I think we discussed this and the consensus of the group was to keep it as a qualifier.
