### ISSUE TITLE
KafkaStreams UncaughtExceptionHandler can only be set before starting the stream

### ISSUE THREAD

**Issue by ozangunalp** [quarkusio/quarkus#18018]
## Describe the bug
It is not possible to use KafkaStreams#setUncaughtExceptionHandler on the injected `KafkaStreams` instance because it is already started by the `KafkaStreamsProducer` managed by kafka-streams Quarkus extension.

### Expected behavior
The kafka-streams extension calls setUncaughtExceptionHandler with an instance of `StreamsUncaughtExceptionHandler` discovered in the application the before the start, much like StateListener and StateRestoreListener

Reported by @andrerigon

**Comment by andrerigon** [comment]
@ozangunalp sorry for the wait, I could only work on this today. I openned https://github.com/quarkusio/quarkus/pull/18379 for it. 

How do you recommend testing this? I notice that are no tests for the other listernes, since KafkaStreams doesn't allows inspecting the stream object after you configure it. A full blown integration test using _TopologyTestDriver_ might work, but will add considerable complexity.
