### ISSUE TITLE
Implement shared Redis Server with DevServices

### ISSUE THREAD

**Issue by machi1990** [quarkusio/quarkus#18029]
## Description

Ability to reuse a shared server launched by dev services across multiple Quarkus apps

## Implementation ideas

This should be label based discovery just like what we have for [Kafka](https://github.com/quarkusio/quarkus/pull/17837) and  [AMQP](https://github.com/quarkusio/quarkus/pull/17980)

**Comment by patrox** [comment]
@machi1990 I saw a related PR for label-based discovery for Kafka and I could work on this one.
Is that fine with you?

**Comment by machi1990** [comment]
@patrox thanks, yes that's fine with me. The label-based discovery is indeed the way to go here.

**Comment by stuartwdouglas** [comment]
@cescoffier and I have been talking about refactoring the label code to be more generic rather than something each extension has to implement, however I am not sure about when we will get to it. Just be aware that if you do a copy/paste of the Kafka label code depending on the timing it may end up needed to be changed to use our new generic discovery mechanism (if this goes in first then we would just update as part of implementing the generic discovery).

**Comment by patrox** [comment]
@stuartwdouglas Actually you are reading my mind - as I also noticed an opportunity to refactor this "label-based container discovery" code, so it can be easily re-used by other extensions which will be supporting shared containers based on dev services config.

Do you have any plans for when and how to do it? As I can also propose some potential solutions, as I will have a good chance to extract these common parts.

For now, I'm basing my work on [Kafka|https://github.com/quarkusio/quarkus/pull/17837] change - as soon as it will work, I can refactor it as well.

**Comment by stuartwdouglas** [comment]
I haven't really thought about the specifics too much. I would probably create a new module in the extensions/devservices directory to hold common code, and then just move as much code as you can into there for now. That would be a good start and if we want to do any more we can build on it later.

**Comment by machi1990** [comment]
Closed by https://github.com/quarkusio/quarkus/issues/18181

Thanks @patrox.
