### ISSUE TITLE
Can't mock ConfigMapping interface

### ISSUE THREAD

**Issue by ivannov** [quarkusio/quarkus#18031]
## Describe the bug

I am using a `@ConfigMapping` annotated interface to provide external configuration:

```java
@ConfigMapping(prefix = "app")
public interface AppConfig {

    @WithDefault("false")
    boolean showName();
}
```

Then I want to create a mock of it using `@InjectMock`. The reason for that is that I wanted to write some tests that test different branches of my code without creating a special Quarkus profile.

```java
@QuarkusTest
public class GreetingResourceMockConfigTest {

    @InjectMock
    AppConfig appConfig;

    @Test
    public void testHelloEndpoint() {
        Mockito.when(appConfig.showName()).thenReturn(true);
        // The test
    }
}
```

However, the Quarkus test fails to run with the following exception:

```
Caused by: org.mockito.exceptions.base.MockitoException: 
Cannot mock/spy class org.acme.AppConfig2131402041Impl
Mockito cannot mock/spy because :
 - final class
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.createMockAndSetTestField(CreateMockitoMocksCallback.java:54)
	at io.quarkus.test.junit.mockito.internal.CreateMockitoMocksCallback.afterConstruct(CreateMockitoMocksCallback.java:29)
	... 66 more
```

## To Reproduce

https://github.com/ivannov/mocking-config-mappers

1. mvn test

**Comment by radcortez** [comment]
Hi @ivannov,

The issue here is that instances of mapping or properties classes are in the dependant scope, so they cannot be proxied to add the mock even if we remove the final modifier.

One trick here is to just provide your own implementation of the mapping interface with `@io.quarkus.test.Mock` and `@ApplicationScoped`. This will now create a proxy and `@io.quarkus.test.Mock` will set this up as an alternative so it will be the one being injected. The methods implementations don't matter because you will be using the mock result. I'll push a PR to the reproducer with an example.
