### ISSUE TITLE
QuarkusSmallRyeTracingDynamicFeature bean is removed during build

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#18105]
## Describe the bug
While using Quarkus 2.0.0.CR3 with extensions: `resteasy, rest-client, smallrye-opentracing` and no rest endpoint defined in the project, the following warning being thrown to the console:

=-=-==-=-==-=-==-=-==-=-==-=-==-=-==-=-=
CDI: programmatic lookup problem detected

At least one bean matched the required type and qualifiers but was marked as unused and removed during build
Removed beans:
        - CLASS bean io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature [types=[interface javax.ws.rs.container.DynamicFeature, class io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature], qualifiers=[@javax.enterprise.inject.Default(), @javax.enterprise.inject.Any()]]
Required type: class io.quarkus.smallrye.opentracing.runtime.QuarkusSmallRyeTracingDynamicFeature
Required qualifiers: [@javax.enterprise.inject.Default()]
Solutions:
        - Application developers can eliminate false positives via the @Unremovable annotation
        - Extensions can eliminate false positives via build items, e.g. using the UnremovableBeanBuildItem
        - See also https://quarkus.io/guides/cdi-reference#remove_unused_beans
=-=-==-=-==-=-==-=-==-=-==-=-==-=-==-=-=

*Without `quarkus-rest-client` extension there is no warning.

This warning is not happening with 1.13.7.Final
Probably related to https://github.com/quarkusio/quarkus/pull/16101

### Expected behavior
Bean is not removed / No warning message thrown in the console?

### Actual behavior
Warning message is thrown in the console

## To Reproduce
Run `mvn clean quarkus:dev` with the attached project (no resource defined)
[getting-started1.zip](https://github.com/quarkusio/quarkus/files/6701740/getting-started1.zip)

### Output of `java -version`
OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9)

### Quarkus version or git rev
2.0.0.CR3 && 2.0.0.Final

**Comment by kshpak** [comment]
The problem persists in 2.0.1.Final.

**Comment by gsmet** [comment]
@kenfinnigan could you have a look or redirect to the appropriate person?

**Comment by radcortez** [comment]
I'll have a look.

**Comment by radcortez** [comment]
@kshpak I don't see this as an issue. The bean is removed because there is no REST Client in the project, so you get the warning since the bean is not needed and Quarkus removes it.

As you stated, if you remove the dependency, the warning goes away. If you add an actual REST Client, the warning goes away as well.

**Comment by kshpak** [comment]
@radcortez I don't see this warning as appropriate. It should be removed from the console IMHO. There is no added value from that info for user.

**Comment by radcortez** [comment]
I believe it is helpful. 

It doesn't make sense to keep an unused dependency, so the warning either lets you know that you have the dependency and because is not used you can remove it, or lets you know that added the dependency but didn't implement anything meaningful so maybe something is missing.

Can you please let me know what is the use case to include the extension, but not implement a REST Client with it? Thanks!

**Comment by kshpak** [comment]
I mean, how it will help to spot a problem for the user if it doesn't state what causes it (in our case rest-client extension). Even if we have a redundant rest-client dependency it will not mention this dependency in the warning message. That's why IMHO it is a redundant warning.

**Comment by radcortez** [comment]
But I still didn't understand why do you have a rest client dependency without a rest client implementation? Are you looking to use some specific API from this dependency that doesn't require the client?

**Comment by sclorng** [comment]
Hi,

IMHO, the warning is raised because at runtime some instances request for the Bean and CDI couldn't find it due to being removed at build time. So, something in the quarkus bits are actually requesting it even when no Rest Client are seen to be injected at build time.
This can then lead to runtime NPE, see the above linked issue.

**Comment by scrocquesel** [comment]
Fixed at https://github.com/quarkusio/quarkus/issues/22605
