### ISSUE TITLE
GraphQL client extension should directly depend on JSON-B extension

### ISSUE THREAD

**Issue by jmartisk** [quarkusio/quarkus#18187]
When using GraphQL clients, one automatically gets a dependency on the JSON-B library, but not on the JSON-B extension, which causes trouble for example in native mode, because the necessary reflection registrations are not applied.

Example: instantiating a typesafe client
```
Caused by: java.lang.InstantiationException: Type `org.glassfish.json.JsonProviderImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
```

This effectively requires the application to add that extension, if it's not added through something transitively.

**Comment by geoand** [comment]
The question here is, does the GraphQL Client absolutely need to depend on JSON-B?

**Comment by jmartisk** [comment]
Unfortunately yes (at least right now), because it is being directly used under the covers

**Comment by geoand** [comment]
OK. I would hope that in the future that changes, because we've been moving towards Jackson over JSON-B across the board with Quarkus

**Comment by jmartisk** [comment]
Unfortunately that clashes with what MicroProfile is doing, because the MP platform depends on JSON-B :(
https://github.com/eclipse/microprofile/blob/4.0.1/pom.xml#L190
We may be able to ignore that dependency, but I'm not sure, maybe it would become an issue in some cases.

**Comment by phillip-kruger** [comment]
I will propose a lighter dependency in MP GraphQL, so we just say that we need to support the JSONB annotation, but we do not need to include JSONB. The should allow us to replace JsonB with Jackson in SmallRye

**Comment by arimeyer** [comment]
Wanted to know how Quarkus is proceeding with this (and related) issues.  Because Quarkus prefers Jackson, I initially went with it.  Now I find that we can't use it for GraphQL, and need to switch to JSON-B.  I've seen multiple questions online about this as well.  Maybe to clear up the confusion, can the Quarkus team update the docs/guides?

Is there any significant reason why JSON-B can't be the preferred library for Quarkus across the board?  I did find this discussion from a couple years back: https://groups.google.com/g/quarkus-dev/c/RTnvH6LSdxs?pli=1 .  Are all those points still relevant?  In particular, I see:
`JSON-B does not support polymorphic collections.  Jackson does.  That was a key decider for us.`
