### ISSUE TITLE
Support for MDC log metadata when using Opentelemetry

### ISSUE THREAD

**Issue by wabrit** [quarkusio/quarkus#18228]
## Description

When using the [smallrye opentracing extension](https://quarkus.io/guides/opentracing) in Quarkus applications, the [quarkus-logging-gelf](https://quarkus.io/guides/centralized-log-management) extension allows you to include the MDC (mapped diagnostic context) as metadata in each log record. This is essential when using a centralised logging system such as logstash as it allows logs to be filtered (via e.g. kibana) via trace/span/parentspan ids to trace interactions between multiple microservices communicating over synchronous (e.g. REST) or asynchronous (e.g. AMQP, Kafka) channels.

Currently the quarkus opentelemetry extension does not support this feature, which makes it unsuitable for use in a distributed logging system.

## Implementation ideas

None proposed, only that whatever implementation is chosen should meet the following requirements:

- The configuration (via those properties exposed by the gelf logging extension) should be identical to that used in the context of opentracing.
- The resultant log metadata fields should match (in type and name) those produced when used in the context of opentracing.

**Comment by wabrit** [comment]
The following may help in implementing a solution, based on analysing how the gelf logger extension and opentracing work together to include MDC data in logs.

**Gelf Logger**

There is a `MdcGelfMessageAssembler` class in the `logging-gelf` library; this looks to be where log events are augmented with MDC data. The MDC data for that is sourced from calls made elsewhere to `org.jboss.logging.MDC.put()`.

**Smallrye OpenTracing**

With the `smallrye-opentracing` extension declared as a dependency, that pulls in the `quarkus-jaeger` extension; the latter contains an `MDCScope` class which makes the calls to `MDC.put()`. The scopes are created as a result of `QuarkusJaegerTracer.activate(Span)` calls, which in turn appear to be triggered by e.g. `JaegerTracer/SpanBuilder` inside the `jaeger-core` dependency (amongst other places).

_Conclusion_

It feels like the key exemplar class here is `io.quarkus.jaeger.runtime.MDCScope`; it is responsible for placing tracing data into the MDC map, where it can be extracted by Gelf.

It feels like there needs to be some equivalent mechanism within opentelemetry which allow spans to call MDC.put().

P.S. The names of the MDC log attributes are defined by constants in the MDCScope class, to wit `traceId`, `spanId`, `parentId` and `sampled`.

**Comment by wabrit** [comment]
Other otel logging instrumentations (e.g. log4j) are relatively simple because the logging framework in question has an SPI-based extension mechanism in which to inject the MDC behaviour.

For jboss logging the only similar mechanism I can find is the SPI-able `EmbeddedConfigurator` interface, and which allows additional jboss logging `ExtHandler` implementations to be registered. The problem is I think you can only have one EmbeddedConfigurator implementation registered in your app and Quarkus already does this with its bootstrap logging implementation InitialConfigurator.

I wondered whether a custom SpanProcessor that used the onStart/onEnd callbacks to set values into org.jboss.logmanager.MDC would work for jboss logging. But I'm not sure, within the context of a Quarkus app, precisely how you would register an additional SpanProcessor; there doesn't seem to be a mechanism exposed by the quarkus opentelemetry extension.

Besides it feels like manipulating the jboss logmanager MDC, which is a _thread-local_ object, doesn't sit well with the world of Quarkus contexts, and an approach which directly called the `ExtLogRecord.setMDC()` method using data from the current span would be better. But I can't see a way to do that.

**Comment by wabrit** [comment]
In lieu of the fix for the log tracing issue, the following Substrate VM gelf class substitution appears to work:

```java
import biz.paluch.logging.gelf.jboss7.JBoss7JulLogEvent;
import io.opentelemetry.api.trace.Span;
import io.opentelemetry.api.trace.SpanContext;
import com.oracle.svm.core.annotate.Substitute;
import com.oracle.svm.core.annotate.TargetClass;

import org.apache.commons.lang3.StringUtils;

import java.util.Set;

@TargetClass(JBoss7JulLogEvent.class)
public final class JBoss7JulLogEventReplacement {

  @Substitute
  public String getMdcValue(String mdcName) {

    try {
      // Set new values
      final Span currentSpan = Span.current();

      if (null != currentSpan) {
        final SpanContext spanContext = currentSpan.getSpanContext();

        if (null != spanContext && spanContext.isValid()) {
          if (StringUtils.equals(mdcName, "traceId")) {
            return spanContext.getTraceId();
          } else if (StringUtils.equals(mdcName, "spanId")) {
            return spanContext.getSpanId();
          }
        }
      }
    } catch (Exception e) {}

    return null;
  }

  @Substitute
  public Set<String> getMdcNames() {
    return Set.of("traceId", "spanId");
  }
}
```

**Comment by stevefavez** [comment]
Hi, 
we're facing the same "issue". Here's a proposal that seems to work. I know, it's not perfect, but working for your use case. 
 I just created an small extension that enables a ContainerRequestFilter - ContainerResponseFilter provider and when getting request add span and trace in Jboss MDC (from current Span) - and clean MDC when responding.
Please find the code in attachment, don't hesitate to return me any critics - sure I missed many things. 

but really interested what's wrong - what I missed. 

thanks 
St

[trace-logger-extension.zip](https://github.com/quarkusio/quarkus/files/7106395/trace-logger-extension.zip)

**Comment by Dieken** [comment]
Just for your reference,  this comment may help: https://github.com/quarkusio/quarkus/issues/15182#issuecomment-915814501

**Comment by luneo7** [comment]
Though on the following solutions:

1. Change the actual MDC implementation that is being used by Quarkus [[source code link](https://github.com/jboss-logging/jboss-logmanager/blob/master/core/src/main/java/org/jboss/logmanager/MDC.java)], but came up with some issues:
a. The JBoss Log Manager doesn't provide any way to customize it, so to fix it we would need to open PRs there adding a MDC SPI, so we could later provide a Vertx context MDC holder.
b. An easy, hacky way and fast way would be doing byte code replacement using ASM (Gizmo)... tried to do that with Quarkus, managed to get a transformed class a `BytecodeTransformerBuildItem` and also a generated class through `GeneratedClassBuildItem`, the only thing is that the module runs with `parentFirstArtifact` and `runnerParentFirstArtifact`, so it is loaded by the system classloader and in that phase it just disregards the transformed/generated bytecode, so it was a no go...

2. Create custom logging formatter (we would need to create for every scenario: color, banner, pattern, gelf etc), that tries to fetch from MDC and if doesn't exists tries to fetch from Vertx context (did a POC of that, source code [here](https://github.com/luneo7/quarkus/compare/main...otel-mdc))
a. The issue with this approach is that we can only set one formatter with Quarkus and if we have more than one it will use the last one that was set, so we can't guarantee that the formatter with MDC will be used.

A side note, the difference between OpenTelemetry extension and the OpenTracing one, is where the span/context storage is being triggered. With OpenTelemetry we are using a `VertxTracer`, and the context will still be applied, we can add stuff there by using the `receiveRequest` `context` parameter, and it is run in the main threads, and the request itself will be run on the event loop threads applying that context, so different threads thus setting the MDC there doesn't work since it is a thread local hash map. On the other side with OpenTracing, we are using a request filter to start the span and set the scope, this happens in the event loop threads, and it will be where the actual request is being run, so when setting the MDC there will make it appear in the logs since it is using the same thread.

For me the best approach would be changing JBoss LogManager to be flexible in regards to a MDC/NDC provider, where it can have the default as a thread local implementation, but when initializing the class, maybe in the same way that [LogProviders](https://github.com/jboss-logging/jboss-logging/blob/master/src/main/java/org/jboss/logging/LoggerProviders.java#L62) does, it tries to load it using the service loader, if it finds something, use it and if not fallback to the thread local one. Doing like this will make it work with GELF, and any other handler, because they call the log provider MDC class directly, and this class would resolve to the correct MDC provider. And setting this provider (Quarkus side), would be creating a Vertx Local Context MDC Logging Provider extension that would have a Vertx implementation of the SPI.

What do you think @kenfinnigan @wabrit  ?

**Comment by kenfinnigan** [comment]
Would be worth having @dmlloyd and @jamezp provide their thoughts from the JBoss Logging perspective

**Comment by dmlloyd** [comment]
I think having a provider SPI for MDC would be perfectly reasonable. Another option (depending on whether you know the keys in advance) could be to allow `Supplier` instances to be stored into MDC which are evaluated when the value is looked up or the MDC map is copied.

**Comment by luneo7** [comment]
The supplier also seems a good idea, the only thing that I am thinking is that it wouldn't resolve the problem with the way that Vertx async stuff works and the supplier would be in one threadlocal instance that might not be available in other thread, since there the context is create in one thread and propagated to the event loop thread.

I came up with a POC of the embedded log manager with the MDC/NDC Adapter that later we can use on Quarkus + Vertx: https://github.com/luneo7/jboss-logmanager-embedded/compare/master..mdc-ndc-adapter , @dmlloyd @kenfinnigan @jamezp can you take a look to see if it reasonable, I added the resolution of the adapters in the EmbeddedConfigurator SPI, so we don't need to another lookup... but we can also do in the MDC/NDC class a lookup for the SPI implementation and do a fallback.... depending on what you guys think, I can come up with a PR to let us use this in Quarkus

**Comment by jamezp** [comment]
I think for the most part that makes sense. I kind of don't think we should make the `FastCopyHashMap` public, but that would really be my only comment. It's essentially what JBoss Logging does.

**Comment by luneo7** [comment]
Yup, it is mostly what JBoss Logging does, except that the MDC adapter there calls the provider own MDC, and it doesn't let us customize the actual MDC provider, like SLF4J for instance allows us. Internally JBoss Logmanager uses the `FastCopyHashMap` that's why I thought about exposing it, so a custom MDC could also leverage this class, as I found this class scattered through some libs (infinispan, jboss cache, wildfly core...) in some places it is a public class and in others it isn't, if exposing it would be a problem, we can certainly make it back non public =]

**Comment by luneo7** [comment]
And where should this go? `jboss-logmanager-embedded` or `jboss-logmanager`, I see that Quarkus uses `jboss-logmanager-embedded` and that it is not a part of the `jboss-logging` github organization =]

**Comment by jamezp** [comment]
Maybe both, but I would suggest `jboss-logmanager-embedded` for now. `jboss-logmanager`, at least the main branch, is kind of a mess ATM. @dmlloyd do you have an opinion?

**Comment by dmlloyd** [comment]
I agree.

**Comment by luneo7** [comment]
K, opened up the PR there: https://github.com/dmlloyd/jboss-logmanager-embedded/pull/4

**Comment by knutwannheden** [comment]
I also had a look at this, since we are also in the process of switching from OpenTracing to OpenTelemetry. Looking at the OpenTelemetry code I noticed that the Javadoc of `ContextStorage` has an [example of how to use a `ContextStorageProvider` to set the MDC](https://github.com/open-telemetry/opentelemetry-java/blob/main/context/src/main/java/io/opentelemetry/context/ContextStorage.java#L35-L61).

I can't tell what the pros and cons are when compared against the proposed `SpanProcessor` approach. But I did notice that Quarkus already provides a `ContextStorageProvider` implementation, so as an alternative I attempted using `ContextStorage#addWrapper()`. This didn't really work, however, because Quarkus doesn't call `Context#makeCurrent()`. Instead it calls `QuarkusContextStorage.INSTANCE.attach()` directly in `OpenTelemetryVertxTracer#receiveRequest()` and `#sendRequest()`, which effectively "ignores" any wrappers (registered with `ContextStorage#addWrapper()`). I am not sure, but this is possibly a bug.

**Comment by luneo7** [comment]
Even using the wrapper it won't work, it doesn't matter that we are calling the attach directly, just because the MDC is a thread local map, and the creation and setting of the context, the calling of make current happens in a different thread than the your endpoint code or whatever is really run, since Vertx will run it on another thread, thus the MDC will be empty there. That's why we need a MDC implementation that uses Vertx to propagate the MDC context, and also that's why I wrote the MDC PR. One addendum is that If you try run the MDC test using Quarkus unit testing (using span processor, or adding the wrapper) it will pass because there stuff happens on the same thread, as soon you try to run that in a real world app you'll see that it will fail.

**Comment by knutwannheden** [comment]
Yes, I understand that changes to JBoss Log Manager are required. I just wanted to point out what I had found in the OpenTelemetry code.

**Comment by famod** [comment]
Has anyone tried a `ThreadContextProvider` to propagate the MDC as suggested here? https://stackoverflow.com/questions/65039035/manual-context-propagation-in-quarkus-native-mode/65040601#65040601

**Comment by knutwannheden** [comment]
@luneo7 Your PR https://github.com/dmlloyd/jboss-logmanager-embedded/pull/4 was merged a while ago. Does that mean that when a new release is made and integrated into Quarkus, that we should be able to use MDC again to refer to the current `traceId` and `spanId`?

Further, I think it would be most useful with some example of how to add some other custom items to the logging MDC.

**Comment by enqueue** [comment]
Related to #22724

**Comment by luneo7** [comment]
@dmlloyd when can you release a new version of the https://github.com/dmlloyd/jboss-logmanager-embedded so I can create the Quarkus Vert.x MDC Provider extension, and also update the OTEL lib to store the MDC info? Right now I am blocked waiting a release of the jboss-logmanager-embedded lib =]

**Comment by dmlloyd** [comment]
I can do a release now, however be aware that this project is on the process of being merged with the upstream `jboss-logmanager` so there is some slight risk of binary incompatibility when that is complete. This is due to this new API not existing upstream yet.

If that is okay then I'm happy to try and release it today.

**Comment by luneo7** [comment]
When the merge is finished, won't the new API be there? Or you mean that methods signatures and such can be changed after the merge? If that happens when updating Quarkus to use the resulting binary of the merge we will catch those changes and update the Quarkus Vert.x MDC Provider extension... I don't see any problem with that

**Comment by dmlloyd** [comment]
The API will be there, it just might move to another package or have other subtle changes necessary to resolve the divergence between the two forks.

**Comment by radcortez** [comment]
Are we able to move this forward? I'm happy to help.

**Comment by luneo7** [comment]
Yup, just saw that now we have a new jboss-logmanager-embedded version published on Maven Central. I am going to finish the Quarkus Vert.x MDC module and update the OTEL lib to use it.

**Comment by radcortez** [comment]
Thanks!

**Comment by luneo7** [comment]
@dmlloyd the 1.1.0 version of `jboss-logmanager-embedded` also migrated from `javax.json` to `jakarta.json` and to a newer version that is not in use in Quarkus, this rendered the lib incompatible, isn't there a way of releasing a version only with the MDC provider stuff and before the jakarta json changes?

**Comment by jtama** [comment]
Hope this will be made available soon. Opentelemetry without log/trace correlation is sad.

Is there any workaround in the meantime ?

**Comment by dmlloyd** [comment]
See #25347 which updated the logmanager to 1.0.10 which introduces the new MDC API without breaking compatibility due to `javax/jakarta.json`.

**Comment by gastaldi** [comment]
Reopening as https://github.com/quarkusio/quarkus/pull/25311 says it's only the first part

**Comment by luneo7** [comment]
Yup... going to open the OTEL PR =]

**Comment by knutwannheden** [comment]
@luneo7 Does the solution allow for additional custom MDC entries to be added?
