### ISSUE TITLE
add Template.data(Map) to Qute ? 

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#18386]
## Description

qute has various `Template.data(string key, ...)` methods; how about a `Template.data(map<String, Object>)` ?

note, smallest alternative I could think of was: 
`properties.forEach((k,v) -> template.data(k,v));`

which isn't too bad but feels would be nice with something simpler ;)

**Comment by mkouba** [comment]
So you can pass any object as a template data, including maps, see also `Template.data(Object)` and `TemplateInstance.data(Object)`. In fact, if you do `template.data("foo", true)` then internally a map is created to hold the data. To sum it up: `template.data(properties)` should work just fine.

**Comment by maxandersen** [comment]
mkay  - might be worth updating the docs for that method then - https://javadoc.io/doc/io.quarkus.qute/qute-core/latest/io/quarkus/qute/Template.html  doesn't help much

**Comment by mkouba** [comment]
> mkay - might be worth updating the docs for that method then

Feel free to send a PR ;-). I think that the javadoc for `TemplateInstance` is quite clear and those convenient methods declared on `Template` are just delegating to the template instance.

**Comment by maxandersen** [comment]
so I just tried `template.data(properties)` and it does not add each entry in the map - at least it gets destroyed if you do multiple data() calls.

so for now i'm still left having to do:

```
			properties.forEach((k, v) -> templateWithData.data(k, v));
```

**Comment by mkouba** [comment]
> `` and it does not add each entry in the map

It should not add entries in a map but set the properties as the root data object (instead of the data map). And yes, once you add a map entry property via a `data()` method the root object previously set by `data(Object)` is removed by a data map. This behavior is described in the javadoc and if you ask for a use case - it's very useful when you only have one data object and you just need to access the properties directly, i.e. `data(order)` and then in the template `{price}` (instead of `data("order",order)` and `{order.price}`). I'm not quite sure what you're trying to achieve but I think that the best way if you need to add multiple entries in the data map is:
1. add `data("properties", properties)` and then `{properties.get('foo')}, or
2. use the approach you mentioned above; but keep in mind, that if the properties map contains a value with the same key as you pass to the template, one of the values will be overwritten...

**Comment by maxandersen** [comment]
I'm not saying data(properties) is wrong. I'm saying that there is missing an easy way to *add* a map and data is surprisingly asymmetric. 

Ie. .data("a", a).data("b", b) adds two properties but .data("a", a).data("b", b).data(map) removes a and b.

**Comment by mkouba** [comment]
Yes,it's a bit "asymmetric", purposely. And I've tried to explain the reasons in the previous https://github.com/quarkusio/quarkus/issues/18386#issuecomment-878051753.

As for the "missing an easy way to add a map". Well, we could discuss why not add methods for other types as well. But I don't think it would be helpful, rather the opposite - it might be even more confusing. BTW you can simplify your construct to `properties.forEach(templateWithData::data)` which is rather nice ;-).

**Comment by mkouba** [comment]
I'm going to close this issue now. Feel free to reopen if you still think we should do something in this area.
