### ISSUE TITLE
Do not produce Infinispan RemoteCacheManager if no Infinispan configuration is present - part 2

### ISSUE THREAD

**Issue by jamesnetherton** [quarkusio/quarkus#18517]
Follow up to https://github.com/quarkusio/quarkus/issues/18232. See [comments](https://github.com/quarkusio/quarkus/issues/18232#issuecomment-873922973) after testing the changes made in #18363.

**Comment by karesti** [comment]
I don't think the issue is protostuff dependency @jamesnetherton 
in any case, please consider removing that dependency because it will be removed in Infinispan 15 (we are currently on 13 development)
I think the issue is somewhere else for those properties indeed. 
The properties empty is indeed not enough and we need to check that the mandatory properties are present. and that is the infinispan server list IMO quarkus.infinispan-client.server-list

**Comment by karesti** [comment]
@jamesnetherton would you mind testing this commit here ?https://github.com/karesti/quarkus/commit/4ae93de797b3f2ea98bd14e25aa71abe289393ae

**Comment by jamesnetherton** [comment]
> @jamesnetherton would you mind testing this commit here ?[karesti@4ae93de](https://github.com/karesti/quarkus/commit/4ae93de797b3f2ea98bd14e25aa71abe289393ae)

@karesti I tested and it's now working as expected. Thanks!
