### ISSUE TITLE
Continueous testing NPE

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#18723]
### Describe the bug

I have a project with all tests passing when executing the plain `mvn test`. `mvn quarkus:dev` continuous tests fail, however. Probably due to mocking issues.

The project itself is a plain java lib but with profile `qtest`, which allows running `mvn quarkus:dev` as described by @sdaschner  in his [blog](https://blog.sebastian-daschner.com/entries/quarkus-dev-for-java-projects)

### Expected behavior

tests passing with `quarkus:dev`

### Actual behavior

tests not passing with `quarkus:dev`

### How to Reproduce?

[issue.tar.gz](https://github.com/quarkusio/quarkus/files/6824413/issue.tar.gz)

- `tar xvf issue.tar.gz && cd issue`
- `mvn install -f lib1 && mvn package lib2` Tests passing in lib2
- `cd lib2 && mvn quarkus:dev -Pqtest`
- run tests with `r` command

```java
Test SomeBeanTest#t1() failed 
: java.lang.NullPointerException
	at org.me.lib1.Response.setSomData(Response.java:18)
	at org.me.lib1.Request.execute(Request.java:13)
	at org.me.lib2.SomeBean.getResult(SomeBean.java:16)
	at org.me.lib2.SomeBeanTest.t1(SomeBeanTest.java:42)

```

### Output of `uname -a` or `ver`

Linux 5.8.0-59-generic #66~20.04.1-Ubuntu SMP Thu Jun 17 11:14:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20 OpenJDK Runtime Environment AdoptOpenJDK-11.0.11+9 (build 11.0.11+9) OpenJDK 64-Bit Server VM AdoptOpenJDK-11.0.11+9 (build 11.0.11+9, mixed mode)

### Quarkus version or git rev

2.0.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by stuartwdouglas** [comment]
This is because setSomData is package private, and it is loaded in a different ClassLoader in continuous testing mode. Mockito does not support the scenario. 

This is because the tests need to be dropped and re-loaded every time the application changes, so they go in their own ClassLoader, while libraries such as lib1 are loaded in a base CL that is not dropped every time.

In order to fix this you can either:
- Make the method public
- Add a parent pom that contains both projects. This will make Quarkus look for changes in both projects, so they will both be loaded into the same ClassLoader. IMHO this is the best solution, as it means changes in lib1 will also run the tests.
- Create an application.properties file with quarkus.class-loading.reloadable-artifacts=org.me.lib1:lib1

**Comment by ennishol** [comment]
@stuartwdouglas  thanks for looking into this!.

- Mockito seems to work fine in this case with plain maven, so I thought, there is an issue in quarkus
- Unfortunately, I'm not in control of lib1
- `quarkus.class-loading.reloadable-artifacts` did the trick :)
