### ISSUE TITLE
Logging configuration ignores environment variables

### ISSUE THREAD

**Issue by hwellmann** [quarkusio/quarkus#1887]
It seems that logging configuration only respects system properties but ignores environment variables.

Example:

This disables color output:
    
    java  -Dquarkus.log.console.color=false -jar application-configuration-1.0-SNAPSHOT-runner.jar

This should do the same, but has no effect:

    QUARKUS_LOG_CONSOLE_COLOR=false java -jar application-configuration-1.0-SNAPSHOT-runner.jar

**Comment by dmlloyd** [comment]
This is a little bit of a complex issue.  We parse the configuration by iterating all the available configuration keys, so we can detect invalid items and also use free-form object mapping.  The mapping of configuration key to environment variable name is one-way: that is, you can only find the environment variable from the configuration key, not the other way around.  Putting these two things together means that configuration properties which are given *only* by environment variable will not be seen.

There are two workarounds.  One is to supply just an empty value for the key in your `application.properties`, which will cause the key to be found and the environment variable to be read (since it would be a higher priority than the file).  The other would be to give a value like this for the key:

```properties
quarkus.log.console.color=${COLOR_LOGGING:true}
```
And then just pass in a value for `COLOR_LOGGING`.

I know these workarounds are not ideal, but I'm still working on a viable solution.

**Comment by fabricepipart** [comment]
I ran into the same problem today and I had to refer to this issue to understand how to use a Kubernetes secret to define the datasource password (quarkus.datasource.password property).

According to me the current behaviour is fine. You define the property in application.properties but you can override it via environment variables. I even prefer that, this way all properties are declared in the same place.
I also did not realise that you could use bash-like syntax to refer to environment variables. Would you agree that I specify all those in the [user guide](https://quarkus.io/guides/application-configuration-guide#configuring-quarkus) ?
