### ISSUE TITLE
Quarkus cannot use the hibernate-validator constraints in the inherited class/interface

### ISSUE THREAD

**Issue by isikemre** [quarkusio/quarkus#1888]
If you use constraints from the hibernate-validator like [here](https://quarkus.io/guides/validation-guide#rest-end-point-validation) but in a parent interface (or class) the constraints don't work.

### Scenario
**ExampleResourceImpl** is implementing **ExampleResource** (it's a interface).  
**ExampleResource** has all `@GET` and `@Path` (JAX-RS) annotations and has also all hibernate validation constraints like `@Valid` `@NotNull`.  

ExampleResourceImpl.java
```java
@RequestScoped
public class ExampleResourceImpl implements ExampleResource {

    public Response doSomething(SomeObject someObject) {
        return something();
    }
}
```

ExampleResource.java
```java
@Produces(APPLICATION_JSON)
public interface ExampleResource extends Serializable {

    @POST
    @Path("/example")
    Response doSomething(@Valid @NotNull SomeObject someObject);

}
```

### Summary
Quarkus can read the JAX-RS annotations, **but not** the hibernate-validator **constraints** from his parent class/interface.

**Comment by gsmet** [comment]
I discussed with @isikemre on Zulip. Currently, it's not implemented, we need to implement it.

**Comment by isikemre** [comment]
I opened a PR (as discussed) which includes a test case about this isse.  
[https://github.com/quarkusio/quarkus/pull/1913](https://github.com/quarkusio/quarkus/pull/1913)

**Comment by blxbrgld** [comment]
We can workaround by adding @Valid annotations on on both interface and implementation, but the fact that the annotations are gettting ignored on the interface leads to triggering of **io.quarkus.hibernate.validator.runtime.interceptor.MethodValidationInterceptor** instead of **io.quarkus.hibernate.validator.runtime.jaxrs.JaxrsEndPointValidationInterceptor**. Hence the exception is not wrapped as a ResteasyViolationException and the response code is 500 instead of 400 which would be the expected.

**Comment by isikemre** [comment]
Is there any updates/news for this issue?

**Comment by gsmet** [comment]
After a discussion with @mkouba , here is what we should do:
* in the processor, we would analyze the hierarchy of constrained classes and determine the methods of the subclasses that are constrained because they override a constrained method
* then we add an annotation transformer with a goal similar to `MethodValidatedAnnotationsTransformer` that add the interceptor binding annotations for the above methods.

Note that we don't need to be too picky because HV should take care of doing nothing if we end up trying to validate things on a unconstrained method. But it has some overhead so if we can try to filter out the methods, it would be better.

**Comment by gsmet** [comment]
@aguibert this one is yours if you're interested. It's a good opportunity to have a look to the Jandex and annotation transformer infrastructures.

**Comment by ebullient** [comment]
I can have a look

**Comment by ebullient** [comment]
Thank you, Sanne!
