### ISSUE TITLE
quarkus.kubernetes-config.secrets.enabled not explained on Kubernetes Config documentation

### ISSUE THREAD

**Issue by languitar** [quarkusio/quarkus#18963]
### Describe the bug

The [configuration reference](https://quarkus.io/guides/kubernetes-config#configuration-reference) for kubernetes config does not list the property `quarkus.kubernetes-config.secrets.enabled`

### Expected behavior

Should be included in the property list on that page

### Actual behavior

Only mention in the explanations of another property

**Comment by geoand** [comment]
cc @metacosm

**Comment by geoand** [comment]
@machi1990 any idea why https://github.com/quarkusio/quarkus/blob/2.1.0.Final/extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesConfigBuildTimeConfig.java#L14 isn't showing up on https://quarkus.io/guides/kubernetes-config#configuration-reference?

**Comment by machi1990** [comment]
> @machi1990 any idea why https://github.com/quarkusio/quarkus/blob/2.1.0.Final/extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesConfigBuildTimeConfig.java#L14 isn't showing up on https://quarkus.io/guides/kubernetes-config#configuration-reference?

From top of my head no, but I'll have a look at it in couple of hours. It is very suspicious.

**Comment by geoand** [comment]
Thanks!

**Comment by machi1990** [comment]
> Thanks!

I had a first look at there are couple of reasons for this:
- we are only including a partial configuration (quarkus-kubernetes-config-kubernetes-config-source-config.adoc) for the extension (BOOTSTRAP config root from the KubernetesConfigSourceConfig.java file). The one we are interested with is at: quarkus-kubernetes-config-kubernetes-config-build-time-config.adoc (also a partial generated output)
- there is a bug in sense that the quarkus-kubernetes-config.adoc file should be generated too along side the partial configuration but this is not the case. But a quarkus-kubernetes-client.adoc file is generated for the module. 
- There is another bug related to the one above in https://quarkus.io/guides/kubernetes-client#quarkus-kubernetes-client_quarkus.kubernetes-config.secrets.enabled because now the kubernetes-client configuration contains kubernetes-config. Not sure if this is a bug or an intended behaviour at this stage. 

I'll investigate more on this if it impact other area and look into a fix.

**Comment by machi1990** [comment]
> > Thanks!
> 
> I had a first look at there are couple of reasons for this:
> 
> * we are only including a partial configuration (quarkus-kubernetes-config-kubernetes-config-source-config.adoc) for the extension (BOOTSTRAP config root from the KubernetesConfigSourceConfig.java file). The one we are interested with is at: quarkus-kubernetes-config-kubernetes-config-build-time-config.adoc (also a partial generated output)
> * there is a bug in sense that the quarkus-kubernetes-config.adoc file should be generated too along side the partial configuration but this is not the case. But a quarkus-kubernetes-client.adoc file is generated for the module.
> * There is another bug related to the one above in https://quarkus.io/guides/kubernetes-client#quarkus-kubernetes-client_quarkus.kubernetes-config.secrets.enabled because now the kubernetes-client configuration contains kubernetes-config. Not sure if this is a bug or an intended behaviour at this stage.
> 
> I'll investigate more on this if it impact other area and look into a fix.

@geoand I might have found the issue, the package name is `io.quarkus.kubernetes.client.runtime` for the https://github.com/quarkusio/quarkus/tree/main/extensions/kubernetes-config/runtime module. See https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-config/runtime/src/main/java/io/quarkus/kubernetes/client/runtime/KubernetesConfigSourceConfig.java#L1 Since the name is derived from it, the causes some issues. Not sure if that's indeed given that the deployment package is correctly named https://github.com/quarkusio/quarkus/blob/main/extensions/kubernetes-config/deployment/src/main/java/io/quarkus/kubernetes/config/deployment/KubernetesConfigProcessor.java#L1 ?

**Comment by geoand** [comment]
Ouch... That is likely just my dumb mistake in naming the package

**Comment by machi1990** [comment]
> Ouch... That is likely just my dumb mistake in naming the package

Okay, I'll prepare a PR to fix the issue.
