### ISSUE TITLE
ArC - implement assignability rules for decorators delegate injection points according to the spec

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#18982]
### Description

Decorator delegate injection points have a special set of rules for determining assignability of raw and parameterized types as defined in the spec:
https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#delegate_assignable_parameters

**Comment by mrickly** [comment]
Hi @mkouba , I did not manage to make the decorator pattern work in Quarkus for an interface `MyInterface<K,V>`. I suspect it might be related to this issue. Could you share a tentative timeline for the implementation?

**Comment by mkouba** [comment]
To be honest, I don't remember the difference between the rules for regular injection points and for delegate injection points. But I believe that the difference is minimal. @manovotn Do you happen to know?

@mrickly could you share more details about your app? We have a [test with generics](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/tests/src/test/java/io/quarkus/arc/test/decorators/generics/GenericsDecoratorTest.java). So it should work in general.

**Comment by mrickly** [comment]
@mkouba : In our application, the decorator has unbounded type parameters (MyInterface<K, V>) and the delegate has  actual types (e.g. MyDelegate<String, Contract>). In your test, the decorator has actual types (String, Long) which match the actual types (String, Long) of the delegate. One rule of the specification reads: "the delegate type parameter is a type variable, the bean type parameter is an actual type, and the actual type is assignable to the upper bound, if any, of the type variable". If I interpret this statement correctly, it means that our use case is supported by the spec. What I observed however was that the decorator was erased by the ArC framework, because it was unable to match the delegate injection point in the decorator with the bean.

**Comment by mkouba** [comment]
> @mkouba : In our application, the decorator has unbounded type parameters (MyDecorator<K, V>) and the delegate has actual types (e.g. MyDelegate<String, Contract>). In your test, the decorator has actual types (String, Long) which match the actual types (String, Long) of the delegate. One rule of the specification reads: "the delegate type parameter is a type variable, the bean type parameter is an actual type, and the actual type is assignable to the upper bound, if any, of the type variable". If I interpret this statement correctly, it means that our use case is supported by the spec. What I observed however was that the decorator was removed by the ArC framework, because it was unable to match the delegate injection point in the decorator with the bean (delegate).

Could you share the pseudo-code of your decorator and the bean that should be decorated?

Note that it's the delegate injection point that is used during decorator resolution, i.e. the bean must be assignable to the delegate injection point of a decorator to bind the decorator to a bean.

**Comment by mrickly** [comment]
`public class MyParameterizedType<K, V> {

    final K key;

    final V value;

    public MyParameterizedType(K key, V value) {
        this.key = key;
        this.value = value;
    }

    @Override
    public String toString() {
        return "key=" + key.toString() + ", value=" + value.toString();
    }

}`

`public interface MyInterface<K, V> {

    void doSomething(MyParameterizedType<K, V> myParameterizedType);

}`

`@Decorator
@Priority(Interceptor.Priority.APPLICATION)
public class MyDecorator<K, V> implements MyInterface<K, V> {

    @Inject
    @Delegate
    @Any
    MyInterface<K, V> delegate;

    @Override
    public void doSomething(MyParameterizedType<K, V> myParameterizedType) {
        delegate.doSomething(myParameterizedType);
    }

}`

`@ApplicationScoped
public class MyDelegateBean implements MyInterface<String, Contract> {

    @Override
    public void doSomething(MyParameterizedType<String, Contract> myConcreteType) {
    }

}
`

@mkouba : I have omitted package and import statements. The rest is unchanged and the ArC framework produces the following statement in the log: "2022-03-14 09:46:13,238 DEBUG [io.qua.arc.pro.BeanDeployment] (build-42) Removed unused decorator DECORATOR bean [decoratedTypes=[ch.mobi.glu.test.contract.MyInterface<K, V>], target=Optional[ch.mobi.glu.test.contract.MyDecorator]]
"

**Comment by manovotn** [comment]
> To be honest, I don't remember the difference between the rules for regular injection points and for delegate injection points. But I believe that the difference is minimal. @manovotn Do you happen to know?

@mkouba I _think_ there was a difference in a raw type assignment but otherwise it was the same.
I.e. this sentence differs:

> A parameterized bean type is considered assignable to a raw required type if the raw types are identical and all type parameters of the bean type are either unbounded type variables or java.lang.Object.

> A raw bean type is considered assignable to a parameterized delegate type if the raw types are identical and all type parameters of the delegate type are either unbounded type variables or java.lang.Object.

**Comment by manovotn** [comment]
I agree that this scenario seems like it should be covered by this spec statement.

> the delegate type parameter is a type variable, the bean type parameter is an actual type, and the actual type is assignable to the upper bound, if any, of the type variable.

Maybe we are passing in wrong required type for decorators when attempting typesafe resolution (otherwise the same issue would occur outside of decorator since we are using same ruleset - and I am not seeing that happen).

**Comment by mkouba** [comment]
@mrickly I've tried your setup and it seems to work. I think that your `MyDelegateBean` is marked as [unused and removed from the app](https://quarkus.io/guides/cdi-reference#remove_unused_beans). Therefore, the decorator was removed as well.

**Comment by manovotn** [comment]
I think @mrickly has hit the behavior where the assignability rules for delegate injection points differ.

> the delegate type parameter is a type variable, the bean type parameter is an actual type, and the actual type is assignable to the upper bound, if any, of the type variable.

This sentence has no counterpart in standard assignability rules and since we are ATM (incorrectly) using a single set of rules, the check will fail.

[Assignability of raw and parameterized types for delegate injection points](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#delegate_assignable_parameters)
[Assignability of raw and parameterized types](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#assignable_parameters)

In weld, this difference can be seen here - https://github.com/weld/core/blob/master/impl/src/main/java/org/jboss/weld/resolution/DelegateInjectionPointAssignabilityRules.java#L77-L84
There is a few more remarks about different behavior. I suppose we should introduce the same here.

**Comment by manovotn** [comment]
@mrickly just an FYI, I have submitted a [PR](https://github.com/quarkusio/quarkus/pull/24301) that fixes your scenario (and possibly other cases as well), so unless we discover some major flaw, this should land in the next Quarkus release :-)

**Comment by mrickly** [comment]
Thanks @mkouba and @manovotn , that was fast!
