### ISSUE TITLE
Kafka Oauth extension

### ISSUE THREAD

**Issue by merlante** [quarkusio/quarkus#18998]
### Description

In the guide, [Quarkus - Using Apache Kafka with Reactive Messaging guide](https://quarkus.io/guides/kafka), there is a section on "Authentication with OAuth", where a third party library, the strimzi-kafka-oauth client, is specified to provide the jaas callback handler. The problem is that this library is not part of Quarkus and is not guaranteed to work, for example, in native mode. In fact versions 0.8.0+ currently cause native app builds to fail (see [kafka-oauth-client supported for use with Quarkus (native)?](https://github.com/strimzi/strimzi-kafka-oauth/issues/122) in strimzi-kafka-oauth). (This is an issue for the guide, but it is also a more general problem of how to handle this dependency.) In that issue it was pointed out that it is the responsibility of Quarkus to ensure that libs such as this work in conjunction with Quarkus, and therefore it should add explicitly as a dependency and tested as part of Quarkus.

I am suggested adding this lib as a separate Quarkus extension that can be optionally added to enable Oauth for kafka; however, it might make more sense to add it to the "bom" with some tests to ensure that it works correctly, as I think is being suggested here: #18601 and #18605. I defer to your wisdom on this point.

Thanks!

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

**Comment by cescoffier** [comment]
Yes, would be nice to have an extension extracting this. However, there are other oauth supports, so we need to think how we want to articulate this.

**Comment by cescoffier** [comment]
I think we should definitely start an extension (most probably in the quarkiverse). 
This repo would be the perfect place to implement some IT tests verifying the behavior.

I used to test the setup manually, as it was kind of ticky to implement it in an automated manner without eating lots of CI time.

**Comment by emmanuelbernard** [comment]
There are several problems all entangled, let me try and clarify a few things

1. The default SASL for Kafka client works out of the box but is less secure than OAUTHBEARER.
I think we should promote the more secure option by default so I would prefer a model where we don't have a separate extension but rather embed the logic int he main extension (if that does not blow the RSS size up). We could even based on the build time properties short circuit the code for it to be eliminated if no OAUTH server is set or whatever

2. The Strimzi team has moved to a new underlying library, evidently it was not caught up by some CI tool early and I don't even know if we had fixed the Strimzi version in our BOM and we should to control the behavior

3. I can imagine the Strimzi team being real busy and not have Quarkus specific CI pipeline, and I can imagine the Quarkus team not able to cater for all native thing in the universe. But Kafka is an important use case.
So we need to set some CI that:

- check a given sanctionned Strimzi OAUTH lib to Quarkus master every 24hrs
- check Strimzi lib master to Quarkus stable every 24hrs

So that we can get a good grasp of something going wrong within 24 hours. From there, the Strimzi team and the Quarkus team can identify and figure out a solution plan. Good thing is we have defined such a scheme with external extensions (part of the platform or not) and maybe we can just reuse that.

4. Testing Kafka on OAUTH requires (at least), Kafka + Zookeeper + Keycloak (Oauth server) + an app testing the call.
Can GitHub action support such a deployment if we use containers for Kafka and ZK and Keycloak?
And how can we collectively work on a way to set this system up with everyone's experience?
Is containers the right way, or should we rely on something like a Kafka cloud service to test the system?
Feels container would be more predictable at first sight.

5. on the concrete change that happened in 0.8[.1], we should just get a tiger team in place to see how to make nimbus-jose-jwt native friendly

**Comment by cescoffier** [comment]
I can answer the CI part. Yes it should be possible to get all of them running with test containers if we get the right images and configuration.
Last time I checked, having the correct settings (in kafka and keycloak with a preloaded realms) was very very hard and needed updates when we integrated a version of some new strimzi artifacts.

So in addition to the configuration and setup, it should be as stable as possible to focus only on the oauth client integration.

**Comment by emmanuelbernard** [comment]
> So in addition to the configuration and setup, it should be as stable as possible to focus only on the oauth client integration.

What does as stable as possible mean?

**Comment by zbendhiba** [comment]
> I can answer the CI part. Yes it should be possible to get all of them running with test containers if we get the right images and configuration.
> Last time I checked, having the correct settings (in kafka and keycloak with a preloaded realms) was very very hard and needed updates when we integrated a version of some new strimzi artifacts.
> 
> So in addition to the configuration and setup, it should be as stable as possible to focus only on the oauth client integration.

+1
I tried to get inspired from the many Strimzi oauth docker-compose and configurations to get one  CI example for camel-quarkus and it's very very hard.

**Comment by emmanuelbernard** [comment]
OK so what Clement expressed here is that we need images that have the Kafka image with the jar using the oauth strimzi lib. And have a prepopulated state so that Keycloak and Kafka talk to one another. I'll update my original comment with the info

**Comment by cescoffier** [comment]
Exactly @emmanuelbernard !

**Comment by cescoffier** [comment]
Let me verify with @ozangunalp, but I think Kafka oauth is now supported (including in native)

**Comment by cescoffier** [comment]
Closing based on Ozan's comment - it's supported, no need for a separate extension.
