### ISSUE TITLE
gRPC in custom extension causes gRPC to fail

### ISSUE THREAD

**Issue by 0SkillAllLuck** [quarkusio/quarkus#19085]
### Describe the bug

When using a proto file inside an extension and generating code there the gRPC services can no longer work correctly. IntelliJ shows that the classes are found but the gRPC service can't start. The issue seems to only occur with Quarkus 2.0 or higher.

### Expected behavior

The gRPC service starts normally and works

### Actual behavior

The gRPC service starts but returns unavailable exceptions due to classes no longer being found.

### How to Reproduce?

1. Generate a new quarkiverse extension that implements some logic using a proto file and the generated classes.
2. Generate a new quarkus project that uses the above extension and declares the services.
3. Try to start quarkus:dev

### Output of `uname -a` or `ver`

Microsoft Windows [10.0.18363.1679]

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20

### GraalVM version (if different from Java)

21.1.0.0.Final

### Quarkus version or git rev

2.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by michalszynkiewicz** [comment]
@0SkillAllLuck we do something similar with reflection service and health service...
Do you have your extension available somewhere? If not, can you create some minimal reproducer? It helps a lot in fixing issues.

**Comment by 0SkillAllLuck** [comment]
I created a reproducer plugin and project here:

[Plugin](https://github.com/0SkillAllLuck/quarkus-grpc-reproducer-plugin)
[Project](https://github.com/0SkillAllLuck/quarkus-grpc-reproducer)

To reproduce:

- Run `mvn clean install` in plugin
- Run `mvn clean test` in project

**Comment by michalszynkiewicz** [comment]
@0SkillAllLuck thanks! Looking at it

**Comment by michalszynkiewicz** [comment]
Testing with `grpcurl` I see it works outside tests and dev mode.

**Comment by michalszynkiewicz** [comment]
So the problem is that you have duplicated proto file definition in the application project.
This way for the app you generate exactly the same classes as for the extension.

If you remove `src/main/proto/ep2.proto` you will no longer get this error.
You will still have a problem with the generated classes not being available in the jandex index but you may solve it either by indexing your extension with instructions from https://stackoverflow.com/questions/55513502/how-to-create-a-jandex-index-in-quarkus-for-classes-in-a-external-module or by emitting a `AdditionalIndexedClassesBuildItem` for the generated classes from your extensions' processor.
