### ISSUE TITLE
Support for JDO/Datanucleus

### ISSUE THREAD

**Issue by stevespringett** [quarkusio/quarkus#1908]
JPA is nice if you use relational databases, but it's a subset of JDO, which handles no-sql and some graph databases without having to deal with SQL or SQL-like syntax. I don't think modern apps would use JPA in the cloud, but perhaps I'm wrong. Anyway, I typically use JDO (because Google AppEngine) for cloud Java apps, so support for Datanucleus would be ideal.

**Comment by emmanuelbernard** [comment]
Hey,

Frankly, we have seen epsilon demands on JDO. The main reason it stills shows up is the historical choice of Google App Engine (dataNucleus jas no JPA support at the time). Plus there is a lot of proposal around the NoSQL space both in projects and proposed standards.
Since we are heavily focusing on JPA for now, I will close this one. We can revisit as the space clears up and bandwidth increases. But I don't see that very soon.

**Comment by bobmcwhirter** [comment]
That being said, if you'd like to create an extension for JDO/Datanucleus, this could be helpful:

https://quarkus.io/guides/extension-authors-guide

**Comment by emmanuelbernard** [comment]
Of course, I should have stated the obvious that’s Quarkus is an open platform :)
