### ISSUE TITLE
javax.ws.rs.core.Application Marked for Removal, but required

### ISSUE THREAD

**Issue by dansiviter** [quarkusio/quarkus#1914]
* Version: 0.13.0
* Extensions: resteasy, smallrye-jwt 

It appears `Application` instances are removed although they have useful contents. E.g. if wanting to use Microprofile `@LoginConfig` annotation:

```
@ApplicationPath("/")
@LoginConfig(authMethod = "MP-JWT", realmName = "jwt-jaspi")
@ApplicationScoped
public class MyApplication extends Application { }
```

Is marked for removal:
```
2019-04-08 13:59:47,175 WARN  [io.qua.arc.run.ArcDeploymentTemplate] (main) Bean matching class acme.MyApplication was marked as unused and removed during build.
Extensions can eliminate false positives using:
	- a custom UnremovableBeanBuildItem
	- AdditionalBeanBuildItem(false, beanClazz)
```

Is seems the only way to do this is by using `quarkus.smalllrye-jwt.auth-mechanism` and `quarkus.smalllrye-jwt.realm-name` properties.

**Comment by geoand** [comment]
@gsmet @mkouba I vaguely remember talking about this somewhere. Would you like me to take this if you haven't fixed it already?

**Comment by gsmet** [comment]
Yes, I mentioned the issue to @mkouba the other day.

@mkouba I know I'm a bit repetitive on the subject but with this removable bean feature, it looks like we need to think about all the possible features of each framework and tweak things for each framework as they might rely on unused beans. It really seems fragile to me and a lot of work for the future. Am I mistaken?

I think I fail to see why this feature is so useful because if it's just removing beans that the user explicitly declared, I think it's going to be a Pandora box. Could you explain it once and for all so that I'm fully aware of the why and I don't bother you anymore with this?

Thanks!

**Comment by geoand** [comment]
In any case, I have opened a (small) PR for this specific issue.

**Comment by mkouba** [comment]
This issue duplicates https://github.com/quarkusio/quarkus/issues/1880.

As for the `@LoginConfig` annotation - it's not CDI-related and I don't think that the bean removal affects processing of this annotation.

**Comment by mkouba** [comment]
@dansiviter Could you pls verify whether this issue is solved by https://github.com/quarkusio/quarkus/pull/1924?

**Comment by dansiviter** [comment]
Apologies for slow reply. Yes, looks better in v0.13.3.
