### ISSUE TITLE
Option to fail build for unrecognized configuration key in `application.properties`

### ISSUE THREAD

**Issue by renegrob** [quarkusio/quarkus#19270]
If I have an unrecognized configuration key in application.properties (resource file). I'd like the build to fail instead of having a runtime message like:

```
[2021-08-06 11:04:04.930] WARN  io.quarkus.config: Unrecognized configuration key "quarkus.datasource.hibernate-orm.default-schema" was provided;
```
Maybe it could even be the default since I can't figure a situation where you want such a key in your resources and continue the rest of the build pipeline. But I guess it should be possible to have only a warning for some edge-cases.

This should affect all configuration properties that can be validated at build time (quarkus.* (`@ConfigItem`) and own properties declared via `@ConfigMapping`)

Of course the runtime configuration can still contain unrecognized configuration keys - but not anymore the default configuration shipped with the application.

**Comment by geoand** [comment]
@radcortez this sounds like something useful, no?

**Comment by radcortez** [comment]
I feel that failing might be too harsh. For what matters, such properties are harmless. They can indicate a mistype or an old property that was renamed.

Sometimes, fixing the warning is not exactly easy. The property may be coming from a source you don't have access to and require external intervention to fix.  We shouldn't lock the user from the application in such scenarios.

Also, there is at least one scenario where detecting such properties may yield false positives. An application may define a property only accessed through the programmatic API during runtime. We have no reliable way to detect such scenarios, so we cannot fail the application over the assumption of a false positive.

We can still implement this and have a switch to turn it on and off (default is off). But I'm usually not a big fan of config switches in config :)

**Comment by geoand** [comment]
Up to you :)

**Comment by famod** [comment]
_If_ such a flag is added, there should probably also be a kind of exclude list (to specify keys that are ok/should not cause a failure).

**Comment by radcortez** [comment]
> _If_ such a flag is added, there should probably also be a kind of exclude list (to specify keys that are ok/should not cause a failure).

More complexity :) 

Is this feature really worth it?

**Comment by renegrob** [comment]
Why would you want to ship the application with defaults for configuration properties that don't exist? (It is not about the runtime configuration)

**Comment by radcortez** [comment]
Ideally, you don't want to do it, but my concerns apply regardless of the phase. To be more concrete:

For instance, `application.properties` is loaded from the classpath during build time. If an external dependency includes an unrecognized property, it may require some time for that dependency to drop it. In this case, the user cannot fix the issue (considering that the library / extension is required for the app). 

Is this a common scenario? I can't tell, but I have a couple of extensions where I use `application.properties` to configure stuff (including build time properties).

I do have my reservations with such feature, because obsiouvly users are not going to be happy if their application build start failing, so we need to be somehow careful on what we decide to do.

**Comment by renegrob** [comment]
I thought it was a good way to let people notice when they use old properties that are not supported anymore and wonder why the application doesn't work the way they expect (e.g. because a prefix changed). But if it causes more troubles than it helps then it obviously doesn't make sense to implement it.

**Comment by gastaldi** [comment]
Closing it for now. Let's reopen if we change our mind
