### ISSUE TITLE
CDI scope types declared @Inherited are not inherited

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#1937]
See [4.1. Inheritance of type-level metadata](http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#type_level_inheritance).

You could start in `io.quarkus.arc.processor.Beans.createClassBean(ClassInfo, BeanDeployment)`.

**Comment by manovotn** [comment]
Quarkus currently runs only on (modified) `annotated` discovery mode.
That means the to-be bean has to have a [bean defining annotation](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#bean_defining_annotations) in order to be discovered and it has to be something else then scope annotation so it can inherit that one. That leaves us with a single corner case where you have a stereotype as a bean defining annotation and expect the scope to get inherited - not very common I would say. Overall, this feature makes much more sense for standard CDI where you can have discovery mode of `all`.
