### ISSUE TITLE
Arc: Regression issue when mapping `@ConfigMapping` using a custom ConfigSource implementation

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#19448]
### Describe the bug

This issue affects all users that provide a custom config source (org.eclipse.microprofile.config.spi.ConfigSource). For example:

```
public class CustomConfigSource implements ConfigSource {

    private static final int ORDINAL = 999;
    private static final String PROPERTIES_FILE = "/configsource.properties";

    // ...
}
```

Where `configsource.properties` is:

```
from.custom.source.person.name=From Config Source
from.custom.source.person.age=33
```

When mapping:

```
@Path("/config-mapping")
public class ConfigMappingResource {

    @Inject
    @ConfigMapping(prefix = "from.custom.source.person")
    PersonInterface personFromCustomSourceInterface;
```

It does not work any longer by failing with the following exception:
```
[app] Caused by: io.smallrye.config.ConfigValidationException: Configuration validation failed:
08:56:23.182 INFO  [app]        java.util.NoSuchElementException: SRCFG00014: The config property from.custom.source.person.name is required but it could not be found in any config source
08:56:23.183 INFO  [app]        java.util.NoSuchElementException: SRCFG00014: The config property from.custom.source.person.age is required but it could not be found in any config source
08:56:23.184 INFO  [app]        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:840)
08:56:23.185 INFO  [app]        at io.smallrye.config.ConfigMappingProvider.mapConfiguration(ConfigMappingProvider.java:796)
08:56:23.186 INFO  [app]        at io.smallrye.config.SmallRyeConfigBuilder.build(SmallRyeConfigBuilder.java:403)
08:56:23.186 INFO  [app]        ... 17 more
```

The root cause of this issue is this commit https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef. Note that this is a regression test that was working fine in `2.1.2.Final`.

The issue also affects the extension `quarkus-spring-cloud-config-client` to inject properties using `@ConfigMapping`.

### How to Reproduce?

1. git clone `https://github.com/Sgitario/quarkus-test-suite`
2. cd `quarkus-test-suite`
3. git checkout `reproducer_19448`

Then, we can reproduce it using a custom config source directly:
4.a cd `properties`
5.a `mvn clean verify -Dit.test=ConfigMappingResourceIT`

Or using the spring cloud config extension:
4.b cd `spring/spring-cloud-config`
5.b `mvn clean verify`

All the tests should work, but they are failing.

### Quarkus version or git rev

999-SNAPSHOT

**Comment by geoand** [comment]
This is odd, as we have an integration test that tests the extension in native mode

**Comment by Sgitario** [comment]
> This is odd, as we have an integration test that tests the extension in native mode.
> 
> Do you have an example application we can use to check?

Yes, see the reproducer section.

It must be caused to a very recent change as I was using a build (of Quarkus upstream) from the last week and it was working fine.

**Comment by geoand** [comment]
Interesting... I've been on PTO (and will continue for a few more days) for that time so I have no idea what could have changed

**Comment by Sgitario** [comment]
> Interesting... I've been on PTO (and will continue for a few more days) for that time so I have no idea what could have changed.
> 
> I'll check when I get back

I'm checking the integration test in Quarkus upstream and It's using the `@ConfigProperty` annotation which works fine. This issue happens only when using the `@ConfigMapping` annotation.

I will review the commit history from last week to today by tomorrow morning to try to spot what could cause this issue.

**Comment by Sgitario** [comment]
I've updated the issue to state that it's failing on JVM and Native.
This commit is the root cause: https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef
cc @radcortez

**Comment by Sgitario** [comment]
> I've updated the issue to state that it's failing on JVM and Native.
> This commit is the root cause: [fd4b302](https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef)
> cc @radcortez

Also, I've confirmed that this affects all users that provide a custom config source (org.eclipse.microprofile.config.spi.ConfigSource). 

For example:

```
public class CustomConfigSource implements ConfigSource {

    private static final int ORDINAL = 999;
    private static final String PROPERTIES_FILE = "/configsource.properties";

    private final Properties customProperties = new Properties();

    public CustomConfigSource() throws IOException {
        loadProperties();
    }

    @Override
    public Set<String> getPropertyNames() {
        return customProperties.keySet().stream().map(Object::toString).collect(Collectors.toSet());
    }

    @Override
    public int getOrdinal() {
        return ORDINAL;
    }

    @Override
    public String getValue(String propertyName) {
        return customProperties.getProperty(propertyName);
    }

    @Override
    public String getName() {
        return "Custom Config Source";
    }

    public void loadProperties() throws IOException {
        InputStream in = CustomConfigSource.class.getResourceAsStream(PROPERTIES_FILE);
        if (in != null) {
            customProperties.load(in);
        } else {
            throw new FileNotFoundException("Property file " + PROPERTIES_FILE + " not found in the classpath");
        }
    }
}
```

Where `configsource.properties` is:

```
protagonist.hobby=Jellyfishing

## Person
from.custom.source.person.name=From Config Source
from.custom.source.person.age=33
```

When mapping:

```
@Path("/config-mapping")
public class ConfigMappingResource {

    @Inject
    @ConfigMapping(prefix = "from.custom.source.person")
    PersonInterface personFromCustomSourceInterface;
```

It does not work any longer.

I've updated the issue title and description with the new information.

**Comment by radcortez** [comment]
In https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef, we also added support for `@ConfigMapping` during static init (before, it was only available during runtime init).

Now, static init has some limitations regarding custom users config sources. We don't automatically add them, because there is no way to tell if they are static init safe or not. For instance, if a user source at this stage requires the database, this is not possible, because the database service is not yet initialized and you get a chicken / egg situation. 

In `2.1.0` I believe, we added the `@StaticInitSafe` annotation to mark custom user sources as safe to be added during static init: https://quarkus.io/guides/config-extending-support#configsource-init. So, if you add the annotation to your should it should fix the issue. Let me know if that worked.

**Comment by Sgitario** [comment]
> In [fd4b302](https://github.com/quarkusio/quarkus/commit/fd4b3028afbfff649c6e92e8bb51a65a47fa6bef), we also added support for `@ConfigMapping` during static init (before, it was only available during runtime init).
> 
> Now, static init has some limitations regarding custom users config sources. We don't automatically add them, because there is no way to tell if they are static init safe or not. For instance, if a user source at this stage requires the database, this is not possible, because the database service is not yet initialized and you get a chicken / egg situation.
> 
> In `2.1.0` I believe, we added the `@StaticInitSafe` annotation to mark custom user sources as safe to be added during static init: https://quarkus.io/guides/config-extending-support#configsource-init. So, if you add the annotation to your should it should fix the issue. Let me know if that worked.

Adding the `@StaticInitSafe` helped to bind the `@ConfigMapping` properties, but there are still some issues related to the same commit:
- If one property is not set in the `application.properties`, but It's only configured in a remote config source (for ex: consul or Spring Cloud Server), the application will fail to start because this property is missing (which is not as it's in the remote config source).

The same scenario works fine using `2.1.0.Final`. The workaround is to add the property in the `application.properties`, but as far I see it, It's quite a big functional change (in a user view perspective).

Moreover, the bit about `@StaticInitSafe` should be noted in the migration guide.

**Comment by geoand** [comment]
This is indeed pretty problematic because it means that when `@ConfigMapping` is being used, all the configuration properties need to be known before hand, which is certainly not the case for properties coming from custom config sources.

@radcortez Why do we try to perform the mappings in static init? I mean, is there ever a need to have to have the `@ConfigMapping` mappings populated in that phase?

**Comment by radcortez** [comment]
> @radcortez Why do we try to perform the mappings in static init? I mean, is there ever a need to have to have the `@ConfigMapping` mappings populated in that phase?

Yes, for instance to support injection in JAX-RS Providers (which are initialized at static init): https://github.com/quarkusio/quarkus/issues/18333

**Comment by radcortez** [comment]
Let me try to summarize the current status, what we need and where can we go:

- @ConfigMapping instances are created twice (one for static init and another for runtime init), this is because we also have two config instances (one for each phase).
- @ConfigMapping for runtime init is pretty obvious. For static init not so much, but in the case of JAX-RS Providers, which support for `@ConfigProperty` we added support for the `@ConfigMapping` as well, which means it is available at static init as well.
- All custom sources are added to runtime init so we are fine there.
- Custom sources are only added to static init if they include the `@StaticInitSafe` annotation. This is because we don't know if the source can be safely added during static init, because it may depend on services that are not yet available (database, rest, etc).

In reality, the configuration may differ from static init to runtime init, but this has been the case for some time now. Some sources will not work properly during static init, so the difference may be there or not, depending on the configuration values. Ideally, both configs should be the same, but I don't see how due to the described limitations. Regarding mappings, they just make this issue more visible because they validate that all properties are available.

The easiest solution, for now, is to remove the automatic registration for `@ConfigMapping` during static init and use the `@StaticInitSafe` if you want to make them available (like we do with sources).

Moving forward, we need to have a more detailed discussion about static init vs runtime int config, because it keeps raising issues and it is confusing for the users. I'll prepare a doc to detail both, differences and some approaches we can take.
