### ISSUE TITLE
Update JBoss Servlet API to JBoss Jakarta 2.x

### ISSUE THREAD

**Issue by n1hility** [quarkusio/quarkus#19469]
### Description

We need to update all API deps to reference Jakarta derived artifacts. It appears the last remaining is servlet. 

The jakarta version is available here:
https://github.com/jboss/jboss-jakarta-servlet-api_spec

**Comment by gsmet** [comment]
Are you sure? Because we are not using JBoss Servlet API in Quarkus proper (it was used in Quarkus HTTP but we adjust the dependencies in Quarkus itself and we use the Jakarta one).

BUT... we use 2 JBoss API jars in Quarkus:
```
org.jboss.spec.javax.ws.rs:jboss-jaxrs-api_2.1_spec
org.jboss.spec.javax.xml.bind:jboss-jaxb-api_2.3_spec
```
And the reason we decided to keep these two is because they are used all over the place by RESTEasy so including any additional RESTEasy provider would bring these two that would conflict with the ones brought by Quarkus.

The whole story of Javax vs Jboss vs Jakarta is summarized here with the enforcer rule: https://github.com/quarkusio/quarkus/blob/main/build-parent/pom.xml#L419 .

If RESTEasy adjust, we can get rid of these two and we will be 100% Jakarta.

Happy to discuss a plan as certainly like us to be consistent.

**Comment by gsmet** [comment]
The JBoss servlet thing was just a false alarm: it was just an unused property. I remove it here: https://github.com/quarkusio/quarkus/pull/19506 .

As for JAXB and JAX-RS, I confirm they are forks from the Jakarta artifacts so we are good.

There's one thing I want us to check though: it is the provenance of the JAX-RS TCK we are using. I'll discuss with @FroMage and @geoand when they are back.

**Comment by gsmet** [comment]
@FroMage @geoand affecting you so that we can discuss the provenance of the JAX-RS TCK when you're back.

**Comment by stuartwdouglas** [comment]
It is the Jakarta one (you can see from the git history and license headers).

**Comment by stuartwdouglas** [comment]
I have also updated quarkus-http to use the jakarta artifacts.

**Comment by gsmet** [comment]
OK, so I think we can close this one. Thanks!
