### ISSUE TITLE
Reactive rest client does not get registered when the interface extends another interface from dependency 

### ISSUE THREAD

**Issue by damian-burda** [quarkusio/quarkus#19644]
### Describe the bug

We have a lot of API modules that are older (Java 8) but with valid JAX-RS annotations, that we are using in our Quarkus based applications to import the API and have easy REST access to our older services. It all works fine.

No we created the first reactive Quarkus app. Reactive controller needs to call an older service through REST. As usual I added the dependency to other service API, created a rest client that extends the interface from API, registered it. Then an adapter that will wrap the call in Uni. The client is not created and cannot be injected. At injection point I get following exception:

```
java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.arc.deployment.ArcProcessor#validate threw an exception: javax.enterprise.inject.spi.DeploymentException: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type org.acme.NOKRes
tClient and qualifiers [@RestClient]
        - java member: org.acme.RestControllerTest#nokRestClient
        - declared on CLASS bean [types=[org.acme.RestControllerTest, java.lang.Object], qualifiers=[@Default, @Any], target=org.acme.RestControllerTest]
```

What is interesting, it works without problems if:
quarkus-rest-client-jackson is used instead of quarkus-rest-client-reactive-jackson
or
the methods from API interface are copied and pasted into rest client interface

I created a reproducer for this:
https://github.com/damian-burda/rest-client-reactive-bug
just run mvnw clean install and it will not build as the test rest client can not be injected. Do one of the steps above: change dependency or copy/paste and it will work.

### Expected behavior

External API moduls with JAX-RS annotations can be also used with quarkus-rest-client-reactive-jackson as with quarkus-rest-client-jackson.

### Actual behavior

The build does not work and at runtime probably also, when a rest client (quarkus-rest-client-reactive-jackson) extends interface from dependency.

### How to Reproduce?

Checkout the reproducer https://github.com/damian-burda/rest-client-reactive-bug and try building it with mvnw clean install.

### Output of `java -version`

openjdk version "11.0.3" 2019-04-16 LTS

### Quarkus version or git rev

2.1.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by michalszynkiewicz** [comment]
Quarkus doesn't know your interface because the module containing it does not have a jandex index. 

The following section of the User's Guide has information on how to create it in the `api` jar and how to add it for a jar file that is outside your jurisdiction: https://quarkus.io/guides/cdi-reference#how-to-generate-a-jandex-index

**Comment by michalszynkiewicz** [comment]
I'll close the issue, please reopen if that's still the case after you add the index.

**Comment by damian-burda** [comment]
Adding Jandex solved the problem in the example. I should have know about it, already using it in other places. But it is not a solution for my production code, as I can not/do not want to modify the API lib and can only add index-dependency in application.yaml. This on the other hand causes new issues, as not all classes are found at runtime, since I have to use dependency exclusion on API module (old lib is full of garbage), but index is still trying to use them.

**Comment by michalszynkiewicz** [comment]
@Ladicek is there a way to filter out some classes from Jandexing?

**Comment by Ladicek** [comment]
Not that I'm aware of. Note that that's a Quarkus question, not a Jandex question.

Also, "This on the other hand causes new issues, as not all classes are found at runtime, since I have to use dependency exclusion on API module (old lib is full of garbage), but index is still trying to use them" sounds strange to me (and I don't really understand what it means). The `quarkus.index-dependency.<name>` mechanism, as far as I'm aware of, doesn't automatically index transitive dependencies -- only the artifact that you specify. So dependency exclusions shouldn't be a problem. Also the index is built and build time, so what's available at runtime shouldn't be a concern when it comes to building the index. Maybe there are beans in the dependency that are newly discovered thanks to that archive suddenly being indexed?
