### ISSUE TITLE
Expose quarkus.hibernate-orm.database.default-schema as runtime property

### ISSUE THREAD

**Issue by ccarv** [quarkusio/quarkus#19660]
### Description

The property `quarkus.hibernate-orm.database.default-schema` is evaluated only at build-time only. It would be nice to configure this property during runtime.

Our engineering environments share database instances with other teams and occasionally, the same application will be deployed to the same database instance. This means that the schema names will change based on the environment.

**Comment by yrodiere** [comment]
From what I can see, the default schema is used by Hibernate ORM while building metadata from annotations.

The value is retrieved from configuration properties in `org.hibernate.boot.internal.MetadataBuilderImpl.MappingDefaultsImpl#MappingDefaultsImpl`.

Then `getImplicitSchemaName()` is called to retrieve this value in multiple places. Mainly that's to handle cascading of defaults (which shouldn't matter in our case, I think?). But there are also places that seem to really do something with the value, during the creation of Metadata, which in Quarkus is executed during the static init, which means potentially at compile time for native images. Those are the annoying ones:

* `org.hibernate.cfg.AnnotationBinder#buildIdGenerator`
* `org.hibernate.boot.model.relational.Database#Database(org.hibernate.boot.spi.MetadataBuildingOptions, org.hibernate.engine.jdbc.env.spi.JdbcEnvironment)`
* etc.

We cannot delay the creation of `Metadata` to runtime, first because of native images that probably wouldn't work anymore, and second because of performance.

So we would need to change Hibernate ORM to delay this consumption of the "implicit schema name" until runtime. That seems possible, because from what I can see, the schema names are only used at runtime in very specific places, and `quarkus.hibernate-orm.database.default-schema` really is a default and does not override anything. So Hibernate ORM should be able to just ignore `quarkus.hibernate-orm.database.default-schema` when building metadata, and leave schema names in metadata `null` as long as possible, then at runtime when it really uses the schema name, replace any null schema name with `quarkus.hibernate-orm.database.default-schema`.

That would, however, mean upstream changes, and I'm not sure those changes are currently high-priority.

**Comment by psaraf** [comment]
as there is upstream changes, what is alternate solution to this? can we configure this property at runtime like at startup?

**Comment by yrodiere** [comment]
I don't think there is a workaround at the moment.

As I said above, we will need a fix upstream to also support changing the schema at runtime.

@Sanne, care to confirm? There's no way to override build-time Hibernate ORM properties during static init, is there? Even as an ugly, unsupported hack?

**Comment by Sanne** [comment]
> @Sanne, care to confirm? There's no way to override build-time Hibernate ORM properties during static init, is there? Even as an ugly, unsupported hack?

I can confirm it's not possible to override build-time properties. What @yrodiere outlined above seems to represent the better path forward - it might not be too hard, certainly worth trying that before considering hacking the compiler semantics :)

> as there is upstream changes, what is alternate solution to this? 

Hi @psaraf , it seems you're suggesting that upstream changes are hard to achieve. For clarity, both Yoann and me work on Hibernate more often than on Quarkus so that wouldn't be unusual for us to do, it's just a matter of prioritizing our use of time.

**Comment by ccarv** [comment]
Any movement on this?

**Comment by yrodiere** [comment]
I'm currently having a look. But don't get your hopes up just yet: I've been at it since yesterday morning, and it's looking much harder than anticipated. The feature is simple, but the code impacted by the default schema is... let's say it has a long history.

**Comment by yrodiere** [comment]
Created [HHH-14921](https://hibernate.atlassian.net/browse/HHH-14921) to track this on the ORM side.

**Comment by ccarv** [comment]
@yrodiere Ah, as with most with things. Thank you for spearheading this.

**Comment by Sanne** [comment]
Duplicate of #21351

**Comment by yrodiere** [comment]
@Sanne Sorry if I'm confused, but this (#19660) is the issue, and #21351 is the PR containing the fix. Are we supposed to mark issues as duplicate of the PR that fixes them?

**Comment by Sanne** [comment]
@yrodiere no, my mistake.Thanks I'll amend!
