### ISSUE TITLE
Colorized logging output is gone in 0.13.0

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#1972]
In 0.12.0, the logging output is colorized and like: 

```java
➜  java -jar target/my-app-runner.jar
2019-04-10 03:07:09,774 INFO  [io.quarkus] (main) Quarkus 0.12.0 started in 1.373s. Listening on: http://[::]:8080
2019-04-10 03:07:09,777 INFO  [io.quarkus] (main) Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-health]
2019-04-10 03:07:12,572 INFO  [io.quarkus] (main) Quarkus stopped in 0.009s
```

However in 0.13.0, the output is no longer colorized and changed to: 

```java
➜  java -jar target/my-app-runner.jar
Apr 10, 2019 3:07:53 AM io.quarkus.runtime.Application run
WARN: Installation of signal handlers disabled by the presence of the environment variable: DISABLE_SIGNAL_HANDLERS
Apr 10, 2019 3:07:53 AM org.xnio.Xnio <clinit>
INFO: XNIO version 3.7.0.Final
Apr 10, 2019 3:07:53 AM org.xnio.nio.NioXnio <clinit>
INFO: XNIO NIO Implementation Version 3.7.0.Final
Apr 10, 2019 3:07:53 AM org.jboss.threads.Version <clinit>
INFO: JBoss Threads version 3.0.0.Alpha4
Apr 10, 2019 3:07:53 AM io.quarkus.runtime.Timing printStartupTime
INFO: Quarkus 0.13.0 started in 0.594s. Listening on: http://[::]:8080
Apr 10, 2019 3:07:53 AM io.quarkus.runtime.Timing printStartupTime
INFO: Installed features: [cdi, resteasy, resteasy-jsonb, smallrye-health]

```

**Comment by gastaldi** [comment]
This is my project structure:

```bash
.
├── LICENSE
├── pom.xml
├── README.md
└── src
    └── main
        ├── docker
        │   └── Dockerfile
        ├── java
        │   └── io
        │       └── openshift
        │           └── booster
        │               └── http
        │                   ├── GreetingEndpoint.java
        │                   └── Greeting.java
        └── resources
            └── application.properties
```

And the contents of `application.properties`: 
```properties
➜  cat src/main/resources/application.properties 
# Configuration file
quarkus.http.host=0.0.0.0
quarkus.resteasy.path=/api
```

**Comment by gsmet** [comment]
Reproduced here with a quickstart.

**Comment by gsmet** [comment]
This is due to this patch: https://github.com/quarkusio/quarkus/commit/c8ba30fda793913d468db43ff55bce04aa8be696#diff-19c0f957ef85cdc7857ae75b02ef9503R38 .

The logger is accessed too early and thus the log manager is initialized before we set it properly.

Furthermore the logic is incorrect in:
```
if (ImageInfo.inImageRuntimeCode() && System.getenv(property) == null) {
```
in JVM mode this condition is always triggered and the signal handling is not installed and the warn message is displayed.

This is a severe regression :/. Too bad we haven't caught it yesterday...

@dmlloyd what's your take on this? TBH, I don't think having a warning at startup is a good idea because if you set the property, I suspect you don't want the warning. But even if we make it debug, we would have move the signal handling setup later.

**Comment by dmlloyd** [comment]
Just want to point out for future reference that it wasn't colorized logging that was gone due to the regression, it was the entire log manager.
