### ISSUE TITLE
CDI ignores annotations in mvn quarkus:dev

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#19799]
### Describe the bug

The application loads beans via Instance by inspecting Annotations of the beans.
When running `java -jar target/quarkus-app/*.jar` the CDI loads beans as expected. However, with `mvn quarkus:dev` annotations are missed in created proxies, and the factory cannot find the bean.

### Expected behavior

CDI should work the same in both jar and quarkus:dev mode

### How to Reproduce?

[issue.tar.gz](https://github.com/quarkusio/quarkus/files/7084415/issue.tar.gz)

1. tar -xvpzf issue.tar.gz
2. cd issue && mvn install -f lib
3. cd my-artifactId && mvn package
4. java -jar target/quarkus-app/*.jar
5. http http://localhost:8080/hello/lib_bean1 -> 200 OK 'org.me.lib1.Bean1'
6. mvn quarkus:dev
7. http http://localhost:8080/hello/lib_bean1 -> 500 Internal Server Error 'no bean with qualifier lib_bean1 found'

### Output of `uname -a` or `ver`

Linux qkvm20 5.11.0-27-generic #29~20.04.1-Ubuntu

### Output of `java -version`

openjdk version "16.0.1" 2021-04-20

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by mkouba** [comment]
So the problematic part in your code is `bean.getClass().getAnnotation(QualifierParam.class)` in the `org.me.lib1.MyLibFactory.getInstance(String)` method. You can't inspect the class of the bean instance like this because it's an internal container construct, and it could be a [client proxy](https://quarkus.io/guides/cdi#client_proxies) or an intercepted subclass. I.e. you don't necessarily get the `org.me.lib1.Bean1.class` but for example `org.me.lib1.Bean1_Subclass.class`.

It works in production because `Bean1` is `@Dependent` and is not intercepted. However, we do monitor and intercept all beans in the dev mode by default. You can disable this feature via [`quarkus.arc.dev-mode.monitoring-enabled=false`](https://quarkus.io/guides/cdi-reference#quarkus-arc_quarkus.arc.dev-mode.monitoring-enabled) BUT it will not work in the production anyway once you use a normal scope or bind an interceptor to a bean.

You can try to inject the `io.quarkus.arc.InjectableInstance` instead and use`InjectableInstance.handles()` to inspect the qualifiers via `InstanceHandle.getBean().getQualifiers()`.

HTH

**Comment by ennishol** [comment]
@mkouba  thank you for the detailed explanation!
