### ISSUE TITLE
Automatically remove trailing spaces in the application.properties file

### ISSUE THREAD

**Issue by kshpak** [quarkusio/quarkus#19956]
### Description

Trailing spaces after property in the `application.properties` file can cause unwanted errors.
Example:
1. generate an application with the `quarkus-openshift` extension
2. specify `quarkus.application.name=myservice ` (with a trailing space)
3. mvn clean package 
4. Build error 
```
Build step io.quarkus.container.image.deployment.ContainerImageProcessor#publishImageInfo threw an exception: java.lang.IllegalArgumentException: The supplied combination of container-image group 'kshpak' and name 'myservice ' is invalid
```

Is there a reason to leave trimming on developers?

**Comment by geoand** [comment]
Good question.

@radcortez does MP Config say anything about this?

**Comment by gsmet** [comment]
We don't do that globally but we apply a converter locally for the properties for which it makes sense. See `TrimmedStringConverter`.

**Comment by geoand** [comment]
Thanks for that tip @gsmet. I somehow managed to miss it :).

I'll add that for the container-image properties.

**Comment by radcortez** [comment]
> Good question.
> 
> @radcortez does MP Config say anything about this?

Nothing, because it follows the behavior of `properties` files (trailing spaces are read).

I understand that this may be inconvenient for some users, but on the other hand, we cannot blindly remove all trailing spaces for every configuration, because it means we may be changing the user configuration and we don't know if the user wants to have the space there or not.

**Comment by mmDonuts** [comment]
Just a heads up that this change changes the following behavior: if setting the group to empty using a trailing space, you need to replace it with an empty quoted string
