### ISSUE TITLE
Swagger Keycloak Invalid Parameter redirect_uri

### ISSUE THREAD

**Issue by KaiSuchomel** [quarkusio/quarkus#19985]
### Describe the bug

After migration to Quarkus 2.2.1 i got an invalid paramter: redirect_uri when trying to authorize via Keycloak.
The ServerUrl looks like the following:
`https://<serverURL>/<serviceName>/apidocs/#/`
The redirect_uri in the Swagger Authorization call looks like the following:
`XXXX&redirect_uri=<serverURL>:/<serviceName>/apidocs/XXXXX`
As you can see the redirect_uri contains an : (no port given in serverURL) which leads to the invalid parameter Issue.

### Expected behavior

The redirect_uri in the Swagger Authorization call should look like the following:
`XXXX&redirect_uri=<serverURL>/<serviceName>/apidocs/XXXXX` (no ":")

### Actual behavior

The redirect_uri in the Swagger Authorization call looks like the following:
`XXXX&redirect_uri=<serverURL>:/<serviceName>/apidocs/XXXXX` 

### Output of `uname -a` or `ver`

 5.4.0-81-generic #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "14.0.1" 2020-04-14 OpenJDK Runtime Environment (build 14.0.1+7) OpenJDK 64-Bit Server VM (build 14.0.1+7, mixed mode, sharing)

### Quarkus version or git rev

2.2.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven home: /opt/apache/mvn/apache-maven-3.8.1 Java version: 14.0.1, vendor: Oracle Corporation, runtime: /opt/java/jdk/jdk-14.0.1 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "5.4.0-81-generic", arch: "amd64", family: "unix"

**Comment by KaiSuchomel** [comment]
@phillip-kruger FYI

**Comment by phillip-kruger** [comment]
Thanks @KaiSuchomel !

**Comment by phillip-kruger** [comment]
@KaiSuchomel - seems like this is a bug and it happens when there is no port (so 80 for http and 443 for https). For now you can try a workaround by setting this property:

`quarkus.swagger-ui.oauth2-redirect-url=https://smartmom-suite.devalm.gec.io/address-svc/apidocs/oauth2-redirect.html`

You might want to scope this per environment, so for example for prod:

`%prod.quarkus.swagger-ui.oauth2-redirect-url=https://smartmom-suite.devalm.gec.io/address-svc/apidocs/oauth2-redirect.html`

I'll do a fix for this in SmallRye soon

**Comment by phillip-kruger** [comment]
Fix in SmallRye: https://github.com/smallrye/smallrye-open-api/pull/906. Will be in SmallRye OpenAPI 2.1.14
