### ISSUE TITLE
SmallRye Metrics: Gauge not showing up

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#20028]
### Describe the bug

when using the gauge annotation

 ````
@Gauge(name = "highestPrimeNumberSoFar", unit = MetricUnits.NONE, description = "Highest prime number so far.")
    public Long highestPrimeNumberSoFar() {
        return 100L;
    }
````
The metric does not exist in quarkus 2.2.2.Final

### Expected behavior

q/metrics/application contains the gauge

### Actual behavior

the gauge is not present

### How to Reproduce?

https://github.com/rmanibus/quarkus_20028

### Output of `java -version`

openjdk version "15.0.1" 2020-10-20 OpenJDK Runtime Environment AdoptOpenJDK (build 15.0.1+9) OpenJDK 64-Bit Server VM AdoptOpenJDK (build 15.0.1+9, mixed mode, sharing)

### Quarkus version or git rev

2.2.2.Final

**Comment by jmartisk** [comment]
Hi @rmanibus  - the reason you're not seeing your gauge is probably because gauges get registered only when the owning bean is instantiated. You need to make sure that your REST endpoint, or application-scoped bean, is called first.

This applies to only gauges - it is because gauges are a bit special in the sense that to be able to register a gauge, you need an actual bean instance to already exist - because otherwise, if a call arrived to get the value of the gauge, the runtime would not know where to obtain that value. This is in accordance with the spec: https://download.eclipse.org/microprofile/microprofile-metrics-3.0/microprofile-metrics-spec-3.0.html#_responsibility_of_the_microprofile_metrics_implementation

I might be mistaken but I think that if you switch to the Micrometer extension (with the MP Metrics compatibility layer) then you'll see the gauges immediately because the runtime will force to create an instance early

**Comment by rmanibus** [comment]
thanks @jmartisk , this make sens. I tried to add a StartupEvent listener on the bean containing the gauge so it get instantiated

````  void onBoot(@Observes StartupEvent e) {
  }
`````
but I still can't see it !

**Comment by jmartisk** [comment]
In the Edit, I meant that they don't work with Micrometer. With pure SmallRye Metrics extension it should work.

Are you sure you can't see the gauge after adding `@Observes StartupEvent`? I just tried it and it appeared immediately after start.

**Comment by rmanibus** [comment]
yes I just saw that it is working on the demonstrator but not on my project.
in fact I was counting some data in DB and I needed a transaction. but it failed without any messages in the logs !

**Comment by ebullient** [comment]
Are we good to go? Can this be closed?

**Comment by rmanibus** [comment]
yes thanks @ebullient
