### ISSUE TITLE
Add documentation for console dark mode

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#2004]
Today the property is quarkus.log.console.darken / QUARKUS_LOG_CONSOLE_DARKEN
Let's add a documentation in the log guide.

**Comment by geoand** [comment]
There is a slight problem however, when one adds `quarkus.log.console.darken` to `application.properties` that value is ignored (because https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/logging/LoggingResourceProcessor.java#L116 takes precedence). 
The environment variable however works just fine

**Comment by gsmet** [comment]
This is included in the doc now.
