### ISSUE TITLE
Add tests for the startup log output

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2005]
It got broken numerous times either in dev mode or java mode.

We need to add tests for that. And soon.

@cescoffier said the easiest would be to add tests in the Maven tests. But we also need to test the output of `java -jar my-runner.jar`

**Comment by cescoffier** [comment]
That should be possible to implement at the same place:

1. Use the maven invoker to do `mvn package`
2. Use the Java executor (do we have it already?) to do `java -jar ...`

**Comment by machi1990** [comment]
> 1. Use the maven invoker to do `mvn package`

@cescoffier, won't the first option collide with this issue [migrate maven invoker integration tests] (https://github.com/quarkusio/quarkus/issues/1909)?

**Comment by gsmet** [comment]
I think he was talking about the Maven invoker API, not the invoker plugin.

**Comment by vorburger** [comment]
> Use the Java executor (do we have it already?) to do java -jar ...

@cescoffier what is the Java executor? This issue seems kind of related to what I'm up to in #1986...

It should be trivial to assert (logging) output from running the JAR (and the Native) there.

/Cc @stalep

**Comment by vorburger** [comment]
FYI #1986 now proposes a new `QuarkusJavaLauncher` which should come in handy for this.

**Comment by gsmet** [comment]
@machi1990 were you interested by this one? It became pretty critical considering the number of times we broke the output.

I think for now we should stick to the standard APIs, we can still revisit later once we have the structure of the tests.

**Comment by machi1990** [comment]
I started to check this, I run `mvn package` and then run `java -jar` but i have a problem with the ProcessBuilder API running `java` commands. Seems like it cannot find the java bin. Any ideas? 

Otherwise my idea is to redirect the output in a log file and then check if it contains coloured output.

**Comment by gsmet** [comment]
Did you use something like `System.getProperty("java.home") + "/bin/java"` to get the Java home? (obviously, it needs to be made portable for Windows with proper separator char and `java.exe`).

So we should check it contains coloured output but we should also check that:
* it contains the list of features
* it does not contain `JBoss Threads version`

**Comment by gsmet** [comment]
@machi1990 ^

**Comment by machi1990** [comment]
> Did you use something like `System.getProperty("java.home") + "/bin/java"` to get the Java home? (obviously, it needs to be made portable for Windows with proper separator char and `java.exe`).

I tried something like that but had the same error after stealing some piece of code from `QuarkusDev.java` but had the same error. I'll investigate more tomorrow. 

> So we should check it contains coloured output but we should also check that:
> - it contains the list of features
> - it does not contain JBoss Threads version

Once I got the process running I'll check this checks which seem appropriate.

**Comment by vorburger** [comment]
@gsmet @machi1990 have you seen that in  #1986 I am a [QuarkusJavaLauncher](https://github.com/vorburger/quarkus/blob/issue-1623_actually-add-gradle-it-run_ch.vorburger.exec/devtools/gradle-it-run/src/test/java/io/quarkus/gradle/it/QuarkusJavaLauncher.java) for this purpose?

**Comment by machi1990** [comment]
@vorburger thanks for the pointer. I managed to launch the bin after properly finding the java executable. Since your work on `QuarkusJavaLauncher.java` is not already in the master, I decided to use some piece of code that was already in `QaurkusDev.java`.

@gsmet @cescoffier @dmlloyd , any pointer on how to test for coloured output? [here](https://github.com/machi1990/quarkus/commit/b916ea4054804cce8257e064a2fc3d21612685b4#diff-43dc13a840a707728a51169e1b679af1R387) is where I wish to add it.

**Comment by dmlloyd** [comment]
Testing to ensure that `java.util.logging.LogManager.getLogManager()` is an instance of `org.jboss.logmanager.LogManager` would get you most of the way there.

Theoretically you could probe the fields of the console handler to see if it has decided to output in color or not.  But that seems less important since 99% of the cases where color output is lost are due to losing the entire log manager (and thus formatting, log level filtering, etc.).

**Comment by machi1990** [comment]
@dmlloyd thanks for the detailed response. 

I finally decided to leave aside testing for coloured output and instead focus on formatting, log level, installed features etc [PR #2116](https://github.com/quarkusio/quarkus/pull/2116).
