### ISSUE TITLE
@ServerResponseFilter annotated filter is called repeatedly after the filter throws an exception 

### ISSUE THREAD

**Issue by test210820** [quarkusio/quarkus#20254]
### Describe the bug

FilterA throw exception -> catched by ExceptionMapper and then be handled -> FilterA throw exception

### Output of `uname -a` or `ver`

windows10

### Output of `java -version`

java11

### Quarkus version or git rev

2.2.2

**Comment by geoand** [comment]
Can you attach a small reproducer please?

**Comment by test210820** [comment]
Filter:
```java
@ServerResponseFilter
public void doFilter(ContainerRequestContext containerRequestContext,
                     ContainerResponseContext responseContext) {


    int a = 1 / 0;
...
}
```

ExceptionMapper:

```java
@ServerExceptionMapper(value = {Exception.class})
  public Uni<RestResponse<String>> handle(Exception e) {
      log.error("========WebExceptionHandler=====>", e);

      return Uni.createFrom().item(RestResponse.ok("An exception happened!"));
  }
```

**Comment by test210820** [comment]
@geoand

**Comment by geoand** [comment]
According to the JAX-RS specification, what we are doing **is** correct. The spec mentions:

> A  response mapped from an exception MUST be processed using the ContainerResponse filter chain and the
WriteTo interceptor chain (if an entity is present in the mapped response). The number of entries in these
chains depends on whether a resource method has been matched or not at the time the exception is thrown.

So you'll have to make sure your response filter does not throw an exception in order to prevent the behavior you are seeing.
