### ISSUE TITLE
The configuration item quarkus.native.container-runtime will cause the configuration item quarkus.native.container-build=false to be invalid

### ISSUE THREAD

**Issue by test210820** [quarkusio/quarkus#20258]
### Describe the bug

application.properties

![image](https://user-images.githubusercontent.com/65008815/133932659-40de6455-75d8-4fea-bf92-021feb1f62af.png)

![image](https://user-images.githubusercontent.com/65008815/133932813-1331dc40-7e82-45b3-a24b-679a97249313.png)

![image](https://user-images.githubusercontent.com/65008815/133932786-a242466c-7dcb-4c05-aa7f-8f731ead0667.png)

### Output of `uname -a` or `ver`

windows10

### Output of `java -version`

11

### Quarkus version or git rev

2.2.2-final

**Comment by geoand** [comment]
Well, we need to pick on or the other - in this case we seem to picking the latter.

I guess we could make this an error though, WDYT @zakkak ?

**Comment by zakkak** [comment]
> Well, we need to pick on or the other - in this case we seem to picking the latter.
> 
> I guess we could make this an error though, WDYT @zakkak ?

If I recall correctly the reasoning behind this was that if you are setting `container-runtime` then you probably are interested in using a container to build the native image. I can see however that someone might have this set in the application properties file while experimenting with `-Dquarkus.native.container-build=false` on the command line.

I would personally prefer honoring `container-build` and throwing a warning instead of an error, but I think Quarkus users are more suitable to answer this :)
