### ISSUE TITLE
Hibernate entities fields access level was broken after migration from 1.12 to 2.2.3

### ISSUE THREAD

**Issue by RustamSultansoy** [quarkusio/quarkus#20282]
### Describe the bug

I have a base entity like that
```
@FieldDefaults(level = AccessLevel.PUBLIC)
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@MappedSuperclass
public class BaseEntity {

    @Id
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "default_gen")
    Long id;

    @CreationTimestamp
    @Column(updatable = false)
    LocalDateTime createdOn;
}
```
And some child classes.
In old version of quarkus after compilation it still stayed public.
In 2.2.3 after compilation I noticed that all fields except id and transiens are protected. All direct access was changed to getters and setters.
My code:
<img width="842" alt="Screenshot 2021-09-20 at 22 05 25" src="https://user-images.githubusercontent.com/73348899/134064931-a63f2bc7-8067-40d5-9044-8df6537f0dbf.png">
Compiled one:
<img width="863" alt="Screenshot 2021-09-20 at 22 05 36" src="https://user-images.githubusercontent.com/73348899/134064977-b6e676df-a33d-4099-89eb-9e97d9f11ef6.png">

Is there any property to disable such behavior? 

### Expected behavior

public fields stay public

### Actual behavior

public fields transformed to private

### Output of `java -version`

11

### Quarkus version or git rev

2.2.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.1

**Comment by yrodiere** [comment]
To be clear: accessing public fields directly on Hibernate ORM entities prevents lazy-loading from working. That's why Quarkus transforms direct field access into getter/setter calls.

Quarkus also turns public fields in entities into protected fields in order to make sure that if the application bypasses the getters/setters by mistake, an exception will be thrown: such access should not happen and *will* lead to problems in applications, so it should be considered a bug.

This transformation should not impact the code you write in any way: you still write direct field access in your source code, and Quarkus will automatically transform that into getter/setter calls. This should be totally transparent.

Could you explain why fields being transformed from public to protected is a problem for you? Do you have a stack trace somewhere?

**Comment by RustamSultansoy** [comment]
@yrodiere thanks for clarifying.
in my case I've used reflection to access parent class field by name like clazz.getField("somePublicField")
currently method was changed and looks like that:
```
public Field getField(Class<?> clazz, String fieldName) throws NoSuchFieldException {
        try {
            return clazz.getDeclaredField(fieldName);
        } catch (NoSuchFieldException e) {
            Class<?> superClass = clazz.getSuperclass();
            if (superClass == null) {
                throw e;
            } else {
                return getField(superClass, fieldName);
            }
        }
    }
```

**Comment by yrodiere** [comment]
@RustamSultansoy Thanks for the details. I can see how changing the field from public to protected can impact such code, indeed.

Be careful if you're using this to retrieve the value of a field: you really should go through the Quarkus-generated getters instead, so that lazy-loading works correctly. If you don't retrieve values from fields using reflection, you're fine.
