### ISSUE TITLE
Qute fails to resolve properties on enum classes only when native compiled

### ISSUE THREAD

**Issue by jayv** [quarkusio/quarkus#20421]
### Describe the bug

Templates render `NOT_FOUND` in native mode (works fine on JVM) for enum classes when attempting to access a member field of getter of the enum class.

### Expected behavior

Render the member field or method both in JVM as in native mode.

### Actual behavior

Qute resolves the property in JVM mode just fine but resolves as `NOT_FOUND` when compiled to native. Current workaround is to override `toString()` which is the only way to render an enum it seems.

### How to Reproduce?

```kt
data class AuthenticatedUser( 
    val roles: Set<Role>
)

enum class Role(val group: String) {
   
    BASIC("SomeBasicGroup"),
    ADMIN("AdminGroup);

    // this is a workaround
    override fun toString(): String { 
        return group
    }
}


```

```html
            {#for role in user.roles.orEmpty}
                <li>{role.group}</li> 
            {/for}
```

The above renders `NOT_FOUND` when native compiled, however when `{role}` is used it works, so `toString()` can be called. Adding an other method or getter also results in `NOT_FOUND` again only when native compiled.

### Output of `uname -a` or `ver`

quay.io/quarkus/centos-quarkus-maven:21.0-java11

### GraalVM version (if different from Java)

quay.io/quarkus/centos-quarkus-maven:21.0-java11

### Quarkus version or git rev

1.13.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.6.2

**Comment by mkouba** [comment]
Hi @jayv, this is expected. In the JVM a fallback reflection value resolver is used, i.e. enum constants are read as regular fields. Of course, this does not work for native. There are several ways how to solve the problem for the native image:

1. Make use of [type-safe templates](https://quarkus.io/guides/qute-reference#typesafe_templates) or [type-safe expressions](https://quarkus.io/guides/qute-reference#typesafe_expressions) (preferred); this way a specialized value resolver is generated automatically
2. Annotate the enum class with [`@TemplateData`](https://quarkus.io/guides/qute-reference#template_data) so that a specialized value resolver is generated 
3. Annotate the enum class with `@io.quarkus.runtime.annotations.RegisterForReflection` to make the reflection value resolver work
