### ISSUE TITLE
Qute fails to resolve class public property when native compiled

### ISSUE THREAD

**Issue by tehnodev** [quarkusio/quarkus#20469]
### Describe the bug

TemplateException for class public property. It happens only when app is native compiled, from jar works as expected

### Expected behavior

<p>test</p>

### Actual behavior

io.quarkus.qute.TemplateException: Property "name" not found on the base object "org.acme.Car" in expression {car.name} in template ...

### How to Reproduce?

Class
```
public class Car {
    public String name;
}
```

Template in file car.html
`<p>{car.name}</p>`

Handler
```
@Path("/hello")
public class GreetingResource {
    @Inject
    Template car;

    @GET
    @Produces(MediaType.TEXT_HTML)
    public TemplateInstance test() {
        var c = new Car();
        c.name = "test";
        return car.data("car", c);
    }
}
```

### Output of `uname -a` or `ver`

Windows 10 Pro with Docker Desktop

### Output of `java -version`

openjdk 11.0.12 2021-07-20

### GraalVM version (if different from Java)

Container quay.io/quarkus/ubi-quarkus-native-image:21.2-java11

### Quarkus version or git rev

2.2.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

### Additional information

To compile binary on Windows 10 Pro with Docker Desktop installed i use
`./mvnw package -Pnative -Dquarkus.native.container-build=true`
Native binary is executed on Centos 7.

**Comment by mkouba** [comment]
Hi @tehnodev, this is expected. In the JVM a fallback reflection value resolver is used, but of course, this does not work for native. There are several ways how to solve the problem:

 - Make use of [type-safe templates](https://quarkus.io/guides/qute-reference#typesafe_templates) or [type-safe expressions](https://quarkus.io/guides/qute-reference#typesafe_expressions) (preferred); this way a specialized value resolver is generated automatically
 - Annotate the class with [@TemplateData](https://quarkus.io/guides/qute-reference#template_data) so that a specialized value resolver is generated
 - Annotate the class with `@io.quarkus.runtime.annotations.RegisterForReflection` to make the reflection value resolver work

I think that we should add a dedicated section to the docs because we had quite a few similar issues recently...

**Comment by tehnodev** [comment]
Thank you. It worked!
