### ISSUE TITLE
Access multi tenant database programmatically

### ISSUE THREAD

**Issue by joggeli34** [quarkusio/quarkus#20533]
### Description

We have two use cases where we want to access the tenant-databases without coming from a http request. I didn't find any documentation on how to do it, so I'm not sure if this is just a request for a documentation or for the feature it self.

1. We have some db-cleanup tasks running in schedulers. Therefor we need all the connections so that we can loop over them and inject them to the database services.
2. We get events over mqtt and other messages buses where we use custom connectors. There we need a way to resolve the tenant per message.

**Comment by yrodiere** [comment]
Out of the top of my head, I'd say you can handle that in your custom tenant resolver, and have that resolver be application-scoped so that it can be used outside of any request?

Something like that, maybe:

```
@PersistenceUnitExtension 
@ApplicationScoped // This is important
public class CustomTenantResolver implements TenantResolver {

    public static final ThreadLocal<String> EXPLICIT_TENANT_ID = new ThreadLocal<>();

    public static void setTenantId(String tenantId) {
        if (tenantId == null) {
            EXPLICIT_TENANT_ID.remove();
        }
        else {
            EXPLICIT_TENANT_ID.set(tenantId);
        }
    }

    @Inject
    Instance<RoutingContext> context;

    @Override
    public String getDefaultTenantId() {
        return "base";
    }

    @Override
    public String resolveTenantId() {
        if (context.isResolvable()) {
             // In a request: get the tenant from the request context
             return resolveTenantIdInRequest(context.get());
        }
        else {
            // Not in a request: get the tenant from our thread local
            return EXPLICIT_TENANT_ID.get();
        }
    }

    private String resolveTenantIdInRequest(RoutingContext context) {
        String path = context.request().path();
        String[] parts = path.split("/");

        if (parts.length == 0) {
            // resolve to default tenant config
            return getDefaultTenantId();
        }

        return parts[1];
    }

}
```

Then you'll have to call `CustomTenantResolver.setTenantId("myTenantId")` before your background tasks, and `CustomTenantResolver.setTenantId(null)` after each task.

I didn't test this, though. I hope it'll work :)

**Comment by yrodiere** [comment]
There are probably other options if you use advanced CDI features involving custom CDI contexts or allowing to simulate a request context, but I don't know exactly how to do that from application code.

**Comment by yrodiere** [comment]
Since I stumbled upon the annotation while working on something else, I'll just mention that `@ActivateRequestContext` (`javax.enterprise.context.control.ActivateRequestContext`) can be used on a service method to create a request context even though there's no request . I've seen it used in tests, but maybe it can work elsewhere.

As to how you can set the tenant, well, I suppose that following my suggestions above will still be necessary.

**Comment by yrodiere** [comment]
As I did not get a response from you, I'll assume my answer was satisfying or you don't need one anymore.

Closing.

**Comment by loban** [comment]
Just in case someone stumbles onto this ticket while searching for a way to "access many multi-tenant databases in on service method", the exampl that @yrodiere outlined does **not** work. I filed a bug https://github.com/quarkusio/quarkus/issues/33723 regarding this.

**Comment by yrodiere** [comment]
> the example that @yrodiere outlined does not work.

To be fair nobody here was talking about accessing multiple tenants from the same request. I'll answer on your other issue.
