### ISSUE TITLE
Regression: Can't inject beans annotated with `@ConfigProperties`

### ISSUE THREAD

**Issue by Sgitario** [quarkusio/quarkus#20610]
### Describe the bug

Having:

```java
@ConfigProperties(prefix = "server")
public class BulkOfPropertiesConfiguration {
    String url;
    String host;
    String path;
    int port;

    @ConfigProperty(name = "port")
    int repeatedPort;

    @ConfigProperty(name = "url.with.default.found")
    String urlWithDefaultAndConfigFound;
}
```

And this being in use in:

```java
@Path("/bulk-properties")
public class BulkOfPropertiesResource {

    @Any
    @Inject
    BulkOfPropertiesConfiguration config;

    @GET
    @Path("/url")
    public String getUrl() {
        return config.url;
    }
```

The app fails to start because says that can't find BulkOfPropertiesConfiguration:

```
[ERROR] Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.quarkus.qe.properties.bulk.BulkOfPropertiesConfiguration and qualifiers [@Any]
[ERROR]         - java member: io.quarkus.qe.properties.bulk.BulkOfPropertiesResource#config
[ERROR]         - declared on CLASS bean [types=[java.lang.Object, io.quarkus.qe.properties.bulk.BulkOfPropertiesResource], qualifiers=[@Default, @Any], target=io.quarkus.qe.properties.bulk.BulkOfPropertiesResource]
[ERROR]         at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:567)
[ERROR]         at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:470)
[ERROR]         at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:256)
[ERROR]         ... 13 more
```

This is caused by this change: https://github.com/quarkusio/quarkus/pull/19965/commits/6378f80f1c4ff0ad9a50e1cc9944163e2a8eeeeb

I tried to annotate the BulkOfPropertiesConfiguration with `@Unremovable` and also remove the `@Any` but nothing helped.

### How to Reproduce?

1. git clone `https://github.com/Sgitario/quarkus-test-suite`
2. cd quarkus-test-suite
3. git checkout reproducer_20610
4. cd properties
5. mvn clean verify

**Comment by rsvoboda** [comment]
I have noticed too, thanks for quick reporting @Sgitario

**Comment by radcortez** [comment]
So this is not a bug. Yes, it was working before but it was not intended that way.

The `@ConfigProperties` qualifier must be used in the injection point when injecting a relevant bean. Of course, you can omit `@Inject`. Here is the relevant discussion on MP Config: https://github.com/eclipse/microprofile-config/issues/629.

We also have some additional discussions here: https://github.com/quarkusio/quarkus/issues/19526

We can certainly make it work again, but I would prefer to make it as it was intended. I think at some point when the MP spec was not final, the qualifier was not required. Since we wrote the implementation before, we never noticed this little detail that change (and there is no TCK test for it either).

Any thoughts?

**Comment by radcortez** [comment]
Added the clarification here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.4#microprofile-config.

**Comment by Sgitario** [comment]
> Added the clarification here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-2.4#microprofile-config.

Thanks @radcortez ! Closing this issue.
