### ISSUE TITLE
How can I best expose a secure Route?

### ISSUE THREAD

**Issue by iocanel** [quarkusio/quarkus#20644]
### Description

This originates from Stack Overflow: https://stackoverflow.com/questions/69502561/quarkus-openshift-route-annotations#

Possible answer: https://docs.openshift.com/container-platform/4.8/networking/routes/secured-routes.html

We do need to improve the user experience and the documentation here.

**Comment by rquinio** [comment]
Not sure it's possible to avoid a `quarkus.openshift.route.tls` (and `quarkus.kubernetes.ingress.tls`) build time config to enable TLS & termination, because quarkus.http.ssl.certificate.* can change at runtime, so values are not known when generating the manifests ?

- With  `termination: passthrough` a certificate would have to be issued for myhost.com
- With `termination: reencrypt` I'd expect a certificate to be issued instead for the K8s service hostname <service.name>.<service.namespace>.svc(.cluster.local) cf https://docs.openshift.com/container-platform/4.8/security/certificates/service-serving-certificate.html
- With `termination: edge` no ssl would be configured for quarkus.http

**Comment by cescoffier** [comment]
Somewhat related to #24751.

**Comment by iocanel** [comment]
We could possible take `quarkus.http.xxx` into consideration in order to set tls termination and policy.
@Sgitario I think that you have done some related work. Is this something that is feasible makes sense?

**Comment by Sgitario** [comment]
Personally, I would not overcomplicate the logic here to magically/automatically configure the Ingress tls termination when configuring the `http.ssl` ... properties. Mostly, because it's not that simple: the certificates need to be in a Kubernetes secret. 

So, if users still want to proceed, they would have to manually configure the Ingress TLS following the guide: https://quarkus.io/version/main/guides/deploying-to-kubernetes#exposing-with-secured-ingress.

And, sooner than later, we'll have the Quarkus Cert-Manager extension (see [request](https://github.com/quarkusio/quarkus/issues/25874)) that will automatically configure the HTTP SSL and the Kubernetes Ingress TLS properties. This extension will also generate the certificates in a secret by using the Cert-Manager operator. I would say that when available, this should be the recommended way for users to enable SSL.

**Comment by Sgitario** [comment]
Yes, we need to expose these required configuration properties for secured routes. 
I've just added the "good first issue" label, just in case a newcomer wants to implement this. Otherwise, I will take a look when I have the capacity.
