### ISSUE TITLE
Please update the bom version of all jackson modules to 2.13

### ISSUE THREAD

**Issue by MartinX3** [quarkusio/quarkus#20690]
### Description

jackson  2.13 adds support for kotlin 1.5.30 which is used in quarkus 2.3 (1.5.31)

### Implementation ideas

Pushing the package versions in the quarkus-bom

**Comment by geoand** [comment]
See https://github.com/quarkusio/quarkus/pull/20651 for details. We will be holding off on this for now

**Comment by MartinX3** [comment]
@netodevel thank you for the information :)
My project is based on java 11 LTS and I think the next java bumb will be java 17 LTS. :)
But I'm unsure if Quarkus 2.3 or 2.4 is the official java 17 version, since I saw 2.4 milestones in combination with java 17 in this project.

**Comment by netodevel** [comment]
@geoand, 
but only in jvm mode right?
in native mode (graalvm) is also going well?

**Comment by netodevel** [comment]
@geoand,

I'm using records for dto's in my project and in native mode it fails if I don't specify
`@RegisterForReflection` on record.

I will prepare a better sample and open an issue.

Another detail is that it still doesn't have an image to generate a native image for java 17.

the latest is 16:
quay.io/quarkus/ubi-quarkus-native-image:21.2.0-java16

(I imagine that because graalvm hasn't informed full support for the jav 17 yet)

**Comment by gsmet** [comment]
I wonder if we will have to tweak our build steps for records. Are they handled like regular classes by Jandex?

**Comment by netodevel** [comment]
@gsmet, 
I'm already testing a tweak here in the `quarkus-jackson` extension if it works, I open a pull request to be evaluated;
