### ISSUE TITLE
Reactive routes incorrect json serialization

### ISSUE THREAD

**Issue by MM87037** [quarkusio/quarkus#21044]
### Describe the bug

Reactive routes resources returning invalid json when using `@RolesAllowed` annotation. Without the annotation its working fine.

Its working fine using Quarkus 2.3 version

### Expected behavior

API should return below JSON response

```javascript
[
	{
		"message": "Hello!"
	},
	{
		"message": "Hola!"
	},
	{
		"message": "Bonjour!"
	},
	{
		"message": "Ciao!"
	}
]
```

### Actual behavior

Instead its returning

```javascript
{"message":"Hello!"}{"message":"Hola!"}{"message":"Bonjour!"}{"message":"Ciao!"}
```

### How to Reproduce?

Reproducer: https://github.com/MM87037/reactive-routes

Steps:

1. Run `mvn clean verify` to see the failure

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17+35 (build 17+35)
OpenJDK 64-Bit Server VM Temurin-17+35 (build 17+35, mixed mode, sharing)

### Quarkus version or git rev

2.4.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by geoand** [comment]
This was caused by https://github.com/quarkusio/quarkus/commit/eafcc01af2827561e0dbfbbac03d143418191b82 in  combination with the way that the generated invoker checks if the return type is a json array (by `io.quarkus.vertx.web.runtime.MultiJsonArraySupport#isJsonArray`).

@mkouba I would assume that the proper way to handle this is to not check the type of the returned `Multi`, but to check whether the return type is `application/json` (and ndjson and SSE respectively).

**Comment by mkouba** [comment]
> but to check whether the return type is application/json (and ndjson and SSE respectively).

Hm, what do you mean with _the return type is application/json_? I you're talking about the content type of the response then I don't think this would help because by default for a `Multi` return type the items are [written one by one, in the response](https://quarkus.io/guides/reactive-routes#returning-multis). And the docs is clear that you need to wrap the response with a `JsonArrayMulti`.

Anyway, I'm not the author of this code. @cescoffier might have an idea how to fix that?

**Comment by geoand** [comment]
> > but to check whether the return type is application/json (and ndjson and SSE respectively).
> 
> Hm, what do you mean with _the return type is application/json_? I you're talking about the content type of the response then I don't think this would help because by default for a `Multi` return type the items are [written one by one, in the response](https://quarkus.io/guides/reactive-routes#returning-multis). And the docs is clear that you need to wrap the response with a `JsonArrayMulti`.
> 

Yes, I meant the produced `content-type`. 
What I am saying is that what the docs are describing does **not** work when `@RolesAllowed` is being used because of the change I mentioned above. Essentially the cast that is performed no longer works.
So what I am proposing is that instead of doing the case to check, that the check be done based on the produced content-type.

**Comment by mkouba** [comment]
> Essentially the cast that is performed no longer works.

Yes, I get it ;-). But I'm trying to explain that a check based on the produced content-type would not work, because by default we don't return a json array for a `Multi` with produced content-type `application/json` but a list of chunks where each chunk represents a `Multi` item.

**Comment by geoand** [comment]
Right, there would also need to be a check for the type of the multi, but later on in the pipeline (and it could print a proper error message pointing to the docs).

**Comment by mkouba** [comment]
I'm not sure it's doable but if it is then +1.

**Comment by cescoffier** [comment]
Sorry, I just discovered this issue. Having a look.

**Comment by michalszynkiewicz** [comment]
unfortunately the fix caused security annotations not to work on endpoints returning Multi

**Comment by mkouba** [comment]
> unfortunately the fix caused security annotations not to work on endpoints returning Multi

Do we have a test for this particular use case?

**Comment by michalszynkiewicz** [comment]
Apparently we only have a test for `Uni` :(

**Comment by cescoffier** [comment]
I've opened another PR (#21643) that does not fix the issue but provides a new way to declare the Multi serialization. I have deprecated the other way (still working, but not when security is enabled) and I would recommend switching to this new approach (which also works with security).
