### ISSUE TITLE
%custom.quarkus.config.profile.parent=dev in 2.4.1 not working (as in 2.4.0)

### ISSUE THREAD

**Issue by bumbel42so** [quarkusio/quarkus#21334]
# Describe the bug
Hello, 

i´m using custom profiles with profile parents and in 2.4.1 profile.parent is not used as backup as expected: 

application.properties
````
my.config1=prod
my.config2=prod
%dev.my.config1=dev
%custom.quarkus.config.profile.parent=dev
%custom.my.config2=custom
````

Config.java
````
@ConfigMapping(prefix = "my")
public interface Config {
	String config1();
	String config2();
}
````

GreetingResource.java
````
@Inject
Config config;

@GET
@Produces(MediaType.TEXT_PLAIN)
public String hello() {
    return String.format("config1 is %s; config2 is %s", config.config1(), config.config2());
}
````

# Expected behavior
*Output at localhost:8080 with Quarkus 2.4.0:*
config1 is dev; config2 is custom

# Actual behavior
*Output at localhost:8080 with Quarkus 2.4.1:*
config1 is prod; config2 is custom

Project is attached as zip, run with ``mvn clean compile quarkus:dev -Dquarkus.profile=custom``

[code-with-quarkus.zip](https://github.com/quarkusio/quarkus/files/7511378/code-with-quarkus.zip)

**Comment by radcortez** [comment]
Hi @bumbel42so,

This was actually working by accident (setting the `quarkus.config.profile.parent` in a profile, set by `quarkus.profile`). For instance, in SmallRye Config if you try to use the same approach (with the SR Config configuration), it won't work. Both Quarkus and SR Config configuration should be consistent.

In reality, this was never intended to work, since these configuration keys are a bit special since they are used to configure the configuration. My recommendation is to just use the unprofiled name directly `quarkus.config.profile.parent` (either in `application.properties` or by a system property).

Do you have a strong use case for this? I may be able to readd the feature in SmallRye Config, but it is going to need to considerable changes.

**Comment by radcortez** [comment]
This was removed by: https://github.com/quarkusio/quarkus/pull/21064.

See also: https://github.com/smallrye/smallrye-config/issues/663

**Comment by bumbel42so** [comment]
Hi @radcortez, 
thanks for the answer. You are right, i misunderstood the documentary. 
My intention was to have a custom dev profile where i set my db-config to another database then in default dev profile but use the other dev params as fallback. 
But i´m able to solve this use case on a different way (e.g. set all paramaters for custom profile).
