### ISSUE TITLE
quarkus.rest-client.* properties not present in all-config guide

### ISSUE THREAD

**Issue by xstefank** [quarkusio/quarkus#21488]
### Describe the bug

`quarkus.rest-client.*` properties are not included in https://quarkus.io/guides/all-config. Not sure if this is intended.

**Comment by geoand** [comment]
cc @TomasHofman

**Comment by TomasHofman** [comment]
I will have a look, but right now I'm unable to generate anything at all from the docs folder.

Running `./mvnw package -f docs/` results in:

```
...
[INFO] --- jbang-maven-plugin:0.0.7:run (generate-build-item-doc) @ quarkus-documentation ---
[WARNING] JBang not found. Downloading the latest version
[INFO] Using JBang v.0.83.1

[INFO] Error: Unable to initialize main class quarkusbuilditemdoc
[INFO] Caused by: java.lang.NoClassDefFoundError: org/eclipse/collections/api/multimap/MutableMultimap
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

**Comment by TomasHofman** [comment]
@geoand you did develop parts of the rest-client extension so I would ask you for opinion.

I think that the rest-client config properties are not included in the all-config guide because the `@ConfigRoot` annotated class is not part of the extension jar directly, but it's consumed from a dependency jar (which is shared between the rest-client classic and rest-client-reactive).

So the options are:

1) Turn the config jar into a proper extension (the directory structure would change a bit to honor the standard extension layout). The classic rest-client and rest-client-reactive extensions would depend on this new extension.

2) Do some maven trick (shade plugin?) that would physically copy the config classes over to each rest-client extension, so they are part of the extension jar.

3) Hard code something into the `AllConfigGenerator` class so that the jar containing the config root is included in the processing.

I would say 1) is the cleanest and least surprising way. Unless you think it's a bad idea for some reason I would go that way.

**Comment by geoand** [comment]
I am pretty sure it was @michalszynkiewicz you developed the rest client, but IMHO, option 1) is best

**Comment by TomasHofman** [comment]
OK, @michalszynkiewicz interested in your opinion as well :).

I don't know if 1) will be backportable to 2.4 or 2.5 branches, which might be necessary to sort out quarkus.io doc pages. If not I may need to hack `AllConfigGenerator` (in that one branch only).

**Comment by michalszynkiewicz** [comment]
👍🏻 on the first one, sorry for the late response.
