### ISSUE TITLE
quarkus.hibernate-orm.packages not working

### ISSUE THREAD

**Issue by liteultom** [quarkusio/quarkus#21682]
### Describe the bug

When I set `quarkus.hibernate-orm.packages` in my config file :
```
quarkus.hibernate-orm.packages=my.custom.entities.package
```
Table for entities from other package are still created in the DB at startup

### Expected behavior

Entities that are declared in packages that are not in the specified package should not be created in DB.

### Actual behavior

All entities from the project are created in DB

### How to Reproduce?

1. setup a basic Quarkus project with panache
2. add a line to the configuration to specify a value for `quarkus.hibernate-orm.packages`
3. create one entity that is in the specified package and one that is not
4. start quarkus
5. verify that both entities have been created in the DB

I created **[a very simple project that reproduces the bug](https://gitlab.com/twistedcat/quarkus-panache-package-bug)** if you want to check it out.

### Output of `uname -a` or `ver`

Linux tomtom-dell 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.20.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.20.04, mixed mode, sharing)

### Quarkus version or git rev

2.5.0Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by yrodiere** [comment]
I'm a bit perplexed, because this actually seems to be on purpose:

https://github.com/quarkusio/quarkus/blob/afac28f5608efa8ca8cc87027126bedc18167db9/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1217-L1223

We actually ignore the `packages` configuration property, unless you define other, named persistence units.

@gsmet , you seem to have introduced this in 677360504960761d1aad2a2d8930882c0099df4e . Any objection to changing this behavior so that we remove the "shortcut" above, and we *always* take the `packages` configuration property into account, even if there is only one PU?

**Comment by gsmet** [comment]
@yrodiere yeah, I agree we should change it. I don't know what I was thinking.
