### ISSUE TITLE
Strange config props inheritance behavior in multimodule projects

### ISSUE THREAD

**Issue by OleKsimov** [quarkusio/quarkus#21704]
### Describe the bug

// GIVEN

Module B inherits Module A as a dependency in multimodule project:
`implementation(project(":module-A"))`

Module A has the next props in application.yaml:

```
quarkus:
  log:
    level: DEBUG

"%dev":
  quarkus:
    log:
      level: DEBUG

"%prod":
  quarkus:
    log:
      level: DEBUG
```

Module B has the next props in application.yaml:

```
quarkus:
  log:
    level: INFO
```

// PROBLEM

If I run Module B in dev or prod mode log level is DEBUG.
I expect it to be INFO because I configured the default log level in current Module B as INFO, and that must be inherited by all current module profiles.

It becomes a problem when I want to configure for example some Vault properties once per config and suddenly some vault configuration params are taken from another module that has Vault configured as well, and not from the default profile. I've spent a lot of time fixing this in a project. 

### Expected behavior

**Module B** test/dev/prod config profiles are inherited from **Module B** default profile, not from Module A corresponding profiles.

### Actual behavior

**Module B** test/dev/prod config props are inherited from **Module A** corresponding profiles, not from Module B default profile.

### How to Reproduce?

[profiles-inheritance.zip](https://github.com/quarkusio/quarkus/files/7603907/profiles-inheritance.zip)

1. run module profile-child in this multimodule project using gradle:
gradle clean :profile-child:quarkusDev

2. DEBUG logs are shown in the output instead of INFO 

### Quarkus version or git rev

2.4.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.0

### Additional information

I'm not sure if it is a bug but it's some confusing behavior.

**Comment by radcortez** [comment]
This is caused by the profile configuration `%dev.quarkus.log.level` set in the parent module, which takes priority.

Usually we don't let profile values to take priority over main ones if they are on the same source. It needs to have a higher ordinal than the main property. In this case, we use the classloader order to load the sources (and they load as expected, child first parent last), but than we fail on the ordinal compare, because we only use the source ordinal (255) to pick between profile or main configuration. Since both sources are on the same ordinal the profile configuration is selected.

As a workaround, I recommend to add a `config_ordinal: 254` (lower than 255) in the parent module `application.yaml`. In the meanwhile, I'll fix the issue.
