### ISSUE TITLE
@Unremovable does not work with custom parameterized qualifiers

### ISSUE THREAD

**Issue by acanthite** [quarkusio/quarkus#21701]
### Describe the bug

I have a common interface for a bunch of services with custom parametrized qualifier, which I want to lookup in runtime. But @Unremovable does not work when I annotate implementations with the custom qualifier. The `Instance<MyService>` simply has no resolved beans inside (the `resolvedBeans` is empty in debugger).
It behaves as if the beans were not annotated with @Unremovable.

### Expected behavior

Beans should not be removed if marked with @Unremovable and custom parametrized qualifiers.

### Actual behavior

Beans are removed if marked with @Unremovable and custom parametrized qualifiers.

### How to Reproduce?

Reproducer: [acanthite/quarkus-unremovable-bug](https://github.com/acanthite/quarkus-unremovable-bug)

1. `./gradlew quarkusDev`
2. go to http://localhost:8080/hello?service=s2

### Additional information

Here is what it looks like in debugger:
![image](https://user-images.githubusercontent.com/52529496/143457293-a4a1cd39-8a05-4b94-aa22-3080570e64c4.png)

**Comment by mkouba** [comment]
@acanthite The injection point is not correct - it should declare the qualifier otherwise the `@Default` is used and none of your `MyService` impls has the `@Default` qualifier. For example, if you do `@Inject @MyQualifier("s1")  Instance<MyService> services` then `MyService1` will be injected. Note that `MyQualifier#value` is binding which means that it's considered during type-safe resolution. 

You can also do `@Inject @Any Instance<MyService> services` and then iterate over all implementations.

**Comment by acanthite** [comment]
Yep, adding `@Any` to the injection point did the job. Thank you very much!
