### ISSUE TITLE
Make kubernetes limits and requests resources modifiable at runtime

### ISSUE THREAD

**Issue by iompo** [quarkusio/quarkus#21771]
### Description

The kubernetes configuration properties: _quarkus.kubernetes.resources.limits.cpu_, _quarkus.kubernetes.resources.limits.memory_, _quarkus.kubernetes.resources.requests.cpu_, _quarkus.kubernetes.resources.requests.memory_ are compile time properties. 
I have different environments where I deploy my service, each environment has a different configuration in terms of available cpus and memory. I would like to define different limits for my service, based on the environment where the service is deployed, without having to recompile it.

### Implementation ideas

Make the kubernetes limits and requests properties runtime modifiable.

**Comment by geoand** [comment]
Thanks for reporting

> Make the kubernetes limits and requests properties runtime modifiable.

This actually does not make sense since Kubernetes configuration is **only** application to **build-time** meaning that it only affects the `kubernetes.yaml` manifest generation.
That said, you can certainly specify different values for these properties using any of the supported ways
