### ISSUE TITLE
metrics from VertxHttpServerMetrics grows until OOM happens

### ISSUE THREAD

**Issue by janinko** [quarkusio/quarkus#21790]
### Describe the bug

We have an [application](https://github.com/project-ncl/kafka-store) that reads a lot of data over the network. The application crashed several times because of Out Of Memory. Investigating the memory showed that two instances of `io.quarkus.micrometer.runtime.registry.json.JsonDistributionSummary` took 96 % of memory and over 5 days grew from 162.5 MiB to 355.7 MiB, while the rest of the app's memory usage grew by 0.4 MiB.

The two `JsonDistributionSummary` were for `http.server.bytes.read` and `http.server.bytes.written`

### Expected behavior

The memory usage is constrained.

### Actual behavior

The memory usage grows until OOM error happens.

**Comment by geoand** [comment]
Thanks for reporting @janinko.

Do you by any chance have information in your heap dump that shows which fields of `JsonDistributionSummary` where talking up all the memory?

**Comment by ebullient** [comment]
Which version of Quarkus are you using? There was a fix added to the Json registry awhile ago to correct the depth of the ring buffer.

Note that the Json registry is optional, and stores/performs calculations that other registries don't. If you don't need it, I would turn it off.

**Comment by janinko** [comment]
Quarkus version 2.4.2.Final

![image](https://user-images.githubusercontent.com/644267/143907753-84b564b0-edab-4322-9d66-1c04c8187b49.png)

**Comment by geoand** [comment]
Any chance you can test with 2.5 and see if the problem persists?

**Comment by ebullient** [comment]
You misunderstood me. This isn't turning off the meter, it is turning off the json registry if you don't need it: `quarkus.micrometer.export.json.enabled=false`

If you need the json registry, please make sure your ring buffer is set to a small number: 
`quarkus.micrometer.export.json.buffer-length=3`. The larger that number is, the more memory it will require.

**Comment by geoand** [comment]
> so we can only see the problem in production

Understood, but won't profiling your staging environment show an ever increasing ring buffer size if the problem persists?

**Comment by ebullient** [comment]
I don't think anything has changed w.r.t. the Json registry recently, this is a knock-on effect of how the JsonRegistry works (it performs a lot more calculations, and requires more storage). The buffer-length setting is a concern, the setting was added / memory usage fixed in 2.1.0.Final, any release before that could see this runaway memory usage because the ring buffer length was way too big.

**Comment by geoand** [comment]
`quarkus.micrometer.export.json.buffer-length=3` is already the default, isn't it? 
And it seems it has been for a few months

**Comment by ebullient** [comment]
Yes. When we added the flag in June, we set the default. So if the version of Quarkus in use is pre-2.1.0.Final, the explosion of data with the Json exporter is a known issue that would be resolved by turning it off.

**Comment by geoand** [comment]
This issue seems to be about Quarkus `2.4.2.Final`

**Comment by ebullient** [comment]
Right. The amount of calculation the Json exporter does is not really fixable (aside from ensuring the ring buffer value is small, which it should be).

There are a few ways to deal with this: 

- Turn the Json exporter off. This is what I would do, as I don't recommend the Json exporter for production use because it holds so much in memory.
- If you actually require it in production, use a [Deny MeterFilter](https://micrometer.io/docs/concepts#_deny_or_accept_meters) with a MeterFilterConstraint to limit the metrics being sent to the Json exporter to constrain memory usage.

**Comment by ebullient** [comment]
Closing this. Recommendations for how to work around memory usage are given above.

**Comment by gsmet** [comment]
@ebullient hmmm, if this thing is not usable in production, we should either document it or tweak it or implement a filter by default. But it's definitely not the behavior I would expect and I'm even surprised this can be so much of an issue.

**Comment by gsmet** [comment]
What's a bit weird is that the size of the ring buffer is `1024` which is the old default and it has been `3` since 2.0.0.Final (https://github.com/quarkusio/quarkus/pull/17852).

**Comment by gsmet** [comment]
I tried to debug the creation of the ring buffer and I get 3 for the size, which is what we expect in recent Quarkus versions.

@janinko I would be interested in having more information about your setup and how you end up with a ring buffer sized to 1024. I added a breakpoint in `AbstractTimeWindowHistogram` for the `ringBuffer` initialization.
