### ISSUE TITLE
Dev UI Config screen update

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#21904]
In terms of the UI I think we should have 2 tables:

- The explicitly set config at the top
- An alphabetically ordered table down the bottom that also include the values from the top table (double ups are fine).

The second table should be expandable by level, with an expand all button, so you can expand it out to what we have today, or just click to expand the bits you are interested in. 

If we could make that change combined with the changes in this PR I think the editor will be way way more usable.

_Originally posted by @stuartwdouglas in https://github.com/quarkusio/quarkus/issues/21874#issuecomment-985168266_

**Comment by phillip-kruger** [comment]
@cescoffier ^^^ w.d.y.t ?

**Comment by cescoffier** [comment]
For me, what's missing is the configuration per extension and application configuration.
Once this is done, we could make the extension expandable.

However, searching and sorting would be a lot more complex to handle (which is why I've used a vaadin-grid). I believe we should be good with a list of "details" and vaadin-grid in each one and applying search to all grids (and if there is a hit, make the details visible)

**Comment by geoand** [comment]
@phillip-kruger can this be closed now with the new DevUI?

**Comment by phillip-kruger** [comment]
Yes
