### ISSUE TITLE
OIDC: callback URI invoked on error

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22188]
### Describe the bug

I've managed to get auth errors (most of the time due to improper configuration, such as misconfiguring the scopes or disallowed callback URI) which end up invoking my callback endpoint, which should not happen.

Example:

```
2021-11-23 17:54:08,655 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-0) HTTP Request to /Login/oidcLoginSuccess?error=redirect_uri_mismatch&error_description=The+redirect_uri+MUST+match+the+registered+callback+URL+for+this+application.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-authorization-request-errors%2F%23redirect-uri-mismatch&state=a6f7a6c2-b8af-4a67-9f9d-ca5bc882ee0e failed, error id: a5f251f5-479f-4da9-9192-507b1198a3ef-4: io.quarkus.arc.ArcUndeclaredThrowableException: Error invoking subclass method
```

**Comment by sberyozkin** [comment]
Hi @FroMage Yeah, if it were a custom application starting a code flow itself, then it would definitely be correct for it to get the error in the callback - this is so that it can clean up the state matching the state parameter, and as you said in the other issue, return a user friendly HTML page.
I'm also wondering how this could've happened (your callback endpoint called) without the `code` - can you confirm please this callback path was secured at the Quarkus level ? (with `@Authenticated` for ex) ?

**Comment by FroMage** [comment]
Well no, it was not secured with `@Authenticated`, should it be? That was not obvious to me. And I'm not sure how it's relevant. I expect OIDC to intercept the error return just the same way it should intercept the success return, no?

The docs don't say a word about handling errors, so I'm totally in the blind and can only trust my common sense as to what should happen.

**Comment by sberyozkin** [comment]
Hey @FroMage 

> Well no, it was not secured with @Authenticated, should it be ?

It has to be, otherwise `quarkus-oidc` won't be even called, it is a general Quarkus security design, the authentication mechanisms are called if the authentication is required so the redirect back to the Quarkus endpoint is not even seen by `quarkus-oidc` - Quarkus secutiy which orchestrates does not know this `GET` is in fact completing the code flow, all it knows it is targeting a public endpoint, so the request goes in.

> The docs don't say a word about handling errors, so I'm totally in the blind and can only trust my common sense as to what should happen.

I'll make sure it is clarified (alongside the requirement to have `@Authenticated`) while fixing #22189.

Let me close this issue - we can't do anything if the redirect goes to the public endpoint
