### ISSUE TITLE
@Metric annotation requires @Inject too

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#2237]
`@ConfigProperty` field doesn't need to be annotated with `@Inject` although the spec says that the field should be annotated with `@Inject`. In case of `@Metrics` the spec says that `@Inject` should be used too. In Quarkus, if you do not use `@Inject` along with `@Metrics` the field is null.

I think that following the convention started in `@ConfigProperty`, `@Metrics` should not need to be annotated with `@Inject`

**Comment by mkouba** [comment]
Actually, I wonder if we should generalize this feature so that any injection point field annotated with a qualifier could omit the `@Inject` annotation. Hm, but `org.eclipse.microprofile.metrics.annotation.Metric` is not a qualifier although it is used as a qualifier (?). Well, we could reformulate: any quarkus extension is allowed to specify annotations for which `@Inject` is added automatically if placed on a non-static field.

**Comment by lordofthejars** [comment]
Yes that would be great, maybe we can close this and open the generic one?

**Comment by mkouba** [comment]
No need to close the issue. I'll try to prepare something.
