### ISSUE TITLE
Qute bug with string literals and methods

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#22399]
### Describe the bug

I'm trying to obtain a character literal. I've tried the following:

```
{'a'.charAt(0)}
{#let c='a'.charAt(0)}{c}{/let}
{#let c='a'}{c.charAt(0)}{/let}
```

The first one is ignored by the parser. The second one yields an error. Only the third one works. Is this intentional?

**Comment by mkouba** [comment]
Yes, that's intentional and documented. _The content of a tag must start with a digit, or an alphabet character, or underscore, or a built-in command: `#`, `!`, `@`,`/`._ [1]. Furthermore, a literal value can only be used either standalone (such as `'foo'` in `{#if val == 'foo'}`) or as a virtual method param (such as `c.charAt(0)`) [2]. In other words, `'a'.charAt(0)` is not supported. And I doubt that it's something very useful or frequently used...

[1]
https://quarkus.io/guides/qute-reference#identifiers

[2]
https://quarkus.io/guides/qute-reference#expressions

**Comment by FroMage** [comment]
Yeah, it's not frequent. I would not have used this if I didn't need to get a character literal, but there are no character literals… :) We can close this and wait to see who else wants char literals or to invoke methods on literals.
