### ISSUE TITLE
quarkus.http.cors.origins=* : it does not work

### ISSUE THREAD

**Issue by aekkader** [quarkusio/quarkus#22580]
### Describe the bug

quarkus.http.cors.origins=* : it does not work

**Comment by geoand** [comment]
Can you please provide more info?

**Comment by Postremus** [comment]
@aekkader 
By default, `quarkus.http.cors.origins` already allows any host if not otherwise specified.

Please also make sure to set `quarkus.http.cors` to `true`.

This is for example a snippet of the configuration I use:
```
quarkus.http.cors=true
quarkus.http.cors.access-control-max-age=600
quarkus.http.cors.headers=Authorization,Content-Type
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS,HEAD,PATCH
quarkus.http.cors.exposed-headers=Content-Disposition,Content-Encoding,Content-Length,ETag
```

Explicitly defining the star wildcard should work the same. If it does not, we need a reproducer.

**Comment by gsmet** [comment]
Closing, we have tests for it. If it's a problem for you, you need to provide a lot more information such as attaching a small reproducer.

We don't even know which Quarkus version you are using. Some older versions did not support `*` but newer do. It might be a bug and if you can end up preparing a reproducer, please attach it and reopen.
