### ISSUE TITLE
Provide a way to re run changed tests only

### ISSUE THREAD

**Issue by lud** [quarkusio/quarkus#22665]
### Description

Hi,

When the test suite is huge and takes time to run, there is no way to my knowledge to run only the test I am working on.

I either keep it broken with something like `assertTrue(false)` at the end of the test, coupled with broken-only mode, but this is ugly and only practical when there is just one broken test (it does not work when making big changes that will break things).
Otherwise, as soon as the test is green, it will not be ran again in broken-only mode, and running all the tests is not an option when that is slow.

What do you think?

### Implementation ideas

I have no idea of how the state is kept for broken tests, but I guess that state could also keep the last time the test ran, to be compared to the compilation time when the file is changed.

**Comment by famod** [comment]
I think this makes sense. Could be called "affected only" mode or so.

**Comment by geoand** [comment]
I assume you are referring to continuous testing here?

**Comment by famod** [comment]
@geoand I was assuming that but let' have it verified by @lud.

On second thought, continuous testing is already all about just running "affected" tests, so that mode I was referring to actually exists already.
@lud did you have a look at https://quarkus.io/guides/continuous-testing#quarkus-test-dev-testing-test-config_quarkus.test.include-pattern ? You sould be able to set this via `-D` when starting continuous testing.
There is also an open PR adding the ability to change the pattern without restarting: https://github.com/quarkusio/quarkus/issues/22345#issuecomment-997561738

**Comment by lud** [comment]
Oh I totally missed this configuration property.

Well that covers my needs. From my point of view this issue can be closed if you are not interested by a "changed tests" mode.

Thank you!

**Comment by famod** [comment]
Thanks for your feedback!

I'm closing this because cont testing already detects which tests are changed/affected.
