### ISSUE TITLE
Hibernate ORM codestart doesn't compile out of the box, jdbc extension is needed

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#22773]
### Describe the bug

Hibernate ORM codestart doesn't compile out of the box, jdbc extension is needed

Hibernate ORM codestart was introduced in https://github.com/quarkusio/quarkus/pull/20879 by @loicmathieu 

### Expected behavior

codestart compiles

### Actual behavior

codestart doesn't compile on its own, additional changes are needed

### How to Reproduce?

Download sample app with just orm extension selected from https://code.quarkus.io/

Run `mvn clean verify`

**Comment by loicmathieu** [comment]
@rsvoboda you cannot add PostgreSQL automatically, this is not a good default.
And ... there is no good default, that's why you need to add your JDBC extension.
The hibernate ORM guide explain in the first section that a JDBC extension is needed (https://quarkus.io/guides/hibernate-orm#setting-up-and-configuring-hibernate-orm).

The issue states that the application didn't compile, it's surprising, I would expect it compile but didn't run.

**Comment by gsmet** [comment]
If you have an entity and no JDBC extensions around, you have an error at
build.

**Comment by Sanne** [comment]
We need to know which database is being used at build time, so this information is necessary at build.

This limitation is expected I believe? Not sure if all code-starts need to "just work" oob ?

**Comment by rsvoboda** [comment]
imho the OOB experience is quite important. So for hibernate-orm codestart seems there is no other option than what we have at this moment. Correct?

**Comment by loicmathieu** [comment]
At some point an entity will be created and the build error will pop up so the codestart will just fail faster.

Maybe the tooling needs to handle such case.

**Comment by ia3andy** [comment]
Codestarts are not "example quickstart", they are bit of code to start coding. Having the entity is nice to get started on your app.

Maybe we should auto-disable hibernate when there is not db selected and print a warning.

**Comment by ia3andy** [comment]
I will give more thought to that kind of problem when I get back. Still I think it's ok to fail if it says that a db is required to work, this is the normal order of things. 

Most users will have selected a driver at creation time, if they forget, then I think it's ok to fail telling them the next step.

**Comment by Sanne** [comment]
I suppose we could look at making Hibernate ORM 's extension self-disable when no jdbc extension is around - pretty sure Max would like that too for demos which incrementally build an app from scratch and don't want to "interrupt the flow" while having fun with dev mode and adding extensions incrementally. (He complained in the past that Hibernate should "boot" even when no entities are defined).

However we need to be careful that we also don't require a JDBC extension as people should be allowed to bring their own JDBC driver; there's many more databases which we want to support but don't plan to have an extension for.

I wouldn't want to make it more complex for legit users of other DBs, so a solution at the level of the codestart would be preferrable IMO. Or just accept this limitation, possibly polish the error messages and guidance we provide.

**Comment by Sanne** [comment]
I guess we could self-disable and print a nice warning if there's _none of_:

- a datasource configured
- a jdbc extension available
- a dialect configured

I'm not sure about the check on the Dialect; I think I'm inclined to add it too as extra safety as dev-services might also want to try self-configuring a datasource, but supposedly we might never have a dev-service support for some DB w/o a matching DB's extension so that might unnecessary but it shouldn't hurt.

@gsmet WDYT? Too much magic?

**Comment by gsmet** [comment]
Well, IIRC, it was a warning at the beginning and then people asked for an error because they couldn't figure out what was going wrong.

So I'm really not comfortable going back just for the sake of providing a sample entity that (IMHO) has little value for someone who is going to start a Hibernate ORM based project.

**Comment by ia3andy** [comment]
> Well, IIRC, it was a warning at the beginning and then people asked for an error because they couldn't figure out what was going wrong.

Ok, this was just a suggestion.

> So I'm really not comfortable going back just for the sake of providing a sample entity that (IMHO) has little value for someone who is going to start a Hibernate ORM based project.

Then, IMO, failing, with an explanation on the step forward if the user didn't select any driver is fine. It's better to have the entity in that case than nothing, the normal way is to select hibernate + a driver

**Comment by loicmathieu** [comment]
So, what is the decision around this issue ? It blocks #21651 

My take on it: keep it as today, an error is good and people must add a JDBC driver when using Hibernate.

**Comment by gsmet** [comment]
So what is the value of having this codestart? What does it do and how does it make things better for the user? If someone can summarize what this codestart do, we can take an educated decision.

Because again, if it's just a random entity created, I don't see the value of it given all the nice guides we have.

**Comment by loicmathieu** [comment]
It's an example entity with a comment explaining how to use it so people will have some code sample.

I wanted to have the code example in a test case or something else but the decision was taken to add it inside a comment. The entity is a JPA entity when only Hibernate is selected and a Panache entity when both Hibernate and Panache are selected.

A lot of discussions was done at the time with Andy and Sanne, Hibernate and Hibernate with Panache are very popular extensions and the there was a desire to create codestart for them.

**Comment by gsmet** [comment]
Well, why not if it doesn't end up causing problems.

But, IMHO, given it's causing problems, I see very little value in having an example entity if we end up with a broken project.

YMMV I suppose.

I'll let @Sanne and @yrodiere decide on this one.

**Comment by gsmet** [comment]
FWIW, my main problem is that having a just generated project that doesn't build might have the users think that something is broken and it might be bad PR for Quarkus given how widespread the ORM extension is.

**Comment by ia3andy** [comment]
I think we are reversing the problem, when the users are getting the hibernate extension alone and start coding, they will end up in the same situation where they need to add a driver. It seems totally healthy to me that codestarts are doing the same.

Most users will already have selected a driver alongside hibernate and it will work out of the box.
The few users which will have only selected hibernate will at least have an indicator on the way forward (delete the code, or add the driver).

I think it's way better to have an application that is not building with good reasons, than an application that is building just to avoid complaining.

I am not against looking for ways to make the user flow more streamlined but I don't think that removing the code is going in this direction.

**Comment by loicmathieu** [comment]
I'm on @ia3andy team on it ;)

If a JDBC driver is needed, it needs to be handled by our tooling (cli, code.quarkus.io, ...) or a clear exception needs to be thrown at first launch.

**Comment by Sanne** [comment]
I'd love to see it handled by our tooling too.  But I failed to persuade others into developing a general-purpose technique to have the tooling automatically add dependencies based on rules.

Perhaps it's time to reopen that topic, as it was partially dismissed also because people were too busy with more important matters. We could try implementing a non-generic solution as an experiment to address at least the ORM case... for example we could have an hardcoded rule that adds H2 to ORM when no other driver is selected.

To be clear, I'm NOT saying I'll definitely merge such a solution - but that it would be nice to produce such an experiment so to evaluate the option.. need to be cautious as I'm afraid this could open a pandora box of things I've not considered.

@aloubyansky feel free to shut it down already :) Or do you think we could try something among those lines?

**Comment by aloubyansky** [comment]
We'll definitely have to support this. I don't remember anybody being against it in principle. Perhaps some specific impl ideas.
Anyway, as a start we could simply fail project creation (extension addition) if its requirements aren't fulfilled. That would be checked against required capabilities, which we currently don't have a way to express but there are no obstacles to add that, in fact, I knew we'd want that and the current code was written in way to be able to add this easily. So that will be a start.
Then there will be a question of whether and how we want to express the defaults for required capabilities.

**Comment by ia3andy** [comment]
@loicmathieu @gsmet I think we can re-open #2165. as we discussed, until we provide a better experience with required capabilities, failing is the most logical behavior (and the same as when coding)

**Comment by FroMage** [comment]
There are several ways to solve this issue:

- Self-disable Hibernate if there's no config (what @Sanne suggested)
- Self-disable Hibernate if it isn't used: no `@EntityManager` or `@EntityManagerFactory` used (a little bit more complex for Panache)
- Turn this into a runtime error
- Handle the issue at code.quarkus.io time, but this same issue remains when adding the Hibernate extension manually

But frankly, it seems totally fine to keep the current state and fail at build time when the driver is missing, as is currently the case, even for a codestart.

**Comment by yrodiere** [comment]
> I'll let @Sanne and @yrodiere decide on this one.

Ok, so I'll decide: we've been arguing for a long time with no decision, we need to move on. Let's close this.

Two motivations:

1. Codestarts are a thing whether we like it or not. We could argue about their value, but that ship has sailed. If we provide codestarts, let's provide them consistently.
2. Adding a JDBC extension automatically is not possible, because we don't know which one to add. Better an application that fails and tells you why than an application that takes a decision without you knowing, and may take the wrong decision.

So let's keep the things as they are, and keep adding codestarts. If people forget to include a JDBC driver, we'll error out and people will just include a JDBC driver. If the current error is unclear, we'll improve it.

AFAICS, I'm not the only one with that opinion.

Closing as not planned; thanks everyone involved for the discussion.

**Comment by yrodiere** [comment]
Also a note: if people want to have the ORM extension in their application and not use it for some weird reason, they can disable it with https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.enabled
