### ISSUE TITLE
quarkus:dev maven goal should imply process-classes

### ISSUE THREAD

**Issue by evc-erik** [quarkusio/quarkus#22807]
### Description

As noted in #22776, running `quarkus:dev` without `process-classes` doesn't create Jandex indices for dependencies in a multi-module build. If the `process-classes` phase was included as part of the `quarkus:dev` goal, then the output would more closely match the results of the JAR created with the `package` goal.

**Comment by glefloch** [comment]
@aloubyansky I can take care of it for both Maven and Gradle. Just to make, for the maven part, we only need to set a dependency on the `process-classes` phase and we don't need to check wether the `jandex` plugin exists rigth?

**Comment by famod** [comment]
The other day I was wondering whether we should "fork the lifecycle" (as the Maven folks say) so that we don't need to execute specific goals on our own. This would simply do the very same as what Maven would be doing (until the given phase):
```java
@org.apache.maven.plugins.annotations.Execute(phase = LifecyclePhase.PROCESS_CLASSES)
```
This would also catch user-specific plugin executions (for which we had more than one issue).

Downsides:
- would also execute enforcer plugin etc. which might be unwanted, but maybe not
- there is no way to opt out of the forking, which is why plugins like `maven-jar-plugin` introduced `*-no-fork` mojos at some point

**Comment by aloubyansky** [comment]
@famod can you think of a good case when you wouldn't want to "fork the lifecycle" in case of `quarkus:dev`? And what would make sense as the default in most cases? It seems to me forking could make sense in most cases.

**Comment by glefloch** [comment]
Would we do that for all goals we execute or only for the `process-classes` phases ? I'm thinking of compilation of test that can fails but the error is ignored.

**Comment by aloubyansky** [comment]
It would be what Maven was instructed to do by the user. We wouldn't ignore Maven build errors on launch (or preparing to launch).
