### ISSUE TITLE
Incorrect changes after running update-extension-dependencies.sh

### ISSUE THREAD

**Issue by tsegismont** [quarkusio/quarkus#22836]
If you:

-  have cloned and built this repository before #21736 was merged
- run `update-extension-dependencies.sh` because, for example, you're adding an extension

Then the output contains references to the modules that were moved out of the repository.

This was found while working on #22810

**Comment by famod** [comment]
The cause is described here: https://github.com/quarkusio/quarkus/pull/22810#issuecomment-1010996342

@aloubyansky do you want to take this?

**Comment by aloubyansky** [comment]
I am busy with other tasks currently, so not right now.

**Comment by famod** [comment]
I'll try to have look at using that relocations profile later today.

**Comment by gsmet** [comment]
> I'll try to have look at using that relocations profile later today.

I'm not sure it's the right fix. You can use it in the script but personally, I build things separately to make sure it builds before running the script.

And we don't want to enable this profile always as one of the point of this work was to reduce the number of modules.

I think we can probably live with this limitation (but I would fix it in the build you have in the script, so we could say "just ask for a full build when the script asks to fix it"), especially since CI complains loudly.

**Comment by famod** [comment]
To be clear: the script only builds on top of what's in that generated descriptor and that generation picks up "removed" extensions.
So I'd prefer if we could fix the root cause of this.

**Comment by famod** [comment]
Good news: `-Prelocations` seems to fix it.

I don't have time to check whether we can fix the root cause in the descriptor generation, so we have two options AFAICS:
- `-Prelocations` the default
- or, in the script, don't ask the user if the entire projects is already built and always build with `-Prelocations`

I suppose we want to go with option two?

**Comment by famod** [comment]
I found one difference with `-Prelocations` when compared with the result you get with a clean local repo and build withwout `-Prelocations`:
```json
  }, {
    "name" : "Amazon Services Common",
    "description" : "Common components for AWS Lambda functions",
    "metadata" : {
      "keywords" : [ "amazon services", "aws", "amazon" ],
      "categories" : [ "data" ],
      "status" : "stable",
      "unlisted" : true,
      "built-with-quarkus-core" : "999-SNAPSHOT",
      "extension-dependencies" : [ "io.quarkus:quarkus-core", "io.quarkus:quarkus-arc", "io.quarkus:quarkus-netty" ]
    },
    "artifact" : "io.quarkus:quarkus-amazon-common::jar:999-SNAPSHOT",
    "origins" : [ "io.quarkus:quarkus-bom-quarkus-platform-descriptor:999-SNAPSHOT:json:999-SNAPSHOT" ]
```
This exists after building `-Prelocations` with those old extensions still in local repo.

**Comment by famod** [comment]
It seems we're missing a relocation for `quarkus-amazon-common`. I'll add that to my PR.

**Comment by gsmet** [comment]
@famod it's not missing. I don't think we need one given it's not a user-exposed extension.

Let's not make things just to fix a totally unrelated issue.

**Comment by famod** [comment]
@gsmet  It's not unrelated. If `-Prelocations` still adds it to the descriptor, then the script will add it to the `pom.xml` and we again have a deviation.

**Comment by famod** [comment]
The alternative would be to filter out that one artifact in the script (which I find a bit brittle, but it's doable).
This would _not_ prevent it from ending up in the descriptor, though, which means that locally even with `-Prelocations` you'd need to purge your local repo to have a consistent descriptor. (One could argue that this will be needed anyway when we start to remove relocations again...)

I'll wait until you @gsmet and @aloubyansky have decided which way to go.

**Comment by gsmet** [comment]
It's unrelated because you're trying to overcome an issue with a script by adding some stuff that shouldn't be related. You basically need relocations to say "this thing is not an extension anymore". That shouldn't be necessary.

What I fail to see is why we are somehow getting all the extensions that are in the local Maven repo? Why isn't it coming from what's in the tree or are at least filtered with what's in the tree.

**Comment by famod** [comment]
> What I fail to see is why we are somehow getting all the extensions that are in the local Maven repo? Why isn't it coming from what's in the tree or are at least filtered with what's in the tree.

That's what I meant with
> So I'd prefer if we could fix the root cause of this.

which has nothing to do with the script in the first place. 🙂
