### ISSUE TITLE
ExceptionMapper should support superclasses

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#22949]
### Describe the bug

At the moment ExceptionMapper support only specific exceptions like this:

```java
@Provider
@Priority(Priorities.AUTHENTICATION)
public class UnauthorizedExceptionHandler implements ExceptionMapper<UnauthorizedException> {
    @Override
    public Response toResponse(UnauthorizedException e) {
        return Response.ok("Unauthorized").build();
    }
}
```

UnauthorizedException extends SecurityException but the following code is not working

```java
@Provider
@Priority(Priorities.AUTHENTICATION)
public class ForbiddenExceptionHandler implements ExceptionMapper<ForbiddenException> {
    @Override
    public Response toResponse(ForbiddenException e) {
        return Response.ok("Access forbidden").build();
    }
}
```

### Expected behavior

ExceptionMapper should support superclasses of the specific exception.
It should even work with Throwable.

**Comment by kucharzyk** [comment]
@michalszynkiewicz

**Comment by geoand** [comment]
`ExceptionMapper` does work with supertypes. 

Can you attach a sample application exhibiting the problematic behavior?

**Comment by kucharzyk** [comment]
I will prepare sample application today

**Comment by kucharzyk** [comment]
@geoand I've prepared sample applicartion with this behaviour

https://github.com/kucharzyk/quarkus-22949/tree/main/src/main/java/org/acme

I have 3 endpoints:
- /test/a throws UnauthorizedException
- /test/b throws ForbiddenException
- /test/c throws NotFoundException

I have ExceptionMappers for this three exceptions and they works.

Try to comment them.  have three others exception mappers:
- for RuntimeException (supertype of all three exception)
- for ClientError Exception (supertype of NotFoundException)
- for SecurityException (supertype of UnauthorizedException and ForbiddenException)

None of them is working.

Bonus points: Try to set logger to see which exception is thrown without knowing it

**Comment by stuartwdouglas** [comment]
Quarkus provides built in exception mappers for these types:

- io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.ForbiddenExceptionMapper
- io.quarkus.resteasy.reactive.server.runtime.exceptionmappers.UnauthorizedExceptionMapper
- io.quarkus.resteasy.runtime.NotFoundExceptionMapper (dev mode only)

If you have overridden them then your custom mapper will take effect, but otherwise these provide sensible defaults, in terms of responding with the correct response codes etc.

I think this should be closed as the current behavior is expected.

**Comment by geoand** [comment]
I agree with Stuart.
