### ISSUE TITLE
OIDC: Something wrong happens when verifying our internal JWT

### ISSUE THREAD

**Issue by FroMage** [quarkusio/quarkus#23007]
### Describe the bug

I just got this issue when trying to log in using Facebook:

```
org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.InvalidAlgorithmException: 'RS256' is not a permitted algorithm.): JsonWebSignature{"alg":"RS256","typ":"JWT","kid":"XXX"}->XXXX]
		at org.jose4j.jwt.consumer.JwtConsumer.processContext(JwtConsumer.java:264)
		at org.jose4j.jwt.consumer.JwtConsumer.process(JwtConsumer.java:426)
		at org.jose4j.jwt.consumer.JwtConsumer.processToClaims(JwtConsumer.java:171)
		at io.quarkus.oidc.runtime.OidcProvider.verifyJwtTokenInternal(OidcProvider.java:126)
		at io.quarkus.oidc.runtime.OidcProvider.verifySelfSignedJwtToken(OidcProvider.java:90)
		at io.quarkus.oidc.runtime.OidcIdentityProvider.verifySelfSignedTokenUni(OidcIdentityProvider.java:295)
		at io.quarkus.oidc.runtime.OidcIdentityProvider.createSecurityIdentityWithOidcServer(OidcIdentityProvider.java:138)
		at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:129)
		at io.quarkus.oidc.runtime.OidcIdentityProvider$3.apply(OidcIdentityProvider.java:123)
```

Can we really make internal tokens with an algo we don't permit?

**Comment by sberyozkin** [comment]
@FroMage Hmm, but we sign the internal token using the `HS256` algorithm. Something is going on, this does not look like the token we create internally (ex, `kid` is not set for the internal token)

**Comment by sberyozkin** [comment]
@FroMage It looks like, while the correct assumption is made that it is an internal ID token, the wrong cookie containing some other tenant's token may be picked up. Can you grab the token in the debug mode, in `OidcProvider.verifySelfSignedToken()` and check its content say at `jwt.io` ?

**Comment by FroMage** [comment]
Huh. WTF. I have what looks like a real token now:

```
{
  "iss": "https://www.facebook.com",
  "aud": "XXX",
  "sub": "XXX",
  "iat": 1642590366,
  "exp": 1642593966,
  "jti": "XXX",
  "nonce": "",
  "at_hash": "XXX",
  "email": "XXX",
  "given_name": "Stéphane",
  "family_name": "Épardaud",
  "name": "Stéphane Épardaud",
  "picture": "https://platform-lookaside.fbsbx.com/platform/profilepic/XXX"
}
```

How did that happen? Did facebook start support oidc today?

**Comment by sberyozkin** [comment]
@FroMage Looks like it is indeed returning an `IdToken`. If remove `id-token-required=false` it will start working. 
`CodeAuthenticationMechanism` will not create a self-signed token in this case - but during the re-authentication it assumes the token is internal because `id-token-required=false`.
So yes, removing `id-token-required=false` will fix it - however I'll try to tighten the code later on for `id-token-required=false` not to cause side-effects if `IdToken` is in fact returned by the provider

**Comment by FroMage** [comment]
Amazing, FB started sending an ID Token. Excellent. We can change the config for known providers. I can make a PR if you want, also with the fix for Apple discussed in https://github.com/quarkusio/quarkus/pull/22572#issuecomment-1016346209

**Comment by sberyozkin** [comment]
@FroMage Re `facebook`, so if it sends `IdToken`, does requiting `userinfo` is still needed ? Can you also please check, may be it now supports the auto-discovery as well so we can drop all those individual facebook endpoint URLs ?

Re `apple` - I propose to fix it later when `quarkus-oidc` starts supporting `form-post`, so for now please set the extra params manually

**Comment by zimkha** [comment]
Hello, being in an environment where the OIDC provider (Keycloak) is not yet available, I am forced to simulate a token with these claims algorithm:
{
  "sub": "user123",
  "iss": "dummy-issuer",
  "groups": [
    "USER"
  ],
  "iat": 1717232000,
  "exp": 1917235600
}
and this configuration in my application-dev.yaml

mp:
  jwt:
    verify:
      issuer: dummy-issuer
      secret: dev-secret-123

smallrye:
  jwt:
    verify:
      algorithm: HS256
      relax-key-validation: tru

 but I encounter an error Caused by: org.jose4j.jwt.consumer.InvalidJwtException: JWT processing failed. Additional details: [[17] Unable to process JOSE object (cause: org.jose4j.lang.InvalidAlgorithmException: 'HS256' is not a permitted algorithm.): JsonWebSignature{"alg":"HS256","typ":"JWT"}->eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyMTIzIiwiaXNzIjoiZHVtbXktaXNzdWVyIiwiZ3JvdXBzIjpbIlVTRVIiXSwiaWF0IjoxNzE3MjMyMDAwLCJleHAiOjE5MTcyMzU2MDB9.QWCXxkihCtEqilw8g_stQIidPvB5jPtBdLjOKuIDq6o]
