### ISSUE TITLE
No messages emitted on start of smallrye-reactive-messaging-kafka codestart in dev mode

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#23018]
### Describe the bug

No messages emitted on start with `smallrye-reactive-messaging-kafka` codestart in dev mode.

I had to adjust JAX-RS endpoint to inject `MyReactiveMessagingApplication` and invoke the method with emitter as part of endpoint call. When I accessed the endpoint I finally saw the log messages with the upper-case text.

Application code: https://github.com/quarkusio/quarkus/blob/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/reactive-messaging-codestart/java/src/main/java/org/acme/MyReactiveMessagingApplication.java#L19

In the log I noticed new lines just before the upper-case prints:
```
2022-01-19 16:55:03,870 INFO  [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-0) SRMSG18256: Initialize record store for topic-partition 'word-0' at position -1.
2022-01-19 16:55:03,886 INFO  [io.sma.rea.mes.kafka] (vert.x-eventloop-thread-1) SRMSG18256: Initialize record store for topic-partition 'uppercase-word-0' at position -1.
```

Seems that kafka dev service is not fully or properly initialized to handle messages sent from `onStart` method

This behaviour is quite confusing and it took me some time to figure out that the code flow in `MyReactiveMessagingApplication` is correct and the problem is with message sending.

CC @cescoffier 

### Expected behavior

```
>> HELLO
>> WITH
>> SMALLRYE
>> REACTIVE
>> MESSAGE
```
gets printed on boot in dev mode

### Actual behavior

Upper-case text is not printed

### How to Reproduce?

 - Select quarkus-resteasy-reactive and quarkus-smallrye-reactive-messaging-kafka on https://code.quarkus.io/
 - Download the app and run `mvn quarkus:dev`

### Output of `uname -a` or `ver`

macOS Monterey

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.6.2.Final and Quarkus main

**Comment by cescoffier** [comment]
Ok... that's annoying...
The configuration generated with the codestart is incorrect. It cannot work, or really by accident when all planets are aligned. The problem is that Kafka default uses "latest" when subscribing to a topic, which means that only new messages are going to be consumed. The record previously sent are simply ignored. 

Here is the working configuration:

```
mp.messaging.outgoing.source-out.topic=word


mp.messaging.incoming.source-in.topic=word
mp.messaging.incoming.source-in.auto.offset.reset=earliest

mp.messaging.incoming.uppercase-in.topic=uppercase-word

mp.messaging.outgoing.uppercase-out.topic=uppercase-word
```

I would also recommend using the topic as channel name to reduce the configuration to:

```
mp.messaging.incoming.source-in.auto.offset.reset=earliest
```

That would be so much better...

However, I don't know where this codestart is maintained. @maxandersen / @gastaldi any link?

**Comment by cescoffier** [comment]
We may want to rewrite the tests too, to use the dev service and not the in-memory connector.

**Comment by cescoffier** [comment]
I think I found where is it maintained... but I got some weird YAML-based config - do we generate the properties from that Yaml?

**Comment by gastaldi** [comment]
I think it's in https://github.com/quarkusio/quarkus/tree/main/devtools/project-core-extension-codestarts/src/main/resources/codestarts/quarkus/extension-codestarts/reactive-messaging-codestart

**Comment by gastaldi** [comment]
> I think I found where is it maintained... but I got some weird YAML-based config - do we generate the properties from that Yaml?

Yes, I believe so

**Comment by cescoffier** [comment]
Ah, I got why it's done that way (with the topic set). While I believe I agreed with this, I think it is not OK. It shows what I would call an anti-pattern for simple applications (read/write to the same topic from the same application instead of using an in-memory stream). It can be useful when you want to implement checkpoints, but that's quite advanced and should not be covered by the code start.
