### ISSUE TITLE
Override container image deployment registry

### ISSUE THREAD

**Issue by cherrydev** [quarkusio/quarkus#23101]
### Description

There seems to be some significant use cases where the registry that a built container image will be pushed to, and the registry that it would be deployed from might be different. In particular, if you have multi-region clusters, it is common to have mirrors of your container registry in each region. This is important both to reduce data transfer costs and deployment times. A strategy I attempted with my deployment in Kubernetes is to use the kubernetes override file in `src/main/kubernetes/kubernetes.yml` to insert the deployment (mirrored) registry at `spec.template.spec.containers[0].image` but the way that the override file is merged into the quarkus-generated kubernetes configuration causes it to be ignored.

### Implementation ideas

A simple but crude implementation to work-around this would be to alter the way that the final deployment descriptor (`kubernetes.yml` in the case of kubernetes) is merged with overrides to allow the deployment registry to be specified. This would have the slight downside that the image name and the image version would have to be kept in sync in multiple places and could lead to a situation where if one wasn't careful, you could end up pushing one image to the registry, and deploying a different one.
A more direct but complicated implementation would be to add a new configurable value or set of values to the `quarkus.container-image` configuration group that would allow separate image push and image deployment values.

**Comment by geoand** [comment]
I'll leave this to @iocanel to decide

**Comment by geoand** [comment]
@iocanel is this something we want to do?

**Comment by iocanel** [comment]
Even if we adopt a policy not to overwrite provided values (which is something I am open to discuss), I don't see how it adds anything to the use case described.

I think a better solution would be to generate helm charts and request the image to be parameterized. cc @Sgitario wdyt?

**Comment by Sgitario** [comment]
If I understood correctly, you want to override the image that is set when generating the manifests, to a different image to be provided when installing these manifests. Is this right? @cherrydev 
If so, I agree with @iocanel that I don't see how your suggestion can help :/ Though, I think the container image provided by the user at `src/main/kubernetes/kubernetes.yml` should be respected (this is not happening so far). 

Since Kubernetes does not support using system properties to override the container image, you can't do something like this `quarkus.container-image.image=${IMAGE}`. So, the only solution I see is to override the container image using Kubectl after installing the manifests:

```
kubectl set image deployment <deployment-name> <container-name>=<new image>
```

Or you can manipulate the manifests before installing them using either Kustomize or other shell commands. 

As an alternative and as @iocanel suggested, in addition to Quarkus Kubernetes, you can also use [the Quarkus Helm](https://quarkiverse.github.io/quarkiverse-docs/quarkus-helm/dev/index.html) extension that will generate the Helm Chart and allow you to override the image when installing the chart: 
```
helm install <chart name> ./target/helm/kubernetes/<chart name> --set app.image=<new image>
```

I hope it helps!

**Comment by Sgitario** [comment]
Closing as not planned.
If you need this, you can use Quarkus Helm extension.
