### ISSUE TITLE
JAX-RS resources are only considered if @Path in on the class

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#2315]
If you don't have `@Path` on the class but only on the endpoint methods, the resource is currently ignored.

It needs to be fixed here:
https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy-server-common/deployment/src/main/java/io/quarkus/resteasy/server/common/deployment/ResteasyServerCommonProcessor.java#L214

And we need a unit test for that added in the main integration tests.

**Comment by sberyozkin** [comment]
@gsmet Hi, this might affect the subresources. JAX-RS spec does require the root resources to have `@Path`. This may indeed be relaxed, but the issue is probably mainly about the JAX-RS subresources which do not have a root  `@Path`:
```
@Path("/")
public class Root {
  @Path("sub")
  public Sub getSub() {return new Sub(); }
}
public class Sub {
@GET
public Response get() {...}
}
```
If one adds Sub as one of the root resources then it will most likely not affect Root (it is OK for 2 roots to have the same Path values) but Sub resources will now be available in the "GET /" as opposed to the intended "GET /sub" path. In this case, if the Root has the GET method too then on the "/" path then it will introduce the ambiguity.
Sorry if it misses the point of the issue

**Comment by gsmet** [comment]
OK, we did discuss that with Justin and if JAX-RS requires it, it probably makes sense to keep it.
