### ISSUE TITLE
Flyway: Filter SQL files included in the native image

### ISSUE THREAD

**Issue by cristhiank** [quarkusio/quarkus#2326]
Flyway uses a custom script to create the metadata table in some databases. This file is located in `org/flywaydb/core/internal/database/<databaseEngine>`

The Flyway extension is including all the files that are available in the library when creating the native image.
We should include only the SQL file for the database being used in the app.
We could filter them somehow, maybe using the driver name that is know at build time ?

see: https://github.com/quarkusio/quarkus/blob/42c3e7187474e1d5f58569287bf8699e8baa555c/extensions/flyway/deployment/src/main/java/io/quarkus/flyway/FlywayProcessor.java#L163-L171

**Comment by gsmet** [comment]
This one is nice to have but really not critical at all.

**Comment by jaikiran** [comment]
FWIW - these files no longer exist in/since Flyway 6.0.4 version (the one used in Quarkus) and it looks like they were inlined within Java code in Flyway as part of this effort https://github.com/flyway/flyway/commit/91094e520f86b4f1e1bb7ee96d0b001cb0b50767#diff-a39a7b25c14dcbb898f4df3e00d02176

So the current code, you see in that Flyway processor is actually a no-op (I can remove it, if that's OK).

**Comment by Sanne** [comment]
@jaikiran if you'd like to clean that up, would be great! Thanks

**Comment by jaikiran** [comment]
@Sanne, done - https://github.com/quarkusio/quarkus/pull/4643

**Comment by Sanne** [comment]
thanks @jaikiran ! Closing this one.
