### ISSUE TITLE
Qute: type-safe expressions doesn't work with tags

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23289]
### Describe the bug

My tag looks like this

```
{@java.lang.String field}
{field}
```

I can pass any type of value and Qute doesn't report error

```
    {#validation field='general'}{/validation}
    {#validation field=42}{/validation}
```

**Comment by mkouba** [comment]
Duplicates https://github.com/quarkusio/quarkus/issues/21859. Yes, that's expected, the call-sites are not validated ATM.

BTW the `{field}` output expression requires no validation either. And even if you add `{field.toLowerCase}` then no validation error would be thrown at build time because it's the runtime value that is problematic.
