### ISSUE TITLE
Qute: No error for not existing tag

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#23288]
### Describe the bug

``` {#thisTagDoesNotExists}{/thisTagDoesNotExists}```

It works with qute and renders nothing. It should throw an exception.

**Comment by mkouba** [comment]
This definitely results in an error at runtime ([test](https://github.com/quarkusio/quarkus/blob/main/independent-projects/qute/core/src/test/java/io/quarkus/qute/ParserTest.java#L45-L49)). You should get an error like: `Parser error in template [hello.html] on line 9: no section helper found for {#thisTagDoesNotExists}`. We don't validate this at build time because a section helper could be potentially registered at runtime.

**Comment by kucharzyk** [comment]
I'll check this test and try to reproduce my error

**Comment by kucharzyk** [comment]
@mkouba I think it is duplicate of #23290
