### ISSUE TITLE
Allow `@QuarkusTest` and `@QuarkusIntegrationTest` to coexist in same test suite

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#23528]
### Description

I am running across some major hurtles with `@QuarkusTest` vs `QuarkusIntegrationTest`. Essentially, it makes sense to me as a developer that I would want to run both in the same `test*` command, and for the test codebase to comingle.

What I want to accomplish with this:

 - have the same tests for both native and non-native mode (possible in Maven, but not Gradle?)
 - simplify test writing, running, and configuration; nothing special for integration tests
 - potentially simplify Jacoco coverage? (Haven't looked into it, but I might think the extra config typically required for coverage of integration tests would be resolved with these proposed changes)

Currently though it seems that due to how the app is packaged for the different types of test, this is not currently supported and requires multiple code bases and different commands to be used to run them.

In Gradle, this seems to be the purpose of the `native-test` source set at the core, and in Maven an amount of pom configuration.

I suggest that we support a homogeneous codebase and command for running both `@QuarkuTest` and `@QuarkusIntegrationTest` tests. This would drastically simplify test creation and required configuration. If one wanted to have additional source-sets for Gradle runs it should still be possible, but one could also just run the same source set of `test` in native mode, and have the same tests available for jar integration testing.

I also realize I could be missing something and a reasonable solution might exist but I am not seeing it.

### Implementation ideas

We already have the ability to segment/ order tests by profiles and test resources; if we added the ability to order based on the two test annotations, we can separate the required runtime contexts and ensure they can run in the same suite/ run. It is possible I have a naive view of how the tests execution/ordering is handled, but I believe this is possible based on a couple of assumptions:

- we can carefully order the tests
- we have an amount of control of the running instance of quarkus used for each test

**Comment by geoand** [comment]
`@QuarkusIntegrationTest` should only be used for integration tests, i.e. tests run by Maven Failsafe. 

Did you have encounter problems in such a setup?

**Comment by geoand** [comment]
The idea is that the `@QuarkusIntegrationTest` tests **must** run **after** the application has been packaged. In Maven this is acomplished by having them run via failsafe (thus the `IT` suffix).
That way when one runs `mvn verify` (assuming failsafe has been configured to run for the `integration-test` or `verify` goals) the test are executed properly.
AFAIK, a similar case occurs when one invokes `./gradlew check`.

So I fail to see what the proposal is here.

**Comment by GregJohnStewart** [comment]
The proposal is that it should be easier to setup these integration tests; these tests should comingle in the `test` source sets with regular `@QuarkusTest`s, and not require special configuration, and run in the same task (`test`/`check`/etc)

If that means making the build/ package task a dependency for the tests, I feel that is reasonable.

A note that making `test` dependent on `quarkusBuild` results in the following error, and the `check` task did not seem to do much for me.

`Caused by: java.lang.ClassCastException: class io.quarkus.test.junit.RunningAppConfigResolver$1 cannot be cast to class io.smallrye.config.SmallRyeConfig (io.quarkus.test.junit.RunningAppConfigResolver$1 and io.smallrye.config.SmallRyeConfig are in unnamed module of loader 'app')`

I am of course willing to be shown an example of how these are 'meant' to be done, and that I might be overcomplicating something, but from what I have seen I don't see a perfect solution.

**Comment by geoand** [comment]
> The proposal is that it should be easier to setup these integration tests;

I personally don't feel there is nothing difficult about the current setup as it's based on standard build tool practices.

> If that means making the build/ package task a dependency for the tests, I feel that is reasonable.

That is huge breaking change and from my perspective brings no real benefit.

I personally fail to see why the standard `test` vs `verify` Maven goal split is problematic. We are using these the way they were supposed to be used.

I'd like to hear what @famod and @edeandrea think.

**Comment by edeandrea** [comment]
So I'll chime in here with my $0.02. And for those who don't know me, I'm much more a Gradle fan than I am a Maven fan :)

Like @geoand mentions, integration tests must run after the application has been packaged, since those tests are run against whatever the output artifact is (jar file, container image, native binary, etc). This means that those test classes need to have a separate classloader.

I actually prefer the way Gradle does this by having a separate source set (the name `native-test` needs to change - see #22035 for that conversation). In all my history using Gradle over the last 8-9 years I've always created separate source sets to isolate unit from integration tests. This source set has separate dependencies/etc, and _can_ "extend" the unit test source set if you want it to.

I think Maven makes this separation messy because the unit & integration tests _are_ co-mingled in the same source set (`src/test`). Maven relies on 2 separate plugins for running the sets of tests and uses a naming convention to separate them.

You also mention `have the same tests for both native and non-native mode` - but is that the reality? In your unit tests you will test "layers" of your app in isolation using mocking/stubbing/spying, whereas in integration tests you are interacting with your app "from the outside". That is why `@QuarkusTest` tests run with the `test` profile but the `@QuarkusIntegrationTest` tests run with the `prod` profile.

**Comment by edeandrea** [comment]
@geoand I'm playing with this a little bit. If I have a Gradle project and inside `src/native-test/java/org/acme/ExampleResourceIT.java`:

```java
package org.acme;

import io.quarkus.test.junit.QuarkusIntegrationTest;

@QuarkusIntegrationTest
public class ExampleResourceIT extends ExampleResourceTest {

    // Execute the same tests but in native mode.
}
```

If I then run `./gradlew clean build`, that test is NOT executed. It seems it only gets executed if I run the `testNative` task in isolation. Running the `testNative` task though tells Gradle to build a native image.

So maybe I see where @GregJohnStewart is coming from - having _just_ integration tests that you want to run against the output of a Gradle build (not necessarily only against native images) requires some "manual labor" by the developer.

Following [this guide](https://quarkus.io/guides/getting-started-testing#quarkus-integration-test) shouldn't I be able to run these integration tests against whatever the output of the build is?

If I simply run `./gradlew clean build`, it attempts to build the native image and then run the tests in the `native-test` source set against it. If that's how it should behave then I think that is wrong.

**Comment by geoand** [comment]
I haven't used Quarkus with Gradle in a while, so I'll have to check and come back

**Comment by GregJohnStewart** [comment]
Yeah, same on preferring Gradle myself :)

I fully understand the purpose of integration tests, and makes sense for separate source sets, where the `check` (or similar) command would tie them together (and run both). Yes, the maven model seems to be muddying the field, and I have thusfar been trying to keep things out of `native-test` as it felt like not the place for the tests I am wanting to implement (integration tests runnable against any form of a packaged app). If the `native-test` source set is where integration tests want to live, then that's fine and I'm looking forward to the name change, but it seems that the tests in this source set are only ever run in the `nativeTest` task.

That being said, I also saw that with a `build`, the integration tests (in `native-test`) do not run. If we got it working where `native-test` becomes `integration-test` and are run during a `check` (or similar) task then that works with me.

I did end up finding the test quickstart that seems to clear up the Maven questions, though.

**Comment by edeandrea** [comment]
From my perspective the workflow you are mentioning (being able to run integration tests with a `check` or `build` task) is a valid one. You _should_ be able to run the integration tests against whatever the output of the build is.

In my opinion what is there currently is broken. One workaround I did find is that if you do `./gradlew build` and then follow it with `./gradlew nativeTest`, then integration tests in the `native-test` source set are run against the produced jar. NOTE that `./gradlew build nativeTest` doesn't work (because of the way gradle creates its task graphs.

I don't know the internals of the Quarkus Gradle plugin, but something doesn't seem to be right. The `quarkusBuild` task shouldn't be building a native image unless specifically asked to do so (by using the `--native` flag).

**Comment by geoand** [comment]
cc @glefloch who knows more about the Gradle plugin than anyone

**Comment by geoand** [comment]
@glefloch can you perhaps take a look at the issues Eric mentions? 

Thanks!

**Comment by glefloch** [comment]
Yes sure

**Comment by glefloch** [comment]
Looking back at the plugin code, we indeed have a `testNative` task that depends on `quarkusBuild`. When running the `testNative` task we force the `quarkus.package.type` property to `native`, meaning that running `./gradlew clean testNative` will first trigger a `quarkusBuild` with the system property `quarkus.package.type=native`. 

When first running `./gradlew quarkusBuild` and then `./gradlew nativeTest`, `@QuarkusIntegrationTest` tests work because gradle won't run the `quarkusBuild` as it looks "UP-TO-DATE" (which is an issue with the task input/output I think)

I don't know how to handle this. There `buildNative` and `testNative` task that forces the package type to `native` which based on task name seems legit.  But on the other hand, we are not able to run `@QuarkusIntegrationTest` without some special configuration in the build file (I wasn't aware of that).

As mention in #21997 should we introduce a new integration test sourceset in gradle ? and in the future start deprecating the `native-test` source set ?

**Comment by geoand** [comment]
> As mention in https://github.com/quarkusio/quarkus/pull/21997 should we introduce a new integration test sourceset in gradle ? and in the future start deprecating the native-test source set ?

I think so. @aloubyansky WDYT?

**Comment by glefloch** [comment]
This would also fix the issue faced in #22982

**Comment by edeandrea** [comment]
Keep in mind though (also described in #22035) that it needs to be backwards compatible. On the Maven side, the execution of integration tests is done by the `maven-failsafe-plugin`, which means there really isn't much (if anything?) that the `quarkus-maven-plugin` does. Therefore backwards-compatibility isn't an issue because existing projects will just continue doing what they're doing. Its on the user to make changes to `pom.xml`.

In Gradle, however, the source set config/execution is managed by the Quarkus Gradle plugin. That plugin will need to support both the `native-test` source set as-is today as well as a new/renamed source set. Otherwise any apps already out there that still use `native-test` will be broken.

There needs to be a deprecation period in place for users to migrate away before its removed completely.

**Comment by glefloch** [comment]
Right, we won't just rename the sourceset, we will have to create a new source set without the extra `quarkus.package.type=native` and then start deprecating the default `native-test` source set. 

What do you think of first creating that new source set and then updating code start? Have a preference for the source set name ? `it` / `integrationTest` ?

**Comment by GregJohnStewart** [comment]
My own opinion, but `intTest` is my pick, more succinct than `integrationTest` and more descriptive than just `it`

**Comment by aloubyansky** [comment]
> > As mention in #21997 should we introduce a new integration test sourceset in gradle ? and in the future start deprecating the native-test source set ?
> 
> I think so. @aloubyansky WDYT?

Makes sense to me.

**Comment by edeandrea** [comment]
> I'm ok with `src/intTest/java`, this is different from the current `src/native-test/java` but I'm not sure user will get both source set at the same time, so I think it's ok. @geoand, @aloubyansky do you agree ?

@glefloch Maybe better to take that conversation over to #22035 since that ticket has been around for a bit and is specifically for this?

**Comment by glefloch** [comment]
Sure i will sum up everything there. I should be able to come up with a PR quite soon.

**Comment by sdaclin** [comment]
Hello there,
I wonder why the annotation `io.quarkus.test.junit.QuarkusTest` is declaring the jUnit tag `io.quarkus.test.junit.QuarkusTest` whereas the annotation `io.quarkus.test.junit.QuarkusIntegrationTest` isn't declaring any ?
To me it would very easy to have a dedicated tag to be able to include/exclude these in several test runs ?

Something like this for instance : 
``` kotlin
tasks.test {
    useJUnitPlatform {
        excludeTags("io.quarkus.test.junit.QuarkusIntegrationTest")
    }
}

tasks.register<Test>("intTest") {
    group = "verification"
    useJUnitPlatform {
        includeTags("io.quarkus.test.junit.QuarkusIntegrationTest")
    }
    shouldRunAfter("test")
}

tasks.check {
    dependsOn("intTest")
}
```

**Comment by geoand** [comment]
> shouldRunAfter("test")

This is not enough. `@QuarkusIntegrationTest` ests need to run after the application artifact (jar, container or native-image) is built.

**Comment by sdaclin** [comment]
> `@QuarkusIntegrationTest` tests need to run after the application artifact

Definitely, it's more likely to be something like :
```kotlin
dependsOn("assemble")
shouldRunAfter("test")
```

**Comment by edeandrea** [comment]
Really needs to be `mustRunAfter("Quarkus build")` and perhaps even `build.finalizedBy("intTest")`

**Comment by GregJohnStewart** [comment]
Bump to this! How goes it?

**Comment by geoand** [comment]
I don't think anyone is currently working on it

**Comment by glefloch** [comment]
I started some work before holidays, I will and push it. I was waiting for the maven PR to be merge before.

**Comment by edeandrea** [comment]
The maven PR is about whether or not to always run the integration tests (instead of only in the native profile).

Currently it's impossible to even run `@QuarkusIntegrationTest`s in Gradle right? That needs to be fixed.

Whether or not to always run them (i.e. `build.finalizedBy(intTest)` is a different problem. I think regardless we need the `intTest` tasks and source set.

Just my $0.02.

**Comment by FengHuangDong** [comment]
I want to try use different migrate sql in my IT，so i will set test profile in my application.yaml:

`# With profiles
"%test":
  quarkus:
    flyway:
      locations: db/migration,test/db/migration`

But it didn't work in @QuarkusIntegrationTest, maybe i think because maven build package not test env? 
How can i insert mock data to testcontainers pg with QuarkusIntegrationTest?

**Comment by edeandrea** [comment]
Hi @FengHuangDong I'm not sure [your comment](https://github.com/quarkusio/quarkus/issues/23528#issuecomment-1056534773) has anything to do with the issue being discussed in this ticket? It might get more visibility if you [start a discussion thread](https://github.com/quarkusio/quarkus/discussions) about it?
