### ISSUE TITLE
SecurityConstrainer may cause BlockingOperationNotAllowedException 

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#23547]
### Describe the bug

Setup: `resteasy-reactive`, `security`, proactive authentication is **disabled** (`quarkus.http.auth.proactive=false`)

A `BlockingOperationNotAllowedException` is thrown when a resource method is annotated with `@RolesAllowed` and `@NonBlocking` and the method does not return an async type (`Uni<T>`).

It seems that permissions defined via config in `application.properties` work just fine.

### Expected behavior

The build should fail with a more informative error message.

### Actual behavior

An HTTP request fails at runtime.

### How to Reproduce?

1. Checkout https://github.com/mkouba/quarkus-quickstarts/tree/blocking-get-identity
2. Run `mvn quarkus:dev` in the `security-jpa-quickstart`
3. HTTP GET `http://localhost:8080/api/admin`

### Quarkus version or git rev

999-SNAPSHOT

**Comment by mkouba** [comment]
CC @michalszynkiewicz

**Comment by michalvavrik** [comment]
[Docs](https://quarkus.io/guides/security-built-in-authentication#proactive-authentication) says that *authentication process will only be run when an identity is requested, either because there are security rules*, that tells me that authentication for the endpoints with @RolesAllowed should be effectively always proactive. `quarkus-extensions-security` module is aware of `javax.annotation.security.RolesAllowed` existence, thus it should be able to differentiate if the endpoint is annotated.

```
quarkus.http.auth.proactive=true
curl -v http://localhost:8080/api/admin -> 401
curl -v http://localhost:8080/api/admin admin:admin -> 200 admin

quarkus.http.auth.proactive=false
curl -v http://localhost:8080/api/admin -> 401
curl -v http://localhost:8080/api/admin admin:admin -> 200 admin
```

I'll check over the weekended whether this conclusion makes any sense and if so, try to fix it.

**Comment by michalvavrik** [comment]
I don't think that it's possible to impl. the issue "Expected behavior" (fail with more informative message) for all usages of vertx-http - the ex. message is very clear in information Quarkus Security has, vertx-http has no knowledge of link between route and RBAC annotated endpoint. It must be done on the level where route is already linked with REST endpoint/CDI bean method. F.e. in RR.

**Comment by sberyozkin** [comment]
@michalvavrik Looks like it is resolved as well ?

**Comment by michalvavrik** [comment]
yeah @sberyozkin, Martin speaks about resource method and that's resolved.

There is related problem with bean methods annotated with RBAC running on IO thread that returns something in a synchronous manner (e.g. you have non-blocking resource method that call service method like String getMe() annotated with @RolesAllowed), but that's really difficult to fix if authentication didn't happen further up in the chain. In order to get identity, you would have to switch thread or rewrite the way intercepted methods are invoked.
