### ISSUE TITLE
Introduce a hibernate reactive variant of the security JPA extension

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#23553]
### Description

The `quarkus-security-jpa` extension depends on `quarkus-hibernate-orm` so it would have to live in a separate extension. However, the `@Username`, `@Password` and `@Roles` annotations could be shared.

**Comment by geoand** [comment]
Definitely +1 for this

**Comment by Sanne** [comment]
+1

from a usability point of view, it would be nice if it could switch internal implementation automatically, based on the bound datasource being blocking or reactive.

**Comment by SetoKaiba** [comment]
Any update on it? We still can't use it with reactive?

**Comment by egore** [comment]
I started working on this a couple of days ago at https://github.com/egore/quarkus-security-jpa-reactive, as a copy&modify approach. Unfortunately I am currently stuck at the QuarkusSecurityJpaProcessor, which still created the dynamic class using the EntityManager instead of a mutiny session. I think I can steal a good portion from the UserEntityIdentityProvider, but there I had to work around the lack of bySimpleNaturalId of Mutiny.Session.
