### ISSUE TITLE
Buildpack for Quarkus/Quarkus Native

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#23559]
### Description

I've started using Quakrus Buildpacks but I couldn't find any buildpack for Quarkus, the only one that is available is of the Boson project but it is Boson-based and is not generic enough to work standalone.

### Implementation ideas

Develop a buildpack for Quarkus / Quarkus Native and use them as default configuration values

**Comment by geoand** [comment]
cc @iocanel @BarDweller

**Comment by geoand** [comment]
@iocanel @BarDweller is this something that already exists?

**Comment by iocanel** [comment]
I think so

**Comment by geoand** [comment]
@BarDweller has this been implemented?

**Comment by BarDweller** [comment]
There are a variety of ways to use buildpacks with Quarkus. 

We started by looking at creating a standalone 'quarkus buildpack' that would go into a builder image, but found it to be of limited use. These builders are in the snowdrop github, and use simple bash scripts for the detect/build. They are at best prototypes, and due to their standalone nature miss out on much that buildpacks can offer through being part of an ecosystem of buildpacks that work together to implement a build. 

As a result of those investigations we decided to become part of the Paketo buildpack ecosystem, and work towards adding UBI and Quarkus to their builders.

At this stage, we have created and published a UBI Paketo builder image (`paketocommunity/builder-ubi-base`) that contains the Quarkus buildpack (along with the rest of the Paketo java ecosystem, but using a Java runtime supplied by UBI). Note that this does not currently cover Quarkus native, which would require an alternate builder image, in the same manner Paketo handles native for non UBI builders. The UBI Builder image makes use of Builder Image Extensions, that are part of CNCF Buildpacks Platform spec 0.10, if you are using pack cli, make sure it's a recent version. If you are using Quarkus's Container Image Buildpack support, that currently only implements Platform spec 0.4, but I'm working on the update to allow it to cover 0.4-0.12 which should be ready soon. If you are using tekton pipelines, make sure they are correctly implementing at least platform spec 0.10 (Released October 2022) with support for Image Extensions. Many are still at 0.4, or 0.7. 

Quarkus will also work with the non UBI Paketo images (although you have to either configure your Quarkus project options so the targets are seen as expected, or manually include the Paketo Quarkus buildpack when building via pack cli).

**Comment by geoand** [comment]
Thanks for the update @BarDweller
