### ISSUE TITLE
LRA extension endpoints are populated to Swagger UI automatically

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#23586]
### Description

When using LRA and OpenAPI + Swagger UI, all LRA endpoints + business endpoints are shown in the UI. I think that by default it should show only business endpoints and if it is set, then show the LRA endpints

<img width="1198" alt="Screenshot 2022-02-10 at 16 47 10" src="https://user-images.githubusercontent.com/1517153/153444537-da40f31b-7f79-4580-975d-941b9c3fc8ff.png">
endpoints

### Implementation ideas

Remove none business endpoints from swagger UI and add a flag when you want to see them.

**Comment by phillip-kruger** [comment]
Thanks for this. This will have to be in the LRA Extension, but I can also have a look. 
cc @xstefank

**Comment by xstefank** [comment]
I can take a look, @phillip-kruger

**Comment by xstefank** [comment]
I also wonder whether LRA endpoints should go under non-application path. @gsmet ?

**Comment by geoand** [comment]
You mean under `/q`? If so, I think that makes sense

**Comment by xstefank** [comment]
yes, under /q as coordinator paths aren't user paths.

**Comment by geoand** [comment]
Seems reasonable, albeit somewhat breaking

**Comment by xstefank** [comment]
proxy calls should not be exposed to users, these are used if the user doesn't expose business REST methods for participant. But I understand. I'll mention it in the PR.

**Comment by phillip-kruger** [comment]
@xstefank - any news on this ?

**Comment by xstefank** [comment]
@phillip-kruger didn't have much time for this one. Will try to prioritize.

**Comment by xstefank** [comment]
@phillip-kruger I actually got an external contributor willing to look at this :) So sorry that I don't have time for LRA work.
'

**Comment by phillip-kruger** [comment]
No worries :)

**Comment by pcheucle** [comment]
I started looking at this.

My first idea was to change the `@Path` value at build time to move LRA proxy endpoints under non-application path.
But I think that doing changes in the LRA extension processor will not have any effect since these endpoints, coming from Narayana dependency, are already scanned by the REST extension.

My second idea was to recreate proxy endpoints in LRA Extension.
Maybe by creating new JAX-RS resources and making them available to the scanning process using `AdditionalResourceClassBuildItem`, or by creating endpoints using `RouteBuildItem`.
But again, I don't see how to exclude JAX-RS resources coming from the Narayana library.
@xstefank  : in this case, do you think that creating a proxy library without JAX-RS is a possible option ?

**Comment by geoand** [comment]
> @geoand or @xstefank maybe you can help on this ?

I am not familiar with LRA

**Comment by rmanibus** [comment]
@geoand I am working with @pcheucle on this one, 
we are trying to modify some jaxRs annotations in the plugin processor. 
The annotation transformer build item is not working with jaxRs resources.
Is there a way to transform the index that is fed to the jaxRs indexer ?

**Comment by geoand** [comment]
AFAIR, the OpenAPI extension does not take into account the annotation transformer stuff at all, but @phillip-kruger would know for sure

**Comment by phillip-kruger** [comment]
Yea, the best way to achieve this is with filters

**Comment by xstefank** [comment]
@pcheucle, sorry I'm late to the party; I was traveling. I think you're on the right path, but I think we should try a solution where we either transform Narayana classes or remove them and add a new override, as you did. I kind of don't like shading out beans.xml since this can become a problem down the line.

I'll cycle this back to @geoand :) https://stackoverflow.com/a/70847243/14040597. I think this should work for our use case. Maybe `BytecodeTransformerBuildItem` is what we are after.

Your solution as it stands now needs to at least not hardcode the `/q` path since this can be changed with config - https://quarkus.io/guides/all-config#quarkus-vertx-http_quarkus-http-non-application-root-path. We should plug these endpoints into the same non-application endpoint management.

Will you try this?

**Comment by xstefank** [comment]
@MikeEdgar similar case as /q/health or /q/metrics, do we pick those to OpenAPI?

**Comment by MikeEdgar** [comment]
The Health extension can create a filter that adds those paths to the OpenAPI, but I don't believe metrics has that. If those are not using JAX-RS annotations they're invisible to the OpenAPI scanner by default.

**Comment by xstefank** [comment]
@pcheucle TBH, if there is no better way, then we can just "hide" the endpoints from user view for this issue. Just adjust it to take the config changes into account and open a PR please.
