### ISSUE TITLE
Import another gradle module

### ISSUE THREAD

**Issue by vincenzocorso** [quarkusio/quarkus#23617]
### Describe the bug

I have the following gradle multi-module project:
```
app
|- buildSrc
|- quarkus-app
|- spring-app-api
|- spring-app
```
where:
- `buildSrc` contains some gradle conventions files such as `service.spring-conventions.gradle`, `service.quarkus-conventions.gradle`, `api.spring-convention.gradle`
- `quarkus-app` module is a quarkus app. The `build.gradle` file in this module use `service.quarkus-conventions` as plugin to import some recurrent dependencies
- `spring-app-api` module contains some interfaces and classes. Some of them use spring annotations. So this module use `api.spring-convention`
- `spring-app` module is a spring boot app. The `build.gradle` file use `service.spring-conventions` as plugin to import some recurrent dependencies such as `spring-boot-starter-web` and `spring-boot-starter-validation`

If I specify `implementation project(':spring-app-api')` in `quarkus-app` build file, I get an error during the build.

I see that the problem occurs during the `:quarkus-app:quarkusDependency` task 
I don't know if it's my mistake or it's a bug. Is there a way to solve this problem?

### Expected behavior

It should complete the build without errors

### Actual behavior

I get this error
```
A problem occurred configuring project ':quarkus-app'.
> Could not resolve all dependencies for configuration ':quarkus-app:quarkusDependency'.
   > Could not find org.springframework.boot:spring-boot-starter-web:.
     Required by:
         project :quarkus-app > project :spring-app-api
   > Could not find org.springframework.boot:spring-boot-starter-validation:.
     Required by:
         project :quarkus-app > project :spring-app-api

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html
```

### How to Reproduce?

Try to build this project:
[app.zip](https://github.com/quarkusio/quarkus/files/8049115/app.zip)

### Output of `java -version`

java 11.0.10 2021-01-19 LTS Java(TM) SE Runtime Environment 18.9 (build 11.0.10+8-LTS-162) Java HotSpot(TM) 64-Bit Server VM 18.9 (build 11.0.10+8-LTS-162, mixed mode)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.2

**Comment by ethan-gallant** [comment]
This is caused by Quarkus trying to resolve the dependencies of the `spring-app-api` project. When Quarkus bootstraps it depends on the `spring-app-api` package. The `spring-app-api` package depends on the `buildSrc/src/main/groovy/api.spring-conventions.gradle`. 

Because you're pulling in the dependencies like so: 
```
dependencies {
    implementation 'org.springframework.boot:spring-boot-starter-web' <- No Version
    implementation 'org.springframework.boot:spring-boot-starter-validation' <- No Version
}
```

Quarkus has no clue which version of the Spring dependencies to pull in. You can resolve this by either hard coding the versions inside of this file or you can use a `gradle.properties` file and using it to hard-code versions.

I would avoid bringing Spring dependencies into Quarkus if possible in the first place, but that's your issue (missing version in `buildSrc/src/main/groovy/api.spring-conventions.gradle`.

I cannot test locally as the source isn't on GitHub and most people won't execute or open random zip files :smile: If it were on GitHub it would be much easier to help you.

**Comment by glefloch** [comment]
@vincenzocorso where you able to fix the error based on @ethan-gallant comment ?

**Comment by vincenzocorso** [comment]
Yes, solved :+1:

**Comment by glefloch** [comment]
Thanks for the feedback @vincenzocorso and thanks @ethan-gallant for the answer :)
