### ISSUE TITLE
Automatically register health check for Scheduled Task

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#23632]
### Description

Scheduled tasks lack of observability.

We could add a liveness probe for all scheduled jobs if the health extension is present (or maybe configurable with a flag in the @Scheduled annotation).
The HealthCheck could report if the task is overdue, and if the last execution succeeded (did not throw ?).
I think it is easy to implement with quartz directly, but the quarkus Scheduler api lack a method to read the scheduled tasks.

### Implementation ideas

1) allow to read scheduled tasks in quarkus Scheduler:

```java
public interface Scheduler {
     [...]
    List<Trigger> listScheduledJobs();

    Trigger getScheduledJob(String identity);
}
```
2) Expose a status in the trigger:

```java
public interface Trigger {
    [...]
    boolean isOverdue();

    TriggerState getTriggerState();
}
```
3) If Health extension is present, register a health check for each trigger (as it is done for agroal)

The linked PR already solve point 1 and point 2.

**Comment by xstefank** [comment]
@rmanibus is it expected to restart the app if the task is overdue? If the liveness probe reports down the app will be restarted.

**Comment by rmanibus** [comment]
> @rmanibus is it expected to restart the app if the task is overdue? If the liveness probe reports down the app will be restarted.

I think we need a grace period, but after sometime, I think it must be restarted yes

**Comment by mkouba** [comment]
I think that we can close this issue since the Scheduler API now supports both, a) [obtain all scheduled triggers](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/api/src/main/java/io/quarkus/scheduler/Scheduler.java#L60) and b) [test if a trigger is overdue](https://github.com/quarkusio/quarkus/blob/main/extensions/scheduler/api/src/main/java/io/quarkus/scheduler/Trigger.java#L44) so that a custom health check can be registered.
