### ISSUE TITLE
Decorator beans to not appear in /q/arc/beans or /q/arc/removed-beans

### ISSUE THREAD

**Issue by JHahnHRO** [quarkusio/quarkus#23714]
### Describe the bug

Decorator beans do not appear in the list of beans nor in the list of removed beans.

### Expected behavior

Decorator beans should appear in both lists as appropriate, just like Interceptor beans do.

### Actual behavior

Interceptors appear (even have their own graphical list in dev console UI), decorators do not.

### How to Reproduce?

Define a Bean with an interface and a decorator for said interface, e.g.
```
public interface EventCollector {

    List<Object> getFiredEvents();

    <T> void collect(T event);
}


@ApplicationScoped
@Unremovable
public class EventCollectorImpl implements EventCollector {

    List<Object> firedEvents = new ArrayList<>();

    @Override
    public List<Object> getFiredEvents() {
        return firedEvents;
    }

    @Override
    public <T> void collect(final T event) {
        firedEvents.add(event);
    }
}

@Decorator
@Priority(Interceptor.Priority.APPLICATION)
public abstract class EventCollectorDecorator implements EventCollector {

    @Inject
    @Delegate
    @Any
    EventCollector delegate;
}
```
The run quarkus:dev and look in /q/arc/beans, /q/arc/removed-beans, /q/dev/io.quarkus.quarkus-arc/beans, and /q/dev/io.quarkus.quarkus-arc/removed-beans for the decorator.

### Output of `java -version`

11.0.11, vendor: AdoptOpenJDK, runtime: C:\Program Files\AdoptOpenJDK\jdk-11.0.11.9-hotspot

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1 (05c21c65bdfed0f71a2f2ada8b84da59348c4c5d)

**Comment by mkouba** [comment]
FYI removed interceptors are not listed in the result of `/q/arc/removed-beans` either. Mainly because we don't need this kind of information at runtime, removed beans are used to [detect problem with programmatic lookup](https://github.com/quarkusio/quarkus/blob/main/independent-projects/arc/runtime/src/main/java/io/quarkus/arc/impl/ArcContainerImpl.java#L625-L637). But having said that, we could include removed interceptors and decorators in the dev mode.
