### ISSUE TITLE
PanacheMongoEntity: Kotlin: can only find codec if at least one attribute doesn't have default value

### ISSUE THREAD

**Issue by jmpargana** [quarkusio/quarkus#23920]
### Describe the bug

Hey!

First of all I'd like to thank you for an amazing library, which me and my colleagues are loving.

Bug: Instantiation of a `PanacheMongoEntity` extended data class in kotlin fails if *all* attributes have a default parameters. I've read [this section in the documentation](https://quarkus.io/guides/mongodb-panache#working-with-kotlin-data-classes) and this scenario seems like a different situation, than the ones mentioned.

### Actual behavior

```kotlin
@MongoEntity(collection = "test")
data class Test @BsonCreator constructor(
    @BsonProperty("a") val a: String? = null,
    @BsonProperty("b") val b: String? = null,
) : PanacheMongoEntity()
```

Everytime the code reaches an instantiation of this code, it crashes with two exceptions:
1. `Found multiple constructors annotated with @BsonCreator`
2. `Can't find a codec for class de.goodright.care.controller.Test`

If on the other hand, at least one of the attributes does not have a default value, like so:

```kotlin
@MongoEntity(collection = "test")
data class Test @BsonCreator constructor(
    @BsonProperty("a") val a: String?,
    @BsonProperty("b") val b: String? = null,
) : PanacheMongoEntity()
```

It works, but forces us to define it everytime we create an instance elsewhere.

### Output of `uname -a` or `ver`

5.16.5-zen1-1-zen

### Output of `java -version`

openjdk version "11.0.14.1"

### Quarkus version or git rev

1.12.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

3.8.4

### Additional information

I'd be happy to provide any additional information, and eventually contribute with a solution, if you consider it a beginners issue or feature.

Best regards,
Joao Pargana

**Comment by evanchooly** [comment]
I'll dig in to this one.  I'm pretty familiar with this particular problem because I already dealt with it in [morphia](https://morphia.dev).  If you don't need panache query support explicitly, there's a [quarkiverse extension for morphia](https://github.com/quarkiverse/quarkus-morphia) that might get you want.  Or it might not.

**Comment by evanchooly** [comment]
OK.  As I suspected this is an artifact of how default methods are implemented by the kotlin compiler and the driver doesn't know how to accommodate it.  In the byte code you actually end up with 3 constructors:  one that takes both parameters, one that takes none, and a synthetic one used by kotlinc internally.  The first two constructors get the `@BsonConstructor` applied to both.  When the driver finds both of those constructors, it throws an error because it doesn't know which one to use at that point.  I don't know that there's nothing (reasonable?) we can do from the quarkus side to fix this.  In Morphia, we take the constructor that best matches the arguments and use that and then backfill the other fields via field/setter access, depending.  But the Java driver doesn't have this context to perform that kind of logic.

It's like that old saying, "A man with a watch always knows what time it is.  A man with two watches is never quite sure."

**Comment by jmpargana** [comment]
Thank you very much for taking the time and for the explanation. We'll look into morphia as an alternative for panache
