### ISSUE TITLE
RestEasy Reactive Client returns org.jboss.resteasy.reactive.common.jaxrs.StatusTypeImpl instead of javax.ws.rs.core.Response.Status

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#23952]
### Describe the bug

```org.jboss.resteasy.reactive.common.jaxrs.ResponseImpl.getStatusInfo()``` returns an instance of ```org.jboss.resteasy.reactive.common.jaxrs.StatusTypeImpl``` rather than the expected instance of ```javax.ws.rs.core.Response.Status```

### Expected behavior

RestEasy class client returns an instance of ```javax.ws.rs.core.Response.Status``` 

### Actual behavior

RestEasy reactive client returns ```org.jboss.resteasy.reactive.common.jaxrs.StatusTypeImpl```

### How to Reproduce?

From a ClientResponseFilter, call ```responseContext.getStatusInfo()```.   You'll get a ```org.jboss.resteasy.reactive.common.jaxrs.StatusTypeImpl```.

```org.jboss.resteasy.reactive.common.jaxrs.StatusTypeImpl``` could be written with a static factory to produce one of the standard  enum values and fallback to `custom` value:

```java
    public static StatusType getStatusInfo() {
        StatusType standard= Response.Status.fromStatusCode(state.getResponseStatus());
        return standard!=null ? standard :new StatusTypeImpl(state.getResponseStatus(), state.getResponseReasonPhrase());
    }
```

A possible drawback is that for for a standard StatusType, any message from the server is replaced with the standard message.  This is the classic RestEasy client behavior.

**Comment by geoand** [comment]
Thanks for reporting, but I fail to see why this is a problem. Mind elaborating?

**Comment by chonton** [comment]
I was under the impression that resteasy-reactive-client is, as much as possible, a drop-in replacement for resteasy-client

**Comment by geoand** [comment]
To the extent it makes sense.

**Comment by chonton** [comment]
Closed by lazy consensus.

**Comment by michalsomora** [comment]
I bumped to this issue after migrating from quarkus 3.12 (classic resteasy) to 3.15 (reactive). In code where we catch WebApplicationException and check status code like this 
`e.getResponse().getStatusInfo() == Status.NOT_FOUND` the condition always evaluate to false since statusInfo returns StatusTypeImpl class instead of standard Response.Status enum, any specific reason why not use class from jakarta api?

Workaround is to use equals instead
e.getResponse().getStatusInfo().equals(Status.NOT_FOUND)
