### ISSUE TITLE
grpc, intinispan and kafka integration.

### ISSUE THREAD

**Issue by hernael** [quarkusio/quarkus#23960]
### Description

Given a Protofile the quarkus-maven-plugin automatically generates the message classes for grpc protocol.
If infinispan is used in addition to grpc, then the Marshaller classes required by infinispan could be generated automatically.
Additionally support for kafka could be added with protobuf and Schema Registry.

**Comment by michalszynkiewicz** [comment]
How does it work currently for Infinispan marshaller classes?

**Comment by hernael** [comment]
hi @michalszynkiewicz current procedure would be something like this:
1. Place your proto files in src/main/proto and run mvn compile. This step generate model classes for grpc (https://quarkus.io/guides/grpc-service-implementation)
2. Once the classes are generated, Have to create your own Marshaller(s) yourself (https://quarkus.io/guides/infinispan-client#custom-serialization)

However, this second step has two drawbacks:
1. Quarkus guide indicates that MessageMarshaller interface should be implemented, but this "interface is deprecated and planned for removal in a future version of ProtoStream" (https://infinispan.org/docs/stable/titles/encoding/encoding.html#protostream-sci-implementations_marshalling)
2. Making our own marshells is error prone given a change in Protofile Message

I think that creation of Marshaller classes can be generated automatically in compile time

It would also be great if these protofiles can be used with Kafka Protobuf Serializer support

**Comment by hernael** [comment]
MessageMarshaller documenation:
`since 4.3.1.Final. Will be removed in version 5. Please use annotation based marshallers instead. See AutoProtoSchemaBuilder`
(https://www.javadoc.io/doc/org.infinispan.protostream/protostream/latest/org/infinispan/protostream/MessageMarshaller.html)

So, it will not be possible to create the Marshallers from the classes autogenerated by grpc

**Comment by cescoffier** [comment]
Yes, this feature is still in flux last time I asked, which is why we cannot integrate with it without risking breaking change in the future. That being said, we have several ongoing work around gRPC that will simplify such integration:

1 - on the server side, we may remove the gRPC server we are using to use a pure Vert.x approach
2 - on the protoc side, we are exploring protoc less approaches and Java first based approaches (where the proto files are generated from the java classes - it's where you can see the relation with infinispan)

**Comment by hernael** [comment]
@cescoffier thanks for answering me.
Work with Java First Approache sound good :)

Currently if you want to use grpc + infinispan + kafka with schema registry, then is necessary to use avro.. all that together under current approach (a protofile for grpc, a class with annotations for infinispan and an avsc file for avro) becomes complicated application maintenance.

If the same approache can be applied to kafka with schema registry and proto it would be great.
All together in a single java class with annotations.

P.S. i guess this issue can be closed

**Comment by cescoffier** [comment]
In JVM mode, you can use use the protobuf serde for Kafka. It's rather rare (Avro is more popular in the Kafka world), but not impossible. 

Also, Infinispan only supports protobuf messages, not gRPC. It does not handle the "interface" definition. gRPC central-point are these interfaces. That's why we are trying to see how we can combine both.

(Closing as proposed).
