### ISSUE TITLE
Configuration options for locales

### ISSUE THREAD

**Issue by andlinger** [quarkusio/quarkus#23975]
### Description

Issue #22808 mentions several configuration options that are either not mentioned at all or possibly not mentioned "correctly" in the all-config guide.

For example, in the description for the property `quarkus.locales` the following sentence is mentioned in the guide:
> Native-image build uses it to define additional locales that are supposed to be available at runtime.

However, the issue talks about `quarkus.native.locales`. I have tested this property and it works. 
Which of these properties must be used and when? Are both needed at all or can one of them be removed?

The following two properties mentioned in the issue do not appear in the guide at all:
```
quarkus.native.user-language
quarkus.native.user-country
```

**Comment by gsmet** [comment]
`quarkus.native.user-language` and `quarkus.native.user-country` are deprecated and thus not appearing in the documentation.

What is documented is what you should use. The initial implementation described in the issue was heavily overhauled during the review cycle because `quarkus.default-locale` and `quarkus.locales` were already present to serve this purpose.
