### ISSUE TITLE
Qute - localization - multi-module project - need for duplicated resources/messages and beans.xml

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#24090]
### Describe the bug

Qute - localization - multi-module project - need for duplicated resources/messages and beans.xml

I have created https://github.com/rsvoboda/rsvoboda-playground/tree/master/qute-multimodule, api module contains all the necessary code and files, test module uses api module and focuses on testing.

`qute-api` and `qute-test` modules have the identical LocalizedMessagesTest. qute-api based tests work fine / without any workarounds.

But to make qute-test based tests work I had to:
 1) create empty beans.xml in qute-api
 2) copy resources/messages from qute-api to qute-test

For point 1) Would it be possible to auto-discover `@MessageBundle` interfaces?
It was not straightforward to figure out that I need to check https://quarkus.io/guides/cdi-reference#bean_discovery

For point 2) I don't really understand why is this dupplication needed, I would like to have everything in `qute-api` module.

### Expected behavior

No need to duplicate resources/messages, ideally also no beans.xml needed

### Actual behavior

Need for duplicated resources/messages and beans.xml

### How to Reproduce?

Use my sample qute-multimodule project
```
git clone https://github.com/rsvoboda/rsvoboda-playground.git
cd rsvoboda-playground/qute-multimodule
mvn clean verify
```

To see the failures:
- remove beans.xml in qute-api
- remove resources/messages in qute-test

### Output of `java -version`

Java 17

### Quarkus version or git rev

2.7.3.Final

**Comment by mkouba** [comment]
> But to make qute-test based tests work I had to:
> 
>     1. create empty beans.xml in qute-api

You need to add the `beans.xml` or any other marker file in order to make the `qute-api` an application archive. Otherwise the `qute-api` is not part of the app index if you run your app from within `qute-test` module. This behavior is not qute-specific. See also the [Working with multi-module projects](https://quarkus.io/guides/maven-tooling#multi-module-maven) and [Bean Discovery](https://quarkus.io/guides/cdi-reference#bean_discovery) docs. I'm no quarkus multi-module expert but I believe that this requirement applies to any other app components (CDI beans, JAX-RS resources, etc.). CC @geoand @aloubyansky 

> 
>     2. copy resources/messages from qute-api to qute-test

I think that this is something we should fix. Currently, we only load the message files from the app root which is probably a leftover from the original design/POC where only files from `src/main/resources/templates` folder of the root app archive were considered (ofc this is no longer the case). I'll try to prepare a PR.

**Comment by geoand** [comment]
> but I believe that this requirement applies to any other app components (CDI beans, JAX-RS resources, etc.)

Correct

**Comment by Chexpir** [comment]
FYI, so it appears in Google to future people searching for this issue.

After this fix, I believe we can get errors like this one (catching it now during Quarkus upgrade on one service we use qute)

```
  java.lang.IllegalStateException: Duplicate localized files found:
- alert_en.properties: [/app/workdir/x-core-extension/integration-test/build/resources/test/messages/alert_en.properties, /app/workdir/x-core-extension/runtime/build/resources/main/messages/alert_en.properties]
```
