### ISSUE TITLE
Implementation of BeanManager#getELResolver()

### ISSUE THREAD

**Issue by feichtegger** [quarkusio/quarkus#24101]
### Description

Is there a reason why `BeanManager#getELResolver()` has not been implemented yet?

It would be great if the `BeanManager` would return an instance of `ELResolver` instead of throwing an `UnsupportedOperationException`.

**Comment by manovotn** [comment]
> Is there a reason why BeanManager#getELResolver() has not been implemented yet?

Because Quarkus/Arc doesn't implement EL.
Beans can and do have names (via `@Named`) and you can resolve them based on their names using `BeanManager.getBeans(String name)`.

I *think* there is something done for Qute that might resemble what you need, but it won't be standard EL. @mkouba might know more.

**Comment by mkouba** [comment]
Indeed, we don't implement the EL resolver deliberately because there's no standard use case for EL in quarkus (no JSP, no JSF, etc.). However, it should be fairly easy to create a custom EL resolver to cover most of the basic requirements. 

The Qute integration with `@Named` beans is really simple: https://github.com/quarkusio/quarkus/blob/main/extensions/qute/runtime/src/main/java/io/quarkus/qute/runtime/EngineProducer.java#L148-L157, although while looking at it now it's not 100% correct because a `@Dependent` bean is destroyed before it's actually used (I've created https://github.com/quarkusio/quarkus/issues/24137). 

The MyFaces quarkus extension has a [basic EL resolver impl](https://github.com/apache/myfaces/blob/master/extensions/quarkus/runtime/src/main/java/org/apache/myfaces/core/extensions/quarkus/runtime/spi/QuarkusCdiELResolver.java) too.

**Comment by StephenOTT** [comment]
@mkouba is this still the case (no standard use case for EL) given that Qute has a expression language ?

**Comment by mkouba** [comment]
> @mkouba is this still the case (no standard use case for EL) given that Qute has a expression language ? As in, because quite implements a expression lang, is there a good use case to support getELResolver?

Well, Qute does not implement a complex "expression language", see the [docs](https://quarkus.io/guides/qute-reference#expressions). So EL support is not really needed.
