### ISSUE TITLE
Allow Map config properties to contain enum keys

### ISSUE THREAD

**Issue by edeandrea** [quarkusio/quarkus#24214]
Currently it seems that config properties that are `Map`s are only allowed to be keyed by `String`. Allowing `enum` constants as keys would be good to have.

**Comment by edeandrea** [comment]
This came out of #18572. [See comments there](https://github.com/quarkusio/quarkus/issues/18572#issuecomment-1063078066) for more details.

**Comment by geoand** [comment]
Thinking about this more, I actually don't think this is tremendously useful. I understand it's usefulness in what you are trying to do with the Jackson configuration, but I can't remember it ever being useful for any other domain.

@radcortez any thoughts?

**Comment by radcortez** [comment]
We do support Enum keys in SR `@ConfigMapping`. Recently, I've added support to allow the use of SR `@ConfigMapping` for Quarkus extensions, so we could move the config in that direction if we really want to support Enum keys.

**Comment by gastaldi** [comment]
I think this is useful to support auto-completion of Map keys in the IDEs, also you get free key validation.

**Comment by radcortez** [comment]
Does it count if you use SR Config Mapping instead of ConfigRoot? :) It should work for Quarkus Extensions now.

**Comment by gastaldi** [comment]
I think so, what's the impact in the codebase if we (hypotetically) deprecated `@ConfigRoot` on behalf of  `@ConfigMapping`?

**Comment by radcortez** [comment]
Right now,`@ConfigRoot` is still required with `@ConfigMapping` because SmallRye Config has no knowledge about Config Phases (it's Quarkus specific), so you actually use both annotations. We could change this to add something specific just for the phases, but I didn't want to add a new annotation at this point.

This is what it looks like: https://github.com/quarkiverse/quarkus-jberet/commit/22eba2660d8834adfea6c7731dbeb5a2d60768a7

Moving all the current `@ConfigRoots` will require changing from `class` to `interface` and from field accessors to method calls. This will break any users that may be using these classes directly, so I'm not sure if we want to do that.

Alternatively, we could add class support to `@ConfigMapping` (`yikes!`) and replace the Quarkus backing Config Extension implementation with SmallRye Config.

Independently of how we move forward, I would like to phase out the Quarkus implementation, because it requires us to maintain two competing implementations.

**Comment by gastaldi** [comment]
> Moving all the current `@ConfigRoots` will require changing from `class` to `interface` and from field accessors to method calls. This will break any users that may be using these classes directly, so I'm not sure if we want to do that.

You mean fixing it as it should have been from day one 😆  ? I'm +1000 on that. Perhaps something we need to promote more and to be considered the default in Quarkus 3.0

> Alternatively, we could add class support to `@ConfigMapping` (`yikes!`) and replace the Quarkus backing Config Extension implementation with SmallRye Config.

That's a good idea and it would ease the transition a lot.

**Comment by radcortez** [comment]
> > Alternatively, we could add class support to `@ConfigMapping` (`yikes!`) and replace the Quarkus backing Config Extension implementation with SmallRye Config.
> 
> That's a good idea and it would ease the transition a lot.

But in this case, the class approach will never go away. No one would bother to move to interfaces if the current one is working.

**Comment by radcortez** [comment]
Oh from your comment here:

> You mean fixing it as it should have been from day one 😆 ? I'm +1000 on that.

I thought you wanted to get rid of the classes as well. I guess you were just referring to fields vs method access?

**Comment by gastaldi** [comment]
> I thought you wanted to get rid of the classes as well. I guess you were just referring to fields vs method access?

Well, yes and no. Ideally I'd like to migrate all our config classes to interfaces (because it makes more sense to be modeled that way IMHO) but I understand that change is not practical, therefore what I am proposing is that if you want to phase out the Quarkus implementation, we need to at least provide the same features `@ConfigMapping` offers. That would at the bare minimum allow us to deprecate the `@ConfigRoot` annotation safely

**Comment by radcortez** [comment]
So `@ConfigMapping` supports everything that `@ConfigRoot` supports, plus a lot of other stuff (namely mapping support for almost every type combination).

The only thing that it doesn't support is its classes. It is something that I'm not really thrilled to add. I added some semi support for MP `@ConfigProperties` classes (another mistake!). Anyway, if there is interest in this we could add such support to make a possible migration less painful.

**Comment by radcortez** [comment]
We are closing this since we support it in `@ConfigMapping`, and we can use them with Extensions.
