### ISSUE TITLE
PanacheRepositoryBase generates invalid query with Hibernate Reactive

### ISSUE THREAD

**Issue by AmsterdamFilho** [quarkusio/quarkus#24367]
For the query "id in ?1 and message.workspaceId = ?2", PanacheRepositoryBase generated an invalid query in Postgres.

This happens only when message extends for another class using Joined Strategy and workspaceId is in the parent table

Reproducer created here https://github.com/amsterdam-superchat/quarkus-hibernate-delete-issue

Just run the code, open swagger ui, and execute the only endpoint there.

**Comment by loicmathieu** [comment]
Can you please comment with the line of code causing the issue, the exception message and the generated query. You can have the generated query in the log by enabling Hibernate logging via `quarkus.hibernate-orm.log.sql=true`

**Comment by AmsterdamFilho** [comment]
I created a whole reproducer actually. @loicmathieu

**Comment by AmsterdamFilho** [comment]
But here is the generated query 
```
delete 
    from
        tagged_message cross 
    join
        message messagerec1_ 
    where
        (
            id in (
                $1 , $2
            )
        ) 
        and messagerec1_1_.workspace_id=$3
```

And the exception message is `io.vertx.pgclient.PgException: ERROR: syntax error at or near "cross" (42601)`

**Comment by loicmathieu** [comment]
This seems like an Hibernate Reactive issue which generates a wrong SQL queries from what it appears to be a valid JPQL query.

Before asking someone else to have a look I just want to check one of two small things first:

- I notice your reactive pg URL is not like the one from the guide (see https://quarkus.io/guides/hibernate-reactive-panache#setting-up-and-configuring-hibernate-reactive-with-panache) can you check with `vertx-reactive:postgresql://localhost:5432/mydatabase` instead of `postgresql://localhost:5432/postgres`
- I'm not sure Flyway is compatible with Hibernate ORM reactive, I fear that having both reactive and non-reactive client may be problematic. Can you try to remove Flyway and the non-reactive client and see if the issue still occurs ? You can use SQL init script to setup the database

**Comment by amsterdam-superchat** [comment]
I implemented locally the two changes you suggested and the error was the same.

**Comment by AmsterdamFilho** [comment]
I implemented locally the two changes you suggested and the error was the same.

**Comment by loicmathieu** [comment]
Thanks, so the issue seems to be on the Hibernate reactive side which generates a wrong query in your case. Maybe @Sanne can have a look ?

**Comment by DavideD** [comment]
I can  check in a bit. I know that I can check, but maybe you can tell me what  query Panache is passing to Hibernate Reactive?

**Comment by DavideD** [comment]
That syntax doesn't work with Hibernate ORM or Reactive.
You can rewrite the function this way and it should work:
```
    fun delete(ids: List<UUID>, workspaceId: UUID): Uni<Void> {
        return delete("id IN ( select t.id FROM TaggedMessageRecord t where t.id in ?1 and t.message.workspaceId = ?2)", ids, workspaceId)
            .replaceWithVoid()
    }
```

**Comment by DavideD** [comment]
I guess this is something for the Hibernate ORM team to look into. It should be possible to translate the JPQL to the working SQL.

**Comment by amsterdam-superchat** [comment]
Rewriting the query as you suggested did work. Thank you!

**Comment by AmsterdamFilho** [comment]
Rewriting the query as you suggested did work. Thank you!
