### ISSUE TITLE
Add Extension for AWS Alexa Skill Kit (ASK SDK v2 for Java)

### ISSUE THREAD

**Issue by HemanandRajamani** [quarkusio/quarkus#2461]
Adding the extension for AWS Alexa Skill Kit (ASK SDK v2 for Java) will enable supersonic start up of the aws lambda function and will help Alexa skills to get around the cold start delay without compromising the use of the already existing quarkus extensions.

**Comment by gsmet** [comment]
@marcinczeczko is there something that make sense to add to your AWS services extensions?

**Comment by marcinczeczko** [comment]
@gsmet - Alexa sdk is a different SDK. I didn't consider it, but it's worth to look at at some point in the future

**Comment by fcracker79** [comment]
Up to this point I managed to use Quarkus to implement an Alexa skill, not natively. Unfortunately, though, it seems to be that when I try to make it native, the compilation fails because of references to unsupported methods (mostly from `java.lang.Thread`).
I have opened an issue on StackOverflow (https://stackoverflow.com/questions/59531126/native-quarkus-with-aws-lambda-does-not-build/59576326#59576326). No luck for the moment.

**Comment by fcracker79** [comment]
All in all, I managed to implement a fully functional Alexa Skill using Quarkus native.
You can find all the details [here](https://medium.com/@fcracker79/implementing-alexa-skill-using-quarkus-native-459f04cded10).
Hope this help to move forward to the implementation of an extension.

**Comment by geoand** [comment]
Closing because we have a [Quarkiverse](https://github.com/quarkiverse/quarkus-amazon-alexa) extension for this.
