### ISSUE TITLE
REST Client Reactive ARRAY_PAIRS query param style should not impact single values

### ISSUE THREAD

**Issue by michalszynkiewicz** [quarkusio/quarkus#24631]
### Description

From stackoverflow:
I have a service that accepts requests with the following query parameters:
```
limit=1
param[117]=3345
```
parameters `param[117]` are `List<String>`, and parameter limit is a `string`

The service expects to receive these parameters in the following form:

`.../sevice-name?param[117][]=2233&param[117][]=3344&param[117][]=5566&limit=1`

for this I enable the setting on the client in the quarkus options

```
quarkus.rest-client."sevice-name".query-param-style=ARRAY_PAIRS
```
and get a query string like this `limit[]=1`but expected `limit=1`:

`.../sevice-name?param[117][]=2233&param[117][]=3344&param[117][]=5566&limit[]=1`

how can *quarkus-rest-client-reactive-jackson* be configured to get the expected behavior?

### Implementation ideas

We need to either
- treat params mapped to single fields differently and send them as `<name>=<value>`, or
- let users choose if they want the current behavior or ^ with some config property

**Comment by michalszynkiewicz** [comment]
I see there's no easy way to differentiate collection and single value.
@phillip-kruger  I see you approved the MicroProfile REST Client PR - do you by any chance know more how is this supposed to work? ;)

**Comment by phillip-kruger** [comment]
I did ? No idea sorry. Do you have a link to the PR ?

**Comment by michalszynkiewicz** [comment]
https://github.com/eclipse/microprofile-rest-client/pull/276

**Comment by phillip-kruger** [comment]
Maybe @andymc12 can comment ?

**Comment by andymc12** [comment]
I think that this may be a bug.  The spec says that the query-param-style property is intended for use in query parameters that contain more than one value.  For the other cases (MULTI_PAIRS and COMMA_SEPARATED), the query parameter key is the same whether the request's query parameter has a single value or multiple values - but for ARRAY_PAIRS, it seems like the parameter key changes depending on how many values are sent (i.e. `some-service?param1=singleValue,param2[]=multiValueA,param2[]=multiValueB`).  

The MP Rest Client TCK does not properly test a "mixed" request (a request with a single-value param and a multi-value param), which seems like an oversight.  Thus an implementation could pass the TCK, but not necessarily comply with the wording in the spec.

In this particular case, since the multi-valued parameter is a `List<String>`, I think that the implementation (RESTEasy?) could probably detect a collection/array as the parameter type and add the brackets to the parameter name if more than one element is present in the collection.

HTH - Andy

**Comment by michalszynkiewicz** [comment]
To double check, if a query parameter is of type collection on the client interface, but it contains a single value, in your opinion Andy, we should keep the param as `param2=multiValueA`?

Thanks a lot!

**Comment by andymc12** [comment]
I think so, but I’m not 100% sure.
