### ISSUE TITLE
OIDC client: new token on forbidden

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#24677]
### Description

Would be nice if the OIDC client would support the following:

The OIDC client can be configured to perform a single retry on requests that return status code 401 (Forbidden). When the option flag: refreshTokenOnForbidden is set to true, then the client will perform a new token request retry the original request before passing the response to the user.

See https://vertx.io/docs/vertx-web-client/java/#_oauth2_security option refreshTokenOnForbidden

**Comment by sberyozkin** [comment]
@argenstijn Hi, a single optional retry can be of interest - but there is a danger of a loop when doing it with 401 - 401 can be returned not because the token has expired but if it does not pass some verification check (signature, issuer, audience, etc). So the client will get a new token - will get the same  401, and the loop starts.
Besides, I don't think it is even technically possible - the request can not be rewinded at the JAXRS client request filter level.

However, I believe we already a solution for this case: 

https://quarkus.io/guides/security-openid-connect-client#refresh-access-tokens
(`quarkus.oidc.refresh-token-time-skew`) - set it to say `10S` and you'll never get the nearly expired tokens being sent to the target endpoint.

I believe this issue should be closed.

Do you agree ?

Thanks

**Comment by sberyozkin** [comment]
Closing it because:
* OIDC client refreshes the tokens which it knows have expired before propagating them; and the tokens which will expire within the configured `quarkus.oidc-client.refresh-token-time-skew` period will also be refreshed before being propagated.
* Automatically refreshing a token on getting 401 is risky - in all but the expired token verification problems the error will not be seen by the caller and the loop can start - and as mentioned in the previous bullet the expired or nearly tokens can be correctly processed before the propagation
* A request can not be rewound at the client request filter level in any case

thanks

**Comment by argenstijn** [comment]
@[sberyozkin](https://github.com/sberyozkin)

Not totally agree. 

1. Loop is not dangerous as long as you retry only oonce. Like the solution of Vert.x: https://vertx.io/docs/vertx-web-client/java/#_oauth2_security option refreshTokenOnForbidden

2. The solution quarkus.oidc.refresh-token-time-skew will only make sure it will happen less but still can happen. 
For example, the token on the client could be valid but on the server side because of an upgrade, security measure,etc could already have been invalidated.

**Comment by argenstijn** [comment]
Ps. How can we invalidate the token once i receive a 401 (using reactive client)

**Comment by argenstijn** [comment]
@[sberyozkin](https://github.com/sberyozkin)

See my question above. 

And i think the most important thing, what happens if the server says, this token in invalid (because of upgrade of whatever) and the client still thinks the token is OK. ... then we need to wait until the token expires...

**Comment by argenstijn** [comment]
or better to create a new issue for this one?
