### ISSUE TITLE
Integrate the security provider for gRPC clients

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#24755]
### Description
This epic is about integrating the Quarkus security mechanism for the gRPC clients.

The overall idea is to integrate the authentication provider as it's done in the HTTP stack, but instead of using a request filter, use a gRPC interceptor. So, in the end, the code should contain a gRPC server and client interceptor. The required authentication data (token, credentials...) will be passed as headers.

**Comment by sberyozkin** [comment]
You will likely need a copy of `HttpAuthenticator` adapted for GRPC, where it will get the user credentials from the GRPC payload and pass it to `IdentityProviderMechanism`

**Comment by vsevel** [comment]
hello. any news on this?

**Comment by indiealexh** [comment]
> hello. any news on this? just to make sure are we talking about quarkus as being a grpc client? what about server side? does quarkus support already incoming grpc requests with oauth authentication?

I think its supports via an interceptor.

I'm going to be testing it this evening, I can report back after.

**Comment by michalvavrik** [comment]
@alesj @cescoffier In regards of gRPC server, I think using OIDC auth provider is already possible for bearer token authentication if:

- you send credentials metadata over secured TLS channel
- you provide `GrpcSecurityMechanism` that maps gRPC metadata to `AuthenticationRequest`. I take it there is no extension that does that because this is not standardized and each app use different metadata?
- there is a fact that `OidcIdentityProvider` is using `RoutingContext` to resolve tenant config context. 
  - I suppose relying on `RoutingContext` is not desirable even though gRPC is implemented as route handler when not started as a separate server? Not a rhetoric questions, this part is important, we shouldn't rely on the `RoutingContext`, right?
  - If `RoutingContext` is not desirable I think I've opened way to do this without it here #36631
 
I'd like to help and I'd suggest to start with providing OOTB solution for access token based authentication where users just select headers. But maybe it is not necessary? Depends on how you answer questions above.

> The overall idea is to integrate the authentication provider as it's done in the HTTP stack, but instead of using a request filter, use a gRPC interceptor

`io.quarkus.grpc.auth.GrpcSecurityInterceptor` together with RBAC annotations impl. as CDI interceptors seems like sufficient auth/z option, or would you like to provide some analogy to HTTP Security Policies? If so, can you provide some scope/details/ideas (or not :-) not necessary, we can iterate).

>  So, in the end, the code should contain a gRPC server and client interceptor. The required authentication data (token, credentials...) will be passed as headers.

This task has in title `gRPC clients` and I'd like to understand what is meant by this 

- do you mean token propagation for clients, what are concrete goals of this opened issue in regards to client? it could be more accessible for me if I had more specific tasks.
- or can is this be about enhancing identity providers to OIDC and keep relying in authZ on annotations?
- I'm trying to understand what would be advantage of providing some gRPC version of `HttpAuthenticator` with its version of `HttpAuthenticationMechanism`. Is there disadvantage of current implementation?



cc @sberyozkin (though I already suggested it to some time back).

**Comment by michalvavrik** [comment]
It has been about week, I'm probably proposing something that is not of big interested. Please let me know if you need any help with this task. Considering this is _kind/epic_, you can simply open smaller issue with good description that you assign to me. Thanks.

**Comment by cescoffier** [comment]
Looks reasonable. But yes, on the server side, we cannot use routing context. You should use the duplicated context (which actually should be the case almost everywhere).

For the client, we can use an interceptor which adds the right header.

**Comment by michalvavrik** [comment]
> Looks reasonable. But yes, on the server side, we cannot use routing context. You should use the duplicated context (which actually should be the case almost everywhere).
> 
> For the client, we can use an interceptor which adds the right header.

Cool, thanks!

**Comment by cescoffier** [comment]
Seems to have been fixed in https://github.com/quarkusio/quarkus/pull/37966
