### ISSUE TITLE
Kotlin BsonProperty Panache mapping

### ISSUE THREAD

**Issue by Dosexe** [quarkusio/quarkus#24874]
### Describe the bug

When using kotlin panache library `@BsonProperty` is not working as expected.
I have a complex object with nested fields and only fields that is named fully the same as in DB mapped properly.
```kotlin
@MongoEntity(collection = INTEGRATION_COLLECTION)
data class App(
    @BsonId
    var id: IntegrationKey,
    var appData: Integration
) : ReactivePanacheMongoEntityBase()

@MongoEntity
data class Integration(
    var id: String? = null,
    @BsonProperty("authed_at")
    var authedAt: Long? = null,
    var stats: Stats? = null,
    @BsonProperty("lang_stats")
    var langStats: Map<String, Int>? = null,
    var plan: Plan? = null,
    @BsonProperty("is_pro")
    var isPro: Boolean? = null,
    var token: String? = null
)

@MongoEntity
data class Stats(
    var detect: Long? = null,
    @BsonProperty("chars_in")
    var charsIn: Long? = null,
    @BsonProperty("chars_out")
    var charsOut: Long? = null
)

@MongoEntity
data class Plan(
    var id: String = "",
    var period: Period = Period()
)

@MongoEntity
data class Period(
    var start: Long = 0,
    var end: Long = 0
)
```

json inserted to MongoDb (5.0.6)
For access `ReactivePanacheMongoRepositoryBase` is used
```json
{
    "_id" : {
        "appType" : "support",
        "appId" : "123"
    },
    "appData" : {
        "name" : "John",
        "email" : "test@example.com",
        "authed_at" : 1649341731,
        "last_active_at" : 1649341731,
        "token" : "***",
        "stats" : {
            "detect" : 0,
            "chars_in" : 0,
            "chars_out" : 0
        },
        "langs_stats" : {
            "en" : 1,
            "de" : 2
        },
        "is_pro": true,
        "plan" : {
            "id" : "123",
            "period" : {
                "start" : 1649341731,
                "end" : 1654041599
            }
        }
    }
}
```

Fields like `appData`, `stats` and `token` are mapped properly, but all fields with `@BsonProperty` are not working. 
I have discovered that I can overcome this using  `@field:BsonProperty`, but it is still not working for several fields, for example `isPro` field.
If data classes are changed for classes and fields are moved to body annotations start working, despite of `isPro` field.
If I use `@set:BsonProperty + @get:BsonProperty`  on `isPro` it works.
All fields named  `id` are mapped only with  `@field:BsonProperty`.

### Expected behavior

All fields are mapped properly based on field name or `@BsonProperty ` value

### Actual behavior

Some fields are missing

### How to Reproduce?

gradle 
```
plugins {

    kotlin("jvm") version "1.6.20"
    kotlin("plugin.allopen") version "1.6.20"
    kotlin("plugin.noarg") version "1.6.20"
    id("io.quarkus")
}

dependencies {
    implementation(enforcedPlatform("$quarkusPlatformGroupId:$quarkusPlatformArtifactId:$quarkusPlatformVersion"))
    implementation("io.quarkus:quarkus-resteasy-reactive")
    implementation("io.quarkus:quarkus-resteasy-reactive-jackson")
    implementation("io.quarkus:quarkus-rest-client-reactive-jackson")
    implementation("io.quarkus:quarkus-micrometer-registry-prometheus")
    implementation("io.quarkus:quarkus-kotlin")
    implementation("io.quarkus:quarkus-smallrye-health")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
    implementation("io.quarkus:quarkus-arc")
    implementation("io.quarkus:quarkus-smallrye-openapi")
    implementation("io.quarkus:quarkus-config-yaml")
    implementation("io.quarkus:quarkus-mongodb-panache-kotlin")
    implementation("io.smallrye.reactive:mutiny-kotlin:$mutinyKotlinVersion")
    implementation("com.fasterxml.jackson.module:jackson-module-kotlin:$jacksonVersion")
}

noArg {
    annotation("io.quarkus.mongodb.panache.common.MongoEntity")
}
```

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.18363.2037]

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 21.3.0 (build 11.0.13+7-jvmci-21.3-b05)

### Quarkus version or git rev

2.7.5.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.1

**Comment by evanchooly** [comment]
This bug is older than I thought.  Apologies for not digging in sooner.  But here's what's going on.  Since you're annotating those constructor parameters with `@BsonProperty`, they end up in the bytecode on the parameters to the constructor.  So you have, in essence, annotated the constructor function parameters and not the fields.  The `PojoCodec` is not smart enough to know the difference and so doesn't find them.  If you target your annotation with either `@get` (to annotate the getter) or `@field` (to target the field), the annotations end up in a place where the `PojoCodec` can find them.  As this is a limitation of the Java driver itself, there's not much to be done from the quarkus side.

So the fix here is to target your annotations accordingly.  If you'd rather not do that for whatever reason, and you're not tied to the panache querying capabilities, you might be interested in `quarkus-morphia` which integrates morphia in to quarkus and should properly handle your data class case.  (Though I worry now there's a gap there, too, that i'll have to test.)  But updating your annotations is by far the simplest fix.

I'm going to close this as things "work" if not necessarily in the expected way.  If there further questions/concerns, please feel free to reopen this one or open a new issue.
