### ISSUE TITLE
SQL connections not being released back to the pool with hibernate reactive and Panache

### ISSUE THREAD

**Issue by benjes** [quarkusio/quarkus#25138]
### Describe the bug

A simple REST endpoint that returns an Entity which is loaded via Hibernate Panache (findById).
The REST point can only be called n-times with n being the 
quarkus.datasource.reactive.max-size

After that a Timeout Exception is thrown.

See https://stackoverflow.com/questions/71967584/running-out-of-sql-connections-with-quarkus-and-hibernate-reactive-panache and https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/No.20JPA.20entity.20found.20with.20Quarkus.20.3E.202.2E7.20works.20with.202.2E6 (2nd issue)

### Expected behavior

The SQL connection should be released back to the pool and it should be possible to call the REST endpoint indefinitely.

### Actual behavior

After n calls a Timeout Exception is thrown 

` 11:12:48:070 ERROR [org.hibernate.reactive.util.impl.CompletionStages:121] (147) HR000057: Failed to execute statement [$1select <ONE OF THE QUERIES HERE>]: $2could not load an entity: [com.mycode.SomeEntity#1]: java.util.concurrent.CompletionException: io.vertx.core.impl.NoStackTraceThrowable: Timeout
    at <16 internal lines>
io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$null$0(SqlConnectionPool.java:202) <4 internal lines>
    at io.vertx.sqlclient.impl.pool.SqlConnectionPool$1PoolRequest.lambda$onEnqueue$1(SqlConnectionPool.java:199) <15 internal lines>
Caused by: io.vertx.core.impl.NoStackTraceThrowable: Timeout
 `

### How to Reproduce?

Build attached quarkus app with Gradle and run with 
the following environment variables (change as needed)
HTTP_PORT=30008;
DB_PWD=root;
DB_URL=vertx-reactive:mysql://127.0.0.1:3306/ACME;
DB_USER=roo

Call Rest endpoint with GET localhost:30008/api/acme/test?id=1 repeatedly (check max-size in application.settings)

[quarkus-hibernate-reactive-problem.zip](https://github.com/quarkusio/quarkus/files/8554679/quarkus-hibernate-reactive-problem.zip)
t

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 21.4.0 Darwin Kernel Version 21.4.0: Mon Feb 21 20:34:37 PST 2022; root:xnu-8020.101.4~2/RELEASE_X86_64 x86_64

### Output of `java -version`

java version "11.0.11" 2021-04-20 LTS

### Quarkus version or git rev

2.8.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.1

**Comment by dgian** [comment]
#25110 could be broadly related/similar to this.

**Comment by benjes** [comment]
I've got some exceptions early one but I think I have resolved that differently now. Will try to remove the @Blocking to see what difference it makes.

**Comment by benjes** [comment]
Ok that was the actual problem it seems. Behind the Rest Point I had some CPU intensive calculations. Adding this @Blocking annotation made the Exception go away. It was only when I tried to run in native mode that I again got Blocking Exceptions and then hopefully correctly fixed that by using emitOn for the CPU intensive calculations.

But does that mean that whenever a DB query is done on a different thread that the connection is then not returned to the pool? So while having @Blocking on a Rest Endpoint might not be a valid scenario it might highlights potential problems?

**Comment by benjes** [comment]
I've just read this blog https://quarkus.io/blog/resteasy-reactive-smart-dispatch/ 
I remember seeing @Blocking on Rest Calls elsewhere. So IMHO it is easy to configure this wrong for someone new to Quarkus and Mutiny.

**Comment by DavideD** [comment]
The problem is that when using reactive, Quarkus needs to run operations in a different thread (`vertx-loop-thread`) .
Quarkus decides which approach to use based on the signature of the methods. In your example, the method returns a `Uni`, so, as a default, Quarkus will use a non-blocking approach.

In this case the default is correct because you are using reactive code and nothing should be blocked.
When using the `@Blocking` annotation, you are telling Quarkus that the code is not reactive and it can run in a thread that can be blocked.  I think this is what's causing the issue you are seeing. 

Reactive and non reactive code require different approaches underneath. `@Blocking` or `@NonBlocking` exist to provide some workaround when a user needs to override the behaviour but it's not going to work without having a good understanding of what's going on. 

> So IMHO it is easy to configure this wrong for someone new to Quarkus and Mutiny.

We hear you. We don't have a better solution at the moment. Luckily, this is an open source project and we are happy when people give us feedback opening issues or providing fixes. This includes suggesting changes to the documentation and guides to make them clearer.

I will consider this issue closed but feel free to comment on it if you need more help.
