### ISSUE TITLE
Kafka deserializer autodetection with multiple channels of same value class

### ISSUE THREAD

**Issue by ertanden** [quarkusio/quarkus#25185]
### Describe the bug

I have defined multiple `incoming` channels with `smallrye-kafka` connector, and saw the the `value.deserializer` autodetection actually works, however one of the channels remains without being assigned the `value.deserializer` and the application fails to start.

I know I can use a single channel for this, with multi topic subscriptions however I wanted to keep the consumer thread separate for the separate topics.

```
mp.messaging.incoming.channel-1.connector=smallrye-kafka
mp.messaging.incoming.channel-1.topic=topic-1

mp.messaging.incoming.channel-2.connector=smallrye-kafka
mp.messaging.incoming.channel-2.topic=topic-2
```

Then, when 

```
    @Incoming("channel-1")
    public Uni<Void> receiveChannel1(KafkaRecord<String, JsonNode> message) {
        return process(message);
    }

    @Incoming("channel-2")
    public Uni<Void> receiveChannel2(KafkaRecord<String, JsonNode> message) {
        return process(message);
    }
```

The application fails to start with message

```
SRMSG00230: Unable to create the publisher or subscriber during initialization: java.lang.IllegalArgumentException: The attribute `value.deserializer` on connector 'smallrye-kafka' (channel: channel-1) must be set
```

### Output of `java -version`

11

### Quarkus version or git rev

2.8.2.Final

**Comment by ozangunalp** [comment]
Thank you for the issue!

I am guessing you are using `com.fasterxml.jackson.databind.JsonNode` as payload type. 
I think what is happening is because there is no Serde found for `JsonNode` Quarkus is generating one using Jackson `ObjectMapperDeserializer`.
You should see a log saying `Generating Jackson deserializer...`.

If you are willing to use a generic Json type you can use `io.vertx.core.json.JsonObject` OOTB. 
This will detect the type and configure your application to use `JsonObjectDeserializer`. (Just beware that, that class will be replaced in a future release #22295)

That being said there is a bug in Jackson serde generation. If a serde is already generated it doesn't take it into account in configuration.

**Comment by ertanden** [comment]
Thanks for the reply. 

Yep, the payload type is `com.fasterxml.jackson.databind.JsonNode`. In fact the generation of a serializer seems to work when I combine the two Kafka topics into a single incoming channel, like the following;

```
mp.messaging.incoming.channel-combined.connector=smallrye-kafka
mp.messaging.incoming.channel-combined.topics=topic-1,topic-2
```

The problem is still when you separate the channels.

I see this log message in both cases

```
Generating Jackson deserializer for type com.fasterxml.jackson.databind.JsonNode
```
