### ISSUE TITLE
Detect and register event bus codec automatically

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#2529]
**Description**
Detect and register event bus codec automatically

**Implementation ideas**
We need to collect `@ConsumeEvent` method and check for received type:
* direct payload (so type T)
* Message<T>

Once the types are collected, a `GenericCodec` must be registered. It the `@ConsumeEvent` specified a specific behavior this one must be registered.  

The generic codec does the following:

* pass the received instance
* use `clone()` if available

At the same time, the `local` attribute of `ConsumeEvent` should be passed to `true` by default.

**Comment by Dufgui** [comment]
hello, I start to work on it. Could you explain what is expected for the GenericCodec ? especially for encodeToWire and decodeFromWire ?

**Comment by cescoffier** [comment]
Thanks for your help @Dufgui !

So, in the case of local, the `decodeFromWire` / `encodeToWire` should:

* if clonable -> return a clone of the object
* if not, return the direct reference

Otherwise, if not local, encode/decode it to JSON using JSON-B.

**Comment by Dufgui** [comment]
Thanks for your quick reply. but I think we don't talk about the same thing.
https://vertx.io/docs/apidocs/io/vertx/core/eventbus/MessageCodec.html
`decodeFromWire` / `encodeToWire ` read or write in a Buffer. So I cannot return a clone or the direct reference because I have no object and I must a create one.

The local aspect is in the `transform(S s)`. 

So, I propose:

- in the `transform ` :  to code the cloneable and direct reference management. I just call the clone by reflection and I put it accessible. Because by default it's protected.
- in the `decodeFromWire` / `encodeToWire ` : I use the `toJsonObject` of `Buffer` and `toBuffer` of `JsonObject`

Are you ok with this ?

**Comment by Dufgui** [comment]
@cescoffier hello, i put a commit. I don't know if it's follow your idea.
Please take a look, say me if it's ok. I can add maybe some tests no ?
