### ISSUE TITLE
OpenTelemetry Vertx issue - divided traces

### ISSUE THREAD

**Issue by mikipoldi** [quarkusio/quarkus#25336]
### Describe the bug

When using nested/parallel vertx calls with reactive quarkus, issue with OpenTelemetry occurs. Traces are divided instead of being in single trace and some http post spans are missing.

For parallel calls all of them are missing (if using parallel calls greater than 2)
For cascaded calls the dependent http posts spans are missing.

### Expected behavior

One single trace with http post calls included.

### Actual behavior

**Cascaded calls (two parallel calls and on result called third):**
all traces:
![bugged_all_spans](https://user-images.githubusercontent.com/10795311/166456047-162e0a6b-3923-457f-979c-2ab5ae2c939d.PNG)

detached trace:
![bugged_detached_trace](https://user-images.githubusercontent.com/10795311/166456064-a47d1d55-aa5c-4b83-9232-262ef81b043d.PNG)

main trace:
![bugged_main_trace](https://user-images.githubusercontent.com/10795311/166456065-7b060d9b-97ef-4d53-978a-0b72addd9f73.PNG)

**3 Parallel calls:**
all traces:
![image](https://user-images.githubusercontent.com/10795311/166456524-c8606c0a-32a8-4fac-a192-4271b9fff5c1.png)

first trace with http post
![image](https://user-images.githubusercontent.com/10795311/166456786-84ce55d2-fcc4-4ed8-8e45-edcda028531e.png)

other 2 traces (both same, uploading only one image)
![image](https://user-images.githubusercontent.com/10795311/166456889-83b6d5d2-e0c0-4d45-82f3-c5efdc4eca03.png)

### How to Reproduce?

1. Have standard jaeger all in one with collector listening on 14250
2. Download and run project from an attachment (can be simply runned from idea via quarkus plugin)
[quarkus-vertx-otel-bug-001.zip](https://github.com/quarkusio/quarkus/files/8610712/quarkus-vertx-otel-bug-001.zip)
3. Call get on localhost:8080/parallel or localhost:8080/cascaded
4. Observe the traces in jaeger ui 

### Output of `uname -a` or `ver`

Linux optimus-insurance-get-5b9fbc85c4-hdhhk 5.4.181-99.354.amzn2.x86_64 #1 SMP Wed Mar 2 18:50:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

graalvm-ce-java11-linux-amd64-20.3.0

### Quarkus version or git rev

2.8.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Runnable from intellij idea quarkus plugin simply

**Comment by radcortez** [comment]
I'll have a look.

**Comment by mikipoldi** [comment]
Hi, 
any news? 
Thanks a lot,
Michal

**Comment by radcortez** [comment]
The issue here is that the Vert.x client used in the middle of the service does not propagate the context. It needs to transform the context into HTTP headers so the service on the other hand can keep the context going. The RESTEasy Type safe client already does this. I believe I've also looked into the Vert.x client and couldn't find a way to automate it, unless if I provide the client, but let me have another look.

**Comment by radcortez** [comment]
Actually, the Vert.x client is already prepared to propagate the context as well. The issue is in another place. The client was reusing the context if one was already available, but we actually need to create a new one, or it will try to create parent / child relationships, but there are actually separate calls.

I'll push a fix soon.
