### ISSUE TITLE
OidcClientRequestReactiveFilter works with only one named oidc client 

### ISSUE THREAD

**Issue by Archana0510** [quarkusio/quarkus#25388]
### Describe the bug

OidcClientRequestReactiveFilter uses a default OidcClient by default. A named OidcClient can be selected with a quarkus.oidc-client-reactive-filter.client-name configuration property.
quarkus.oidc-client-reactive-filter.client-name = "named oidc client name>"

I can not define multiple named oidc client for OidcClientRequestReactiveFilter

So one oidc client runs with reactive filter and others run with blocking filter

### Expected behavior

there should be some option to use OidcClientRequestReactiveFilter for multiple oidc clients

### Actual behavior

OidcClientRequestReactiveFilter can be used only for one named oidc client with 
propery  **quarkus.oidc-client-reactive-filter.client-name**

**Comment by debu999** [comment]
Support for multi tenant reactive client filters. 
It will be good to have the support as 
`quarkus.oidc-client-reactive-filter.tenant1.register=true
quarkus.oidc-client-reactive-filter.tenant2.register=true
quarkus.oidc-client-reactive-filter.tenant3.register=true`
https://quarkus.io/guides/security-openid-connect-client#oidc-client-reactive-filter

**Comment by debu999** [comment]
Any guide on updating the reactive client filter will also do did not find anything specific in the guide to register oidcfitler in reactive mode.

**Comment by sberyozkin** [comment]
@Archana0510 @debu999 
A single filter can't handle multiple tenants, there is a 1 to 1 relationship between the filter and the tenant, so 
```
quarkus.oidc-client-reactive-filter.tenant1.register=true 
quarkus.oidc-client-reactive-filter.tenant2.register=true 
quarkus.oidc-client-reactive-filter.tenant3.register=true
```

unfortunately does not work.

What can work, in principle, is something like
```
@OidcClientReactiveFilter(name="tenant1")
MyRestClient1 client1;
@OidcClientReactiveFilter(name="tenant2")
MyRestClient1 client2;
```
where an instance of `OidcClientReactiveFilter` initialized with a specific tenant name. But such mechanism is not available for RestEasy Reactive client.

For now I recommend a simple workaround:
```
public class Tenant1OidcClientReactiveFilter extends OidcClientReactiveFilter {
    protected Optional<String> clientId() {
        return Optional.of("tenant1");
    }
}
```
etc

**Comment by debu999** [comment]
Thanks @sberyozkin will use the same and create filters and extend the oidcclientfilter. Thanks for the help as usual.

**Comment by michalvavrik** [comment]
Strictly speaking this issue as described in the description should be closed as it's already possible by https://github.com/quarkusio/quarkus/pull/29788, but @sberyozkin mentioned creating named client instance for each injection point. I agree it can be done in principle (e.g. we can transform `@OidcClientFilter("My-client")` into unique qualifier for each combination MP client <> named Oidc client), but I'm not sure this is needed.

- Only advantage over what we already provide with `@OidcClientFilter("My-client")` is that you can re-use one MP rest client with several Oidc clients
- We will need to do build time validation and document clearly order of precedence
- We will need to change `@OidcClientFilter` target as it can't be used on target (I mention it as personally I like target is TYPE because without studying docs I already know it don't need to be repeated on injection point, but that's just me)
- I think Sergey mentioned it as example, the issue description asks for what we already have

IMHO issue should be closed.

**Comment by debu999** [comment]
Yes we used the suggestion by @sberyozkin so it's not a blocker and issue was kept open only if a furyurr enhance is planned. May be a trivial jira can be opened for the change which should bot be a urgent priority. 

This will help others who want to go all reactive and need security injection in ractive fashion

**Comment by michalvavrik** [comment]
> Yes we used the suggestion by @sberyozkin so it's not a blocker and issue was kept open only if a future enhance is planned. May be a trivial jira can be opened for the change which should not be a urgent priority.
> 
> This will help others who want to go all reactive and need security injection in reactive fashion

Thanks, I was suggesting this https://quarkus.io/version/main/guides/security-openid-connect-client-reference#oidc-client-reactive-filter
```
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;
import io.quarkus.oidc.client.filter.OidcClientFilter;
import io.smallrye.mutiny.Uni;

@RegisterRestClient
@OidcClientFilter("jwt-secret")
@Path("/")
public interface ProtectedResourceService {

    @GET
    Uni<String> getUserName();
}
```

**Comment by michalvavrik** [comment]
I'll close this as completed via https://github.com/quarkusio/quarkus/pull/29788 for I didn't hear arguments against it, feel free to re-open the issue if you don't agree with my comments above.
