### ISSUE TITLE
Make Stork CDI-aware

### ISSUE THREAD

**Issue by knutwannheden** [quarkusio/quarkus#25422]
### Description

It would be nice if implementations for the `ServiceDiscovery` and `LoadBalancer` SPIs could be instantiated as CDI beans by Quarkus, so that custom implementations can transparently participate in the CDI dependency injection (e.g. have a REST client injected via `@RestClient`).

**Comment by manovotn** [comment]
I don't know much about Stork (well, nothing really :-D) but here are my 0.02$ from CDI perspective.

Technically, this is doable assuming the given service provide is only needed after CDI/ArC is started.
The service impl would need to either have a bean defining annotation or it'd need to be added programatically in which case there'd only be one impl allowed to avoid conflicts.

Furthermore, this could cause some funky behavior due to automatic removal of unused beans that Quarkus does. To avoid this, you could of course make such bean `@Unremovable` but it is an extra step.
Last but not least, such beans would then be publicly visible within the application (and from within dev UI) which I am not sure makes much sense for service implementations.

**Comment by mkouba** [comment]
Hm, I don't think it's a question of the Quarkus integration. I mean it seems that Stork is using the `ServiceLoader` mechanism to load all ``LoadBalancerLoader``s and ``ServiceDiscoveryLoader``s which are then used to build a map of type -> `LoadBalancerLoader` and type -> `ServiceDiscoveryLoader` respectively. 

So even if you provide a custom impl of `ServiceDiscovery` you'll need to implement a service provider for the given "type". And this provider can easily obtain the CDI `ServiceDiscovery` bean. But of course, as Matej mentioned above, Stork would have to be initialized after the CDI container starts.

In any case, @michalszynkiewicz will know better :-).

**Comment by michalszynkiewicz** [comment]
We control the moment of Stork initialization in Quarkus - it's done by a recorder. I'm guessing we can invoke it after the CDI container starts
Can we?

**Comment by geoand** [comment]
Although @mkouba will probably say otherwise :), I personally have always viewed CDI as an integration framework, so this sounds very reasonable to me

**Comment by cescoffier** [comment]
Added to the Stork roadmap.

**Comment by cescoffier** [comment]
It has been addressed in stork 2.0. Now you can either use a cdi bean or the spi.

**Comment by geoand** [comment]
Great!
