### ISSUE TITLE
Native test fails if configure different final name property

### ISSUE THREAD

**Issue by marcelomrwin** [quarkusio/quarkus#25477]
### Describe the bug

In case of using quarkus.package.output-name or quarkus.package.runner-suffix property the native test will fail.

### Expected behavior

Tests executed and passed

### Actual behavior

error=2, No such file or directory Caused by: java.io.IOException: Cannot run program

### How to Reproduce?

Just configure the properties  quarkus.package.output-name or quarkus.package.runner-suffix in application.properties or via -D param to run the test.

### Output of `uname -a` or `ver`

MacOs Darwin 21.4.0 arm64

### Output of `java -version`

OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)

### GraalVM version (if different from Java)

OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 11.0.15+10-jvmci-22.1-b06)

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4

**Comment by geoand** [comment]
Nice catch. 

This happens because the Maven failsafe plugin (which is responsible for running integration tests) has the following configuration:

```xml
                    <plugin>
                        <artifactId>maven-failsafe-plugin</artifactId>
                        <version>${surefire-plugin.version}</version>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>integration-test</goal>
                                    <goal>verify</goal>
                                </goals>
                                <configuration>
                                    <systemPropertyVariables>
                                        <native.image.path>${project.build.directory}/${project.build.finalName}-runner</native.image.path>
                                        <!-- Other properties omitted -->
                                    </systemPropertyVariables>
                                </configuration>
                            </execution>
                        </executions>
                    </plugin>
```

What is of interest in the previous snippet is the `native.image.path` system property, which as you see contains `-runner` as the suffix.

One way to specify a custom suffix would be to include:

```xml
<quarkus.package.runner-suffix>-custom<quarkus.package.runner-suffix>
```

in the Maven's `<properties>` section and then update ` <native.image.path>` to have`${project.build.directory}/${project.build.finalName}${quarkus.package.runner-suffix}` as its value.

If you want to a;so use `quarkus.package.output-name`, then you can do something like this:

```xml
<quarkus.package.output-name>out</quarkus.package.output-name>
<quarkus.package.runner-suffix>-run<quarkus.package.runner-suffix>
```

in the Maven's `<properties>` section and then update ` <native.image.path>` to have`${project.build.directory}/${quarkus.package.output-name}${quarkus.package.runner-suffix}` as its value.
