### ISSUE TITLE
In command mode, version provider doesn't support CDI

### ISSUE THREAD

**Issue by PierreBtz** [quarkusio/quarkus#25475]
### Describe the bug

In command mode, if providing a custom VersionProvider, nothing can be injected in the provider (eg `@Inject` or `@ConfigProperty`).

### Expected behavior

VersionProvider benefits from Quarkus CDI.

### Actual behavior

VersionProvider cannot use any injection.

### How to Reproduce?

Steps to reproduce:

1. Clone https://github.com/PierreBtz/picocli-version-provider-bug
2. Run `mvn quarkus:dev -Dquarkus.args="version"` and observe the failure:

```
java.lang.NoSuchMethodException: eu.pierrebeitz.provider.MyVersionProvider.<init>()
	at java.base/java.lang.Class.getConstructor0(Class.java:3349)
	at java.base/java.lang.Class.getDeclaredConstructor(Class.java:2553)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5514)
	at io.quarkus.picocli.runtime.PicocliBeansFactory.create(PicocliBeansFactory.java:16)
	at picocli.CommandLine$DefaultFactory.create(CommandLine.java:5541)
	at picocli.CommandLine$DefaultFactory.createVersionProvider(CommandLine.java:5529)
	at picocli.CommandLine$Model$CommandSpec.updateVersionProvider(CommandLine.java:7324)
	at picocli.CommandLine$Model$CommandSpec.updateCommandAttributes(CommandLine.java:7290)
	at picocli.CommandLine$Model$CommandReflection.extractCommandSpec(CommandLine.java:11496)
	at picocli.CommandLine$Model$CommandSpec.forAnnotatedObject(CommandLine.java:6236)
	at picocli.CommandLine.<init>(CommandLine.java:227)
	at picocli.CommandLine.<init>(CommandLine.java:221)
```

### Output of `uname -a` or `ver`

Darwin Pierres-MacBook-Pro-2.local 21.4.0 Darwin Kernel Version 21.4.0: Fri Mar 18 00:46:32 PDT 2022; root:xnu-8020.101.4~15/RELEASE_ARM64_T6000 arm64

### Output of `java -version`

openjdk version "11.0.13" 2021-10-19 LTS OpenJDK Runtime Environment Zulu11.52+13-CA (build 11.0.13+8-LTS) OpenJDK 64-Bit Server VM Zulu11.52+13-CA (build 11.0.13+8-LTS, mixed mode)

### Quarkus version or git rev

2.8.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537)

### Additional information

It seems that picocli delegates version provider creation to a factory that doesn't support it.

Note that it's related to this discussion https://github.com/remkop/picocli/issues/1673

**Comment by manovotn** [comment]
@PierreBtz normal scoped beans (app scoped, req scoped, session scoped mostly) always create a proxy object and require a no-args constructor for it. Furthermore, a class-based bean declaration need either no-arg constructor or one that has all parameters as injection points (CDI beans) so that CDI can automatically initialize the object. Your class doesn't meet either requirement and as such cannot be initialized.

I am not familiar with `picocli` but if you want to have the resulting class as a bean and need to retain current constructor, you could also declare a producer method for it.

**Comment by manovotn** [comment]
Oh, I didn't realize `VersionService` was a bean in your original case as well. That's interesting; I am not sure why it didn't work then, let me try to poke around it a little more.

> I understood that Quarkus CDI was simplifying things for us by handling the no-arg constructor itself as per https://quarkus.io/guides/cdi-reference#simplified-constructor-injection

You are correct, what I described was pure CDI specification behavior and Quarkus makes it simpler to use.

> One more note for somebody that would find this thread, I noticed it works only if the bean is declared @Unremovable (on my reproduction repository, the error was clear, but on my current project it wasn't).

Yes, any bean that is not "used" is automatically removed. The details of it can be seen [here](https://quarkus.io/guides/cdi-reference#remove_unused_beans) or there was even an [article](https://quarkus.io/blog/unused-beans/) on this by Martin.

**Comment by manovotn** [comment]
@PierreBtz ok, found it.

Your original scenario only needs to add `@Unremovable` to your `MyVersionProvider` class and it will work.

The reason is that without the annotation, the bean class will be dropped as unused and as such won't have the no-args constructor added. Following that, [`DefaultPicocliCommandLineFactory`](https://github.com/quarkusio/quarkus/blob/main/extensions/picocli/runtime/src/main/java/io/quarkus/picocli/runtime/DefaultPicocliCommandLineFactory.java) will fail to resolve the bean and will instead try manual object creation but will fail as well because that also requires no-args constructor. The code for that can be seen [here](https://github.com/quarkusio/quarkus/blob/main/extensions/picocli/runtime/src/main/java/io/quarkus/picocli/runtime/DefaultPicocliCommandLineFactory.java#L38-L41).

**Comment by PierreBtz** [comment]
Perfect! I think it makes things clear now. Somehow using `@Inject` annotation caused the same root issue (bean is removed) but the error message was more helpful in guiding me.

Thanks a lot for taking the time to dig into this :)

**Comment by manovotn** [comment]
> Somehow using @Inject annotation caused the same root issue (bean is removed)

If you inject your `MyVersionProvider` into another bean `Foo`, the error will disappear.
However, that `Foo` also has to be used/injected somewhere, the search for unused beans is recursive and deep and if `Foo` is unused, it will remove it and will therefore also remove `MyVersionProvider` as it has no other injection detected.
Hope it makes sense.

**Comment by PierreBtz** [comment]
Totally, thanks!
