### ISSUE TITLE
Invalid RabbitMQ message causes silent NACKing of valid messages

### ISSUE THREAD

**Issue by sandersteenhoudt** [quarkusio/quarkus#25863]
### Describe the bug

When the application receives a message that it cannot handle, e.g. because it has no content_type property set (leading to a byte array as payload on the receiving end), that message is correctly NACKed. However, valid messages appear to be automatically NACKed as well, without any noticeable error logging. I have no idea where exactly this occurs, though.
This was first discovered on 2.8 but can still be reproduced using the latest Quarkus version (2.9.2).

### Expected behavior

Invalid messages are simply NACKed without impacting anything else. Maybe they should not even be called by a handler that cannot handle them, although I'm not familiar enough with the inner workings to say anything sensible about that.

### Actual behavior

When the application receives a message it cannot handle (e.g. not a JSON message), it is NACKed (which is good), but subsequent valid messages appear to be automatically NACKed as well, without any noticeable error logging (which is bad).

### How to Reproduce?

I've made a quick reproducer: https://github.com/sandersteenhoudt/quarkus-reproducer-sr-rabbitmq
I've also added all the info related to the suspected bug to the README, I'll repeat them here if that makes things more helpful.

1. Start an instance of RabbitMQ with the web ui port exposed, or find a way to easily publish a message. A Docker Compose file has been added for this purpose. The RabbitMQ instance provided by Dev Services currently doesn't expose the web UI port.
2. Start the application, which will declare the required exchange and queue.
3. As a bonus, check the [application's health endpoint output](http://localhost:9090/q/health). It should be UP.
4. In the [rabbitMQ web ui](http://localhost:15762/), log in using the default credentials (`guest/guest`).
5. In the web ui, go to the [exchanges overview page](http://localhost:15672/#/exchanges/%2F/some-message-exchange)
   and publish a message with a property `content_type` set to `application/json` and a simple JSON payload, e.g. `{"message":"This works"}`
6. Check the logs for correct handling of the message. It should log the raw `IncomingRabbitMQMessage` being received and the payload being deserialized to a `SomeMessage` instance (see the [implementation] (src/main/java/be/steen/reproducer/quarkus/rabbitmq/SomeMessageListener.java) as to why).
7. Optionally check the application health again, which should still be UP.
8. In the RabbitMQ web ui, remove the `content_type` property and hit Publish again.
9. Check the application logs. There should be an exception and a log entry stating the message was NACKed.
10. Check the application health. It should now say DOWN, with a new "channel" with the message listener method as its name, and the exception as its value.
11. Repeat step 5 (by adding the `content_type` property back). Hit the button a few times for good measure.
12. Check the logs, they should not mention the new valid messages. (it's possible new error logs are being added due to the NACKed message being redelivered)
13. In the RabbitMQ web UI, check [the queue's overview page](http://localhost:15672/#/queues/%2F/some-queue). The number of NACKed messages is higher than one, which leads me to believe all subsequent messages are silently NACKed despite being valid (due to *something* being in an invalid state, maybe?).

### Output of `uname -a` or `ver`

Linux thinkpad 5.18.0-arch1-1 #1 SMP PREEMPT_DYNAMIC Tue, 24 May 2022 22:00:36 +0000 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment (build 17.0.3+7) OpenJDK 64-Bit Server VM (build 17.0.3+7, mixed mode)

### Quarkus version or git rev

2.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.4 (9b656c72d54e5bacbed989b64718c159fe39b537) Java version: 17.0.3, vendor: N/A, runtime: /usr/lib/jvm/java-17-openjdk Default locale: en_US, platform encoding: ANSI_X3.4-1968 OS name: "linux", version: "5.18.0-arch1-1", arch: "amd64", family: "unix"

### Additional information

This is mostly unrelated to the bug, but during development, I encountered an issue where consuming a payload directly (rather than the SmallRye Message, as described [here](https://smallrye.io/smallrye-reactive-messaging/3.17.0/concepts/model/#consuming-payloads)). I've only included this at all because if this is also unreported the reproducer of this bug can be reused for that with only a minor code change. Not sure if this (or this whole bug report) needs to be in the Quarkus repo or somewhere in SmallRye, so if anyone could direct me on what to do with this, that would be nice. More info on that in the listener implementation.

**Comment by kdubb** [comment]
@sandersteenhoudt I've been through your reproducer and I think it might actually be working "correctly" or "as designed" in this specific case.

FYI, I haven't reconciled the current behavior with the "Eclipse Microprofile Reactive Messaging" spec at this point but its behavior makes sense to me. 

## Manual Acknowledgement
First there is no "ack"ing or "nack"ing happening anywhere in your reproducer, not by you or by the SmallRye Reactive Messaging framework (aka SRRM). 

Since you have not enabled `auto-acknowledgement`, you, the message handler, must manually "ack" or "nack" the message and you are not doing this. In many ways this makes sense because you have expressly asked to handle acknowledgment yourself.

When SRRM receives an error that bubbles up, instead of making a decision on your behalf (to "ack" or "nack") it essentially shuts down the connector. Note that this specifically leaves the message in the queue and it will be reprocessed if that's what your topology dictates. This is *very* problematic for durable queues. If your environment detects the "down" health state and restarts your server, RabbitMQ will redeliver the same bad message and the process will repeat indefinitely.

What you are seeing in the UI is the "total" # of messages currently in the queue and the current # of "un-acked" messages (i.e. the number of messages sent to the server for processing but haven't been "ack"ed or "nack"ed); I cannot see anywhere that is shows the # of "nack"ed messages most likely because RabbitMQ views a "nack" as a special kind of "ack".

### Working Example

Change your handler to the following and you will see that in the UI the "total" and "unacked" numbers essentially always stay at zero.

```java
    return Uni.createFrom().item(incomingMessage)
        .log("Raw smallrye message")
        .onItem()
        .transformToUni(message-> {
            try {
                message.getPayload().mapTo(SomeMessage.class);
                return Uni.createFrom().completionStage(message.ack());
            } catch (Throwable x){
                return Uni.createFrom().completionStage(message.nack(x));
            }
        })
        .log("Deserialized json message")
        .onItem().ignore().andContinueWithNull();
```

### Enhance with "Auto-Nack on Failure"

It is conceivable that an option could be added to SRRM that essentially "nack"s all failing messages when using manual acknowledgement. That would essentially make it operate as you believe it should right now.

Again, I think this may be an enhancement, not an issue to fix.

## Auto-Acknowledgement
Where SRRM seems to fail is if `auto-acknowledgement` is enabled. In this case the message is considered handled by RabbitMQ to moment the server accepts the messages for processing. 

In this case, SRRM _should_ ignore the error and continue on processing messages. Currently it does not do this.

**Comment by sandersteenhoudt** [comment]
@kdubb You're absolutely right! This issue arose because I first tried to implement this functionality by simply consuming the payload directly instead of the Message envelope (and then forgetting the requirement of manual acknowledgement). I just needed the application to _ack_ at completion and _nack_ on failure, which seems to be the behaviour described in the [SRRM docs](https://smallrye.io/smallrye-reactive-messaging/3.17.0/concepts/model/#consuming-payloads). 
However, as briefly mentioned in the reproducer and the additional info section of this issue, that didn't work for me due to a ClassCastException being thrown. My guess is a missing converter that uses Jackson deserialization, but I'm not sure if that is something that I should implement myself or not. I know this is unrelated to this issue, which is why I'll close this as soon as I get an answer to this last question. What should I do with this? A (admittedly very brief) issue search revealed no related issues. I don't want to inundate you with issues that are actually expected behaviour, so on top of your head, does this sound like a bug to you or should I simply implement the required converter myself?

**Comment by kdubb** [comment]
For message conversion there is `io.smallrye.reactive.messaging.MessageConverter` functionality for converting incoming messages. Not that even when using this functionality you need to be wrapping the conversion in try/catch and manually "nack" or "ack" as you see fit.

**Comment by sandersteenhoudt** [comment]
Are you sure about that last part? The SRRM docs I linked to state:
> For example, you can consume a payload as follows:
```
@Incoming("my-channel")
public void consumePayload(Price payload) {
    // do something
}
```
> In this case, you don’t need to deal with the acknowledgement yourself. The framework acknowledges the incoming message (that wrapped the payload) once your method returns successfully.

Or would the message not be _nacked_ when the converter fails to convert the payload?

**Comment by kdubb** [comment]
I just perused the code a bit more. I do see the ack/nack calls being bade. I'd convert your reproducer and verify it's operating as described though.
