### ISSUE TITLE
Quartz Scheduler and Hibernative Reactive current operation requires a safe (isolated) Vert.x sub-context

### ISSUE THREAD

**Issue by jccarvalhosa** [quarkusio/quarkus#25886]
### Describe the bug

The following code fails since the upgrade from 2.6.3.Final to 2.7.0.Final
```
@Inject
Mutiny.SessionFactory sessionFactory;

private final AtomicInteger lastFruitId = new AtomicInteger();

@Scheduled(every = "1s")
public void fetchFruits() {
    sessionFactory.withStatelessSession(session -> session.createQuery(
                "select f from fruit f where f.id > " + lastFruitId.get(), Fruit.class).getResultList())
                        .subscribe().with(this::onFruitsCallback, this::onFruitsFailure);
}
```

This is the exception:

```
022-05-31 11:32:01,245 WARNING [com.pos.cor.Server] (vert.x-eventloop-thread-0) Fruits query failed with Multiple exceptions caught:
	[Exception 0] java.lang.IllegalStateException: The current operation requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such. You can still use Hibernate Reactive, you just need to avoid using the methods which implicitly require accessing the stateful context, such as MutinySessionFactory#withTransaction and #withSession.
	[Exception 1] java.lang.IllegalStateException: The current operation requires a safe (isolated) Vert.x sub-context, but the current context hasn't been flagged as such. You can still use Hibernate Reactive, you just need to avoid using the methods which implicitly require accessing the stateful context, such as MutinySessionFactory#withTransaction and #withSession.: io.smallrye.mutiny.CompositeException: Multiple exceptions caught:
...
```

### Output of `uname -a` or `ver`

Linux 5.4.0-107-generic #121-Ubuntu SMP x86_64 GNU/Linux

### Output of `java -version`

openjdk 11.0.11

### Quarkus version or git rev

2.9.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.1

**Comment by mkouba** [comment]
Yes, this is expected. A scheduled method is invoked on the main executor for the blocking tasks. However, hibernate reactive should only be used from the event loop. The fact that it somehow worked with a stateless session was probably an oversight. AFAIK, the check was introduced in 2.7 to avoid unexpected problems with hibernate reactive which relies on the "duplicated contexts" in Vertx 4; see also https://groups.google.com/g/quarkus-dev/c/lBmQkCi_VK0/m/_O9b9mUxBQAJ.

Since 2.9 you can [mark a scheduled method as non-blocking](https://quarkus.io/guides/scheduler-reference#non-blocking-methods). In older versions you'd have to `@Inject Vertx` and offload the execution manually, i.e. something along these lines: https://github.com/quarkusio/quarkus/blob/2.9.2.Final/extensions/scheduler/runtime/src/main/java/io/quarkus/scheduler/runtime/SimpleScheduler.java#L322-L329

**Comment by mkouba** [comment]
I'm going to close this issue. Feel free to reopen it if needed.

**Comment by mkouba** [comment]
> Thank you Martin!
>
> Any hints to run tests on vertx event loop as well?

@jccarvalhosa You can try to add the `io.quarkus:quarkus-test-vertx` as a test dependency and then annotate a test method with `@io.quarkus.test.vertx.RunOnVertxContext`.
