### ISSUE TITLE
Azure Function binding types

### ISSUE THREAD

**Issue by DominiqueClaes** [quarkusio/quarkus#25998]
I've recently found the following question: https://stackoverflow.com/questions/67883734/quarkus-app-as-azure-function-with-time-trigger
We would like to have support for the other binding types as well (events, queue, schedule, ...)

Is this already available or available in the near future? We would love to keep using Quarkus and not to switch to a different framework that does support these binding...

**Comment by geoand** [comment]
cc @loicmathieu

**Comment by loicmathieu** [comment]
As far as I know, Azure function binding only support HTTP functions.
We will need to create new extensions to support other kind of functions (including HTTP functions with the Azure API which are not supported neither).

cc @wburns

**Comment by DominiqueClaes** [comment]
Than maybe my topic is not well described (English is not my native language ;-)).
If you look at https://docs.microsoft.com/en-us/azure/azure-functions/functions-bindings-expressions-patterns than I should be able to add additional binding type to function.json and use these in Quarkus?

**Comment by patriot1burke** [comment]
There were not any good integration points or APIs with Azure Functions that would allow us to expand our Quarkus integration.  So, we only bridge to our HTTP APIs like JAX-RS.  Maybe the azure developers have improved things here, I don't know.

**Comment by Nithanim** [comment]
Since I switched my job and simultaneously from AWS to Azure, I would like to have a proper binding-support too. I sat down and made a proof-of-concept: https://github.com/Nithanim/quarkus-azure-generic-functions

Not ready for production because
- I have only used the http binding yet
- it is still very fresh and messy
- the source is currently a bit out-of-sync with the one at work
- I am new to Azure and missing experience for everything and building everything there from scratch
- there may be bugs


But since I depend on it at work I pretty much have to develop it further ;)

**Comment by loicmathieu** [comment]
@Nithanim this is interesting, you didn't take the same approach than in GCP or AWS functions where we don't generate a proxy but use our own function class that delegates to the developer's one. I assume that due to the usage of annotation to bind to a function (instead of an interface for GCP and AWS) you don't have choice here.

I think it's a good step and we should discuss it's integration inside the Quarkus core repo where the other function binding are, even if it only support HTTP functions for now, it's still an interesting improvement over the existing support.

@patriot1burke what do you think ?

**Comment by patriot1burke** [comment]
Proxy approach might work.  I'll take a look!

**Comment by Nithanim** [comment]
@loicmathieu I don't know anything about GCP but for AWS, there is just a single interface to implement. With Azure functions you can define any number of functions you want by just using annotations on any method you want. Therefore, I cannot just make one Quarkus entry point and then find the implementation of the user.

For basic functionality you "just" have to make sure that you have an entry point that matches the generated function definition in the `.json` which somehow ends up in the usercode with initialized CDI. I don't know how Azure functions work exactly yet and I just wanted a simple way for Quarkus to work.

Theoretically, you could insert the init-code directly in the user-class and then make sure to initialize the fields. (Pretty sure the user-class needs a no-args-constructor.) Since I feared this could interfere with debugging and had to deal with the fields manually, I simply chose to make my own entry point and delegate from there by initializing Quarkus and then fetching the already initialized user instance from there. Currently there is one generated for each user class but that does not matter - I just did it that way.

This is a rather simple solution but the current downside is the dependency of the modified azure-functions-maven-plugin. It has the translation of the annotations to json in there but it works on reflection which is totally useless to us. My approach was to rewrite that to use jandex but this is a rather large-scale rewrite for this "simple" usecase. I did not want to make the translation myself and drag the support for that along.

**Comment by loicmathieu** [comment]
@patriot1burke just contribute Azure function bindings in #30762 I think we can close this one now.
