### ISSUE TITLE
`quarkus.grpc.dev-mode.force-server-start=false` property is not mentioned in documentation

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#26423]
### Describe the bug

`quarkus.grpc.dev-mode.force-server-start=false` property is not mentioned in documentation

Relates to https://github.com/quarkusio/quarkus/discussions/26102

CC @michalszynkiewicz 

Not sure which guide is the best fit, https://quarkus.io/guides/grpc-service-consumption looks like a good candidate as it covers client-side primarily

**Comment by gsmet** [comment]
So the problem is that the server and client are all mixed up and it's hard to extract the documentation properly.

I wonder if we should have 2 separate extensions: one for the server and one for the client, similar to what was done for GraphQL.

In the meantime, I will shoe in the configuration properties.

@cescoffier @michalszynkiewicz @alesj WDYT?

**Comment by cescoffier** [comment]
Yeah, but there are a lot of dependencies between them. We can try to split, but I'm not sure of the result, especially about testing (you need to run fake implementations at the moment). 

With the new gRPC server coming, things will be a lot cleaner.

**Comment by gsmet** [comment]
OK, well, I will add some doc for now. PR created.

**Comment by michalszynkiewicz** [comment]
thanks @gsmet !
