### ISSUE TITLE
Quarkus SwaggerUI ignores http.root.path if quarkus.resteasy-reactive.path is set

### ISSUE THREAD

**Issue by Fernichter** [quarkusio/quarkus#26870]
### Describe the bug

Im using the following config:

```
quarkus.http.root-path=/test-service
quarkus.http.port=${PORT:8080}
quarkus.resteasy-reactive.path=rest

```
SwaggerUI converts this to the following URL in the "try-out" feature:

```
curl -X 'GET' \
  'http://localhost:8080/rest/test' \
  -H 'accept: application/json'

```
SwaggerUI seems to ignore the `http.root.path` set in the config.

When im using the `@ApplicationPath("/rest") ` annotation instead of `quarkus.resteasy-reactive.path`, everything works just fine. Is this intended or am I missing something?

Thanks

### Expected behavior

SwaggerUI should provide the following request-url:

```
curl -X 'GET' \
  'http://localhost:8080/test-service/rest/test' \
  -H 'accept: application/json'

```

### Actual behavior

SwaggerUI provides the following request-url:

```
curl -X 'GET' \
  'http://localhost:8080/rest/test' \
  -H 'accept: application/json'

```

### How to Reproduce?

Use the following config:

quarkus.http.root-path=/test-service
quarkus.http.port=${PORT:8080}
quarkus.resteasy-reactive.path=rest

### Quarkus version or git rev

 Quarkus 2.10.2.Final

**Comment by Fernichter** [comment]
Can anyone reproduce this bug?

**Comment by phillip-kruger** [comment]
I have not looked at this yet. If you create a small reproducer that makes it easier

**Comment by phillip-kruger** [comment]
@MikeEdgar ^^^

**Comment by MikeEdgar** [comment]
The issue is that for RESTEasy Classic the smallrye-openapi extension uses the RESTEasy extension's path that already includes the http.root-path, whereas for reactive it's using the raw configuration property. I'll put together a PR to address this.

https://github.com/quarkusio/quarkus/blob/d21383094cdc29d3d7370d6eb40fef923f2663be/extensions/smallrye-openapi/deployment/src/main/java/io/quarkus/smallrye/openapi/deployment/SmallRyeOpenApiProcessor.java#L869-L883
