### ISSUE TITLE
Qute parsing issue

### ISSUE THREAD

**Issue by kucharzyk** [quarkusio/quarkus#26975]
### Describe the bug

This is valid qute template with custom tag
```html
{#textInput field="username" label="Username"}
```
Same template with spaces around equal sign is not valid
```html
{#textInput field = "username" label = "Username"}
```

It is producing 3 really hard to understand errors
```
        Suppressed: io.quarkus.qute.TemplateException: SignIn/login.qute.html:7:6 - {field}: Only type-safe expressions are allowed in the checked template defined via: dev.kucharzyk.tardis.pages.SignIn$Templates.login(); an expression must be based on a checked template parameter [redirect], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
                at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:168)
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:195)
                ... 11 more
        Suppressed: io.quarkus.qute.TemplateException: SignIn/login.qute.html:7:6 - {=}: Only type-safe expressions are allowed in the checked template defined via: dev.kucharzyk.tardis.pages.SignIn$Templates.login(); an expression must be based on a checked template parameter [redirect], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
                at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:168)
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:195)
                ... 11 more
        Suppressed: io.quarkus.qute.TemplateException: SignIn/login.qute.html:7:6 - {label}: Only type-safe expressions are allowed in the checked template defined via: dev.kucharzyk.tardis.pages.SignIn$Templates.login(); an expression must be based on a checked template parameter [redirect], or bound via a param declaration, or the requirement must be relaxed via @CheckedTemplate(requireTypeSafeExpressions = false)
                at io.quarkus.qute.TemplateException$Builder.build(TemplateException.java:168)
                at io.quarkus.qute.deployment.QuteProcessor.processTemplateErrors(QuteProcessor.java:195)
                ... 11 more

```

It's very common to use expresions like this (custom tags or let blocks) and I think it should be improved.
By default IDEs like InteliJ while formatting code are adding spaces around equal sign in templates.

Could we improve parser to work with such syntax?

**Comment by mkouba** [comment]
Well, at the moment section parameters are whitespace-separated chunks where the equals sign is used to identify the optional name of a param.

I.e. for `{#textInput field="username" label="Username"}`  the `SectionHelperFactory` for `textInput` receives two params. The first has a name `field` and the value is `"username"`. The second has name `label` and value `"Username"`. For `{#textInput field = "username" label = "Username"}` however, 6 params are parsed: [`field`, `=`, `"username"`, `label`, `=`, `"Username"`]. Also round brackets can be used to group several chunks (such as `{#if (item.active || item.sold) && item.enabled}`).

The `SectionHelperFactory` is then allowed to interpret these params in any way it needs to. So for example the `#if` section has a complex logic to turn the list of params into a condition.

Now back to the problem. I do agree that the error message is confusing. And in this particular case the parser should be more lenient. We could probably treat the equals sign specially so that `field = "username"` is parsed as `field="username"`. It would not be backward compatible but it shouldn't be a problem in most cases.

> By default IDEs like InteliJ while formatting code are adding spaces around equal sign in templates.

That's unfortunate and I'm not sure whether it's actually reasonable.

**Comment by mkouba** [comment]
It's not about a "proper" parser. Those rules were intentional. OTH I agree that we should be more lenient in case of named params and [this PR](https://github.com/quarkusio/quarkus/pull/26993) should fix the problem.

**Comment by kucharzyk** [comment]
Great news. It was one of the biggest problems with Qute for me. Good job @mkouba
