### ISSUE TITLE
Start a WireMock Server in development mode

### ISSUE THREAD

**Issue by Spanjer1** [quarkusio/quarkus#27039]
### Description

Run Wiremock (https://wiremock.org/) together with your Quarkus application in development mode.
Separated from your application code and only build when a property is set. 

While Wiremock can be easily started in a separate process, it is nice to have it together in one project with one startup command.
 
Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Configuration suggestion

quarkus.wiremock.dev.enabled=true
quarkus.wiremock.dev.path=src/main/resources

### Additional context

Currently within our team we use Wiremock for our integration tests. During development we also run a standalone Wiremock process where we can develop against. It would be nicer to run Wiremock embedded when development mode is active. The  lifecycle will be synced and you would only have to run quarkus:dev to get everything you need. 

While we need Wiremock in development we do not want this to be active in prod. 

I already did a POC where I could successfully point to a folder with all the Wiremock mappings.
[wiremock-dev.zip](https://github.com/quarkusio/quarkus/files/9229544/wiremock-dev.zip)

If there is interest I can iterate further on this.

**Comment by geoand** [comment]
Hi,

This does sounds interesting to me. Can you explain the workflow you envision a little more?

Thanks

**Comment by Spanjer1** [comment]
We have an application that connects to multiple external services. 
At startup we fetch all kind of keys from external sources and cached them for later usage.
We also run schedules to refresh those keys. 

When we develop a new feature and we startup the application it does these http calls. 
So then Wiremock just gives the right responses to continue the development process. We also use Wiremock to give us
bad responses/timeouts for investigating different states the application can be in. 

We want to have a simple local setup that with one command all these dependencies just work out of the box. 

So previous setup is -> Run Wiremock seperatly and let Quarkus connect to that. 
But this requires an extra installation step and stop/starting of the Wiremock server at the right time.

So proposed workflow is -> Run quarkus:dev with property, at startup the Wiremock starts first and fetches its configuration from files. 
The logs are in the same stream and you are good to go. The nice thing is that it is just synced.

**Comment by geoand** [comment]
Thanks for the explanation. I personally think it makes sense.

> The logs are in the same stream

Which logs exactly are you referring to?

**Comment by Spanjer1** [comment]
Wiremock also produces logs, while not much. Mostly when there is problems with the configuration. 
When an url is not matched for example. This will then show up together with the Quarkus logging.

**Comment by geoand** [comment]
That's what I thought, just wanted to make sure I understood correctly, thanks.

**Comment by Spanjer1** [comment]
I guess it could be created as a in-process dev service.

Something like the H2DevService. 
https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/h2/src/main/java/io/quarkus/devservices/h2/deployment/H2DevServicesProcessor.java

What do you think?

**Comment by geoand** [comment]
Yes, that's most likely the way to go.

**Comment by holly-cummins** [comment]
This makes sense to me as well. In fact, it makes so much sense that I thought we already did it. :) 

Do we know how typical running Wiremock as a standalone/separate server is (rather than using the [JUnit extension](https://wiremock.org/docs/junit-jupiter/) to auto-start and stop it, or starting and stopping it inline in the test code? 

I feel like it's perhaps a minority case, and so I wonder if the configuration property names should make that clearer? My reading of the suggested properties is 'enable wiremock' ("yes please!") not 'enable separate wiremock'

```
quarkus.wiremock.dev.enabled=true
quarkus.wiremock.dev.path=src/main/resources
```
I don't have any bright ideas for an alternative, though. `quarkus.wiremock.standalone.enabled` isn't quite right if it's actually in-process. `quarkus.wiremock.separate.enabled` isn't clear without context. 

What behaviour would we expect if tests use the JUnit extension, and the `quarkus.wiremock.whatever.enabled` is set? I assume the natural behaviour would be that Wiremock starts a second server for the `@WiremockTest` tests, but we'd want to check that. Would there be a performance gain in manipulating the annotation so that instead of starting its own server, `@WiremockTest` would do an `WireMock.configureFor("wherever.quarkus.started.it", 8000);`? That wouldn't be any advantage for this case, where config files are being used instead of the static DSL, but would it help in others?

**Comment by geoand** [comment]
@holly-cummins the main advantage I see with this proposal is that Wiremock would be available in dev-mode as well as test mode.

**Comment by holly-cummins** [comment]
> @holly-cummins the main difference/advantage I see with this proposal is that Wiremock would be available in dev-mode as well as test mode.

Ahhh, got it, thank you! I sliced a bunch of starwberries into the compost bin this morning and put the stems on my cereal, and then I made coffee without putting any grounds into the machine. Clearly, it's one of those days.

Since tests would run in dev mode, I think my questions still make sense, with the caveat that if tests behaved differently in dev and test mode, that would be awful, so that puts a limit on how clever anything it could be. It perhaps adds some new ones about whether anyone would be surprised to set `quarkus.wiremock.dev.enabled` option and not have a server started in test mode (probably not, since their tests would be starting one?). Is there a risk that if people set that option, they'd forget to create a wiremock server in their tests and tests would pass in dev mode and fail in test mode?
I also wondered whether there should be any automagic configuration sharing between test and dev modes? That would be hard to do without scraping the tests to figure out what the configuration should be, even if the configuration was consistent across all tests (highly unlikely) and it's desirable to have the same configuration between tests and dev mode, which it probably doesn't.

**Comment by Spanjer1** [comment]
I am glad that there is interest in this. I am interesting to lead the development of this extension or making the MVP. 

As of the configuration options, what do you both think of:

//This can be optional, and use the port one as enabled/disabled
quarkus.wiremock.dev.enabled=true
quarkus.wiremock.test.enabled=true

//when it is the same it can be the same instance otherwise different instances.
quarkus.wiremock.dev.port=8089
quarkus.wiremock.test.port=8089

quarkus.wiremock.dev.rootDir=src/main/resources
quarkus.wiremock.test.rootDir=src/test/resources

Would it then be possible to inject that into a test class?

@InjectWireMock
 WireMock mockServer;
 
 Perhaps after every test you could reset it to the standard mappings. 
 
The Continuous testing (when you run quarkus:dev) are still run in Test mode. So they don't come into conflict as far as I can see.

**Comment by geoand** [comment]
> Clearly, it's one of those days.

:)

> Is there a risk that if people set that option, they'd forget to create a wiremock server in their tests and tests would pass in dev mode and fail in test mode?

If we follow the same approach we have followed for other dev-services, this won't be a problem. Things will work seamlessly and in dev and test modes.

> I also wondered whether there should be any automagic configuration sharing between test and dev modes

What do you have in mind here?

**Comment by geoand** [comment]
@Spanjer1 although we could likely do things like that, it's not exactly the patter we have followed for other dev-services.

More likely, things would look like:

```properties
%test.quarkus.wiremock.port=8089
%dev.quarkus.wiremock.port=8089
```

**Comment by stephan-strate** [comment]
Very interested in this feature! Any updates @Spanjer1?

**Comment by Spanjer1** [comment]
I have something basic that I can show coming week. I am currently relocating so it is a bit hectic here😀

**Comment by Spanjer1** [comment]
@geoand
@holly-cummins 

The basic version I have currently is found here: https://github.com/Spanjer1/wiremock-dev

What would I need to do to get it on-boarded to Quarkiverse? 
As it is my first time creating a Quarkus extension. 

I have read https://github.com/quarkiverse/quarkiverse/wiki#joining-quarkiverse

**Comment by geoand** [comment]
> What would I need to do to get it on-boarded to Quarkiverse?

I am sure @gastaldi will create the repository for you :)

**Comment by gastaldi** [comment]
Repository created in https://github.com/quarkiverse/quarkus-wiremock, please check https://github.com/quarkiverse/quarkiverse/wiki/Checklist#after-the-repository-is-created about the next steps.

Enjoy!
