### ISSUE TITLE
Jacoco coverage across jUnit and @QuarkusTest not working

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#27155]
### Describe the bug

Wen having plain jUnit tests and @QuarkusTests side by side, the jacoco coverage is missing the coverage from the jUnit test. This behaviour still exists after applying the configuration suggested by quarkus: https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest

### Expected behavior

The jacoco coverage report should respect the jUnit test and the @QarkusTest coverage

### Actual behavior

Only the @Quarkus coverage is included in the jacoco coverage report

### How to Reproduce?

Sample repository: https://github.com/HerrDerb/quarkus-jacoco-issue

1. Run `./mvnw clean install`
2. Open `/target/jacoco-report/org.acme/index.html`

**Comment by joggeli34** [comment]
Any news about this issue?

Is it recomendet to only use `@QuarkusTest` tests for beans and not normal unit tests if possible?

**Comment by darraghc345** [comment]
I was experiencing this issue.

Changing the jacoco-maven-plugin version to be the same as the jacoco version imported by quarkus, seems to have fixed it.

Unfortunately, it seems this has to be manually synced. Maybe it helps.

**Comment by felipemendes-maplink** [comment]
I've been facing the same problem about this topic in my project. I have the 0.8.7 jacoco version set in my pom, but the issue still happening.

**Comment by markuseckstein** [comment]
I'm experiencing the same issue as @HerrDerb . Unfortunately, the workaround proposed by @darraghc345 does not seem to help in my case.

**Comment by GChapel** [comment]
@HerrDerb I generated jacoco report based on your sample project, I got both coverage (junit + quarkus) : 

![image](https://user-images.githubusercontent.com/5603183/198900161-3ee7a681-7f56-4878-b54b-b9de1a62e040.png)

GreetingService = Quarkus
ByeService = jUnit

**Comment by HerrDerb** [comment]
I must have had some wierd configuration. In our new project it also does work. I'll close this issue. If it does not work, it's most probalby because of a bad configuration.

**Comment by mueihn** [comment]
I know that this issue is already closed. But I just experienced the exact same problem.

Quarkus 2.14.2, Jacoco 0.8.8.

None of the advice given here helped for me.

In the end, I found that, at the beginning of the integration tests, Quarkus threw away target/jacoco-quarkus.exec and recreated it from scratch. So, all the coverage from the unit tests was lost by design.

What helped for me was adding `quarkus.jacoco.reuse-data-file` to my application.yml and setting it to true (defaults to false).

I guess this hint should be added to the Quarkus documentation that most of the people relied on before coming here

**Comment by gitkeerthi** [comment]
Same issue. Using quarkus 2.16.

**Comment by Serkan80** [comment]
I've fixed this like this in my pom.xml

```xml
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>${versions.jacoco}</version>
                <executions>
                    <execution>
                        <id>default-prepare-agent</id>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                        <configuration>
                            <exclClassLoaders>*QuarkusClassLoader</exclClassLoaders>
                            <destFile>${project.build.directory}/jacoco-quarkus.exec</destFile>  ----> this is the fix
                            <append>true</append>
                        </configuration>
                    </execution>
                    <execution>
                        <id>generate-code-coverage-report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>

```

Really, strange that I had to change that line, since this pom.xml was a copy/paste from another project where the unit tests do get covered by Jacoco. And there the line was `${project.build.directory}/jacoco.exec`.

And btw, I'm using Quarkus 3.2.8.Final & jacoco 0.8.11.

**Comment by otavioprado** [comment]
> I've fixed it like this in my pom.xml
> 
> ```
>             <plugin>
>                 <groupId>org.jacoco</groupId>
>                 <artifactId>jacoco-maven-plugin</artifactId>
>                 <version>${versions.jacoco}</version>
>                 <executions>
>                     <execution>
>                         <id>default-prepare-agent</id>
>                         <goals>
>                             <goal>prepare-agent</goal>
>                         </goals>
>                         <configuration>
>                             <exclClassLoaders>*QuarkusClassLoader</exclClassLoaders>
>                             <destFile>${project.build.directory}/jacoco-quarkus.exec</destFile>  ----> this is the fix
>                             <append>true</append>
>                         </configuration>
>                     </execution>
>                     <execution>
>                         <id>generate-code-coverage-report</id>
>                         <phase>test</phase>
>                         <goals>
>                             <goal>report</goal>
>                         </goals>
>                     </execution>
>                 </executions>
>             </plugin>
> ```
> 
> Really, strange that I had to change that line, since this pom.xml was a copy/paste from another project where the unit tests do get covered by Jacoco. And there the line was `${project.build.directory}/jacoco.exec`.
> 
> And btw, I'm using Quarkus 3.2.8.Final & jacoco 0.8.11.

Didn't work here :(

**Comment by douglas444** [comment]
I'm experiencing the same issue in a specific application (while other applications work fine by simply following the tutorial: [Quarkus Tests with Coverage](https://quarkus.io/guides/tests-with-coverage#coverage-for-tests-not-using-quarkustest)).

For this problematic application, I found two workarounds:  
1. Set `quarkus.jacoco.reuse-data-file=true` in the `application.properties`.  
2. Move the `<quarkus.jacoco.reuse-data-file>true</quarkus.jacoco.reuse-data-file>` property from the `surefire` configuration to the `failsafe` configuration.

I have no idea why, in this particular project, `quarkus-jacoco` fails to read the property from `surefire` but successfully reads it from `failsafe` during the report generation. In other projects, keeping the property in the `surefire` plugin (as shown in the tutorial) works perfectly fine.

To investigate why the property in `surefire` isn't being applied, I printed the system properties in a test using `System.getProperties()`. Interestingly, `quarkus.jacoco.reuse-data-file` was present, so the issue seems to be with `quarkus-jacoco` not reading it properly and defaulting to `false`.

**Comment by Nikontem** [comment]
@douglas444 

For us this was caused because some of our @QuarkusTest tests were named with the "Test" suffix (e.g., IntegrationTest.java) while others used the "IT" suffix (e.g., CompleteOrderIT.java). Files with the "Test" suffix are run by Surefire, and files with the "IT" suffix are run by Failsafe. Since Surefire runs first and Failsafe runs after, the JaCoCo coverage from the Failsafe phase was overwriting the Surefire results. 

The fix was to ensure all @QuarkusTest classes use the same naming convention so they run in the same phase. Or use arkus.jacoco.reuse-data-file=true
