### ISSUE TITLE
Infinite iteration in LocalProject.loadRootModel

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#2719]
**Describe the bug**
When <relativePath> of <parent> is set to empty value, loadRootModel iterates indefinitely

**Expected behavior**
iteration should quit

**Actual behavior**
iteration continues forever

**To Reproduce**
1. set pom.xml to contain a parent similar to:
```xml
  <parent>
    <groupId>com.example.quarkus</groupId>
    <artifactId>parent</artifactId>
    <version>1.0</version>
    <relativePath></relativePath>
  </parent>
```

**Environment (please complete the following information):**
  - Quarkus version or git rev: 0.16.0

**Additional context**
 io.quarkus.bootstrap.resolver.maven.workspace.LocalProject
line 86:
            if(parent.getRelativePath() != null) {
should be 
            if(parent.getRelativePath() != null && !parent.getRelativePath().isEmpty) {

**Comment by rquinio** [comment]
I faced this problem as well: it looks like empty relativePath is actually a hack used by some projects (ex: https://www.robintegg.com/2019/01/20/why-does-spring-initializr-set-the-parent-pom-relativepath-to-empty/) to bypass default resolution - I also found https://stackoverflow.com/a/37068864/1234362 with more details on the resolution.

Since it doesn't stack-overflow, Quarkus command line just hangs forever and you have to debug to understand what's happening - not the best user experience. So I think it's worth handling this case.
