### ISSUE TITLE
Enhancements for test resources on tests annotated with `@QuarkusIntegrationTest`

### ISSUE THREAD

**Issue by ivansenic** [quarkusio/quarkus#27285]
### Description

I have two proposals for enhancements, with respect to the `@QuarkusTestResource` annotation when combined with the `@QuarkusIntegrationTest`.

**1. Don't include resources when running `@QuarkusTest` test classes**

Of course, I don't want integration tests to run in the same phase with the other (unit) tests. However, annotating `@QuarkusIntegrationTest` with the `@QuarkusTestResource`, will still consider this resource to be global and it will started for the tests that are not integration tests. I tried multiple things here, and the only thing that works for me know is to use a profile that disables global resources in all tests that are annotated with `@QuarkusTest`, but this is annoying and error prone for future.

The option `restrictToAnnotatedClass` does work, but if I have numerous integration tests having the same resource, the resource would be started and stopped over and over again. This makes CI way longer and is thus unacceptable.

**2. Disable resource on custom `-Dquarkus.http.test-host` value**

Once I want to run my `@QuarkusIntegrationTest`s against a running app, I most likely don't need the resource. I don't see any reason when resource should be started, if I am pointing to the running app.

**Comment by geoand** [comment]
Thanks for reporting!

`1` seems like a reasonable approach, however it could break existing code. FWIW, we made a bad decision from the beginning on how `@QuarkusTestResource` is applied and we have been paying the price ever since because there is too much code out there that depends on it.

For `2`, I don't see how `quarkus.http.test-host` is related to the test resources. Can you please elaborate?

Thanks

**Comment by geoand** [comment]
Closing for lack of feedback
