### ISSUE TITLE
Load a class with @ConfigMapping or @ConfigProperties annotations with a file other than application.properties.

### ISSUE THREAD

**Issue by rruffer** [quarkusio/quarkus#27293]
### Description

Hello guys.

In spring it is possible to load a class with data from a specific file. whether it is inside or outside the resource folder. it would be interesting to have this configuration in quarkus too. This would avoid polluting the application.properties

spring examples:

Config class:
![image](https://user-images.githubusercontent.com/11635050/184706738-794d93c1-6b97-4136-a1a0-a73f961cb723.png)

application.properties
![image](https://user-images.githubusercontent.com/11635050/184706935-c332d6d0-ef8d-4af1-8f10-ec3bc953dc62.png)

config file in classpath
![image](https://user-images.githubusercontent.com/11635050/184707413-575501d6-d557-46e6-9a1e-e56ad5cce0ef.png)

config external file
![image](https://user-images.githubusercontent.com/11635050/184707319-e1b6ecd4-7832-48ea-a943-c64d3621485c.png)

### Implementation ideas

The idea would be to create an attribute in the annotation pointing to the specific file.

Example:
@ConfigMapping(prefix = "config", file="file-watcher-config.yml")

**Comment by geoand** [comment]
Hi,

Does https://quarkus.io/guides/config-reference#application-properties-file not fit your needs?

**Comment by rruffer** [comment]
Hi @geoand 

It works, but it doesn't work. depending on the object or objects you want to build in the file, it gets huge. it would be nice to do this configuration in another file and be able to call it directly in the class annotation. That is, a file that represents exactly that class.

Can you do it in application.properties?
Yes, but it gets mixed up with the other settings.

Is it possible to do this with jackson and @Produces (Form I implanted)?
Yes, but if @ConfigMapping was born to build an object from a file. Nothing more fair for him to accept files other than the application.properties itself.

And that would help a lot in the migration from spring to quarkus.

**Comment by geoand** [comment]
Thanks for the explanation.

I'm personally +0 on this, but this is @radcortez's decision to make.

**Comment by radcortez** [comment]
This is possible if you use `quarkus.config.locations`: https://quarkus.io/guides/config-reference#quarkus-config-config_quarkus.config.locations.

You can add multiple paths for additional classpath resources or external files. You don't have the explicit mapping to a file in the annotation, but I think that is unnecessary. You can just split the files per prefix you use, with the added benefit that you can still override values using other sources.

Our Config is just a view of all available sources. I don't think it is a good idea to start offering subsets of that view, because it may lead to different configurations for the same properties, which will be confusing and inconsistent.
