### ISSUE TITLE
[quarkus-oidc] Wrong client id sent to introspection endpoint when introspection credentials are given

### ISSUE THREAD

**Issue by DCCSKrezovic** [quarkusio/quarkus#27442]
### Describe the bug

This has been mentioned by a colleague that's using the same OIDC provider as I am

When setting the form field "client_id" in the introspection call, it must match the introspection_client_id introduced in quarkus 2.12 (see pr https://github.com/quarkusio/quarkus/pull/26917#issuecomment-1222351950)

Otherwise, the following error is shown:

![image](https://user-images.githubusercontent.com/109545110/186160446-882c9d76-aca9-4c13-8a72-9641c2869cd7.png)

### Quarkus version or git rev

2.12.0.CR1

**Comment by sberyozkin** [comment]
@DCCSKrezovic I'm not sure about it. This rule that your provider is implementing does not look correct to me. The whole concept of using a custom authentication for the token introspection (avoiding the client id) is non standard, but if the client id is present then I see no problems with your provider ignoring this field in the introspection request since it has no impact on the actual introspection authentication. We can imagine that other users would expect that the client id is also provided as per the standard introspection request spec even if the configure a basic authentication.

Or drop the client id from the configuration completely - it is optional for the bearer token authentication.

**Comment by DCCSKrezovic** [comment]
HI @sberyozkin 

According to the spec, only the token and token_type_hint are required. Everything else is optional and OIDC provider specific. Can providing the client id be made into a turnable?

https://www.rfc-editor.org/rfc/rfc7662#page-4

**Comment by mqs24d** [comment]
@sberyozkin the oidc provider we are using defines two clients:
* one client which is for token/userinfo retrieval 
* and a second one just for the introspection (so basically the custom authentication is just a separate client-id/client-secret)
So when the introspection is done the oidc provider expects the client id of the introspection client. I also don't know why our provider is doing that.

**Comment by sberyozkin** [comment]
@DCCSKrezovic Hi, as far as the other optional parameters are concerned they are not really about the client authentication, but about some extra properties related to the actual introspection input. The client authentication implied there refers to the OIDC client.

>Can providing the client id be made into a turnable?

I guess so, I can just add one more property to the `IntrospectionCredentials` config group to skip it if required

**Comment by sberyozkin** [comment]
No problems, we'd like to support various OIDC provider setups, whenever possible

**Comment by DCCSKrezovic** [comment]
Thanks for quick fix!
