### ISSUE TITLE
Jakarta - EE 9 - Context propagation tests failing

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#27507]
We have several context propagation tests failing and I have no idea what's going on there:

`integration-tests/smallrye-context-propagation`

:heavy_multiplication_x: io.quarkus.context.test.SimpleContextPropagationTest.testTransactionContextPropagationSingle line 130

:heavy_multiplication_x: io.quarkus.context.test.SimpleContextPropagationTest.testTransactionContextPropagationPublisher line 139

:heavy_multiplication_x: io.quarkus.context.test.SimpleContextPropagationTest.testTransactionTCContextPropagation line 118

**Comment by manovotn** [comment]
@gsmet lame question but what was the easiest way to locally run these in the transformed version? Been a while since I played with it :)

**Comment by gsmet** [comment]
@manovotn so I'm creating the issues now but I will document things properly, present something on a Tuesday and send an email to the list :).

But in the meantime, if you're eager to have a look:
https://github.com/quarkusio/quarkus/tree/main/jakarta#build-locally

**Comment by manovotn** [comment]
Thanks I wanted to have a look on Mon and see if I can spot what's wrong with the failures

**Comment by manovotn** [comment]
I did some debugging and:

* `io.quarkus.context.test.SimpleContextPropagationTest.testTransactionTCContextPropagation`
  * This test actually passes when executed separately, and the failure seems to be a byproduct of the other two failures
*  `io.quarkus.context.test.SimpleContextPropagationTest.testTransactionContextPropagationSingle` 
  * In this case, context propagation never seems to even trigger; I had a breakpoint in `JTAContextProvider` and it never stopped there
  * This test uses an endpoint with `io.reactivex.Single` and I have no idea where we perform CP integration for these calls; however, in `main` I noticed this test makes use of `ContextPropagatorOnSingleAssemblyAction`
* `io.quarkus.context.test.SimpleContextPropagationTest.testTransactionContextPropagationPublisher`
  * Here I can see context capture happening several times and at first an active transaction is there and being captured (`ContextEndpoint#L318`)
  * However, at a later time, there is another context capture (after `ContextEndpoint#L321`) where the transaction is just `null`, so that inside `io,reactivex.Flowable#map()`, there is then no active transaction

I assume both failures are related in that in some part of the chain, the CP doesn't happen for types from `io.reactivex` but so far I don't understand why and I know even less about why would it happen only in jakarta-transformed branch...
Maybe @FroMage has some ideas?

**Comment by manovotn** [comment]
Debugging a little further, it seems that [`RxJava2ContextPropagator`](https://github.com/smallrye/smallrye-context-propagation/blob/main/propagators-rxjava2/src/main/java/io/smallrye/context/propagators/rxjava2/RxJava2ContextPropagator.java#L21-L38) never gets registered in the `jakarta-rewrite` branch which, I assume, could be the issue.

**Comment by gsmet** [comment]
Ah yeah, that could explain things. How is it registered? I might have broken things during the transformation.

**Comment by manovotn** [comment]
@gsmet so, the `RxJava2ContextPropagator` is a `ContextManagerExtension` and all of these extensions are discovered and registered via `SmallRyeContextPropagationProcessor`
The code can be seen here - https://github.com/quarkusio/quarkus/blob/main/extensions/smallrye-context-propagation/deployment/src/main/java/io/quarkus/smallrye/context/deployment/SmallRyeContextPropagationProcessor.java#L75-L85

**Comment by manovotn** [comment]
So it seems that this is an issue because `org.jboss.resteasy:resteasy-rxjava2:jar:6.0.3.Final:test` no longer declares a dependency on `io.smallrye:smallrye-context-propagation-propagators-rxjava2:jar`.

According to James, this is intentional. Therefore, we need to declare this dependency ourselves.
I can confirm that with it, all CP tests in this module pass:
```
[INFO] Results:
[INFO] 
[INFO] Tests run: 30, Failures: 0, Errors: 0, Skipped: 0
```
