### ISSUE TITLE
Reactive Postgres Client and Flyway/Postgres does not work together

### ISSUE THREAD

**Issue by markuslackner** [quarkusio/quarkus#2751]
**Describe the bug**
The use of the reactive postgres client and flyway or classical agroal datasource together in one project does not work. Its not possible to configure both features at the moment because reactive postgres client must be configured with `quarkus.datasource.url=vertx-reactive:postgresql://localhost:5432/quarkus_test`  and flyway with `quarkus.datasource.url=jdbc:postgresql://localhost:5432/quarkus_test` (both use the default datasource).

**Expected behavior**
The use of reactive postgres client and flyway/agroal in the same quarkus project should be possible

**Actual behavior**
Exception at startup: 
```
java.lang.RuntimeException: Failed to start quarkus
        at io.quarkus.runner.ApplicationImpl1.doStart(Unknown Source)
        at io.quarkus.runtime.Application.start(Application.java:100)
        at io.quarkus.runner.RuntimeRunner.run(RuntimeRunner.java:130)
        at io.quarkus.dev.DevModeMain.doStart(DevModeMain.java:173)
        at io.quarkus.dev.DevModeMain.main(DevModeMain.java:100)
Caused by: java.lang.NullPointerException
        at io.quarkus.agroal.runtime.DataSourceProducer_ProducerMethod_createDefaultDataSource_7c487e3ef869f878aa871e917c94f4d26d5d5c56_ClientProxy.getConnection(Unknown Source)
        at org.flywaydb.core.internal.jdbc.JdbcUtils.openConnection(JdbcUtils.java:56)
```

**To Reproduce**
1. Steps described in Reactive postgres guide (https://quarkus.io/guides/reactive-postgres-client}
2. add flyway and postgre-jdbc dependencies to pom
```
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-flyway</artifactId>
</dependency>
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-jdbc-postgresql</artifactId>
</dependency>
```

**Additional context**
I was able work around this behavior with following steps:

1. Changing config root to `reactive-datasource` in reactive postgres client ( https://github.com/quarkusio/quarkus/blob/master/extensions/reactive-pg-client/runtime/src/main/java/io/quarkus/reactive/pg/client/runtime/DataSourceConfig.java)

```
@ConfigRoot(name = "reactive-datasource", phase = ConfigPhase.RUN_TIME)
public class DataSourceConfig {
```

2. application.properties
```
quarkus.reactive-datasource.url=vertx-reactive:postgresql://localhost:5432/quarkus_test
quarkus.reactive-datasource.username=quarkus_test
quarkus.reactive-datasource.password=quarkus_test

quarkus.datasource.url=jdbc:postgresql://localhost:5432/quarkus_test
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=quarkus_test
quarkus.datasource.password=quarkus_test
```

**Comment by cescoffier** [comment]
@tsegismont Any idea?

**Comment by tsegismont** [comment]
@cescoffier we could add named datasources support in the reactive pg extension. Then users would be able to:
- stick to the default datasource for Flyway (and blocking db access with Hibernate/Panache
- use a different "named" datasource for Pg client

Config:

```properties
quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/quarkus_test
quarkus.datasource.url=jdbc:postgresql://localhost:5432/quarkus_test

```

Code:

```java
@Inject
@Named("reactive")
io.reactiverse.axle.pgclient.PgPool client;
```

**Comment by cescoffier** [comment]
Looks good (and close to reactive messaging). Just worried about `@Named`, every time I tried to use it @mkouba told me "NO :-)". Should we introduce a qualifier?

**Comment by cescoffier** [comment]
@markuslackner would the solution proposed by @tsegismont works for you?

**Comment by tsegismont** [comment]
Maybe we can reuse the [at]Datasource annotation from Agroal extension.

Le ven. 7 juin 2019 à 13:46, Clement Escoffier <notifications@github.com> a
écrit :

**Comment by markuslackner** [comment]
@cescoffier yes this solution would be great and working perfectly for me.

**Comment by tveon** [comment]
AFAIK it should be possible to reuse the standard data source for the reactive jdbc client from vert.x 3.7.1. 
https://vertx.io/docs/vertx-jdbc-client/java/
`JDBCClient.create(vertx, datasource);`

**Comment by tsegismont** [comment]
@tveon the Reactive Postgres client is not based on JDBC. It's a fully reactive Java implementation of the Postgres network protocol.

**Comment by tveon** [comment]
Oh, sorry - I didn't notice the difference between `vertx-jdbc-client` and `vertx-sql-client`. 😕 

I'm facing the same issue, so I was looking for possible solutions. To me, the solution proposed by @markuslackner seems cleaner than using a `@Named` bean - but obviously I'm pretty new to Quarkus and Vert.X... 😊 

BTW (unrelated) - are there clients for all the "callback, RxJava and Axle based APIs."?

**Comment by machi1990** [comment]
> @cescoffier we could add named datasources support in the reactive pg extension. Then users would be able to:
> 
> * stick to the default datasource for Flyway (and blocking db access with Hibernate/Panache
> * use a different "named" datasource for Pg client
> 
> Config:
> 
> ```ini
> quarkus.datasource.reactive.url=vertx-reactive:postgresql://localhost:5432/quarkus_test
> quarkus.datasource.url=jdbc:postgresql://localhost:5432/quarkus_test
> ```
> 

@cescoffier @tsegismont 
This could still cause an issue since `agroal` extension provide support of multiple `named` databasources e.g https://github.com/quarkusio/quarkus/blob/83303fd6f46405f98f225032a29fd945b62906fd/extensions/agroal/deployment/src/test/resources/application-multiple-datasources.properties#L1-L17

/cc @gsmet ping

**Comment by FroMage** [comment]
ATM Flyway is configured using the default datasource, by depending on agroal (and narayana but I'm not sure why), which means we can't use it for reactive-pg-client (and soon mysql).

Flyway depends on JDBC, and reactive-pg-client doesn't provide JDBC access, but there's no reason people couldn't use the JDBC driver for flyway without having to define an extra datasource just for flyway.

I think the following datasource settings should be sufficient:

```
# configure your datasource
quarkus.datasource.url: vertx-reactive:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver: org.postgresql.Driver
quarkus.datasource.username: sarah
quarkus.datasource.password: connor

# Flyway minimal config properties
quarkus.flyway.migrate-at-start=true
```

And the following imports would be required:

```xml
<dependency>
    <groupId>io.quarkus</groupId>
    <artifactId>quarkus-reactive-pg-client</artifactId>
</dependency>
    <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-jdbc-postgresql</artifactId>
    </dependency>
```

But we would not require agroal or narayana.

Otherwise ATM we can't use Flyway with reactive-pg-client because:

- Flyway depends on agroal owning the default datasource (#3449)
- Reactive-pg-client can only be used on the default datasource

We could fix both of these issues (the first one has a PR and we want to fix the second for sure), but we'd still be left with being forced to declare two datasources: one for flyway and one for reactive-pg-client, which is less than ideal.

Related: #2835

**Comment by schulzp** [comment]
Hi,

I followed @FroMage's idea and excluded `quarkus-agroal[-deployment]` from the POM and tweaked `FlywayProducer` to require `javax.sql.DataSource` instead of `io.agroal.api.AgroalDataSource`.  Then In my own project I created a producer for a `org.postgresql.ds.PGSimpleDataSource` et voilá: it works (see snippets below).

So here are a few things I noticed:
* `io.quarkus.agroal.runtime.AgroalRuntimeConfig` and `io.quarkus.reactive.pg.client.runtime.DataSourceConfig` share the same `@ConfigRoot(name = "datasource")`. As far as I understand the config mechanism it reads blocks, such as `quarkus.datasource`, only once, hence agroal conumes the values and pg never sees the values. At least that's what it looks like from debugging. Can anyone confirm that? If so I'd strongly argue for a separate  `@ConfigRoot(name = "reactive-datasource")` as suggested by @markuslackner.
* As pointed out by @FroMage `quarkus-flyway` depends on  agroal for no obvious reason. That would be solved by #3449 (PR: #3521)

*`pom.xml`*
```xml
<!-- [...] -->
  <dependencyManagement>
    <dependencies>
      <dependency>
        <groupId>io.quarkus</groupId>
        <artifactId>quarkus-flyway-deployment</artifactId>
        <exclusions>
          <exclusion>
            <groupId>io.quarkus</groupId>
            <artifactId>quarkus-agroal-deployment</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
    </dependencies>
  </dependencyManagement>
  <dependencies>
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-flyway</artifactId>
      <version>999-SNAPSHOT</version> <!-- to use javax.sql.DataSource  -->
      <exclusions>
        <exclusion>
          <groupId>io.quarkus</groupId>
          <artifactId>quarkus-agroal</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
  </dependencies>
<!-- [...] -->
```

*`application.properties`*
```properties
quarkus.datasource.url=vertx-reactive:postgresql://localhost:5432/postgres
quarkus.datasource.username=postgres
quarkus.datasource.password=secret

quarkus.flyway.migrate-at-start=true
```

*`PGSimpleDataSourceProducer.kt`*
```kotlin
package com.traum.aggregator

import io.quarkus.arc.AlternativePriority
import org.eclipse.microprofile.config.inject.ConfigProperty
import org.postgresql.ds.PGSimpleDataSource
import javax.enterprise.context.Dependent
import javax.enterprise.inject.Produces
import javax.inject.Inject

@Dependent
class PGSimpleDataSourceProducer {

    @Inject
    @ConfigProperty(name = "quarkus.datasource.url")
    lateinit var url: String

    @Inject
    @ConfigProperty(name = "quarkus.datasource.username")
    lateinit var username: String

    @Inject
    @ConfigProperty(name = "quarkus.datasource.password")
    lateinit var password: String

    @Produces
    @Dependent
    @AlternativePriority(1)
    fun create():PGSimpleDataSource {
        val dataSource = PGSimpleDataSource()
        dataSource.setURL(asJdbcUrl(url))
        dataSource.password = password
        dataSource.user = username
        return dataSource
    }

    private fun asJdbcUrl(url: String): String {
        return url.replace("vertx-reactive", "jdbc")
    }
}
```

**Comment by machi1990** [comment]
>  Can anyone confirm that? If so I'd strongly argue for a separate  `@ConfigRoot(name = "reactive-datasource")` as suggested by @markuslackner.

Is this envisageable post 1.0? May be for 2? @gsmet @FroMage @cescoffier WDYT?

**Comment by FroMage** [comment]
Well, the plan was to make all datasources use the same configuration prefix, and agroal would skip all datasources that are not JDBC. It's just that we didn't get there yet, but I don't think they should have separate config prefixes.

**Comment by tsegismont** [comment]
Agreed. The Pg/MySql extensions will be updated to support named
datasources (as Agroal extension does). Then you will be able to use the
default datasource for Hibernate / Flyway and create a separate datasource
for reactive data access.

**Comment by FroMage** [comment]
@tsegismont didn't we have an issue open to support those shared datasource declarations?

**Comment by FroMage** [comment]
I can't find it.

**Comment by Sanne** [comment]
@aguibert this one might be a good issue for you, want to try?

**Comment by tsegismont** [comment]
@FroMage I don't believe there is any issue filed other than this one

**Comment by FroMage** [comment]
We should open it, then. Do you remember the plan? We wanted to abstract the configuration of data sources to a neutral new module and agroal and the reactive sql clients would use it for the named (or default) datasources they supported, right?

**Comment by tsegismont** [comment]
@FroMage the plan was to

1/ support named datasources in the reactive database client extensions
2/ in a second phase, avoid duplication by abstracting shared config properties in a generic datasource extension

**Comment by aguibert** [comment]
perhaps we could part out the datasource configuration into separate host/port/dbname elements instead of URLs?

So this:
```
quarkus.datasource.url=jdbc:postgresql://localhost:5432/quarkus_test
```

would become:
```
quarkus.datasource.hostname=localhost
quarkus.datasource.port=5432
quarkus.datasource.dbname=quarkus_test
```

This would allow the extension to provide the appropriate protocol (i.e. `jdbc:` or `reactive-datasource:`). The tricky part would be getting the sub-protocol in there or properly building up extra properties that typically come in at the end of the URL. 

Another option could be configuring the transport protocol to a specific token or variable like so:
```
quarkus.datasource.url=${PROTOCOL}:postgresql://localhost:5432/quarkus_test
```

Here the user is acknowledging they are OK with Quarkus munging their URL property a bit, specifically replacing the `${PROTOCOL}` portion with `jdbc` for JDBC Datasources and `reactive-datasource` for the Vertx reactive client

**Comment by aguibert** [comment]
sounds like the general agreement is to have a separate `vertx-reactive` prefixed config source. If that's the case I can go ahead and implement/deliver that change

**Comment by JohT** [comment]
Would it be possible to let reactive-pg-client provide another way to attach it? Is it possible to write a sort of datasource decorator/interceptor/qualified producer? It would be less easier to use reactive-pg-client, but it would be more reusable (use/reuse relation in modularization)?

**Comment by FroMage** [comment]
Yeah, we want to keep the datasource in a single `url` property, and we want to declare jdbc and vertx-reactive datasources in the same list, so with the same `quarkus.datasource` config prefix. But for that we need to be able to extract the list of datasources conf away from agroal into a new common module that agroal and vertx-sql-clients would depend on.

**Comment by Sanne** [comment]
Is it really a good idea to want to reuse the same `quarkus.datasource` prefix?  I'm not sold about that.

I understand that conceptually they are very close, but `Datasource` is also a specific standard Java interface which people can inject by type (interface) and name - it wouldn't work for the reactive one as it's not the same contract, and hopefully their type shouldn't be named `Datasource` as well as we don't want types to be differentiated just by package.

**Comment by Sanne** [comment]
Also, I don't think you can just steal the "quarkus.datasource` prefix and move its management responsibility into a new extension. What would you do with all Agroal specific configuration properties?

 - https://quarkus.io/guides/datasource#configuring-the-datasource

I guess many of these could be shared, but requiring the reactive pools to have all of these (and vice-versa) doesn't seem sensible design.

One thing that I'd really like is for the difference reactive / non reactive to be driven by the consumer of the component: automatically initialize the pool of the right type depending on reactive capabilities of who's using it. That would be great, and possibly one reason to only expose the minimal subset of configuration properties - but I'm afraid that's not really possible without breaking changes so I'd suggest hold onto that idea for 2.0.

**Comment by FroMage** [comment]
Well, from a clueless user's POV, both are a source of data, and they even point to the same damn DB, just with a non-JDBC driver, which is why it's a bit hard to convince me they should be separated. The other concern about config is technical. Hopefully it doesn't get in the way of design decisions, unless it's a blocker, but I'm not sure at this point.

**Comment by tsegismont** [comment]
We had the same conversation months ago about whether or not to share the
datasource url property as well as a few other simple common props (eg
user, password).

Yes there are standard datasource properties that are not relevant to the
reactive one, and vice-versa.
But the idea was to move shared properties in a base module (not an
extension per se) and then let each module extend them with its own
properties.

I agree with Steph. Unless implementing this is impossible technically
speaking (I can't see why but you never know) there is nothing new to
justify reverting the decision.

**Comment by Sanne** [comment]
I remember we had some similar discussion, but I don't remember agreeing on this :) Happy to re-think though.

Do you happen to have a link? Can't find it. To comment on the above suggestions: reusing the Datasource annotation would be fine I think as it would be applied on a different _type_. typesafety helps there, but not so much with validation of configuration properties.

For context, I think we all agree that we want to improve usability here. I'm just skeptical as I think it's going to actually cause more usability pain: if we want this to be kinda "magic" then we need to have really good validation, exemplary warnings and think about how we plan to resolve ambiuities carefully.

What will happen if you try to consume the same "datasource" from both a reactive and a non-reactive component? Please specify such cases in a proposal, as people will try that, especially if they mix the instructions from different guides and try to re-use the existing "datasource" sections which happen to look exactly the same in different guides.

If they LOOK the same, I want them to BE the same for all practical purposes.

**Comment by tsegismont** [comment]
I found this https://github.com/quarkusio/quarkus/pull/2039#issuecomment-487906328

But there was also a thread on quarkus-dev

**Comment by FroMage** [comment]
> What will happen if you try to consume the same "datasource" from both a reactive and a non-reactive component? 

You should get an error, because they have different drivers.

**Comment by aguibert** [comment]
Perhaps we could do separate config roots for Vertx-sql-client connections and traditional JDBC Data sources?

Looking at the [Agroal configuration reference](https://quarkus.io/guides/datasource#configuration-reference), there is very little overlap between JDBC DataSource properties and Vertx-sql-client properties. Basically the only thing that a user would potentially be able to reuse is the username/password field, and fragments of the URL (e.g. Host and Port).

If a user wanted to configure for this scenario (Flyway w/ JDBC and Vertx-sql-client elsewhere) I propose the following:
```
# JDBC/Agroal DataSource config
quarkus.datasource.url=vertx-reactive:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=sarah
quarkus.datasource.password=connor

# Vertx SQL Client config
quarkus.reactive-mysql-client.url=vertx-reactive:postgresql://localhost:5432/mydatabase
quarkus.reactive-mysql-client.username=sarah
quarkus.reactive-mysql-client.password=connor
```

While it is tempting to try and consolidate common configuration (url/user/pass) IMO we should avoid this because at the API level level JDBC and Vertx-sql-client are completely different, and when you look beyond the basic url/user/pass configuration settings there isn't any overlap.

As a side note, it might be good to support variables in application.properties so similar values can be reused. For example:
```
my.db.user=sarah
quarkus.datasource.username=${my.db.user}
quarkus.reactive-mysql-client.username=${my.db.user}
```

**Comment by aguibert** [comment]
Also, while we are reworking Vertx-sql-client config, I think it would be better to use a config root that aligns better with the rest of Vertx config (`quarkus.vertx.*`), so instead of properties like:
```
quarkus.datasource.url
quarkus.datasource.username
quarkus.datasource.password
quarkus.reactive-mysql-client.charset
quarkus.reactive-mysql-client.collation
```

We could have config like:
```
# Common Vertx SQL Client config
quarkus.vertx.sql-client.url
quarkus.vertx.sql-client.user
quarkus.vertx.sql-client.password
# DB-specific config (MySQL)
quarkus.vertx.sql-client.mysql.charset
quarkus.vertx.sql-client.mysql.collation
```

**Comment by FroMage** [comment]
> While it is tempting to try and consolidate common configuration (url/user/pass) IMO we should avoid this because at the API level level JDBC and Vertx-sql-client are completely different, and when you look beyond the basic url/user/pass configuration settings there isn't any overlap.

Well, it's just that most users will only set url/user/pass and the rest that doesn't overlap is rarely used. I really feel like the sql-client drivers are just another type of drivers and we should have a single entry point to defining data sources, regardless of their drivers (jdbc or sql-client or others in the future).

**Comment by tsegismont** [comment]
>Basically the only thing that a user would potentially be able to reuse is the username/password field, and fragments of the URL (e.g. Host and Port).

Pool size, url (even if the format is different), username and password are the current shared properties.

We could (and should) also support credentials-provider, health and metrics in the extension, I think.

Other props like acquisition timeout, max lifetime, background validation, ...etc are not supported in the SQL clients yet, but they can be added if there is interest from users.

So, from my perspective, Agroal and Reactive SQL clients configs do share a lot of traits.

Let me reiterate that, for the purpose of the issue, it's not important if we share code between Agroal and SQL clients config classes yet. We just need SQL client extensions to support named datasources so that Flyway can be configured with the default datasource.

>As a side note, it might be good to support variables in application.properties so similar values can be reused.

Sounds like a good idea to me but, indeed, it's out of the scope of this issue.

**Comment by dmlloyd** [comment]
> As a side note, it might be good to support variables in application.properties so similar values can be reused. For example:
> 
> ```
> my.db.user=sarah
> quarkus.datasource.username=${my.db.user}
> quarkus.reactive-mysql-client.username=${my.db.user}
> ```

You can already do that!

**Comment by rsvoboda** [comment]
Can somebody please summarize current status and future plans with this (long) issue?

I tried vertx-quickstart and added quarkus-flyway + quarkus-jdbc-postgresql.

I received following error: Caused by: java.lang.IllegalArgumentException: Multiple matching properties for name "datasource.url" property was matched by both public java.util.Optional io.quarkus.agroal.runtime.DataSourceRuntimeConfig.url and public java.util.Optional io.quarkus.reactive.pg.client.runtime.DataSourceConfig.url. This is likely because you have an incompatible combination of extensions that both define the same properties (e.g. including both reactive and blocking database extensions)

**Comment by aguibert** [comment]
hi @rsvoboda, discussion on this topic has primarily moved to the mailing list here:
https://groups.google.com/forum/#!topic/quarkus-dev/3r0lquVsUsc

I believe this proposal by @dmlloyd is the current best option, but we don't have consensus on it:
https://groups.google.com/d/msg/quarkus-dev/3r0lquVsUsc/xkqiIA0aAwAJ

**Comment by rsvoboda** [comment]
@aguibert thanks for the update

**Comment by stuartwdouglas** [comment]
@gsmet can this be resolved now?

**Comment by gsmet** [comment]
Yes it can be closed. The new datasource config solved the issue.

**Comment by wfrank2509** [comment]
Hi. I understood that right now in quarkus 1.12.1 there is no solution to have reactive database and flyway, right?

**Comment by tsegismont** [comment]
Hi @wfrank2509 , with Quarkus 1.12.1 you should be able to use both Flyway and Reactive SQL client extensions in the same project.
