### ISSUE TITLE
Support annotation @PostConstruct (and similar) for reactive code

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#27591]
### Description

When writing reactive code, it's not possible to use `@PostConstruct` correctly:
```java
    @PostConstruct
    public Uni<Void> init() {
       return doSomething();
    }
```

This doesn't work and if users want to call a reactive method and be sure that it's executed before returning,
they have to block and wait:
```java
    @PostConstruct
    public void init() {
       doSomenthing().await().indefinitely();
    }
```

There are [some implementation details](https://github.com/quarkusio/quarkus/pull/26551#issuecomment-1231334195) that make this issue hard to solve:
> `@PostConstruct` callbacks are invoked during bean creation and the CDI API for bean construction is not async and therefore it does not help much. In other words, we can't properly support @PostConstruct Uni<Void> init() until we have an async bean construction API.

Note that returning a `Uni` is not the only solution and we could accept a parameter for synchronization. For example:
```java
    @PostConstruct
    public void init(CompletableFuture<Object> future) {
       doSomenthing()
           .subscribe().with( future::complete, future::completeExceptionally );
    }
```

Although we don't use this approach in other places.

Other resources:
* [The StackOveflow question of the user asking about it](https://stackoverflow.com/questions/73000578/using-transaction-in-postconstruct)
* [The previous PR where we briefly discuss this](https://github.com/quarkusio/quarkus/pull/26551#issuecomment-1231308629)

**Comment by mkouba** [comment]
We'll need an asynchronous version of `javax.enterprise.context.spi.Contextual` and all other connected parts of the API.

CC @manovotn @Ladicek

**Comment by Ladicek** [comment]
I'm struggling to imagine how invasive this would be. Say I have a JAX-RS resource that injects a request-scoped bean with async `@PostConstruct` and exposes an async resource method, something like:

```java
@Path("/")
public class HelloResource {
    @Inject
    HelloService service;

    @GET
    public Uni<String> get() {
        return service.hello();
    }
}

@RequestScoped
public class HelloService {
    @PostConstruct
    Uni<Void> init() { ... }

    public Uni<String> hello() { ... }
}
```

How would this work?

It's the JAX-RS implementation (RESTEasy Reactive in our case) who subscribes to the `Uni` returned by `HelloResource.hello()`. To execute that method, we have to instantiate `HelloResource`, which is a singleton and has a client proxy for `HelloService`, so that's fine. To be able to execute `service.hello()`, we have to instantiate `HelloService`, which has an async post-construct method, and then forward the invocation to this instance.

We can easily call that async post-construct method, but to be able to store the instance in the request context and let the previously-mentioned invocation to proceed, we'd have to wait on the returned `Uni` for completion, thereby block.

Which means to me that the code above couldn't possibly work in a truly non-blocking manner ("reactive all the way down").

We could possibly allow injecting a `Uni<HelloService>`. Say we do:

```java
@Path("/")
public class HelloResource {
    @Inject
    Uni<HelloService> service;

    @GET
    public Uni<String> get() {
        return service.flatMap(it -> it.hello());
    }
}

@RequestScoped
public class HelloService {
    @PostConstruct
    Uni<Void> init() { ... }

    public Uni<String> hello() { ... }
}
```

So here, we inject `Uni<HelloService>`, even though there's no bean of such type. We would probably have to special case `Uni` injection, or use an extra annotation (e.g. `@Inject @Async`, similarly to what we do with `@Inject @All List<...>`).

Say we do. The `Uni` we inject would probably play the role of a client proxy here. On the first invocation, it would trigger instance creation, subscribing to the `Uni` that the CDI container would internally have to return, and all the other invocations would use the same instance. I vaguely recall we had to do the same in the Quarkus Cache extension and in SmallRye Stork (and probably on a bunch of other places I'm not aware of), so it must be doable.

I'm not sure if this could interop with the traditional synchronous CDI or not. In fact, my head is close to explosion even after writing this short comment...

**Comment by mkouba** [comment]
> I'm struggling to imagine how invasive this would be

Very invasive!

> How would this work?

The regular `@Inject` would need to remain blocking/sync.

> or use an extra annotation (e.g. @Inject @Async, similarly to what we do with @Inject @All List<...>).
 
Yes, I think that we'll need a special annotation.

> On the first invocation, it would trigger instance creation, subscribing to the Uni that the CDI container would internally have to return, and all the other invocations would use the same instance.

Yep, something like a "memoized Uni", i.e. `Uni.memoize().indefinitely()`.

**Comment by DavideD** [comment]
What I get from all this is that this issue is complex and it might not be worthy to spend time on it.

I guess my main issue is that, in general,  it's hard to figure out which annotations accept unis and which don't.

In this case we are specifying the order of the operations, it seems sensible to think that it would work (as a user that's not aware of what's happening under the hood).
