### ISSUE TITLE
OIDC Remote Intropsection should work with discovery-enable set to true

### ISSUE THREAD

**Issue by jayfray12** [quarkusio/quarkus#27637]
### Description

Based on the docs [here](https://quarkus.io/guides/security-openid-connect#token-verification-introspection) you must turn off `quarkus.oidc.discovery-enabled` in order for remote introspection to work.  If you turn this off then you must set the `introspection-ath` and the other paths as well to known defaults like `/protocol/openid-connect/token/introspect`.  This doesn't make any sense.

It seems as though with `discovery-enabled` set to true only local introspection occurs.  Meaning it will check the expiration of the token but not if the token is still `active` by calling the introspection path.  We should be able to do both.  Perhaps by adding another parameter.  Something like `remote-introspection-enabled` that way you could have `discovery-enabled` set to true to pull in the paths from the oidc provider and if `remote-introspection-enabled` is true it would validate the token by calling the introspection path.

**Comment by sberyozkin** [comment]
@jayfray12 It works with the discovery enabled, that doc section is about enabling the introspection only by effectively blocking the acquisition of the metadata containing the info such as the jwks_endpoint - because its availability will allow to fetch the verification keys and the default way of verifying things will work (use the keys and only try the remote introspection if no local key is available even if the JWK set has been refreshed).

What is your requirement ? Do the introspection only even if the JWK keys are available ? If yes the disabling the discovery and configuring the introspection path only will do it - or if the discovery doc returns the introspection endpoint url only then nothing has to be done. If the introspection has to be tried only if no local verification is possible then nothing has to be done. 

Does it clarify it ?

**Comment by jayfray12** [comment]
not really...
In my specific use case (which in my experience is pretty common).  I have a SPA and a backend application.  The SPA passes the Bearer token to the backend and the backend needs to validate the token.  Doing just local introspection isn't enough.  What if the token was invalidated by the admin or the user invalidated the token themselves?  In this case I was still able to use the token until it expired.  
The only way I could get this to work was to disable discovery and explicitly specify the introspection path which is the default based off the auth url.  Perhaps I'm missing something but to me this isn't very intuitive.

**Comment by sberyozkin** [comment]
@jayfray12 

> Doing just local introspection isn't enough. What if the token was invalidated by the admin or the user invalidated the token themselves? In this case I was still able to use the token until it expired.

This is why it is not recommended to make ATs long lived like 24 hours but make it minutes and then refresh it or in case of SPA rerun the authentication flow - the session between KC and SPA should still be valid so the user should not be challenged to re-enter the credentials but the new AT should be obtained as a result.

Please recall that some providers don't even have an introspection endpoint so relying on the introspection may not be possible to have a portable SPA + Quarkus combination.

I'm also not sure admins really deal with specific tokens as there could be thousands or more of them - they deal with sessions and users (revoking them).

So, I think what you'd really like to do is to do the introspection only - the local verification would not be a good idea if you still would like to do the introspection - since the introspection must do the token signature verification anyway before returning any info on it.

Doing a remote introspection after a successful local verification will negatively affect the performance.

> The only way I could get this to work was to disable discovery and explicitly specify the introspection path

I'll add a new property like `allowIntrospectionOnly` - instead of doing the same indirectly (disabling the auto-discovery and having to set the introspection path manually)

**Comment by jayfray12** [comment]
If the provider doesn't have introspection (mine does in this case, Keycloak) then I agree, local introspection is the only option.
Yes, I want introspection only not both.  I agree doing both is redundant.

Thanks for willing to add the property to allow this.  Much appreciated.

**Comment by sberyozkin** [comment]
@jayfray12 No problems at all, thanks for highlighting that the way it is enabled now is not ideal :-)
