### ISSUE TITLE
Support distributed configuration with HashiCorp Vault

### ISSUE THREAD

**Issue by yuhaibohotmail** [quarkusio/quarkus#2764]
**Description**
(Describe the feature here.)

**Implementation ideas**
(If you have any implementation ideas, they can go here, however please note that all design change proposals should be posted to [the Quarkus developer mailing list](mailto:quarkus-dev@googlegroups.com) (or [the corresponding Google Group](https://groups.google.com/group/quarkus-dev); see [the decisions process document](https://github.com/quarkusio/quarkus/blob/master/DECISIONS.adoc) for more information).

**Comment by sberyozkin** [comment]
@yuhaibohotmail I have updated the title since @vsevel has completed #2897. Please open another issue if you'd like Spring Cloud Config be added on

**Comment by gsmet** [comment]
@sberyozkin @vsevel I'm not sure what's this one is referring to? Especially the "distributed" part. Was it fixed by the Vault PR?

**Comment by vsevel** [comment]
> @sberyozkin @vsevel I'm not sure what's this one is referring to? Especially the "distributed" part. Was it fixed by the Vault PR?

@yuhaibohotmail I am not sure what you are referring to. can you elaborate?
thanks

cc @gsmet

**Comment by sberyozkin** [comment]
@gsmet @vsevel I hope this issue can be safely resolved :-). Originally it was referring to either HashiCorp Vault or Spring Cloud Config. I was looking to open an issue to match @vsevel 's PR, found this one and updated.
Vault is distributed in nature, which is what the 'distributed' referred to. And its key-value secrets service can be used for keeping the general configuration values, not necessarily secret keys, this is mentioned in Vault docs as far as I recall.
We've discussed with Vincent the idea of adding the support of more Vault stores in time (Azure, etc, etc) - they can be added on demand for sure

**Comment by vsevel** [comment]
@sberyozkin I now recall some of our conversations about supporting other vault like products. we did not elaborate at that time. it was several months ago. and back then we were deep down in the design of the vault service, then the vault config source. that is what you are referring to right? you were thinking of having a UniversalVault interface of some sort. correct?

I think we achieved some of that, at least if we think in terms of abstraction.

first we introduced a vault config source. somebody else could do something similar for another vault like product. very much like the zookeeper config source available in smallrye. 

second we introduced the vault spi CredentialsProvider interface, that other extensions could implement.

finally you have created https://github.com/quarkusio/quarkus/issues/3937, which would make any property fetched from a config source available to another component that relies on MP config to gets its configuration.

as far as this issue is concerned, I think it is indeed fixed by https://github.com/quarkusio/quarkus/pull/2897

what do you think?

cc @gsmet

**Comment by sberyozkin** [comment]
@vsevel thanks; 
I only meant that right now we already have KV and DB credentials stores supported, and the former can be transparently used by the users, and once #3937 is resolved then it will be even better, our own extensions will be able to use their own properties to indirectly fetch the secrets of all sorts from Vault.
But Vault has a dozen more types of stores (engines, sorry) supported :-), https://www.vaultproject.io/docs/secrets/.
So if there will be a demand to support Active Directory, then we will add a new service alongside KV and DB creds service.

**Comment by vsevel** [comment]
@sberyozkin I see. I agree the vault extension will naturally evolve toward supporting new secret engines, and new authentication methods.
I do not think this issue is meaningful as it is. It should be more specific (eg add support for transit secret engine). or I would rather close it (because to me it has been fixed in https://github.com/quarkusio/quarkus/pull/2897), and open new ones as needed.
