### ISSUE TITLE
Performance regression in RequestContext activations

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#27735]
### Describe the bug

There is a performance regression caused by #27249 : the logging statements are allocating various `java.util.stream.SliceOps$1` and `byte[]` + `StringBuilder` to encode numbers as hex, capturing and  formatting the stacktraces.

These logging statements are protected by a check for TRACE being enabled, but it would seem the value of this is true at the point it's captured (during Arc recorder) even when not configured.

### Expected behavior

No significant overhead should be introduced.

**Comment by mkouba** [comment]
> These logging statements are protected by a check for TRACE being enabled, but it would seem the value of this is true at the point it's captured (during Arc recorder) even when not configured.

Do we know why this actually happens?

**Comment by Sanne** [comment]
> > These logging statements are protected by a check for TRACE being enabled, but it would seem the value of this is true at the point it's captured (during Arc recorder) even when not configured.
> 
> Do we know why this actually happens?

I don't know exactly, sorry. Only remembered similar issues we had in the past - would be great to make it easier to catch such a mistake - it's very misleading and clearly anyone could fall it into.

**Comment by galderz** [comment]
There was a slightly similar issue with Infinispan and other middleware projects, that cached TRACE enabled into static final variables. These would be turn out to be true at native executable runtime, even if they were built with TRACE disabled. The case here seems slightly different since caching the value of TRACE enabled is done on an instance variable rather than static variable, but maybe the cause is the same. However, as noted in https://github.com/infinispan/infinispan/pull/8921, we eventually moved away from caching this at all to enable optimizations in https://github.com/quarkusio/quarkus/pull/13376 to kick in.

**Comment by geoand** [comment]
@aldettinger, the regression happens with any kind usage of RESTEasy Reactive. We have not tested RESTEasy Classic, but it is likely affected as well.

**Comment by aldettinger** [comment]
Ok, that's interesting to know. Many thanks @geoand .

**Comment by geoand** [comment]
👍🏼

**Comment by geoand** [comment]
This kind of thing should never happen in user code. 
The reason is happened in Arc code is that some specifics parts of Quarkus are loaded before the entire logging setup is complete.
