### ISSUE TITLE
Optional Quarkus extension on native mode

### ISSUE THREAD

**Issue by spolti** [quarkusio/quarkus#27813]
### Describe the bug

We are creating a addon that, when enabled perform some queries in the Kubernetes Cluster to apply certain configurations.
However, this query, can be looking for specific OpenShift resources and the quarkus-openshift-client is then used. To avoid adding extra dependencies when not used, we would like to have this dependency as optional and if user wants to use that specific feature that relies on this extension, we would print a warn message just before the CNF exception to happen.

In the addon's runtime package we did make the ocp client as provided and removed it from the deployment package.
```
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-openshift-client</artifactId>
      <scope>provided</scope>
    </dependency>
```
For JVM mode, this change is fine. but for native, we get a compilation issue.

What is the best/recommended way to achieve it on native mode?

Initially we found that `NativeImageAllowIncompleteClasspathBuildItem` could be used, however its usage is totally discouraged. 

Thanks.

**Comment by gsmet** [comment]
Yeah so you can't do that with a native executable, at least it's really not recommended and we try to avoid that in Quarkus at all force. Thus why we deprecated `NativeImageAllowIncompleteClasspathBuildItem`.

What you should do is: have your own specific openshift dependency that depends on the Quarkus one and that will implement an SPI that is exposed by the main module so that you don't have any OpenShift specific classes in your main module.

**Comment by geoand** [comment]
+1 on what @gsmet suggests

**Comment by spolti** [comment]
Thanks all, I am closing this issue.
