### ISSUE TITLE
Impossible to set quarkus.hibernate-orm.unsupported-properties."hibernate.cache.region.factory_class"

### ISSUE THREAD

**Issue by zyc** [quarkusio/quarkus#27894]
I'm trying to use Redisson as second level strategy on my project but it is impossible because that line in `quarkus-hibernate-orm` version `2.12.1.Final`:

https://github.com/quarkusio/quarkus/blob/13b15b1f87f40cf262a767fc7e6d9f34e37c778b/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/boot/FastBootMetadataBuilder.java#L368

Because that, is useless set `quarkus.hibernate-orm.unsupported-properties."hibernate.cache.region.factory_class"=org.redisson.hibernate.RedissonRegionFactory` entry in my `application.properties`

Should `QuarkusInfinispanRegionFactory` really be mandatory using `quarkus-hibernate-orm` or am I missing something?

Thanks folks!

**Comment by yrodiere** [comment]
Configuration set by Quarkus cannot be overridden and that's on purpose, so that people don't abuse `unsupported-properties` and send feature request instead.

And that worked: you just requested a way to set the region factory to something else than the default ;)

We should indeed probably add cache-related settings to the Hibernate ORM extension.

**Comment by zyc** [comment]
You're right. I need to set some settings like:

```
quarkus.hibernate-orm.unsupported-properties."hibernate.cache.region.factory_class"=org.redisson.hibernate.RedissonRegionFactory
quarkus.hibernate-orm.unsupported-properties."hibernate.cache.use_query_cache"=true
quarkus.hibernate-orm.unsupported-properties."hibernate.cache.redisson.fallback"=false
quarkus.hibernate-orm.unsupported-properties."hibernate.cache.redisson.config"=/redisson.yaml
```

I've realized the settings being ignored here:

![Captura de Tela 2022-09-13 às 05 52 41](https://user-images.githubusercontent.com/541500/189868603-d8edfbe1-b7c7-4b70-a1ed-8f90898401ad.png)

So would be nice if had a way to set the cache settings overriding the defaults. Thanks!

**Comment by yrodiere** [comment]
Looking closer at the code, it seems Quarkus is forcing a custom Infinispan local cache on purpose. That looks like a very deliberate choice, especially from what I can read in the documentation.

@Sanne any constraints that should make us think twice before allowing custom cache implementors?

**Comment by Sanne** [comment]
Quarkus was meant to be an opinionated platform; standardizing some components was meant to make our life much simpler, and also provide great value for end users: we'd all be able to move over from the times in which platform maintainers would not take responsibility for the odd behavious of "3rd party" libraries maintained by a different community.

For example we made Agroal the mandatory datasource; not being able to replace it allows us tighter integrations and stronger performance optimisations; it also forces us to take action when *any* issue is identified in Agroal rather than saying "well, report it to them and/or use a different implementation". As a user, I've had such answers frequently in the past and it typically leads to spending most time doing integration rather than enjoying development progress.
Not least, a prescriptive approch forces us to take into account the cross-library dependency alignment; we also need to ensure that the performance you get via Agroal is so good that you won't need to ask for something else.

That's not to say that I cathegorically don't want to allow redisson's 2LC implementation as an option, but I'll need some convincing about how important and critical this is for you to become an option, and if there's something in your specific context that warrants making this an option.

Could you also share some thoughts on these points:

1.  Efficiency

Wondering if you have some data to back the idea that an external K/V store would perform better than a relational RDBMS in your context? I understand a K/V store is more suited for this kind of access pattern making it an intuitive choice, but there's always a chance for caches to not be hit - which implies there's a certain probability that the ORM will need to first bother Redis, and then bother the RDBMS *as well*, which clearly is less optimal than going straight to the DB. Consider that Hibernate ORM can do batching very well and transparently, so if your transaction needs to load say ~20 objects, you'll need to make these as 20 different Redis requests as the Cache API works on a per-item base, and you're only going to skip the RDBMS select if *all* of the requests are a hit. Anyone with a bit of a statistics background will see that this is not worth it, unless the chances to hit a single key are extremely high, almost certain.

As opposing to that pattern, while the current 2LC clearly is limited by the fact that it's in-process, but each map lookkup is so extremely cheap and local, there's no serialization overhead nor any RPCs as perforfamnce penalties for a failed cache lookup.

2. Consistency

Redis doesn't support transactions, and an Hibernate 2LC which doesn't integrate with transactions is inherently inconsistent - especially when it's out-of-process. That doesn't make it worthless, but it severaly limits the suitability of this use, to the point that I'd like to know more about your expectations in this area.

I suppose it would be fine if you're planning this for read-only, immutable reference data, and plan to pre-load the Redis cluster to ensure 100% cache hits. But would you need this to happen transparently via Hibernate in that case? The benefit of Hibernate's integration is the fact that there's a transparent fallback strategy and that it works hard to maintain consistent state across your changes and the cache.

**Comment by zyc** [comment]
Hi Sanne!

Thanks for your deep inside response but there are some relevant points on the project's architecture that were not considered in your observations and I would like to explain it.

First of all, the monetary cost to access the RDBMS data, or to provision a more robust instance, or the architecture decisions to make it scaleble, in this specific ptoject are to high and unfeseable.

The most expensive ($) calls (something about 80%) could be solved with a cache hit. I've implmented a cache control over the RESTful service layer but other ones I have to treat at data layer for the project specific reasons. I did some tests using the local cache, but this case is restricted to only one node. To garantee the scalability I must to delegate the cache control to a third-party server. In this case: the Redis.

Why Redis? Again because the conclusion of the economic feseablity analisys considering the architecture decisions orieented by the business model and infra-structure available on the ecosystem of the project.

So... would be very nice if I could choose and set that config option to override the default second level cache implementation.

**Comment by gsmet** [comment]
I agree that we should relax our point of view on this. Sure there are tradeoffs using a non transactional remote cache but the users should have the possibility to make these trade offs by themselves.

**Comment by yrodiere** [comment]
> I agree that we should relax our point of view on this. Sure there are tradeoffs using a non transactional remote cache but the users should have the possibility to make these trade offs by themselves.

Agreed, but there already is an issue about that: #9460

Closing as duplicate.
