### ISSUE TITLE
RestClient Reactive -  set HostnameVerifier or SSLContext

### ISSUE THREAD

**Issue by Chexpir** [quarkusio/quarkus#27901]
### Description

There is a [known limitation](https://quarkus.io/guides/rest-client-reactive#known-limitations) on RestClient Reactive, we cannot set a HostnameVerifier or SSLContext. 

We have switched back to rest-client-mutiny for now, even if it's deprecated, but it would be useful to get this done, so we can move back towards a fully reactive service.

Do we know the priority of this feature? At least for HostnameVerifier.

Context: It is very common to give user, when configuring webhooks, the option to use insecure SSL at their own expense, usually for testing purposes, and we want to give that to our users.

**Comment by geoand** [comment]
@Sgitario would you be willing to look into lifting this restriction?

**Comment by geoand** [comment]
I should note that it's entirely possible that we will need changes in Vert.x to support this

**Comment by cescoffier** [comment]
Vertx does not provide such a feature. So, I don't believe we can provide that feature. However, you can enable the trustall feature which will by-pass the verification.

**Comment by cescoffier** [comment]
The SSL context approach may work with vertx 4.3.4 (some rework around ssl has been achieved, it should provide such an option)

**Comment by Chexpir** [comment]
Thanks everybody for your prompt responses. If HostnameVerifier support is not achievable, SSLContext support is still good for our requirements.

trust-all operates in the app level, and we have the need to trust only _some_ of the Rest Clients.

When I said "at least HostnameVerifier" I thought it would be easier, but I am totally happy without HostnameVerifier, as SSLContext will perfectly be valid to get different Rest Clients in the same service with and without SSL verification.

**Comment by famod** [comment]
My 2 cents:
> Allow providing a custom TrustManager. 

How would an implemetation look like that tries to mimic `io.quarkus.restclient.NoopHostnameVerifier`?
As already mentioned, the manager approach would probably _not_ verify much more than just the host?
Could Quarkus provide such a "workaround" manager OOTB?

Also, I assume that with this workaround, Quarkus would still properly set up the `KeyManager`?
Reason I'm asking is that it's too easy to shoot yourself in the foot when setting up `SSLContext`, e.g. passing `null` for the managers by mistake because you only want to set the TLS version (just had that in my project recently).

To me, the second option _look_ better for now.

**Comment by famod** [comment]
> trust-all operates in the app level, and we have the need to trust only _some_ of the Rest Clients.

+💯

**Comment by geoand** [comment]
I personally think that if we properly document how to address the common concerns, we don't really need to have `HostnameVerifier` "emulation".

**Comment by famod** [comment]
My point is that it's not _that_ rare to skip hostname verification, so it would be much more developer friendly if Quarkus would close that gap by shipping something that can be used OOTB.
Otherwise people woud need to implement their own Manager and carry it around from project to project to cover a concern that most would expect to be just a flag to enable. Just saying. 😉

**Comment by famod** [comment]
> My point is that we don't need to necessarily have a `HostnameVerifier` emulation layer - I think it's acceptable to have something different but equally easily usable.

Agreed!
In the end I just need the client to _not_ verify the hostname (_without_ skipping every other verification), so I don't need such a layer.

**Comment by Sgitario** [comment]
If what we want is to skip the hostname verification, we can achieve this by setting 'verifyHost(false)'. All we would need is to add a new property for setting this flag.

**Comment by Chexpir** [comment]
Hi @Sgitario ! I am sure most of the developer use cases will be covered with that, and developer experience using it is very straightforward.

I am unsure if our specific use case is covered, as due to the dynamic base URLs we have, we are forced to use [RestClientBuilders](https://quarkus.io/guides/rest-client-reactive#programmatic-client-creation-with-restclientbuilder) programatically.
