### ISSUE TITLE
Resteasy @JsonProperty not work

### ISSUE THREAD

**Issue by pipinet** [quarkusio/quarkus#2810]
**Describe the bug**
Resteasy @JsonProperty not work

**Expected behavior**
i can get post data identityType in User class instance

**Actual behavior**
identityType is null

demo is: https://github.com/qwlabs/quarkus-issues/tree/master/2019-06-21-21-00

**Comment by gsmet** [comment]
I think the issue is that you have both declared `resteasy-jsonb` and the Jackson provider as dependencies.

You are using Jackson's `@JsonProperty` and I bet it's using JSON-B to serialize the bean.

I would remove `resteasy-jsonb` and see how it goes. Or use `@JsonbProperty` and remove the Jackson dependency.

**Comment by pipinet** [comment]
ok, thanks, i remove quarkus-resteasy-jsonb, works!!!

**Comment by Jonathanfdr** [comment]
> I think the issue is that you have both declared `resteasy-jsonb` and the Jackson provider as dependencies.
> 
> You are using Jackson's `@JsonProperty` and I bet it's using JSON-B to serialize the bean.
> 
> I would remove `resteasy-jsonb` and see how it goes. Or use `@JsonbProperty` and remove the Jackson dependency.

You are my Jesus!
