### ISSUE TITLE
AWS XRay extension doesn't send traces

### ISSUE THREAD

**Issue by snowe2010** [quarkusio/quarkus#28610]
### Describe the bug

XRay traces are not mapped between nodes. This has previously been an [issue](https://github.com/quarkusio/quarkus/issues/22595). Using @patriot1burke's [xray-demo](https://github.com/patriot1burke/xray-demo) provided in that issue, you can easily deploy it and see that no xray traces are generated for the subsegments. In addition to that I have created a
[reproducer](https://github.com/quarkusio/quarkus/files/9789041/reproduce-xray-issue.zip) that uses a lambda, rather than an api endpoint, that demonstrates that automatic instrumentation showing traces between applications does not work. 

### Expected behavior

I expect viewing a service map in AWS  
<img width="618" alt="image" src="https://user-images.githubusercontent.com/1534535/195914432-80fe5ca6-424c-4e35-93ff-ff56f0dbfb8c.png">
to display the full map of services called rather than only the quarkus app itself. 

### Actual behavior

For quarkus apps, we only see a single node, no dependencies. <img width="678" alt="image" src="https://user-images.githubusercontent.com/1534535/195913909-8603bb9d-bdde-4052-99e3-3dafc59c90e2.png">

### How to Reproduce?

Using @patriot1burke's [xray-demo](https://github.com/patriot1burke/xray-demo)

1. build with `mvn clean install -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.1.0-java17`
2. deploy with `sam deploy -t sam.native.yaml -g`
3. hit the endpoint through api gateway test
4. verify in service map that there are no subsegments

[reproducer](https://github.com/quarkusio/quarkus/files/9789041/reproduce-xray-issue.zip)

1. build with `mvn clean install -Dquarkus.native.container-build=true -Dquarkus.native.builder-image=quay.io/quarkus/ubi-quarkus-native-image:22.1.0-java17`
2. deploy with `sam deploy -t sam.native.yaml -g`
5. hit the lambda through Test tab in console
6. verify in service map that there are no calls or subsegments to any aws services

### Output of `uname -a` or `ver`

Darwin MacBook-Pro.local 21.6.0 Darwin Kernel Version 21.6.0: Mon Aug 22 20:17:10 PDT 2022; root:xnu-8020.140.49~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.3" 2022-04-19 OpenJDK Runtime Environment GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06) OpenJDK 64-Bit Server VM GraalVM CE 22.1.0 (build 17.0.3+7-jvmci-22.1-b06, mixed mode, sharing)

### Quarkus version or git rev

2.13.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

 Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /Users/tyler/.asdf/installs/maven/3.8.6 Java version: 17.0.3, vendor: GraalVM Community, runtime: /Users/tyler/.asdf/installs/java/graalvm-22.1.0+java17 Default locale: en_US, platform encoding: UTF-8 OS name: "mac os x", version: "12.6", arch: "x86_64", family: "mac"

### Additional information

https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/aws.20xray

**Comment by dvelho** [comment]
Also having the same issue

**Comment by radcortez** [comment]
I've tried to reproduce the issue by running the reproducers. I believe that everything is working as intended.

If you use https://github.com/patriot1burke/xray-demo, the configuration is missing the `Tracing: Active` in the generated sam file. I'm wondering if we should add that automatically if you add the x-ray extension. On the other hand, I'm not sure if this is something we want to do.

![Screenshot 2022-11-04 at 12 20 24](https://user-images.githubusercontent.com/5796305/200014220-bf33f0b7-8c68-4161-9d64-fad23aed8c19.png)

We can observe the subsegment generated in the tracing log.

When using your reproducer with the Lambda function, I was also able to observe AWS resources being called:

![Screenshot 2022-11-04 at 15 04 36](https://user-images.githubusercontent.com/5796305/200014576-52bf5bab-ffef-4d18-8eb8-10ed5c4c050f.png)

I get an error invoking the service, but this is expected since I don't have an SSM, but I think it doesn't matter since we can observe the call to that AWS service.

**Comment by radcortez** [comment]
Closing due to no response back and unable to reproduce.
