### ISSUE TITLE
Simplify development of Kafka Streams applications

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#2863]
As of #2663, there's support for running Apache Kafka Streams stream processing applications on Quarkus. There's still some boilerplate, though, which could be further reduced. Eventually, all that the application developer should have to provide is the actual stream pipeline topology and its configuration. So I could see the following to be done as a follow-up:

- [x] Support that a `Topology` can be provided by the application developer using a producer method
- [x] Have the extension automatically take care of managing the `KafkaStreams` instance running that topology (start, stop)
- [x] Support configuring KS via `application.properties`, akin to messaging sinks/sources in Reactive Messaging (see https://github.com/quarkusio/quarkus/issues/3030 for an issue related to resolving nested properties - as needed for resolving the application name - which should be fixed by now)
- [x] Take advantage of simpler JNI set-up (see https://github.com/quarkusio/quarkus/pull/3060)

If have some code for this already handy in a PoC.

@gsmet, can you assign this to me?

**Comment by aesteve** [comment]
Thank you for putting so much effort into this.
Would Avro serde be part of your goal ?
Like adding schema-registry URL in application.properties, and (un)marshalling from/to Avro's generic record onto a POJO ?

Thank you.

**Comment by gunnarmorling** [comment]
Hey @aesteve, I haven't thought about Avro support yet. AFAIK there are Avro SerDes coming with the schema registry already, those should work?

**Comment by aesteve** [comment]
Didn't try it yet (with Quarkus), but they should work indeed for extracting `GenericRecord`, but I'm not sure if they allow to map directly on POJOs ? 

Maybe there are some traps with blocking non-blocking ? Since http requests to the registry could block ? not sure how Quarkus handles the blocking/non-blocking ambiguity, not sure if the Quarkus Kafka extension is blocking or not, but that shouldn't be a major issue.

I was maibly asking about Avro because I read : 

> Auto-register types for reflection that are de-serialized by Serdes used in the pipeline

Not sure how this would be handled with Avro or another SerDe (not the Quarkus-provided Jsonb one)

**Comment by gunnarmorling** [comment]
I was having some issues in dev mode (see https://github.com/quarkusio/quarkus/issues/3058). Will provide a reproducer in a bit.

**Comment by gunnarmorling** [comment]
@gsmet, shouldn't this one have be closed with the last release?

**Comment by machi1990** [comment]
Hi @gunnarmorling, I just noticed that all sub-tasks in this issue have been checked. Can this issue be safely closed? Thanks.
