### ISSUE TITLE
Default Quarkus application generated by maven plugin with security-webauthn extension doesn't compile

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#28746]
### Describe the bug

Quarkus: `2.13.3.Final`

The Default Quarkus application generated by Maven plugin with `security-webauthn` extension is throwing an exception on compile time.

Stacktrace
```
[ERROR] [1] Unsatisfied dependency for type io.quarkus.security.webauthn.WebAuthnUserProvider and qualifiers [@Default]
[ERROR]     - java member: io.quarkus.security.webauthn.WebAuthnTrustedIdentityProvider#userProvider
[ERROR]     - declared on CLASS bean [types=[io.quarkus.security.identity.IdentityProvider<io.quarkus.security.identity.request.TrustedAuthenticationRequest>, io.quarkus.security.webauthn.WebAuthnTrustedIdentityProvider, java.lang.Object], qualifiers=[@Default, @Any], target=io.quarkus.security.webauthn.WebAuthnTrustedIdentityProvider]
```

### Expected behavior

Quarkus application that actually works.

### Actual behavior

Quarkus app doesn't compile

### How to Reproduce?

```
mvn io.quarkus.platform:quarkus-maven-plugin:2.13.3.Final:create\
    -DprojectGroupId=org.acme\
    -DprojectArtifactId=config-quickstart\
    -Dextensions='security-webauthn'\
    -DnoCode
```

`mvn clean install`

**Comment by geoand** [comment]
cc @FroMage

**Comment by sberyozkin** [comment]
Steph, I thought it might be related to `quarkus-security` being absent from the pom, but it is there

**Comment by sberyozkin** [comment]
Steph, please have a look

**Comment by FroMage** [comment]
Yeah, that's normal, actually, the docs mention that in order to use webauthn you must provide a mapping from your entities to webauthn credentials by providing a CDI bean implementing that interface: https://quarkus.io/guides/security-webauthn#exposing-your-entities-to-quarkus-webauthn

I could generate a default bean that fails at run-time, but that's not ideal either. Would you be content with a better build-time error message that tells the user they should implement that interface?

**Comment by geoand** [comment]
+1 for an actionable build time message

**Comment by sberyozkin** [comment]
@FroMage Steph, this one should be easy to fix, please open a small PR as you planned

**Comment by sberyozkin** [comment]
Closing as a duplicate of #32376
