### ISSUE TITLE
Container labels for dev services

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#28857]
### Description

I have a multi tenant setup with multiple databases. Therefor, running quarkusDev or quarkusTest will launch multiple devservices. 
This will result in 2 identical containers with randomly generated names and I am not able to tell which is for which tenant, making debugging difficult.

### Implementation ideas
It would be great if I could either configure a container name of a dev service or attach labels to a dev service, so I can recognize which is which. 

Or even better, the container automatically gets the datasource name as label. The last approach would not clutter up the configs and would not bother anyone.

_No response_

**Comment by geoand** [comment]
I think this is a very good idea. 

WDYT @gsmet @yrodiere @cescoffier?

**Comment by cescoffier** [comment]
+1 for labels. 

We are already suing labels to "share" dev services.

**Comment by geoand** [comment]
Apart from the datasource name, what other labels do we want?

**Comment by yrodiere** [comment]
When dev service sharing is disabled, some identifier of the application could be useful. It wouldn't hurt when sharing is enabled, though it could be confusing: it would be about the application that started the container, not the application that uses it (since there may be multiple such applications).

What would we use to identify the application, though... I guess the value of `quarkus.application.name` or the GAV would be a start, but I'm not sure how to differentiate between two instances of the same application; maybe the startup timestamp?

Other than that, nothing comes to mind. Of course we could add plenty of metadata, but I think what's most important here is to distinguish between similar containers, not to get actual metadata.

**Comment by geoand** [comment]
> Of course we could add plenty of metadata, but I think what's most important here is to distinguish between similar containers, not to get actual metadata.

+1

**Comment by HerrDerb** [comment]
> Other than that, nothing comes to mind. Of course we could add plenty of metadata, but I think what's most important here is to distinguish between similar containers, not to get actual metadata.

+1 that currently the only need

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/28949 adds only the datasource label for now

**Comment by HerrDerb** [comment]
Cool, thank you 👍😊

**Comment by geoand** [comment]
Thanks for reporting the issue :)
