### ISSUE TITLE
Managed Executor from Smallrye Context Propagation: Add configuration options

### ISSUE THREAD

**Issue by mschorsch** [quarkusio/quarkus#28977]
### Description

As discussed in https://github.com/quarkusio/quarkus/discussions/28862 the worker pool that should be used in Quarkus is the [Managed Executor from Smallrye Context Propagation](https://quarkus.io/guides/context-propagation#usage-example-for-completionstage).

The worker pool cannot currently be configured via `application.conf`. Please add configuration options to configure this pool (e.g. min/max size).

**Comment by mschorsch** [comment]
@geoand as discussed in https://github.com/quarkusio/quarkus/discussions/28862#discussioncomment-4015964

**Comment by FroMage** [comment]
This is a wrapper onto the Quarkus thread pool, which is configured separately. The `ManagedExecutor` settings don't actually apply in this case because it's not creating a new thread pool.

You can configure the thread pool with [quarkus.thread-pool.core-threads](https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.core-threads) and [quarkus.thread-pool.max-threads](https://quarkus.io/guides/all-config#quarkus-core_quarkus.thread-pool.max-threads)

**Comment by geoand** [comment]
Thanks for the information @FroMage. I didn't know that

**Comment by FroMage** [comment]
I had to re-read the code to remember :)
