### ISSUE TITLE
Setting of system property  java.io.tmpdir having no effect on VertxTemplate in native mode

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#2898]
**Describe the bug**
Setting of system property `java.io.tmpdir` in native mode has no effect for vert.x quickstart. This is part of the discussion [here](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Native.20builds.3A.20JVM.20options.20at.20runtime/near/168516155). 

**Expected behavior**
Setting the `java.io.tmpdir` system property should work correctly since the `VertxTemplate` is a RuntTime init template

**Actual behavior**
The system property is ignored

**To Reproduce**
1. Use the vertx quickstart :https://github.com/quarkusio/quarkus-quickstarts/tree/master/using-vertx
2. Create a native binary
3. Attempt to set the system property by doing something like: `target/using-vertx-1.0-SNAPSHOT-runner -Djava.io.tmpdir=/dummy`. This should fail normally since the directory does not exist (and it of course does fail when running `java -Djava.io.tmpdir=/dummy -jar target/using-vertx-1.0-SNAPSHOT-runner.jar`).

**Comment by emmanuelbernard** [comment]
CC @cescoffier @vietj @tsegismont

**Comment by mkouba** [comment]
So I've just verified that the system property itself is not ignored. But maybe it's too late to set it here: https://github.com/quarkusio/quarkus/blob/master/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/runtime/VertxTemplate.java#L79 because the `FileSystemOptions` is already initialized with the `io.vertx.core.file.FileSystemOptions.TMPDIR` static field which is probably recorded during the native image build.

According to [the docs](https://vertx.io/docs/vertx-core/java/#_configuring_vert_x_cache) the cache is only used when accessing files from the classpath. Is that right @cescoffier @vietj @tsegismont? What's the easies way to test a cache dir?

**Comment by mkouba** [comment]
It turns out the cache dir is initialized eagerly so I've manually tested that `using-vertx` quickstart fails if I use `target/using-vertx-1.0-SNAPSHOT-runner -Djava.io.tmpdir=/dummy` and quarkus build from [this PR](https://github.com/quarkusio/quarkus/pull/3016)
