### ISSUE TITLE
Request Context Race condition in quarkus 2.13

### ISSUE THREAD

**Issue by rmanibus** [quarkusio/quarkus#29017]
### Describe the bug

when firing an async CDI Event, the request context from the emitter briefly exists for the observer and is then terminated.
This prevents to create a new Request context for the Async observer since the emitter context still exist.

This was working in Quarkus 2.12

### How to Reproduce?

reproducer: 

https://github.com/rmanibus/quarkus_29017

execute the ReproducerTest

### Quarkus version or git rev

2.13.3.Final

**Comment by rmanibus** [comment]
@mkouba do you have an idea about this ?

**Comment by mkouba** [comment]
> @mkouba do you have an idea about this ?

No idea so far. I need to take a good look at the reproducer. In any case, the `@ActivateRequestContext` should not be needed for async observers because the request context is always active during notification.

**Comment by mkouba** [comment]
It seems that a new request context is not activated during the notification because the thread that is used has an associated Vertx _duplicated context_ with the request context state from the thread that was used to handle the `org.acme.Resource.execute()` resource method... which is really weird :thinking: CC @cescoffier 

Note that we use the `ExecutorService` obtained from the `ExecutorBuildItem` (i.e. the  executor for blocking tasks) for notification of async observers. 

What's also weird is that if stop the execution during debugging in the `EventImpl.Notifier.notify()` method before the observer is notified and wait a little then a new context is not activated but the test passes.

**Comment by mkouba** [comment]
It turns out that the [Vertx context is captured](https://github.com/quarkusio/quarkus/blob/2.14.0.Final/extensions/vertx/runtime/src/main/java/io/quarkus/vertx/core/runtime/VertxCoreRecorder.java#L549-L573) when a new task is submitted from a thread of the default blocking `ExecutorService` and restored when the task is executed on a different thread. I would not expect this kind of behavior but it's implemented this way for a long time (probably because of some Mutiny use cases?). As a result, the https://github.com/quarkusio/quarkus/pull/27443 caused this regression.

**Comment by mkouba** [comment]
> I would not expect this kind of behavior but it's implemented this way for a long time

Note that the capture/restore makes it possible to access the vertx context concurrently from multiple threads.
