### ISSUE TITLE
JwtClaimsBuilder failing with setting claims for UUID with the Quarkus 2.13.3

### ISSUE THREAD

**Issue by Esakkimuthu991** [quarkusio/quarkus#29023]
### Describe the bug

We 've got issue saying "_java.lang.ClassCastException: class java.util.UUID cannot be cast to class java.lang.String (java.util.UUID and java.lang.String are in module java.base of loader 'bootstrap')_" while setting claims using JwtClaimsBuilder with the latest quarkus version 2.13.3.

```java
public final class TestUtil {
    public static String generateString(final UUID uuid) {
        final JwtClaimsBuilder claimsBuilder = Jwt.claims();
        claimsBuilder.claim("TEST_ACCESS", Map.of(UUID.randomUUID(), List.of("test")));
        return claimsBuilder.toString();
    }
}
```

We are facing issue in line `claimsBuilder.claim("TEST_ACCESS", Map.of(UUID.randomUUID(), List.of("test")));` . 

### Expected behavior

It was worked with the previous version which is quarkus 2.11.3. With the current version (2.13.3) also, it should work as the same as expected.

### Actual behavior

Getting error saying "_java.lang.ClassCastException: class java.util.UUID cannot be cast to class java.lang.String (java.util.UUID and java.lang.String are in module java.base of loader 'bootstrap')_"

### How to Reproduce?

Create a java final class and create a static method which should try to set the JwtClaimsBuilder claims using arguments as follow

Argument-1 : DataType- String , Value - TESTSTRING
Argument-2: DataType- Object, Value- Map.Of(UUID.randomUUID, List.Of("test"))

### Output of `java -version`

Java 11

### Quarkus version or git rev

Quarkus-2.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by sberyozkin** [comment]
Hi @Esakkimuthu991 It feels like it is something to do with the project not being re-built or something like that, can you please provide a reproducer ?

**Comment by sberyozkin** [comment]
@Esakkimuthu991 I've looked at it closer, I'm not sure how it ever worked for you, since `smallrye-jwt-build`, when dealing with the Maps which represent a complex claim value/JSON structure, always expects Map keys be strings which is what JSON doc keys are always are.
I don't think we should update `smallrye-jwt-build` to convert Map keys to String as `.toString()` as it can lead to harder to diagnoze JSON parsing/creation issues if `toString()` produces some Object representation which can't be a real JSON key value like an object system hash value for some object which does not override `toString()` like `UUID` does, IMHO it is better to detect the problem early
Please use `Map.Of(UUID.randomUUID().toString(), List.Of("test"))`

**Comment by Esakkimuthu991** [comment]
we can change it to String but the cause is with the latest version is not supports UUID in few other scenarios as well. if we fix this its failing in some other scenario. then we couldn't reap the benefit of using UUID in our project.

**Comment by sberyozkin** [comment]
@Esakkimuthu991 
>we can change it to String but the cause is with the latest version is not supports UUID in few other scenarios as well. if we fix this its failing in some other scenario. then we couldn't reap the benefit of using UUID in our project.

I'm sorry, but I don't understand how the fact that we can't treat objects as JSON keys predictably has anything to do with the use of UUID elsewhere in your project. You have said you had it working in the earlier, I can't see how it ever worked, can you do a reproducer confirming it ?

IMHO we should close this issue...

**Comment by geoand** [comment]
Closing as we never got feedback
