### ISSUE TITLE
Mocking Rest client does not work with 2.14.0.CR1

### ISSUE THREAD

**Issue by robp94** [quarkusio/quarkus#29128]
### Describe the bug

Mocking a Client like this worked with 2.13.3

```
@Alternative()
@Priority(1)
@ApplicationScoped
@RestClient
public class ClientMock implements Client {
```
but does not with 2.14

### Expected behavior

Mocking works.

### Actual behavior

The mock is ignored.

### How to Reproduce?

[code-with-quarkus-client-mock.zip](https://github.com/quarkusio/quarkus/files/9962098/code-with-quarkus-client-mock.zip)

There is a simple test included.

If you switch to 2.13.3 the test passes.

### Output of `uname -a` or `ver`

windows/ubuntu

### Quarkus version or git rev

2.14.0.CR1

**Comment by geoand** [comment]
@mkouba this seems to be an Arc issue. Essentially with Quarkus `2.13`, `io.quarkus.arc.processor.Types#getClassBeanTypeClosure` would include `Client` for the `ClientMock` class of the reproducer.
However in `2.14` `Client` is not included as one of the types of the bean.

I assume this is due to #28374

**Comment by geoand** [comment]
The commit was just my best guess, I could certainly be off the mark

**Comment by manovotn** [comment]
> > The commit was just my best guess, I could certainly be off the mark
> 
> I think that it's a regression caused by #28429.
> 
> CC @manovotn

Yeah, that looks like a side effect of this issue.
Resteasy resources classes are `@Typed` to only the implementation class so that they work correctly with bean resolution in bean factories used (among others) in resteasy reactive.
`Client` class is affected because it has `@Path` annotation on it and I assume RR carries that over to the impl class somehow (since this is outside of CDI behavior).

So `@Inject ClientMock` would work but `@Inject Client` will fail.

**Comment by geoand** [comment]
We'll need to address this because this manual mocking won't work otherwise

**Comment by manovotn** [comment]
I agree, I am just not sure how to do that yet :)

**Comment by geoand** [comment]
Let's figure it out tomorrow 😜

**Comment by geoand** [comment]
> Client class is affected because it has @Path annotation on it and I assume RR carries that over to the impl class somehow (since this is outside of CDI behavior)

I am not sure I understand this, can you elaborate please?

**Comment by manovotn** [comment]
> > Client class is affected because it has @path annotation on it and I assume RR carries that over to the impl class somehow (since this is outside of CDI behavior)
> 
> I am not sure I understand this, can you elaborate please?

That is just a poorly formulated remnant of my brain trying to figure out how this works behind the scenes; feel free to disregard that :)

I discussed this with @mkouba and @Ladicek and while we haven't discovered any silver bullets, we could improve it by adding interfaces into bean types. It is a little but of extra processing but solves the issue presented here.
I've cobbled together a draft of that proposal in https://github.com/quarkusio/quarkus/pull/29155
Comments and better ideas are welcome!
