### ISSUE TITLE
java.lang.NoSuchMethodError: 'boolean org.junit.platform.commons.util.CollectionUtils.isConvertibleToStream(java.lang.Class)'

### ISSUE THREAD

**Issue by punkratz312** [quarkusio/quarkus#29139]
### all @ParameterizedTest fail because of missing code

upgrading from 2.13.0 to 2.13.4.Final brakes out build:

<img width="2026" alt="image" src="https://user-images.githubusercontent.com/8830888/200749955-5765b290-1ec5-4e2e-aeba-d0e0cef32c28.png">

<img width="2394" alt="image" src="https://user-images.githubusercontent.com/8830888/200750247-cfd13a5f-5bcf-4f00-8cbe-1dd761c750b9.png">

'boolean org.junit.platform.commons.util.CollectionUtils.isConvertibleToStream(java.lang.Class)'
java.lang.NoSuchMethodError: 'boolean org.junit.platform.commons.util.CollectionUtils.isConvertibleToStream(java.lang.Class)'
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.lambda$getFactoryMethodBySimpleName$4(MethodArgumentsProvider.java:92)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:178)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethodBySimpleName(MethodArgumentsProvider.java:94)
	at org.junit.jupiter.params.provider.MethodArgumentsProvider.getFactoryMethod(MethodArgumentsProvider.java:68)
	at 

### Expected behavior

fix missing dependency no: java.lang.NoSuchMethodError

**Comment by gsmet** [comment]
Screenshots are not so useful for us to debug. Please provide a reproducer.

**Comment by punkratz312** [comment]
@gsmet yes, you have managed to fix this issue, probably by accident or luck 🍀. the NoSuchMethodError, which is obviously an quarkus problem, is fixed in 2.14.2. its very annoying that for every little obvious issue you require a reproducer. seeing the high number of bugs that gets released, im really fighting for the spring migration they have serverless too. imho rather have 1% more resource footprint by using spring than using the new fancy kid on the block thats not production ready and full of even critical security bugs that i have reported by my self and that wasn’t even merged as fast at possible. forcing us to build a fix for every PanacheEntityResource.

<img width="259" alt="image" src="https://user-images.githubusercontent.com/8830888/204479725-85355b24-4005-4fd3-997d-4e4692f6956d.png">

**Comment by gsmet** [comment]
Well, first, I don't see you reporting many issues so if you have many, maybe you should report them?

Then, your issue was most probably caused by a misalignment of your dependencies so nothing to do with Quarkus itself.

Finally, you benefit from the project, the least you can do is take the time to qualify the issues you have and make it easy for us to reproduce the problem. If we have to spend 4 hours shooting in the dark trying to reproduce every issue, it just doesn't scale. Also, in a lot of cases, by trying to reproduce the issue, people discover it's an issue in their own code, not in Quarkus. This issue is not obvious, we have absolutely no idea how to reproduce it, especially given our test suite is using JUnit and working well.

As for your security issue, which was a missing feature, a fix was merged the day after you reported the issue (not sure that qualifies as `that wasn’t even merged as fast at possible`) and, unfortunately the issue was created just after we built the 2.14.0.Final core artifacts so you had to wait until Nov 16th for the 2.14.1.Final release. We usually release every week but when doing the `.0.Final`, we have a 2 week gap.
I don't see any comment from you in the issue stating it was a pressing issue for you. We might have considered changing our schedule.

But, for sure, using Quarkus or not using Quarkus is up to you. I certainly don't force you to use it.

**Comment by punkratz312** [comment]
@gsmet thanks for your message.

please believe me, the only think that was changes is the quarkus dependency and 2.14.1 fails 2.14.2 works. so the only possible source for the pretty obvious NoSuchMethodError issue comes from the framework in my humble opinion.
i even tried to add the junit-params dependency it did not fixed the issue, only the bump to 2.14.2 does, so there is no doubt for me where the issue is/was located.
