### ISSUE TITLE
spring-di - WARN Failed to index org.osgi.annotation.bundle.Requirements

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29206]
### Describe the bug

spring-di - WARN Failed to index org.osgi.annotation.bundle.Requirements

This wasn't happening in previous Quarkus releases

```
mvn quarkus:dev
...
2022-11-11 15:04:25,550 WARN  [io.qua.arc.pro.BeanArchives] (build-9) Failed to index org.osgi.annotation.bundle.Requirements: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV@2b4bac49
...
```

### Expected behavior

No warning

### Actual behavior

`2022-11-11 14:57:43,349 WARN  [io.qua.arc.pro.BeanArchives] (build-13) Failed to index org.osgi.annotation.bundle.Requirements: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: DEV@50a7bc6e`

### How to Reproduce?

 - generate app which is using `spring-di`
 - run `mvn quarkus:dev`
 - check the log

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 11

### Quarkus version or git rev

2.14.0.Final

**Comment by famod** [comment]
I'm also seeing this during image build (quarkus-maven-plugin -> jib):
```
[WARNING] [io.quarkus.arc.processor.BeanArchives] Failed to index org.mapstruct.Mapping: Class does not exist in ClassLoader QuarkusClassLoader:Deployment Class Loader: PROD@61791fd1
```
Mapstruct is a `provided`  dependency.

**Comment by geoand** [comment]
The Spring code producing this has not changed for a while, so this is probably indeed due to the Jandex update.
I wonder if the `WARNING` should be downgraded to `DEBUG`...

**Comment by Ladicek** [comment]
So the `@Requirement` annotation comes from MP Config's `@ConfigProperty`, and it's been there for quite a while. The only reason why it shows now is that Jandex 3 also indexes class-retained annotations, while Jandex 2 only indexed runtime-retained annotations.

Since this happens during creation of the bean archive index, I'd probably suggest to ignore class-retained annotations altogether, because all CDI annotations should be runtime-retained anyway. Thoughts @mkouba?

**Comment by Ladicek** [comment]
Hmm, except we can't distinguish class-retained annotations from runtime-retained annotations during indexing, as `ClassSummary` only has annotation names. Uhm...

**Comment by mkouba** [comment]
> Since this happens during creation of the bean archive index...

It does not have to be. It could also happen when computing an additional class info, i.e. when a `BeanArchiveIndexBuildItem` client does something like `index.getClassByName(Requirements.class.getName())`...

**Comment by Ladicek** [comment]
Right, wrong language on my side. It isn't during _creation_ of the bean archive index, but it is still a meta-annotation looked up from the bean archive index. Which I _think_ could just pretend that class-retained annotations do not exist.

Not entirely pretty -- but I'm fairly confident that failing to find a class-retained annotation during `SpringDIProcessor`'s annotation traversal is harmless, and there must be a good way to distinguish situation.

**Comment by Ladicek** [comment]
Okay so my comment above is not correct: during bean archive index creation, only annotations directly present on classes are indexed. Meta-annotations are not.

This prevents a simple solution: just remember missing classes during bean archive index creation, so that when the on-demand-indexing `IndexWrapper` is asked for `@Requirements`, it can just straight return `null` without trying to load its class.

However, a slightly more complex variation on that is possible: when creating the bean archive index, look for and remember missing meta-annotations. (I don't really know why we don't index meta-annotations transitively, perhaps we should?)

I'll have a PR shortly.

**Comment by mkouba** [comment]
> Okay so my comment above is not correct: during bean archive index creation, only annotations directly present on classes are indexed. Meta-annotations are not.

Just to be clear - you're talking about indexing additional bean classes coming from `AdditionalBeanBuildItem`, right? 

I agree that we could just index meta-annotations as well and prefill the `BeanArchives.IndexWrapper` with _"known misses"_.

**Comment by Ladicek** [comment]
> > Okay so my comment above is not correct: during bean archive index creation, only annotations directly present on classes are indexed. Meta-annotations are not.
> 
> Just to be clear - you're talking about indexing additional bean classes coming from `AdditionalBeanBuildItem`, right?

Correct.

> I agree that we could just index meta-annotations as well and prefill the `BeanArchives.IndexWrapper` with _"known misses"_.

Okay, @geoand expressed the same opinion in the PR, so I'll do that.
