### ISSUE TITLE
Kubernetes resources generation log not on par with what is generated

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#29209]
### Describe the bug

When you generate a container image and Kubernetes resources but not push the image to a remote Docker registry, the following logs is shown

```
[WARNING] [io.quarkus.kubernetes.deployment.KubernetesDeployer] A Kubernetes deployment was requested, but the container image to be built will not be pushed to any registry because "quarkus.container-image.registry" has not been set. The Kubernetes deployment will only work properly if the cluster is using the local Docker daemon. For that reason 'ImagePullPolicy' is being force-set to 'IfNotPresent'.
```

However, the generated resouce have `imagePullPolicy: Always`.

### Expected behavior

Either the log is updated either the generated resource is updated to match each other.

### Output of `uname -a` or `ver`

Ubuntu 22.04

### Output of `java -version`

17

### Quarkus version or git rev

2.14.0.Final

**Comment by geoand** [comment]
I remember we used to change the image pull policy but I don't see where we do that anymore... 
I am thinkin of removing the warning completely, WDYT @Sgitario ?

**Comment by Sgitario** [comment]
I agree with you. The warning message is confusing more than helping. Will create a pull request to remove the warning.

**Comment by llowinge** [comment]
@Sgitario @geoand Actually i've found such warning very handy - if it would actually works like written in the description. With local kubernetes developing, one really has to change the `imagePullPolicy` from `Always` to `Never` or `IfNotPresent` otherwise, the deployment will fail (because it tries to pull the image from dockerhub even it is already present locally).
