### ISSUE TITLE
Some tests are failing for rest and reactive data panache

### ISSUE THREAD

**Issue by afalhambra** [quarkusio/quarkus#29304]
### Describe the bug

It seems that since this commit https://github.com/quarkusio/quarkus/commit/d24ec2ec6720e559b798ebf4dc7cc3a320e2c7e4 was merged, we got some failures in our test suite related to it.

For instance:
```
Error:    CRUDAllInPanacheWithFlywayIT.testAllRepositoryMethods:33 expected: <[Alaba, Balaba]> but was: <[Balaba, Alaba]>
```

It's actually calling a rest data panache based [endpoint](https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/panache-flyway/src/test/java/io/quarkus/ts/sqldb/panacheflyway/CRUDAllInPanacheWithFlywayIT.java#L29), with no sort/ordering passed as a parameter to the same and as per [doc](https://quarkus.io/guides/rest-data-panache), we should expect to be ordered ascending when this is the case.

Note: It is failing as well reactive data panache tests and other databases tests, such as MariaDBPanacheResourceIT, PostgresqlPanacheResourceIT,  etc.

Log can be found: https://github.com/quarkus-qe/quarkus-test-suite/actions/runs/3474964498/jobs/5808929978

### Expected behavior

CRUDAllInPanacheWithFlywayIT pass and the order is ascending

### Actual behavior

Return ordered is not meeting the expecting value - ascending order.

### How to Reproduce?

1. Clone https://github.com/quarkus-qe/quarkus-test-suite
2. Run below maven command

```
mvn clean verify -f sql-db/panache-flyway -Dtest=NONE -DfailIfNoTests=false -Dit.test=CRUDAllInPanacheWithFlywayIT
```

### Output of `uname -a` or `ver`

Linux antferna.remote.csb 4.18.0-372.32.1.el8_6.x86_64 #1 SMP Fri Oct 7 12:35:10 EDT 2022 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18

### Quarkus version or git rev

main

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

**Comment by afalhambra** [comment]
@Sgitario fyi

**Comment by Sgitario** [comment]
Those tests were working before because you were overriding the `findAll` method in the UserRepository: https://github.com/quarkus-qe/quarkus-test-suite/blob/main/sql-db/panache-flyway/src/main/java/io/quarkus/ts/sqldb/panacheflyway/UserRepository.java#L12

From https://github.com/quarkusio/quarkus/commit/d24ec2ec6720e559b798ebf4dc7cc3a320e2c7e4, we're not using the `findAll()` method any longer, but `find(String query, Map<String, Object> params)`. Actually, if you change the implementation to:
```java
@ApplicationScoped
public class UserRepository implements PanacheRepositoryBase<UserEntity, Long> {

    @Override
    public PanacheQuery<UserEntity> find(String query, Map<String, Object> params) {
        return find(query, Sort.ascending("name"), params);
    }
}
```

All the tests will pass now. 

Moreover, I've checked the Quarkus REST Data with Panache extension documentation and this way of overriding the default sort configuration is not supported, so I'm closing this issue. Though, I think this is a nice thing to add (to be included in the `@ResourceProperties` or in the `@MethodProperties` annotations.

I hope it helped you out!
