### ISSUE TITLE
@QuarkusTest fails to load MyFaces injections that Quarkus app loads fine

### ISSUE THREAD

**Issue by quarkusGorilla** [quarkusio/quarkus#29421]
### Describe the bug

We use Quarkus and Primefaces.  

Some of our objects are created with @ViewScoped which is a Myfaces construct.   This requires us to use the myfaces-quarkus extension.  While running in dev mode and deploying the application as normal, everything works fine.  

We just started to try using @QuarkusTest instead of mocking so much.  We want to inject our beans in to our tests just as they are in our application.  Everything was going smooth until we tried to inject an @Viewscoped bean.  

Either it is a bug or I need to do something special with our @QuarkusTests unit tests to get the CDI to recognize @Viewscoped beans during the Surefire testing phase.  

Thank you so much for your help.

### Expected behavior

Myfaces @Viewscoped beans are recognized by the Quarkus CDI in tests annotated with @QuarkusTest during Surefire Testing phase.  This assumes the use of org.apache.myfaces.core.extensions.quarkus::myfaces-quarkus is being used.  For reference, we use the version 2.3-next-M7

### Actual behavior

@Viewscoped beans are recognized by Quarkus during dev mode and while the application is running, but not during testings with tests annotated with @QuarkusTest.   ContextNotActive is the issue with anything injected that is @Viewscoped.

### Output of `java -version`

18.0.2

### Quarkus version or git rev

2.7.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven

**Comment by manovotn** [comment]
> Either it is a bug or I need to do something special with our @QuarkusTests unit tests to get the CDI to recognize @Viewscoped beans during the Surefire testing phase.

This won't be a bug simply because `@ViewScoped` is a so-called custom CDI scope - Arc/Quarkus has no control over how and when to activate and deactivate this scope. This is also true for any other custom scope such as `@Transactional`.

Now, I don't really know how this scope works in terms of activation, but I am going to assume it is not always active (as for instance app context) and therefore the test needs something to activate it. You could subclass the Quarkus JUnit extension class to add the functionality, or you could just add something like a `beforeAll` method and do it there.
Take what I am saying with a pinch of salt though because, like I said, I am not familiar with this scope in particular :)

**Comment by manovotn** [comment]
@quarkusGorilla Actually, you might be interested in how request context is activated for those tests and mimic the same approach.

See [`ArcTestRequestScopeProvider`](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcTestRequestScopeProvider.java) which implements a `TestScopeSetup` interface. All of these are loaded via service loader mechanism ([here](https://github.com/quarkusio/quarkus/blob/main/test-framework/common/src/main/java/io/quarkus/test/common/TestScopeManager.java)) and used as a setup for testing.
If you can provide your own impl for view scoped context, it should start working for you.

**Comment by geoand** [comment]
Closing this as answered
