### ISSUE TITLE
Basic Auth HowTo and Tutorial content is identical 

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#29472]
### Describe the bug

At the moment, https://quarkus.io/version/main/guides/security-enabling-basic-auth-howto and https://quarkus.io/version/main/guides/security-enabling-basic-auth-tutorial have an identical content, giving a brief into to Basic Auth and linking to a Getting Started doc where Basic Auth is shown alongside Security JPA.

As far as I understand, in https://quarkus.io/version/main/guides/security-enabling-basic-auth-howto, we can give a really simple , more complete, example - basic auth is enabled and the users and roles are configured in `application.properties` ?

CC @michelle-purcell. Michelle if you agree I can prototype a PR for you to review ?

**Comment by michelle-purcell** [comment]
@sberyozkin - Bug #29472 (the duplication bit) is fixed in the PR https://github.com/quarkusio/quarkus/pull/29418, whereby the enhanced security-getting-started.adoc is migrated into diataxis as security-basic-authentication-tutorial.adoc.

When that gets merged, you are 100% correct, `security-enabling-basic-auth-howto.adoc` which btw, I renamed to `security-basic-authentication-howto.adoc` duplicates what's in the tutorial. +1 to your enhancement suggestion above :arrow_up: .  

I also wondered whether this topic (or another specific how-to_ could be included (`::include`) in the tutorial to single-source content? That might be for later. 

I'd be happy to review your prototype. Thanks :+1:

**Comment by sberyozkin** [comment]
@michelle-purcell, sure, I'll prototype some simple text for `security-basic-authentication-howto.adoc` a little bit later, thanks
