### ISSUE TITLE
ElasticsearchDevServicesBuildTimeConfig uses elasticsearch:7.17.0, newer versions are available

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#29523]
### Describe the bug

ElasticsearchDevServicesBuildTimeConfig uses elasticsearch:7.17.0, newer versions are available

https://github.com/quarkusio/quarkus/blame/main/extensions/elasticsearch-rest-client-common/deployment/src/main/java/io/quarkus/elasticsearch/restclient/common/deployment/ElasticsearchDevServicesBuildTimeConfig.java#L32

https://hub.docker.com/_/elasticsearch - `8.5.1` and `7.17.7` are available

**Comment by yrodiere** [comment]
The high-level Elasticsearch client currently bundled with Quarkus only supports ES 7, and we can't upgrade to a new version of *that* client because it's no longer open-source.

So, unfortunately, we might need to wait until #22622 is merged, because it introduces the replacement client which should officially support ES 8. That would mean waiting until Quarkus 3 (see PR for reasons).

I'm open to suggestions, but since the present issue is only about changing a default that can be overridden by users anyway, I think it's not worth taking too much risks (like trying to make the old high-level Elasticsearch client work with ES 8).

**Comment by rsvoboda** [comment]
ok, let's wait for https://github.com/quarkusio/quarkus/pull/22622
