### ISSUE TITLE
Add quarkus property to set the hibernate flushmode

### ISSUE THREAD

**Issue by slimequartz** [quarkusio/quarkus#29604]
### Description

By default, the hibernate flushmode is set to AUTO.
It would be beneficial to have a quarkus property to set the hibernate flushmode to other flushmodes e.g. COMMIT in case you don't want the default flushmode. 

### Implementation ideas

The name of the property could be _quarkus.hibernate-orm.flushmode_.

**Comment by rafmcpaf** [comment]
Great idea

**Comment by Parthib314** [comment]
Is this issue closed?

**Comment by Sanne** [comment]
It's not closed - but I admit I missed it.

I'm not sure it's a good idea - changing the flush mode has fundamental implications on the semantics: when not in auto-mode, actual code using Hibernate needs to be different.

This implies that other components and extensions which are depending on Hibernate ORM might break as they assume the standard flushmode is being used; one might say "well that's your choice" but such other components might have critical implications, which implies we'd need them to be tested in multiple modes.

Could someone elaborate on why you'd need this as a configuration property rather than setting your preference on the specific `Session` in which you need it?  I would recommend that, as the implications would be a more explicit opt-in and have impact only that particular session, so unlikely to have unintended sideeffects.

**Comment by Sanne** [comment]
BTW the relevant property can already be set by using the [quarkus.hibernate-orm.unsupported-properties](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key)
, so the doubt here is about this being worth it to be promoted as a supporter property and more prominently visible in the documentation.

**Comment by Parthib314** [comment]
@Sanne  Can you please explain this issue & what I have to do about it so that I can resolve it? What's better to learn quarkus than a "Good First Issue".

**Comment by yrodiere** [comment]
@Parthib314 It's probably not a good first issue after all, because we're not even sure we want to fix it ;) Besides, someone already sent a pull request. I removed the label.

**Comment by Parthib314** [comment]
Then I should find another issue to work on

**Comment by Sanne** [comment]
@slimequartz or @rafmcpaf : do you have a specific need for this, and in that case could you elaborate on the use case please?

If not, that's totally fine too: we will close this issue and possibly even remove the configuration property from Hibernate ORM.

**Comment by slimequartz** [comment]
Such a configuration property would be more convenient to use (and more visible) than setting the flushmode in the EntityManager (which I do now).
I also remember trying to use [quarkus.hibernate-orm.unsupported-properties](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.unsupported-properties-full-property-key) for this, but it didn't seem to be picked up.

**Comment by Sanne** [comment]
@slimequartz but I'd like to know what's your use case, please?

**Comment by slimequartz** [comment]
We had to override the default flushmode to fix the following error we had: 
_org.hibernate.TransientObjectException: object references an unsaved transient instance - save the transient instance before flushing_

**Comment by Sanne** [comment]
Ok, thanks for replying. That sounds like you had a different design issue and are using this property only as a workaround - I'd not recommend that.
