### ISSUE TITLE
@TestTransaction and inheritance - only works if the superclass is in the same package

### ISSUE THREAD

**Issue by josephearl** [quarkusio/quarkus#29710]
### Describe the bug

I have a base test class :

```java
package a.b;

public abstract class FooTestBase {
  protected abstract Foo getFoo();

  @Test
  void test() {
    // do some tests with getFoo
  }
}
```

And a test that in inherits it:

```java
package a.b;

@QuarkusTest
@TestTransaction
class FooTest extends FooTestBase {
  @Override
  protected Foo getFoo() {
    // return a Foo that needs a transaction
  }
}
```

This works.

However if I move `FooTest` to package `a.c`, the test then fails with:

`javax.persistence.TransactionRequiredException: Transaction is not active, consider adding @Transactional to your method to automatically activate one.`

### Expected behavior

Package structure does not affect whether a test transaction is created

### Output of `uname -a` or `ver`

Darwin MacBook-Pro 22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:54 PDT 2022; root:xnu-8792.41.9~2/RELEASE_X86_64 x86_64

### Output of `java -version`

openjdk version "17.0.5" 2022-10-18 OpenJDK Runtime Environment Temurin-17.0.5+8 (build 17.0.5+8) OpenJDK 64-Bit Server VM Temurin-17.0.5+8 (build 17.0.5+8, mixed mode, sharing)

### Quarkus version or git rev

2.14.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.6

**Comment by geoand** [comment]
cc @mkouba

**Comment by mkouba** [comment]
So the problem is that even if we add a generated `test()` method to the intercepted subclass (class that extends `FooTest` and handles associated interceptors; including the one for `@TestTransaction`) the `QuarkusTestExtension` attempts to execute the `FooTestBase#test()` method; which makes sense because `FooTestBase#test()` cannot be overriden by the `FooTest`. As a result the interceptors are not used and a new transaction is not started.

Anyway, even [JUnit docs](https://junit.org/junit5/docs/current/user-guide/#writing-tests-classes-and-methods) state that: _"It is generally recommended to omit the public modifier for test classes, test methods, and lifecycle methods unless there is a technical reason for doing so – **for example, when a test class is extended by a test class in another package**."_ So I'd recommend to use `public` test classes and methods instead.

It would be interesting to see if/how Weld (former CDI RI) handles this use case. CC @manovotn

**Comment by josephearl** [comment]
Thanks, will try making the test method public and see what happens

**Comment by manovotn** [comment]
> It would be interesting to see if/how Weld (former CDI RI) handles this use case. CC @manovotn

IIUIC, the issue here is because we invoke the JUnit method - this doesn't happen in Weld (test methods aren't intercepted).
As such, you basically don't get into this situation because from a class inside package `a.c`, you cannot invoke `FooTestBase#test` since that method is package private.

**Comment by mkouba** [comment]
> > It would be interesting to see if/how Weld (former CDI RI) handles this use case. CC @manovotn
> 
> IIUIC, the issue here is because we invoke the JUnit method - this doesn't happen in Weld (test methods aren't intercepted). As such, you basically don't get into this situation because from a class inside package `a.c`, you cannot invoke `FooTestBase#test` since that method is package private.

Yes, you're right. You would have to invoke the method via reflection.

**Comment by manovotn** [comment]
> Yes, you're right. You would have to invoke the method via reflection.

Yes. I am aware of that but I wouldn't consider that a standard use case scenario.
BTW if you try that, Weld doesn't intercept it either.

**Comment by josephearl** [comment]
Thanks @mkouba it works when the test methods in the base class are public, so think we can close this
