### ISSUE TITLE
OpenTelemetry JDBC instrumentation stops working after dev mode reload

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#29849]
### Describe the bug

#29645 fixed instrumentation of REST endpoints in 2.15.0, but it seems [JDBC instrumentation](https://quarkus.io/guides/opentelemetry#jdbc) is now broken after dev mode reload.

### Expected behavior

JDBC spans are shown in Jaeger after dev mode reload just as they were shown before

### Actual behavior

No JDBC spans after dev mode reload

### How to Reproduce?

[hibernate-orm-quickstart.zip](https://github.com/quarkusio/quarkus/files/10222684/hibernate-orm-quickstart.zip) (hibernate-orm-quickstart with additional OTEL config and disabled query caching)

1. `docker compose up -d`
2. `mvn quarkus:dev`
3. http://localhost:8080/fruits
4. check console: SQL statement is logged
5. check jaeger (http://localhost:16686): operation `/fruits` has 2 spans, one being a `SELECT` span
6. call `/fruits` one more time and check again
7. hit `s` in dev mode to trigger a restart
8. http://localhost:8080/fruits
9. check console: SQL statement is logged
10. check jaeger: latest operation `/fruits` has only 1 span, `SELECT` span is missing
11. _(edited) call `/fruits` one more time and check again, still nothing_

### Quarkus version or git rev

2.15.0

**Comment by brunobat** [comment]
@famod can you please do the request twice after the reload?
Reload of Otel tracing ,in general, was not working before this PR: https://github.com/quarkusio/quarkus/pull/28792.
However it has a known issue that is tricky to solve now. The first trace after the reload will be lost. 
However, if you do the request again, you should see it.

**Comment by famod** [comment]
> @famod can you please do the request twice after the reload?

I'm sure I did that already.

> Reload of Otel tracing ,in general, was not working before this PR: #28792.

The reproducer is using 999-SNAPSHOT, so that's covered. My app is using 2.15.0 (which also includes that fix).

> The first trace after the reload will be lost. However, if you do the request again, you should see it.

Doesn't make a difference, unfortunately. I just re-tested this with the reproducer.

**Comment by famod** [comment]
Hey @brunobat, did you already have a chance to take a look?

**Comment by brunobat** [comment]
@famod I wonder if you could try your issue in main.
This PR introduced important changes to that part: https://github.com/quarkusio/quarkus/pull/28921

**Comment by famod** [comment]
@brunobat the problem still persists, unfortunately.

**Comment by brunobat** [comment]
Thanks for checking.

**Comment by radcortez** [comment]
The issue is that the driver initializes the jdbc `Instrumenter` in a static block with the current OTel instance. The OTel instance is also reloaded on a dev reload, but the jdbc driver keeps the reference to the previous OTel instance, so it stops working: https://github.com/open-telemetry/opentelemetry-java-instrumentation/blob/main/instrumentation/jdbc/library/src/main/java/io/opentelemetry/instrumentation/jdbc/internal/JdbcSingletons.java

I don't think there is an easy way to fix this. I don't see an opening on the API for that, or we would have to override a lot of stuff.

The best option is to raise an issue in the OTel repo and propose an API that allows us to reset (or change) the OTel instance in the jdbc driver.

**Comment by brunobat** [comment]
Created bug on the OTel side

**Comment by brunobat** [comment]
Otel 1.23 has introduced changes on this jdbc instrumentation.
Checking now along with other upgrades.

**Comment by brunobat** [comment]
Took a look at this, after the OTel extension re-write and with Quarkus 3.
The JDBC spans now show up correctly, however, there's a catch...

On the first REST request, the one triggering the reload, there is a known issue that will hide the trace. This happens because of the request starts with the old OTel SDK and ends with the new one. 

Also, upon reload, you also see several traces related with connections and DB provisioning:

![Image](https://user-images.githubusercontent.com/2318030/236275795-f90279cd-49fd-4e83-8ea0-8223894fd9d2.png)

@famod Can we close this issue?

**Comment by famod** [comment]
Sounds good, thanks!

I haven't migrated to Q3 yet but when I do I'll check again and everything should be fine.

**Comment by brunobat** [comment]
Sorry, this message got buried. Yes, It's available on 3.0.0.Final and above.
The new activation instructions are here: https://quarkus.io/guides/opentelemetry#jdbc
