### ISSUE TITLE
[Extension Proposal] digma-quarkus-opentelemetry

### ISSUE THREAD

**Issue by arik-dig** [quarkusio/quarkus#29864]
### Description

[digma.ai](http://digma.ai) wants to extend the existing [quarkus-opentelemetry](https://github.com/quarkusio/quarkus/tree/main/extensions/opentelemetry) ,
mainly by adding span attributes for the web controller - and its mapped method (and class).
see [OTEL Semantic conventions for Source Code attributes](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/semantic_conventions/span-general.md#source-code-attributes)

Interested in this extension, please +1 via the emoji/reaction feature of GitHub (top right).

### Repository name

digma-quarkus-opentelemetry

### Short description

add span attributes of code.function and code.namespace

### Repository Homepage URL

https://quarkiverse.github.io/quarkiverse-docs/digma-quarkus-opentelemetry/dev/

### Repository Topics

- quarkus-extension
- opentelemetry

### Team Members

- @arik-dig
- @doppleware

### GitHub Applications?

- [ ] [Stale](https://github.com/marketplace/stale) - Automatically close stale Issues and Pull Requests that tend to accumulate during a project

**Comment by maxandersen** [comment]
interesting, but does this require a separate extension to add those items? /cc @brunobat 

On the repo then the recommended naming convention is `quarkus-digma-opentelmetry`

**Comment by radcortez** [comment]
It shouldn't require a separate extension. Our strategy with OTel is to put everything in one extension because it would be tricky for the user to know which extensions to add for OTel to work correctly. 

I would oppose it if this were a feature outside the OTel specification, but it is part of the OTel spec. I think we should be able to add the span attributes to some of the span instrumenters. Getting the executing method / classname for REST is possible. Not sure about other components.

**Comment by arik-dig** [comment]
@radcortez , if that is the case I will create a Pull request on the main project on the original extension. ok?

**Comment by radcortez** [comment]
Sure, please go ahead.

**Comment by gastaldi** [comment]
Thanks for clarifying this. Closing this issue now
