### ISSUE TITLE
Restricting X-Forwarded-* header parsing

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#29888]
### Discussed in https://github.com/quarkusio/quarkus/discussions/29887

<div type='discussions-op-text'>

<sup>Originally posted by **Doctor-love** December 15, 2022</sup>
Hi y'all,

Is it possible in Quarkus to restrict from which IP addresses the X-Forwarded-*  headers are parsed/trusted?
A similar option exist in nginx called ["set_real_ip_from"](https://nginx.org/en/docs/http/ngx_http_realip_module.html#set_real_ip_from).  
  
My use-case is exposing a distributed application both via a load balancer and direct connections, but for traceability I don't want to enable trivial spoofing of source IP addresses. Something like "_quarkus.http.proxy.allow-forwarded-from=ip.address.of.loadbalancer_" would be useful.</div>

**Comment by sberyozkin** [comment]
@michalvavrik Have a look please if it can be of interest when time allows

**Comment by michalvavrik** [comment]
@sberyozkin yes, it's interesting, thank you for pinging me. I've this week packed already, I'll look later this month.

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, post Christmas/New Year will be fine as well :-)

**Comment by Doctor-love** [comment]
Thanks @sberyozkin and @michalvavrik for the quick response - I'm not a Java developer but I'll keep watch on this issue so that I can at least help with security testing of the feature.

**Comment by sberyozkin** [comment]
@Doctor-love Can you please test #30084 and provide the feedback ?

**Comment by michalvavrik** [comment]
@sberyozkin here https://github.com/quarkusio/quarkus/pull/30084#issuecomment-1370377492 is suggestion to provide same option for `Forwarded`. I think we can implement it, but I don't know why users can't use `X-Forwarded` if they need such restriction. Your thoughts, please?

cc @Doctor-love

**Comment by Doctor-love** [comment]
For my use-case it doesn't really matter, as I'm fine with just using XFF. I think most reverse proxies/load balancers supports supplying the information using both methods (XFF and the "Forwarded" header).

The main reason a made the comment was because this seems (from a pure user perspective, no idea how it's technically implemented) like an unnecessary inconsistency - I can't see a use-case where you'd want to restrict one method and not the other. Likewise I don't see why'd you want different source restrictions from proxies using different methods (even though it's a bad idea to have XFF and "Forwarded" parsing enabled at the same time as the Quarkus warning mentions), so providing a single option which restricts all types of proxy information headers seems like a simpler ans safer way to do this.

As I said, the current solution is fine by me and I don't wanna be nitpicky - thanks for your work, guys!
