### ISSUE TITLE
Registration for reflection with unsafeAllocated

### ISSUE THREAD

**Issue by ppalaga** [quarkusio/quarkus#29922]
### Description

Follows up https://github.com/apache/camel-quarkus/issues/4284#issuecomment-1354604958 where Mandrel hits us registering a class for reflection with `unsafeAllocated=true` which is currently not possible using Quarkus BuildItems.

See also https://www.graalvm.org/22.2/reference-manual/native-image/metadata/#specifying-reflection-metadata-in-json

### Implementation ideas

`ReflectiveClassBuildItem` (and perhaps other build items handling reflection registrations) should get a support for this.

**Comment by ppalaga** [comment]
One more report, this time in Quarkiverse CXF, where Mandrel wants us to use `unsafeAllocated=true` but there is still no way to do that in Quarkus: https://github.com/quarkiverse/quarkus-cxf/issues/695

**Comment by zakkak** [comment]
I suggest we handle this after merging https://github.com/quarkusio/quarkus/pull/29886, since without it we will need to [use non public API](https://github.com/oracle/graal/blob/ff8623b78afafc24c35556d0cc6399d49cf644de/sdk/src/org.graalvm.nativeimage/src/org/graalvm/nativeimage/impl/ReflectionRegistry.java#L52).
