### ISSUE TITLE
Set quarkus-cache properties at runtime

### ISSUE THREAD

**Issue by mikethecalamity** [quarkusio/quarkus#29934]
### Description

The properties for the `quarkus-cache` extension look like they should be settable at runtime. At the very least: `enabled`, `initial-capacity`, `maximum-size`, `expire-after-write`, `expire-after-access`.

**Comment by geoand** [comment]
@gwenneg I'll let you decide whether you want to keep this or https://github.com/quarkusio/quarkus/issues/28966 open.
There is no reason to have both issues around

**Comment by gwenneg** [comment]
This issue covers more config keys so I'm closing the other one.

**Comment by gwenneg** [comment]
@ben-manes I see that [Policy](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.html) can be used to change `maximum-size`, `expire-after-write`, `expire-after-access` at run time. Is it possible to change the `initial-capacity` as well?

**Comment by gwenneg** [comment]
There are at least two approaches to make _some_ of the config values overridable at run time:

1. Changing the config phase of these values, which are currently declared in [CacheConfig](https://github.com/quarkusio/quarkus/blob/main/extensions/cache/deployment/src/main/java/io/quarkus/cache/deployment/CacheConfig.java), from `BUILD_TIME` to `RUN_TIME`. This isn't as easy as it sounds though because cache instances are constructed at build time using recorded bytecode which is eventually run from a static initializer.

2. Taking advantage of Caffeine's [Policy](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.html) which could be used from new [CaffeineCache](https://github.com/quarkusio/quarkus/blob/main/extensions/cache/runtime/src/main/java/io/quarkus/cache/CaffeineCache.java) methods to override `maximum-size`, `expire-after-write`, `expire-after-access`. For instance, `CaffeineCache#setMaximumSize` could be called at any time (application startup or later) to change the max size of a cache. This could be added to the dev console by the extension, but also exposed through a REST API (or any other mean) by the Quarkus users if relevant.

I am exploring a bit these two approaches. Feel free to suggest a third idea 😃

**Comment by gwenneg** [comment]
I've submitted a PR for option #1. I'm also preparing another PR for option #2 which is much simpler to implement.

**Comment by gwenneg** [comment]
#30000 and #30005 should hopefully cover everything you need @mikethecalamity and @Jojal.

**Comment by gwenneg** [comment]
The `quarkus-cache` config will be settable at run time starting Quarkus `2.16.0`. It will also be possible to change some of the cache config values in real time with the programmatic API. [Here's a preview of the cache doc](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/cache.adoc#changing-the-expiration-policy-or-the-maximum-size-of-a-caffeinecache-in-real-time) from 2.16 that explains how to do that.

Please let me know (with a new Quarkus issue) if anything's missing after that.
