### ISSUE TITLE
Missing First Kafka messages from Quarkus Tests on every new container.

### ISSUE THREAD

**Issue by Eli-Ronai** [quarkusio/quarkus#29966]
### Describe the bug

When I create a completely new docker container with docker-compose down / docker-compose up:
 -- confluentinc/cp-zookeeper:latest
 -- confluentinc/cp-server:latest
 
 The first time I run a @Test that publishes a batch of messages and recieves them, the messages do not appear in the @Incoming annotated method. Re-running the test again once the state is 'primed' will not produce the same failure. 
 
The consumer of the messages is an @ApplicationScoped object outside of the @QuarkusTest class that prints out the message  as it recieves them to termial and then pushes them into a BlockingQue.

Hypothisis: Something about the quarkus lazy loading behavior is causing the @Injected consumer to be improperly initialized at boot time allowing it to acknowlege messages to Kafka without them hitting the @Incoming(channel). Only after the first batch of messages is missed, does the new Kafka create the _consumer offsets directory and finish setting itself up.

Basically, I think that due to the lazy loading until we hit blockingQue.take(), that resource isn't initialized and the consumer is providing false acknowledgements to the kafka consumer offset. 

### Expected behavior

Expected: All messages acknowleged in Kafka are recieved by @Incoming method.

### Actual behavior

Actual Behavior: Messages are ack'ed from Kafka but do not appear in @Incoming method.

### How to Reproduce?

1. Clone https://github.com/Eli-Ronai/QuarkusKafkaBugDemo.git

2. MVN clean install.

3. RestartDocker.bat (or use docker-compose up in terminal.)

4. Run BufferTests.Java, first test fails.

5. Run BufferTests.Java again, test now passes.

-----

Reproduction of the bug requires the recreation of the docker container each time. Stopping and starting the container does not reproduce the bug. You must completely destroy the container and rerun docker-compose up.

### Output of `java -version`

java version "17" 2021-09-14 LTS Java(TM) SE Runtime Environment (build 17+35-LTS-2724) Java HotSpot(TM) 64-Bit Server VM (build 17+35-LTS-2724, mixed mode, sharing)

### Quarkus version or git rev

2.13.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.8.6

**Comment by ozangunalp** [comment]
If you set `mp.messaging.incoming.TestChannel1.auto.offset.reset=earliest` (or `kafka.auto.offset.reset=earliest` globally) in your tests it should be fine. 
The default value for `auto.offset.reset` is `latest`. With that, a Kafka consumer will start consuming assigned partitions from the log end offset. When you start your application, by the time the kafka consumer is up and polling, your emitter has already produced messages which the consumer will miss because of `auto.offset.reset=latest`.

**Comment by Eli-Ronai** [comment]
> If you set `mp.messaging.incoming.TestChannel1.auto.offset.reset=earliest` (or `kafka.auto.offset.reset=earliest` globally) in your tests it should be fine. The default value for `auto.offset.reset` is `latest`. With that, a Kafka consumer will start consuming assigned partitions from the log end offset. When you start your application, by the time the kafka consumer is up and polling, your emitter has already produced messages which the consumer will miss because of `auto.offset.reset=latest`.
> 
> And also, if there is already a committed offset on a partition for the consumer group, the newly joined consumer will continue consuming from the last committed offset, not the earliest or latest configured in `auto.offset.reset`.

Thanks, this solves the issue. Could you explain why in the above example the messages were published before the @ApplicationScoped listener was being created? I would think that due to it being application scoped, it would be created at initialization - before "testId=a".

**Comment by ozangunalp** [comment]
No this is not a bandaid fix, it is intentional that we keep the Kafka consumer default value for `auto.offset.reset`.

The Kafka consumer is created at initialization and `@Incoming` reactive stream will be subscribed to at initialization. But everything else is asynchronous. So by the time the Kafka consumer is assigned partitions, fetches positions for those partitions, resets positions to the offset and starts fetching records, it is very probable that your other thread publishes records to the topic.

**Comment by cescoffier** [comment]
See comment - expected behavior.
