### ISSUE TITLE
smallrye-reactive-messaging: incompatibility with configuration through environment variables

### ISSUE THREAD

**Issue by mederel** [quarkusio/quarkus#30106]
### Describe the bug

This issue was discovered while using the smallrye-reactive-messaging-kafka Quarkus extension with their QuarkusIntegrationTest annotation test with some configuration overrides. But it besically boils down to an issue of smallrye-reactive-messaging-provider to extract the different channel names from the smallrye-config root object.

Imagine a words-in channel is defined with @incoming. We then want for an override of one of its properties with an environment variable. Example: MP_MESSAGING_INCOMING_WORDS_IN_RETRIES=1. That breaks the initialization of the provider package, because it interprets the environment variable as being a in.retries property for the words channel.

### Expected behavior

The Quarkus application starts normally.

### Actual behavior

```
java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `words`
        at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$0(ConnectorConfig.java:50)
        at java.base/java.util.Optional.orElseThrow(Optional.java:403)
        at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.lambda$new$1(ConnectorConfig.java:50)
        at java.base/java.util.Optional.orElseGet(Optional.java:364)
        at io.smallrye.reactive.messaging.providers.impl.ConnectorConfig.<init>(ConnectorConfig.java:49)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.lambda$extractConfigurationFor$0(ConfiguredChannelFactory.java:86)
        at java.base/java.lang.Iterable.forEach(Iterable.java:75)
        at io.smallrye.reactive.messaging.providers.impl.ConfiguredChannelFactory.extractConfigurationFor(ConfiguredChannelFactory.java:75)
```

### How to Reproduce?

I have prepared a reproducer (using Quarkus): [bug-smallrye-kafka-integration-config-override-2.zip](https://github.com/smallrye/smallrye-reactive-messaging/files/10247915/bug-smallrye-kafka-integration-config-override-2.zip)

Modus operandi:

1. get the zip and unzip
1. run mvn clean install inside
1. run MP_MESSAGING_INCOMING_WORDS_IN_RETRIES=1 java -jar target/quarkus-app/quarkus-run.jar and see the stacktrace

### Output of `uname -a` or `ver`

5.15.0-56-generic

### Output of `java -version`

Java version: 11.0.17, vendor: GraalVM Community

### Quarkus version or git rev

2.15.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.6

### Additional information

I have already opened [an issue upstream](https://github.com/smallrye/smallrye-reactive-messaging/issues/2028), and tried to fix it, but it is not trivial, so I am proposing a fix in the Quarkus extension instead.

**Comment by rquinio1A** [comment]
As I understand from PR discussion, the current generic workaround in smallrye-config is to define at build time properties that _may_ later be set at runtime via an environement variable:

```
mp.messaging.incoming.words-in.fetch.min.bytes=1
mp.messaging.incoming.words-in.health-enabled=true
mp.messaging.incoming.words-in.partitions=1
mp.messaging.incoming.words-in.poll-timeout=1000
mp.messaging.incoming.words-in.retries=1
mp.messaging.incoming.words-in.retry-attempts=-1
(...)
```

If the property is not listed at build time, it won't work.
But it's not very practical because microprofile-reactive-messaging-kafka has *a lot* of runtime properties.
I know the smallrye-config code is already quite complex, so I think for production mode that's one more reason to pass runtime configuration via ConfigMaps and `quarkus.config.locations`, given that:

- env variable case is more error prone than properties or YAML format
- some passthrough properties cannot be overridden via env anyway, since they are not known by smallrye-config (cf quarkus.kafka-streams.* properties that are passed 'as-is' to kafka).

The problem @mederel has is in the context of `@QuarkusIntegrationTest` which passes any config override to the containerized app via environement variables.
Maybe `@QuarkusIntegrationTest` could use another mechanism to pass the overrides ? Maybe via system properties via container entrypoint args maybe ?

**Comment by martaisty** [comment]
Funny you should mention this, @mederel. I've faced the same problem. I'm not sure that it is connected with Kafka. I'm using `JMS` connector and have the same issue.

I have two channels: incoming (`hello`) and outgoing (`hello-world`). And I'd like to override `destination` property via environment variables. So I have these build time properties:
* `mp.messaging.incoming.hello.destination: ''`
* `mp.messaging.outgoing.hello-world.destination: ''`

However, environment variable `_DEV_MP_MESSAGING_OUTGOING_HELLO_WORLD_DESTINATION` (notice prefix `_DEV` for `%dev` profile) is converted to `mp.messaging.outgoing.hello.world.destination`. Therefore I get an error:
```
2023-04-11 18:17:29,731 ERROR [io.qua.run.Application] (Quarkus Main Thread) Failed to start application (with profile [dev]): java.lang.IllegalArgumentException: SRMSG00071: Invalid channel configuration -  the `connector` attribute must be set for channel `hello`
```

I ended up removing prefix `_DEV` from environment variable `_DEV_MP_MESSAGING_OUTGOING_HELLO_WORLD_DESTINATION` -> `MP_MESSAGING_OUTGOING_HELLO_WORLD_DESTINATION` and it worked because I have build time property ` mp.messaging.outgoing.hello-world.destination: ''`. Thank you @rquinio1A for a workaround 👍 . Probably, the best way would be to give up environment variables as a way for configuration [because](https://smallrye.io/smallrye-config/3.2.1/config/environment-variables/):

> Environment Variables format cannot represent the entire spectrum of common property names.

**Comment by cescoffier** [comment]
@radcortez does the latest change in Config improve this issue?

**Comment by radcortez** [comment]
This is not an issue but a limitation of how environment variables are represented:
https://smallrye.io/smallrye-config/3.3.4/config/environment-variables/

When you have dynamic names like `hello-world`as part of the key, notice that both keys:

`mp.messaging.outgoing.hello.world.destination`
`mp.messaging.outgoing.hello-world.destination`

Have the same env variable representation, following MP Config conversion rules (https://download.eclipse.org/microprofile/microprofile-config-3.0/microprofile-config-spec-3.0.html#default_configsources.env.mapping):

`MP_MESSAGING_OUTGOING_HELLO_WORLD_DESTINATION`

If such configuration is expressed only as an environment variable, there is no way for the Config system to know if `HELLO_WORLD` is `hello.world` or `hello-world` (it assumes the dot because it is the most likely character). For that reason, adding an empty property in the expected format in any source, helps the Config system disambiguate such cases  and map the name correctly.

If anyone has better ideas on how to handle this, I'm all ears.
