### ISSUE TITLE
Add library version to exception logging

### ISSUE THREAD

**Issue by ennishol** [quarkusio/quarkus#30228]
### Description

Would be nice to have a library version in exception logging as shown in the tweet of @gunnarmorling 
![tweet](https://user-images.githubusercontent.com/64908285/211041718-374568b0-95dd-4b21-8c3c-b0cfd360d6e6.jpeg)

log4j2 does that automatically. (can be added "%xThrowable{full}")
https://twitter.com/gunnarmorling/status/1610738090699522071?t=bQeVfwCJwzoT2JLCVgoMBA&s=19

**Comment by geoand** [comment]
@jamezp @dmlloyd does JBoss Logging provide something like this?

**Comment by dmlloyd** [comment]
Yes JBoss LogManager does have this formatting method, or rather, it _did_. As of Java 9 however the functionality was removed for the following reasons:

* It is not 100% reliable, since it relies on essentially guessing the class loader of a given stack frame.
* It uses code source, which isn't guaranteed to be reliable.
* Any modern Java 9-aware framework was expected to use a separate, named class loader for each artifact (like JBoss Modules) which includes the artifact ID and version, _or_ JMPS modules, or some mixture of the two, which would provide a much more reliable and readable stack frame for each class using just JDK APIs.

Of course, that last point didn't end up happening. But I would still argue that we should rethink this, especially since we, and our users, seem to encounter class loading glitches and/or confusion with some frequency as a result of many classes being available from multiple class loaders in several contexts.

**Comment by geoand** [comment]
Thanks a lot of the insights @dmlloyd. 

Just for my our curiosity, when can `CodeSource` not work? Asking because we use it here in Quarkus as well :)

**Comment by geoand** [comment]
> Of course, that last point didn't end up happening. But I would still argue that we should rethink this, especially since we, and our users, seem to encounter class loading glitches and/or confusion with some frequency as a result of many classes being available from multiple class loaders in several context

+1

**Comment by dmlloyd** [comment]
> Thanks a lot of the insights @dmlloyd.
> 
> Just for my our curiosity, when can `CodeSource` not work? Asking because we use it here in Quarkus as well :)

Some classes and class loaders will always give a `null` code source. There is nothing which requires it to be correct or consistent. And, since the code source is used to find the JAR manifest, it only works when the code source correctly points to the original JAR (this is the class loader's responsibility) _and_ the JAR contains the correct version information in its manifest (this is the artifact packager's responsibility). OTOH, if we supply a name to a class loader we can control it so that the name includes whatever information we deem relevant without having to probe the JAR files for each stack frame.

And of course once native image comes into play, there are no JAR files at all.

**Comment by geoand** [comment]
Gotcha, thanks 👍

**Comment by geoand** [comment]
Let's close this as `won't fix`
