### ISSUE TITLE
Inline Log category property doesn't work

### ISSUE THREAD

**Issue by pjgg** [quarkusio/quarkus#30275]
### Describe the bug

Quarkus 2.15.0.Final

I am trying to set `quarkus.log.category` property through an inline system property at start time (Quarkus Dev Mode)

`mvn quarkus:dev -Dquarkus.log.category."io.quarkus".level=WARN`  or 

```
mvn quarkus:dev -Dquarkus.log.category.\"io.quarkus\".level=WARN
```

But looks like the property is ignored. Works If I add the property to the application.property

This issue has an impact on the developer user experience

### Expected behavior

log level for `io.quarkus` package should be "warning". 

### Actual behavior

log level for `io.quarkus` is not changed 

### How to Reproduce?

```
quarkus create app org.acme:getting-started \
    --extension='resteasy-reactive'
```

```
cd getting-started
```

```
mvn quarkus:dev -Dquarkus.log.category."io.quarkus".level=WARN
```

Result:
```
2023-01-10 09:45:36,125 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.log.category.io.quarkus.level" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### Output of `uname -a` or `ver`

Linux fedora 6.0.16-300.fc37.x86_64

### Output of `java -version`

openjdk 17.0.5 2022-10-18

FYI: @llowinge

**Comment by radcortez** [comment]
I'll have a look

**Comment by radcortez** [comment]
> This will result in the proper logging configuration, but it will print a false positive about an unused property - @radcortez this part should probably be addressed

This is caused by the system properties being propagated by the DevMojo plugin. The parser code removes the quotes here:
https://github.com/quarkusio/quarkus/blob/8398d79f770b7f5b7e1cb6c90397072cafee6264/independent-projects/bootstrap/maven-resolver/src/main/java/io/quarkus/bootstrap/resolver/maven/options/BootstrapMavenOptions.java#L58

And set it up here:
https://github.com/quarkusio/quarkus/blob/25c96c3fd17caa890afeac936e4aaa7a18e0d285/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L1210

Results in the command line:
```console
[DEBUG] Launching JVM with command line: /Users/radcortez/.sdkman/candidates/java/11.0.14-tem/bin/java -Xverify:none -Dquarkus-internal.serialized-app-model.path=/Users/radcortez/Code/personal/quarkus-playground/services/number-api/target/quarkus/bootstrap/dev-app-model.dat -javaagent:/Users/radcortez/.m2/repository/io/quarkus/quarkus-class-change-agent/999-SNAPSHOT/quarkus-class-change-agent-999-SNAPSHOT.jar -Dhttps.protocols=TLSv1.1,TLSv1.2 -Dquarkus.log.category.io.quarkus.level=DEBUG -XX:TieredStopAtLevel=1 -agentlib:jdwp=transport=dt_socket,address=localhost:5005,server=y,suspend=n -Djava.util.logging.manager=org.jboss.logmanager.LogManager -jar /Users/radcortez/Code/personal/quarkus-playground/services/number-api/target/number-api-dev.jar
Listening for transport dt_socket at address: 5005
```

Without the quotes.

It ends up working because the properties are correctly propagated in https://github.com/quarkusio/quarkus/blob/ee14de75b5227632002f77dd3388d3b65d1ad9ff/core/deployment/src/main/java/io/quarkus/deployment/dev/DevModeMain.java#L68-L72

So we get one quoted property and an unquoted property in System properties, which causes the warning.

I wonder if we need to propagate the properties in the java process since the `DevModeContext` is already doing this. Maybe other cases require it.

@aloubyansky what do you think?

**Comment by aloubyansky** [comment]
Yes, it looks like there is an overlap.

**Comment by radcortez** [comment]
Are we ok to remove the plugin overlap and keep the `DevModeContext` one?

**Comment by aloubyansky** [comment]
I did that in my branch and it passed the CI. I guess so.

**Comment by aloubyansky** [comment]
Here is what I tested https://github.com/aloubyansky/quarkus/commit/611b3de655ece7561a069415c8438ec8c15ce224

**Comment by aloubyansky** [comment]
I wanted to add a test based on this report but it appears to be tricky the way our tests are launched. I guess I'll just open a PR, we do have tests for passing `-Dxxx` args.
