### ISSUE TITLE
Introduce `quarkus format` (or `quarkus fmt`)

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#30337]
### Description

Analogous to `go fmt`, it would be nice if the CLI had a command to automatically format the project sources by running `quarkus fmt`

### Implementation ideas

The command may invoke the [`mvn formatter:format`](https://code.revelc.net/formatter-maven-plugin/format-mojo.html) goal (if configured in the project) otherwise prompt to include it in the project and use the Quarkus IDE Config (`io.quarkus:quarkus-ide-config`) by default

**Comment by dvsingh9** [comment]
Most of the time formatting is specific to company. Companies creates their custom formatting rules, this may not add much value and if Quarkus is going to add it then it should be configurable.

**Comment by holly-cummins** [comment]
I think it needs to be consistent rules, to make sure everyone in a team gets the exact same stuff, without argument and with no option for configuration. In formatting, customisation is what causes pain. So invoking the formatter plugin would have a risk that someone customised it. Our rules seem like good rules to assume.

And then we need to make sure the IDE's formatter agrees with our view of the world, so that the IDE and CLI aren't fighting. That on its own would be worth the price of admission, actually, even if didn't do anything else. I keep tripping over that on projects - most recently I was getting release failures because of formatting mismatches between IDE and CLI.

**Comment by holly-cummins** [comment]
In particular, `go fmt` is not configurable. That's why it adds so much value - it's not the speed of invocation, it's the "you will never have to have a discussion about formatting conventions again." (See, for example, https://github.com/golang/go/issues/40028)

"It is an intentional design choice that there are no configuration options for gofmt. The benefit of eliminating bike shed discussion about formatting choices is considered to be more important than the cost of not permitting people to use their preferred style. The usual saying is that gofmt isn't anybody's preferred style, but it's adequate for everybody."

**Comment by holly-cummins** [comment]
... and if companies feel the position of braces justifies the cost of arguing about formatting rules, they can always not use the quarkus fmt command. The differentiator of this command would *have* to be that it's massively opinionated, because formatting code on its own is definitely not novel :) 

No one needs the cognitive another tool to remember, if it behaves exactly like the many tools already out there.

**Comment by gastaldi** [comment]
@holly-cummins that makes sense. I'll prototype something and see how that works out
