### ISSUE TITLE
AWT `io.quarkus.awt.it.ImageGeometryFontsIT` native integration test failing with "GraalVM for Java 20" dev builds

### ISSUE THREAD

**Issue by zakkak** [quarkusio/quarkus#30354]
### Describe the bug

$title

cc @Karm 

### Expected behavior

Tests should pass.

### Actual behavior

Test fails with:

```
[ERROR] Failures: 
[ERROR]   ImageGeometryFontsIT>ImageGeometryFontsTest.testGeometryAndFonts:89 TIFF: Wrong pixel at 80x56. Expected: [46,14,32,255] Actual: [194,59,132,255] ==> expected: <true> but was: <false>
[ERROR]   ImageGeometryFontsIT>ImageGeometryFontsTest.testGeometryAndFonts:89 GIF: Wrong pixel at 80x56. Expected: [2,0,0,0] Actual: [156,0,0,0] ==> expected: <true> but was: <false>
[ERROR]   ImageGeometryFontsIT>ImageGeometryFontsTest.testGeometryAndFonts:89 PNG: Wrong pixel at 80x56. Expected: [46,14,32,255] Actual: [194,59,132,255] ==> expected: <true> but was: <false>
[ERROR]   ImageGeometryFontsIT>ImageGeometryFontsTest.testGeometryAndFonts:89 JPG: Wrong pixel at 80x56. Expected: [73,0,44,0] Actual: [201,53,137,0] ==> expected: <true> but was: <false>
[ERROR]   ImageGeometryFontsIT>ImageGeometryFontsTest.testGeometryAndFonts:89 BMP: Wrong pixel at 80x56. Expected: [46,14,32,0] Actual: [194,59,132,0] ==> expected: <true> but was: <false>
```

See https://github.com/oracle/graal/actions/runs/3898752856/jobs/6658142635#step:9:487

### How to Reproduce?

1. Build GraalVM `master` using Java 20 EA
2. Set GRAALVM_HOME to `<graalvm-repo>/sdk/latest_graalvm_home`
3. ./mvnw -Dnative -pl integration-tests/awt -Dnative.surefire.skip -Dformat.skip -Dno-descriptor-tests -Dlog.level=ALL clean verify -Dquarkus.native.container-build=false

### Output of `uname -a` or `ver`

Linux 6.0.17-300.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Wed Jan 4 15:58:35 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### GraalVM version (if different from Java)

GraalVM for Java 20 - dev build based on 92cfa766d1f059561e6c6a5631d6b082fc9f7765

### Quarkus version or git rev

f1be907e9994569e1e321ebda596bf3e49ac4900

**Comment by zakkak** [comment]
@Karm may I assign this to you?

**Comment by Karm** [comment]
@zakkak Thx. I will take a look and fix it.

**Comment by Karm** [comment]
I'll turn to AWT on JDK 20 when I get this up and running: https://github.com/oracle/graal/pull/5751

**Comment by Karm** [comment]
@zakkak, so this is actually more sinister than something being rendered slightly differently.
It appears that https://github.com/quarkusio/quarkus/pull/30360 was actually related. We need to deal with fonts, otherwise we have this situation where we have no fonts support and most importantly, there is not a single error line in the log about it...

I will try to amend it.

## Mandrel 22.3.1.0-Final, JDK 17.0.6+10:
![test_image](https://user-images.githubusercontent.com/691097/214050458-43330bb6-40c1-4db0-927f-915c9f0abda2.PNG)

## Mandrel 23.0.0-devf01989ebb59a, JDK 20 (1c840506 January 19th)
![test_image](https://user-images.githubusercontent.com/691097/214050379-8bbe8f24-3834-47bd-92f6-39221ce98ad6.PNG)

**Comment by Karm** [comment]
The silent omission of rendering anything fonts related is present also with JDK 19, e.g. with 
```
GraalVM 23.0.0-dev Java 19.0.1+10-jvmci-23.0-b04 CE (Java Version 19.0.1+10-jvmci-23.0-b04)
```
So it's been there for a long time :disappointed:

**Comment by Karm** [comment]
I have a fix, just need to make it work on older JDKs too...
