### ISSUE TITLE
add a pagination interface to Panache

### ISSUE THREAD

**Issue by hmbig2** [quarkusio/quarkus#30385]
### Description

The Jakarta Data specification defines [a pagination interface,](https://github.com/jakartaee/data#pagination)
spring JPA has the same interface.

why didn't  Quarkus-panache implement this interface?

**Comment by mkouba** [comment]
`PanacheQuery` does support pagination: https://quarkus.io/guides/hibernate-orm-panache#paging

**Comment by geoand** [comment]
@gavinking what is our position WRT Jakarta Data?

**Comment by FroMage** [comment]
> why didn't Quarkus-panache implement this interface?

Because we don't implement Jakarta Data, because it's not released yet and Quarkus ORM with Panache is older than this and supports pagination already, as noted above :)

> what is our position WRT Jakarta Data?

I believe our position is to wait until later to implement it.

Let's close this issue, we'll open another one to implement Jakarta Data later when/if we intend to implement it.
