### ISSUE TITLE
Set default topic in Kafka Dev Services if no topic is configured

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#30551]
### Description

I have a demo where an OIDC secured REST endpoint publishes a Movie object to Kafka `movies-out` channel linked to the configured `movies` topic, and this Movie being consumed from the `movies` topic, linked to the `movies-in` channel, and then this Movie is saved in DB.
3 devservices containers are launched, Kafka, PostgresQL, and Keycloak, the application.properties is nearly empty, the only thing I have to configure is:
```
mp.messaging.incoming.movies-in.topic=movies
mp.messaging.outgoing.movies-out.topic=movies
```
No other Kafka, Hibernate, PostgreSql, or Keycloak properties have to be configured.

It would be awesome if it were not necessary to configure a Kafka topic in devmode, perhaps a default topic could be created in devmode if none is configured, ex, named as `dev-mode-topic`

**Comment by cescoffier** [comment]
It's a bit more tricky. 
It creates a topic with the channel name by default. In your example, it would create the `movies-in` and `movies-out` topics automatically. However, you often want to write and read to the same one (that's why you set `movies`). 

The spec is very strict about the channel names: they must be unique inside the application. So, you cannot have:
```
mp.messaging.incoming.movies.topic=movies
mp.messaging.outgoing.movies.topic=movies
```

I've tried to remove that constraint (in quarkus), but it's not without consequences. 

It shouldn't be a really issue outside of demos. Indeed, it's rare to have a single application reading and to write to the same topics. If your demo would have multiple applications, and all use `movies` as the channel name, you would have:

.application.properties of the first app
```
# nothing
```

.application.properties of the second app
```
# nothing
```

**Comment by sberyozkin** [comment]
Thanks for the explanation @cescoffier.
Sure, having the consumer in its own application makes sense.

I've been thinking that may be with Kafka DevServices config having a property like `defaultTopicName` might work, the docs would explain that in production, the channel name is used to set the topic name if the topic is not configured, while in devmode, this property can be used to override it, which would work; 
But then I realised that indeed, as you say, a single application won't do write to / read from the same topic in prod, so it is probably pointless to try to add such a property.

Making a demo to have 2 different applications is a better idea.

Please close this issue if you'd like, not sure if there is something else that can be considered
