### ISSUE TITLE
Build error quarkus-kubernetes-client with Quarkus >= 2.14

### ISSUE THREAD

**Issue by HiddenSplioGuy** [quarkusio/quarkus#30915]
### Describe the bug

Build error : 
```
Unable to find method ''io.fabric8.kubernetes.api.model.BaseKubernetesListFluent io.fabric8.kubernetes.api.model.KubernetesListBuilder.addToItems(io.fabric8.kubernetes.api.builder.VisitableBuilder)''
'io.fabric8.kubernetes.api.model.BaseKubernetesListFluent io.fabric8.kubernetes.api.model.KubernetesListBuilder.addToItems(io.fabric8.kubernetes.api.builder.VisitableBuilder)'
````

### Expected behavior

No error

### Actual behavior

Error

### How to Reproduce?

- Clone my [repo](https://github.com/HiddenSplioGuy/kubernetes-client-bug-reproducer)
- Run `gradle QuarkusBuild`

### Output of `java -version`

JDK 17

### Quarkus version or git rev

> \>= 2.14

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.4.2

**Comment by iocanel** [comment]
Checked on the main branch that uses version 6.4.1 of the client and the method seems to be there.
Could you please provide a reproducer ?

**Comment by HiddenSplioGuy** [comment]
Hi @iocanel ,
I edited my comment and added a reproducer.
Thank you.

**Comment by geoand** [comment]
@metacosm is there perhaps a mismatch with the Operator SDK here?

**Comment by metacosm** [comment]
Indeed. There are several issues, the first being that you shouldn't use different versions of the quarkus-operator-sdk dependencies together: that's what the BOM is for (that said, I'm not sure how things are supposed to be handled by gradle here). The second thing is that you're using the extension in version 4.0.4 which uses java-operator-sdk at the 3.2.4 version. That version is meant to be used with the fabric8 client in version 5.12, which is why your code won't compile with more recent Quarkus versions which have updated the client to version 6.x. quarkus-operator-sdk versions 4.x are meant to be used with Quarkus 2.13. If you need to use Quarkus 2.14 or above, please use version 5.x of the extension.

**Comment by metacosm** [comment]
Also, while you might have edited the code out from your reproducer, but you don't appear to be using any functionality provided by the java operator sdk, which you don't need to be able to use the fabric8 client with Quarkus.

**Comment by HiddenSplioGuy** [comment]
Indeed, you were right about the quarkus-operator-sdk versions.
I wasn't aware of the newer versions. Upgrading them fixed my issue. 
Sorry about the inconvenience.
