### ISSUE TITLE
Server response is 404 when deleting the client resource with Keycloak Admin Reactive Client

### ISSUE THREAD

**Issue by cleverqy** [quarkusio/quarkus#31137]
### Describe the bug

var clientsResource = keycloak.realm(command.getRealm()).clients();
        clientsResource.get(command.getClientId()).remove();

### Actual behavior

org.jboss.resteasy.reactive.ClientWebApplicationException: Received: 'Server response is: 404' when invoking: Rest Client method: 'org.keycloak.admin.client.resource.ClientResource#remove'
        

### Output of `java -version`

jdk 17+

### Quarkus version or git rev

20.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 7.5+

**Comment by geoand** [comment]
Any chance you could attach a sample application we can use to debug?

**Comment by sberyozkin** [comment]
@cleverqy Can you capture a request URL/path leading to 404, see https://quarkus.io/guides/rest-client-reactive#logging-traffic ?
It should be something like `DELETE /clients/1`

Hey @geoand, FYI, `clientsResource.get(command.getClientId())` is a move from `ClientsResource`  resource to `ClientResource` subresource:
```
public interface ClientsResource {

    @Path("{id}")
    ClientResource get(@PathParam("id") String id);
    ...
}
```
Not sure it is relevant though...

**Comment by sberyozkin** [comment]
OK, I did a quick test, the problem I think is with the redundant `/admin` path segment:

```
DELETE http://localhost:32771/admin/realms/quarkus/clients/quarkus-app
```



so we have
```
@Path("/admin/realms")
@Consumes(MediaType.APPLICATION_JSON)
public interface RealmsResource {

    @Path("/{realm}")
    RealmResource realm(@PathParam("realm") String realm);
```

So when we do `ClientResource resource = keycloak.realms("quarkus")`.clients().get("quarkus-app"), it is

`/admin/realms/quarkus/clients/quarkus-app`.

If I understand it correctly the correct path is `/realms/quarkus/clients/quarkus-app` for an individual client rep.

If it is the case then this issue has to be moved to Keycloak because Quarkus KC admin client just follows the path annotations as expected.

**Comment by pedroigor** [comment]
@cleverqy You should use the client UUID when calling `keycloak.realms("quarkus").clients().get()`.

@sberyozkin The behavior is expected so that a `404` is returned because no client can be found with UUID `quarkus-app`.

Instead, you can use `ClientsResource.findByClientId` to get a representation for a client based on its client id. Afterwards you can call `keycloak.realms("quarkus").clients().get(rep.getId())`

**Comment by sberyozkin** [comment]
Thanks @pedroigor
