### ISSUE TITLE
Map configuration from both parent/default and selected profile is loaded

### ISSUE THREAD

**Issue by ntfc** [quarkusio/quarkus#31182]
### Describe the bug

When using multiple profiles and mapping a `Map` property I see that instead of using only the configuration values of the selected profile, it actually merges the values from the selected profile and the default profile.

Example:

Using the `@ConfigMapping`
```java
@ConfigMapping(prefix = "example")
public interface ExampleConfig {

    Map<String, Repository> repositories();

    interface Repository {
        String name();

        @WithDefault("config.yaml")
        String configFile();
    }
}
```

with a `application.yml` like:
```yaml
example:
  repositories:
    default:
      name: "default/default"
```

and a `application-local.yml` like:
```yaml
example:
  repositories:
    local:
      name: "local/local"
```

When running the application with `local` profile, I would expect  `ExampleConfig#repositories` to contain only 1 entry: the one loaded from `application-local.yml`. However both entries from `application.yml` and `application-local.yml` are loaded to the resulting `Map`.

Is this an issue with my setup or a bug?

Thank you!

### Expected behavior

Only properties from `application-local.yml` are loaded to `Map` property

### Actual behavior

Properties from both `application.yml` and `application-local.yml` are loaded to `Map` property

### How to Reproduce?

Using small example to reproduce the issue:

1. Clone https://github.com/ntfc/quarkus-config-mapping-map-issue
2. Check the code in `src/test/java/org/acme/ExampleConfigTest.java`
3. Run `mvn test -Dquarkus.test.profile=local -Dtest=ExampleConfigTest#testWithLocalProfile` 
    - this fails because it configuration from both `application.yml` and `application-local.yml` is loaded
4. Additionally there is a `mvn test -Dquarkus.test.profile=default -Dtest=ExampleConfigTest#testWithDefaultProfile` that loads data only from `application.yml`

### Output of `java -version`

build 17.0.5+1

### Quarkus version or git rev

2.16.2.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6

**Comment by radcortez** [comment]
This is the expected behaviour.

The `application.yaml` file is always loaded regardless of which profile is active. Additional files may be loaded and layered on top and override properties with the same name. So you get:

- application-local.yaml
  - `examples.repositories.default.name=default/default`
- application.yaml
  - `examples.repositories.local.name=local/local`

Both end up on the map because they are both present on the `Config`, and the keys are different.

A way to support this scenario is to specify each key on its own profile file, for instance, `dev`, `test`, and `prod`. Or you. can specify it in the main file as:

`%prod,dev,test.example.repositories.default.name=default/default`
