### ISSUE TITLE
Container image and Kubernetes ITs takes too much time on CI

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31273]
I recently had a look at how the time in CI is spread and stumbled upon this:
```
2023-02-17T21:32:22.0244219Z [INFO] Quarkus - Integration Tests - Container Image - Invoker SUCCESS [13:17 min]
2023-02-17T21:32:22.0244682Z [INFO] Quarkus - Integration Tests - Container Image - Standard SUCCESS [ 19.944 s]
2023-02-17T21:32:22.0245125Z [INFO] Quarkus - Integration Tests - Kubernetes - Invoker . SUCCESS [01:15 min]
2023-02-17T21:32:22.0245567Z [INFO] Quarkus - Integration Tests - Kubernetes - Standard  SUCCESS [09:14 min]
```

That is 20+ minutes to run the Container image and Kubernetes ITs.

If this is normal (?), we need to split them from the standard JDK builds as we did for the Maven and Gradle tests.

**Comment by gsmet** [comment]
@iocanel could you check if anything suspicious is going on there?

I checked the raw logs of this build: https://github.com/quarkusio/quarkus/actions/runs/4206183467/jobs/7299751359

**Comment by iocanel** [comment]
Started looking at the issue.

**Comment by iocanel** [comment]
@gsmet: I looked in detail at the Kubernetes tests and I don't see anything worrisome other than their number.

The problem seems to lie in the container image tests (the invoker part which does take the longest).

I think that we do have way too many of them that practically test the same thing.
For example, I don't see why we test the jib build along with redis, keycloak, mongo, etc as practically the additional dependencies only affect the content of the jar to be containerized and nothing more. 

So, my suggestion is to keep one for each extension (one docker, one jib etc) and drop the rest. If we want to furhter trim the time down we could just run them daily as we do with the kubernetes ones.

@geoand: wdyt?

**Comment by geoand** [comment]
Sounds reasonable to me

**Comment by Sgitario** [comment]
@iocanel This issue should have not been addressed by https://github.com/quarkusio/quarkus/pull/31295 ? Or are you planning to do something else?

**Comment by iocanel** [comment]
Depends on whether we are satisfied with the result. If not we could run the container itests once per day. @gsmet how does it look now?

**Comment by iocanel** [comment]
@gsmet: wdyt is this something we can close now?

**Comment by iocanel** [comment]
Let's close this and we can re-open if issue re-appers
