### ISSUE TITLE
QuarkusTestResourceLifecycleManager incompatible with ConfigSource

### ISSUE THREAD

**Issue by lgtti** [quarkusio/quarkus#31450]
### Describe the bug

Quarkus provides a custom configuration source that can be used to retrive some configurations.
In our project, we need to use AWS Secret Manager to retrive some secrets (applicative secrets, not quarkus agroal or similar secrets)

The problem is the integration with TestContainers. In our integration tests we need to emulate the AWS environment using localstack and the best practice is to use a class that inherits from QuarkusTestResourceLifecycleManager.

During our tests we have noticed that the ConfigSource (the ConfiguSourceFactory also) is initialized and used BEFORE the QuarkusTestResourceLifecycleManager and it raises error during the creation of the AWS SecretManager client. This because the test resources environment is not ready.

How we can fix this behavior?

### Expected behavior

QuarkusTestResourceLifecycleManager initialized BEFORE ConfigSource invocation.

### Actual behavior

ConfigSource is initialized and invoked BEFORE any QuarkusTestResourceLifecycleManager class is started.

### Output of `uname -a` or `ver`

5.19.0-31-generic #32-Ubuntu

### Output of `java -version`

OpenJDK 64-Bit Server VM (build 11.0.17+8-post-Ubuntu-1ubuntu2, mixed mode, sharing)

### Quarkus version or git rev

2.9.1.Final

### Additional information

testcontainers version 1.17.6

**Comment by geoand** [comment]
What kind of error are you seeing? Also, if you could add some sort of sample application we could use to test, it would be very helpful

**Comment by lgtti** [comment]
[getting-started-testing.zip](https://github.com/quarkusio/quarkus/files/10851324/getting-started-testing.zip)

Here a sample project.
In this project you can see a custom AWS ConfigSource, a custom TestProfile and a testLifecycleManager used to start AWS Localstack testcontainers.

If you run mvn test the execution will fail because some variables used by the ConfigSourceFactory are null. These variables are created by the testcontainer environment.

**Comment by geoand** [comment]
This happens because when building up the build time configuration is automatically discovering ConfigSource objects [here](https://github.com/quarkusio/quarkus/blob/ebee0a4b66d1b4dba9c51165e78d22fbf3b90d3e/core/deployment/src/main/java/io/quarkus/deployment/ExtensionLoader.java#L159) and [here](https://github.com/quarkusio/quarkus/blob/010e903d8e03514351cab13595060a21fd017a44/test-framework/junit5/src/main/java/io/quarkus/test/junit/BasicLoggingEnabler.java#L140).

In the second case, we almost certainly do not to do the auto-discovery, but I am not clear about the first one - @radcortez can shine some light here.

The workaround for the time being is to return an empty List from `AWSConfigSourceFactory#getConfigSources` when the properties are not available.

**Comment by radcortez** [comment]
> In the second case, we almost certainly do not to do the auto-discovery, but I am not clear about the first one - @radcortez can shine some light here.

The auto-discovery is turned on for both because of the YAML source. 

Currently, a source registered via the ServiceLoader is discovered during build time and runtime (and in static init if the source is annotated `@StaticInitSafe`).

The workaround suggested by @geoand  is correct. The cleaner solution would be to provide the AWS Config Source in its own extension and register the source manually with `RunTimeConfigBuilderBuildItem` (like we do with sources in https://github.com/quarkiverse/quarkus-config-extensions). Maybe adding the source there is an option?

**Comment by geoand** [comment]
> The auto-discovery is turned on for both because of the YAML source.

Is this the only reason? If so, I would say we should probably find another way :(

**Comment by geoand** [comment]
I am actually thinking that we should have a way to discover some vetted sources (like the YAML one) as it is almost certain that users don't expect their config customizing code to be run  during build time.

**Comment by lgtti** [comment]
Ok, actually we have moved to another solution.
We have splitted the test logic in two parts:
- Part one: we assume that the Quarkus logic of the ConfigSource works :) So we only need to test how we access the secret value. This can be tested using classic testcontainers logic. The ConfigSource used in this part is a file-based ConfigSource.
- Part two: after deployment in our test environment we will run some e2e integration tests and these tests will use the AWS Config Source. In this step we have tested the quarkus logic (we need to check it because if we upgrade quarkus the logic cannot change).

Adding a new quarkus extension is a little bit complicated so actually we use this solution.

**Comment by radcortez** [comment]
That sounds like a good solution for you. Thanks for sharing :)

Regardless, feel free to contribute the AWS Config Source to the Quarkiverse Config Extensions, and then you don't have to worry about it.

In closing the issue, since I think we are ok with this.
