### ISSUE TITLE
Configuration property to give a hint to Quarkus/Hibernate ORM regarding the database version

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#31474]
### Description

Hibernate ORM 6 takes advantage of database metadata to determine the "kind" and version of the database, and configures its dialect accordingly.

When the database metadata is not available, it defaults to the oldest supported version.

We already have a property to set the "database kind", though we probably need to wire it to the corresponding property in Hibernate ORM 6, if appropriate (currently we use the db-kind to set the dialect).

More importantly, we need to expose a property to allow configuring the version of the database explicitly. There's a corresponding property in Hibernate ORM 6 for that.

Related to #13522

**Comment by yrodiere** [comment]
I think it would make sense to put that property in `quarkus.datasource`, next to db-kind... Even though only Hibernate ORM would use it (at the moment), it really is about the datasource rather than about Hibernate ORM.

If you disagree, speak up :)

**Comment by Sanne** [comment]
Interesting idea - yes I love it. Other datasource consumers might benefit from it as well.

As you know for now this will need to be a build-time property; but let's try to future-proof the name so that eventually we can also add an "actual version" to be injected at runtime. So we'd have a "min version" supported by the built application, and an "actual version" to which the built application could theoretically be able to adapt better during first connection.

**Comment by yrodiere** [comment]
Works for me. I'll start with `quarkus.datasource.db-min-version` then. We'll adjust during review if necessary.
