### ISSUE TITLE
Multiple bugs related to sequences after switch to Hibernate 6

### ISSUE THREAD

**Issue by fedinskiy** [quarkusio/quarkus#31481]
### Describe the bug

I have an application, which works with Postgress db via Panache (using the pattern based on PanacheEntity ). On the latest Quarkus, I see several problems, when working with autogenerated ids:
1. Sequences(formerly `hibernate_sequence`) have increment of 50 (instead of previous 1)
2. If sequence is altered to use increment of 1, ids of saved entities became negative

Solution from original PR[1] (`ALTER SEQUENCE Vegetable_SEQ RESTART with 8;`) didn't solve the problem.

[1] https://github.com/quarkusio/quarkus/pull/31235/files#diff-73007bb246230662d33fbca552c060313b33bf990949ac844988bb571ac003bb

### Expected behavior

Quarkus should support creation of entitites with consequential ids

### Actual behavior

see above

### How to Reproduce?

1. `git clone 	git@github.com:fedinskiy/reproducer.git -b reproducer/hibernate-sequence-negative`
2. `mvn clean verify -Dquarkus.platform.version=3.0.0.Alpha4` — this works. 
3. Change line `quarkus.hibernate-orm."vegetables".sql-load-script` from `import-vegetables_old.sql` to `import-vegetables_new.sql` (NOTE: for some reason, quarkus profiles[1] do not work with this option)
4. Run `mvn clean verify`, which fails, selecting content from `vegetable` table in db shows this:
```
 id  |   name   
-----+----------
   1 | Potato
   2 | Carrot
   3 | Parsley
   4 | Kohlrabi
   5 | Leek
   6 | Onion
   7 | Garlic
 -41 | Eggplant # this is expected to be 8
 -40 | Eggplant
 -39 | Eggplant

```
5. If line `ALTER SEQUENCE Vegetable_SEQ INCREMENT 1;` removed from  `import-vegetables_new.sql`,  tests fails and the table looks like this:
```
 id  |   name   
-----+----------
   1 | Potato
  51 | Carrot
 101 | Parsley
 151 | Kohlrabi
 201 | Leek
 251 | Onion
 301 | Garlic
 302 | Eggplant
 303 | Eggplant
 304 | Eggplant
(10 rows)
```
[1] https://quarkus.io/guides/config-reference#custom-profiles

### Output of `uname -a` or `ver`

6.0.18-300.fc37.x86_64

### Output of `java -version`

17.0.5, vendor: GraalVM Community

### Quarkus version or git rev

1d45952917c72a12eed6b9351f6ecdca813637a8

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)

### Additional information

Probably related to https://github.com/quarkusio/quarkus/pull/31235

**Comment by yrodiere** [comment]
Whoa there, testing snapshots is nice (and I think @gsmet is very grateful) but give us some time :) In this case we're not even done working on 6.0 changes... I'll explain anyway.

> Sequences(formerly hibernate_sequence) have increment of 50 (instead of previous 1)

The switch from a single global sequence to one sequence per entity hierarchy is explained [here](https://github.com/hibernate/hibernate-orm/blob/6.0/migration-guide.adoc#implicit-identifier-sequence-and-table-name).

The switch to increments of 50 seems motivated by JPA compliance; I'm currently discussing that with the ORM team since I couldn't find any refernece to the change in the migration guide: https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/Default.20increment.20size.20for.20sequences

> If sequence is altered to use increment of 1, ids of saved entities became negative
> Solution from original PR[1] (ALTER SEQUENCE Vegetable_SEQ RESTART with 8;) didn't solve the problem.

With pooled sequences proper solution would be something like:

```
SEQUENCE Vegetable_SEQ RESTART with 58; -- 8 + pool size
```

Or (simpler in my opinion):

```
SEQUENCE Vegetable_SEQ RESTART with 8;
-- Simulate pooling; syntax here is for postgres, adapt to your DB vendor.
select nextval('Vegetable_SEQ');
```

You will get a gap in IDs; with pooled sequences it happens from time to time, but it's rare and considered a reasonable price to pay for better performance.

> Quarkus should support creation of entitites with consequential ids

It does, as long as entities are created through Hibernate ORM. It just happens that you're using native SQL, and then incrementing the sequence will give you the first value of the next pool of IDs, not the next ID... so you'll need to go through hoops.

I'm still investigating if there's a Hibernate ORM setting to set the increment size to 1 globally.

---

Regardless... we're investigating the introduction of some "best-effort backwards-compatible mode" when it comes to the database schema and Hibernate ORM. No promises though, that's tricky to get right.

**Comment by Sanne** [comment]
Hi @fedinskiy ;
in Hibernate ORM 6 the default is to use the pooled high-lo algorithm;  unless you configure it otherwise, the default is to use pools of 50. This requires the sequence to increment by gaps of 50.

In your reproducer you alter the sequence: `ALTER SEQUENCE Vegetable_SEQ INCREMENT 1;` - at this point it doesn't match the ORM's expectations anymore and you get into trouble.

If you want to use a sequence with increments of 1, you can of course do that but need to configure Hibernate ORM to use a different sequence: the mapping needs to match your DB schema.

But also... you could simply not do anything at all, Hibernate ORM will generate sequential numbers. Just don't alter the schema!

Replace this script:
```
ALTER SEQUENCE Vegetable_SEQ INCREMENT 1;
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Potato');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Carrot');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Parsley');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Kohlrabi');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Leek');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Onion');
INSERT INTO vegetable (id, name) VALUES (nextval('Vegetable_SEQ'), 'Garlic');
```

With:
```
INSERT INTO vegetable (id, name) VALUES (1, 'Potato');
INSERT INTO vegetable (id, name) VALUES (2, 'Carrot');
INSERT INTO vegetable (id, name) VALUES (3, 'Parsley');
INSERT INTO vegetable (id, name) VALUES (4, 'Kohlrabi');
INSERT INTO vegetable (id, name) VALUES (5, 'Leek');
INSERT INTO vegetable (id, name) VALUES (6, 'Onion');
INSERT INTO vegetable (id, name) VALUES (7, 'Garlic');
alter sequence Vegetable_SEQ restart with 8;
```

**Comment by yrodiere** [comment]
@Sanne I don't think this will work:

```
alter sequence Vegetable_SEQ restart with 8;
```

AFAICT ORM will use 8 as the end of the next pool, and upon persisting will start assigning negative IDs to entities, ultimately assigning the ID `1` to a new entity and triggering constraint validation failures.

**Comment by yrodiere** [comment]
In any case, I'm trying to document this change (and others) as well as solutions here: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.0:-Hibernate-ORM-5-to-6-migration#increment-size-for-sequences-defaults-to-50-instead-of-1
