### ISSUE TITLE
Hibernate ORM - Document how to handle sequences in import.sql

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#31521]
Apart from the fact that we now have a sequence per table by default and that we might have to update the examples in the doc if we have some, we need to document the fact that you need to increment any incremented sequence by 50 at the end of the script if you are using the default generators.

**Comment by yrodiere** [comment]
Also, we should fix our own tests. We have some scripts that don't correctly reset sequences, which doesn't matter in practice because the corresponding tests don't persist any entity or persist much fewer than 50 entities (so we use negative IDs but don't actually end up with ID collisions). But still, tests should at least be correct.

Note this applies to Hibernate Reactive as well.

**Comment by yrodiere** [comment]
Also the codestart seems out of date as it includes an `import.sql` that references `hibernate_sequence`.

**Comment by yrodiere** [comment]
I'll confirm the Hibernate Search quickstart re-initializes sequences incorrrectly  (`restart with 2`), leading to new entities being created with negative IDs (e.g. `[{"id":-47,"firstName":"foo","lastName":"bar","books":[]}]`).

**Comment by yrodiere** [comment]
#31899 should remove the need for the extra 50 increment.

So I think this is all that's left in this issue:

> we now have a sequence per table by default and that we might have to update the examples in the doc if we have some
