### ISSUE TITLE
Support and/or document pushing the logs to EFK (elastic fluentd kibana) and ELK (elastic logstash kibana)

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#3166]
Apparently, we don't have anything built in for that in JBoss Logging but we have a generic JSON handler that could maybe be used.

Maybe it's just documentation needed but we had a question about that on Zulip and we need a proper answer.

/cc @emmanuelbernard to prioritize

**Comment by emmanuelbernard** [comment]
Looks like a good contribution opportunity

**Comment by loicmathieu** [comment]
Hello,

There is two sides on this issue:
1. Formatting the log to EFK or ELK: usually, it's advised to just generate standard logs and making in EFK/ELK the logs mapping to the internal representation. So I don't think there is something specific to be done in Quarkus. Of course it exists some solution for log4j to generate log events in logstrash native format but I don't think it's a good idea.
2. Sending the log to EFK/ELK: again, usually it's advised to just log to a file (or the console in containerized application) and let the log shipper do the job (tail the file or read the console with the docker log driver). Again in log4j it exists a socket appender that can send the log to Logstash directly but it's not a good idea as it will couple together the apps and the log solution and in case the event cannot be send to the socket it's lost

That's why I don't think something specific needs to be done at Quarkus level. Of course JBoss loggin can propose formatter/appender for logstash or fluentd but the current avised way (I discuss this with devops experts) is to log locally (file or console) in a parseable pattern and use the tool to parse and ship.

For me, centralized logging is something, like monitoring, that is not the concern of the application.

**Comment by gsmet** [comment]
Even if we don't end up doing anything (it appears it's not needed), I think it would be interesting to have a blog post explaining how to properly map the fields and so on.

This way, we could also check that we have all the necessary information to do it.

**Comment by dmlloyd** [comment]
Related #453, #2348

**Comment by bamling** [comment]
Any idea when a solution for this will be introduced? We're currently experimenting with Quarkus and would like to end up using it in production, but we require (if possible, easily configured) JSON logging for our ELK stack.

**Comment by gsmet** [comment]
We have preliminary work here: https://github.com/quarkusio/quarkus/pull/2348 .

But it needs to be moved to a separate extension to avoid having the JSON dependency in our core artifacts.

It's typically something a new contributor should be able to do. Would you be interested? I can provide some guidance along the way.

**Comment by gsmet** [comment]
@dmlloyd I was thinking a bit more about https://github.com/quarkusio/quarkus/pull/2348 and I wonder if we should just merge it and add instructions about how you should explicitely add the `quarkus-jsonp` extension if you want to use JSON log formatting.

It doesn't look so bad to me. What do you think?

**Comment by dmlloyd** [comment]
TBH I think it wouldn't be too much more work to do it "right": basically add a multi build item for extra handlers (to support custom logging targets), and a single build item for the console format which the log processor can optionally consume.  If the format item is present, the configured format is ignored and the injected formatter is used.

This wouldn't be much more work than just rebasing alone probably!

**Comment by ia3andy** [comment]
JSON formatter is now available for console logging on master (target: 1.1.0).

**Comment by loicmathieu** [comment]
I have a working prototype for a GELF logger that should be able to send logs to Graylog or Logstash. Tested with Graylog but not yet Logstash.
I'll rebase and create a draft PR in a few hours (I hope).
Native is not working (no error but logs are not sent to Graylog), I think it has something to do with static vs runtime init but I will need help to deug this :)

**Comment by loicmathieu** [comment]
ELK has been tested with the new GELF extension and works, see #5694 

For EFK, Fluentd allows an input of syslog that is already supported by Quarkus, there is also a GELF input, and as GELF supports multiline this is also a good choice.

I can create a guide "Central log management: Graylog, ELK and EFK" with examples for the three solutions, just tell me wich one seems the best for Fluentd: syslog or GELF ?

**Comment by gsmet** [comment]
On Fri, Nov 22, 2019 at 6:12 PM Loïc Mathieu <notifications@github.com>
wrote:

> just tell me wich one seems the best for Fluentd: syslog or GELF ?
>

I don't have a strong opinion about that but I'm pretty sure devops have,
and probably different ones.

So I would document both.

**Comment by loicmathieu** [comment]
OK, I'll doo this.
I will also have a chat with my devops friends, but I fear they answer me: log to the console and let us do the rest :)

**Comment by loicmathieu** [comment]
The logging-gelf extension covers this, and the guide explain how to use it for the three major central log management system (ELF, EFK, Graylog) so I close this one.
