### ISSUE TITLE
Uni.awaitSuspending() at the end of suspending function changes return type of the function

### ISSUE THREAD

**Issue by guimeira** [quarkusio/quarkus#31829]
### Describe the bug

Hi Quarkus community!
I'm not sure if this has been reported before. I feel like this would probably have been noticed by someone else before and I might be missing something really silly, but I couldn't find a similar issue, so I'm reporting it.

Today I stumbled upon a very weird behavior. I noticed that calling `Uni.awaitSuspending()` as the last statement of a Kotlin suspending function somehow makes the function return whatever the contents of the `Uni` are, regardless of the actual return value of the function.
Storing the return value of the function in a variable, or adding some other useless statement to the end of the function makes the function behave as expected.

### Expected behavior

Calling `Uni.awaitSuspending()` as the last statement of a suspending function should suspend the function. When the Uni emits an item, the function should ignore the emitted item and return `Unit`.

### Actual behavior

The value emitted by the Uni becomes the return value of the function.

### How to Reproduce?

Small reproducer:

```kotlin
@Path("/example")
class GreetingResource {
    @GET
    @Path("/does-not-work")
    suspend fun doesNotWork(): Unit {
        returnThing().awaitSuspending()
    }

    @GET
    @Path("/works-1")
    suspend fun works1(): Unit {
        val ignore = returnThing().awaitSuspending()
        //println(ignore.javaClass.name) //prints java.lang.String
    }

    @GET
    @Path("/works-2")
    suspend fun works2(): Unit {
        returnThing().awaitSuspending()
        "abc"
    }

    @GET
    @Path("/works-3")
    fun works3(): Unit {
        returnThingSync()
    }

    fun returnThing(): Uni<String> {
        return Uni.createFrom().item("thing")
            .onItem().delayIt().by(Duration.ofMillis(1))
    }

    fun returnThingSync(): String {
        return "thing"
    }
}
```

My understanding is that all endpoints should return an empty response with status 204, but the first one returns a 200 with `thing` in the body

```
$ curl -i http://localhost:8080/example/does-not-work
HTTP/1.1 200 OK
content-length: 5
Content-Type: text/plain;charset=UTF-8

thing

$ curl -i http://localhost:8080/example/works-1
HTTP/1.1 204 No Content

$ curl -i http://localhost:8080/example/works-2
HTTP/1.1 204 No Content

$ curl -i http://localhost:8080/example/works-3
HTTP/1.1 204 No Content
```

Full project: [kotlin-uni-reproducer.zip](https://github.com/quarkusio/quarkus/files/10962657/kotlin-uni-reproducer.zip)

### Output of `uname -a` or `ver`

Linux fedora 6.1.14-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Sun Feb 26 00:13:26 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

```
openjdk version "17.0.6" 2023-01-17
OpenJDK Runtime Environment (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.6.0.10-1.fc37) (build 17.0.6+10, mixed
mode, sharing)
```

### GraalVM version (if different from Java)

Not using GraalVM, this happened when running on the JVM

### Quarkus version or git rev

999-SNAPSHOT (tested on March 13, 2023)

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

```
Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63)
Maven home: /path/to/.m2/wrapper/dists/apache-maven-3.8.6-bin/1ks0nkde5v1pk9vtc31i9d0lcd/apache-maven-3.8.6
Java version: 17.0.6, vendor: Red Hat, Inc., runtime: /usr/lib/jvm/java-17-openjdk-17.0.6.0.10-1.fc37.x86_64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "6.1.14-200.fc37.x86_64", arch: "amd64", family: "unix"
```

**Comment by geoand** [comment]
cc @jponge @cescoffier

**Comment by cescoffier** [comment]
Isn't that how Kotlin works? It returns the result of the last line? If you want to return Uni instead of Thing you need to tell Mutiny or your code to do that.

**Comment by guimeira** [comment]
It works like that for lambdas. If there isn't an explicit `return` in a lambda, the value of the last expression is implicitly returned. ([kotlin playground](https://pl.kotl.in/DE6eiOiB9))
```kotlin
val myLambda: (String)->String = { name -> 
    println("Hello $name!")
    "done!"
}

val result = myLambda("Clement")
println(result) //prints "done!"
```
For regular functions, `return` is required. ([kotlin playground](https://pl.kotl.in/mpmM_Fetl))
```kotlin
fun main() {
    val result = sayHello("Clement")
    println(result) //prints kotlin.Unit
}

fun sayHello(name: String) {
    println("Hello $name!")
    "done!"
}
```

If I try to set the return type of that `sayHello` function to String, it doesn't compile ([kotlin playground](https://pl.kotl.in/KM54wUJU8))
```kotlin
fun sayHello(name: String): String { //compilation error!
    println("Hello $name!")
    "done!"
}
```

The `works2` function in the reproducer doesn't return anything (returns `Unit`), even though its last expression is the string `"abc"`.
So I think there's something weird going on when I use `awaitSuspending()`. Even if somehow that made the return type of the function be the contents of the Uni, that should cause a compilation error, since the return type of the function is declared to be `Unit`.

**Comment by cescoffier** [comment]
Hum, that's above my kotlin knowledge. @jasondlee can you help here?

**Comment by evanchooly** [comment]
I've been digging through the bytecode trying to see what leaps out at me.  I'm just spitballing here because the coroutine code generated is pretty complicated and i'm not sure my bytecode reading skills are processing everything correctly.  But, some observations notwithstanding:

* In the source, the function returns `Unit` (explicitly or not).  In the generated code for that function, it actually returns `Object` and has an extra parameter for the `Continuation`.  This function then delegates to a synthetic function where the actual work happens and where the coroutine state function is implemented.  This synthetic function also returns `Object` and consistently ends with an `ARETURN` and is typically returning a `Unit` reference.
* All of the working examples seem to end with an expression that evaluates to `Unit` (whether via the `printlin()` or the assignment to a variable.

I'm wondering if that is the source of things getting confused because the analyis of the working functions all end with a `Unit` expression where the broken one ends with the `Uni` from the `awaitSuspending()` call.  So where we should look to resolve this is where we bridge in to the coroutine context in the resteasy-reactive extension.  I have a feeling it's just looking at the return type in the bytecode and seeing `Object` and then dumping that value down the pipe.  It looks like we need to ensmarten it to look more closely at the metadata from the kotlin compiler to make such determinations.  When looking at the bytecode in my viewer plugin, i see lines like `  // declaration:  works1(kotlin.coroutines.Continuation<? super kotlin.Unit>)` which does give the proper signature but the signature bytecode lists that `Object` return value.  I'm not sure where that `declaration` information comes from.  I don't think i've seen that in digging through bytecode before but that appears to be the point of confusion.

**Comment by cescoffier** [comment]
So, is there anything we can do?

**Comment by cescoffier** [comment]
Closing - it's changing the signature, not much we can do. If someone has an idea, please re-open.
