### ISSUE TITLE
Dev UI 2 - RESTEasy Reactive speedometer on front page really a good idea?

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32228]
I know my eyes are not exactly normal but whenever I load the Dev UI with RESTEasy Reactive around, my eyes are immediately drawn to the speedometer and I really don't think it's a good UI choice.

When going to the Dev UI, I might want to do a lot of other things and having your eyes focused on something that might or might not be useful looks like detrimental to me.

If you want this information, you go to the appropriate page and you have it.

![2023-03-29 16 26 31 localhost cfcb4b382d64](https://user-images.githubusercontent.com/1279749/228571169-3a3c6959-5aa0-4513-a7a0-4680472898db.png)

/cc @geoand @phillip-kruger @cescoffier

**Comment by geoand** [comment]
I'm the last person that is qualified to give a UI opinion :)

**Comment by stuartwdouglas** [comment]
One thing I really don't like about it is that you get marked down for using blocking endpoints, which is a design choice rather than a problem you can fix. 

I don't think it is great to basically judge developers for using blocking rather than reactive when that is one of our key marketing points. I was not overly worried when it was kinda hidden away but if it is going to be front and center IMHO we really should not be basically criticizing the developer for using blocking.

**Comment by maxandersen** [comment]
+1 on removing from front - This isn't appropriate to have front and center when the scoring is assuming you are doing reactive when we are saying you should use resteasy reactive for blocking. 

It's interesting to have but better to put it in the details and even there make it clear somehow that the scoring is skewed to reactive patterns.
