### ISSUE TITLE
Clicking on Dev UI main logo/title doesn't bring me to the home page

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#32233]
When I click on the Dev UI main logo/title (top left), it doesn't bring me to the home page, which is what I would expect.

Tested with Vivaldi and Firefox. I don't have any errors in the console, it's just doing nothing.

From what I can see, it's implemented in the `_reload` method as:

```
        fetch(devuiState.applicationInfo.contextRoot);
```

From what I can see, the `_reload` method is called but `fetch` does nothing.

**Comment by phillip-kruger** [comment]
Well, it was intentional. You can get "home" by clicking on extension menu. What that does is trigger a hot reload. I.e. if your code has changed and you need to hit some endpoint, that will trigger the reload. We can also go to extension after that, if that is what you think should happen? 

But we are also thinking of building a home page, that can replace the static index.html you get after creating a project. And that will then be the first (naked) page

**Comment by maxandersen** [comment]
not following - are you saying clicking "devui" icon is supposed to trigger reload? what reload is that as I see nothing change.

I would expect (like @gsmet) that it would go to `/q/dev-ui` now and `/q/dev` in the future.
