### ISSUE TITLE
Update command shouldn't suggest older "stable" version if already on latest candidate

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#32290]
### Describe the bug

Update command shouldn't suggest older "stable" version if already on latest candidate

```
[INFO] Instructions to update this project from '3.0.0.CR1' to '2.16.5.Final':
[INFO]
[INFO] Recommended Quarkus platform BOM updates:
[INFO] Update: io.quarkus.platform:quarkus-bom:pom:3.0.0.CR1 -> 2.16.5.Final
```

### Expected behavior

No update needed

### Actual behavior

Update suggestion printed

### How to Reproduce?

- Download app from code.quarkus.io, pick CR stream, not the stable/recommended one
   - e.g. https://code.quarkus.io/?S=io.quarkus.platform%3A3.0
- run `mvn quarkus:update`

**Comment by aloubyansky** [comment]
I don't agree with this. It's meant to suggest the latest recommended combination. A user can also specify a stream when looking for the latest recommended for a particular stream.

**Comment by aloubyansky** [comment]
I can see your point. Migrating from upstream to downstream though may require a stream argument and knowing the value.
Looks like both options could be useful and it's about what should be the default. We do have an option already for specifying the stream. We don't have an option to "reset" the stream yet though, because if not specified it's assumed to be "reset".

**Comment by gsmet** [comment]
I haven't heard a lot of complaints about this so I will close it.

It can be reopened if someone is actually willing to do the work and suggest a solution.
