### ISSUE TITLE
Cannot using 2 classes with Qute @MessageBundle with different namespace

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#32355]
### Describe the bug

I have 2 classes which manages Qute messages:

```java
@MessageBundle
public interface AppMessages {

    @Message("Hello {name ?: 'Qute'}")
    String hello_name(String name);
}
```
and the second which definesthe `msg2` namespace:

```java
@MessageBundle("msg2")
public interface App2Messages {

    @Message("HELLO")
    String hello();

}
```

When I'm trying to use `[msg2:hello}` in my template I have teh following error:

`#1 page.qute.html:32:1 - {msg2:hello}: Message bundle [name=msg, interface=org.acme.AppMessages] does not define a method for key: hello`

![image](https://user-images.githubusercontent.com/1932211/229456276-14a1e4b8-f98e-492b-8b21-d62a68ae43e2.png)

**Comment by mkouba** [comment]
This issue should be fixed in https://github.com/quarkusio/quarkus/pull/32360. 

Note that this problem only occurs if there is a namespace that starts with a different namespace, such as `msg` and `msg2`. So a workaround is to use namespaces that do not collide in this way, such as `msg1` and `msg2`.
