### ISSUE TITLE
Cyclic dependency for injected bean produced in the same class

### ISSUE THREAD

**Issue by Postremus** [quarkusio/quarkus#3241]
**Describe the bug**
I try to produce a bean, and inject it, all in the same class. In Thorntail, this worked fine.
In Quarkus / Arc, this does not work. I get a circular dependencie error, which I can not understand. There should be no circular dependencies.
See example code.

**Expected behavior**
Bean gets injected just fine. No error.

**Actual behavior**
Can not compile with mvn install

```
[ERROR] Failed to execute goal io.quarkus:quarkus-maven-plugin:0.19.1:build (default) on project project-web: Failed to build a runnable JAR: Failed to build a runner jar: Failed to augment application classes: Build failure: Build failed due to errors
[ERROR] 	[error]: Build step io.quarkus.arc.deployment.ArcAnnotationProcessor#build threw an exception: java.lang.IllegalStateException: Circular dependencies not supported: 
[ERROR] 	 PRODUCER METHOD bean [types=[java.lang.Object, ProducerBugExample$SomeBean], qualifiers=[@Default, @Any], target=ProducerBugExample$SomeBean produceSomeBean(), declaringBean=ProducerBugExample] injected into: ProducerBugExample
[ERROR] 	 CLASS bean [types=[ProducerBugExample, java.lang.Object], qualifiers=[@Default, @Any], target=ProducerBugExample] injected into: ProducerBugExample
[ERROR] -> [Help 1]
```

**To Reproduce**
* Have this class in your project.
* Run mvn install
```
import javax.enterprise.inject.Produces;
import javax.inject.Inject;

public class ProducerBugExample {

    @Inject
    SomeBean bean;

    @Produces
    public SomeBean produceSomeBean() {
        return new SomeBean();
    }

    public class SomeBean {

        private String someProperty;

        public String getSomeProperty() {
            return someProperty;
        }

        public void setSomeProperty(String someProperty) {
            this.someProperty = someProperty;
        }
    }
}
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: MSYS_NT-10.0 NANB7NLNVP2 2.10.0(0.325/5/3) 2018-06-13 23:34 x86_64 Msys
 - Output of `java -version`: java version "1.8.0_211"
Java(TM) SE Runtime Environment (build 1.8.0_211-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.211-b12, mixed mode)
 - Quarkus version or git rev: 1.0.0.CR1

**Comment by gsmet** [comment]
@mkouba could you have a look? Should this be supported?

**Comment by mkouba** [comment]
@Postremus It is a circular dependency because when the container creates a `ProducerBugExample` instance it has to inject `SomeBean` which is produced by `ProducerBugExample` -> cycle. AFAIK in Thorntail, Weld registers an incompletely initialized instance of `ProducerBugExample` through the `CreationalContext#push()` method. This helps with the circular dependency but may cause unpredictable problems because the producer is invoked upon an incompletely initialized instance.

From the spec point of view - I don't think that this is required or even tested by TCK. @manovotn WDYT?

Anyway, adding a normal scope annotation (e.g. `@ApplicationScoped`) to the `produceSomeBean()` should solve the circular dependency as well. Of course, it's not always acceptable to change the scope of the producer like this.

**Comment by Postremus** [comment]
@mkouba 

I at least get a different error when I add `@ApplicationScoped` to `produceSomeBean()`.

```
Caused by: javax.enterprise.inject.spi.DefinitionException: Return type of a producer method for normal scoped beans must declare a non-private constructor w
ith no parameters: PRODUCER METHOD bean [types=[java.lang.Object, ProducerBugExample$SomeBean], qu
alifiers=[@Default, @Any], target=ProducerBugExample$SomeBean produceSomeBean(), declaringBean=ProducerBugExample]
```

**Comment by mkouba** [comment]
Are you sure that `SomeBean` declares a non-private constructor with no parameters? This is a requirement for normal scoped beans...

**Comment by manovotn** [comment]
Circular dependencies should only be supported when at least one bean in the chain is normal scoped. That isn't the case in the above posted code where both beans are dependent.
See [Dependency injection and lookup chapter](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#injection_and_resolution).

TCK tests for circular deps are [here](https://github.com/eclipse-ee4j/cdi-tck/blob/master/impl/src/main/java/org/jboss/cdi/tck/tests/lookup/circular/CircularDependencyTest.java).

**Comment by Postremus** [comment]
@mkouba Yes. I have no constructor in `SomeBean` at all. It should therefore have the default public constructor, with no args.
I tested this by copy and pasting the above code, and adding `@ApplicationScoped` to `produceSomeBean()`.

**Comment by mkouba** [comment]
@Postremus Ah, I can see the problem - `SomeBean` is an inner class (non-static) and so it has an implicit constructor with `ProducerBugExample` as an argument (generated by the compiler).

**Comment by mkouba** [comment]
I'm to close this issue. 1) In CDI, circular dependencies are only supported when at least one bean in the chain is normal scoped, which is not the case in the snippet above. 2) `@ApplicationScoped` should work if you add a no-args constructor to the `SomeBean` class or even better, make it `static` so that an implicit constructor is not generated by the compiler. 3) It might even work in newer versions of quarkus because we try to add a no-args constructor automatically.
