### ISSUE TITLE
Can't create multiple stored procedures with transactions in setup script for MS-SQL

### ISSUE THREAD

**Issue by GregJohnStewart** [quarkusio/quarkus#32552]
### Describe the bug

I'm working to import a schema from an existent MS-SQL database, and have devservices handle setting up that test instance and use a specified `.sql` file to set it up.

However, it seems that there is no way to have more than one `CREATE PROCEDURE` statement present in that file, as it is treated as one batch. The `GO` keyword is also not available in this setup script, making it impossible to setup the schema I need for testing.

This is further confirmed as the case when the script is pasted into MS SQM Server Management Studio; the first `CREATE PROCEDURE` statement has an error noting that multiple cannot exist in the same batch.

Possible solutions, from my thoughts:

- Somehow recognize the `GO` keyword, or other way to separate batches in the same file
- Support multiple scripts specified in `quarkus.datasource.devservices.init-script-path`, and execute each in order

### Expected behavior

An SQL Script that has multiple `CREATE PROCEDURE` commands should be able to used

### Actual behavior

Error message:

```
Caused by: org.testcontainers.ext.ScriptUtils$ScriptStatementFailedException: Script execution failed (import.sql:234): CREATE PROCEDURE testProcedureOne ( @Correlation_Id VARCHAR(100) ) AS BEGIN
```

### How to Reproduce?

Example setup script:

import.sql
```sql
CREATE TABLE foo;
...

CREATE PROCEDURE testProcedureOne 
(@Process AS VARCHAR(50))
AS
BEGIN
        BEGIN TRY
	    BEGIN TRANSACTION -- having this transaction causes issues
		SELECT * FROM foo;

		COMMIT TRANSACTION
	END TRY
	BEGIN CATCH
	    ROLLBACK TRANSACTION
		SELECT * FROM foo;

	END CATCH
END;

CREATE PROCEDURE testProcedureTwo
(@Process AS VARCHAR(50))
AS
BEGIN
    SELECT * FROM foo;
END;
```

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-19044 DEVDP-AM027 3.3.6-bec3d608-341.x86_64 2023-02-22 08:29 UTC x86_64 Msys

### Output of `java -version`

openjdk version "11.0.18" 2023-01-17 LTS

### Quarkus version or git rev

2.16.6

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Maven

**Comment by geoand** [comment]
Hi,

Can you please attach a sample application which we can use for checking the problematic behavior and potential fixes?

Thanks

**Comment by yrodiere** [comment]
This is most likely a limitation of the `multi-line` import script parser. Basically Hibernate ORM has to parse the import script in order to push the appropriate string into each JDBC statement (in your case, all the text from `CREATE PROCEDURE` to `END;`, and in this case it seems it parsed wrong.

I second a reproducer would be useful.

Also, do you get the same error in Quarkus 3.0.0.CR2, which uses a different (hopefully better) parser?

Regarding the implementation, see `hibernate.hbm2ddl.import_files_sql_extractor` in the [Hibernate ORM user guide](https://docs.jboss.org/hibernate/orm/current/userguide/html_single/Hibernate_User_Guide.html#basic-bitset-jdbc-type); Quarkus sets that to `multi-line` by default, which means it uses [`MultiLineSqlScriptExtractor`](https://github.com/hibernate/hibernate-orm/blob/0094616d2da191ff58ec3df2d4478a7593d242e4/hibernate-core/src/main/java/org/hibernate/tool/schema/internal/script/MultiLineSqlScriptExtractor.java), which relies on [this lexer](https://github.com/hibernate/hibernate-orm/blob/0094616d2da191ff58ec3df2d4478a7593d242e4/hibernate-core/src/main/antlr/org/hibernate/grammars/importsql/SqlScriptLexer.g4) and [this parser](https://github.com/hibernate/hibernate-orm/blob/0094616d2da191ff58ec3df2d4478a7593d242e4/hibernate-core/src/main/antlr/org/hibernate/grammars/importsql/SqlScriptParser.g4).

**Comment by GregJohnStewart** [comment]
Quarkus 3.0.0.CR2 gives me a ton of compilation errors, complaining that `javax.persistence` package does not exist.. This would be my first time trying `3.x`, so haven't looked into migration procedures yet.

I'm working on a reproducer now, but having the rather annoying issue of not being able to reproduce the issue in a simplistic example. Still hashing at it though

**Comment by geoand** [comment]
You need to replace javax with jakarta or use our tooling for upgrading

**Comment by GregJohnStewart** [comment]
So I have a poc going here: https://github.com/GregJohnStewart/quarkus-proofs/tree/main/32552-multi-stor-proc-poc

however, I've noticed that I cannot seem to get it to pick up the import script; it does not pull in the default `import.sql`, and when I specify a different script via `quarkus.datasource.devservices.init-script-path`, it says that the script cannot be found. Also noticing the `application.properties` aren't being picked up in the `test/resources` dir.. lots of confusion here

**Comment by GregJohnStewart** [comment]
Got through the pathing issues I was having, but now can't reproduce the issue. It runs just fine...

This is really strange to me, as in the 'real' project, both stored procedures are fine on their own, and only have issues when both are included

**Comment by GregJohnStewart** [comment]
Found the issue! It appears that having a transaction within the stored procedure is what kicks off the error:

https://github.com/GregJohnStewart/quarkus-proofs/blob/main/32552-multi-stor-proc-poc/src/test/resources/db/importScript.sql#L26

**Comment by GregJohnStewart** [comment]
Also, Just swapped the code to Quarkus 3.0.0.CR2, no change in error

**Comment by yrodiere** [comment]
> This is most likely a limitation of the `multi-line` import script parser. Basically Hibernate ORM has to parse the import script in order to push the appropriate string into each JDBC statement (in your case, all the text from `CREATE PROCEDURE` to `END;`, and in this case it seems it parsed wrong.

So that was completely wrong as I thought you were using [`quarkus.hibernate-orm.sql-load-script`](https://quarkus.io/guides/hibernate-orm#quarkus-hibernate-orm_quarkus.hibernate-orm.sql-load-script) but you are using `quarkus.datasource.devservices.init-script-path`.

FWIW `quarkus.hibernate-orm.sql-load-script` seems to fare even worse with that script, but that's a different topic.

Back to `quarkus.datasource.devservices.init-script-path`... Quarkus doesn't do anything with that script and simply passes it to `MSSQLServerContainer#withInitScript`, which ultimately triggers a call to `org.testcontainers.ext.ScriptUtils#splitSqlScript`, which understands `BEGIN`/`END`, but unfortunately not `COMMIT`, so it doesn't correctly see that the `BEGIN TRANSACTION` block ends.

I don't think we can support multiple scripts in `quarkus.datasource.devservices.init-script-path` , as testcontainers only supports one such script. I'm not sure it would solve the problem anyway.

If we want to fix this, we'll need to submit a PR to https://github.com/testcontainers/testcontainers-java/tree/main/modules/database-commons to add `BEGIN TRANSACTION`/`COMMIT TRANSACTION` support.

**Comment by yrodiere** [comment]
FWIW this has been reported to the testcontainers project before: https://github.com/testcontainers/testcontainers-java/issues/6435

They basically recommend using container-specific initialization methods. Which I guess we could do instead of using `withInitiScript`, where supported. But while that's relatively easy with PostgreSQL or Mariadb, it seems with MS SQL Server [it would require a custom image](https://stackoverflow.com/questions/58309452/docker-initialize-database-tables-and-records-in-sql-server)... Someone might be able to find an alternative with just volume mounts and a custom entrypoint though, I don't know.

**Comment by yrodiere** [comment]
Finally, a workaround for anyone with this problem: use either [Flyway](https://quarkus.io/guides/flyway) or [Liquibase](https://quarkus.io/guides/liquibase), which should be able to handle more complex init scripts.

**Comment by geoand** [comment]
@yrodiere so assume there is nothing to be done on our side?

If so, we can close the issue

**Comment by yrodiere** [comment]
Well I guess there's that:

> They basically recommend using container-specific initialization methods. Which I guess we could do instead of using `withInitiScript`, where supported. But while that's relatively easy with PostgreSQL or Mariadb, it seems with MS SQL Server [it would require a custom image](https://stackoverflow.com/questions/58309452/docker-initialize-database-tables-and-records-in-sql-server)... Someone might be able to find an alternative with just volume mounts and a custom entrypoint though, I don't know.

But I'm not sure we want to go there, as this will likely be fragile.

Submitting a PR to testcontainers would be the way to go, IMO. They didn't want to fix it themselves, but they may accept a PR if someone submits one and asks nicely, explaining this affects Quarkus and containers that don't have easy workarounds such as MS SQL Server.

Anyway, yes, nothing we can do in Quarkus proper. Closing.
