### ISSUE TITLE
Undertow: Servlet context path failing with `_static` directory

### ISSUE THREAD

**Issue by melloware** [quarkusio/quarkus#32724]
### Describe the bug

Running PrimeFaces Integration Tests with 999-SNAPSHOT nightly gets this..

```
An error occured while initializing MyFaces: 
Unable to get listed resource _static from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@35c3d6e8
```

Caused by fix for: https://github.com/quarkusio/quarkus/issues/28028

### Expected behavior

No error to occur

### Actual behavior

```
An error occured while initializing MyFaces: 
Unable to get listed resource _static from directory  for path  from underlying manager io.undertow.server.handlers.resource.ClassPathResourceManager@35c3d6e8
```

### How to Reproduce?

See PrimeFaces Extension nightly integration Test: https://github.com/quarkiverse/quarkus-primefaces/actions/runs/4728799924/jobs/8390684815

### Output of `java -version`

OpenJDK Runtime Environment Temurin-17.0.6+10 (build 17.0.6+10)

### Quarkus version or git rev

999-SNAPSHOT

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.1 (2e178502fcdbffc201671fb2537d0cb4b4cc58f8)

**Comment by geoand** [comment]
Can you please update the issue title?

Thanks!

**Comment by melloware** [comment]
Yep and I am trying to reproduce the issue now with a Test

**Comment by geoand** [comment]
💪🏼

**Comment by melloware** [comment]
PR submitted I am sure you will hate it 😄 but all my PrimeFaces Test cases pass now.

**Comment by geoand** [comment]
Ouch :)

**Comment by melloware** [comment]
Maybe we should just ease that Exception since it was not there before?  We could log a warning?

**Comment by stuartwdouglas** [comment]
Logging a warning is ok, but I still would like to understand what is actually going on.

**Comment by stuartwdouglas** [comment]
@aloubyansky This is being caused by deployment only code from the new Dev UI being added to the list of known paths, and these paths are not there at runtime: https://github.com/quarkusio/quarkus/blob/f9595108f9ae3375c5449f156050272c9d0d6652/extensions/undertow/spi/src/main/java/io/quarkus/undertow/deployment/UndertowStaticResourcesBuildStep.java#L70

Is there an existing utility method somewhere that can handle this? You could fix it by using the CurateOutcomeBuildItem to manually scan the runtime CP, but I am wondering if there is a better way.

**Comment by melloware** [comment]
Nice work @aloubyansky !
