### ISSUE TITLE
Backport Gradle 8.x upgrade to Quarkus v2.x branch

### ISSUE THREAD

**Issue by koalalam** [quarkusio/quarkus#32892]
### Description

As captioned - Gradle 8.x upgrade seems to be included in Quarkus v3 only. Is there any plan to make this available in Quarkus v2 as well?

**Comment by aloubyansky** [comment]
@snazy what's your take on this?

@koalalam there were quite a lot of significant changes in Quarkus 3 Gradle integration that would not fit into a micro version update for 2.16 (which is meant to be the last 2.x stream). The first final release of Quarkus 3 is meant to be published today. If it's feasible, Gradle users are encouraged to migrate their projects to Quarkus 3.

**Comment by snazy** [comment]
The Gradle version defined in Quarkus is only used to build Quarkus. I doubt it's worth to bump the Gradle version in the Quarkus 2.x build. You can safely use the newest Gradle version with Quarkus 2.x.

The Gradle changes that went into Quarkus 3 are quite intrusive and IMO too big to be backported to 2.16.x.

**Comment by gastaldi** [comment]
According to @snazy's comments above and because we'll [maintain Quarkus 2.16 with bugfixes and important CVE fixes for a few months](https://quarkus.io/blog/quarkus-3-0-final-released/#i-use-quarkus-2-x-do-i-need-to-update-right-away) and not introduce new features, I'm closing this issue as not planned.
