### ISSUE TITLE
Setting Quarkus datasource `db-kind` configuration property by environment variable results in unrecognized configuration key warning

### ISSUE THREAD

**Issue by mzuber** [quarkusio/quarkus#32943]
### Describe the bug

Setting the `quarkus.datasource.db-kind` configuration property via the environment variable `QUARKUS_DATASOURCE_DB_KIND` as described in the [configuration reference](https://quarkus.io/guides/datasource#quarkus-datasource_quarkus.datasource.db-kind) results in the following warning at application start up:

```
2023-04-27 10:49:40,033 WARN  [io.qua.config] (Quarkus Main Thread) Unrecognized configuration key "quarkus.datasource.db.kind" was provided; it will be ignored; verify that the dependency extension for this configuration is set or that you did not make a typo
```

### Expected behavior

No warning message is shown.

### Actual behavior

Quarkus works fine, but the above warning message is shown.

### How to Reproduce?

Set the `quarkus.datasource.db-kind` configuration property via the environment variable `QUARKUS_DATASOURCE_DB_KIND`.

### GraalVM version (if different from Java)

GraalVM CE 22.3.1 (build 17.0.6+10-jvmci-22.3-b13)

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by mzuber** [comment]
Not sure if this is somehow related to #17818.

**Comment by mzuber** [comment]
> When are you setting this property?
> 
> I am asking because the property is a [build time](https://quarkus.io/guides/config#build-time-configuration) property, meaning that you cannot change it at runtime.

Good point. I'm setting the property before application startup via a local `.env` file. Interestingly, I didn't had the warning with Quarkus `2.16`.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
You cannot set `QUARKUS_DATASOURCE_DB_KIND` alone, because of the conversion rules for environment variables. This gets mapped to `quarkus.datasource.db.kind` (notice the dot instead of the dash in `db.kind`). When you set a single property like that, we cannot know if separators are dots or dashes.

You must set a `quarkus.datasource.db-kind` in `application.properties` (or any other source). This will provide us with some extra information to match what is expected. The value can be empty or something else, since env will override it; we need the property name; for more information check:

https://quarkus.io/guides/config-reference#environment-variables
