### ISSUE TITLE
Tests with PanacheMock and PanacheEntityResource fail

### ISSUE THREAD

**Issue by marcozanghi** [quarkusio/quarkus#33016]
### Describe the bug

When attempting to run a test by using PanacheMock and RestAssured in conjunction with using PanacheEntityResource the test fails with the following error:

`
Caused by: java.lang.NullPointerException: Cannot invoke "io.quarkus.hibernate.orm.panache.PanacheQuery.page(io.quarkus.panache.common.Page)" because "<local2>" is null
`

```java
        @Test
	void mock() {
		PanacheMock.mock(Fruit.class);
		when(Fruit.listAll()).thenReturn(Collections.singletonList(createFruit("Banana")));

		given()
				.when().get("/fruit")
				.then()
				.statusCode(200)
				.body("$.size()", is(1),
						"[0].name", is("Banana"));
	}	
```

```java
import io.quarkus.hibernate.orm.rest.data.panache.PanacheEntityResource;
public interface FruitResource extends PanacheEntityResource<Fruit, Long> {
}
```

### Expected behavior

The test should run normally as when commenting out the MockPanache

### Actual behavior

The test is not executed, at run time the exception above is thrownThe test

### How to Reproduce?

Create a Quarkus v3.0.1 Project

### Output of `uname -a` or `ver`

Darwin  22.1.0 Darwin Kernel Version 22.1.0: Sun Oct  9 20:14:30 PDT 2022; root:xnu-8792.41.9~2/RELEASE_ARM64_T8103 arm64

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7) OpenJDK 64-Bit Server VM (build 17.0.7+7, mixed mode)

### GraalVM version (if different from Java)

-

### Quarkus version or git rev

3.0.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

### Additional information

-

**Comment by Sgitario** [comment]
This fails because the auto-generated GET resource by the `rest-data-panache` is not internally using the `listAll` method that is the one you're mocking, but `findAll + page`, and depending on the logic, `find(query, sort, params)` or `find(query, sort)`. 

Since this is an implementation detail of the `rest-data-panache` and it's not expected to be altered by users, I don't think this is a valid issue. 

If you're keen to use mocks, I recommend implementing the resource yourself instead of using the generated GET resource. 

I'm closing this ticket, but feel free to reopen it if you still think there is something we can do.
