### ISSUE TITLE
Improve the How-to and Tutorial templates

### ISSUE THREAD

**Issue by rolfedh** [quarkusio/quarkus#33276]
### Description

I find the contents of the existing [how-to](https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/_templates/template-howto.adoc) and [tutorial](https://raw.githubusercontent.com/quarkusio/quarkus/main/docs/src/main/asciidoc/_templates/template-tutorial.adoc) doc templates confusing. 

They contain both _template_ and _instructional_ text, without a clear distinction between the two. Some useful template elements seem to be missing, such as prerequisites and procedure sections. I'd like to separate the instructional text from the template text by moving the instructional to a separate document.

**Comment by ebullient** [comment]
As a developer, I don't find this confusing. Instructional text is minimal, reminds me of what I need to do, and then gets out of my way.
History suggests that folks just want to get the job done.
They will go looking when they have specific questions, otherwise, minimal guidance in-line is best.

The TODO comments are clear: do what is in this comment block (as appropriate) and then delete it. It's a reminder that includes the text you need that is inconvenient to remember. 

At the moment, prerequisites are only present in the tutorial document (as that is the only place that clearly requires it). We could add it to the How-to template as well. 

It should be clear that a how-to is not necessarily a single "procedure" (and we avoid the word procedure universally as overly formal).

If you want to add additional notes related to creating docs of various types, the existing docs how-to is probably the right place to do it.

**Comment by rolfedh** [comment]
Thanks again, @ebullient. I added the prereqs and a couple of lines based on our conversations. I welcome your feedback on the proposed changes.
