### ISSUE TITLE
FIPS compliant SmallRye Keystore creation using keytool

### ISSUE THREAD

**Issue by Pepo48** [quarkusio/quarkus#33314]
### Describe the bug

We plan to integrate the recent [SmallRye Keystore](https://github.com/smallrye/smallrye-config/pull/833) to Keycloak. This should allow to us to use a Java Keystore as a Quarkus config source. As far as we understand, the implementation relies on PBE (Password-based Encryption). So for example, a compatible keystore can be generated by the following keytool command:
```
keytool -importpass -storetype pkcs12 -alias master_smtp__key -keystore myks -storepass keystorepass
```
and right after that you're prompted to **Enter the password to be stored**.

This results to a keystore with an Secret Key Entry. This SKE is encrypted with the keystore password (`-storepass` parameter) and the used algorithm is dependant on JDK's implementation. For OpenJDK17 it is `PEWithMD5AndDES`, which according to available resources isn't allowed to use in FIPS strict mode (see e.g. [this paper](https://csrc.nist.gov/CSRC/media/projects/cryptographic-module-validation-program/documents/security-policies/140sp3741.pdf), section 5.2).

**Can we consider such keystore to be FIPS compliant?**
___
###### Additional info: what we already tried?

As per our investigation so far, there is no way to specify a stronger algorithm via keytool. The parameters `-keyalg` and `-keysize` don't have a desired effect. Moreover, as we inspected what Java keytool actually does, it seems that whenever you use PBE, the algorithm is given by a hardcoded value.

We also tried to generate such keystore on RHEL9 with FIPS mode enabled while using OpenJDK17. Such environment provides different Java security provider that should be in alignment with FIPS (in our case SunPKCS11-NSS). The generation was successful. What we didn't expect is that such keystore is readable even on non-FIPS machine and again the same `PEWithMD5AndDES` is used.

Elytron seems to overcome this by implementing their own toolset, where first a separate key is generated, which is then used for the encryption of a secret. This also results to a custom keystore and ideally we would like to avoid similar approach.
Also, we were successful, when it comes to programatically importing a SKE with a stronger algorithm, but again that would require a custom tool to be implemented.

We went through all of this just recently, while we were implementing [a new vault SPI in Keycloak](https://github.com/keycloak/keycloak/pull/19644) and we used a similar approach initially.

**Comment by jerboaa** [comment]
@Pepo48 When I run the mentioned command on my FIPS enabled Fedora VM with `-J-Djava.security.debug=providers,properties` it appears it'll do the right thing. Is that what you need? In my case it generates the keystore with:

```
$ keytool -J-Djava.security.debug=properties,providers -importpass -storetype pkcs12 -alias master_smtp__key -keystore myks -storepass keystorepass
[...]
properties: FIPS mode default keystore.type = pkcs12
properties: FIPS mode javax.net.ssl.keyStore = 
properties: FIPS mode javax.net.ssl.trustStoreType = pkcs12
properties: FIPS support enabled with plain key support
properties: FIPS mode support configured and enabled.
[...]
Provider: Cipher.PBEWithHmacSHA256AndAES_256, mode: encryption, algorithm from: SunPKCS11-NSS-FIPS
Provider: Mac.HmacPBESHA256 algorithm from: SunPKCS11-NSS-FIPS
Provider: KeyStore.PKCS12 type from: SUN
Provider: Mac.HmacPBESHA256 algorithm from: SunPKCS11-NSS-FIPS
```

Those look OK to me for FIPS.


/cc @martin_uy

**Comment by martinuy** [comment]
@jerboaa is right. There you see the default option when Fedora is configured in FIPS mode. Optionally, you can use ```keystore.pkcs12.certProtectionAlgorithm```, ```keystore.pkcs12.keyProtectionAlgorithm``` and ```keystore.pkcs12.macAlgorithm``` to choose the algorithms for key store privacy and integrity respectively. Notice that ```PBEWithMD5AndDES``` is not supported by SunPKCS11+NSS (Fedora, FIPS mode). You can see the list of what we support [here](https://github.com/rh-openjdk/jdk/blob/257d544b594a29ece24ce6026a75667b20fff23c/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java#L937) and [here](https://github.com/rh-openjdk/jdk/blob/257d544b594a29ece24ce6026a75667b20fff23c/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/SunPKCS11.java#L686).

**Comment by Pepo48** [comment]
@jerboaa @martinuy guys, first of all thanks for the answers.

The command you used seems to be the same as the one I provided in the issue description (apart from the debug iinfo part).

Just to be completely sure I tried generate a keystore on RHEL9 with FIPS enabled using OpenJDK17 again and I got the very same output:
![image](https://github.com/quarkusio/quarkus/assets/12138171/3dfb0290-89b4-420a-bb78-80c674b1c2ba)
![image](https://github.com/quarkusio/quarkus/assets/12138171/b540d26d-cafe-42dd-a51b-6963969de95a)

As I already mentioned in the description above, what surprises me is that I'm able to open the keystore even on non-FIPS machine (MacOS in my case) and I can read the password stored in it Should I be allowed to do that?

On top of that (and at this point don't know if it's relevant or not but), if I try to get an information about algorithm used for the secret key entry via Java API (`ske.getSecretKey().getAlgorithm()`), it says `PBEWithMD5AndDES`. Here's the screenshot from KeyStore Explorer installed on my local non-FIPS machine:
<img width="947" alt="image" src="https://github.com/quarkusio/quarkus/assets/12138171/9b3398b3-7ba5-4883-b3b6-286375c043b2">

Thanks for your time.

**Comment by jerboaa** [comment]
@Pepo48 I think the question is this: "How can I store a PBE secret key entry in a pkcs12 keystore that is itself using a fips compliant PBE algorithm?" Or did I get this wrong?

The keystore itself uses compliant PBE encryption. But there seems no way to massage `keytool`s `-genseckey` option together with PBE to use one.

**Comment by franferrax** [comment]
@Pepo48, @jerboaa:

I can confirm this seems to be a `keytool` issue, even outside FIPS, `bash` reproducer:
```sh
# Try to generate a SecretKey with the PBEWithHmacSHA256AndAES_256 algorithm, using the 'secret' password.
# Then store it in a PKCS12 keystore, encrypted and protected with the 'keystorepass' password.
echo secret | keytool -genseckey -storetype PKCS12 -keystore /tmp/Test.p12 -storepass keystorepass \
                      -keyalg PBEWithHmacSHA256AndAES_256 -alias master_smtp__key -keypass keystorepass

# Read the stored SecretKey, print its algorithm and raw bytes content.
cat >/tmp/Test.java <<'END' && javac /tmp/Test.java
import java.io.FileInputStream;
import java.security.KeyStore;
import javax.crypto.SecretKey;
public final class Test {
    public static void main(String[] args) throws Throwable {
        KeyStore ks = KeyStore.getInstance("PKCS12");
        ks.load(new FileInputStream("/tmp/Test.p12"), "keystorepass".toCharArray());
        SecretKey key = (SecretKey) ks.getKey("master_smtp__key", "keystorepass".toCharArray());
        System.out.println("**** Key algorithm: " + key.getAlgorithm());
        System.out.println("****   Key content: " + new String(key.getEncoded()));
    }
}

END
java -Djava.security.debug=providers -cp /tmp Test 2> >(grep '^Provider: \(Cipher\|Mac\)'); rm -f /tmp/Test.*
```

Output from a FIPS-enabled Java 17 RHEL 9 virtual machine:
```
Provider: Mac.HmacPBESHA256 algorithm from: SunPKCS11-NSS-FIPS
Provider: Cipher.PBEWithHmacSHA256AndAES_256, mode: decryption, algorithm from: SunPKCS11-NSS-FIPS
**** Key algorithm: PBEWithMD5AndDES
****   Key content: secret
```

Output from a FIPS-disabled Java 17 RHEL 9 virtual machine:
```
Provider: Mac.HmacPBESHA256 algorithm from: SunJCE
Provider: Mac.HmacSHA256 algorithm from: SunJCE
Provider: Cipher.PBEWithHmacSHA256AndAES_256, mode: decryption, algorithm from: SunJCE
**** Key algorithm: PBEWithMD5AndDES
****   Key content: secret
```

Here we can see that the key algorithm is wrong, since it should be `PBEWithHmacSHA256AndAES_256` (although we can see that this algorithm is used to decrypt the key). Also, the key isn't derived, it consists of just the password bytes, like [_SunJCE_'s password-only `PBEKey`](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/com/sun/crypto/provider/PBEKey.java#L45) instances (which don't inherit from `javax.crypto.interfaces.PBEKey`).

What is confusing here, is that the key protection algorithm (for encryption in the store) and the key's algorithm itself (for the key usage, which `keytool` isn't honoring) are the same.

Additionally, the original post uses `keytool -importpass` which we (me and @martinuy) thought was importing the `SecretKey` from another keystore, but, at least for this example, is the same as using `keytool -genseckey`.

**Comment by martinuy** [comment]
Thanks @franferrax for commenting on this issue. As said privately, the important point from the FIPS-compliance point of view is that the PKCS 12 key store is protected with the PBEWithHmacSHA256AndAES_256 (privacy) and HmacPBESHA256 (integrity) algorithms, coming from the NSS library which is a FIPS-certified module in RHEL. While the key type in the PKCS 12 bag algorithm seems incorrect, it's at some point opaque data that we are storing and recovering: as long as we don't use the recovered key for an PBEWithMD5AndDES encryption (which is not available in the SunPKCS11-NSS-FIPS security provider anyways), should be fine.

**Comment by vmuzikar** [comment]
@franferrax @martinuy Thanks for the replies.

So, if I understand correctly, as long as the keystore itself is protected using FIPS-compliant algorithms (in this case `PBEWithHmacSHA256AndAES_256` and `HmacPBESHA256`), there's no issue with storing opaque Secret Keys – it's still FIPS-compliant. Is that correct.

What I don't understand still is where is the `PBEWithMD5AndDES` encryption coming from. As you mentioned:
> 

Is that possibly a bug since the key is seemingly stored unencrypted (`` returns the opaque Secret)?

**Comment by jerboaa** [comment]
> @Pepo48, @jerboaa:
> 
> I can confirm this seems to be a `keytool` issue, even outside FIPS, `bash` reproducer:

@franferrax Thanks. I had a feeling it's that (an upstream keytool issue) from my code spelunking. Could you report a bug in JBS, please?

**Comment by jerboaa** [comment]
> Can we consider such keystore to be FIPS compliant?

I would say in such a scenario the keystore itself is FIPS compliant as @martinuy  explained in [this comment](https://github.com/quarkusio/quarkus/issues/33314#issuecomment-1550632005), but the content isn't (the `SecretKeyEntry`). No FIPS certification expert, though.

**Comment by franferrax** [comment]
@franferrax
> Additionally, the original post uses `keytool -importpass` which we (me and @martinuy) thought was importing the `SecretKey` from another keystore, but, at least for this example, is the same as using `keytool -genseckey`.

[`-importpass` and `-genseckey` are very similar](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/sun/security/tools/keytool/Main.java#L1189-L1202), except that `-genseckey` makes `-keyalg` mandatory, whereas `-importpass` assumes a default `-keyalg PBE`. Please also remember that [`PBE` is an alias for `PBEWithMD5AndDES`](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/sun/security/util/SecurityProviderConstants.java#L253).

@vmuzikar
> Is that possibly a bug since the key is seemingly stored unencrypted (`key.getEncoded()` returns the unencrypted Secret)?

The `SecretKey` is encrypted in the keystore, and it can't be decrypted without the keystore's password. What I think you are referring to, is the fact that the _password_ is stored instead of the _derived key_.

Password-Based Encryption (PBE) implies deriving a _key_ from a _password_, a PBE algorithm takes the following input:

* _Password_ (bytes)
* _Salt_ (bytes)
* _Iterations Count_ (positive nonzero integer)
* _Desired Output Key Length_ (positive nonzero integer, can be inferred in Java for some algorithms, for example [it's 256 bits for `PBEWithHmacSHA256AndAES_256`](https://github.com/openjdk/jdk/blob/cd48dc20125baae3a5b47baba645852204062cf4/src/jdk.crypto.cryptoki/share/classes/sun/security/pkcs11/P11SecretKeyFactory.java#L210-L211))

The output of the derivation process is the _derived key_ (bytes), from which you can't retrieve or recover the _password_, even if you know all the remaining input parameters.

@vmuzikar
> What I don't understand still is where is the `PBEWithMD5AndDES` encryption coming from.

First of all, let's note that there is no `PBEWithMD5AndDES` encryption involved, it's just a string indicating the algorithm name in Java's `SecretKey`, and metadata (an attribute) in the `PKCS12` keystore. In FIPS, it's impossible to derive a _key_ using this algorithm, so you'll find this key doesn't work in neither the `Cipher` nor the `Mac` service.

This algorithm name comes from the mentioned `PBE` &rarr; `PBEWithMD5AndDES` alias, since [`keytool` gets this _SunJCE_ `SecretKeyFactory` for any `-keyalg` starting with `"PBE"`](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/sun/security/tools/keytool/Main.java#L1835-L1836).

Non-derived PBE Keys just holding the _algorithm name_ and the _password_ are part of an [identified _SunJCE_ limitation](https://bugs.openjdk.org/browse/JDK-8301553#:~:text=To%20keep%20compatibility,security%20providers.) which we don't expect to be addressed, due to the backwards-compatibility issues arising from a hypothetical fix. Also, please note that generation of this _SunJCE_ `PBEKey` is enabled in FIPS, since it doesn't involve any crypto (just storing the _password_ inside an object) and it is required for `PKCS12` keystores to work.

Interestingly, for PBE, instead of the key's algorithm itself, **`-keyalg` [is interpreted as the key protection algorithm](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/sun/security/tools/keytool/Main.java#L1884)**. Key's algorithm is kept as `PBEWithMD5AndDES`, and we could think of this as a way to say "generic `PBE`", per the alias. This can be demonstrated by changing `-keyalg` from `PBEWithHmacSHA256AndAES_256` to `PBEWithHmacSHA512AndAES_128` in my previous "reproducer". I'm now starting to think that this is by-design, not a bug, @martinuy, @jerboaa: what do you think?

So it seems that `keytool` is designed to honour `-keyalg` as the "key" protection algorithm, which in this case is used as the **_password_ protection algorithm**. When you retrieve this `SecretKey` from the keystore, you are actually retrieving a _password_, and its algorithm name doesn't have any useful meaning, you just want the _password_ bytes, which are in `key.getEncoded()`. @Pepo48, @vmuzikar: if this is the usage scenario you are after, I don't find any FIPS-compliance issue.

Lastly, [this _SunJCE_ non-derived PBE Key limits the password characters to only be ASCII](https://github.com/openjdk/jdk17u/blob/jdk-17.0.7-ga/src/java.base/share/classes/com/sun/crypto/provider/PBEKey.java#L69-L71), so you might want to consider encoding the password in UTF-8 (or anything else) and later encoding those resulting bytes in some ASCII format (such as hex digits or base 64). Unfortunately, this would imply some wrapping around, without the ability to directly use `keytool`:
```shell
echo -e '\u2022 non-ASCII pass' | keytool -importpass -keystore k.p12 -storepass keystorepass
```
```
keytool error: java.security.spec.InvalidKeySpecException: Password is not ASCII
```

**Comment by Pepo48** [comment]
@franferrax thanks for your very comprehensive answer.  It helped us a lot to understand how it works under to hood and I guess you covered all of our questions and concerns.

@jerboaa @martinuy @sberyozkin @franferrax guys, thank you all once again. We really appreciate the effort you put into the investigation and all the attention that our questions got, not just here but even on the mailing list, via chat or during the meeting. It helped us tremendously.
