### ISSUE TITLE
Log redaction in Quarkus (JBoss Log Manager)

### ISSUE THREAD

**Issue by GavinRay97** [quarkusio/quarkus#33392]
### Description

We have a multi-tenant application and need to redact some information.

After searching for extension points, it doesn't currently seem possible to define new classes that intercept/modify the logging pipeline.

I thought I could use Log4j and write a plugin for that, but it seems that ultimately it all gets routed back to JBoss Log Manager:
- https://stackoverflow.com/a/68543056/13485494

In the docs, I see that there are `filter` expressions which can be used in `application.properties`, specifically `substitute`:
- https://github.com/jboss-logging/jboss-logmanager#filter-expressions
- https://github.com/jboss-logging/jboss-logmanager/blob/ee6db025e9dc3b269ff12f7ca5a1ca28008a142c/src/test/java/org/jboss/logmanager/FilterTests.java#L448-L490

But in our case, the rules may get quite complicated and numerous, and may be easier maintained in code.

Is there any way to implement this as something like Log4j 2's `LogEventPatternConverter` plugin?

Thank you =)

**Comment by geoand** [comment]
cc @jamezp @dmlloyd

**Comment by dmlloyd** [comment]
Are you looking to skip entire messages or just redact parts of them (e.g. just certain format arguments)?

**Comment by manofthepeace** [comment]
@GavinRay97  in our application we actually do quite a bit of log redaction. I have raised this as an improvements for simplicity https://github.com/quarkusio/quarkus/issues/32998. But it does works quite well in our case by using JUL filters. Thanks to ladicek for helping me on that in the past.

I hope this is what you are looking for, otherwise sorry for the noise. But for example in our code we have a lot of restclients and we want to log them, but there are some headers we want to redact, like credentials/jwt. 

So we have something a bit like this; `public class RestClientFilter implements Filter`. where Filter is a `java.util.logging.Filter`. The filter is registered this way as warly as possible; 
`Logger.getLogger("org.jboss.resteasy.reactive.client.logging.DefaultClientLogger")
                .setFilter(new RestClientFilter());`
                
  there are filter examples here; https://github.com/jboss-logging/jboss-logmanager/tree/main/src/main/java/org/jboss/logmanager/filters

Hope that helps

**Comment by GavinRay97** [comment]
@dmlloyd Looking to just redact with `****` certain parts of messages

@manofthepeace Thanks for the examples!

Was able to get this working using something like the below -- I think the Quarkus Logging docs should add a small section/example noting that you can actually modify the logs, not just filter whether they show or not.

 It wasn't obvious to me you could do that in the JUL Filter interface 👍 

```properties	
quarkus.log.console.filter=password-redaction-filter
```

```kt
import io.quarkus.logging.LoggingFilter
import java.util.logging.Filter
import java.util.logging.LogRecord

@LoggingFilter(name = "password-redaction-filter")
class PasswordRedactionFilter : Filter {

    private val REDACTED = "****"

    // Catch for passwords in the form: "password=xxxx"
    private val passwordRegex = Regex("password=([^&]+)")

    override fun isLoggable(record: LogRecord): Boolean {
        val message = record.message
        val maskedMessage = message.replace(passwordRegex, "password=$REDACTED")
        record.message = maskedMessage
        return true
    }
}
```

**Comment by andreiyusupau** [comment]
I've tried method suggested by @GavinRay97, the log reduction works fine, except that original quarkus logs become broken(those `%s` instead of values):
```java
2024-12-19 15:42:07,121 INFO  [io.quarkus] (main) Installed features: [%s]
2024-12-19 15:42:07,120 INFO  [io.quarkus] (main) %s %s (powered by Quarkus %s) started in %ss. %s
2024-12-19 15:42:07,121 INFO  [io.quarkus] (main) Profile%s %s activated. %s
```
Maybe there are some default filters that get overriden by this approach?

**Comment by dmlloyd** [comment]
The reason is the use of `setMessage`, which resets the formatting mode. You'll have to cast the record to `ExtLogRecord`, and capture the `formatStyle` property, so you can re-set the `formatStyle` after re-setting the message.
