### ISSUE TITLE
@Parameter in openapi complains about missing jaxrs parameter

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#33465]
### Description

`@POST @Path("/todos/{username}")
    @Operation(summary = "Add a todo to the list")
    public void addTodo(@Parameter(required=true,
                  description = "The name of the user") String username, String todo) {
`

gives warning about `@Parameter annotation missing JAX-RS parameter.`

we should:
a) give more hint about possible solutions. i.e. `@Parameter annotation missing JAX-RS parameter. Add @RestPath or @PathParam
b) not warn as the @Path annotation already states its required.

**Comment by MikeEdgar** [comment]
This is an order-of-operations issue in the scanner. The `@Parameter`s without JAX-RS annotations are identified prior to the final step of finding Resteasy parameters w/o annotations. Ultimately, the `username` argument should be associated with the `@Parameter` having the description, but the warning has already been issued by that point.

This warning has also been raised as an issue [1] & [2] for cases where the parameters are not simply passed to the resource method - e.g. pulled out of `UriInfo` or handled elsewhere such as in a filter. Since the original issue resulting in the addition of the warning was simply a handling bug, there may be a case to just remove the warning entirely.

[1] https://github.com/quarkusio/quarkus/issues/28006
[2] https://github.com/smallrye/smallrye-open-api/issues/1264
