### ISSUE TITLE
OIDC: Constant 401 instead of new challenge when user abort login, browser back, then reload, then 401 loop

### ISSUE THREAD

**Issue by kkazuo** [quarkusio/quarkus#33481]
### Describe the bug

I have found similar issue #33200.
I think this is unexpected behavior, but I'm sorry if I have misconfigured Quarkus.

On code flow, UA redirected to IdP, but the user click back the browser and reload first page, then enter 401 endless loop.

application.properties is like this...
```
quarkus.oidc.auth-server-url=https://login.microsoftonline.com/...
quarkus.oidc.client-id=the-id
quarkus.oidc.credentials.secret=the-secret
quarkus.oidc.application-type=web-app
quarkus.http.auth.permission.authenticated.paths=/*
quarkus.http.auth.permission.authenticated.policy=authenticated
```

1. User hit the landing page: http://localhost:8080/
1. Redirect to auth-server-url with q_auth_ Cookie set.
1. UA show auth-server-url's login prompt.
1. But the user doesn't login (her reason are no matter). The user click Browser back button 2 step back, the landing page (http://localhost:8080/). Then reload.
1. UA will show http://localhost:8080/. BUT now there is q_auth_ Cookie, so 401 error return.
1. The user continue hitting reload button, but unfortunately just return 401 error. endlessly.

### Expected behavior

I'm not OIDC expert, but IMHO if there is invalid q_auth_ Cookie found, it would not emit 401 error, instead would it good just ignore the invalid q_auth_ Cookie as if there is not exist at the request beginning. And just start a new login flow.

### Actual behavior

If q_auth_ Cookie exists and UA way out the OIDC flow for some reason, UA gets 401 error endlessly and user could not recover the situation himself.

### Output of `uname -a` or `ver`

Linux 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (build 17.0.7+7-Ubuntu-0ubuntu120.04) OpenJDK 64-Bit Server VM (build 17.0.7+7-Ubuntu-0ubuntu120.04, mixed mode, sharing)

### Quarkus version or git rev

3.0.3.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.8 (4c87b05d9aedce574290d1acc98575ed5eb6cd39)

**Comment by sberyozkin** [comment]
Hi @kkazuo 

So we have a case here of the user, instead of completing the provider authentication challenge, just pressing a browser back button. I have to admit, took me awhile to start supporting the idea of a multi-tab authentication :-), but here it is not even a multi-tab, the user just returns for some reasons in the current authentication challenge tab... 

OK, here OIDC detects the current code flow is in process because it sees a callback path being called, `q_auth` cookie is available therefore it must be a redirect from the provider, but a required `state` query parameter is missing. 

Your proposal is to delete that cookie, and start a new redirect, right ? But now we have a multi-tab authentication, so by deleting a state cookie - how do we know it belongs to the current tab ? We delete it and then the flow running in another tab gets broken. If we have such a case - something unusual has happened which is why 401 is reported.

Can I ask you a question: do you configure a callback URL ? 
It looks like to me you might not... 

If you look at #33200, the problem there was, Quarkus will authenticates any request, without users have to configure the callback path - i.e,  the current request URL is a redirect URL which OIDC provider will have to redirect to - it can only work if one configures a provider to support any redirect URLs - this is not the production level option though, might be good for dev/test but not for prod.

The solution is to follow a recommended OIDC/OAuth2 pattern, configure say `quarkus.oidc.authentication.redirect-path=/callback` and it will be all, everything will just work, even you press a `Back` button in the same tab.

If you do prefer to have users redirected exactly to the same request URL the user started from, it is still the right idea, to create a `/callback` path - simply to make sure the client can be white-listed in the provider console by enforcing that users can only go back to  `/callback` - but you can complement `quarkus.oidc.authentication.redirect-path=/callback` with `quarkus.oidc.authentication.restore-path-after-redirect=true` - and if the user called `/a` - the user will end up at `/a` in the end:

```
quarkus.oidc.authentication.redirect-path=/callback
quarkus.oidc.authentication.restore-path-after-redirect=true

quarkus.http.auth.permission.callback.paths=/callback
quarkus.http.auth.permission.callback.policy=authenticated
``` 

Note in this last case, `/callback` does not even have to exist as a JAX-RS endpoint path, it is a virtual path - which is which a policy configuration is added to trigger an authentication on this path.

Does it help ?

**Comment by kkazuo** [comment]
@sberyozkin Thank you for very detailed explanation.
And the last case, I have add these properties (for my web-app case),
401 cookie error solved seemlessly!!
I don't know theese properties, but it's all my miss-configuration.
You save me, thank you!

```
quarkus.oidc.authentication.redirect-path=/login
quarkus.oidc.authentication.restore-path-after-redirect=true

quarkus.http.auth.permission.callback.paths=/login
quarkus.http.auth.permission.callback.policy=authenticated
```

> Your proposal is to delete that cookie, and start a new redirect, right ?

No, I have thought that just ignore that cookie's existence and that continue other processing will solve the problem.
But true cause is I didn't set callback.paths config as you have suggested.
So please ignore my idea.

Thank you.

**Comment by kkazuo** [comment]
> Note in this last case, /callback does not even have to exist as a JAX-RS endpoint path, it is a virtual path

I think this is a very easy explanation to understand the behind mechanism if I have understanded correctly.

> thousands of orphaned state cookies

aha, You right. That's a problem. I didn't noticed.

Thank you again.

**Comment by effusion** [comment]
We still face this issue in the current version of Quarkus 3.2
