### ISSUE TITLE
Bug in ternary operator in {#let} section

### ISSUE THREAD

**Issue by dscoppelletti** [quarkusio/quarkus#33526]
### Describe the bug

My checked template contains the following:

```
{#let readOnly = (mode == 5) ? 'readonly="true"' : ''}
<p>{readOnly}</p>
{/let}
```

### Expected behavior

Right result.

### Actual behavior

The build fails with the following:

```
[error]: Build step io.quarkus.qute.deployment.QuteProcessor#analyzeTemplates threw an exception: io.quarkus.qute.TemplateException: Parser error in template [test.qute.html] line 11: empty expression found {:}
```

### How to Reproduce?

Reproducer: [quarkustest.zip](https://github.com/quarkusio/quarkus/files/11531171/quarkustest.zip)

### Output of `uname -a` or `ver`

MAC OSX 13.3.1 x86_64

### Output of `java -version`

17.0.6

### Quarkus version or git rev

3.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.8

### Additional information

I've tryed with:

```
{(mode == 5) ? 'readonly="true"' : ''}
```

The build succeded but the expression is literally printed in the browser:

```
{(mode == 5) ? 'readonly="true"' : ''}
```

**Comment by mkouba** [comment]
This is expected. You can't use the ternary operator like this. As [documented](https://quarkus.io/guides/qute-reference#sections), the values of a section parameter can be grouped, e.g. something like `{#let key=(value1 + value2)}`

Also the `==` operator is not supported outside the `{#if}` section by default.

You can try something like: `{#let readOnly = (mode.equals(5) ? 'readonly="true"' : '')}`.

> {(mode == 5) ? 'readonly="true"' : ''}

The content of a tag must start with [a digit, an alphabet character, underscore, or built-in command](https://quarkus.io/guides/qute-reference#identifiers), otherwise it's ignored. Again, something like `{mode.equals(5) ? 'readonly="true"' : ''}` could work. And if not you can add a [template extension method](https://quarkus.io/guides/qute-reference#template_extension_methods) to handle the specific type of `mode`, e.g.

```java
static boolean is(Integer mode, Integer value) { 
        return mode.equals(value);
}
```
and in the template: `{mode.is(5) ? 1 : 2}`.
