### ISSUE TITLE
OpenTelemetry + GraphQL - graphql.operationName is empty

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#33545]
### Describe the bug

`graphql.operationName` is empty when using OpenTelemetry + GraphQL

I'm expecting to see the name of invoked query (`@Query("fooBar")`

<img width="2032" alt="Screenshot 2023-05-22 at 18 34 07" src="https://github.com/quarkusio/quarkus/assets/925259/42156922-22b8-4e2c-956c-b9b4d0e3f2f6">

I'm using Quarkus main from 2023-05-22

### Expected behavior

`graphql.operationName` contains the name of invoked query (`@Query("fooBar")`

### Actual behavior

`graphql.operationName` is empty 

### How to Reproduce?

 - Clone https://github.com/quarkus-qe/quarkus-test-suite
 - run `mvn clean verify -f http/graphql-telemetry -Dit.test=GraphQLTelemetryIT#verifyTelemetry`

It's suggested to adjust GraphQLTelemetryIT to have time to open Jaeger instance and investigate spans for graphql-telemetry service, or add `System.out.println(body.prettyPrint());` to see the response in terminal

```diff
--- a/http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
+++ b/http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/GraphQLTelemetryIT.java
@@ -48,7 +48,8 @@ public class GraphQLTelemetryIT {
                     .get(jaeger.getTraceUrl());
             Assertions.assertEquals(HttpURLConnection.HTTP_OK, traces.statusCode());
             JsonPath body = traces.body().jsonPath();
-            Assertions.assertEquals(2, body.getList("data").size());
+            System.out.println(jaeger.getTraceUrl());
+            Assertions.assertEquals(222, body.getList("data").size());
             Assertions.assertEquals(2, body.getList("data[0].spans").size());
             Assertions.assertEquals(2, body.getList("data[1].spans").size());
             // Span with "operationName": "GraphQL" is child of the span with "operationName": "POST /graphql"
```

### Output of `uname -a` or `ver`

macOS

### Output of `java -version`

Java 17

### Quarkus version or git rev

319a0d9734

**Comment by jmartisk** [comment]
`graphql.operationName` is the name of the GraphQL operation as described in https://spec.graphql.org/draft/#sec-Language.Operations, not the name of a query. A GraphQL operation can contain multiple queries at the same time.

If you execute, for example,
```
query {
  fooBar
}
```
then you're executing an UNNAMED operation that asks for a single query named `fooBar`. That's why the `graphql.operationName` field is empty.

To name the operation, you would have to do something like

```
query myQuery {
  fooBar
}
```

In that case the `graphql.operationName` field would get filled with `myQuery`.

Looking at https://github.com/quarkus-qe/quarkus-test-suite/blob/8d2eb61e51dda1f72004fdc5a7c2ac62674eadd0/http/graphql-telemetry/src/test/java/io/quarkus/ts/http/graphql/telemetry/Utils.java#L19,
I assume that the test suite executes an unnamed operation, that's why the name is empty.

**Comment by fedinskiy** [comment]
@jmartisk the query is unnamed for tracing as well, but we have operation name nonetheless.

**Comment by jmartisk** [comment]
The original implementation with OpenTracing, as far as I remember, created two kinds of spans, one for the top-level operation, and one for each query contained in it, so perhaps you're referring to the span for the query - that contained the name, IIRC.

But we've now dropped the query-level spans, because it's actually not very useful when one can simply have it generated on the CDI level by the CDI tracing interceptor, because the query is a method of a CDI bean.

**Comment by geoand** [comment]
Is there something we need to do with this one?

**Comment by jmartisk** [comment]
I think this was explained and can be closed. @fedinskiy, please ask and/or reopen if you have more issues

**Comment by brunobat** [comment]
@jmartisk If it will never be set, can the `graphql.operationName` property be removed from the span?

**Comment by brunobat** [comment]
Ok, thanks
