### ISSUE TITLE
Jib not using image name when using variables

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#33552]
### Describe the bug

If I use Jib to build a container with the following property (voluntarily without value):
```
quarkus.container-image.name=hide-and-seek-${application.name}
````

It ignores the value and uses the artifactId as the default image name.

If I use:

```
quarkus.container-image.name=hide-and-seek-place-service
```

It works.

### Expected behavior

It should use the set image name, at least try to resolve it, and fails, or at least report something instead of switching silently to the default name.

### Actual behavior

It does not.

**Comment by geoand** [comment]
@cescoffier that's the expected behavior because `application.name` is not a property that exists.

If you use `quarkus.container-image.name=hide-and-seek-${quarkus.application.name}` it should work. Can you try?

**Comment by cescoffier** [comment]
Yes, that's my point; it should NOT go back to the default without telling anything. Either fail (you're dumb - that property does not exist) or replace it using an empty string.

**Comment by cescoffier** [comment]
(I would prefer a failure - as mandatory properties are ... mandatory)

**Comment by geoand** [comment]
That's how Smallrye Config works ATM. If we want to change the expected behavior, we would need to make the change there - we would need @radcortez for this.

**Comment by cescoffier** [comment]
Yes, I agree. At least having a BIG warning telling me that something is wrong and I may do something really wrong (which was the case, as now I've lots of images in my docker registry)

**Comment by cescoffier** [comment]
BTW, while is this log printed twice:
```
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -jar, quarkus-run.jar]
[INFO] [io.quarkus.container.image.jib.deployment.JibProcessor] Container entrypoint set to [java, -Djava.util.logging.manager=org.jboss.logmanager.LogManager, -jar, quarkus-run.jar]
```

**Comment by geoand** [comment]
Dunno, I am not seeing this

**Comment by radcortez** [comment]
The issue is not with SmallRyeConfig. It is how is mapped.

If you map it as a `String` and if an expansion value does not exist, you get a `NoSuchElementException`. If you map it as an `Optional<String>` and if an expansion value does not exist, you get an empty `Optional`. 

The `ConfigRoot` is mapped as an `Optional`:
https://github.com/quarkusio/quarkus/blob/9e3b81315c1931ed320c1ccbfc4f1cd037e21b6a/extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java#L27

And the extension does silently fallback to the application name if there is no value:
https://github.com/quarkusio/quarkus/blob/177ddeb2f047a80d292e85cc9b29b208912a9a19/extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageProcessor.java#L91-L93

**Comment by geoand** [comment]
Thanks @radcortez for the analysis!

I'll have a closer look.

**Comment by radcortez** [comment]
BTW, since the `@ConfigRoot` sets a default:
https://github.com/quarkusio/quarkus/blob/9e3b81315c1931ed320c1ccbfc4f1cd037e21b6a/extensions/container-image/deployment/src/main/java/io/quarkus/container/image/deployment/ContainerImageConfig.java#L25-L27

There is not much value in mapping this with an `Optional`, unless the configuration is explicitly emptied in the configuration with `quarkus.container-image.name=`.

**Comment by geoand** [comment]
So if we did:

```java
 @ConfigItem(defaultValue = "${quarkus.application.name:unset}") 
 @ConvertWith(TrimmedStringConverter.class) 
 public String name; 
```

the expected behavior would be for `quarkus.container-image.name=hide-and-seek-${application.name}` to fail?

**Comment by geoand** [comment]
Understood: https://github.com/quarkusio/quarkus/pull/33560

**Comment by cescoffier** [comment]
Wow! Thanks @radcortez for the explanation! It makes sense! We should document that somewhere, as I'm sure lots of extension author do not see the difference of behavior!

**Comment by geoand** [comment]
+100 for documenting it!
