### ISSUE TITLE
Localization does not work in Qute message bundles

### ISSUE THREAD

**Issue by dscoppelletti** [quarkusio/quarkus#33774]
### Describe the bug

I have written I type-safe Message Bundles `MyMessages` with namespace `testMsg` and two messages `header` (default "Label") and `greeting` (default "Hello").  
I have written a `messages/testMsg_it.properties` file for localize the messages: `header` is "Etichetta" e `greeting` is "Ciao".  
I have used the `header` message in a Qute template using the sintax `{testMsg:header()}`.  
I have used the `greeting` message in Java using the injection of the `MyMessages` interface.  
Finally I have tested my Web App using my browser configured for Italian language.

### Expected behavior

Message `header` must be resolved to "Etichetta"
Message `greeting` must be resolved to "Ciao"

### Actual behavior

Message `header` is resolved to "Etichetta" (localization OK)
Message `greeting` is resolve to "Hello" (localization KO)

### How to Reproduce?

Reproducer: [quarkustest.zip](https://github.com/quarkusio/quarkus/files/11625693/quarkustest.zip)

Try the page `localhost:8080/test`.  
The method handler also logs the `Accept-Language` header.

### Output of `uname -a` or `ver`

MAC OSX 13.4 x86_64

### Output of `java -version`

17.0.6

### Quarkus version or git rev

3.0.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.8.8

**Comment by mkouba** [comment]
Thanks for the report @dscoppelletti. I believe that it works as expected because the `greeting` value is obtained directly from the injected default message bundle, i.e. `MyMessages`. You would either need to qualify the injection point with the `@io.quarkus.qute.i18n.Localized` and hard-coded IETF language tag (I'm not sure if that's possible with lombok) or use the message bundle in the template, i.e. replace `{model.greeting}` with `{testMsg:greeting}`. Finally, you can also obtain the correct message bundle programmatically via `io.quarkus.qute.i18n.MessageBundles#get()`, e.g. `MessageBundles.get(MyMessages.class, Localized.Literal.of(language))` in your test, or something along these lines.

**Comment by mkouba** [comment]
> So I can't inject a localized MessageBundle at runtime dependending on current request locale just like I can do with Templates, am I right? It's a pain!

No, you can't. Like I said you would need to obtain the correct message bundle with `MessageBundles.get()`... In fact, you can also `@Inject Instance<MyMessages> instance` and then obtain the bundle with `instance.select(Localized.Literal.of(language)).get()`.
