### ISSUE TITLE
Finalize the QuarkusComponentTest API

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#33827]
### Description

This is a follow-up of https://github.com/quarkusio/quarkus/pull/33607.

`QuarkusComponentTest` is now an experimental feature.

We should find answers for the following questions before it gets stable:

- Should we try to find a better name for `@ConfigureMock` ?
- Is there anything else that would be needed for component/unit testing?
- Should we make it more clear so that users have a more consistent understanding of what gets mocked?
- Should we replace the `@QuarkusComponentTest` with `@QuarkusTest(goFast=true)` or similar?

**Comment by mkouba** [comment]
CC @holly-cummins @geoand @Ladicek @stuartwdouglas

**Comment by mkouba** [comment]
We will need to reimplenent/mock some of the features provided by the arc extension, e.g. `@LookupIfProperty` and `@IfBuildProperty`.

**Comment by holly-cummins** [comment]
So that we can see the relationships between things in the bigger picture, I've tried to make some tables. To muddy the waters further, I threw in contract testing. :) 

I'm hoping these will 
- Guide us to the simplest user experience
- Be a useful starting point for some docs

These are very rough, with errors and gaps, so we can refine them.

## Class-level annotations
| | | | |
|:----|:----|:----|:----|
| |*Notional’ test pyramid level*|*Implications for mocks*|*Implication for dev services*| 
|`@QuarkusUnitTest`|N/A, for testing extensions| 
|no annotation|Unit test|All mocking must be manual. No CDI support.| Not possible|
|`@QuarkusComponentTest`|Unit test (but higher up the pyramid than with no annotation)|Everything is mocked, unless explicitly mentioned in the annotation or ‘de-mocked’ with `@Inject`. Mocks can be accessed for configuration using `@ConfigureMock`.| 
|`@QuarkusTest`|Integration test (in-process)|Everything is real, unless made into a mock with `@InjectMock` (for that test) or `@Mock` (for all tests)| 
|`@QuarkusIntegrationTest`|Integration test (out of process)|Everything is real (is this right, or does `@Mock` still work?)|Not used| 
|`@QuarkusContractTest`  (does not actually exist! but it’s a style we may want to think about)|Contract testing|With vanilla pact, mocking happens at the HTTP layer. We may want to change this to have an `@ContractMock` annotation at the rest client layer. … or something| 

## Annotations for field injection/mocking

| |Behaviour in test class|Implications for implementation classes|Valid contexts|Mocking library support| | |
|:----|:----|:----|:----|:----|:----|:----|
|`@Inject`| |None, unless the test is a `QuarkusComponentTest`. In that case, @Inject forces the injected thing to be real. |Everywhere|N/A, it’s not a mock … except if an `@Mock` is on the prowl elsewhere in the codebase.| | |
|`@InjectMock`|Injects a mock, which can be configured.|Changes the behaviour of @Inject globally so that what gets injected is a mock.|Anywhere except `@QuarkusComponentTest`|Only in `quarkus-junit5-mockito`. Mockito-specific.| | |
|`@ConfigureMock`|Injects a mock, which can be configured.|None (the thing would already have been a mock)|Only `QuarkusComponentTest`|`quarkus-junit5`. Will use whatever mocking system `@QuarkusComponentTest` uses| | |
| | | | | | | |
|`@Mock`|Trick question! Cannot be used in a test class (but [people may try](https://stackoverflow.com/questions/76427256/resourceinfo-mock-not-working-throwing-npe-in-quarkustest/76429939#76429939).|Changes the behaviour of `@Inject` globally (and across all tests) so that what gets injected is the mock defined in the `@Mock` class|Only in a standalone implementation|`quarkus-junit5`. Not compatible with Mockito.| | |

**Comment by mkouba** [comment]
The experimental status was removed in [3.13.0.CR1](https://github.com/quarkusio/quarkus/pull/41324). The API is now stable and the only remaining (but a bit more general) issue is the naming.
