### ISSUE TITLE
Keycloak integration | Make keycloak.json (or keycloak properties) not mandatory in multitenant scenario

### ISSUE THREAD

**Issue by reste85** [quarkusio/quarkus#3396]
**Description**
I've implemented the KeycloakConfigResolver due to the fact that our backend service must deal with multiple tenants. In that situation, why must i specify a keycloak.json file (or properties) inside resources folder? I know that can be useful as a "default fallback", but in some cases we just don't want something like this. Imagine a sidecar service which intercepts calls before forwarding to the underlying microservice. In this case we'll have:

- Several tenants configuration
- Clients in configurations could be different from one another
- files named as the realm name (we intercept the JWT and resolve the config path extracting the realm name from the iss field)

It could be useful to remove the default?

**Implementation ideas**
I can imagine a specific boolean property to be specified in application.properties, in case we don't want to preload the default configuration from keycloak.json file.

**Comment by sberyozkin** [comment]
@reste85 IMHO it is a reasonable request. Can you please consider creating a simple PR for @pedroigor and @sebastienblanc to review ? 

Minor suggestion: instead of adding a boolean property, may be just check the custom `KeycloakConfigResoiver` first, if it is available - then it is up to it how to do the per-request configuration resolution, otherwise continue preloading.  @pedroigor, @sebastienblanc, does it sound reasonable ?

**Comment by reste85** [comment]
@sberyozkin Unfortunately not yet, we've a lot of stuff to do and it's not something i can do soon. I'm sorry, maybe in next weeks i can take a look...

**Comment by sberyozkin** [comment]
@reste85 Please watch #4448
