### ISSUE TITLE
Index dependency env vars are not honored

### ISSUE THREAD

**Issue by amoscatelli** [quarkusio/quarkus#34037]
### Describe the bug

According to : 
https://quarkus.io/guides/all-config

QUARKUS_INDEX_DEPENDENCY__DEPENDENCY_NAME__GROUP_ID
QUARKUS_INDEX_DEPENDENCY__DEPENDENCY_NAME__ARTIFACT_ID

env vars can be used.

Right now, this is not working. An example will follow.

using application.properties is working : 

quarkus.index-dependency.problem-details.group-id=com.github.t1
quarkus.index-dependency.problem-details.artifact-id=problem-details-ri

using lower case env vars is working : 

quarkus.index-dependency.problem-details.group-id=com.github.t1
quarkus.index-dependency.problem-details.artifact-id=problem-details-ri

using documented upper case env vars is not working :

QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__GROUP_ID=com.github.t1
QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__ARTIFACT_ID=problem-details-ri

### Expected behavior

QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__GROUP_ID=com.github.t1
QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__ARTIFACT_ID=problem-details-ri

should be honored

### Actual behavior

QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__GROUP_ID=com.github.t1
QUARKUS_INDEX_DEPENDENCY__PROBLEM_DETAILS__ARTIFACT_ID=problem-details-ri

is not honored and the dependency is not added to index

### How to Reproduce?

Try to index a dependency using documented environment variables

### Quarkus version or git rev

3.1.0 Final

**Comment by gsmet** [comment]
Have you tried:
```
QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_GROUP_ID=com.github.t1
QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_ARTIFACT_ID=problem-details-ri
```
?

Note that I removed the double underscores.

**Comment by amoscatelli** [comment]
> Have you tried:
> 
> ```
> QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_GROUP_ID=com.github.t1
> QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_ARTIFACT_ID=problem-details-ri
> ```
> 
> ?
> 
> Note that I removed the double underscores.

Just tried but it doesn't work.

The only working combinations are in application.properties or envs with lower case style.

**Comment by geoand** [comment]
cc @radcortez

**Comment by radcortez** [comment]
Please check https://quarkus.io/guides/config-reference#environment-variables.

It is simply not possible to correctly map `QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_GROUP_ID` to its dotted name format, due to the mix-ins of dots and dashes. In these cases, you need to use the dotted name format (could be empty), so we know to which property name you want to refer to:

```application.properties
quarkus.index-dependency."problem-details".group-id=
quarkus.index-dependency."problem-details".artifact-id=
```

**Comment by mkouba** [comment]
> Please check https://quarkus.io/guides/config-reference#environment-variables.
> 
> It is simply not possible to correctly map `QUARKUS_INDEX_DEPENDENCY_PROBLEM_DETAILS_GROUP_ID` to its dotted name format, due to the mix-ins of dots and dashes. In these cases, you need to use the dotted name format (could be empty), so we know to which property name you want to refer to:
> 
> ```ini
> quarkus.index-dependency."problem-details".group-id=
> quarkus.index-dependency."problem-details".artifact-id=
> ```

I don't understand how this should work. The doc is clear that config searches several environment variables for a given property name, e.g. for `quarkus.index-dependency."problem-details".group-id` it should search exact match, replace non-alphanumeric chars with `_`, etc. In other words, the config does not map an ENV variable to a config property but the other way around, it should attempt to find an ENV variable for a property. 

@radcortez Are you talking about the _"In some situations, looking up the exact property name is impossible. For instance, when looking up a configuration that is part of a Map, ..."_ part? If so then maybe we should highlight this part somehow, maybe even extract the paragraph in a separate admonition of type IMPORTANT/CAUTION/WARNING. 

WDYT?

**Comment by radcortez** [comment]
> I don't understand how this should work. The doc is clear that config searches several environment variables for a given property name, e.g. for `quarkus.index-dependency."problem-details".group-id` it should search exact match, replace non-alphanumeric chars with `_`, etc. In other words, the config does not map an ENV variable to a config property but the other way around, it should attempt to find an ENV variable for a property.

Yes, but in this case, the segment `"problem-details"` is dynamic (the `Map` key). There is no way for us to know which such names in advance to perform the lookup and apply the mapping ENV rules. In these cases, we need to iterate the list of the property names. Now consider:

If we get a single property in the names list from the ENV source `QUARKUS_INDEX_DEPENDENCY__DEPENDENCY_NAME__GROUP_ID`, how do we remap this back to its original format? The issue is that there is a loss of information because a `_` can either be a dot or a dash. For instance, both dotted properties `quarkus.index.dependency."dependency-name".group-id` and `quarkus.index.dependency."dependency.name".group-id` have the same environment variable representation. By default, we map the ENV name always with dots, because we don't know where the dashes could be.

Now, if you also include a property `quarkus.index.dependency."dependency-name".group-id` in any source (can be empty), plus the ENV name, we know have both properties in the list. This will provide us enough information to determine that `QUARKUS_INDEX_DEPENDENCY__DEPENDENCY_NAME__GROUP_ID` is `quarkus.index.dependency."dependency-name".group-id`, so now the matching works as expected.

> @radcortez Are you talking about the _"In some situations, looking up the exact property name is impossible. For instance, when looking up a configuration that is part of a Map, ..."_ part? If so then maybe we should highlight this part somehow, maybe even extract the paragraph in a separate admonition of type IMPORTANT/CAUTION/WARNING.

Correct.

**Comment by mkouba** [comment]
Ok, how about this: https://github.com/quarkusio/quarkus/pull/34366 ?

**Comment by radcortez** [comment]
Sure. Thanks!
