### ISSUE TITLE
Wrong hibernate dialect version detected for MS Sql Server

### ISSUE THREAD

**Issue by DavideD** [quarkusio/quarkus#34032]
### Describe the bug

It's possible to see this [updating one of the quickstart to use MS SQL Server](https://github.com/DavideD/quarkus-quickstarts/tree/mssql-sequence-final/hibernate-reactive-quickstart).

Quarkus will start an instance of MS SQL server 2019-latest (shouldn't we update it to 2022?) and use as dialect:
```
HHH035001: Using dialect: org.hibernate.dialect.SQLServerDialect, version: 10.0
```

The workaround is to set a custom dialect using the property `quarkus.hibernate-orm.dialect=org.acme.hibernate.reactive.SqlServerDialect`:

```java
package org.acme.hibernate.reactive;

import org.hibernate.dialect.DatabaseVersion;
import org.hibernate.dialect.SQLServerDialect;

public class SqlServerDialect extends SQLServerDialect {
	public SqlServerDialect() {
		super( DatabaseVersion.make( 15 ) );
	}
}
```

I've tested this with Hibernate Reactive and Quarkus 3.1.1

**Comment by gavinking** [comment]
The workaround is pretty bad, so this one is important.

**Comment by DavideD** [comment]
Maybe @Sanne or @yrodiere have some insight about this? I think it has to do with Quarkus start up and the fact that a database might not be present. So, [Quarkus set a default dialect](https://github.com/quarkusio/quarkus/blob/33db72dbb0c56651a2a3da83c08af6e4b725a1b0/extensions/hibernate-reactive/deployment/src/main/java/io/quarkus/hibernate/reactive/deployment/HibernateReactiveProcessor.java#L247).

**Comment by DavideD** [comment]
Maybe I can just update the default for Sql Server?

**Comment by DavideD** [comment]
Ah, I think this class is just behid compared to the ORM one. I will try to update it

**Comment by yrodiere** [comment]
Quarkus sets the dialect and DB version at build time. Technically during static init, but the rule in Quarkus is that anything done at static init must be assumed to happen at build time -- I tried to challenge that, but no luck so far as it implies degraded functionality in native mode.

Anyway, the thing is: Hibernate ORM in Quarkus it cannot detect the version running on the server, since the version is set before the application starts.

By default it will assume the minimal supported version, i.e. SQL Server 2016: 

https://github.com/quarkusio/quarkus/blob/0a6d90945ef528d30dbe0800f28b08c81f87d347/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/config/DialectVersions.java#L20

Setting a custom dialect is not the correct solution. If you want a more recent version, you can configure it explicitly:

https://quarkus.io/guides/hibernate-orm#hibernate-dialect

**Comment by yrodiere** [comment]
Now I'm having a look why the dialect version is wrong... I suspect it might be related to a different handling of `jakarta.persistence.database-product-version` in Hibernate Reactive compared to Hibernate ORM? Checking.

**Comment by yrodiere** [comment]
@DavideD It looks like the problem is in the Hibernate Reactive extension in Quarkus; namely `HibernateReactiveProcessor` doesn't have an equivalent to `io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#collectDialectConfig` in Hibernate ORM.

**Comment by DavideD** [comment]
> Setting a custom dialect is not the correct solution. If you want a more recent version, you can configure it explicitly:

Ah, thanks. I was wondering if there was something like that.

> HibernateReactiveProcessor doesn't have an equivalent to io.quarkus.hibernate.orm.deployment.HibernateOrmProcessor#collectDialectConfig 

Yep, I will have a look

**Comment by DavideD** [comment]
I'm struggling with this issue. @yrodiere do you have time to have a look at it?

I've copied the method in HibernateOrmProcessor but I don't know how to get the missing information.
You can find my progress here: [Optional<JdbcDataSourceBuildItem> jdbcDataSource,](https://github.com/DavideD/quarkus/commit/f7d17df73aad894d39dfa1050c6244f900751fb9#diff-0e6dba65e9fb565f0f6a85e937bcab1f9574091bfe5323a4965f085bbab07b5bR423)

I'm not sure how to get the jdbcDataSource or  the  info the method need to guess the dialect (also, working on Quarkus with my laptop takes ages).

**Comment by yrodiere** [comment]
> I'm not sure how to get the jdbcDataSource or the info the method need to guess the dialect

Just to be extra clear and avoid any misunderstanding, the only "guessing" going on here is related to the datasource Hibernate Reactive is going to use. There's no way we are going to detect the version running on the server, since this all happens at build time.

Basically Agroal gets told to create a datasource targeting DB of such kind and (optionally) such version, and Hibernate ORM extracts that information from `JdbcDataSourceBuildItem` to deduce its dialect and (optionally) the targeted DB version.

In your case since you're not using JDBC datasource, you will need some equivalent of `JdbcDataSource`, but for reactive datasources, not coming from Agroal but from reactive SQL clients. 

But... from what I can see, you have no such SPI, and currently the Hibernate Reactive extension is basically doing what Agroal does (parsing datasource config) to deduce the `dbKind`. See https://github.com/quarkusio/quarkus/blob/f7d17df73aad894d39dfa1050c6244f900751fb9/extensions/hibernate-reactive/deployment/src/main/java/io/quarkus/hibernate/reactive/deployment/HibernateReactiveProcessor.java#L165-L171 I guess you'll have to do something similar to that code get the `dbVersion`? Fortunately you only have to worry about the default datasource, since the Hibernate Reactive extension apparently only supports targetting the default datasource.

---

> also, working on Quarkus with my laptop takes ages

Something we can all empathize with, unfortunately. It helps if you do one large build first and only rebuild modified extensions/modules after that. See https://github.com/quarkusio/quarkus/blob/main/CONTRIBUTING.md#workflow-tips

---

BTW you might want to add tests similar to the ones we have for Hibernate ORM, e.g. `integration-tests/jpa-mssql/src/test/java/io/quarkus/it/jpa/mssql/DialectTest.java`/`integration-tests/jpa-mssql/src/main/java/io/quarkus/it/jpa/mssql/DialectEndpoint.java`. There's one per DB kind.
