### ISSUE TITLE
TLS improvements

### ISSUE THREAD

**Issue by cescoffier** [quarkusio/quarkus#34193]
### Description

Simplify and extend TLS support

- Central TLS configuration
- Acme / Let's encrypt support
- Allows using real certificates locally (dev and test mode)
- Certificate rotation support
- Cert Manager integration
- ...

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

**Comment by sberyozkin** [comment]
+1, and if we could reuse some of the production-ready Elytron code eventually then it would be great :-), CC @darranl

**Comment by sberyozkin** [comment]
@cescoffier Hi Clement, we've just talked with @maxandersen (not specifically about this issue, but it was related), as far as the certificate rotation is concerned, before we can have it supported in OpenShift, a POC can probably be realized as an integration test, where, vertx-http, in the running test endpoint, will detect a certificate file change and re-init the TLS connection - this is probably going to be the most challenging technical task since in OpenShift, the cert manager should be managing the actual certificate renewal and updating the shared certificate file location.

Also CC @fjuma, @darranl

**Comment by cescoffier** [comment]
Yes, the API to handle this use case on the Vert.x side has been added. Note that rotation is happening in many case (not only cert-manager). For example, ACME renewal.

**Comment by cescoffier** [comment]
Closing - all the mentioned tasks have been completed as part of the TLS Working Group (https://github.com/orgs/quarkusio/projects/24)
