### ISSUE TITLE
ParamConverter String to java.nio.file.Path

### ISSUE THREAD

**Issue by adamhenderson** [quarkusio/quarkus#34225]
### Describe the bug

When using a ParamConverter to convert from a String to a java.nio.file.Path results in an exception. New user defined classes work as expected

### Expected behavior

Alter creating a ParamConverterProvider class to register the conversion of a String, there should be evidence that the appropriate ParamConverter is registered and calls to REST API endpoints correctly convert the String to a Path.

### Actual behavior

When an endpoint is called that has a java.nio.file.Path as a parameter results in an exception.

When a simple wrapper class (PathWrapper.java) is created everything works as expected, logs show the ParamConverterProvider method being called for the PathWrapper but nothing related to java.nio.file.Path.

Additional observations

- the ParamConverterProvider.getConverter() method is also called multiple times on startup
- this failing behaviour also appears to happen with java.io.File.File as a parameter + defined converter (not demonstrated in reproducer)

### How to Reproduce?

Reproducer: https://github.com/adamhenderson/paramconverter-java.nio.file.path-reproducer

### Output of `uname -a` or `ver`

Darwin iMac.local 22.5.0 Darwin Kernel Version 22.5.0: Mon Apr 24 20:51:50 PDT 2023; root:xnu-8796.121.2~5/RELEASE_X86_64 x86_64

### Output of `java -version`

OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 19.0.1+10-jvmci-22.3-b08, mixed mode, sharing)

### Quarkus version or git rev

3.2.1.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.2 (c9616018c7a021c1c39be70fb2843d6f5f9b8a1c)

**Comment by geoand** [comment]
That passes the eyeball test :)

**Comment by FroMage** [comment]
Which eyeball test? The one where we roll our eyes? 🙄

`Path`, like `File`, is _special_, especially in the context of multipart. Not sure at all what a user `ParamConverter` would do, since we create them, for multipart bodies.

I'm curious what use there is for having a `ParamConverter` for them, provided it's unrelated to having that path point to a binary file containing the corresponding multipart body.

**Comment by gastaldi** [comment]
IMHO it's misleading to assume that `java.nio.file.Path` or `java.io.File` will only be used in multipart requests. The proof is that if you run the same code using RestEasy classic the converter is invoked.

**Comment by adamhenderson** [comment]
@FroMage In my use case it's a convenience to convert a String in the path param to a Path for addressing existing resources on a filesystem or other stores and not as part of an upload process. As @gastaldi points out, the behaviour is different to RestEasy classic.

**Comment by FroMage** [comment]
Well, it's different because our multipart support is different too.

Given that it seems to me much more natural to support `File/Path` to obtain data which is part of the body as uploads, this makes a lot of sense for multipart support, just like `byte[]` or `InputStream`, and as such, these types are _special_.

Also given that turning a `String` parameter into a `Path` seems to omit the filesystem part, I'm not sure how useful it really is, especially compared to how useful it is for multipart.

Finally, you can easily turn your `String` parameter into a `Path`.

I'm skeptical about adding support for this, it seems very confusing.

**Comment by geoand** [comment]
After reading through this again, I agree with @FroMage

**Comment by adamhenderson** [comment]
Thanks for looking into this and providing your views and explanations, happy to close along with maybe a note in the docs to point out the differences in case anyone else comes across this.

**Comment by geoand** [comment]
👍🏼
