### ISSUE TITLE
Generated values does not work with Mongo Panache

### ISSUE THREAD

**Issue by Tobbelobb2** [quarkusio/quarkus#34354]
### Describe the bug

I am trying to create a custom ID for my collection, always incrementing 1 to ID of the previous document.  This does not work, instead the standard ID field is generated. 

### Expected behavior

I am expecting that the following code generates a referenceNumber field which is used as an id, starting at 10.000: 

```
@MongoEntity(collection = "order")
public class Order extends PanacheMongoEntityBase {


    @Id
    @BsonId
    @SequenceGenerator(
            name = "referenceNumberSequence",
            sequenceName = "referenceNumber_seq",
            allocationSize = 1,
            initialValue = 10000)
    @GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "referenceNumberSequence")
    public Integer referenceNumber;
}
```

### Actual behavior

Instead the generated document contains an _id field, like normal, instead of my referenceNumber field. 
{
    "_id" : ObjectId("some_id"),
}

### How to Reproduce?

Create a new Order, call order.persist(), the persisted order has an _id field, not a referenceNumber field. I have tried naming my custom id "id", but it makes no difference.

### Output of `java -version`

18.0.2.1

### Quarkus version or git rev

3.0.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Mvn 3.8.4

**Comment by loicmathieu** [comment]
Same answer than in the Stackoverflow question https://stackoverflow.com/questions/76570442/custom-ids-with-panachemongoentitybase-does-not-work/76571521#76571521

@Id, @SequenceGenerator and @GeneratedValue are JPA annotations. MongoDB with Panache is not a JPA implementation on top of MongoDB so you cannot use them.

If you want such feature, you need to implement it manually, for example by using a sequence collection with a unique document and incrementing this document for each new document on your order collection.

To explain why the _id field is generated as normal it's because your referenceNumber is null so MongoDB will generate a default id.

**Comment by geoand** [comment]
I am going to close the issue as per @loicmathieu's comment
