### ISSUE TITLE
Resteasy Classic is not properly handling exceptions when serializing elements in a Java Stream

### ISSUE THREAD

**Issue by pedroigor** [quarkusio/quarkus#34419]
### Describe the bug

When an application is using a custom `ExceptionMapper` and `WriterInterceptor` and returning a Java Stream from its endpoint, it might happen that part of the elements in a stream is successfully written to the response even though subsequent elements fail during their serialization.

When the exception happens during serialization, Resteasy will invoke the custom `ExceptionMapper` and append whatever error response is added by it. In the end, the response might end up as:

```
[0,1,2,3,4,5,6,7,8] BAD Request
```

The response above is about returning a Java Stream from a JAX-RS method where an exception is through when serializing the 9th element in a Java Stream.

This behavior only happens if you have a custom `ExceptionMapper`, otherwise a proper error response from Resteasy Classic is returned to the client.

### Expected behavior

If any exception is thrown when serializing a Java Stream, the response body should hold only the error message from the `ExceptionMapper`.

### Actual behavior

If any exception is thrown when serializing a Java Stream, the response includes the elements in a stream that were successfully serialized and the error message from the `ExceptionMapper` appended at the end of the response body.

### How to Reproduce?

1. `git clone https://github.com/patrickjennings/quarkus-response-interceptor-streaming.git`
2. `cd quarkus-response-interceptor-streaming`
3. `mvn quarkus:dev`
4.  `curl http://localhost:8080/api/users`

As a result of the last step, you should get a response as follows:

```
[0,1,2,3,4,5,6,7,8]BAD Request
```

### Output of `uname -a` or `ver`

Linux fedora 6.3.8-200.fc38.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Jun 15 02:15:40 UTC 2023 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.7" 2023-04-18 OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7) OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-4.fc38) (build 17.0.7+7, mixed mode, sharing)

### GraalVM version (if different from Java)

N/A

### Quarkus version or git rev

3.1.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /pedroigor/development/tools/maven/current Java version: 17.0.5, vendor: Eclipse Adoptium, runtime: /pedroigor/development/sdk/java/jdk-17.0.5+8 Default locale: en_US, platform encoding: UTF-8 OS name: "linux", version: "6.3.8-200.fc38.x86_64", arch: "amd64", family: "unix"

### Additional information

This issue originates from https://github.com/keycloak/keycloak/issues/20451.

**Comment by alechenninger** [comment]
I shared this [on the original Keycloak issue](https://github.com/keycloak/keycloak/issues/20451#issuecomment-1613302906), but I don't think the expected behavior is valid for this use case. The reason you use a Stream, most likely, would be to avoid buffering the result set in memory before starting to send the response body on the wire. In this case, by the time you get an error, you've already sent part of the response. You can't "undo" that and instead send only the error response. So to accomplish the expected behavior you'd have to buffer the stream until it was done. This would recreate the heap allocation problem Streams would be used to solve. More details in the link.

**Comment by pedroigor** [comment]
What would be the expected behavior from a client's perspective then? For the use case I have in mind, they want either a success or an error response.

I wouldn't assume Java Streams solve heap allocation problems because it depends on how the underlying stack is handling them. At least for me, in Keycloak the idea of having streams everywhere is just adding complexity with little if any improvement to the runtime.

**Comment by alechenninger** [comment]
Just streaming from the HTTP interface alone doesn't guarantee you're not buffering somewhere before that, true. But in order to return large responses without risking heap exhausting, you need to be able to stream end to end, everywhere, including in the HTTP response. Just saying that if this ended up buffering in the HTTP layer, it would make other efforts to avoid buffering useless.

It is typical of end to end streaming to have this problem, because it is in the nature of the solution. It is why streaming commonly uses [jsonl](https://jsonlines.org/) for example (such as in grpc-gateway). I have to imagine the resteasy reactive types have a similar challenge.

From the client's end, most errors occur before results start to be returned (Hynek mentioned this also). If there is an error while streaming, I gave a few options in the Keycloak comment. Just returning an invalid response is a valid resolution. As Marek pointed out, it is the same semantic (a server-related error where there's nothing the client can do but retry), either way. It is also possible to serialize the error as an element in the array, or as a top level (bottom) field in the response, while still streaming, and still adhering to valid JSON, but it would require changing the response schema. Personally, I suggest resteasy behaves consistently between `Stream`, and other reactive types like `Flux` or `Multi`, whatever that is.

Whether or not Keycloak wants to stream end to end is a different matter I guess, but FWIW I have seen this approach improve reliability and latency in a prior large scale service I've worked with personally (though that service routinely had larger responses).

**Comment by hmlnarik** [comment]
I don't think this is a bug on Quarkus side. However I can see a room for improvement - if Quarkus offered a buffer for response which would save the beginning of the response and which would be discarded if there is an exception. If an exception would be thrown after the buffer is flushed to the wire, it would still lead to broken response, but this is IMO acceptable since it is more likely that a serialization exception would be thrown in the beginning of the stream than at the end.

**Comment by geoand** [comment]
Ultimately this comes down to the fact that `org.jboss.resteasy.plugins.providers.jackson.ResteasyJackson2Provider` closes the output stream [here](https://github.com/resteasy/resteasy/blob/6.2.4.Final/providers/jackson2/src/main/java/org/jboss/resteasy/plugins/providers/jackson/ResteasyJackson2Provider.java#L348), even though an IOException was thrown from Jackson.

There is nothing Quarkus can do here unfortunately...

**Comment by pedroigor** [comment]
@geoand But why it happens only when using a custom write interceptor? Even though it is just moving forward in the interceptor chain?

I could not see the relation when debugging ...

**Comment by geoand** [comment]
It seems that when interceptors are not used, `org.jboss.resteasy.core.messagebody.AsyncBufferedMessageBodyWriter` comes into play, and that uses a `ByteArrayOutputStream` as a buffer in front of the actual `OutputStream` - so when the error happens and `ResteasyJackson2Provider` closes the stream, nothing really happens (i.e. nothing is flushed to the real stream)

**Comment by pedroigor** [comment]
So it might still happen that depending on the buffer capacity and how much that was written to the buffer before the exception is thrown, the response will end up with the same problem. Makes sense?

**Comment by geoand** [comment]
Yup

**Comment by pedroigor** [comment]
And it does not happen with Resteasy Reactive.

**Comment by geoand** [comment]
It does not, but it theoretically could if the Stream is large and exceeds the bufer size
