### ISSUE TITLE
Generated-sources not resolved in dev mode

### ISSUE THREAD

**Issue by yntelectual** [quarkusio/quarkus#3450]
hi there,

**Describe the bug**
Using annotation processor e.g. mapstruct, the generated sources end up in `target/generated-sources` folder. Compilation works fine, however during dev mode, these generated classes are not present in classpath, causing ClassNotFoundError.
This seems to be a regression from version 0.19.0 as it works fine there.

**Expected behavior**
Generated classes should be present in classpath in dev mode.

**Actual behavior**
Classes from `generated-sources` produced by annotation processor are not present in classpath in dev mode.

**To Reproduce**
You can use the Mapstruct-quarkus example project: https://github.com/mapstruct/mapstruct-examples/tree/master/mapstruct-quarkus and test it. With version >=`0.19.0` it works fine, bumping the version up to `0.20.0` breaks the dev mode.

**Comment by seseso** [comment]
I found that same error when I upgraded my project from version 0.15.0 to 0.20.0.

I was using jsonschema2pojo to generate some classes but after upgrading, the run stopped working. In the meantime, and since my code is stable, I included the generated sources on my source tree but it would be great to have it work as it should!

I'll keep an ey on this one!

**Comment by atzoum** [comment]
I can confirm that this bug is still present in `0.21.1`. This is keeping us from upgrading from `0.19.0`

**Comment by yntelectual** [comment]
resolved by #3613 in master
