### ISSUE TITLE
OIDC Logout doesn't work after 5 minutes

### ISSUE THREAD

**Issue by zeppelinux** [quarkusio/quarkus#34592]
### Describe the bug

Quarkus OIDC logout functionality works as expected immediately after user logged in, but fails after 5 minutes. It doesn't matter if user is idle or triggering some Ajax requests. 

### Expected behavior

After clicking on Logout link user is logged out.

### Actual behavior

Clicking on logout link fails with:
`{"errorId":"4e309bd4-1537-4799-8ec5-9f51cf15e53c","errors":[{"path":"An error has occurred. If you are not clear how to fix it on your end - please contact support.","message":"RESTEASY003210: Could not find resource for full path: https://dev.collarclubvernon.ca/secure/logout"}]}`

Or with 'Page Not found', depending from the web app error handling.

### How to Reproduce?

Reproducer project (created from https://github.com/melloware/quarkus-faces) can be cloned from here https://github.com/zeppelinux/quarkus-oidc-reproducer

To reproduce:
1. mvn clean compile quarkus:dev (it uses Dev services for Keycloak deployment, requires Docker)
2. Navigate to  http://localhost:8081
3. Login with bob:bob
4. Click on 'Log Out' link in the toolbar and see it logs out successfully
5. Login again . You can click some buttons or navigate to different pages.
6. Wait 5 min
7. Try to logout
8. Observe 'Page Not Found' and the actual logout did not happen

### Output of `uname -a` or `ver`

Mac OS Ventura 13.4

### Output of `java -version`

openjdk version "17.0.2" 2022-01-18 OpenJDK Runtime Environment (build 17.0.2+8-86) OpenJDK 64-Bit Server VM (build 17.0.2+8-86, mixed mode, sharing)

### Quarkus version or git rev

3.2.0.Final

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.8.6 (84538c9988a25aec085021c365c560670ad80f63) Maven home: /usr/local/Cellar/maven/3.8.6/libexec Java version: 17.0.2, vendor: Oracle Corporation, runtime: /Users/dimas/Library/Java/JavaVirtualMachines/openjdk-17.0.2/Contents/Home Default locale: en_CA, platform encoding: UTF-8 OS name: "mac os x", version: "13.4", arch: "x86_64", family: "mac"

**Comment by sberyozkin** [comment]
@zeppelinux I think I've found the problem - it is related to the auto-refresh - Ajax timer is pinging Quarkus to keep auto-refreshing the session, this is fine. 

When `Log out` is pressed, the token is verified, before attempting to logout the user, and it can be found to be nearly expired (Keycloak admin UI which you can access from `/q/dev` shows the session is about 10 mins, so if the ID token is more than 5 mins old it gets into the auto-refresh brackets configured in Quarkus config), and then an attempt is made to auto-refresh which breaks the logout flow - I'll fix it, trying to auto-refresh the session which is about to be terminated makes no sense, it is a bug.

**Comment by sberyozkin** [comment]
@zeppelinux For now, you can temp disable the timer and the auto-refresh config, please only make sure that Log Out is intercepted to handle 499.

**Comment by zeppelinux** [comment]
> @zeppelinux For now, you can temp disable the timer and the auto-refresh config, please only make sure that Log Out is intercepted to handle 499.

@sberyozkin Thanks a lot for quick turnaround! 
Just to clarify - the Log Out link invokes normal http GET request, i.e. there is no 499  if it fails.

**Comment by sberyozkin** [comment]
@zeppelinux OK. FYI: #34610

**Comment by sberyozkin** [comment]
@zeppelinux FYI, you will also need to handle timer errors - I haven't really found in Keycloak Admin Console how to change it, but I'm seeing a few exactly the same errors reported on the web:
```
2023-07-07 18:37:10,803 DEBUG [io.qua.oid.run.OidcProviderClient] (vert.x-eventloop-thread-3) Request has failed: status: 400, error message: {"error":"invalid_grant","error_description":"Token is not active"}
```

when the refresh grant is attempted. So in your reproducer, if you login, and then just sit for 5+ mins, there would be 5+ timer pings and then the SPA, without me pressing anything, goes to the Keycloak login page.

The reason behind it, is that after 5 or so pings, the refresh token grant fails - but your SPA timer, in this case of 499, should just ignore it and as I said in Zulip, may be stop and restart in 10 mins or so, or start pinging at longer intervals says every 10 mins, because in meantime, user will at some point will press Logout, and then login again, or the regular Ajax call will cause reauthentication, which will refresh not only ID but also refresh token.

The reason the refresh grant fails is Keycloak specific - but as suggested in Zulip - it may because the refresh token has already expired or its usage count is limited or may be for some other reasons, but whatever the reason behind its failure is, the timer should be prepared to handle the errors

thanks

**Comment by sberyozkin** [comment]
The timer should be stopped after the logout too - so may you'd want to move the logout into the script

**Comment by melloware** [comment]
Also @zeppelinux you have an incorrect import...

```xml
<h:outputStylesheet name="css/layout-dark.css" library="freya-layout"/>
```

That stylesheet does not exist and is throwing MyFaces warning. For this demo that sheet can probably be removed.
