### ISSUE TITLE
ManagedExecutorTest TCK override current context: is ti valid?

### ISSUE THREAD

**Issue by franz1981** [quarkusio/quarkus#34598]
https://github.com/quarkusio/quarkus/pull/34310#issuecomment-1617500255 for more info

https://github.com/quarkusio/quarkus/pull/34310 has removed the context state assertion via 6de045cf4d6bbeadd74b51eecb7e733ac14b831b , be we still need to understand if that's valid or we should enforce/detect it somehow.

The reason for that is that we would like to guarantee a race free (request) context activation, given that we are not managing replacing any current context nor we have idea what it means for users.

**Comment by franz1981** [comment]
@mkouba that's it :)

**Comment by franz1981** [comment]
@manovotn too

**Comment by manovotn** [comment]
I am not sure how much of it I'll understand but I can look at it on Mon once I am back from my PTO :)

**Comment by manovotn** [comment]
@franz1981 @mkouba looking at this and the related issue, I think the assertion shouldn't be there.

Quoting Martin's comment from linked issue:

> It seems that the captured `ContextState` is not valid anymore but the current context is set. I have no idea if this is legal from MP CP POV. But it probably is because the code in `io.quarkus.arc.runtime.context.ArcContextProvider.ContextSnapshot.begin()` simply tests the validity of the context and passes null if it's not, thus effectively overrides the current context.

MP CP as such has no notion of `ContextState`, that's something we added so that we are are able to determine at what point the the previously saved context expired (was destroyed by Arc).
This is here because MP CP can in some cases capture a state and then try to reuse it at a later point - this means the snapshot can outlive the original CDI req. context that Arc destroyed in the meantime. In such case, we default to creating a fresh req. context.

**Comment by manovotn** [comment]
Can we close this issue or is the answer I provided not what you were looking for @franz1981?
