### ISSUE TITLE
Inconsistent API of Mongo Kotlin PanacheMongoRepositoryBase and ReactivePanacheMongoRepositoryBase

### ISSUE THREAD

**Issue by hantsy** [quarkusio/quarkus#34623]
### Description

I used `persist` fun from [PanacheMongoRepositoryBase](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache-kotlin/runtime/src/main/kotlin/io/quarkus/mongodb/panache/kotlin/PanacheMongoRepositoryBase.kt) and [ReactivePanacheMongoRepositoryBase](https://github.com/quarkusio/quarkus/blob/main/extensions/panache/mongodb-panache-kotlin/runtime/src/main/kotlin/io/quarkus/mongodb/panache/kotlin/reactive/ReactivePanacheMongoRepositoryBase.kt), but found the former does not return an value, and in the later API, it returns the result in the reactive stream.

### Implementation ideas

Personally I would like it returns result, it is also easy to mock it in tests.

**Comment by loicmathieu** [comment]
Hi,
This has already been brought up, on the imperative version, when you persist an entity, you still have access to the persisted entity so you can check it's ID.
On reactive it's usually not that easy because your code is generally inside a pipeline of operations so you need to return the entity to be able to access it after persist.
The API is also the same on Hibernate.

Code example (not tested)

Imperative:
```java
public Response create(MyEntity myEntity) {
    myEntity.persist();
    return Response.created("/v1/my-entities/" + myEntity.getId());
}
```

Reactive:
```java
public Uni<Response> create(MyEntity myEntity) {
    return myEntity.persist().transform(entity -> Response.created("/v1/my-entities/" + entity.getId()))
}
```

So I would say "that ship has sailed" :(

**Comment by geoand** [comment]
@loicmathieu if this is not going to be addressed, by close the issue and add the proper label.

Thanks a lot

**Comment by hantsy** [comment]
```java
public Response create(MyEntity myEntity) {
    myEntity.persist();
    return Response.created("/v1/my-entities/" + myEntity.getId());
}
```
This is really a bad idea, for most best practice of software design guidelines, the input argument should be immutable. Of course, I know the EntityManager.persist follow the same style.

**Comment by loicmathieu** [comment]
This is the MongoDB POJO Codec that does this: when no id are set it sets one.
