### ISSUE TITLE
make quarkus swagger/openapi properties runtime

### ISSUE THREAD

**Issue by debu999** [quarkusio/quarkus#34745]
### Description

[quarkus.smallrye-openapi.info-title](https://quarkus.io/guides/all-config#quarkus-smallrye-openapi_quarkus.smallrye-openapi.info-title)
[quarkus.swagger-ui.title](https://quarkus.io/guides/all-config#quarkus-swagger-ui_quarkus.swagger-ui.title)

As we can see the above 2 are build time properties, can this be changed to run time properties.

In any pipeline we need to build once for UAT and PROD and the swagger for UAT and PROD shows title as PROD.

we have to use -Dquarkus.profile=uat,prod in most of the cases during builds but ideally the rest apis remains same and swagger is same but the title should be env specific. Can we make the above 2 properties runtime instead of buildtime.

**Comment by gsmet** [comment]
The OpenAPI document is generated at build time so we can't really do that without changing drastically how things are done.

I don't think we want to do that for now but if others have this issue, please add a comment here so that we can collect feedback about it and potentially reconsider our decision.

I will close this for now.
