### ISSUE TITLE
Getting a different instance when injecting @ApplicationScoped in a test

### ISSUE THREAD

**Issue by ia3andy** [quarkusio/quarkus#3478]
**Describe the bug**
Trying to reproduce this guide to spy on a service: https://quarkus.io/guides/getting-started-testing#mock-support

I encountered an issue with the `@ApplicationScoped` annotation. I get different instance between the one injected in the app and the one in the test. 

*Using `@Singleton` solved the problem.*

**Expected behavior**
I am not sure about the expected behavior.

**Actual behavior**
Getting different instance

**To Reproduce**
[bug-test-inject.zip](https://github.com/quarkusio/quarkus/files/3491517/bug-test-inject.zip)

CC @mkouba @gsmet @geoand

**Comment by mkouba** [comment]
Hi @ia3andy, this is not a bug. The `ExampleService` is a normal scoped bean and therefore a client proxy is injected instead of a direct reference. A client proxy has no state (hence `ExampleService.callRef` is `null`) and delegates all method calls to the current instance.

To fix your test simply add a getter for `ExampleService.callRef` and use this getter instead of the direct access in your test.

It works for `@Singleton` because it does not require a client proxy to be injected. See [What’s the difference between @ApplicationScoped and @Singleton?](http://weld.cdi-spec.org/documentation/#13)  Weld FAQ entry for more info.

**Comment by ia3andy** [comment]
Thanks @mkouba!! Very nice explanation..
