### ISSUE TITLE
OIDC: 401 instead of new challenge when token expired or uses hits back button

### ISSUE THREAD

**Issue by effusion** [quarkusio/quarkus#34806]
### Describe the bug

Since the Update to Quakrus 3 when a session expires, the HTML pages served by the App return a 401 Status code and can't be recovered without manual intervention. We currently use OIDC with Azure to implement the login. I found the following Tickets [33200](https://github.com/quarkusio/quarkus/issues/33200) and [33481](https://github.com/quarkusio/quarkus/issues/33481) but they did solve the problem.

### Expected behavior

If the Session runs out or the back button is used, the user should be redirected to the OIDC login page.

### Actual behavior

Quarkus writes a `q_auth_*` token into the cookie store if the session runs out and a new request is sent. This causes a 401 and blocks any further requests. The cookie needs to be deleted manually and a browser refresh is needed to trigger the auth_flow again.

### How to Reproduce?

Prerequisites:
Quarkus App with Azure AD configured as Identity Provider(incl 2FA) and an Index.html page in resources/META-INF/resources and a GrapqhQL Endpoint.

Option 1: 
1. Navigate to the index.html to trigger the auth_flow
2. Enter password and username
3. If on the 2FA Page press the back button
4. The app returns 401 and can not be recovered

Option 2: 
1. Navigate to /q/graphql-ui/ to trigger the auth_flow
2. Enter password and username
3. Enter 2FA Code
4. Wait until the token expires
5. Send a query over the UI. The request fails
6. Navigate to the index.html. The Server returns a 401

### Output of `uname -a` or `ver`

Mac OS 10.x Windows 10, 11

### Output of `java -version`

17.04

### Quarkus version or git rev

3.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

8.2.1

### Additional information

We have the following properties configured for the OIDC feature:

```
quarkus.http.auth.permission.root.enabled=true
quarkus.http.auth.permission.root.paths=/*
quarkus.http.auth.permission.root.policy=authenticated
quarkus.oidc.auth-server-url=<Azure AD URL>
quarkus.oidc.application-type=hybrid
quarkus.oidc.token.refresh-expired=true

quarkus.oidc.authentication.redirect-path=/
quarkus.oidc.authentication.restore-path-after-redirect=true

quarkus.oidc.authentication.scopes=profile,email
quarkus.oidc.authentication.cookie-same-site=lax
quarkus.oidc.roles.role-claim-path=roles
quarkus.oidc.token-state-manager.split-tokens=true
```

**Comment by sberyozkin** [comment]
@effusion As far as I understand it is not related to the expired sessions but as you have mentioned, orphaned state cookies, specifically, 401, I believe, can only happen if the current request contains no `state` URL query parameter - but there is an orphaned state cookie from an uncompleted previous authentication request - and the current request URL matches the callback URL .

`Option 1` fits this case precisely - you have started an authentication which creates a unique state cookie, then with the back button, without completing the authentication, start again, exactly matching the same request URL. Redirecting back to OIDC in such cases has a risk of the browser redirect loops - caused unintentionally or intentionally.

I think the easy fix is to have a more specific redirect path, example, `/callback`. With `/` it matches `/index.html` I guess.

That said, given a few recent issues like this one, I updated the code to allow redirecting instead of failing in such cases:
#34631.

I think #34631, with its `quarkus.oidc.authentication.fail-on-missing-state-param=false` fixes this issue. If you an orphaned/unmatched cookie 

Would you like to try the latest SNAPSHOT to verify, with this new property ? 

Or as I said, have a more specific callback path.

**Comment by effusion** [comment]
@sberyozkin thx for the swift response. I'll go through your suggestion and try it out.

**Comment by PatrickWolleb** [comment]
@sberyozkin I have fixed it with @effusion. We have changed the callback path from `/` to `/signin` where `signin` is an arbitrary path not matching any of our paths. When using `/` as path there was a collision between our root resource controller and the OIDC middleware. Thanks you heaps for your help!

**Comment by sberyozkin** [comment]
@PatrickWolleb Np at all, great it is working now. Having a virtual callback path will certainly help with avoiding matching any of the real service paths (Having a reserved existing callback path should also do the trick as long as UI does not offer users access it - random non-authenticated access to this path would work - 401 in case of orphaned state cookies for this path only may be reasonable).

But in any case, #34631, with its `quarkus.oidc.authentication.fail-on-missing-state-param=false` will help as well when `3.3.0.Final` is released and I've just proposed a backport of it to the `3.2` branch.  Going forward, `quarkus.oidc.authentication.fail-on-missing-state-param` may have to become `false` by default, we'll see how it goes
