### ISSUE TITLE
Regression 3.3.0 config quarkus.config.locations with vault

### ISSUE THREAD

**Issue by vsevel** [quarkusio/quarkus#35410]
### Describe the bug

When switching from `3.2.4`  to `3.3.0` , loading properties from vault does not work anymore when using `quarkus.config.locations`. It may apply to other config source extensions. Not sure at this point.

### Expected behavior

property should be loaded from vault, as in `3.2.4`

### Actual behavior

the property is not loaded.

### How to Reproduce?

create an application with quarkus `3.3.0` and vault extension `3.1.0` .
start a vault like in the quickstart:
```
docker run --rm --cap-add=IPC_LOCK -e VAULT_ADDR=http://localhost:8200 -p 8200:8200 -d --name=dev-vault vault
docker logs dev-vault
...
# get Root Token: from the logs
docker exec -it dev-vault sh
...
# inside shell
export VAULT_TOKEN=...
vault kv put secret/myapps/vault-quickstart/config a-private-key=123456
```

in a directory somewhere outside the app:
- create a `config` directory
- create 2 files: `application.properties` and `base-application.properties`

in `application.properties`, add:
```
quarkus.config.locations=./config/base-application.properties
```

in `base-application.properties`, add:
```
config_ordinal=255

#quarkus.http.port=8090
quarkus.vault.kv-secret-engine-version=2

quarkus.vault.url=http://localhost:8200
quarkus.vault.tls.skip-verify=true
quarkus.vault.secret-config-kv-path.quickstart=myapps/vault-quickstart/config
quarkus.vault.authentication.client-token=<root token>
foo=${quickstart.a-private-key}

quickstart.a-private-key=xxx

quarkus.log.category."io.quarkus.vault".level=DEBUG

```

in `GreetingResource`:
``` 
    @ConfigProperty(name = "foo")
    String foo;

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    @Path("/prop")
    public String helloProp() {
        return foo;
    }
``` 

start the application. you get:
```
$ java -Dquarkus.http.port=8090 -jar ../target/quarkus-app/quarkus-run.jar
Failed to load config value of type class java.lang.String for: foo
```

it works if:
- you switch to quarkus `3.2.4`  and vault `3.0.0`  
- you add property `quickstart.a-private-key=xxx` to `base-application.properties`
- you move the content of `basde-application.properties` into `application.properties`

### Output of `java -version`

17

### Quarkus version or git rev

3.3.0

**Comment by radcortez** [comment]
In SmallRye Config, sources go through a two-step initialization, first the traditional sources (or non-configurable sources, meaning that they don't require configuration) and second the configurable sources, which use the config available from the first step.

The sources loaded by `quarkus.config.locations` are, by definition Configurable Sources, meaning that they require configuration to initialize. Same as Vault. Configurable sources cannot configure other sources, because property value lookup and source ordering would not be consistent.

What ConfigPhase.Bootstrap did, was to add yet another level (a third phase) of configurable sources (so it would use the resulting config of the described two-phase initialization). In a few corner cases, it created some inconsistencies because the third level was not inside SmallRyeConfig itself, but was built around it in Quarkus. For instance, expecting sources created by Bootstrap to init sources from SmallRyeConfig. 

I can certainly understand the frustration of seeing something that works going away.

I guess we could make `quarkus.config.locations` a bit special and contribute the loaded sources to the chain. Another option is to add layers (or groups) of sources to be initialized and each group can contribute values to the next group being initialized.

**Comment by vsevel** [comment]
thanks for this explanation.
ideally config sources should be able to feed one another (granted I am missing a lot of the associated complexity with that simple statement)
specifically, variables coming from system properties, env variables, vault, consul, ... should be able to be used inside `application.properties` in templated values.
in a sophisticated system, one could even imagine multiple cross references, as in:
```
system properties
---
-Dfoo=bar -Durl=${host}


application.properties
---
host=${bar}.acme.org
```

in our current configuration approach, we add 2 files in the config map:
- the first one `base-application.properties` entirely generated by the provisioning system, containing base properties that we won't the apps to have to know about (base service urls, default kafka parameters, including security elements coming from vault, ...)
- the second one `application.yaml` provided by the app

and a `quarkus.config.locations` to get the `application.yaml` to sit on top of the base file (so that it can override some of the defaults).
if we move away from that behavior, I will have to develop a merge between these 2 files and the result of this merge into the config map as a single `application.yaml`. doable, but I liked when quarkus did it for me ;)
the other option is to move the entire base properties as system properties, but then I am losing the ability to override the default properties from the app `application.yaml` (the overrides have to be themselves system properties).

note that our SB apps are working in a similar way than our quarkus `3.2` apps:
- we have a `default.yml`, which contains the base properties, including some assembled from props coming from vault
- other applicative files provided by the dev team
- env var `SPRING_CONFIG_LOCATION` ordering those files: `optional:classpath:/,/deployments/config/default.yml,/deployments/config/`

**Comment by radcortez** [comment]
Sorry for the late reply, I've been busy with high priority issues :)

> ideally config sources should be able to feed one another (granted I am missing a lot of the associated complexity with that simple statement)

I agree, and I thought about this multiple times, but never got around these issues:

- Each source has the ability to set the ordinal in which they are going to place themselves in the config stack via `config_ordinal`. This feature is really a pain, for this use case, because you may end up with a configured source on top of the source that configured it.
- This allows to have the same configuration to override itself over and over until all sources are loaded with different results. While in the end you only have a single value, sources could have used different values from the same configuration name to configure itself. Think for instance if you need `quarkus.http` and all sources set something different. Each source when being configured would connect to a different port, but we know that there can only be one available. We need to ensure that once a property is read, at least for the duration of the Config set up, there is no mutability involved.

> specifically, variables coming from system properties, env variables, vault, consul, ... should be able to be used inside `application.properties` in templated values.

Yes, but with the `config_ordinal` override, there is no way to make sure it works. Users are ultimately responsible for how they set up their sources and their substitutions because these end up creating weak dependencies between configuration resolution.

> and a `quarkus.config.locations` to get the `application.yaml` to sit on top of the base file (so that it can override some of the defaults).

You can still use the `config` folder in working folder directory relative to Quarkus and place an `application.properties` or `application.yaml` file there. Let me see if I can move the configuration added by `quarkus.config.location` to the first loading layer.

> note that our SB apps are working in a similar way than our quarkus `3.2` apps:

I'll have to check, but I guess that SB does not have an arbitrary way to reshuffle the order of a source.

Maybe we need to drop that feature (the `config_ordinal`). Or at the very least, completely ignore it for sources that require configuration.

**Comment by vsevel** [comment]
I was able to reproduce with your app, assuming the 2 following changes:
- comment line https://github.com/radcortez/quarkus-config-playground/blob/quarkus-35410/config/base-application.properties#L12
- config should not be at the root of your project, instead:
  - create dir `test_config`
  - move `config` into `test_config`
  - package you app, and run it from within `test_config`

```
Sevel@DEVVX700077 MINGW64 /e/tmp/roberto-quarkus-config-playground/test_config (quarkus-35410)
$ java -Dquarkus.http.port=8070 -jar ../target/quarkus-app/quarkus-run.jar
Failed to load config value of type class java.lang.String for: foo
```

this is because when you compile, if there is a `config` dir available, props will be used in your built app as if they were part of `src/main/resources` , which is a treacherous issue to me. I had reported it way back in the [quarkus dev](https://groups.google.com/g/quarkus-dev/c/KXzJ2UPGRvI/m/3AEsLvZNBAAJ)

**Comment by radcortez** [comment]
Thanks! I was now able to replicate it.

The issue here is that `quarkus.config.locations` loads the sources in the second phase. We cannot do it in the first phase because we don't know in which order the sources are going to end up, so we need first to load all sources and then query `quarkus.config.locations` and then add the additional sources.

This worked before with the `BOOTSTRAP` phase, because the way it was implemented in Quarkus, it would first create a separate Config instance, create the config object to start the source, and finally create a new config instance with the new sources. The downside to this is that not only you require additional config instances, but you effectively had sources with lower ordinals contributing values to higher ordinal sources. Again, the ability to arbitrarily define a source ordinality is a real pain from the specification.

Looking into the use case from a different perspective, I believe that you want to express something like:

_Provide a way to include base or common properties to the current config instance_

I think that `quarkus.config.locations` is not the best way to express such use case. I could probably make it work, but it was always meant to add additional sources and not include sources (which is a bit different). Having a way to set a common configuration is nothing new and we were asked about it several times. Our recommended way to do it is to use multiple profiles.

In this case, you can rename `base-application.properties` to `application-base.properties` and start Quarkus with `-Dquarkus.profile=base,prod`. In this scenario, `quarkus.config.locations` is not required and can be completely dropped or even used to load other sources. It may be annoying to set the profile for each run. You can get rid of that by setting `quarkus.config.profile.parent=base` in the `config/application.properties`. 

I think this is a bit more powerful, because now any `application-base.properties` in your classpath will contribute configuration to the base / parent profile.

**Comment by vsevel** [comment]
> Provide a way to include base or common properties to the current config instance
yes. base (generated by the provisioning process) being overridable by the application level config (provided by the dev team).

> It may be annoying to set the profile for each run
it is not. this is a situation that only applies to deployment on our ocp cluster. 

this is promising. thanks. I am going to try that.

side issue: do you find reasonable (I don't) that properties contained into `./config` would be baked into the built application?

**Comment by vsevel** [comment]
I can't get the `application.properties`  to override `application-base.properties`.
I have:
```
# application-base.properties
foo=foovalue-from-base
bar=barvalue-from-base
```
and
```
# application.properties
foo=override
```
I tried:
```
-Dquarkus.profile=prod,base, or
-Dquarkus.profile=base,prod, or
-Dquarkus.config.profile.parent=base
```

I always get `foovalue-from-base` instead of `override` 

is there a way to order profiles?

**Comment by vsevel** [comment]
I tried also putting `quarkus.config.profile.parent=base` in `application.properties` but it keeps reporting the value from the base profile.
what is the logic behind ordering profiles?

**Comment by vsevel** [comment]
I reread the doc in https://quarkus.io/guides/config-reference#multiple-profiles
it says: _then the last listed profile has priority_
I reused your example with the prod profile:
```
./config/application.properties
---
quarkus.profile=common,prod

my.prop=123
%common.my.prop=456
```

I run `java -jar ../target/quarkus-app/quarkus-run.jar`. it says:
```
2023-09-06 12:49:11,524 INFO  [io.quarkus] (main) Profiles prod,common activated. 
```

(why is `common` after `prod`?)

when I display the value for `my.prop` , I get `456`. I was expecting `123`.

I was able to get something to work, but that is a bit convulated:
- create an empty `application.properties`
- create `application-app.properties` with `my.prop=foovalue-from-app`
- create `application-common.properties` with `my.prop=foovalue-from-common`
- start the app with ` -Dquarkus.profile=common,app`

then I get as expected `myprop=foovalue-from-app`.
it seems there is something special about the `prod`  profile.
is that they way to go?
should I pass the `prod` profile to `-Dquarkus.profile` as well?
any hints @radcortez ? Thanks

**Comment by radcortez** [comment]
Hum.. yes probably it is a bit confusing.

The logic when setting the profile is that the last listed profile has priority, so when you set something like `base,prod`, you mean that you want `prod` to override `base` (for properties in both, and also taking source ordinal into account).

In practice, this means that for a give property `foo.bar` we search `prod` first and then `base`, so in the console you get the order in which the profiles are queried.

**Comment by radcortez** [comment]
I've changed the example a bit in:
https://github.com/radcortez/quarkus-config-playground/commit/a4e10199183b09e254af2881b5c7513280ced564

And I run (from the `test_config` folder) `java -jar ../target/quarkus-app/quarkus-run.jar`.

With the following outputs:

```console
🌀 curl http://localhost:8080/config/my.prop
ConfigValue{name='my.prop', value='prod', rawValue='prod', profile='null', configSourceName='PropertiesConfigSource[source=file:/Users/radcortez/Code/personal/quarkus-config-playground/test_config/config/application.properties]', configSourceOrdinal=260, configSourcePosition=4, lineNumber=-1}16:03:42 (566) radcortez@radcortez: ~
🌀 curl http://localhost:8080/config/only.in.base
ConfigValue{name='only.in.base', value='base', rawValue='base', profile='null', configSourceName='PropertiesConfigSource[source=file:/Users/radcortez/Code/personal/quarkus-config-playground/test_config/config/application-base.properties]', configSourceOrdinal=255, configSourcePosition=5, lineNumber=-1}16:03:51 (567) radcortez@radcortez: ~
🌀 curl http://localhost:8080/config/only.in.prod
ConfigValue{name='only.in.prod', value='prod', rawValue='prod', profile='null', configSourceName='PropertiesConfigSource[source=file:/Users/radcortez/Code/personal/quarkus-config-playground/test_config/config/application.properties]', configSourceOrdinal=260, configSourcePosition=4, lineNumber=-1}16:03:55 (568) radcortez@radcortez: ~
🌀 curl http://localhost:8080/config/foo
ConfigValue{name='foo', value='123456', rawValue='${quickstart.a-private-key}', profile='null', configSourceName='PropertiesConfigSource[source=file:/Users/radcortez/Code/personal/quarkus-config-playground/test_config/config/application-base.properties]', configSourceOrdinal=255, configSourcePosition=5, lineNumber=-1}
```

**Comment by vsevel** [comment]
Interesting. We could not get it to work with prod and common profiles. Must have missed something obvious. Will try again on monday. Thanks

**Comment by radcortez** [comment]
Sure. Feel free to reach out!

**Comment by vsevel** [comment]
hello @radcortez 
I understand now why my new reproducer discussed in https://github.com/quarkusio/quarkus/issues/35410#issuecomment-1706794360 failed
I was missing the `config_ordinal` that you kept in your [example](https://github.com/radcortez/quarkus-config-playground/blob/quarkus-35410/test_config/config/application-base.properties#L1C1-L1C19)
I am surprised. I would have thought that the profile ordering `base,prod` would have been enough for `prod` to override `base`, without needing the additional ordinal. 
if I remove the ordinal from your reproducer, I get: `configSourceOrdinal=261` and `prod` does not override `base` anymore (260 when coming from `prod`):
```
$ curl localhost:8040/config/my.prop
ConfigValue{name='my.prop', value='base', rawValue='base', profile='null', configSourceName='PropertiesConfigSource[source=file:/E:/tmp/roberto
-quarkus-config-playground/test_config/config/application-base.properties]', configSourceOrdinal=261, configSourcePosition=4, lineNumber=-1}
```   

that works for me. I will go back to the production code and apply this approach. when I have everything running, I will close the issue. if you think it is worth a doc PR I will gladly do it (I am not sure though what we should add).

thanks again for the kind support,

> The reason we do it is that you may have configuration required for build time and also readable at runtime. We call this recording configuration. The purpose is to avoid failing the application run because a configuration is missing. It also makes sure that the configuration cannot be overridden, since you usually don't want the same configuration that was used at build time to have a different value at runtime.

thanks for the explanation. I understand the purpose. I just wished we had another way of achieving this. I know another person in the team who was very surprised to see `mvn -Dquarkus...` props getting recorded into the final app. I keep thinking it is not intuitive. we'll live with it.

cheers

**Comment by gsmet** [comment]
I think Vincent has a point about the order without ordinal. At least I would expect Quarkus to respect the order. And if it doesn’t and there’s a good reason to not fix it, it needs to be clearly documented.

**Comment by radcortez** [comment]
Hum... let me have a look.

**Comment by radcortez** [comment]
This is working as expected, but I do confess that even I got confused for a bit :)

There are two features in effect here: profiled files and multiple profiles. 

Profile files allow you to add configuration in the format `application-${profile}.properties`, which will be loaded when such profile is active. For the main `application.properties`, the correct name would be unprofiled, since the file is always loaded no matter which profile is active. Consider:

```
application.properties
application-base.properties
application-prod.properties
```

If you have `base` active you get:

```
application-base.properties
application.properties
```

If you have `prod` active you get:

```
application-prod.properties
application.properties
```

And, of course, the profiled file has a higher ordinality to override the main `application.properties` one.

When you mix multiple profiles `base,prod`, you get:

```
application-prod.properties
application-base.properties
application.properties
```

In this particular example, I was thrown off because of the `config_ordinal` that was set there, so it almost seemed that `application.properties` was being set as the `prod` one, but it is not. (see? I told you that having `config_ordinal` is bad :)). 

So it will be just a matter of taste on how you want to set that up. You can transform your `base` in the unprofiled `application.properties` and then use specific files for whatever profile you get active.

Really sorry for all the confusion :(

**Comment by vsevel** [comment]
another surprising issue: if I convert the `application.properties` to `application.yaml`  (and I add `quarkus-config-yaml` dep), it does not work anymore. the `application-base.properties` gets ignored.
I have tried on my tiny example, and on your reproducer, and I get the same faulty result.
even if I convert the base to yaml as `application-base.yaml`, it does not work.

``` 
    <dependency>
      <groupId>io.quarkus</groupId>
      <artifactId>quarkus-config-yaml</artifactId>
    </dependency>
``` 

``` 
# src/main/resources/application.yaml
"%prod":
  quarkus:
    http:
      port: 8060
``` 

``` 
# test_config/config/application.yaml

my.prop: fooprod
only.in.prod: barprod
``` 

``` 
# test_config/config/application-base.yaml

config_ordinal: 255

my.prop: foobase
only.in.base: barbase
``` 

``` 
$ java -Dquarkus.profile=base,prod -jar ../target/quarkus-app/quarkus-run.jar 
Failed to load config value of type class java.lang.String for: my.prop
```

**Comment by radcortez** [comment]
> another surprising issue: if I convert the `application.properties` to `application.yaml` (and I add `quarkus-config-yaml` dep), it does not work anymore. the `application-base.properties` gets ignored.

Yes, this is expected. If a profile is active, the profile resource is only loaded if the unprofiled resource is available in the exact location. This is to keep a consistent loading order and match the unprofiled resource.

> I have tried on my tiny example, and on your reproducer, and I get the same faulty result.
> even if I convert the base to yaml as `application-base.yaml`, it does not work.

The YAML source read `my.prop` as a compound key `"my.prop"` (quoted).  Please check https://github.com/quarkusio/quarkus/issues/11744 for more information. Please try with `my:\n  prop: value`.

I've also added that example here:
https://github.com/radcortez/quarkus-config-playground/commit/d0fc8e0c27cdaa7d4bb1fdb05b4458d6951e9143

**Comment by vsevel** [comment]
@radcortez I confirm this is working as you describe. this will require us to refactor our `application-base.properties` into `application-base.yaml`. slightly unfortunate because with our provisioning templating, this was easy to apply if/else conditions around blocks of properties. but we'll manage. thanks.

**Comment by radcortez** [comment]
Ok, sorry for any inconvenience. Please, let me know if we can help with something (or improve).

**Comment by vsevel** [comment]
sure. np. I may propose some doc improvement.

**Comment by vsevel** [comment]
> @radcortez I confirm this is working as you describe. this will require us to refactor our `application-base.properties` into `application-base.yaml`. slightly unfortunate because with our provisioning templating, this was easy to apply if/else conditions around blocks of properties. but we'll manage. thanks.

another unexpected behavior @radcortez : in multi profile it seems you have to have the exact same file extension. for instance it does not work if you have `application.yml` and `application-base.yaml`. do you confirm?

**Comment by vsevel** [comment]
this could be alphabetical. `properties` then `yaml` and `yml`. as long as the rule is clear, I do not see a problem.
I should be free to use any format I want, even mixing should be allowed, because eventually they all end up being just a bunch of properties.

**Comment by radcortez** [comment]
In my opinion mixing is a bad idea :)

Users already get confused with all the ordinal order. If you have for instance an `application.yaml` and `application-prod.properties`, with the current rules, `application-prod.properties` is not loaded. If we were to load it, should it override `application.yaml`? Profile properties have priority, but yaml source is higher...

Instead, if you have `application.yaml`, `application-prod.yaml`, `application.properties`, and `application-prod.properties` in my opinion, it becomes more clear just by looking into the files, who overrides who, and you just check the ordinal of the file type in the docs to know which loads first.

Also, let me clarify that while it may look weird to require the unprofiled file to load all the resources, we do it for a reason. Ordering matters a lot here. If all files have different properties names, it is all good, but if files override properties, the overriding order needs to be very clear. We require an unprofiled file for classpath scanning of the files. If we were to load files from the classpath without that rule, configuration files in the same jar could end up with different loading orders. So, we load the unprofiled file first and then load the profiled files using the jar location from the unprofiled one, ensuring consistent ordering. Yes, it would be possible to come up with a predictable order by loading all candidates and then matching each candidate to the exact loading location. Tricky, but possible. Call me lazy :)

Then for consistency reasons, we apply the same rules to the files in a folder.

We can certainly loosen up the rule about requiring the exact same extension and load-related extensions like `yml` and `yaml`.

**Comment by vsevel** [comment]
> In my opinion mixing is a bad idea :)

I don't think mixing is bad. it was actually very convenient to have `application-base.properties` (generated by CD), and `application.yaml` (provided by app team). right now I am generating `application-base.yaml`  in CD, but I had to add a check failing the CD if the dev team provides an `application.properties` . so I had to restrict their choices.

however I think that allowing `application.properties` and `application.yaml` (or `application-foo.properties` and `application-foo.yaml`) is an anti-pattern. I see 2 possible behaviors in the situation:
 - fail startup with message: `you can't have application.properties and application.yaml in the same directory. choose one or the other`
 - choose one (e.g. ignore the other), and print a warning: `we saw that you had both application.properties and application.yaml in the same directory. using application.properties and ignoring application.yaml`.

one other thing we could have is a log displaying the complete sources and files that are used to assemble the configuration, and display the exact order in which the override each other. this could be a log info, or at least a log debug.

> We can certainly loosen up the rule about requiring the exact same extension and load-related extensions like yml and yaml.

that would be good if nothing else. we spent one hour with the dev team trying to figure out why its applicative config was ignored, until after searching all other options we came up with _it is very unlikely, but what if quarkus was disturbed by the missing 'a'..._ ;)

**Comment by vsevel** [comment]
> May I ask why you consider application.properties and application.yaml an anti-pattern, but application-base.properties and application.yaml is ok? Each of the file will build on top (with the ordinal) and override properties if they are the same.

I meant in the same location having 2 files with 2 different extensions is to me an anti-pattern.
but having 2 files with different extensions in 2 different locations should not be an issue.
the extension is just a format, just like a config source. we can mix different config sources. I am missing some of the difficulties. but from the outside I do not see a difference between mixing config sources or mixing formats (yaml, properties, json, ...)

**Comment by radcortez** [comment]
> I meant in the same location having 2 files with 2 different extensions is to me an anti-pattern.
> but having 2 files with different extensions in 2 different locations should not be an issue.

That was my point. Personally, I don't see any difference. Maybe you have a large `application.properties` file and you are now migrating to `application.yaml`. You are either required to migrate everything or have them in separate directories even if they are part of the same configuration. Maybe you prefer to have a shared folder for all the apps, which can share different configuration files. it seems to me just an arbitrary restriction that takes away flexibility.

In the meantime, I've added the discussed enhancements to SR Config:

- https://github.com/smallrye/smallrye-config/pull/1025
- https://github.com/smallrye/smallrye-config/pull/1026

**Comment by vsevel** [comment]
> Personally, I don't see any difference

I don't have a use case for the first one. but I do for the second: dev team providing `application.properties` and CD providing `application-base.yaml`, both mounted in the same applicative pod, with the goal to get the base application config overridden by the dev team config file, and ideally avoiding the `application-base.yaml` to force the dev team on yaml format. is there a solution for this use case?

**Comment by radcortez** [comment]
> I don't have a use case for the first one. but I do for the second: dev team providing `application.properties` and CD providing `application-base.yaml`, both mounted in the same applicative pod, with the goal to get the base application config overridden by the dev team config file, and ideally avoiding the `application-base.yaml` to force the dev team on yaml format. is there a solution for this use case?

Not currently.

I've recently added to SmallRye Config (and now in Quarkus  3.5.x) a way to access the config builder. You can use it to customize the resulting Config. It is possible to remove the `application.properties` loader so you can force your teams to use `yaml` only.

**Comment by vsevel** [comment]
hello. I think all questions have been answered. thanks so much @radcortez for taking the time.
in the end, if there was one thing that I wish was working, it is ability to mix formats.
I do not see anything else to discuss here.
