### ISSUE TITLE
Support annotating `ContainerRequestFilter` and `ContainerResponseFilter` with `@Tenant` in `quarkus-oidc`

### ISSUE THREAD

**Issue by Eng-Fouad** [quarkusio/quarkus#35420]
### Description

It would be really useful if filters can be triggered only based on selected tenant. Something like:

```
import org.jboss.resteasy.reactive.server.spi.ResteasyReactiveContainerRequestFilter;
import io.quarkus.oidc.Tenant;

@Tenant("tenant2")
public class Tenant2Filter implements ResteasyReactiveContainerRequestFilter {
    // ...
}
```

**Comment by Eng-Fouad** [comment]
cc @sberyozkin @michalvavrik

**Comment by sberyozkin** [comment]
I'm not sure about this enhancement. In this case, Tenant is an OIDC specific concept, filters - RestEasy specific ones, mixing both does not seem to work. 
I think you can already achieve it with `DynamicFeature` and `@Tenant` annotations which can already be attached to JAX-RS resource classes.

**Comment by sberyozkin** [comment]
@Eng-Fouad See, one thing is to express that when `MyService` JAX-RS resource is called a tenant `a` configuration should be selected, and another - run a given set of filters when the tenant `a` is selected. I'd like to close this issues as Not Planned since as I said, `DynamicFeature` is exactly what can do it - you check the tenant annotation - and attach tenant specific filters - I don't see how it can be done otherwise, or if it is worth it given the `DynamicFeature` option is available, but I'd like to get my comments first, thanks

**Comment by Eng-Fouad** [comment]
I ended up querying tenant name inside the filter via security identity, something like:

```
if ("Default".equals(securityIdentity.getAttribute("tenant-id")) {
    // ...
}
```

which works fine for me.

**Comment by sberyozkin** [comment]
Thanks @Eng-Fouad
