### ISSUE TITLE
@ShutDown as opposite to @Startup

### ISSUE THREAD

**Issue by HerrDerb** [quarkusio/quarkus#35848]
### Description

With `@Startup`, I can register a method to be executed when the startup event is fired. The alternative is to `@Observes` the `StartupEvent` directly.

For the shutdown event, I currently need to `@Observes ShutdownEvent env`. While it does work, I mostly don't have any use of the event object. This also leads to some code smells, as I have a unused parameter. (Usually marked by sonarcloud)

### Implementation ideas

Therefor it would be nice to have, similar to the startup event, a shotdown annotation `@ShutDown` which registers the method to the `ShutdownEvent`. This would be short handed and leads to cleaner code.

**Comment by manovotn** [comment]
I am not opposed to this since we already have `@Startup` anyway. Just a side note - Quarkus events are just extending the CDI events which work very much the same and also have no other use than as a marker payload. So while I understand the code smell argument, in some scenarios it was deliberately designed this way (and not just in this case for CDI does behave similarly for observing context activation/deactivation events for instance).

Shutdown - https://github.com/jakartaee/cdi/blob/master/api/src/main/java/jakarta/enterprise/event/Shutdown.java
Startup - https://github.com/jakartaee/cdi/blob/master/api/src/main/java/jakarta/enterprise/event/Startup.java

**Comment by mkouba** [comment]
Hm, but we'll need a bit different semantics for `@Shutdown`. I mean the `@Startup` annotation can be declated on a bean class in which case we initialize the bean (and call the `@PostConstruct` callback). What should happen in case of `@Shutdown` declared on a bean class? Should we only support `@Shutdown` declared on a method?

**Comment by HerrDerb** [comment]
@mkouba Cool, thank you very much 🙂👍
