### ISSUE TITLE
Discovery of the Lambda function does not work when there is a parent class not in the project that implements RequestHandler

### ISSUE THREAD

**Issue by debae** [quarkusio/quarkus#3608]
**Describe the bug**
We for example have a base / common library that holds a baseLambda containing some common code. So we end up with only a subclass of that baseLambda in the project where we will use Quarkus. In this case no Lambda is discovered.

Code inside the project : 
`
public class LambdaInProject extends BaseLambda
`

Code inside a library :
`
public class BaseLambda implements RequestHandlerRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent>
`

**Expected behavior**
The lambda that extends the baseLambda is correctly marked as being the lambda within the project.

**Actual behavior**
No lambda is discovered AND no exception is thrown (this is only the case when multiple lambda's are found). We then deploy our lambda on AWS and you get a timeout after 30 seconds without any error in CloudWatch.

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Darwin APRXJGH6D5D5F9 18.7.0 Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64 x86_64
 - Output of `java -version`: 1.8.0_211
 - GraalVM version (if different from Java): 19.0.2
 - Quarkus version or git rev: 0.21.1

**Additional context**
Related to https://github.com/quarkusio/quarkus/issues/3099

**Comment by debae** [comment]
A workaround to get this working is to also implement the RequestHandler in the lambda within the project, so ending up with :

Code in project :
`
public class LambdaInProject extends BaseLambda implements RequestHandlerRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent
`

Code in library :
`
public class BaseLambda implements RequestHandlerRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent
`

I do suggest to adapt the AmazonLambdaProcessor to throw an exception when no lambda is discovered. Will create a Pull Request for this change.

**Comment by gsmet** [comment]
So, the root of the issue is that you need your library code to be indexed in Jandex. Otherwise, Quarkus can't know that `LambdaInProject` implements `RequestHandler` because we don't know what `BaseLambda` is.

See my answer here: https://stackoverflow.com/a/55513723 . I recommend you to use the Jandex Maven plugin to build the index at build time if you can.

**Comment by debae** [comment]
Thanks Guillaume, will try that.

But I guess we do still want an exception to be thrown when no lambda is found right ?

**Comment by gsmet** [comment]
That's a question for @evanchooly . Usually, we try to not throw an error when you just add an extension because it can be a bit counter productive when using dev mode (it's nice to be able to add the extension, start dev mode and then start coding).

But I'm not sure if it makes sense for Amazon Lambda so I'll let @evanchooly answer.

**Comment by evanchooly** [comment]
The general consensus on throwing exceptions is to *not* throw them.  It's entirely feasible that one could add the extension (say, in dev mode) before adding any code that uses.  Throwing exceptions in that window would lead to a terrible user experience.  For the most part, extensions seem to be following the quietly do nothing school of thought in the absence any work to do.

**Comment by debae** [comment]
Agree, however if you made a mistake , like I did with the parent class not being picked up by Jandex ... it's hard to figure this out without debugging. Maybe logging a warning might be usefull ?

**Comment by oztimpower** [comment]
The code has changed a lot since this issue was raised, it does now fail to build, with the following warning.
> Caused by: java.lang.RuntimeException: Unable to find handler class, make sure your deployment includes a single com.amazonaws.services.lambda.runtime.RequestHandler or, com.amazonaws.services.lambda.runtime.RequestStreamHandler implementation

Or, if a named annotation is used on the derived class, and the application.properties refers to this:

> Caused by: java.lang.RuntimeException: Unable to find handler class with name test make sure there is a handler class in the deployment with the correct @Named annotation

Suggest the issue can be closed? @debae want to re-try? I've simulated your use case.

**Comment by oztimpower** [comment]
Please close, no longer relevant.

/cc @geoand
