### ISSUE TITLE
Add support for custom Jackson JsonMappingException exception mapper

### ISSUE THREAD

**Issue by danifalconr24** [quarkusio/quarkus#36155]
### Describe the bug

Using Quarkus 2.16.10.Final

Hello,

The issue im having is that im not able to provide custom exception mappers for exceptions like ValueInstantiationException or even better would be being able to provide a mapper for JsonMappingException which is a more generic type, but, this mappers are getting ignored, because in the case of  ValueInstantiationException the exception is getting mapped to a WebApplicationException by the resteasy reactive jackson quarkus extension, another example could be the InvalidFormatException which is not getting mapped into a WebApplicationException but the only way to override the default exception mapper is to provide an specific mapper for this exception, it could be much better if we can just create a mapper for JsonMappingException and handle all this Jackson exceptions directly there because they all extend from this exception.

### Expected behavior

Support the possibility to provide a JsonMappingException and get all this exceptions that extends from this one

### Actual behavior

Handle every exception differently, anď map them to WebApplicationException.

### How to Reproduce?

Reproduce:

_ValueInstantiationException_

1 -> have some endpoint that receives an object with any enum property
2 -> request with invalid enum value 
3 -> ValueInstantiationException is mapped somewhere to a WebApplicationException 

_InvalidFormatException_

1 -> have some endpoint that receives an object with an Integer property
2 -> request with a string that cannot be mapped to an Integer. ie: "abcd"
3 -> We cannot handle this exception inside the JsonMappingException mapper because there is a more specific exception mapper provided by Jackson library

**Comment by geoand** [comment]
Can you please attach a sample application that behaves as you have described?

Asking because I would like to see how this is different from what https://github.com/quarkusio/quarkus/pull/29661 addressed.

**Comment by geoand** [comment]
Closing as we never got feedback

**Comment by krismatusiak** [comment]
Hey @geoand @gsmet Could we please reopen this issue?

I have an app sample here that shows the problem:
https://github.com/krismatusiak/quarkus-exception-handling

**Comment by geoand** [comment]
@krismatusiak looking at your sample I am not sure I understand the problem

**Comment by krismatusiak** [comment]
@geoand Thanks for looking so fast  ;) I appreciate that :)

The challenge is to make all the tests pass ;) 
Right now the JsonMappingException cannot be caught in the ConfusedExceptionHandler. 
So even though I am setting the status code to 200 there (for whatever reason), this is not working, because the WebApplicationException consumed the JsonMappingException ;) Very dramatic.
On the other hand, catching WebApplicationException is also not productive and leads to other issues.

So the problem is this: I want to customize the status code (and such) when the JsonMappingException is thrown, and I cannot do that now.

You provided a good solution for a similar case of the MismatchedInputException: this can be caught in the hanlders (= yeey).
But so the JsonMappingException is actually a parent of MismatchedInputException, so: not all that different. Perhaps the parent is the better target for allowing customizations of the response?

**Comment by krismatusiak** [comment]
Hey @geoand, 
 
Yes indeed, this is just like #41479 
I read the conversation there, and I follow the argument that Quarkus 'ships' with its own mapper.
This, to me signals a conscious decision and not an accidental bug :)

That said, the customization of the response code should be made to be easy, regardless.
And by 'easy' I understand setting a boolean in the config :) Well, perhaps providing a list of exceptions that I would like to handle myself (is that possible? I think I came across a conversation about this somewhere, but cannot find it anymore), would also be 'easy'. And by 'easy' I also mean 'easy for ME, the developer' :) I totally understand that 'my easy' is not 'your easy' :)

And now for the adding of quarkus.class-loading.removed-resources."io.quarkus\:quarkus-rest-jackson"=io/quarkus/resteasy/reactive/jackson/runtime/mappers/DefaultMismatchedInputException.class

So: IntelliJ does not like. It keeps reformatting this: cutting the 'key' off and adding more and more equal signs in the 'value', for some reason, in its configuration UI. So that does not fly there, regardless, even if its something werid on Intellij env var UI side. (vide screenshot one)

![Screenshot 2024-09-09 at 09 21 47](https://github.com/user-attachments/assets/a6334786-371a-468b-9dc8-44f918c2af88)

In the commandline, however, I do get to pass it along. And so there: not only does the one failing test not pass, but also other tests are failing now. It is possible that I am not passing the var correctly or Im making a typo of some kind? I cannot see it. (vide screenshot two)


![Screenshot 2024-09-09 at 09 09 18](https://github.com/user-attachments/assets/d8b492f6-5d4e-4655-891a-d674e6753228)

**Comment by geoand** [comment]
#43126 should make things better (I used a sample application to verify)

**Comment by krismatusiak** [comment]
@geoand 

For me, and the app that I provided, it does not work.
Oh, but so it is not merged yet? 
Im confused ;) Did we expect it to work for my app?

**Comment by krismatusiak** [comment]
Ok, got it.

Would you consider simplifying this (perhaps in addition to this property) into an easily-named boolean flag?

disableNativeMismatchedInputExceptionHandler: true

or:
disableHandlers:
    - MismatchedInputException

**Comment by geoand** [comment]
Yeah, that's definitely up for discussion :)

**Comment by geoand** [comment]
I'm on the fence. WDYT @gsmet ?

**Comment by omasseau** [comment]
Any news on this ? 

Quarkus desperately needs a way to easily disable the built-in exception mappers (everytime it is a nightmare to find a workaround for each type of exception we want to handle manually in our code).

A property
`quarkus.disable-builtin-exception-mapper.<ExceptionClass>=true `would be nice

**Comment by geoand** [comment]
I'll take another look soon

**Comment by geoand** [comment]
I think I'll probably add something like `quarkus.rest.exception-mapping.disable-mapper-for` where this property will take a list of class names as the input. 
This should be simple enough to implement in `RuntimeExceptionMapper`

**Comment by geoand** [comment]
I opened a PR that should cover the use case discussed: https://github.com/quarkusio/quarkus/pull/51303
