### ISSUE TITLE
SR Health annotations used in a stereotype don't take effect

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#36187]
### Discussed in https://github.com/quarkusio/quarkus/discussions/36106

<div type='discussions-op-text'>

<sup>Originally posted by **famod** September 22, 2023</sup>
Hi @xstefank, @jmartisk and all other experts in this area!

I'm trying to use `@Wellness` and `@HealthGroup` like this:
```java
    @WellnessCheck
    static class SomeWellnessCheck implements HealthCheck {
        // ...
    }

    @Singleton
    @Wellness
    @HealthGroup("my-group")
    @Retention(RUNTIME)
    @Stereotype
    @Target(TYPE)
    @interface WellnessCheck {
    }
```
but my checks are not picked up.

It does work when I add those annotations directly to each actual check.

Is this a bug or a missing feature or am I doing something wrong here?

Thanks!</div>

----

- unzip [q_well.zip](https://github.com/quarkusio/quarkus/files/12743131/q_well.zip)
- run `HealthTest`

Quarkus 3.4.1

**Comment by mkouba** [comment]
@famod Ah, my mistake. A stereotype may not be used to associate qualifiers. It can be used to define a default scope, a set of interceptor bindings and if the annotated beans should have defaulted bean names or are alternatives. And it makes sense because qualifiers are usually used to distinguish the beans, not to group them.

In other words, you always need to annotate the class with `@Wellness` and `@HealthGroup("wellness")`.

**Comment by xstefank** [comment]
@mkouba can we maybe make and exception for Health-related qualifiers since they are indeed used for grouping?

**Comment by manovotn** [comment]
> A stereotype may not be used to associate qualifiers. It can be used to define a default scope, a set of interceptor bindings and if the annotated beans should have defaulted bean names or are alternatives.

True, stereotypes not carrying over qualifiers is intentional.
Just for the sake of completeness, you can also add `@Priority` to stereotypes since CDI 4.

> I'm not sure it's a good idea. We should definitely not create an exception exclusively for SR Health.

+1, if we want to look for solution, it should be more generic.
FTR, you could achieve this via an extension (CDI extension for instance). You could look for beans with your stereotype annotation and add qualifiers programmatically.

**Comment by xstefank** [comment]
Just an idea. Thanks for the explanations!
