### ISSUE TITLE
OIDC: Backchannel logout not being called when using Sign out all Session in Keycloak

### ISSUE THREAD

**Issue by tmulle** [quarkusio/quarkus#36216]
### Describe the bug

Hi,

1) When I try to use the "Sign out all sessions" on a client in Keycloak it appears the back-channel endpoint is not being  called.

If I individually sign each session out in the UI Keycloak calls my server and the user is logged out.

But nothing happens when I click the `Confirm` button.

Is this by design?

2) Also, when the backchannel logout endpoint is called, is there a way to have Quarkus automatically redirect to a specific page?

This works for the normal logout method of defining a `/logout` url in the `application.properties` and I'm redirected to whichever page I want after the user manually initiated the logout.

Just wondering if there is a way to get the same behavior using back-channel as well.

Keycloak Version: 22.0.3
Quarkus: 3.4.1

<img width="1460" alt="Screenshot 2023-09-29 at 10 51 48 AM" src="https://github.com/quarkusio/quarkus/assets/5183186/4108c58a-6969-4467-a82c-90c3af88d0bc">

### Expected behavior

I would think the users would be logged out via the backchannel logout as it is for a single user.

### Quarkus version or git rev

3.4.1

**Comment by sberyozkin** [comment]
Hi @tmulle Ok, thanks for testing, good you have confirmed it works for individual session logout at the Keycloak level. Can you please move this issue though to Keycloak to investigate further ? This issue can not be impacted at the Quarkus level

**Comment by tmulle** [comment]
@sberyozkin Ok, I just  created a new ticket over on Keycloak for this issue.

Thanks for the answer in number 2, I was thinking in terms of web applications. A user signed into the same app on two different browers, etc. 

And when I use the Keycloak UI to sign the session out, the end user would be signed out and redirected to a logout page.

Essentially, giving the KeyCloak Admin remote ability to sign out a misbehaving user on the site, etc.

But no worries, we can close this for now.

**Comment by sberyozkin** [comment]
@tmulle Thanks, right, the back channel logout can help with it, but since it is bypassing the browser it is not possible to trigger anything in the browser immediately - the back channel logout state is pending, but when the user will attempt to access Quarkus - the user will be redirected to Keycloak.

You may want to experiment with the front channel logout - this goes via the browser's inner frame - right now, Quarkus will also redirect to Keycloak to reauthenticate - but may be, in case of the frontchannel logout - we can redirect the user to the configured post logout url instead - that would probably be a reasonable enhancement
