### ISSUE TITLE
Resteasy without vertx - Add Error Page support

### ISSUE THREAD

**Issue by patriot1burke** [quarkusio/quarkus#3646]
Error page support.  We will probably want to look at accept header to see if its from a browser or not and send text or html depending on this.

_Originally posted by @gsmet in https://github.com/quarkusio/quarkus/pull/3631#issuecomment-523795569_

**Comment by gsmet** [comment]
What would really be nice is having a consistent experience across RESTEasy with/without Undertow.

**Comment by FroMage** [comment]
That's error pageS. We have one for any error and one for 404 which lists all available endpoints.

**Comment by loicmathieu** [comment]
I just tested it on master and the error page from Resteasy is correclty displayed in both representation (html: the default and json).

So the only issue is to add a default error page to Vert.x similar that the one generated by the undertow `QuarkusErrorServlet`.

Nothing to be done at Resteasy level.

**Comment by loicmathieu** [comment]
Just saw that if all still works on master it's because there is no more undertow but still quarkus-undertow as a dependency of resteasy so the `QuarkusErrorServlet` is still used. Maybe it should be replaced by a dedicated route in Vert.x, see [Vert.x Error Handling](http://vertx.io/docs/vertx-web/java/#_error_handling)

Just for the records, there is 3 error pages(and not two), security related error page is generated via 
 `io.quarkus.resteasy.runtime.RequestFailer` that only generate HTML message.

This also needs to be added to the TODO list but it should still works as it's used via a jax-rs `ContainerRequestFilter`.

**Comment by FroMage** [comment]
Looking at this.

**Comment by FroMage** [comment]
Just checked and both the error page and the 404 pages work on resteasy-only on 23.2. The security error page is resteasy-specific so it will work too. Closing.
