### ISSUE TITLE
Upgrade SnakeYaml to address CVE-2022-1471

### ISSUE THREAD

**Issue by pehunka** [quarkusio/quarkus#36583]
### Description

Hi team,

do you have any plans to upgrade snakeyaml version to address CVE-2022-1471? It is used by following quarkus components:

- io.quarkus-config-yaml : 2.16.12.final
- io.quarkus : quarkus-smallrye-openapi : 2.16.12.final

I know it is mainly used to parse secure inputs such as application.yml, but it will help to calm down security officers as this CVE is flaged with highest security  score in my project.

### Implementation ideas

Looks like version 2.x addressed this CVE:
https://bitbucket.org/snakeyaml/snakeyaml/wiki/Changes

**Comment by gsmet** [comment]
Hi @pehunka ,

We won't update SnakeYaml in 2.x because it's a major version upgrade and the fix was mostly to remove a constructor that was used by a lot of other libraries so upgrading would force us to upgrade a lot of other components (and potentially break applications).

If you're worried about security anyway, you should migrate to Quarkus 3 ASAP as we won't maintain 2.16 very soon (plan is end of October), as mentioned in the announcements for a while.

Quarkus 3 upgraded to SnakeYaml 2.

**Comment by pehunka** [comment]
Thanks for the quick response. I will work with the team to upgrade to v3. For the moment, we are trying to keep the circus flying.

**Comment by gsmet** [comment]
@pehunka install the CLI and use `quarkus update`. It won't solve everything but should help a lot in your journey.
