### ISSUE TITLE
event handler not respect @IfBuildProfile?

### ISSUE THREAD

**Issue by lost22git** [quarkusio/quarkus#36613]
### Describe the bug

in quarkus dev mode, it still works

```java
@IfBuildProfile("prod")
public void print(@Observes StartupEvent startupEvent) {
    System.out.println("-----------> test prod");
}
```

**Comment by manovotn** [comment]
From [javadoc](https://github.com/quarkusio/quarkus/blob/main/extensions/arc/runtime/src/main/java/io/quarkus/arc/profile/IfBuildProfile.java):

> When applied to a bean class or producer method (or field), the bean will only be enabled
>  if the Quarkus build time profile matches the rules of the annotation values.

You're annotating observer method instead which is why nothing is happening.
If you want to disable this bean for any other than `dev` mode, move the annotation to the class level.

**Comment by mkouba** [comment]
Matej is right. `@IfBuildProfile`only works for beans, not observer methods. If you want to perform some logic in an observer method only in production//dev/test then inject the `io.quarkus.runtime.LaunchMode` like:
```java
public void print(@Observes StartupEvent startupEvent, LaunchMode mode) {
   if (mode == LaunchMode.TEST) {
      System.out.println("-----------> test prod");
   } 
}
```
