### ISSUE TITLE
Run time configuration consumed from VertxWebProcessor.kubernetes()

### ISSUE THREAD

**Issue by dmlloyd** [quarkusio/quarkus#3677]
**Describe the bug**
A build step (`VertxWebProcessor#kubernetes`) is consuming a run time configuration object during build time to determine the HTTP listen port.  This is not allowed because run time values cannot be resolved (#3516, #3637) or accessed during build time.  The run time configuration objects can only correctly be used to pass as proxies to recorders for run time actions (though in this case, it is quite hard to detect invalid accesses to config fields because of the decision to opt for field injection instead of using e.g. a proxy interface for configuration values, so I might still look into directly injecting the config roots into the recorder proxies and drop support for any injection of run time config objects into build steps).

**Additional context**
Blocks #3516/#3637.

**Comment by geoand** [comment]
The `KubernetesPortBuildItem` is used to populate the Kubernetes resources and is only ever used at build time - meaning that changing the port value at runtime wouldn't affect the Kubernetes code in any way, since none of that code even exists at runtime.

If we can't consume the runtime config value at build time, what is the alternative? 
We need to be able to use whatever value is configured in `application.properties` (or fallback to whatever the `HttpConfiguration.port` default is), so should we code this logic inside the processor instead of relying on the regular Quarkus config handling?

**Comment by stuartwdouglas** [comment]
For now I would just directly use MP config to get the values. Long term we
might need something better but this is a somewhat odd case.

**Comment by geoand** [comment]
PR incoming

**Comment by dmlloyd** [comment]
The port value might not be present at build time, so reading it from the config only works if the user happened to supply it to the build.  Maybe there should just be a separate configuration item for the Kubernetes port?

**Comment by geoand** [comment]
If the port is not supplied, wouldn't we just use the default http port?

**Comment by dmlloyd** [comment]
Run time config is read & used at run time, so the port number could change from run to run.

**Comment by geoand** [comment]
That is true, but the kubernetes resources can't be changed in any case. It's just a file that the users can choose (or not) to use when the they build the application.
