### ISSUE TITLE
Quarkus cannot find gRPC input files through symlinks

### ISSUE THREAD

**Issue by LarsSven** [quarkusio/quarkus#37223]
### Describe the bug

When one makes the /src/main/proto directory a symlink to another directory, Quarkus cannot find the `.proto` files within that symlinked directory.

### Expected behavior

Quarkus compiles the .proto files within the symlink target to java classes within `/build/classes/java/quarkus-generated-sources`

### Actual behavior

`/build/classes/java/quarkus-generated-sources` is empty.

### How to Reproduce?

1. Set up a Quarkus project with the gRPC extension installed.
2. Create a directory with `.proto` files that Quarkus can compile
3. Create a symlink in /src/main/proto that links to the directory in step 2.
4. Run `quarkusBuild`

### Output of `uname -a` or `ver`

Microsoft Windows [Version 10.0.22635.2771]

### Output of `java -version`

java version "21.0.1" 2023-10-17 LTS

### Quarkus version or git rev

3.5.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.4

**Comment by LarsSven** [comment]
We also ran this on Ubuntu, with the exact same issue presenting itself.

**Comment by LarsSven** [comment]
A colleague of mine told me that the issue likely lies with this line: https://github.com/quarkusio/quarkus/blob/main/extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java#L108

A symlink doesn't resolve to a directory unless you retrieve the canonical fiile using getCanonicalFile. One interesting detail may be that for our use case, we used a relative directory (`../../../proto`).

**Comment by dmlloyd** [comment]
It is likely that a better fix would be to do `Files.isDirectory(context.inputDir().resolve("."))` instead: it should resolve to the self-reference of the directory regardless of whether the target itself was actually a symlink, while simply returning `false` in any other case (including the case where either `inputDir` or one of its parents does not exist).

**Comment by alesj** [comment]
@LarsSven ^^ can you patch latest Quarkus with @dmlloyd 's suggestion and tell us if it works for you?

**Comment by LarsSven** [comment]
Will try to find some time for it soon

**Comment by LarsSven** [comment]
@alesj I built the patch locally and included it in my project, it did not seem to have solved the issue, as it still does not generate the gRPC code.

**Comment by dmlloyd** [comment]
Is there any more information you can share?

**Comment by cescoffier** [comment]
@LarsSven Can you show us what you did?

**Comment by LarsSven** [comment]
I replaced `if (Files.isDirectory(context.inputDir())) {` with `if (Files.isDirectory(context.inputDir().resolve("."))) {` at https://github.com/quarkusio/quarkus/blob/main/extensions/grpc/codegen/src/main/java/io/quarkus/grpc/deployment/GrpcCodeGen.java#L108.

I then built this locally and included this in my project, which did not seem to solve the issue. I'm not very experienced with building the Quarkus project so I may have made a mistake with including it in my project, but it should have used my local version and not the remote version of the platform, plugin and gRPC extension.

I suspect it may be because we are passing the check now for whether it is empty, but then the actual code for grabbing the set of files from the directory still cannot deal with a symlink?

**Comment by dmlloyd** [comment]
When opening a directory, the logic is slightly different than the logic for determining a file's type (`stat` in UNIX-ese). If the target of the open is a symlink to a directory, then the directory it refers to will be opened rather than the link ("opening" or reading a link requires a special flag to `open` like `O_SYMLINK` or a dedicated syscall like `readlink`, depending on the OS being used). Passing the `NOFOLLOW_LINKS` flag will produce an error if the target is a directory though.

That said, this code uses the `Files.walk` API which does not traverse symbolic links by default. So, it is possible that the initial directory is being excluded here. This could be tested by adding the `FileVisitOption.FOLLOW_LINKS` flag to the `Files.walk` call on the next line and seeing if this fixes the issue. However, this fix would have to be evaluated through a security lens before being accepted (specifically, do we allow symlinks to "escape" the traversed directory?).

**Comment by alesj** [comment]
> specifically, do we allow symlinks to "escape" the traversed directory?

How would you check this?
By checking the "prefix" all the time?
Or going back via parent file(s) and we need to come to `inputDir`?

I guess this would be the same problem every time symlinks are involved ...
