### ISSUE TITLE
Invalid documentation for 'quarkus extension add'

### ISSUE THREAD

**Issue by Dieken** [quarkusio/quarkus#37564]
### Describe the bug

https://quarkus.io/guides/security-jwt

```
quarkus extension add smallrye-jwt,smallrye-jwt-build
```

It should be `quarkus extension add smallrye-jwt smallrye-jwt-build`.

**Comment by geoand** [comment]
@Dieken would you like to contribute the fix?

**Comment by geoand** [comment]
No problem, I'll take care of it

**Comment by geoand** [comment]
Actually, this is a problem because the syntax used for adding extensions is not the same in CLI and Maven/Gradle plugins. 

So the way I see it, we have the following options:

* Make the CLI understand the syntax that the build tool plugins use (the one with commas)
* Make the build tool plugins understand the syntax the CLI uses (the one with spaces)
* Add new variable to the Ascidoc (unless there is a way to manipulate variables)

WDYT @quarkusio/devtools @gsmet ?

**Comment by ebullient** [comment]
> Actually, this is a problem because the syntax used for adding extensions is not the same in CLI and Maven/Gradle plugins.
> 
> So the way I see it, we have the following options:
> 
>     * Make the CLI understand the syntax that the build tool plugins use (the one with commas)
> 
>     * Make the build tool plugins understand the syntax the CLI uses (the one with spaces)
> 
>     * Add new variable to the Ascidoc (unless there is a way to manipulate variables)
> 
> 
> WDYT @quarkusio/devtools @gsmet ?

CLI can understand commas, that's easy (and forgiving)

**Comment by geoand** [comment]
I tried it, and it gives an error

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/37581 should take care of it.

**Comment by gsmet** [comment]
@Dieken thanks for taking the time to report the issue. It has gone unnoticed for quite a while...
