### ISSUE TITLE
Docs: security-openid-connect-dev-services#dev-services-and-ui-support-for-other-openid-connect-providers section is doesn't work in new DEV UI

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#37661]
### Describe the bug

Nothing described in https://quarkus.io/version/main/guides/security-openid-connect-dev-services#dev-services-and-ui-support-for-other-openid-connect-providers works now that Quarkus migrated to the new DEV UI.

### Expected behavior

For one, describe behavior that works. Or don't and drop it, as it is very unlikely someone is actually using it. Noone opened issue that it doesn't work when old DEV UI was dropped. Maybe it doesn't make sense to invest into a feature noone is using.

### Actual behavior

The `DevConsoleRuntimeTemplateInfoBuildItem` item is ignored.

### Additional information

This is sort of my fault @sberyozkin , but since I'm also tasked with reviewing this guide, I have to report it. I'll address this issue eventually.

**Comment by sberyozkin** [comment]
@michalvavrik Thanks, and it is no one's fault, if only it is mine, but in any case as I said earlier, with the old Dev UI, the idea was that it would give, an option, for example, to Okta developers, register a completely Okta specific Dev UI experience.

>Maybe it doesn't make sense to invest into a feature noone is using.

I kind of agree, though I'd say the reason no one is using is that no one sees how it can actually work for non-Keycloak providers.

That said, as demoed for example in the Auth0 guide, https://quarkus.io/guides/security-oidc-auth0-tutorial#looking-at-auth0-tokens-in-the-oidc-dev-ui, the same DevUI we use for Keycloak, works for Auth0, and the one Steph has started looking at will also work, so indeed, rather than carrying the section around that noone uses, lets drop it for now.

Unless you'd like to experiment at some point, for example, as POC, use https://quarkus.io/guides/security-oidc-auth0-tutorial#looking-at-auth0-tokens-in-the-oidc-dev-ui with Auth0-tailored Dev UI, but in any case, I'm OK if you decide to drop this section for now, thanks

**Comment by michalvavrik** [comment]
I just think we have long of stack issues that users asked for (and some bugs) and it should have priority. And we can't just leave this open as docs is describing something that is not true anymore. Therefore I'm going to create PR that drop it and we can get back to it when there is anyone who will request it in the future.
