### ISSUE TITLE
Building Quarkus with Buildpacks uses Liberica as JDK

### ISSUE THREAD

**Issue by fniephaus** [quarkusio/quarkus#37777]
### Describe the bug

When following the [docs on building Quarkus with Buildpacks](https://quarkus.io/guides/container-image#buildpack), I end up with a container that uses Liberica as the JDK.

### Expected behavior

Mandrel is used a the JDK, or the user is given a choice which JDK to use.

### Actual behavior

Liberica is used as the JDK.

### How to Reproduce?

```bash
$ git clone --depth 1 https://github.com/quarkusio/quarkus-quickstarts.git
$ cd quarkus-quickstarts/getting-started
$ ./mvnw quarkus:add-extension -Dextensions='container-image-buildpack'
$ ./mvnw install -Dquarkus.container-image.build=true
# ...
===> EXPORTING
Reusing layer 'paketo-buildpacks/ca-certificates:helper'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:helper'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:java-security-properties'
Reusing layer 'paketo-buildpacks/bellsoft-liberica:jre'
Adding 1/1 app layer(s)
Reusing layer 'buildpacksio/lifecycle:launcher'
Reusing layer 'buildpacksio/lifecycle:config'
Adding label 'io.buildpacks.lifecycle.metadata'
Adding label 'io.buildpacks.build.metadata'
Adding label 'io.buildpacks.project.metadata'
no default process type
Saving ubuntu/getting-started:1.0.0-SNAPSHOT...
*** Images (336e9b9fad07):
      ubuntu/getting-started:1.0.0-SNAPSHOT
Adding cache layer 'paketo-buildpacks/bellsoft-liberica:jdk'
Adding cache layer 'paketo-buildpacks/syft:syft'
Adding cache layer 'paketo-buildpacks/maven:application'
Adding cache layer 'paketo-buildpacks/maven:cache'
[INFO] Buildpack build complete, with exit code 0
# ...
```

**Comment by zakkak** [comment]
Thanks for reporting this @fniephaus.

**Comment by zakkak** [comment]
@iocanel if I understand correctly we are not setting a builder image by default and [thus buildpack uses `paketo-buildpacks/bellsoft-liberica`](https://bell-sw.com/blog/how-to-use-buildpacks-to-build-java-containers/).

Since in general we don't test Quarkus with Liberica NIK and there is no buildpack using Mandrel, the next best choice for Quarkus seems to be GraalVM CE, i.e. [paketo-buildpacks/graalvm/](https://github.com/paketo-buildpacks/graalvm/). WDYT?
