### ISSUE TITLE
OpenAPI filters run twice when storing

### ISSUE THREAD

**Issue by phillip-kruger** [quarkusio/quarkus#37901]
Yeah, so that is not ideal, I think we can get a better way to do this so that your filter is not run twice. I can look at this. Basically we need to create a document (for inclusion in the runtime), and then use that and only add runtime filters when we store.

I am about to take a break (summer holiday) so I'll only look at this next year. If you are in a hurry, you are welcome to do a PR ?

W.r.t priority, yeah that is something we can add. Having multiple filters is Quarkus specific (the spec only allow one) so from a spec p.o.w a user needs to do everything in one filter. But because we allow many we can look at a way to order them for sure

_Originally posted by @phillip-kruger in https://github.com/quarkusio/quarkus/issues/36152#issuecomment-1866009465_

**Comment by mcruzdev** [comment]
Hi @phillip-kruger, if you want, I can get this issue.

**Comment by phillip-kruger** [comment]
Go for it! Thanks

**Comment by mcruzdev** [comment]
Hi @phillip-kruger getting a first look into the code, I saw that the filter is called two times because:

The method responsible for executing filter is `prepareOpenApiDocument(staticModel, annotationModel, openAPIBuildItems, index)` and is called by:

1. `loadDocument(OpenAPI staticModel, OpenAPI annotationModel,
            List<AddToOpenAPIDefinitionBuildItem> openAPIBuildItems, IndexView index)` 
2. `storeDocument(OutputTargetBuildItem out,
            SmallRyeOpenApiConfig smallRyeOpenApiConfig,
            IndexView index,
            OpenAPI loadedModel,
            boolean includeRuntimeFilters)` 

I have a question: 

The filter with RunStage `OpenApiFilter.RunStage.BUILD` should appear in http://localhost:8080/q/openapi download or just when generating via build?

**Comment by phillip-kruger** [comment]
Both

**Comment by mcruzdev** [comment]
Hi @phillip-kruger, HAY? Can you review the pull request https://github.com/quarkusio/quarkus/pull/38070?

**Comment by phillip-kruger** [comment]
Away from PC at the moment, back next week
