### ISSUE TITLE
Entity not refresh after update in transaction

### ISSUE THREAD

**Issue by resilience-guillaume-gardais** [quarkusio/quarkus#38223]
### Describe the bug

Gets hibernate entity does not returns entity updated in a previous transaction

### Expected behavior

We want to update an entity into a transaction and get the updated entity after committing transaction 

### Actual behavior

We update and persist an entity into a transaction, when we get entity outside the same transaction, the entity is not up to date

### How to Reproduce?

run tests from [https://github.com/resilience-guillaume-gardais/quarkus-transaction-issue](https://github.com/resilience-guillaume-gardais/quarkus-transaction-issue)

### Output of `uname -a` or `ver`

Linux bdl09-dx 6.5.0-14-generic #14-Ubuntu SMP PREEMPT_DYNAMIC Tue Nov 14 14:59:49 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21.0.1" 2023-10-17

### Quarkus version or git rev

3.6.4

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.1.1

**Comment by yrodiere** [comment]
Hello,

This is the failing test in your reproducer:

```kotlin
    fun `Get updated entity without transaction`() {
        // Get book from repository once
        val bookEntityFromRepository = getBookWithoutTransactionService.getBookById(bookEntity.id!!)
        assertThat(bookEntityFromRepository, Is(bookEntity))

        // Update book title
        updateBookService.updateBookWithTransaction(bookId = bookEntity.id!!, newTitle = "New Title 2")

        // Get updated book from repository
        val bookEntityWithoutTransaction = getBookWithoutTransactionService.getBookById(bookEntity.id!!)
        val expectedUpdatedBookEntity = BookEntity(id= bookEntity.id, title = "New Title 2")
        assertThat(bookEntityWithoutTransaction, Is(expectedUpdatedBookEntity))
    }
```

The last assertion fails, as the book remains unchanged. Which indicates the same Hibernate ORM's first-level cache (session) is getting reused across (transaction-less) service calls.

When you're not using transactions, the session has to be bound to *some* context, and that context cannot be the transaction, since it doesn't exist. So the session is bound to the request context: one session is reused for the whole duration of the processing of one request.

So, this behavior indicates that a same request context is active across your service calls, leading to the session being reused.

From what I can see in https://github.com/quarkusio/quarkus/blob/5725791a1f620f1c7358e97958030b00bc67b2f9/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/ArcTestRequestScopeProvider.java#L9, this is actually on purpose: whoever designed the test extensions thought it was a good idea to consider one test method as one request, and to activate the request context accordingly. I suppose it's a judgment call, as either solution (doing it, or not) has its downsides.

So... Not a bug, just a quirk. If you have suggestions as how this should behave instead, we can discuss that, but personally I don't see what we could do. Maybe @geoand has an opionion?

---

That being said, I will reiterate what we've said in other bug reports before: use transactions. It doesn't cost you much, and will spare you problems such as this one. There are almost no reasons not to use transactions -- and no, performance is not a reason, in the *vast* majority of cases, as DBs will generally implicitly open a single-statement transaction anyway.

If you need to simulate multiple requests being sent to your application, either make multiple calls to your (transactional) services, or use one transaction per simulated request (`QuarkusTransaction.requiringNew().run/call` may help here).

**Comment by geoand** [comment]
Excellent analysis @yrodierem, thanks! 

> So... Not a bug, just a quirk. If you have suggestions as how this should behave instead, we can discuss that, but personally I don't see what we could do. Maybe @geoand has an opionion?

Agreed, this is how things were designed to work.

**Comment by Sanne** [comment]
> We want to update an entity into a transaction and get the updated entity after committing transaction

Why would you want to read anything outside of a transaction?

Besides, I thought I had made sure that Quarkus would require a transaction to do anything - did you do something to bypass this?

**Comment by yrodiere** [comment]
> Besides, I thought I had made sure that Quarkus would require a transaction to do anything - did you do something to bypass this?

You only forbade writes. Reads are allowed outside transactions at the moment.
