### ISSUE TITLE
Mixing auth-mechanizms fails `TestSecurity` tests

### ISSUE THREAD

**Issue by 01epa** [quarkusio/quarkus#38298]
### Describe the bug

In case if security is mixed (basic+bearer) accordingly to quarkus doc I have to specify [an authentication mechanizm ](https://quarkus.io/guides/security-authentication-mechanisms#path-specific-authentication-mechanisms)

After that tests with `@TestSecurity` failed.

Looks like the problem is in the transport method - `io.quarkus.test.security.TestHttpAuthenticationMechanism#getCredentialTransport` since it does return null for tests and as a result `findBestCandidateMechanism`  [here ](https://github.com/quarkusio/quarkus/blob/main/extensions/vertx-http/runtime/src/main/java/io/quarkus/vertx/http/runtime/security/HttpAuthenticator.java#L112 )returns baisic auth mechanizm instead of null

### Expected behavior

Test passed

### Actual behavior

Test failed

### How to Reproduce?

To reproduce the issue just replace lines in [application.properties](https://github.com/quarkusio/quarkus/blob/main/integration-tests/elytron-resteasy/src/main/resources/application.properties) file
from
```
%auth-failed-ex-mapper.quarkus.http.auth.permission.basic.paths=/*
%auth-failed-ex-mapper.quarkus.http.auth.permission.basic.policy=authenticated
%auth-failed-ex-mapper.quarkus.http.auth.proactive=false
```
to
```
quarkus.http.test-port=0
quarkus.http.auth.permission.basic.paths=/*
quarkus.http.auth.permission.basic.policy=authenticated
quarkus.http.auth.permission.basic.auth-mechanism=basic
```
and run test [TestSecurityTestCase ](https://github.com/quarkusio/quarkus/blob/main/integration-tests/elytron-resteasy/src/test/java/io/quarkus/it/resteasy/elytron/TestSecurityTestCase.java)

If commented out line
```
quarkus.http.auth.permission.basic.auth-mechanism=basic
```
then everything will work.

The same problem is with bearer mechanizm. 

### Quarkus version or git rev

latest

**Comment by sberyozkin** [comment]
@01epa Thanks, I've just updated the issue name a bit to make the problem clearer

**Comment by sberyozkin** [comment]
@01epa One more edit to make it even more clearer. Looks like fixing it will require adding a new `TestSecurity` attribute

**Comment by michalvavrik** [comment]
The `TestSecurity` is not basic auth, so expectation that you select it with the `quarkus.http.auth.permission.basic.auth-mechanism=basic` is wrong. Problem is that currently, you can't select the `TestSecurity` authentication mechanism as you correctly pointed out.

The easiest thing that we can do is to allow to explicitly select test `TestSecurity` so that you can explicitly select other mechanisms for `/*`.

I actually run into same situation and here https://github.com/quarkusio/quarkus/blob/0b209bd21b787fca85b92159363a657829c8b0ff/integration-tests/oidc-code-flow/src/main/resources/application.properties#L209 I had to list all non `TestSecurity` paths as we have no exclusions pattern on HTTP Perms (IMO not necessary).

I think `io.quarkus.test.security.TestHttpAuthenticationMechanism` should have `io.quarkus.vertx.http.runtime.security.HttpCredentialTransport#authenticationScheme` called `test`. Alternative proposal would be `auth-mechanism=any`, but it's bit more complicated. Thoughts?
