### ISSUE TITLE
Quarkus 3.7.0 doesn't work on Java 11

### ISSUE THREAD

**Issue by rob-spoor** [quarkusio/quarkus#38388]
### Describe the bug

We use renovate to automatically create PRs for our dependencies. On the change from Quarkus 3.6.7 to 3.7.0 we got a compiler error on class `QuarkusTest` (see below). The version change was the only thing that was different from our working `main` branch.

### Expected behavior

Code compiles correctly.

### Actual behavior

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:testCompile (default-testCompile) on project xxxxx: Compilation failure: Compilation failure: 
[ERROR] /path/to/project/src/test/java/path-to-file/Class.java:[25,29] cannot access io.quarkus.test.junit.QuarkusTest
[ERROR]   bad class file: /home/jenkins/.m2/repository/io/quarkus/quarkus-junit5/3.7.0/quarkus-junit5-3.7.0.jar(/io/quarkus/test/junit/QuarkusTest.class)
[ERROR]     class file has wrong version 61.0, should be 55.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
[ERROR] /path/to/project/src/test/java/path-to-file/Class.java:[27,2] cannot find symbol
[ERROR]   symbol: class QuarkusTest
[ERROR] -> [Help 1]
```

### How to Reproduce?

Create a simple test class and annotate it with `@QuarkusTest`. Try to compile it with Java 11.

### Output of `uname -a` or `ver`

Linux ci-slave4 4.19.0-25-amd64 #1 SMP Debian 4.19.289-2 (2023-08-08) x86_64 GNU/Linux

### Output of `java -version`

OpenJDK 64-Bit Server VM Temurin-11.0.21+9 (build 11.0.21+9, mixed mode)

### Quarkus version or git rev

3.7.0

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)

**Comment by rob-spoor** [comment]
Note that if we use Java 17 to build it works, but we are unable to upgrade at this time.

I've used a hex dump to check the Java version of the Quarkus 3.7.0 classes. Not just classes from `quarkus-junit5` but also from others like `quarkus-core` and `quarkus-arc` have `3d` (61) in them which means Java 17. In other words, without any mention in the release notes, Quarkus 3.7.0 seems to require Java 17 now. That kind of breaking changeshould have meant version 4.0.0.

**Comment by gsmet** [comment]
I would recommend your app to depend on `io.quarkus.platform:quarkus-bom` so that you get the upgrade when the full Platform is released (that will be in a week). Announcement will be available when you upgrade which will make it easier to grasp the changes.

I can confirm that Quarkus 3.7 will require Java 17. See https://quarkus.io/blog/java-17/ for more information about why we are doing that.

FWIW (but it won't help you), we are not the first framework to move to Java 17 as the base version. We tried to be conservative but at some point, we have to move to newer versions.

You can continue to use the pre-3.7 versions. Quarkus 3.2 is LTS so it will be maintained for a while.
