### ISSUE TITLE
Upgrading to Quarkus 3.7 leads to duplicate app deployment in OpenShift

### ISSUE THREAD

**Issue by yrodiere** [quarkusio/quarkus#38455]
### Describe the bug

In 3.6 and below, the Quarkus OpenShift extension used to generate a `DeploymentConfig` for apps by default.

Since 3.7, it generates a `Deployment` instead: #37229  

Since `Deployment` and `DeploymentConfig` resources do not share their namespace, this means that simply upgrading and deploying to openshift will create a *new* `Deployment` and *will not remove* the old `DeploymentConfig`, leading to a single application being deployed twice.

We need to discuss how to make this easier on users.

See https://github.com/quarkusio/quarkus/pull/37229#issuecomment-1914526410

cc @iocanel  , @maxandersen , @gsmet , @edeandrea

**Comment by yrodiere** [comment]
Note that the change is missing from the migration guide, and the problem can be missed very easily even if you have a staging env, unless you're very careful and check every single resource in your namespace.

**Comment by gsmet** [comment]
Also /cc @tqvarnst as I suspect it will impact the product.

**Comment by tqvarnst** [comment]
If I understand correctly, the way to reproduce this is:

1. Deploy the 3.6 (or earlier) version of quarkus using the default setting (DeploymentConfig) to OpenShift using the generated deployment descriptor from the quarkus-openshift extension.
2. Upgrade the project to 3.7
3. Deploy again, and since the default now has changed to use `Deployment` instead of `DeploymentConfig` the tooling, which won't replace the `DeploymentConfig`, but rather create a new `Deployment` so you might end up with both a `DeploymentConfig` using a 3.6 (or earlier) version of Quarkus as well as a `Deployment` using Quarkus 3.7.

Also, would setting `quarkus.openshift.deployment-kind=deployment-config` avoid this issue?

@yrodiere can you confirm?

**Comment by yrodiere** [comment]
> If I understand correctly, the way to reproduce this is:
> 
>     1. Deploy the 3.6 (or earlier) version of quarkus using the default setting (DeploymentConfig) to OpenShift using the generated deployment descriptor from the quarkus-openshift extension.
> 
>     2. Upgrade the project to 3.7
> 
>     3. Deploy again, and since the default now has changed to use `Deployment` instead of `DeploymentConfig` the tooling, which won't replace the `DeploymentConfig`, but rather create a new `Deployment` so you might end up with both a `DeploymentConfig` using a 3.6 (or earlier) version of Quarkus as well as a `Deployment` using Quarkus 3.7.

That's right. And depending on the setup, existing `Service`/`Route` resources might end up pointing alternatively to each deployment.

> Also, would setting quarkus.openshift.deployment-kind=deployment-config avoid this issue?

It would. Though that appears to be discouraged; from what I understand `DeploymentConfig` is deprecated.

The way forward appears to move to `Deployment`, which has some impact for users:

* They will need to update any custom `openshift.yaml` that adds attributes to their app's `DeploymentConfig` [^1]
* They will need to delete the old `DeploymentConfig`
* Not sure, but they may need to fiddle a bit with `PersistentVolumeClaims`, if any. I've dealt with that in the past and had trouble moving them from one `StatefulSet` to another; not sure if that's relevant for `Deployment`/`DeploymentConfig`.

[^1]:  As allowed [here](https://quarkus.io/guides/deploying-to-kubernetes#using-existing-resources):
    > If one of the provided resources has the same name as one of the generated ones, then the generated resource will be created on top of the provided resource, respecting existing content when possible (e.g. existing labels, annotations, environment variables, mounts, replicas etc).

**Comment by edeandrea** [comment]
This definitely should be mentioned in the migration guide. I mentioned that in the description of #37229 when I created it. I don't have permissions to edit the migration guide (at least I didn't last time I checked when I created that issue).

**Comment by tqvarnst** [comment]
I want to be clear here. Quarkus tooling should not migrate existing deployments from `DeploymentConfig` to `Deployment` descriptors. In OpenShift 4.14 `DeploymentConfig` has been deprecated, and therefore, our default has changed, but automatic migration to `Deployment` is a very error prune task and not really a responsibility of Quarkus to handle.

What I do agree with is that the tool could, before deploying an app, check if there is an existing `DeploymentConfig` already deployed in the namespace and, in that case, fall back to continue using `DeploymentConfig`. Note that according to https://access.redhat.com/articles/7041372 there are currently no plans to remove DepoloymentConfig APIs from OpenShift, but for new apps we should default to `Deployment` instead of `DeploymentConfig`.

**Comment by maxandersen** [comment]
at minimal we should mention the change in migration guide as others recommended for sure.

@tqvarnst I'm not sure what "tool" you are referring to about checking before deploying the app - but I like the idea of Quarkus openshift deploy extension do this check and possibly fail to deploy and require users to explicitly set which deploy mechanism they want to use if they truly want both to coexist. 

@iocanel is that a possibility ?

**Comment by iocanel** [comment]
> @iocanel is that a possibility ?
No, this is not possible. Manifest generation is something that happens offline (it needs to be idempotent).

**Comment by maxandersen** [comment]
Ok so if no good place to handle it we should at least document in migration guide the change in default incl. Giving example of config to restore previous behaviour.

**Comment by gsmet** [comment]
Frankly this is bad. I wonder if we should go back to the previous deprecated way instead of taking the risk of having people breaking their deployments when pushing the new version.

**Comment by iocanel** [comment]
To save users the frustration and the time before they realize that both DeploymentConfig and Deployment are deployed side by side, I think that we should prevent that from happening, with an error message that explains whats going on.

**Comment by edeandrea** [comment]
> To save users the frustration and the time before they realize that both DeploymentConfig and Deployment are deployed side by side, I think that we should prevent that from happening, with an error message that explains whats going on.

That sounds like a great idea. It should still be mentioned in the migration guide, though.

**Comment by maxandersen** [comment]
@iocanel i see section added on https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.7#deprecation-of-deploymentconfig - is there no way to restore the old behavior? we should call that out imo.

**Comment by edeandrea** [comment]
Setting `quarkus.openshift.deployment-kind=deployment-config` would restore previous behavior.

**Comment by iocanel** [comment]
Updated wiki with instructions and created: https://github.com/quarkusio/quarkus/pull/39160 that causes deployment to fail if there is any kind of conflict.
