### ISSUE TITLE
The ImageMetricsITCase failing with RH Mandrel because postgres is bigger than expected

### ISSUE THREAD

**Issue by jedla97** [quarkusio/quarkus#38563]
### Describe the bug

The `ImageMetricsITCase`  failing with RH mandrel (registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0) as it's bigger then then expected compared to the upstream.

The issue is same as https://github.com/quarkusio/quarkus/issues/37882 . Tha new version was released 11 days ago 23.0-19 and it's start failing. It seems that it is just little bigger than before.

Graalvm issue from previous issue is https://github.com/graalvm/mandrel/issues/654 (just for the link the issues)

### Actual behavior

Test is failing with this output:
`Expected image_details.total_bytes to be within range [79228920 +- 3%] but was 81620672 ==> expected: <true> but was: <false>`

For info in December it was `81149928` now it's 81620672

### How to Reproduce?

Failing test
```
mvn -f integration-tests/pom.xml clean dependency:tree verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g -U -V -B -fae -Denforcer.skip=true -Dtest-containers -Dstart-containers -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0-19 -pl jpa-postgresql -Dpostgres.image=postgres:14
```
The `-Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0-19` can be substitute as `-Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0`

Passing test
```
mvn -f integration-tests/pom.xml clean dependency:tree verify -Pnative -Dquarkus.native.container-build=true -Dquarkus.native.native-image-xmx=4g -U -V -B -fae -Denforcer.skip=true -Dtest-containers -Dstart-containers -Dquarkus.native.builder-image=registry.access.redhat.com/quarkus/mandrel-23-rhel8:23.0-16 -pl jpa-postgresql -Dpostgres.image=postgres:14
```

### Output of `uname -a` or `ver`

Having it on RHEL 8.9 and Fedora 39

**Comment by zakkak** [comment]
It is actually failing with both 23.0-26 and 23.0-29 on Quarkus `main` for me:

## 23.0-16

```
Expected image_details.total_bytes to be within range [79228920 +- 3%] but was 81637352 ==> expected: <true> but was: <false>
```

## 23.0-19
```
Expected image_details.total_bytes to be within range [79228920 +- 3%] but was 81653440 ==> expected: <true> but was: <false>
```

The difference between 23.0-16 and 23.0-19 is ~0.02%

## Upstream `23.0.3.0-Final-java17-2024-02-04`

Building with the latest upstream 23.0 builder image results in a binary with a total size of 79727808 bytes (which is ~0.6% higher than the baseline).

## Upstream `23.0.2.1-Final-java17-2024-01-21`

Building with the previous upstream 23.0 builder image results in a binary with a total size of 79712248 bytes, so the difference between the upstream versions is again ~0.02%.

# Conclusion

Since the differences are reasonable and there is an increase both in upstream and the Red Hat builds of Mandrel, I suggest we raise the baseline (to 79712248) for 23.0 (I will open a PR).
