### ISSUE TITLE
ClassCastException when Hibernate tries to create a list of UUIDs for query since Quarkus 3.7.1

### ISSUE THREAD

**Issue by b-thiswatch** [quarkusio/quarkus#38660]
### Describe the bug

With `quarkus-hibernate-orm-panache-kotlin` we have Countries and Cities with `@ManyToOne` and `@OneToMany` relation and discovered that when we call `CitiyEntity.listAll()`, it crashes with `java.lang.IllegalStateException: Illegal pop() with non-matching JdbcValuesSourceProcessingState` which is created by a ClassCastException when Hibernate tries to retrieve all Countries with a FROM-Query on Countries by using `where in` and converting a list of UUIDs.

`wrapped[ select ce1_0.id,ce1_0.iso,ce1_0.iso3,ce1_0.name,ce1_0.nice_name,ce1_0.num_code,ce1_0.phone_code from country ce1_0 where ce1_0.id = any (?) ]`

```java
@Override
			protected void doBind(PreparedStatement st, X value, int index, WrapperOptions options) throws SQLException {
				st.setBytes( index, javaType.unwrap( value, byte[].class, options ) );
			}
```

<img width="580" alt="Screenshot 2024-02-07 at 19 26 34" src="https://github.com/quarkusio/quarkus/assets/106271647/65d87dfd-78d5-4e55-949b-43f47154cc93">

When using the debugger and "Evaluate Expression" to run CityEntity.listAll() multiple times, it works after the first time.

### Output of `java -version`

21

### Quarkus version or git rev

3.7.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw

**Comment by yrodiere** [comment]
Hey @b-thiswatch , thanks for reporting.

Can you please provide a reproducer?

Even better would be reproducing with the [plain Hibernate ORM test case templates without Quarkus](https://github.com/hibernate/hibernate-test-case-templates/tree/main/orm/hibernate-orm-6) and [reporting directly to the ORM project](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/?filter=allissues) (mentioning this Quarkus issue in the description), because this really doesn't look like a bug in Quarkus, but rather in Hibernate ORM.

**Comment by b-thiswatch** [comment]
Hi @yrodiere ,

when updating Quarkus to 3.7.3 the Exception became clearer and trying to build a reproducer, I realised we ran into https://github.com/vladmihalcea/hypersistence-utils/issues/698 

We also updated to using the new native PostgresqlEnums...

Thanks for looking into this

**Comment by gsmet** [comment]
Nice, thanks for the feedback!

**Comment by yrodiere** [comment]
Thanks for the update!
