### ISSUE TITLE
Logging unknown values when have special characters

### ISSUE THREAD

**Issue by Willian199** [quarkusio/quarkus#38695]
### Describe the bug

When logging something with special characters, is logged unknown values.

This bug started happening in version 3.6.5. Before this version it worked as expected.

I tried to set `quarkus.log.file.encoding=ISO-8859-1`, but still not working.

Maybe related to issue 36919

### Expected behavior

Log all the specials characters as know values
Ex: `[org.acm.GreetingResource] (executor-thread-1) àáéíóúç`

### Actual behavior

Log unknown values
Ex: `[org.acm.GreetingResource] (executor-thread-1) �������  `

### How to Reproduce?

Go to [code.quarkus.io](https://code.quarkus.io/?j=21&e=resteasy-reactive&e=resteasy-reactive-jackson) and download it

Code sample:
```
@Path("/hello")
public class GreetingResource {

    @GET
    @Produces(MediaType.TEXT_PLAIN)
    public String hello() {
        Log.info("àáéíóúç");
        return "àáéíóúç";
    }
}
```

### Output of `java -version`

Graalvm Java 21

### Quarkus version or git rev

3.7.2

**Comment by geoand** [comment]
I can't reproduce this with greek characters

**Comment by Willian199** [comment]
Maybe it only happens with Latin characters.

Reproducer: https://github.com/Willian199/quarkus_log_chars

**Comment by geoand** [comment]
That one works fine for me as well

**Comment by dmlloyd** [comment]
By "special" characters I assume you mean "non-ASCII" (aka Unicode code points whose value is greater than 127), which are only "special" outside of the USA (the "A" in "ASCII" stands for "American"). The problems you are having likely indicate that your system's default character encoding does not match what Java is expecting for whatever reason.

You did not indicate anything about your system environment (`uname -a` or `ver` along with `java -version` at least is needed) so that's all I can say for certain. You also did not indicate where you are seeing this issue: is it on the console, or in a file, or somewhere else?

What changed in Quarkus 3.6.5 is that the console charset is now detected more actively, and if no charset is given, we are falling back to the system default charset (which normally defaults to UTF-8 if all else fails). So I'm guessing that your problem is occurring on the console, in which case setting `quarkus.log.file.encoding` will do nothing, since that applies only to file logging. But, you should specify, otherwise I'm just guessing.

**Comment by Willian199** [comment]
I'm using Windows 11 22H2 and this happens in console. If I do `System.out.println("àáéíóúç");` works as I expect

ver 

`Microsoft Windows [versão 10.0.22621.3007]`

Java -version
```
java version "21" 2023-09-19
Java(TM) SE Runtime Environment Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15)
Java HotSpot(TM) 64-Bit Server VM Oracle GraalVM 21+35.1 (build 21+35-jvmci-23.1-b15, mixed mode, sharing)
```

**Comment by Willian199** [comment]
The `Charset.defaultCharset()` returns UTF-8.
But the StreamEncoder use IBM850.

![image](https://github.com/quarkusio/quarkus/assets/40872392/b0a5dd6b-41ee-4331-a437-256e593b56cb)

![image](https://github.com/quarkusio/quarkus/assets/40872392/60170aa4-413a-4196-8077-71b8419b72a4)

**Comment by Willian199** [comment]
Well, following this tutorial solved the problem.

https://itsontreinamentos.com/2022/05/05/how-to-change-character-encoding-windows-11/

**Comment by dmlloyd** [comment]
To add more information: `System.out` does not use the console encoding, which is determined by `java.io.Console` separately (see `Console.charset()` for more information). The log manager uses this console encoding for console logging.
