### ISSUE TITLE
OIDC Multitinancy by actual answer from teenant

### ISSUE THREAD

**Issue by StanislavMakhrov** [quarkusio/quarkus#38696]
### Description

Hello! 
I have a question about https://quarkus.io/guides/security-openid-connect-multitenancy
Is there any way to make 2 tenants but which will be working in the following way:

- if the first tenant was not allowed user with token to pass then will be tried second teenant with this user token.
Currently according to documentation I can switch between teenants only by path but not by answer from teenant (token passed or not)

**Comment by sberyozkin** [comment]
@StanislavMakhrov It is not possible right now. What is a use case ?

**Comment by DisterDE** [comment]
Hello.
We have a case where our customers would like to request several endpoints with two different token issuers.
This process was implemented in spring security using two different auth providers.
Something like:
1. Decode JWT
2. Get iss
3. Find the correct provider by iss
4. Validate
5. ...
6. Profit.
 ```
private fun jwtAuthProvider(): AuthenticationProvider {
        return JwtAuthenticationProvider(
            CompositeJwtCreationStrategy(
                listOf(
                    AzureAdAuthenticationStrategy(azureTokenConfiguration()),
                    ImpersonationAwareWso2AuthenticationStrategy(jwtTokenConfiguration())
                )
            )
        )
    }
```
Important thing: we have no information on what kind of token we get from the customer and can't route them to another path.
So, having this opportunity out of the box would be nice.
Thanks.

**Comment by sberyozkin** [comment]
@DisterDE So the provider selection is driven by the token content. While the examples are checking paths, you can get the token claims, for example, get the Authorization header from `RoutingContext` and do `OidcUtils.decodeTokenContent(jwt)` - which will give `JsonObject`, get the issuer.

Next it depends if you have a static or dynamic resolution.

 If it is static with `TenantResolver` - have `TenantConfigBean` injected - it gives all the tenant configurations, their metadata, incl the issuer, return a matching tenant id.

If it is dynamic with `TenantConfigResolver` then it is pretty much the same approach, except that you already have a map of configurations locally.

Can you try it ?

I think Quarkus itself iterating over tenants does not really work, composing all of them as you show you can do with Spring, as the correct tenant may fail the token verification so continuing iterating until the success is already wrong, they may need to do remote introspection calls, and we have cases where users have a lot of tenants such as Keycloak realms, if we have 5+ tenants then it is becoming too expensive.

That said, I may consider automating the issuer driven resolution if the token is in the JWT format, so that it is done by default, as the issuer is indeed a good indicator which tenant can handle it.

**Comment by sberyozkin** [comment]
@DisterDE @StanislavMakhrov The solution which you can already do now is a little bit more involved but it will require literally a few extra lines of code and you are in control, IMHO it is an important point.

And in one of the future releases it will work out of the box for the `issuer` driven selection case

**Comment by sberyozkin** [comment]
Assigning to myself but the PR which will eventually resolve this issue will only do an automatic tenant selection for the JWT tokens given their `iss` claim value.

**Comment by sberyozkin** [comment]
@DisterDE @StanislavMakhrov With 3.10 the issuer based tenant selection for JWT tokens will be activated with a single property
