### ISSUE TITLE
Reactive Keycloak Admin Client - BlockingNotAllowedException issue and other issues when called with Panache.withTransaction

### ISSUE THREAD

**Issue by maxlam79** [quarkusio/quarkus#38874]
### Describe the bug

Hello there,

I came across BlockingNotAllowedException being thrown while using the Reactive Keycloak Admin Client "quarkus-keycloak-admin-client-reactive". Since the name "reactive" is there, I would assume that it runs smoothly with other reactive components and through Uni calls. But somehow, the BlockingNotAllowedException is thrown. I also have discovered some other weird issues as well.

To reproduce the problem, I have created a small repo to tryout: [https://github.com/maxlam79/quarkus-propagation-tryout](https://github.com/maxlam79/quarkus-propagation-tryout). All the dependencies are "reactive" at best.

Note: please take note that the DB settings are to point to the DB dev services which runs fine. But the keycloak settings are pointed to a an external demo keycloak server. The settings are right and tested (I have to do this because it was very painful for me to get the keycloak dev services up and running).

Test results:
GET - http://localhost:8080/resource/p02
This end point only calls the Keycloak Admin Client and retrieves the total number of users. Calling this end point fails, throwning BlockingNotAllowedException without ```@Blocking``` annotation. But it runs fine with ```@Blocking```. My expectation is that it shoudln't throw a BlockingNotAllowedException since all calls are through Uni.

POST - http://localhost:8080/resource/p03
This end point creates some entries to the DB, runs fine. Generally, I use Panache.withTransaction when persistence to DB is involved.

POST - http://localhost:8080/resource/p04
This is where things gets really interesting. This end point make calls to Keycloak Admin Client and create entries to the DB. All are executed within Panache.withTransaction.

Without ```@Blocking``` - throws BlockingNotAllowedException
With ```@Blocking``` - it throws error id: c0270815-eeff-465e-9084-63f54c80dd60-2: java.lang.IllegalStateException: HR000068: This method should exclusively be invoked from a Vert.x EventLoop thread; currently running on thread 'executor-thread-1'

Appreciate if someone could look into this. Thank you.

### Output of `uname -a` or `ver`

MacOS Montery 12.7.2

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.7.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

apache-maven-3.9.4

**Comment by giorgio-aimani** [comment]
As i understood from https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.9

Currently, there are still two variants of the Quarkus Keycloak Admin Client
- `quarkus-keycloak-admin-resteasy-client` -> Extensions named `-resteasy` are extensions using RESTEasy Classic
- `quarkus-keycloak-admin-rest-client` -> Extensions named `-rest` are extensions using Quarkus REST (and RESTEasy Reactive)

both still depend on the `keycloak-admin-client` which as @geoand mentions [above](https://github.com/quarkusio/quarkus/issues/38874#issuecomment-1953786350) exposes aq **non-blocking API**. The only difference really is that the (reactive supporting) variant `quarkus-keycloak-admin-rest-client` also imports other `-rest` extensions such as `io.quarkus:quarkus-rest-client-jackson` whilst the resteasy counterpart imports `-resteasy` extensions.

So that means if we're integrating the Keycloak Admin Client for a reactive REST stack (and hence choose `quarkus-keycloak-admin-rest-client`), we have to be mindful that invoking the REST methods from Keycloak Admin Client is **blocking**. To handle this would mean to offload the load to a worker thread (e.g, by using `@Blocking` annotations on methods which ultimately triggers the invoking of those REST methods)

Is this the expected way to deal with the Keycloak Admin Client in a reactive REST stack?
