### ISSUE TITLE
@VirtualThreads ScheduledExecutorService

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#39101]
### Description

According to https://quarkus.io/guides/virtual-threads, we can inject a quarkus managed `ExecutorService` based on VirtualThreads:

```
@Inject
@VirtualThreads
private ExecutorService executor;
```

It will return this instance:

`executor = class io.quarkus.arc.generator.ExecutorService_nW3tWaMAKDCDV-PTvKsACBy-qrg_Synthetic_ClientProxy`

Would it be possible to also inject a quarkus managed `ScheduledExecutorService` based on VirtualThreads:

```
@Inject
@VirtualThreads
private ScheduledExecutorService executor;
```

Currently, this is not possible:

`Caused by: jakarta.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type java.util.concurrent.ScheduledExecutorService and qualifiers [@VirtualThreads]`

But creating a `ScheduledExecutorService` based on VirtualThreads could be done something like:

```
// currently not quarkus managed
var schedule = Executors.newScheduledThreadPool(0, Thread.ofVirtual().factory());
```

Would this makes sense?

**Comment by mkouba** [comment]
I don't think it's currently possible because the underlying implementation is based on [`xecutors.html#newThreadPerTaskExecutor()`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/util/concurrent/Executors.html#newThreadPerTaskExecutor(java.util.concurrent.ThreadFactory)) which only returns `ExecutorService`.

But let's see what @ozangunalp thinks ;-)

**Comment by ozangunalp** [comment]
We did not provide a scheduled executor because the current implementation is written with thread pooling in mind and you shouldn't pool virtual threads. Also, not sure if it does make any sense to use virtual threads for scheduling tasks.
