### ISSUE TITLE
Add the ability to ask for devservices to use the shared network

### ISSUE THREAD

**Issue by jtama** [quarkusio/quarkus#39156]
### Description

As of now, the only way to ask for dev services to be run in the shared network is to produce a `DevServicesSharedNetworkBuildItem`, which I think is only done here : https://github.com/quarkusio/quarkus/blob/607ece496231d6278471e76c337d8637bc67c640/test-framework/junit5/src/main/java/io/quarkus/test/junit/IntegrationTestUtil.java#L292.

It would be great to be able to ask for it through configuration. I first thought that was what quarkus.<extension>.devservice.shared was for, it turned out it was not ;).

**Comment by geoand** [comment]
Can you give #39177 a try please?

The property to use is `quarkus.devservices.launch-on-shared-network=true`

**Comment by jtama** [comment]
The project for which I have the need is still using 3.4.3. I know it's bad, but we have a blocker for the moment.

I will to try to backport your patch though.

**Comment by jtama** [comment]
Ok I did backport your fix, that works as expected. Almost.

Devservices launched by extension use a different network because of this : 

https://github.com/quarkusio/quarkus/blob/44f9b08b795722bdfd65c6ecc0369ccafb70867d/extensions/devservices/common/src/main/java/io/quarkus/devservices/common/ConfigureUtil.java#L30

Which means If I launch a container configuring it via `ConfigureUtil.configureSharedNetwork`, that won't work, because they will be launched on an other network.

**Comment by geoand** [comment]
> Which means If I launch a container configuring it via ConfigureUtil.configureSharedNetwork, that won't work, because they will be launched on an other network.

I am not sure I understand when this happens, can you elaborate?

**Comment by jtama** [comment]
When an extension such as oidc or postgresql launch devservices, they're thread is attached to the "deployment" classloader.
When an application launches a test container, let's say in a `QuarkusTestResourceLifecycleManager` instance, they use a thread which is attached a "test" classloader.

Thus they will not be attached to the same docker/podman network.

**Comment by geoand** [comment]
Oh, I see. I kinda doubt we'll be able to fix that though...

**Comment by jtama** [comment]
Coudn't we use the `DevServicesContext` ?

**Comment by jtama** [comment]
not sure... I was just looking at the `QuarkusTestResourceLifecycleManager` interface and where it's used.

**Comment by geoand** [comment]
Where did you put that hack, I didn't catch that

**Comment by jtama** [comment]
oups sorry I was a bit quick : Labeling the network is done [here](https://github.com/quarkusio/quarkus/blob/8348ef14c119eacd4def4e636ea04bd9bd8dfd93/extensions/devservices/common/src/main/java/io/quarkus/devservices/common/ConfigureUtil.java#L35)

The lookup is done in my application code.

I think the main point here is labeling the network. There is no easy identification of the devservice network as of today (its id is random)

**Comment by geoand** [comment]
> I think the main point here is labeling the network. There is no easy identification of the devservice network as of today (its id is random)

That's an excellent point. 
Would you like to contribute your code?

**Comment by jtama** [comment]
yes of course, directly to your branch ? via a fork/pr to it ?

**Comment by geoand** [comment]
Whatever you like :)

**Comment by jtama** [comment]
I don't have write access to your repo.

**Comment by geoand** [comment]
2 options:

* Create a new PR against this which includes my commit
* Do a PR against my repo

**Comment by jtama** [comment]
This will be done by tomorrow !

**Comment by geoand** [comment]
👌

**Comment by gsmet** [comment]
> The project for which I have the need is still using 3.4.3. I know it's bad, but we have a blocker for the moment.

@jtama could you elaborate on that? Is this something that needs fixing on our side?

**Comment by jtama** [comment]
@gsmet I am not sure whether you should do something or I should. Let me explain.

We have this module that depends on kafka-stream extension, and that may or not depending on runtime event, in anyway, the kstream topolgy initialized at start time. The 3.6.0 version of the extension added devui related code that need a topology to be defined at startup otherwise it will trigger a `NullPointerException` if I recall correctly.
We could update to 3.5.3, but we would be blocked there anyway.

**Comment by lbroudoux** [comment]
Hi @jtama and @geoand,
I'm currently struggling with the shared network on DevServices as well, as explained here: https://github.com/quarkusio/quarkus/discussions/38398
I'll read thoroughly this thread but I can already guess some kind of side effects with what I'm trying to do at the moment. As I understand it, relying on the proposed `quarkus.devservices.launch-on-shared-network=true` property to determine what should be launched on the shared network will probably help me a lot...
Any thoughts if (and how) we could converge would be greatly appreciated!

**Comment by jtama** [comment]
Hi @lbroudoux 
Certainly we can, there is a draft PR here https://github.com/quarkusio/quarkus/pull/39177. It allows application to ask devservices to be run on the shared network (without having to produce SharedNetworkBuildItem), AND labels the created network so it can be found (network ids are random)

**Comment by lbroudoux** [comment]
Sorry if I'm polluting this thread a bit but as I'm having issues on a very related topic, I'd like to share findings to see if we can find a common solution...

As explained in [this other thread comment](https://github.com/quarkusio/quarkus/discussions/38398#discussioncomment-8792073), I'm facing problems in dev and test modes because database-related devservices are automatically joining the shared network when it exists.

Combining the existing, this issue and mine, there are now 3 different situations where a shared network can be created:
* By [quarkus/test-framework/junit5/src/main/java/io/quarkus/test/junit/IntegrationTestUtil.java](https://github.com/quarkusio/quarkus/blob/607ece496231d6278471e76c337d8637bc67c640/test-framework/junit5/src/main/java/io/quarkus/test/junit/IntegrationTestUtil.java#L292) when running tests in container mode (with artifact type being `jar-container` or `native-container`),
* By having the `quarkus.devservices.launch-on-shared-network=true` property as proposed here,
* By having the Microcks (or others) DevServices enabled in dev or test mode and requiring a shared network.

I think there's a situation where:
1. `quarkus.devservices.launch-on-shared-network` is `false` or undefined,
2. We're not running containerized artifact (we're in regular dev or test mode),
3. Microcks (or others) devservices is running and has created a shared network for its devservices needs

and where database-related services should still **not join** the available shared network (otherwise, they would become unreachable for the application.)

I started exploring things to see what can be used `LaunchModeBuildItem` or `ArtifactResultBuildItem`. But I can't find a way to establish we're in the above-mentioned situation when deciding whether or not the database devservices must join the shared network. I saw that `IntegrationTestUtil` is reading property from the `quarkus-artifact.properties` file but this file actually does not exist when running in dev or test mode...

Maybe we should have a way to differentiate between a shared network created because of `quarkus.devservices.launch-on-shared-network=true` and a shared network required by a devservice? Another additional build property that can be reused later on?

What do you think?

**Comment by jtama** [comment]
> and where database-related services should still not join the available shared network (otherwise, they would become unreachable for the application.)

A container launched in a shared network can still be used by code running on the host. The only subtlety is the devservice would have to configure url using the host ip instead of the network alias (that's what I've done).

**Comment by lbroudoux** [comment]
Hum... maybe that could be another way to solve this issue: having the database devservices settings the connection url properties to use the container IP and not the randomly generated host alias 🤔 ...

**Comment by geoand** [comment]
> > and where database-related services should still not join the available shared network (otherwise, they would become unreachable for the application.)
> 
> A container launched in a shared network can still be used by code running on the host. The only subtlety is the devservice would have to configure url using the host ip instead of the network alias (that's what I've done).

I agree with as I wrote [here](https://github.com/quarkusio/quarkus/discussions/38398#discussioncomment-8923939), so I am not sure I understand the original problem.

**Comment by lbroudoux** [comment]
I submitted a PR embedding the `quarkus.devservices.launch-on-shared-network` change I built upon. See https://github.com/quarkusio/quarkus/pull/39899
