### ISSUE TITLE
No way to configure iat claim as optional in quarkus-oidc

### ISSUE THREAD

**Issue by wesleysalimansdvb** [quarkusio/quarkus#39215]
### Description

quarkus-oidc currently enforces iat as mandatory claim and there is no way to make it as optional:

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java#L212

We use quarkus-oidc to support multi tenancy for our tokens, but as they do not have the iat claim present, the parsing fails with the following error:
`rejected due to invalid claims or other invalid content. Additional details: [[3] No Issued At (iat) claim present.]`

### Implementation ideas

I would recommend making the iat claim optional via configuration properties (just like the exp claim for example):

https://github.com/quarkusio/quarkus/blob/main/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcProvider.java#L201-L203

**Comment by sberyozkin** [comment]
Hi @wesleysalimansdvb 

`iat` is an important claim, it was enforced not because Keycloak sets it (many other providers will do it), but because it really must be present in the code flow for ID tokens in order to calculate the session cookie life span, also having it allows to restrict the lifespan of the tokens, for example, if the token expires in 1 year, it can be restricted to 1 day.

However, I recall thinking that may be should allow making it optional after all, but the bearer access tokens only, as in smallrye-jwt, as some issuers don't set it, AWS Load balancer is one of them, so I agree we can make it possible to relax for the bearer access token case.

FYI, that optional expiry check is only optionally true for the Back channel logout flow where some providers do not set the expiry on the logout token, and even in that case it can only be disabled if the token age property is set to compensate for the missing expiry

**Comment by wesleysalimansdvb** [comment]
Hi @sberyozkin,

I will propose a PR later this day where the iat claim is optional via a config property. 

Thanks!

**Comment by sberyozkin** [comment]
@wesleysalimansdvb You can try Jose4j directly: https://bitbucket.org/b_c/jose4j/wiki/JWS%20Examples

**Comment by sberyozkin** [comment]
I could've added an option to the JWT build API not to set `iat`, but adding it to the public API only to support the test case is a not quite ideal, but indeed, you can create a token easily Jose4j directly...

**Comment by wesleysalimansdvb** [comment]
@sberyozkin i have opened a PR (my first contribution ever, so hopefully I did everything right :) )
