### ISSUE TITLE
WebSockets Next: support method parameter injection

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#39224]
### Description

Once really handy feature of JAX-RS / Jakarta REST is that resource methods can have a set of well define parameters. 

We should introduce something similar to WebSockets next

**Comment by Ladicek** [comment]
I think being able to inject `@PathParam`s would be nice.

If we could somehow identify the message parameter, we could also treat all other parameters as CDI injection points, which might be nice as well.

**Comment by geoand** [comment]
Yeah, so in JAX-RS any method parameter that doesn't have an annotation is considered the body, I think we can do something similar.

Another thing I think that would be nice in general is to provide things in a way that is similar to JAX-RS so users can use this new stuff easily and without having to read an entire reference doc.

**Comment by geoand** [comment]
I don't see why `1. ` is a problem...

For `2.`, sure we would need annotations just like JAX-RS has them.

I am not really thinking of CDI beans, I am thinking of HTTP request related stuff.

As for `4.`, I completely fail to see why the user experience would be worse - I don't see **anyone** complaining about the corresponding features in JAX-RS (and our RR extensions to it) - on the contrary. In my view, having the runtime "inject" method parameters is the quintessence of ease of use. 



> That said, I don't say no but my opinion is 👎 ... at least in this phase.

-1 for this :)

**Comment by Ladicek** [comment]
> Yeah, so in JAX-RS any method parameter that doesn't have an annotation is considered the body, I think we can do something similar.

That is AFAIK changing in JAX-RS 4.0 or so (see e.g. https://github.com/jakartaee/rest/issues/1183 or https://github.com/jakartaee/rest/issues/1207), they body parameter will be annotated `@Body`. (I'm not sure if that will be mandatory in case no other non-annotated parameter is present, I didn't bother looking.) That makes total sense to me and could easily be mirrored here if necessary.

> WebSockets is not about processing _HTTP requests_ but _messages_.

Yeah, so that itself is not a difference. The actual difference is that HTTP is a request/response kind of communication, while WebSocket is in general a bidirectional streaming communication. However, and that's what I believe WebSockets Next makes a lot easier, WebSocket is often used in a request/response manner. In that case, a message _is_ a request.

> 3. The endpoint is a CDI bean and all dependencies should be injected there.

The same applies to JAX-RS resource classes :-)

**Comment by geoand** [comment]
> That is AFAIK changing in JAX-RS 4.0 or so (see e.g. https://github.com/jakartaee/rest/issues/1183 or https://github.com/jakartaee/rest/issues/1207), they body parameter will be annotated @Body

That's a change I like honestly.

**Comment by mkouba** [comment]
> > Yeah, so in JAX-RS any method parameter that doesn't have an annotation is considered the body, I think we can do something similar.
> 
> That is AFAIK changing in JAX-RS 4.0 or so (see e.g. [jakartaee/rest#1183](https://github.com/jakartaee/rest/issues/1183) or [jakartaee/rest#1207](https://github.com/jakartaee/rest/issues/1207)), they body parameter will be annotated `@Body`. (I'm not sure if that will be mandatory in case no other non-annotated parameter is present, I didn't bother looking.) That makes total sense to me and could easily be mirrored here if necessary.

One more useless annotation to add?

> 
> > WebSockets is not about processing _HTTP requests_ but _messages_.
> 
> Yeah, so that itself is not a difference. The actual difference is that HTTP is a request/response kind of communication, while WebSocket is in general a bidirectional streaming communication. However, and that's what I believe WebSockets Next makes a lot easier, WebSocket is often used in a request/response manner. In that case, a message _is_ a request.

My point was that in JAX-RS/HTTP app every request has metadata associated whereas in WS it does not, it's merely the metadata used when opening the connection. So it makes more sense to inject path params, headers, queries in a resource method than in a message callback.

> 
> > 3. The endpoint is a CDI bean and all dependencies should be injected there.
> 
> The same applies to JAX-RS resource classes :-)

Indeed, it does.

**Comment by geoand** [comment]
> So it makes more sense to inject path params, headers, queries in a resource method than in a message callback

I still don't understand how you've come to this conclusion...

**Comment by mkouba** [comment]
> > So it makes more sense to inject path params, headers, queries in a resource method than in a message callback
> 
> I still don't understand how you've come to this conclusion...

In WebSocket there's an initial handshake HTTP request (path param, headers, etc.) sent to the server and then message payloads flow in both directions. No metadata, no headers, etc. Just messages. A message callback represents _message processing_. In JAX-RS, a client sends an HTTP request to the server, server sends HTTP response to the client. HTTP request consists of body, headers, query string, path params, etc. A JAX-RS resource method represents _HTTP request/response processing_, right? :shrug:

**Comment by geoand** [comment]
All that is true, but you seem to think that because all the HTTP metadata is part of the handshake, it's not useful for creating messages... 

Even if that were true (which I highly doubt), then at the very least, that metadata should be avaiable in the `@OnOpen`  method.

**Comment by mkouba** [comment]
> All that is true, but you seem to think that because all the HTTP metadata is part of the handshake, it's not useful for creating messages...
> 
> Even if that were true (which I highly doubt), then at the very least, that metadata should be avaiable in the `@OnOpen` method.

I guess that it's a matter of taste. I personally prefer a similar workflow: _"focus on messages and if you need some metadata, just inject the `WebSocketConnection` and navigate the API to see what's available"_ instead of _"you can inject various metadata directly in your method arguments, using specialized annotations, the set includes: blablabla, and if you need more then just inject the `WebSocketConnection` and navigate the API to see what's available"_.

But like I said before, I'm open to discussion :D

**Comment by FroMage** [comment]
Sounds like you guys are missing real-world use-cases and user stories to figure out how people would be using the API :)

I have never used web sockets myself, so I can't really judge. I think @ia3andy has. Pretty sure @cescoffier also has. We could start asking them. Or, we could look at how other frameworks handle/document web sockets, like Rails.

Now, on a more Quarkus UX note, thinking about consistency, we've set up quite a nice story in RESTEasy Reactive where most parameters can be injected by the framework without requiring a special annotation, when it's not ambiguous. And rely on annotations when it is.

Which is why the framework can magically handle a set of known types (http request, security context…, without requiring `@Context`), or entity body (that one is tricky sometimes, and `@Entity` will help in case of ambiguity), or container types (types that contain annotated parameters).

This is extremely helpful for endpoints, but also interceptors or exception mappers.

We had an issue open to also support CDI injection as parameters, but we never did it, for a reason I can't recall, since that works for constructor parameters, so it must be possible…

Anyway, for UX regularity, it makes sense to support this same pattern of being able to "inject" known types and annotated types in a method called by the framework, in all Quarkus APIs, including WebSockets Next. As to which types and annotations make sense, I've no idea, but I'm sure you do.
