### ISSUE TITLE
Mongo-Client FindOneAndReplace blocking in some cases

### ISSUE THREAD

**Issue by gcollin** [quarkusio/quarkus#3957]
**Describe the bug**
When enhancing the provided using-mongodb-client quickstart to support PUT to replace existing documents in a collection, one wants to use 

```
FindOneAndReplaceOptions opts = new FindOneAndReplaceOptions().upsert(true);
return getCollection().findOneAndReplace(filter, document, opts);

```

**Expected behavior**
If the filter doesn't match any element, then a new document is inserted automatically (upsert)

**Actual behavior**
The call to findOneAndReplace() never returns.
However, with 

```
FindOneAndReplaceOptions opts = new FindOneAndReplaceOptions().upsert(true).returnDocument(ReturnDocument.AFTER);
return getCollection().findOneAndReplace(ret, document, opts);
```
Then a new document is created and the function returns in all cases.

**To Reproduce**
1. Modify https://github.com/quarkusio/quarkus-quickstarts/blob/master/using-mongodb-client/src/main/java/org/acme/rest/json/ReactiveFruitService.java to add replace function:

```
    public CompletionStage<Document> replace (Fruit fruit) {
        Document document = new Document()
                .append("name", fruit.getName())
                .append("description", fruit.getDescription());
        BsonDocument ret = new BsonDocument();
        ret.put("name", new BsonString(fruit.getName()));
        FindOneAndReplaceOptions opts = new FindOneAndReplaceOptions().upsert(true);

        return getCollection().findOneAndReplace(ret, document, opts);

    }
```

2. modify https://github.com/quarkusio/quarkus-quickstarts/blob/master/using-mongodb-client/src/main/java/org/acme/rest/json/ReactiveFruitResource.java
to add Put method:
```
    @PUT
    public CompletionStage<List<Fruit>>  replace(Fruit fruit) {
        return fruitService.replace(fruit).thenCompose((document) -> {
            return list();
        });
    }


```
3. Start the mongo quickstart (mvn compile quarkus:dev) with a mongo database running on localhost:207017
4. Call PUT http://localhost:8080/reactive_fruits with a new fruit name for example:

```
{
	"name":"fraise",
	"description":"Cest une fraise"
}

5. See that you'll never get any response


**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: Microsoft Windows [version 6.1.7601]
 - Output of `java -version`: 
java version "1.8.0_152"
Java(TM) SE Runtime Environment (build 1.8.0_152-b16)
Java HotSpot(TM) 64-Bit Server VM (build 25.152-b16, mixed mode)

 - Quarkus version or git rev: 0.21.2

Regards,

**Comment by gsmet** [comment]
@cescoffier can you have a look at this one (or delegate)?

**Comment by Postremus** [comment]
Underlying problem is, that findOneAndReplace can return null.

With 1.2.0.Final, I can reproduce the described blocking action.

With the new Mutiny based reactive mongo, this causes no problem. The action is not blocking, and I get the expected response from the resource - a new document.


On 1.3.0 with the axle based reactive client, I get the following exception.

```
2020-03-23 20:31:48,879 ERROR [org.jbo.res.res.i18n] (Thread-37) RESTEASY002020: Unhandled asynchronous exception, sending back 500: java.lang.IllegalStateException: Unexpected empty stream
        at io.quarkus.mongodb.impl.Wrappers.<clinit>(Wrappers.java:89)
        at io.quarkus.mongodb.impl.AxleReactiveMongoCollectionImpl.findOneAndReplace(AxleReactiveMongoCollectionImpl.java:790)
        at org.acme.rest.json.ReactiveFruitService.replace(ReactiveFruitService.java:49)
        at org.acme.rest.json.ReactiveFruitService_ClientProxy.replace(ReactiveFruitService_ClientProxy.zig:52)
        at org.acme.rest.json.ReactiveFruitResource.replace(ReactiveFruitResource.java:30)
```

Cause are the following few linex, which throw an exception when a null value is in the stream: https://github.com/quarkusio/quarkus/blob/251eaab8cd0b95b76a9002dcf16d18f6e46e080e/extensions/mongodb-client/runtime/src/main/java/io/quarkus/mongodb/impl/Wrappers.java#L96-L100


I propose, that we just remove the axle based reactive mongo, since it is deprecated since 1.3.0 anyway. I already prepared the changes for this: https://github.com/Postremus/quarkus/tree/remove-axle-reactive-mongo

@cescoffier @loicmathieu WDYT?
