### ISSUE TITLE
maven Quarkus code generation phase has failed: InvocationTargetException: io.smallrye.config.SecretKeysHandler Provider not found

### ISSUE THREAD

**Issue by camproto** [quarkusio/quarkus#39689]
### Describe the bug

Using CXF, SmallRye config with a custom SecretsKeyHandler and upgrading quarkus vom 3.2.4 to 3.6.9. 
Using the CXF extension to generate Java POJOs from WSDL files using maven and the quarkus-maven-plugin with <goal>generate-code</goal>.
Bug seems to be related to #36716 (gradle). 

 

### Expected behavior

generate-code goal did not find the custom SecretsKeyHandler at the same unchanged location it reside and worked with version 3.2.4. 

### Actual behavior

[WARNING] [io.quarkus.deployment.CodeGenerator] The following services are not (yet) available and will be disabled during configuration initialization at the current build phase:
- de.tollcollect.konz.fallgruppenbestimmung.config.FromFileSecretKeyHandler
[WARNING] [io.smallrye.config] SRCFG01005: Could not find sources with smallrye.config.locations in src/main/resources,/deployments/config/configmap,/deployments/config/secret
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  55.474 s
[INFO] Finished at: 2024-03-26T09:45:17+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.6.9:generate-code (default) on project fallgruppenbestimmung: Quarkus code generation phase has failed: InvocationTargetException: io.smallrye.config.SecretKeysHandler: Provider de.tollcollect.konz.fallgruppenbestimmung.config.FromFileSecretKeyHandler not found -> [Help 1]

### How to Reproduce?

[getting-started.zip](https://github.com/quarkusio/quarkus/files/14755578/getting-started.zip)

Attached the modified getting-started from the quarkus-quickstart repo. 

### Output of `uname -a` or `ver`

MINGW64_NT-10.0-22621 MSGN20199 3.3.4-341.x86_64 2022-05-13 22:10 UTC x86_64 Msys

### Output of `java -version`

$ java --version openjdk 17.0.3 2022-04-19 OpenJDK Runtime Environment Temurin-17.0.3+7 (build 17.0.3+7) OpenJDK 64-Bit Server VM Temurin-17.0.3+7 (build 17.0.3+7, mixed mode, shari

### Quarkus version or git rev

<quarkus.platform.version>3.6.9</quarkus.platform.version>

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvnw clean install

**Comment by camproto** [comment]
Fix in 3.6.* preferred, because this is last Java 11 supported version of Quarkus.

**Comment by geoand** [comment]
Thanks for reporting. 

@radcortez can you take a look?

> Fix in 3.6.* preferred, because this is last Java 11 supported version of Quarkus.

3.6 is no longer supported and therefore it does not receive any bug fixes.

**Comment by camproto** [comment]
understood, sic. in my projekt we are still on Java11. the upgrade to Java17 is scheduled, so a fix in latest quarkus version would be fine also.

**Comment by aloubyansky** [comment]
Including a config source related class into main sources and making it available in the source code generation phase is not supported.
The source code generation phase precedes the compile phase (sources are generated and then compiled), so `FromFileSecretKeyHandler` isn't available as a binary class at this point, which is what the warning is about.

In this case, config source related classes should be extracted in their own module and be added as a dependency of the main application module.

**Comment by aloubyansky** [comment]
I struggle to see how that could have worked though, since the class wouldn't be available for the config initialization.

So in previous versions (don't remember exactly the range) the config was for the source code generation phase was initialized in a different way but it should still not be able to pick up a class that would be compiled later.

**Comment by radcortez** [comment]
I believe this is caused by https://github.com/quarkiverse/quarkus-cxf/issues/1007.

In the Quarkus `CodeGenerator` we ban such services from the classloader, but in the case `Wsdl2JavaCodeGen`, there is an explicit call to get the configuration with the TCCL. It worked in the past because this did not exist in previous versions.

While Config services cannot be available in the code generator phase, fixing the issue in the Quarkiverse CXF repo can prevent the build from failing.

Can you please open a new issue there? Thanks!

**Comment by ppalaga** [comment]
Thanks for the report and the reproducer @camproto. I can confirm the statment of @radcortez that it worked before because Wsdl2JavaCodeGen did not rely on SmallRye config. 
I can also confirm the assessment of @aloubyansky that the current way how the classloader is setup for the codegen phase does not allow for service providers in the application code. Moving the FromFileSecretKeyHandler to a separate Maven module is valid workaround.

Anyway, I wonder, @aloubyansky, whether making the application's `src/main/resources/META-INF/services`  visible to the codegen classloader is a good idea? The service implementations are really not compiled yet, so what is the point of making SmallRyeConfig aware of `src/main/resources/META-INF/services`? Couldn't we solve this by removing `src/main/resources/META-INF/services` from the class loader? Quarkus CXF codegen would work just fine withtout those. After all it uses only build time config, while the user defined stuff is runtime.

Or perhaps I need to use a different or custom classloader for `BuildTimeConfigurationReader`? I'd expect the TCCL of a CodeGen impl. to see only the build time stuff, no?

**Comment by aloubyansky** [comment]
The config instance initialized for code generation excludes those services and the warning is logged.
I guess you are creating your own config instance?

**Comment by ppalaga** [comment]
> The config instance initialized for code generation excludes those services and the warning is logged.
> I guess you are creating your own config instance?

Thanks for the explanation, @aloubyansky. Indeed, I was calling `new BuildTimeConfigurationReader(Thread.currentThread().getContextClassLoader());` to be able to get my build time config POJO. But when reading my old comments around, I found this [little hint](https://github.com/quarkusio/quarkus/pull/35963#issuecomment-1753184692) from you which not only works but also solves the current issue. Sorry for my ignorance.
