### ISSUE TITLE
@RunOnVertxContext incompatible with @ParameterizedTest

### ISSUE THREAD

**Issue by leslion** [quarkusio/quarkus#39752]
Hi,

This is a follow up of the discussion #34222. I have the exact same scenario as described in that issue.

Is there an upcoming fix for the incompatibility between @RunOnVertxContext and @ParameterizedTest?

**Comment by cescoffier** [comment]
@mkouba I've no idea what it would mean in practice. I'm actually not sure @ParameterizedTests are well supported in @QuarkusTest. Maybe when using @QuarkusUnitTest.

**Comment by mkouba** [comment]
> I'm actually not sure @ParameterizedTests are well supported in @QuarkusTest.

It is not. We will have to revisit the `io.quarkus.test.TestMethodInvoker` SPI because currently only one invoker is supported and it has to handle all the method params. Morever, we do not use `io.quarkus.test.TestMethodInvoker`s for test template methods (such as `@RepeatedTest` or `@ParameterizedTest` (in both `@QuarkusTest` and `QuarkusUnitTest`). I have no idea why. See also my comment here: https://github.com/quarkusio/quarkus/issues/24590#issuecomment-2407004451.

**Comment by cescoffier** [comment]
@mkouba should we close all these issues as `won't fix`, or do you believe there is a near future hope. (Closing does not mean it won't be done, just that it's not going to be done soon).

**Comment by mkouba** [comment]
> [@mkouba](https://github.com/mkouba) should we close all these issues as `won't fix`, or do you believe there is a near future hope. (Closing does not mean it won't be done, just that it's not going to be done soon).

I'm not sure to be honest. We should ask the `TestMethodInvoker` SPI authors first ;-). 

CC @FroMage @geoand

**Comment by holly-cummins** [comment]
@leslion, is it easy for you to check if this is still an issue?
