### ISSUE TITLE
document @Inject ScheduledExecutorService

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#39796]
### Description

https://github.com/quarkusio/quarkus/discussions/39096#discussioncomment-8639218 indicates

@Inject ScheduledExecutorService is supported but when you search for that in our docs we dont mention it.

Particularly https://quarkus.io/guides/scheduler does not mention it.

100% for documenting the type safe/annotation based approach first but for some cases more dynamic scheduling is warranted and here an injected ScheduledExecutorService seems like our best option(or is there some other way?) and thus we should document/mention it IMO

**Comment by maxandersen** [comment]
p.s. if for some reason this is mentioned somewhere already lets at least link to it from the scheduler docs.

**Comment by mkouba** [comment]
Well, it is supported but it's not something we would like to promote. 

>  for some cases more dynamic scheduling is warranted and here an injected ScheduledExecutorService seems like our best option(or is there some other way?) and thus we should document/mention it IMO

In fact, there is an API for programmatic scheduling: https://quarkus.io/guides/scheduler-reference#programmatic_scheduling and this API should be good enough for most use cases.

In other words, the `@Inject ScheduledExecutorService` is a "last resort" and should be used with caution because it's also used by various extensions.

There is a [separate issue](https://github.com/quarkusio/quarkus/issues/13048) to support `ManagedScheduledExecutorService` (Concurrency Utilities for Java EE).

**Comment by manovotn** [comment]
Seeing some of the recent issues, I was also thinking we might want to mention it.
We can still say it's not recommended but just stating that it exists is IMO useful.

> In fact, there is an API for programmatic scheduling: https://quarkus.io/guides/scheduler-reference#programmatic_scheduling and this API should be good enough for most use cases.

We could basically just add a note about its existence underneath that section.
