### ISSUE TITLE
Elasticsearch Geopoint

### ISSUE THREAD

**Issue by teceP** [quarkusio/quarkus#39851]
### Description

Id like to use GeoPoints for Elasticsearch.

Model:
```java
public class Behave {
    public String id;
    public String name;
    GeoPoint location;
}
```

Ressource:
```java
    @POST
    public Response index(Behave behave) throws IOException{
        LOG.info(behave.location.getLat() + ", " + behave.location.getLon());
        if(behave.id == null){
            behave.id = UUID.randomUUID().toString();
        }

        esBehaveService.index(behave);
        return Response.created(URI.create("/v0/behave/" + behave.id)).build();
    }
```

There is no implementation for GeoPoint in `io.quarkus:quarkus-elasticsearch-rest-client` nor in `io.quarkus:quarkus-elasticsearch-rest-client`.

When I use `org.elasticsearch.client:elasticsearch-rest-high-level-client`, and make a POST request to my ressource (index method) with following JSON as body, it wont get mapped to the GeoPoint implementation of `org.elasticsearch.common.geo.GeoPoint`:

```json
{
    "name": "a", 
    "location": {
        "lat": 40.7128,
        "lon": -74.0060
    }
}
```
```json
{
    "name": "b", 
    "location": [40.7128, -74.0060]
}
```

I also tried to post the location as GeoHash. Also not working. 
It always raises a NullPointerException when i try to log the `behave.location.getLat()`.
When I remove the LOG call, the document gets stored in ES but without any location.

Am I missing any documentation from Quarkus which helps me to solve this problem? Could not find any Quarkus docs according to GeoPoints.

**Comment by yrodiere** [comment]
> There is no implementation for GeoPoint in io.quarkus:quarkus-elasticsearch-rest-client nor in io.quarkus:quarkus-elasticsearch-rest-client.

That's expected. This is the low-level client, which has no mapping capabilities. It deals with raw JSON strings only, as far as I remember.

> When I use org.elasticsearch.client:elasticsearch-rest-high-level-client

This client is deprecated. It's not even present in recent versions of Quarkus. You should use the [Elasticsearch Java client](https://quarkus.io/guides/elasticsearch) instead. Or use [Hibernate Search in Standalone mode](https://quarkus.io/version/main/guides/hibernate-search-standalone-elasticsearch), but unfortunately that will only be available starting with Quarkus 3.10.

>, and make a POST request to my ressource (index method) with following JSON as body, it wont get mapped to the GeoPoint implementation of org.elasticsearch.common.geo.GeoPoint:

Which serialization library are you using: jsonb, jackson, ...?
Did you check that `org.elasticsearch.common.geo.GeoPoint` fullfils the requirements to be serializable by that library? If not, you might need custom configuration (e.g. a custom serializer/deserializer).

Requalifying the issue as being related to resteasy, since this has nothing to do with the Elasticsearch client.

> Am I missing any documentation from Quarkus which helps me to solve this problem? Could not find any Quarkus docs according to GeoPoints.

You're trying to serialize types from one library (the Elasticsearch client) using another library (Jackson or jsonb or...). So no, Quarkus does not cover this (rather specific) use case.

For documentation about JSON REST services in Quarkus, see https://quarkus.io/guides/rest-json.

For documentation about how to map arbitrary java types to JSON, see the documentation of the JSON serialization library you use.
