### ISSUE TITLE
Deprecate and remove Uni<Void> invalidateIf(Predicate<Object> predicate) from Cache API

### ISSUE THREAD

**Issue by karesti** [quarkusio/quarkus#39901]
### Description

As discussed on the linked pull-requests, **invalidateIf** method is a dangerous and not recommended operation particularly for client/server caching providers such as Infinispan or Redis. The API should be minimal to apply to all caching providers. 
The as(Class<T> type) method already gives access to the underlying native cache for additional method calls proposed by the implementation.

https://github.com/quarkusio/quarkus/pull/30316
https://github.com/quarkusio/quarkus/pull/39836

### Implementation ideas

Redis and Infinispan Cache extensions, should not implement this method while is preset in the API, before removal

**Comment by mkouba** [comment]
As I stated in https://github.com/quarkusio/quarkus/pull/30316#issuecomment-2037196942 I don't think we should deprecate/remove this method but clarify that it may not be supported by the underlying implementation and throw `UnsupportedOperationException` instead :shrug:.

**Comment by cescoffier** [comment]
It actually can be used with any implementation, as soon as the key set is not too large. Thus, I would recommend keeping the method with a big warning - do not use this method if you key set if very large.

**Comment by karesti** [comment]
If the fact that no caching provider offers this method doesn't resonate with you, I'm not sure what more I can say to convince you.

**Comment by tristantarrant** [comment]
I think we should go back to the original reason for implementing this method. What was the envisioned use-case ? It feels very artificial. A quick scan of the Quarkus repo doesn't show any uses of it. Neither Spring Cache nor JCache have anything like it. None of the client/server caching implementations have an efficient way of implementing this, unless it's with server-side scripts/tasks.
If the API cannot be implemented efficiently across providers (and I don't see how it could be, since the predicate can be a fully-fledged Java method), then it provides no advantage to an explicit iteration, making it much more obvious to the developer of the involved cost.
