### ISSUE TITLE
Request to Address Vulnerability CVE-2024-270

### ISSUE THREAD

**Issue by drik98** [quarkusio/quarkus#39927]
### Describe the bug

I am reaching out to bring to your attention a vulnerability that has been identified in the Quarkus repository.

Vulnerability Details:

CVE Identifier: CVE-2024-2700
Severity: HIGH

I would like to inquire about the impact of this vulnerability on the Quarkus framework. Specifically, I am interested to know if this vulnerability affects all users of Quarkus or if it is limited to specific configurations or use cases.

Furthermore, I would like to inquire if the Quarkus team has plans to address this vulnerability in an upcoming release. If so, I would appreciate any information regarding the timeline for the release of the fix.

**Comment by gsmet** [comment]
Hi,

A fix has been pushed to 3.9.2 and we will backport the fix at some point to all supported branches. We just want to gather some feedback before doing so as the fix can affect some behaviors and we don't want it to cause regressions in maintenance branches (we already caught and fixed a regression).

As for how it can affect you, it really has something to do with using environment variables in your local environment.

If for instance you have a local env var set to `QUARKUS_DATASOURCE_PASSWORD` when you build your Quarkus app, the value will be recorded in the binary as the possible default value if the variable is not set otherwise.
The purpose of this feature was to provide sensible defaults but as you can imagine it can also leak local environment variables into the binary.
Also having an env var set at build might affect the behavior of the application if the config property is not set otherwise when running the app, as it will be considered the default for the binary.

This only affected the `quarkus.*` config namespace.

Starting with 3.9.2, only config properties set at build time values are recorded. Anything runtime is not.

**Comment by drik98** [comment]
Awesome, thank you :)

**Comment by sberyozkin** [comment]
@drik98 Hi, can you please close this question issue if you are happy with the answer from @gsmet ?
FYI, we also encourage users to report Quarkus security concerns to security@quarkus.io.
Thanks

**Comment by drik98** [comment]
> can you please close this question issue if you are happy with the answer

Will do. The only thing missing is that it seems the fixed version (3.9.2) is still reported as vulnerable on  https://ossindex.sonatype.org/vulnerability/CVE-2024-2700?component-type=maven&component-name=io.quarkus%2Fquarkus-core&utm_source=dependency-check&utm_medium=integration&utm_content=8.4.2 

> References:
> OSSINDEX - [[CVE-2024-2700] CWE-526: Information Exposure Through Environmental Variables](https://ossindex.sonatype.org/vulnerability/CVE-2024-2700?component-type=maven&component-name=io.quarkus%2Fquarkus-core&utm_source=dependency-check&utm_medium=integration&utm_content=8.4.2)
> OSSIndex - http://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2024-2700
> OSSIndex - https://github.com/advisories/GHSA-f8h5-v2vg-46rr
> 
> Vulnerable Software & Versions (OSSINDEX):
> 
> cpe:2.3:a:io.quarkus:quarkus-core:3.9.2:*:*:*:*:*:*:*

> FYI, we also encourage users to report Quarkus security concerns to [security@quarkus.io](mailto:security@quarkus.io). Thanks

I have seen that, but as the vulnerabilty was already made public I thought this could be of public interest :)

**Comment by sberyozkin** [comment]
Sure @drik98, thanks

**Comment by psini** [comment]
Could you update also the redhat entry so the other scan tool provider could be updated and the official reference (https://nvd.nist.gov/vuln/detail/CVE-2024-2700) could be updated ? 

https://access.redhat.com/security/cve/CVE-2024-2700	
https://bugzilla.redhat.com/show_bug.cgi?id=2273281

**Comment by bschuhmann** [comment]
See https://github.com/github/advisory-database/pull/4284#issue-2250116558 - GH allows making suggestions to their database. Someone from Redhat should update the other sources? And pls either properly update GH also for 3.8.4 - assuming the vulnerability is considered fixed in that version too?

**Comment by gsmet** [comment]
Yes, 3.8.4 has the fix.

We will work on propagating this info to the database.

**Comment by vlad-nev-kaseya** [comment]
Hi there! Looks like some of the tools still report this vulnerability, like:

<img width="1356" height="272" alt="Image" src="https://github.com/user-attachments/assets/2291778d-07fd-4493-b6ac-bb08686d45d8" />

https://security.snyk.io/vuln/SNYK-JAVA-IOQUARKUS-6053219
https://access.redhat.com/security/cve/cve-2023-5720
https://bugzilla.redhat.com/show_bug.cgi?id=2245700
the vulnerability is reported for both 3.24.5, 3.25.4, did not have a chance to try newer versions. Is this an issue in their databases?
