### ISSUE TITLE
() breaks title in devui

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#39992]
### Describe the bug

```
card.addPage(Page.externalPageBuilder("HomeAssistant (admin/secret)")
                        .url(uiPath, uiPath)
                        .isHtmlContent()
                        .icon("font-awesome-solid:house"));
```

result in url generated to have () in it and then not work.

raises 3 questions:

1) should ( and / and ) not be escape or at least properly routed?
2) is there a better way to handle adding info in the label/title
3) i.e. should I be able to set componentName separate from the human readable title?

**Comment by gastaldi** [comment]
How about sanitizing the component name to remove the weird chars (replacing with `_` for example)?

**Comment by phillip-kruger** [comment]
This PR (#40002) will fix the issue. 


> 1) should ( and / and ) not be escape or at least properly routed?

Yes. Fixed by the PR above. There is a workaround(s) if needed now.

> 2) is there a better way to handle adding info in the label/title

The idea is to use labels for these kind of things. Label can be static, dynamic, or even streaming (see https://quarkus.io/guides/dev-ui#adding-labels). But, in your case you are using the external url feature, and that is just a predefined static label. The PR above adds a feature that allows multiple labels.

> 3 i.e. should I be able to set componentName separate from the human readable title?

The componentName and the title can be different. In your case however, you are not providing a component (you are using a built-in component)

**Workaround options:**

- You can add this to the label, however, you will have to create a dynamic label to add both the admin/secret and the link.
- You can create a custom card and do anything (see https://quarkus.io/guides/dev-ui#custom-cards)

**After PR is merged**

Once the PR above is merged and available you can do this:

```
cardPageBuildItem.addPage(Page.externalPageBuilder("HomeAssistant")
                .staticLabel("admin/secret")
                .icon("font-awesome-solid:house")
                .isHtmlContent()
                .url(uiPath, uiPath));
```

And it will render like this:

![Home2](https://github.com/quarkusio/quarkus/assets/6836179/93233562-30dd-49e8-a5f2-1d074a71c5c7)
