### ISSUE TITLE
Some dev services are restarted on dev mode restart

### ISSUE THREAD

**Issue by Malandril** [quarkusio/quarkus#40015]
### Describe the bug

I am not sure if this is a bug, or if its as intended, but when using the dev mode, or test mode some database services are always restarted on changes, but it depends on the dev service.

For example with a test container config with `testcontainers.reuse.enable=false`
when using _mariadb_  or _mysql_ the dev container is always restarted on changes, but when using _kafka_ or _mongodb_ the services are not restarted.

With `testcontainers.reuse.enable=true` they are never stopped, but then we have to clean them up manually which makes it unpractical to use.

Happens with gradle and maven

### Expected behavior

I think it should be the same behaviour independent of the devservices.
This only happen since arround quarkus 3.7.0 , and i couldn't find any documentation on this behaviour change.
It used to never restart the devservices on reload, independent of the  `testcontainers.reuse.enable`

### Actual behavior

Some devservices are always restarted on reload, if the `testcontainers.reuse.enable` is set to `false`

### How to Reproduce?

Ensure that you disabled testcontainer re use in `~/.testcontainers.properties`
```
testcontainers.reuse.enable=false
```

Then create a sample quarkus app with
```shell
quarkus create app -x 'quarkus-rest, mongodb-panache, jdbc-mysql,hibernate-orm-panache' quarkus-virt -P 3.9.3
```

Then go in the directory and run `quarkus dev`

When restarting the application, by pressing `s` or making changes, you will see that only the _mysql_  devservice is restarted

### Output of `uname -a` or `ver`

Linux DESKTOP 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "21" 2023-09-19

### Quarkus version or git rev

3.9.3

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by geoand** [comment]
I am pretty sure what you are seeing intentional - cc @yrodiere @ozangunalp

**Comment by yrodiere** [comment]
> With testcontainers.reuse.enable=true they are never stopped, but then we have to clean them up manually which makes it unpractical to use.

This is expected. The goal of this feature is to reuse containers across processes, so they're never stopped.

I often wonder what the point of Ryuk even is, if it doesn't stop these containers after some timeouts, but... That's completely related to Testcontainers, and they may have their reasons.

> For example with a test container config with testcontainers.reuse.enable=false
when using mariadb or mysql the dev container is always restarted on changes, but when using kafka or mongodb the services are not restarted.

I must admit this sounds strange to me too.

I can understand containers restarting when you're pressing `s`, since you're, you know, asking for a restart.

On change though... I'm not sure. I guess it depends what you changed in the app exactly? Supposedly that should only happen when you change your datasource config: https://github.com/quarkusio/quarkus/blob/5bbae6fc32ca65188b91d0f86db987fde727332f/extensions/datasource/deployment/src/main/java/io/quarkus/datasource/deployment/devservices/DevServicesDatasourceProcessor.java#L79-L98

> I think it should be the same behaviour independent of the devservices.

Can't argue with that... Though there may be reasons to behave differently for Kafka. Behaving differently between mysql or mongodb seems strange though.

**Comment by Malandril** [comment]
From what i have tried it seems indepent of the changes made, editing the hello world return string triggers it for example.
It also affect the `quarkus test` mode. For each test run it restarts the _mysql_  but not _mongo_ .

It seems to only happen since quarkus 3.7.1, before that the _mysql_ devservice are not restarted each times,

```shell
quarkus create app -x 'quarkus-resteasy, mongodb-panache, jdbc-mysql,hibernate-orm-panache' quarkus-virt -P 3.6.9
```
In 3.6.9 the _mysql_ service is not restarted on application restart, or on rerunning tests. The _mongo_ and the _mysql_ services have the same behaviour.

**Comment by stuartwdouglas** [comment]
If mysql is restarting on every reload that is definitely a bug. It should only restart if you change config that affects the database.
