### ISSUE TITLE
CaffeineCache metrics are doubled

### ISSUE THREAD

**Issue by jasonsaruulo** [quarkusio/quarkus#40042]
### Describe the bug

Hey Quarkus team,

we are using Quarkus' cache and Micrometer extensions.

- https://quarkus.io/guides/cache
- https://quarkus.io/guides/telemetry-micrometer

We realized that our cache metrics are doubled.
```
# HELP cache_gets_total The number of times cache lookup methods have returned a cached (hit) or uncached (newly loaded or null) value (miss).
# TYPE cache_gets_total counter
cache_gets_total{cache="users-cache",result="hit",} 0.0
cache_gets_total{cache="users-cache",result="miss",} 2.0 
```
In the example above, we expected 1 cache miss instead.

We inject the cache, access it as `CaffeineCache` and use its `getIfPresent` method.

```
@Inject
@CacheName(CACHE_NAME)
Cache cache;

cache.as(CaffeineCache.class).getIfPresent(key);
```

We investigated the issue a bit and think that `CaffeineCacheImpl` is counting hits/misses while the underlaying `AsyncCache` is counting as well and both use the same `StatsCounter`.

https://github.com/quarkusio/quarkus/blob/main/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheImpl.java 

### Expected behavior

1 cache hit/miss is only reported once in metrics.

### Actual behavior

1 cache hit/miss is reported twice in metrics.

### Output of `java -version`

21

### Quarkus version or git rev

3.9.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Gradle 8.6

**Comment by geoand** [comment]
Thanks for reporting!

This indeed seems weird... @gwenneg do you remember why our code is also manually recording stastistics?

**Comment by ebullient** [comment]
those are not doubles. 
```
cache_gets_total{cache="users-cache",result="hit",} 0.0
cache_gets_total{cache="users-cache",result="miss",} 2.0 
```

One is hit, and one is miss.  Two separate time series because the result value is different.

**Comment by geoand** [comment]
> cache_gets_total{cache="users-cache",result="miss",} 2.0 

This is the problem AFAIU - that the miss is double counted not that there are 2 entries

**Comment by ebullient** [comment]
I totally missed that you meant the value, not the series. 🤦‍♀️

**Comment by geoand** [comment]
I made the same mistake initially!

**Comment by gwenneg** [comment]
> Thanks for reporting!
> 
> This indeed seems weird... @gwenneg do you remember why our code is also manually recording stastistics?

I don't, but I'll take a look at this tomorrow. There's an integration that checks metrics IIRC. This should have been caught, or maybe that test coverage isn't good enough.

**Comment by gwenneg** [comment]
There is indeed a bug and the integration test didn't cover it. I'll submit a PR to fix both of them shortly.

**Comment by gwenneg** [comment]
Metrics are manually updated here and it's fine because the Caffeine cache is used as a `Map`, which prevents Caffeine internal logic about metrics from being executed:
https://github.com/quarkusio/quarkus/blob/25dac4567a29b757d7071ca867afe778d46e0b33/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheImpl.java#L165-L183

On the other hand, this method (which was added more recently) relies on the Caffeine cache impl including the logic about metrics, so we should have never modified the metrics manually from the extension in that case:
https://github.com/quarkusio/quarkus/blob/25dac4567a29b757d7071ca867afe778d46e0b33/extensions/cache/runtime/src/main/java/io/quarkus/cache/runtime/caffeine/CaffeineCacheImpl.java#L126-L153
