### ISSUE TITLE
Introduce support for Spring Security

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#4037]
### Description
Decide on what features from Spring security should be supported then implement the important ones for this Epic.

### Analysis
(links to analysis docs containing architecture design work, requirements gathering, etc)

### Tasks
- [x] Support Spring Security's `@Secured` (#5225)
- [x] Support Spring Security's `@PreAuthorize` (open PR: #5787)

**Comment by hantsy** [comment]
Currently there are some issues I found when copying a very simple Spring sample to Quarkus. I think port Spring in Quarkus is a lot of work. 
 
Instead of introducing Spring Security I hope there is a more generic programmatic approach to configure Security rules by matching HTTP url/method etc, like the configuration in Spring Security.

**Comment by geoand** [comment]
Quarkus is going to introduce a native security solution soon. 
Any work we do towards this ticket will be based on that.

**Comment by ebullient** [comment]
Spring 5 Security is pretty tidy now.. we really should figure out how to pull this in, as Spring applications will tend to use it.

**Comment by ppalaga** [comment]
Two people recently asked me about Spring Security on Quarkus on a Java developer conference. (And I got no questions about other missing Spring components).

**Comment by geoand** [comment]
@ppalaga thanks for the info!

**Comment by geoand** [comment]
Has been implemented
