### ISSUE TITLE
add property to configure allowed devui origins

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#40477]
### Description

as discussed in https://github.com/quarkusio/quarkus/issues/34097 it would be good if devui had a way to configure allowed origins to allow known hosts to have http/browser requests from something is useful.

### Implementation ideas

suggested is separate property which user then explicitly can set to main http if they wish to (but not recommend nor default)

```
quarkus.devui.cors.origins=${quarkus.http.cors.origins}
```

**Comment by sberyozkin** [comment]
AFAIK, DevUI CORS filter must be restricting the origins to the localhost only, and if the local origin check passes then it delegates to the standard CORS filter.  

If we do
```
quarkus.devui.cors.origins=${quarkus.http.cors.origins}
```

then we'd need to duplicate all other CORS properties in the devui.cors namespace. IMHO doing
```
%dev.quarkus.http.cors.origins=...
``` 
should avoid it if there is a requirement to have origins available in devmode only.

If I undertand it correctly though, since DevUI Cors filter should be delegating to the main CORS filter, the only thing which blocks it from picking up the main filter's properties is the DevUI CORS localhost origin restriction.

So maybe

```
quarkus.devui.cors.restrict-origins-to-localhost=false
``` 
is what is needed to have CORS filter properties become affective, such as origins, etc

**Comment by stuartwdouglas** [comment]
There is already `quarkus.devui.cors.enabled`

Then you can just enable the normal CORS filter with dev profile config to enable the origins, and AFAIK it should also protect the dev ui.

**Comment by stuartwdouglas** [comment]
I just tested this out and it works, you can just do:

```
%dev.quarkus.dev-ui.cors.enabled=false
%dev.quarkus.http.cors=true
%dev.quarkus.http.cors.allowed-origins=http://someorigin.com
```
