### ISSUE TITLE
HTTP Access Logs should allow ISO 8601 date format 

### ISSUE THREAD

**Issue by trixpan** [quarkusio/quarkus#40614]
### Description

It is 2024. We are already asking how can we manage timestamps from Mars, yet in Quarkus we are stuck with a locale bound timestamp... :-) 

```09/May/2024:22:41:30 +000```

> | Date and time, in Common Log Format format | %t | %{DATE_TIME} |
> | ---------------------------------------------- | --- | --------------- |

There seems to be an undocumented `%{time,` option but who would want to use an undocumented option for something so critical?

**Comment by maxandersen** [comment]
@trixpan i'm having a challenge parsing your request/enhancement.

Are you saying that %{time} works for you and it does what you need and you just wish it was officially documented?
or saying that nothing seemed to work, please add a way to add iso formatting?

I'm actually personally surprised access log is using locale driven format by default :)

**Comment by gsmet** [comment]
For the record, the date format is actually correct and follows the Common Log Format used for access logging since forever (that might explain the format not exactly in line with our modern habits...)

Quoting Wikipedia:

> [10/Oct/2000:13:55:36 -0700] is the date, time, and time zone that the request was received, by default in [strftime](https://en.wikipedia.org/wiki/Strftime) format %d/%b/%Y:%H:%M:%S %z.

From https://en.wikipedia.org/wiki/Common_Log_Format .

Now I don't know if there's a better format nowadays, that is widely used.

As for `%{time,`, it looks supported in `DateTimeAttribute` and allows to provide a custom format. We should probably add it to the doc.

@trixpan care to provide a patch for https://github.com/quarkusio/quarkus/blob/main/docs/src/main/asciidoc/http-reference.adoc?plain=1#L376 ?

**Comment by trixpan** [comment]
@gsmet "correct" is subjective, after all, quarkus http logs may be json logs where the CLF doesn't directly apply, so restricting the logger abilities may be undesirable. 

I get a PR on your way later today. 

Cheers

**Comment by gsmet** [comment]
So yes, but access logs are inherited from the good old Apache days. and CLF was well... common?

Now, yes, we should document the other option and also it would be nice to provide an example for ISO 8601 that people can just copy paste.

We could even imagine a shortcut but it seems risky given the number of various options supported.

Let's at least start with the doc, that's definitely something we need to document.

**Comment by maxandersen** [comment]
@trixpan was there a doc pr made so we can close this now or ?

**Comment by trixpan** [comment]
@maxandersen apologies, life has been insane in the last few weeks. PR can be found above.

**Comment by maxandersen** [comment]
> @maxandersen apologies, life has been insane in the last few weeks. PR can be found above.

Awesome. Welcome to hopefully more sanity :)
