### ISSUE TITLE
Support Salesforce oauth_jwt_flow

### ISSUE THREAD

**Issue by argenstijn** [quarkusio/quarkus#40905]
### Description

Currently when performing OIDC with grant-type JWT with the following configuration:

```
quarkus.oidc-client.auth-server-url=https://XXXXX.salesforce.com
quarkus.oidc-client.discovery-enabled=false
quarkus.oidc-client.token-path=/services/oauth2/token
quarkus.oidc-client.client-id=XXXXXXXXXXXXXXX
quarkus.oidc-client.grant.type=jwt
quarkus.oidc-client.credentials.jwt.lifespan=3600
quarkus.oidc-client.credentials.jwt.key=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
quarkus.oidc-client.credentials.jwt.audience=${quarkus.oidc-client.auth-server-url}
```

it will create the following request:

```

POST https://XXXXXXX.salesforce.com/services/oauth2/token
Content-Type: application/x-www-form-urlencoded

grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer
    &client_assertion_type=urn%3Aietf%3Aparams%3Aoauth%3Aclient-assertion-type%3Ajwt-bearer
    &client_assertion=XXXXXXXXXXXXXXXXXXXXXXXX
```

But SF uses the JWTs as Authorization Grants (https://datatracker.ietf.org/doc/html/rfc7523) as authentication.
See  https://help.salesforce.com/s/articleView?id=sf.remoteaccess_oauth_jwt_flow.htm&type=5.

So it expects the following:
```

POST /services/oauth2/token HTTP/1.1
Host: login.example.com
Content-Type: application/x-www-form-urlencoded

grant_type= urn:ietf:params:oauth:grant-type:jwt-bearer&
assertion=eyJpc3MiOiAiM01WRz...[omitted for brevity]...ZT
```

Can we support this flow well for the OIDC client?  Or is it already possible?

**Comment by sberyozkin** [comment]
@argenstijn Hi, so far you have only configured the client authentication to use jwt-bearer, is it required ?

As far as using jwt bearer as an authorization grant is concerned, you need to provide an `assertion` property since it must be provided and not generated, you can configure it with `quarkus.oidc-client.grant-options.jwt.assertion=jwt-token` if it is already known or, if it is created dynamically or passed from the upstream endpoint, then you can supply it with the filter, for example:

https://github.com/quarkusio/quarkus/blob/main/integration-tests/oidc-client-wiremock/src/main/java/io/quarkus/it/keycloak/OidcClientRequestCustomFilter.java

(but use the `assertion` parameter)

and use with the REST client. Or, with you use `OidcClient` directly then you can use its getTokens method which accepts a  Map extraParams.

One of these options can do it, can you try please ?

**Comment by argenstijn** [comment]
The JWT is not known upfront because it's generated in the client by using a private key. 
This flow can also be used as authentication. It's almost similar with client_credentials flow with JWT. 

[For more information see stackoverflow discussion](https://stackoverflow.com/questions/29696728/oauth2-what-is-the-difference-between-the-jwt-authorization-grant-and-client-cr)

_Salesforce website:_
With the OAuth 2.0 JWT bearer token flow, the client posts a JWT to the Salesforce OAuth token endpoint. Salesforce processes the JWT, which includes a digital signature, and issues an access token based on prior approval of the app.

In this case the prior approval is when SF accept the related public key of the private key. 
It would be nice if OIDC could support this flow as well. 

So i need this part of the OidcClientImpl to be set in an assertion token.

  `jwt = OidcCommonUtils.signJwtWithKey(this.oidcConfig, this.tokenRequestUri, this.clientJwtKey);`

I could solve the problem by using the OidcRequestFilter and change the request. But would be nice if it is supported right out of the box :)

**Comment by sberyozkin** [comment]
@argenstijn Well, `quarkus.oidc-client.credentials.jwt.` configuration is about the JWT bearer client authentication meaning in this case that users want a `client_assertion` and `client_assertion_type` properties, and I'm aware of several such cases for `client_secret_jwt` and `private_key_jwt` (which is what you configure)  standard modes.

It is totally possible to use JWT bearer for the authorization grant and for the client authentication, where one can have both `assertion` and `client_assertion`, so we can't use the `quarkus.oidc-client.credentials.jwt.` configuration to setup an `assertion` because it can be supplied from elsewhere.

I think using `OidcRequestFilter` is a bit complex for this case, supplying an `assertion` property in a OIDC client filter will be easier, and for now, you can generate with JWT Build API, it will be very easy. 

I'm not sure how to support it out of the box right now. May be we can extend `jwt` grant support to support an automatic `assertion` generation... I'll need to think after PTO

**Comment by argenstijn** [comment]
Thanks for your explaination. Appreciate it :)

I am using now the following OidcRequestFilter to add the assertion form parameter
```

@ApplicationScoped
@Priority(500)
@Unremovable
public class OidcRequestCustomizer implements OidcRequestFilter {

    private static final String CLIENT_ASSERTION_PARAM = "client_assertion";    
    private static final String ASSERTION_PARAM_NAME_VALUE_TEMPLATE = "&assertion=%s";

    private static final String PARAM_SEPARATOR = "&";
    private static final String NAME_VALUE_SEPARATOR = "=";    
    
    static String bodyParameterValue(String parameterName, String formString) {  
        Objects.requireNonNull(parameterName, "parameterName cannot be null!");    
        return Stream.of(formString.split(PARAM_SEPARATOR))
                .map(s -> s.split(NAME_VALUE_SEPARATOR))
                .filter(arr -> parameterName.equalsIgnoreCase(arr[0]))
                .findFirst()
                .map(OidcRequestCustomizer::readValueOfNameValuePairIfExist).orElseThrow(() ->
                        new IllegalStateException("No '%s' found as body form parameter!.".formatted(parameterName) ));
    }


    private static String readValueOfNameValuePairIfExist(String[] arr ){         
       return arr.length==2 ? arr[1].strip() : null;        
    }
    
    @Override
    public void filter(HttpRequest<Buffer> request, Buffer buffer, OidcRequestContextProperties contextProperties) {
        var jwt = bodyParameterValue(CLIENT_ASSERTION_PARAM,buffer.toString());
        buffer.appendString(ASSERTION_PARAM_NAME_VALUE_TEMPLATE.formatted(jwt));           
    }
}
```

**Comment by sberyozkin** [comment]
Thanks @argenstijn. FYI, these filters are currently unordered.

OK, lets keep this enhancement request and see what can be done to simplify this case

**Comment by sberyozkin** [comment]
@argenstijn I was wondering what if we just add one more property to `quarkus.oidc-client.credentials.jwt.*`, lets say `quarkus.oidc-client.credentials.jwt.grant=true` which means the client authentication token is a jwt bearer grant value and therefore instead of producing `client_assertion` and `client_assertion_type` form properties, only `assertion` will be produced.

So adding `quarkus.oidc-client.credentials.jwt.grant=true` to your configuration above will lead to:
```
grant_type= urn:ietf:params:oauth:grant-type:jwt-bearer&
assertion=eyJpc3MiOiAiM01WRz...[omitted for brevity]...ZT
```

Does it sound good to you ? If yes, please consider a PR, I can help with a test.

**Comment by argenstijn** [comment]
@sberyozkin

 Sounds good. Will create a PR this somewhere this week.

**Comment by argenstijn** [comment]
I guess i should add the part to OidcClientImpl:

 else if (this.clientJwtKey != null) {
                body = !refresh ? copyMultiMap(formBody) : formBody;
                jwt = OidcCommonUtils.signJwtWithKey(this.oidcConfig, this.tokenRequestUri, this.clientJwtKey);
                if (OidcCommonUtils.isClientSecretPostJwtAuthRequired(this.oidcConfig.credentials)) {
                    body.add("client_id", (String)this.oidcConfig.clientId.get());
                    body.add("client_secret", jwt);
                } else {

                   if(grant==true) {
                            ...
                  } else {
                    body.add("client_assertion_type", "urn:ietf:params:oauth:client-assertion-type:jwt-bearer");
                    body.add("client_assertion", jwt);
                  }
                }
            }

Do you agree?

**Comment by argenstijn** [comment]
@sberyozkin

Added a pull request: 
OIDC JWTs as Authorization Grants #41061 

This still missing some test covering this new feature. 

I had some problems which checking out quarkus into intelij. So i did the commits direclly in github. 
But solved it now! So now i can again use intelij again.

**Comment by argenstijn** [comment]
Thanks :).
