### ISSUE TITLE
Arc - implement CDI inheritance rules properly

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#41]
See also http://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#inheritance.

**Comment by cescoffier** [comment]
@mkouba isn't this done?

**Comment by mkouba** [comment]
I'm not sure. @manovotn could you pls verify the relevant functionalities?

**Comment by manovotn** [comment]
@cescoffier @mkouba 
Well, Arc deliberately doesn't implement specialization so there's that.
Other than that, in type-level inheritance, we seem to be missing qualifier and stereotype inheritance while scope and interceptor bindings work.
Member-level inheritance seems to work fully.
I've written these tests to try that out - https://github.com/manovotn/quarkus/tree/inheritanceRules

**Comment by manovotn** [comment]
FTR, [CDI spec recommends](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#type_level_inheritance) that qualifiers should not declare `@Inherited`:
> qualifier types should not be declared @Inherited,

so that's definitely of minor priority.

As for stereotypes, those would be nice to have feature, but probably not mandatory right away.
It would require deep recursive search through annotations because [stereotypes can declare another stereotypes](https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#stereotypes_with_additional_stereotypes)...

**Comment by Ladicek** [comment]
I can confirm that stereotype inheritance doesn't work, as well as transitive stereotypes (stereotype declared on another stereotype). I added some `@Disabled` tests for these in a mostly-unrelated PR (#13553).

**Comment by dufoli** [comment]
so I have start to work on it but I am stuck because jandex seems to not return annotation of superclass got from classInfo.
I am maybe thinking to change completly the code and init all BeanInfo then enriched with qualifer/stereotype inherited
wdyt ? Or there is a solution to 
@mkouba 
Btw, I copy past the test from @manovotn but I will try to do my own later and add other test.

**Comment by cescoffier** [comment]
CC @Ladicek - is it something doable?

**Comment by mkouba** [comment]
> I am stuck because jandex seems to not return annotation of superclass got from classInfo.

That's intentional and well-documented. You need to walk the class hiearchy instead.

**Comment by Ladicek** [comment]
@mkouba Considering recent developments in CDI Lite and extensions, I think the annotation store in ArC should probably always include all annotations of a class (including inherited ones). This is a little more complicated for scope annotations, and I didn't really think it through yet, so this is more like a heads up than a definitive claim :-)

**Comment by mkouba** [comment]
>  I think the annotation store in ArC should probably always include all annotations of a class (including inherited ones)

I assume that you mean the annotations declared on superclasses and annotated with `@Inherited`?

**Comment by Ladicek** [comment]
Yes.

**Comment by manovotn** [comment]
@Ladicek might be worth an issue with some details so we keep track of it?

**Comment by Ladicek** [comment]
At some point, sure. I need to think more about it.
