### ISSUE TITLE
Swagger UI config at runtime

### ISSUE THREAD

**Issue by ChMThiel** [quarkusio/quarkus#41112]
### Description

i have the following situation: Our Software provides APIs for public use and APIs that are ment for internal use only.
Those two kind of APIs are described in two OpenApi.yamls, that are accessable by two endpoints:

1. Standard OpenApi-URL describing all APIs (build-in functionality of swagger-extension)
2. Public OpenApi-URL describing the public APIs only

We use the config [urls-name](https://quarkus.io/guides/all-config#quarkus-swagger-ui_quarkus-swagger-ui-urls-name) to enable a drop-down-box in swagger to let the user choose between those options.
So far everything works just fine :+1:

Now there is a request to disable the option to show the public-APIs in some customer installations.
During build this is not a problem: If the application.properties contains only one urls-name (the one pointing to the public API), the drop-down-box is automatically removed (because there is nothing to choose) and the given URL is used to load the OpenApi to be used by swagger. Just as i want :+1:

But because this config-option is a build-time-option, i can not change it during runtime (e.g. by setting it in a K9s configMap on customer-site)... :worried:

@phillip-kruger  Do you see any way to change this config from build-time to run-time?

see also [zulipchat](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/swagger.20UI.20config.20at.20runtime)

**Comment by phillip-kruger** [comment]
The Swagger config are used at build time to generate the `index.html` for swagger ui. Because this is done at build time, there are no way (currently) to do this at run time. In other words it's more work than just moving the property to runtime. You are welcome to suggest a PR for this effort.

**Comment by ChMThiel** [comment]
The only way i could provide a solution for this is to move the whole `index.html` generation process to runtime - given current implementation of smallrye's [IndexHtmlCreater](ui/open-api-ui/src/main/java/io/smallrye/openapi/ui/IndexHtmlCreator.java) (Changing that would be over the top IMHO).

But the maxime of quarkus is to do as much as possible on build-time to make startup as quick a possible.
I don't know the impact (time) of moving the index.html-generation to runtime. Worst case the PR might be rejected...

The the only other way would be to change the process on smallrye's side...but i assume it's not worth the effort.

@phillip-kruger WDYT? If my solution (move index.html generation from buildtime to runtime) has a chance to be approved, i can ask my boss if he will given me the time to implement that.

**Comment by phillip-kruger** [comment]
I think it can be approved if, 1) it is not the default, i.e by default it works like it does currently, but in the case of some config, it switches to runtime and (or) 2) only some fields are added in runtime, so most work is still done during build time

**Comment by phillip-kruger** [comment]
Another option is to allow a custom index.html, that users can provide at runtime.

**Comment by phillip-kruger** [comment]
You can also try and do this with JavaScript somehow. And allow adding custom js

**Comment by ChMThiel** [comment]
I think all proposed options take a lot of effort - not worth for my request: don't show private APIs on customer site.
For now the default 'show public apis' in the drop-down box must suffice.

**Comment by donndorf** [comment]
Hey there,

we are facing similar issues. We are deploying to a K8s cluster fort testing and want to access the Swagger UI via Ingress.
This then fails because the URL which is used to fetch the openapi is rewritten ( https://myhost/myapp/q/openapi -> https://myhost/q/openapi).

I don't see a way to counter this behaviour at runtime.
Sadly [quarkus.smallrye-openapi.path](https://quarkus.io/guides/openapi-swaggerui#quarkus-smallrye-openapi_quarkus-smallrye-openapi-path) is also only configurable at build time.

It seems like for the servers section it was possible to allow runtime configuration: https://github.com/quarkusio/quarkus/pull/27172 

Would it be that much harder to implement it for urls and/or openapi-path? I haven't yet looked into the code but was just wondering since i saw this other issue.

Or should one take a completely different approach when trying to serve SwaggerUi on a K8s cluster? 
 
 Thanks!

**Comment by donndorf** [comment]
I can currently only think of the workaround, where i adjust my quarkus.smallrye-openapi.path to be /myapp/myopenapipath . That should probably make it work but would require every single deplyoment/ingress to also always have /myapp as adress

**Comment by phillip-kruger** [comment]
You can use Runtime Filters to change the OpenAPI Schema doc to anything you like. That would be the way to do this. See https://quarkus.io/guides/openapi-swaggerui#enhancing-the-openapi-schema-with-filters

**Comment by donndorf** [comment]
@phillip-kruger this way i can only adjust the contents of the openAPI document right? I don't see how i could configure the path at which Quarkus serves my openAPI. Am i missing something?

Also i cannot configure the [quarkus.swagger-ui.urls."name"](https://quarkus.io/guides/openapi-swaggerui#quarkus-swaggerui_quarkus-swagger-ui-urls-name) to configure from where i fetch APIs

**Comment by phillip-kruger** [comment]
Just to make sure I understand your issue, swagger ui does not find the openapi schema ? If so have you tried the [quarkus.swagger-ui.urls."name"](https://quarkus.io/guides/openapi-swaggerui#quarkus-swaggerui_quarkus-swagger-ui-urls-name) property?

**Comment by donndorf** [comment]
The issue is with configuration at runtime. 
It is basically the same as here: 
https://stackoverflow.com/questions/76652113/accessing-quarkus-swagger-ui-in-k8s-environment

Since my Quarkus app is behind an ingress and the path is rewritten, it is looking for the api Definition at the wrong place.

As a workaround i quarkus.swagger-ui.query-config-enabled=true and now call my swagger-UI with the adjusted URL.

Meaning i can call https://myhost/myapp/q/swagger-ui?url=https://myhost/myapp/q

**Comment by donndorf** [comment]
That overrides the default url that is used to fetch my api
