### ISSUE TITLE
Error during native compilation

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#4156]
**Describe the bug**

I have created a simple hello world project, and then I compiled to native without any problem: `mvn package -Pnative -Dnative-image.docker-build=true`

Then I added next dependencies https://pastebin.com/ecDazT1v

And when running native compilation without any other modification I get the next stacktrace: 
https://pastebin.com/dhsK3GBv

**Expected behavior**
Should compile into native

**Actual behavior**
Exception

**Environment (please complete the following information):**
 -  Quarkus 0.22.0

**Comment by geoand** [comment]
@lordofthejars where you perhaps able to narrow down the set of dependencies that causes the problem?

**Comment by limadelrey** [comment]
@lordofthejars I think that behaviour is happening because of quarkus-hibernate-orm-panache maven dependency. In fact it is a known issue (#2482). Just add a class with an `@Entity` annotation and configure your datasource on application.properties file and the error should be gone ([https://quarkus.io/guides/hibernate-orm-guide]()).

**Comment by lordofthejars** [comment]
weird, but definitely not a blocker or high priority bug.

Missatge de limadelrey <notifications@github.com> del dia dt., 24 de set.
2019 a les 18:14:

**Comment by stuartwdouglas** [comment]
I just tested this out and it seems fine now.
