### ISSUE TITLE
Implement token propagation in the REST client

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#4214]
The token should be retrieved from the `SecuredIdentity` credentials. 

The `SecuredIdentity` must be propagated using MP Propagation (need a provider managing propagation)

**Comment by kenfinnigan** [comment]
Is it a token that's come in from an external request, or one we've created internally?

If the former, then you can use header propagation in the REST Client to pass it along

**Comment by sberyozkin** [comment]
@stuartwdouglas what flow are you referring to ? What about a proper association with the roadmap ideas to do with the token propagation (impersonation vs delegation) ? The automatic end to end user authentication enabled via the token propagation is an anti-pattern. @pedroigor FYI

**Comment by sberyozkin** [comment]
@stuartwdouglas it has to be coordinated with smallrye-jwt `JsonWebToken` which I thought we agreed about

**Comment by stuartwdouglas** [comment]
This issue was created from the original roadmap 1.0 board following the F2F, I just went through and hit the button to turn them from notes into real issues. 

The original design from the F2F was to use Credential for propagation, which is why this was written the way it was.

**Comment by sberyozkin** [comment]
@stuartwdouglas thanks for the clarification :-). Actually, now that I think about it, it can be a good master issue for dealing with the mechanics of the token propagation in scope of the client request, since it will be up to the OIDC adapter how to prepare a token for the possible propagation (i.e, whether to use the currently validated token picked up from a header, or have this token exchanged first, etc). I keep typing `JsonWebToken` everywhere :-), but it probably does not conflict with the 'Credential' idea because the latter can be mapped to the former

**Comment by stuartwdouglas** [comment]
Credential is basically just the raw token (in the current impl). If something more advanced is need we might need to re-think this API. I wonder if there are cases where you would want to generate a new token for propagation with a different set of claims.

**Comment by pedroigor** [comment]
@stuartwdouglas There are cases where you want a new token in order to invoke other services. Take the [`audience` claim](https://tools.ietf.org/html/rfc7519#section-4.1) as an example.

Another example could be related to the access scope of the token which can be different across different services even though services are dealing with the same subject.

**Comment by stuartwdouglas** [comment]
All of this info should be available from the SecurityIdentity. We probably just need some kind of config or interface to control how this is propagated.

**Comment by sberyozkin** [comment]
@stuartwdouglas, @pedroigor we should probably have an OIDC adapter providing such an interface implementation where it will decide, depending on its configuration, what to do with the currently available token for the propagation purposes, use the token exchange or return as is if really needed, etc

**Comment by sberyozkin** [comment]
@stuartwdouglas Hi Stuart, I think I'll close this one as we have another issue for the token exchange and also there will be an issue related to the JAX-RS + Security sync epic about a possibility of launching the security from the JAX-RS chain - this will make it possible to auto-propagate MP REST Client headers. And right now one can also use MP Context Propagation or `JsonWebToken.getRawToken()` to propagate manually.
So I believe we can safely close this issue as Emmanuel is asking to close a few if possible
