### ISSUE TITLE
Support proxy protocol

### ISSUE THREAD

**Issue by chonton** [quarkusio/quarkus#4227]
**Describe the enhancement**
Support [proxy protocol](https://www.haproxy.org/download/1.8/doc/proxy-protocol.txt). Undertow supports version 1 by setting [useProxyProtocol](http://undertow.io/undertow-docs/undertow-docs-2.0.0/#listeners-2) on the listener.

Interested in this enhancement, please +1 via the emoji/reaction feature of GitHub (top right).

**Configuration suggestion**
I suggest using an annotation such as ```@ListenerOptions``` on the ```@Path``` or ```@WebServlet``` annotations.

**Additional context**
#3626 is a similar request in that an undertow functionality needs to be exposed to the programmer.

**Comment by chonton** [comment]
Snce Vertx is now the implementation layer, this no longer makes sense

**Comment by OOTS** [comment]
Hey @chonton,
Vertx also seems to support the proxy protocol: https://vertx.io/docs/apidocs/io/vertx/core/http/HttpServerOptions.html#setUseProxyProtocol-boolean- . Anyway, I'd still be interested in this feature.

**Comment by Reamer** [comment]
@OOTS 
Have you figured out how to enable this feature in Quarkus?

**Comment by OOTS** [comment]
@Reamer 
No, but I haven't even tried seriously so far (the project that I needed this for was put on hold).

**Comment by OOTS** [comment]
I've created #32124 as a replace for this issue, since I'm not able to re-open this one.

As an (ugly) workaround, one could deploy HAProxy (or maybe Nginx) as an additional reverse proxy running on the same machine as the application using Quarkus. This software could be used to translate the PROXY protocol to something that Quarkus already understands, e.g. the `Forwarded` header.
