### ISSUE TITLE
StackOverflowError when firing event in @PreDestroy listener

### ISSUE THREAD

**Issue by timonzi** [quarkusio/quarkus#42337]
### Describe the bug

We currently try to switch from 3.2.9.Final to 3.8.5. Here we run into the problem, that we get an `StackOverflowError` during the destroy phase of a `RequestScoped` bean. Here we fire an event in a method which is annotated with `@PreDestroy`. This seems to create a new context, which leads to the creation of a new instance of our request scoped bean.

The reason for the loop/StackOverflowError seems to be a change in the method `io.quarkus.arc.impl.RequestContext#isActive()`, because in version 3.8.5 a check for the request context state is done, which was not the case in 3.2.9.Final. 

**3.8.5**
```
@Override
public boolean isActive() {
    return isActive(currentContext.get());
}

private boolean isActive(RequestContextState state) {
    return state == null ? false : state.isValid();
}
```

**3.2.9.Final**
```
@Override
public boolean isActive() {
    return currentContext.get() != null;
}
```

This method is used in `io.quarkus.arc.impl.EventImpl.Notifier#notify(T, io.quarkus.arc.impl.EventImpl.ObserverExceptionHandler, boolean)`. If the request context is not "active" (marked as invalid), it "activates" the request context, notifies the observers and terminates the request context afterwards.

```
void notify(T event, EventImpl.ObserverExceptionHandler exceptionHandler, boolean async) {
    if (!isEmpty()) {
        //[...]

        // Non-tx observers notifications
        // req. context is activated if not in strict mode and not for lifecycle events such as init/shutdown
        if (activateRequestContext) {
            ManagedContext requestContext = Arc.container().requestContext();
            if (requestContext.isActive()) {
                notifyObservers(event, exceptionHandler, predicate);
            } else {
                try {
                    requestContext.activate();
                    notifyObservers(event, exceptionHandler, predicate);
                } finally {
                    requestContext.terminate();
                }
            }
        } else {
            notifyObservers(event, exceptionHandler, predicate);
        }
    }
}
```

This activation leads to the creation of the request scoped bean (same as where we fire the event) and also to the termination/destroy of the bean. This again leads to the creation, etc.

As mentioned, we didn't had this problem, as in 3.2.9.Final, a request context was active when the current context was not null. Now it additionally checks the state, which is set, before the `PreDestroy` observers are called.

**io.quarkus.arc.impl.RequestContext#destroy(io.quarkus.arc.InjectableContext.ContextState)**
```
if (reqState.invalidate()) { // state is set to invalid
    // Fire an event with qualifier @BeforeDestroyed(RequestScoped.class) if there are any observers for it
    fireIfNotEmpty(beforeDestroyedNotifier);

    // [...]
}
```

Here I don't know whether this is useful as I would expect that my beans/contexts are still valid, as we are in the **Pre**Destroy phase.

Maybe the problem is a different, but this is what I saw.

### Expected behavior

I would expect that it works as before (with Quarkus 3.2.9.Final) - no new beans/contexts should be created during destroy of my request scoped bean. I think the current context should not be invalidated before the observers/listeners are called. But in the end the solution might be different.

### Actual behavior

Everytime the request scoped bean is destoyed, a new one is created, which then gets destoyed, which creates a new one, etc. So we end up in an stack overflow.

When I log the stacktrace in a `PostConstruct` listener, we can see the behavior:

```
2024-08-06 12:29:22,475 INFO  [org.acm.imp.RequestContextIdImpl] (main) postConstruct stacktrace [a939c69e-d0f1-4a7a-9062-89534ba85d45] 
        java.base/java.lang.Thread.getStackTrace(Thread.java:2450)
        org.acme.impl.RequestContextIdImpl.postConstruct(RequestContextIdImpl.java:25)
        org.acme.impl.RequestContextIdImpl_Bean.doCreate(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.create(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.create(Unknown Source)
        io.quarkus.arc.impl.RequestContext$1.get(RequestContext.java:79)
        io.quarkus.arc.impl.RequestContext$1.get(RequestContext.java:75)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.c0(Unknown Source)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.computeIfAbsent(Unknown Source)
        io.quarkus.arc.impl.RequestContext.getIfActive(RequestContext.java:75)
        io.quarkus.arc.impl.ClientProxies.getSingleContextDelegate(ClientProxies.java:28)
        org.acme.impl.RequestContextIdImpl_ClientProxy.arc$delegate(Unknown Source)
        org.acme.impl.RequestContextIdImpl_ClientProxy.getId(Unknown Source)
        org.acme.impl.ScopeControlImpl.requestBegin(ScopeControlImpl.java:42)
        org.acme.impl.ScopeControlImpl_Observer_requestBegin_mw2VP99394RKqVtjuIvXp784XXI.notify(Unknown Source)
        io.quarkus.arc.impl.EventImpl$Notifier.notifyObservers(EventImpl.java:346)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:334)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:263)
        io.quarkus.arc.impl.RequestContext.fireIfNotEmpty(RequestContext.java:238)
        io.quarkus.arc.impl.RequestContext.activate(RequestContext.java:145)
        io.quarkus.arc.ManagedContext.activate(ManagedContext.java:17)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:327)
        io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        org.acme.impl.ScopeControlImpl.fireRequestEnd(ScopeControlImpl.java:34)
        org.acme.impl.ScopeControlImpl_ClientProxy.fireRequestEnd(Unknown Source)
        org.acme.impl.RequestContextIdImpl.preDestroy(RequestContextIdImpl.java:39)
        org.acme.impl.RequestContextIdImpl_Bean.doDestroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:78)
        io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:26)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.removeEach(Unknown Source)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:217)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:200)
        io.quarkus.arc.ManagedContext.terminate(ManagedContext.java:50)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:330)
        io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        org.acme.impl.ScopeControlImpl.fireRequestEnd(ScopeControlImpl.java:34)
        org.acme.impl.ScopeControlImpl_ClientProxy.fireRequestEnd(Unknown Source)
        org.acme.impl.RequestContextIdImpl.preDestroy(RequestContextIdImpl.java:39)
        org.acme.impl.RequestContextIdImpl_Bean.doDestroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:78)
        io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:26)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.removeEach(Unknown Source)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:217)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:200)
        io.quarkus.arc.ManagedContext.terminate(ManagedContext.java:50)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:330)
        io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        org.acme.impl.ScopeControlImpl.fireRequestEnd(ScopeControlImpl.java:34)
        org.acme.impl.ScopeControlImpl_ClientProxy.fireRequestEnd(Unknown Source)
        org.acme.impl.RequestContextIdImpl.preDestroy(RequestContextIdImpl.java:39)
        org.acme.impl.RequestContextIdImpl_Bean.doDestroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:78)
        io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:26)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.removeEach(Unknown Source)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:217)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:200)
        io.quarkus.arc.ManagedContext.terminate(ManagedContext.java:50)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:330)
        io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        org.acme.impl.ScopeControlImpl.fireRequestEnd(ScopeControlImpl.java:34)
        org.acme.impl.ScopeControlImpl_ClientProxy.fireRequestEnd(Unknown Source)
        org.acme.impl.RequestContextIdImpl.preDestroy(RequestContextIdImpl.java:39)
        org.acme.impl.RequestContextIdImpl_Bean.doDestroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        io.quarkus.arc.impl.AbstractInstanceHandle.destroyInternal(AbstractInstanceHandle.java:78)
        io.quarkus.arc.impl.ContextInstanceHandleImpl.destroy(ContextInstanceHandleImpl.java:26)
        io.quarkus.arc.generator.Default_jakarta_enterprise_context_RequestScoped_ContextInstances.removeEach(Unknown Source)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:217)
        io.quarkus.arc.impl.RequestContext.destroy(RequestContext.java:200)
        io.quarkus.arc.ManagedContext.terminate(ManagedContext.java:50)
        io.quarkus.arc.impl.EventImpl$Notifier.notify(EventImpl.java:330)
        io.quarkus.arc.impl.EventImpl.fire(EventImpl.java:82)
        org.acme.impl.ScopeControlImpl.fireRequestEnd(ScopeControlImpl.java:34)
        org.acme.impl.ScopeControlImpl_ClientProxy.fireRequestEnd(Unknown Source)
        org.acme.impl.RequestContextIdImpl.preDestroy(RequestContextIdImpl.java:39)
        org.acme.impl.RequestContextIdImpl_Bean.doDestroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
        org.acme.impl.RequestContextIdImpl_Bean.destroy(Unknown Source)
[...]
```

During the Maven build (with tests), we often run into a StackOverflowError (adjusted log of our real application):

```
2024-08-01 09:17:52,079 ERROR [io.qua.arc.imp.UncaughtExceptions] (main) Error occurred while destroying instance of CLASS bean [types=[org.acme.impl.AbstractContextId, java.io.Serializable, org.acme.impl.RequestContextIdImpl, org.acme.ContextId, java.lang.Object], qualifiers=[@Any, @RequestId], target=org.acme.impl.RequestContextIdImpl]: java.lang.StackOverflowError [Error Occurred After Shutdown]
2024-08-01 09:17:52,259 INFO  [io.quarkus] (main) context-loop-test stopped in 0.219s
@QuarkusTest has detected a hang, as there has been no test activity in PT10M
To configure this timeout use the quarkus.test.hang-detection-timeout config property
A stack trace is below to help diagnose the potential hang
=== Stack Trace ===
...
```

### How to Reproduce?

Reproducer: https://github.com/timonzi/quarkus-3.8-bean-loop

Execute `mvn clean install`

Hints: 
* When executing the tests via the IDE (in my case IntelliJ), the test finishes after some seconds - but at the end the problem is the same.
* When executing the tests via Maven, we often (not always) get the StackOverflowError (in our real application)
* The log output is pretty long as I log the  stacktrace everytime we run into the `PostConstruct` listener.

### Output of `uname -a` or `ver`

Linux timon-laptop 6.9.10-1-MANJARO #1 SMP PREEMPT_DYNAMIC Fri Jul 19 15:08:51 UTC 2024 x86_64 GNU/Linux

### Output of `java -version`

openjdk version "17.0.12" 2024-07-16

### Quarkus version or git rev

3.8.5

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.8 (36645f6c9b5079805ea5009217e36f2cffd34256)

### Additional information

I tested with multiple Maven and OpenJDK versions.

And sorry for adding so much code and logs.

**Comment by mkouba** [comment]
Hello @timonzi and thanks for the report!

First of all, it's a good practice to avoid communication with other components in a `@PreDestroy` callback of a bean, i.e. calling other beans and firing events, esp. if such communication may result in an "ordering issue". Your reproducer is a good example of this _invalid_ communication. Another example could be calling a dependency `B` in a `@PreDestroy` callback of a bean `A` where both `A` and `B` live in the same CDI context.

The main problem is that ordering is not well-defined in such cases. For example, when we destroy the request context then it's no longer active and so a new one is created in the `@PreDestroy` callback of `RequestContextIdImpl`. And so the  StackOverflowError is _thrown as expected_ because your code creates a new `RequestContextIdImpl` for each request context initialized.

> The reason for the loop/StackOverflowError seems to be a change in the method io.quarkus.arc.impl.RequestContext#isActive(), because in version 3.8.5 a check for the request context state is done, which was not the case in 3.2.9.Final.

The current check is correct. It worked before by coincidence. If a request context is destroyed then it's no longer valid.

I think that we should wait for my colleagues' opinion but my opinion is:
1. Never ever call other beans/fire events from a `@PreDestroy` callback.
2. Works as expected.

**Comment by timonzi** [comment]
Thank you for your fast response and your explanations! I would be interested to hear what your colleagues will say to this topic.

> The current check is correct. It worked before by coincidence. If a request context is destroyed then it's no longer valid.

The question for me is, whether the request context state should be invalidated before the `@PreDestroy` annotated methods are called. Because of the name of the annotation (**Pre**Destroy) I would expect that it really happens before anything is destroyed, respectively in this case also the invalidation.  If such listeners would be called in beforehand, we probably don't have the problem. But I don't know the implementation so well to be able to say what effects this would have or why it was implemented in this way.

**Comment by mkouba** [comment]
> I would expect that it really happens before anything is destroyed, respectively in this case also the invalidation.

Well, it _must happen_ before the bean is actually destroyed but not necessarily before the context is being destroyed. These are two different things/concepts.

**Comment by manovotn** [comment]
I think this is a case related to Quarkus non-standard feature where we choose to activate req. context for sync. observers which causes a cycle. See https://quarkus.io/guides/cdi-reference#request-context-lifecycle

Personally I don't think working with other beans from within pre destroy is always bad but it does get tricky and potentially non portable. Generally, you should be able to work with a "wider" scoped beans so trying to resolve an app. scoped bean from predestroy callback of a req. bean should be fine.
Events work similarly as you have to be aware what context you need active and which beans are receivers of given events.

That being said, I agree with Martin that for your use case it works as intended and was previously working by accident.

**Comment by mkouba** [comment]
> I think this is a case related to Quarkus non-standard feature where we choose to activate req. context for sync. observers which causes a cycle. See https://quarkus.io/guides/cdi-reference#request-context-lifecycle

Yes, we should also clarify that the request context is not activated in the [strict mode](https://quarkus.io/guides/cdi-reference#strict_mode) and for container lifecycle events (such as `@Initialized(RequestScoped.class)`). So it's the `ScopeEvent` that triggers activation.

> Generally, you should be able to work with a "wider" scoped beans so trying to resolve an app. scoped bean from predestroy callback of a req. bean should be fine.

Yes, this should be fine but I would still try to avoid it, esp. for a complex dependency tree.

> Events work similarly as you have to be aware what context you need active and which beans are receivers of given events.

The problem with events is that you never know who observes the event due to its decoupled nature.

**Comment by Ladicek** [comment]
I looked at the reproducer and it felt extremely abstract to me, to the point I couldn't understand it. I started simplifying it down, and ended up with these 3 classes:

```java
@RequestScoped
public class RequestId {
    private final Lock lock = new ReentrantLock(false);

    private String id;

    @Inject
    Event<RequestEndEvent> requestEnd;

    public String getId() {
        lock.lock();
        try {
            if (id == null) {
                id = UUID.randomUUID().toString();
            }
        } finally {
            lock.unlock();
        }
        return id;
    }

    @PostConstruct
    void postConstruct() {
        boolean active = Arc.container().requestContext().isActive();
        String id = getId();
        Log.info("RequestId.postConstruct, active: " + active + ", id: " + id);
    }

    @PreDestroy
    void preDestroy() {
        boolean active = Arc.container().requestContext().isActive();
        String id = getId();
        Log.info("RequestId.preDestroy, active: " + active + ", id: " + id);
        requestEnd.fire(new RequestEndEvent(id));
    }
}
```

```java
public class RequestEndEvent {
    private final String id;

    public RequestEndEvent(String id) {
        this.id = id;
    }

    public String getId() {
        return id;
    }
}
```

```java
@ApplicationScoped
public class RequestListener {
    public void requestBegin(@Observes @Initialized(RequestScoped.class) Object o) {
        boolean active = Arc.container().requestContext().isActive();
        Log.info("RequestListener.requestBegin, active: " + active);
    }

    public void requestBeforeEnd(@Observes @BeforeDestroyed(RequestScoped.class) Object o) {
        boolean active = Arc.container().requestContext().isActive();
        Log.info("RequestListener.requestBeforeEnd, active: " + active);
    }

    public void requestEnd(@Observes @Destroyed(RequestScoped.class) Object o) {
        boolean active = Arc.container().requestContext().isActive();
        Log.info("RequestListener.requestEnd, active: " + active);
    }

    public void requestEnd(@Observes RequestEndEvent event) {
        boolean active = Arc.container().requestContext().isActive();
        Log.info("RequestListener.requestEnd, active: " + active + ", id: " + event.getId());
    }
}
```

Then, on one HTTP request, the following is logged:

```
2024-08-09 12:45:54,112 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestBegin, active: true
2024-08-09 12:45:54,116 INFO  [org.acm.RequestId] (executor-thread-1) RequestId.postConstruct, active: true, id: 6683e176-b38c-42f4-974a-449eb59b04cb
2024-08-09 12:45:54,119 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestBeforeEnd, active: false
2024-08-09 12:45:54,119 INFO  [org.acm.RequestId] (executor-thread-1) RequestId.preDestroy, active: false, id: 6683e176-b38c-42f4-974a-449eb59b04cb
2024-08-09 12:45:54,120 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestBegin, active: true
2024-08-09 12:45:54,120 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestEnd, active: true, id: 6683e176-b38c-42f4-974a-449eb59b04cb
2024-08-09 12:45:54,120 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestBeforeEnd, active: false
2024-08-09 12:45:54,120 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestEnd, active: false
2024-08-09 12:45:54,120 INFO  [org.acm.RequestListener] (executor-thread-1) RequestListener.requestEnd, active: false
2024-08-09 13:02:03,818 INFO  [io.quarkus] (Shutdown thread) context-loop stopped in 0.026s
```

This shows a few interesting things:

1. We first fire `@BeforeDestroyed(RequestScoped.class)`, then destroy the bean instances in the request context, then fire `@Destroyed(RequestScoped.class)`. However, we _deactivate_ the request scope even before we fire the `@BeforeDestroyed` event. I guess that's what @mkouba alluded to above, although not exactly correctly. I believe we do always destroy all the [remaining] bean instances before we destroy the context -- the question is when do we _deactivate_ the request context. Deactivation and destruction are by necessity two different things and they cannot always happen at the same time (at the very least, this is because we may deactivate and reactivate the request context multiple times before actually destroying it).
2. Since we deactivated the request context, we activate it _again_ for the duration of the `RequestEndEvent` observer. That's what @manovotn mentioned above. If I set `quarkus.arc.strict-compatibility` to `true`, this doesn't happen and the output is a little clearer, but the present output is not too hard to understand either.
3. It works! As in, there is no infinite regress. However, note that I specifically avoided injecting `RequestId` into any of those observers, and also note that even if the request context is active in the `RequestEndEvent` observer, it is a _different_ request context than the one that fired the event.

In my opinion, the question here really is why is the request context not active during the `@PreDestroy` lifecycle callback. I see `ManagedContext.terminate()` first destroys the context and only then deactivates it, but apparently, we do that in different order sometimes. That doesn't have to be wrong, but it seems suspicious.

**Comment by mkouba** [comment]
> I started simplifying it down, and ended up with these 3 classes:

Your "reproducer" is not accurate. The original problem arises because `ScopeControlImpl` [observes `@Initialized(RequestScoped.class)`](https://github.com/timonzi/quarkus-3.8-bean-loop/blob/main/src/main/java/org/acme/impl/ScopeControlImpl.java#L39-L44) and in this observer the `RequestContextIdImpl` bean is obtained. However, in the `@PreDestroy` callback of `RequestContextIdImpl` an event is fired. Now, in Quarkus we activate the request context per observer notification by default (disabled if `quarkus.arc.strict-compatibility=true`). And since the request context is not active during destruction of the request context, we activate a new one -> stack overflow.

>We first fire @BeforeDestroyed(RequestScoped.class), then destroy the bean instances in the request context, then fire @Destroyed(RequestScoped.class). 

Yes, this is (more or less) mandated by the spec.

> However, we deactivate the request scope even before we fire the @BeforeDestroyed event. I guess that's what @mkouba alluded to above, although not exactly correctly. 

Hm, I'm not sure what you mean with "exactly correctly". But yes, we deactivate the request context before it's destroyed and I believe that it makes a lot of sense. In fact, in case of request context we "invalidate" the context (that's another concept we use because of Context Propagation ;-) before we destroy the bean instances. That's why it's effectively "inactive" during `@PreDestroy`.

> I believe we do always destroy all the [remaining] bean instances before we destroy the context 

Well, destroying the context means destroying the bean instances.

> -- the question is when do we deactivate the request context. Deactivation and destruction are by necessity two different things and they cannot always happen at the same time (at the very least, this is because we may deactivate and reactivate the request context multiple times before actually destroying it).

Yes, they are by necessity two different things but in most cases (and also for most users) it's an "atomic" operation.

> If I set quarkus.arc.strict-compatibility to true, this doesn't happen and the output is a little clearer, but the present output is not too hard to understand either.

Yes, as I mentioned in https://github.com/quarkusio/quarkus/issues/42337#issuecomment-2274993786 - `quarkus.arc.strict-compatibility=true` disables the non-portable feature described in https://quarkus.io/guides/cdi-reference#request-context-lifecycle.

> In my opinion, the question here really is why is the request context not active during the @PreDestroy lifecycle callback. 

In my opinion, it does not make any sense to keep the request context active while destroying it. It could lead to other unexpected problems, such as, you can create new request scoped beans when the context is destroyed. 

> I see ManagedContext.terminate() first destroys the context and only then deactivates it, but apparently, we do that in different order sometimes. That doesn't have to be wrong, but it seems suspicious.

Yes, this is a bit weird and should IMO be the other way around. But in practice, it's not that important because we never deactivate `@ApplicationScoped` and `@Singleton`, and request context has the concept of invalidation so `deactive()` is more less superfluous.

**Comment by Ladicek** [comment]
> Your "reproducer" is not accurate.

Yeah, that was the point :-) I wanted to show that you can restructure the code so that it works. I don't disagree with you that it previously only worked by accident.

**Comment by manovotn** [comment]
> In my opinion, it does not make any sense to keep the request context active while destroying it. It could lead to other unexpected problems, such as, you can create new request scoped beans when the context is destroyed.

I agree, this makes sense to me as well.
Also, due to context propagation, you want to make sure a context appears inactive while you destroy its beans.

> Yes, this is a bit weird and should IMO be the other way around. But in practice, it's not that important because we never deactivate @ApplicationScoped and @Singleton, and request context has the concept of invalidation so deactive() is more less superfluous.

The ordering here seems intentional because of req. context and its propagation mechanic - if you just attempt to `deactivate()` req. context, you will simply remove its `CurrentContext` which means a subsequent `destroy()` would then do nothing.

**Comment by mkouba** [comment]
Ok, so I guess that we agree that it works as intented and the issue should be closed.

If anyone has more questions/comments feel free to reopen the issue.
