### ISSUE TITLE
System properties config overrides in tests does not seem to take effect properly in quarkus 3.14.1

### ISSUE THREAD

**Issue by manofthepeace** [quarkusio/quarkus#42844]
### Describe the bug

I have a test that fails when I set `user.timezone` to UTC I expect the config to have user.timezone to have UTC, this has worked for as long as this test is in, probably around quarkus 2.3, and now fails with quarkus 3.14

### Expected behavior

test should pass and config should return UTC

### Actual behavior

does not return UTC

### How to Reproduce?

Reproducer: https://github.com/manofthepeace/quarkus-test-overrides

Step to reproduce;
1- run the test, it will fail
2- change the quarkus version in the pom to 3.13.3
3- rerun the test, it will pass.

### Output of `uname -a` or `ver`

Darwin Kernel Version 21.6.0

### Output of `java -version`

openjdk version "21.0.4" 2024-07-16 LTS

### Quarkus version or git rev

3.14.1

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

mvn 3.9.9

### Additional information

in the pom file added the following on top the the provided one by the code start;
`<jvm.args>-Duser.timezone=UTC</jvm.args>`

**Comment by gsmet** [comment]
To be precise: this is about somehow overriding the `user.timezone` system property using a test profile.

```
@QuarkusTest
@TestProfile(GreetingResourceTest.TestProfile.class)
class GreetingResourceTest {

    public static class TestProfile implements QuarkusTestProfile {
        @Override
        public Map<String, String> getConfigOverrides() {
            Map<String, String> properties = new HashMap<String, String>();
            properties.put("user.timezone", "UTC");
            return properties;
        }
    }

    @Test
    void testTz() {
        Config config = ConfigProvider.getConfig();
        SmallRyeConfig smallRyeConfig = config.unwrap(SmallRyeConfig.class);
        var configSource = smallRyeConfig.getConfigSource("SysPropConfigSource");
        var prop = configSource.get().getProperties().get("user.timezone");
        assertThat(prop, is("UTC"));
    }

}
```

I will let @radcortez answer but I wonder if it worked like that by accident and because of an implementation details.

**Comment by fredericBregier** [comment]
Just a side note: I observed the same thing.

I have multiple Profiles, each one setting different values using `getConfigOverrides`. Multiple tests are using various profiles and during the test run Maven is combining all tests using the same profile as expected.

Using 3.13.3 is OK, each group of tests are getting the right values from the associated profile.

But changing to 3.14.1 gives an error in very similar conditions of this issue where the first group is ok, then the second one is KO, since it seems the profile values are simply ignored (a log confirm in the profile confirms the correct values, but the test then is getting the value from the previous profile, not the current one).

This is obviously blocking for test purposes and we cannot therefore upgrade to 3.14.1 yet.

**Comment by gsmet** [comment]
@fredericBregier but you were using system properties or it's about plain config?

**Comment by gsmet** [comment]
@fredericBregier could you try to prepare a small reproducer? I'm surprised our test suite didn't catch it so we might miss something in there.

**Comment by fredericBregier** [comment]
I'll try. Not so easy since code is heavy. But I try to extract the idea

**Comment by radcortez** [comment]
This is caused by https://github.com/quarkusio/quarkus/pull/41957.

The problem is that we should never rely on mutating a source for the same `Config` instance because this causes issues where different pieces of the code see different configurations.

Also, some related discussions:
https://github.com/quarkusio/quarkus/pull/42106#issuecomment-2250045346

Let me see what I can do.

**Comment by gsmet** [comment]
@fredericBregier maybe just post an extract of what you do in your profile? I would like to make sure you are doing something similar to the OP.

**Comment by fredericBregier** [comment]
Here is the Common part of all Profiles:

```
package xxx.test.resource;

import java.util.HashMap;
import java.util.Map;

import io.quarkus.test.junit.QuarkusTestProfile;
import org.jboss.logging.Logger;

public abstract class CommonProfile implements QuarkusTestProfile {
  public static final String FALSE = "false";
  private static final Logger LOGGER = Logger.getLogger(CommonProfile.class);

  private static Map<String, String> getDefaultConfigOverrides() {
    return Map.of(ResourcesConstants.QUARKUS_DEVSERVICES_ENABLED, FALSE,
        ResourcesConstants.QUARKUS_HIBERNATE_ORM_ENABLED, FALSE, ResourcesConstants.CCS_DB_TYPE,
        ResourcesConstants.MONGO);
  }

  @Override
  public Map<String, String> getConfigOverrides() {
    return getDefaultConfigOverrides();
  }

  public Map<String, String> getConfigOverrides(final Map<String, String> override) {
    Map<String, String> map = new HashMap<>();
    map.putAll(getDefaultConfigOverrides());
    map.putAll(override);
    LOGGER.infof("Config: %s", map);
    return map;
  }

  @Override
  public boolean disableGlobalTestResources() {
    return true;
  }
}

```

And two particular profiles (all are using the same logic):
- The difference is in the CCS_DB_TYPE which is either Mongo (default) or Postgre


```
import java.util.Map;

import io.clonecloudstore.test.resource.CommonProfile;
import io.clonecloudstore.test.resource.ResourcesConstants;

public class NoMongoDbProfile extends CommonProfile {
  @Override
  public String getConfigProfile() {
    return "test-no-mongo";
  }

  @Override
  public Map<String, String> getConfigOverrides() {
    return getConfigOverrides(Map.of(ResourcesConstants.QUARKUS_DEVSERVICES_ENABLED, "false",
        ResourcesConstants.QUARKUS_HIBERNATE_ORM_ENABLED, "false", ResourcesConstants.CCS_DB_TYPE,
        ResourcesConstants.MONGO));
  }
}

```

```
import java.util.Map;

import io.clonecloudstore.test.resource.CommonProfile;
import io.clonecloudstore.test.resource.ResourcesConstants;

public class NoPostgreDbProfile extends CommonProfile {
  @Override
  public String getConfigProfile() {
    return "test-no-postgre";
  }

  @Override
  public Map<String, String> getConfigOverrides() {
    return getConfigOverrides(Map.of(ResourcesConstants.QUARKUS_DEVSERVICES_ENABLED, "false",
        ResourcesConstants.QUARKUS_HIBERNATE_ORM_ENABLED, "false", ResourcesConstants.CCS_DB_TYPE,
        ResourcesConstants.POSTGRE));
  }
}

```

Of course, similar profiles exist with Mongo or Postgre active with associated TestContainer started as of:

```
public class PostgresProfile extends CommonProfile {
  @Override
  public String getConfigProfile() {
    return "test-db-postgre";
  }

  @Override
  public Map<String, String> getConfigOverrides() {
    return getConfigOverrides(Map.of(ResourcesConstants.QUARKUS_DEVSERVICES_ENABLED, "false",
        ResourcesConstants.QUARKUS_HIBERNATE_ORM_ENABLED, "true", ResourcesConstants.CCS_DB_TYPE,
        ResourcesConstants.POSTGRE));
  }

  @Override
  public List<TestResourceEntry> testResources() {
    return Collections.singletonList(new TestResourceEntry(PostgresResource.class));
  }
}
```

**Comment by fredericBregier** [comment]
For the moment, "simple" configuration is working on 3.13.3 and 3.14.1, but my configuration (more complex with TestContainers) is not working in 3.14.1 while OK with 3.13.3

**Comment by radcortez** [comment]
@gsmet I think the best course of action is to revert https://github.com/quarkusio/quarkus/pull/41957.

I preferred to deal with quarkus port mutating the system properties separately, but this has to be done in a single PR. Or, at the very least, do the port change first and then this one.

**Comment by radcortez** [comment]
To further explain things:

The "working" implementation not only had issue #/27996 but also prevented the test config overrides from overriding sources higher than system properties (since the overrides were being written there). 

The idea behind the new implementation was to create a new temporary source per test to avoid leaking and set it up as a very high ordinal source (to override everything). Unfortunately, this caused issues with https://github.com/quarkusio/quarkus/pull/34135, and I thought I could just get away with not overriding the system properties in the first place. Obviously, this was not a good idea now, since users may have things set at system properties that require tests override (and we don't have such test case).

On another note, and about @manofthepeace reproducer, do not expect to pick up test config overrides on system properties, or any other for that matter, because we want to remove that behavior:
https://quarkusio.zulipchat.com/#narrow/stream/187038-dev/topic/Remove.20mutable.20system.20properties.3F

**Comment by radcortez** [comment]
Sorry. I may not have been totally clear.

The config override is not going to change. Config overrides by `@TestProfile` mutate `System` properties, and this creates a few issues:

- Because `System` is global and we are mutating, we must be extremely careful to restore the properties before and after each test. This is very error-prone and doesn't scale on parallel tests.
-If you have a higher ordinal source than `System` and set properties there, `@TestProfile` cannot override those, and it should. Again, we put things in `System`, so there is no override if you have something higher than that.

Returning to your reproducer, you are checking the overridden update in `SysPropConfigSource,` which works because of what is described above, but we want to remove that. The override would still work, but it would not necessarily be done in `System`. You would be able to just query `SmallRyeConfig#getValue` and get the overridden value.
