### ISSUE TITLE
Store Quarkus version in native executable

### ISSUE THREAD

**Issue by jmesnil** [quarkusio/quarkus#43020]
### Description

I'm working on an [OpenShift enhancement](https://github.com/openshift/enhancements/pull/1584) to detect workload runtimes and Quarkus is a runtime that we are targeting.

When the container runs a Java-based of Quarkus, I can detect its version (from the jar manifest).
However in native mode (from GraalVM), I don't have access to the info. I'm looking at the strings in the `elf` executable, I can see that it's coming from GraalVM and using Quarkus but the version info is lost.
Could it be possible to keep the version of Quarkus somewhere in the executable?

**Comment by geoand** [comment]
I think we had discussed something like in the past, right @zakkak?

Does GraalVM allows us to add/change information in the executable?

**Comment by maxandersen** [comment]
@cescoffier mentioned he looked at it and shuold be way to do it.

would be nice if minor and feasible to enable in LTS.

**Comment by cescoffier** [comment]
My idea was just to add a String constant that we could extract when reading the symbols.

**Comment by zakkak** [comment]
> I think we had discussed something like in the past, right @zakkak?

I don't recall discussing it, but is definitely doable.

> My idea was just to add a String constant that we could extract when reading the symbols.

Yup, that should work. I will prepare a PR.

> I'm looking at the strings in the elf executable, I can see that it's coming from GraalVM and using Quarkus but the version info is lost.

FTR the version is actually present but you are right in that there is no good way to get it (if you don't know the version already), e.g.:

```
$ strings target/cli-1.0.0-SNAPSHOT-runner | grep -F '3.14.2'
3.14.2
```

For Mandrel/GraalVM we can do:

```
$ strings target/cli-1.0.0-SNAPSHOT-runner | grep -F 'com.oracle.svm.core.VM='
com.oracle.svm.core.VM=Mandrel-23.1.4.0-Final
```

so we can do something similar for Quarkus as @cescoffier suggests.

[Here](https://github.com/oracle/graal/blob/9fa5f685c7d2dbde0f46dcd0814b7db9ad8fa8c7/substratevm/src/com.oracle.svm.hosted/src/com/oracle/svm/hosted/VMFeature.java#L94-L96) is how GraalVM does it. The problem is that `CGlobalDataFeature` is not public API so we shouldn't use it. A `static final String` should have the same result (but it's worth keeping in mind that it might stop working someday if the analysis decides that the field is not reachable at some point).

**Comment by gsmet** [comment]
In Quarkus 3.14.3+, you will be able to find a symbol containing `__quarkus_analytics__quarkus.version=the version`.

As reported by @zakkak :

```
❯ strings integration-tests/picocli-native/target/quarkus-integration-test-picocli-native-999-SNAPSHOT-runner | grep -F 'quarkus.version'
__quarkus_analytics__quarkus.version=999-SNAPSHOT
```

**Comment by jmesnil** [comment]
@gsmet Great, that'll be very helpful. Thanks!
