### ISSUE TITLE
Maven compilation failure - Unable to find javadoc for config item... (io.smallrye.config.ConfigMapping)

### ISSUE THREAD

**Issue by IvanPuntev** [quarkusio/quarkus#43117]
### Describe the bug

I'm no longer able to compile my project  after updating to quarkus 3.14.1
After executing command   mvn clean compile  I get the following message: 

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.13.0:compile (default-compile) on project integration-common: Compilation failure: Unable to find javadoc for config item.....

The problematic classes are the ones using - io.smallrye.config.ConfigMapping

I also have this property set to true <maven.javadoc.skip>true</maven.javadoc.skip>

### How to Reproduce?

1. Update to 3.14.1
2. Use  io.smallrye.config.ConfigMapping somewhere in the code
3. Run mvn clean compile

### Quarkus version or git rev

3.14.1 +

**Comment by gsmet** [comment]
Is your project an extension?

Are you using the `quarkus-extension-processor`? Because you should only use it for extensions. Except if you want to document your config but in this case you need to provide Javadoc for your config properties.

If it's actually an extension and you want to disable the doc feature, you can pass `-AgenerateDoc=false` as a compiler argument.

See the guidance here on how to add a compiler argument: https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.14#getting-your-application-to-compile

In any case, I'm interested in your feedback on what you're doing exactly. Thanks!

**Comment by IvanPuntev** [comment]
@gsmet My project is indeed an extension and I'm also using the quarkus-extension-processor.

**Comment by IvanPuntev** [comment]
I also didn't knew there are migration guides... so thanks.

**Comment by IvanPuntev** [comment]
Closing the issue.
