### ISSUE TITLE
Documentation is not rendering the VSCode icon

### ISSUE THREAD

**Issue by mcruzdev** [quarkusio/quarkus#43113]
### Describe the bug

<img width="1022" alt="image" src="https://github.com/user-attachments/assets/d1c78f56-ce78-4fa6-8d36-e2f66747b3e8">

The simple icon [removed the Microsoft brands](https://github.com/simple-icons/simple-icons/pull/10019).

### Expected behavior

Show Visual Studio Code icon

**Comment by rolfedh** [comment]
Hi @mcruzdev, Thank you for highlighting simple-icons' removal of the Visual Studio icon in [#10019](https://github.com/simple-icons/simple-icons/pull/10019) due to Microsoft's permission requirements. 
Your PR, https://github.com/quarkusio/quarkus/pull/43112, adds a similar icon to the quarkus repo. 
Do we have permission to use this icon?

**Comment by mcruzdev** [comment]
I think we can use in our website, the problem is host the icon. But we need to read the Microsoft rules 😄
