### ISSUE TITLE
quarkus.datasource.db-version does not work

### ISSUE THREAD

**Issue by shawkins** [quarkusio/quarkus#43216]
### Describe the bug

Attempting to override the h2 version after the upgrade to Quarkus 3.14.2 results in an error mentioning that quarkus.datasource.db-version can be used. However when that is set, the error remains.

### Expected behavior

quarkus.datasource.db-version should be honored.

### Actual behavior

quarkus.datasource.db-version is not honored. I can see that the appropriate build time value is captured, but the check is always performed against https://github.com/quarkusio/quarkus/blob/e1577e6f462b325ca050f6326b5cb7fffab91b10/extensions/hibernate-orm/runtime/src/main/java/io/quarkus/hibernate/orm/runtime/service/QuarkusRuntimeInitDialectFactoryInitiator.java#L28 which results in an error.

### How to Reproduce?

Try to downgrade h2 on quarkus 3.14.2 to a 2.2.x release.

### Quarkus version or git rev

3.14.2

**Comment by shawkins** [comment]
Tried to reproduce in just quarkus against 3.14.2 and the property worked as expected, so this is actually a keycloak issue.

**Comment by shawkins** [comment]
@mabartos @vmuzikar this issue is being caused by having the default-persistence.xml - we hit https://github.com/quarkusio/quarkus/blob/155093dbe854e4fa69c6878f1cee32a0426abf81/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1209 rather than https://github.com/quarkusio/quarkus/blob/155093dbe854e4fa69c6878f1cee32a0426abf81/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L1192 which would propogate the setting as needed. 

@yrodiere is there a workaround for this? Are values in the default-persistence.xml interpolated against the smallrye configuration such that we could add the mapping from quarkus.datasource.db-version to the jakarta property ourselves?

We also still have an active issue on moving away from using persistence.xml both internally and for customizations.

**Comment by yrodiere** [comment]
> this issue is being caused by having the `default-persistence.xml`

That's indeed a problem. From [the docs](https://quarkus.io/guides/hibernate-orm#persistence-xml):

> If you use a `persistence.xml`, then you cannot use the `quarkus.hibernate-orm.*` properties and only persistence units defined in `persistence.xml` will be taken into account.

----

> Are values in the default-persistence.xml interpolated against the smallrye configuration such that we could add the mapping from quarkus.datasource.db-version to the jakarta property ourselves? - I believe the concensus from https://github.com/keycloak/keycloak/issues/25384 was that env property references were not supported.

They are not.

`persistence.xml` completely short-circuits the Quarkus configuration infrastructure. So you only get what plain Hibernate ORM would provide, which indeed does not include env property references.

----

> @yrodiere is there a workaround for this?
 
Looking at the code, you can try to set the H2 version through configuration property `jakarta.persistence.database-product-version` in `persistence.xml`; I think this might just work, though I'm not entirely sure.

If you cannot hardcode it -- but for your investigation, surely you can? -- you can try setting it as a system property... Hibernate ORM might possibly pick it up, though I'm not certain.

**IMPORTANT**: This is **only** something you should do in the context of **investigations**. Overriding the version of H2 in Quarkus is completely untested and unsupported, because part of the H2 integration in Quarkus is tied to its internal code (in particular for native image). Changing the version of H2 may result in various unpredictable failures.
This is true for basically any dependency defined in the Quarkus BOM, by the way.

----


> We also still have an active issue (https://github.com/keycloak/keycloak/issues/27320) on moving away from using persistence.xml both internally and for customizations.

That would indeed spare you a lot of trouble. Beside these limitations, there are very few tests in Quarkus involving `persistence.xml`, so there are likely other problems we haven't (yet) encountered.

**Comment by vmuzikar** [comment]
I'd still argue that `quarkus.datasource.db-version` doesn't work with `persistence.xml` is a bug. The [docs say](https://quarkus.io/guides/hibernate-orm#persistence-xml) that only `quarkus.hibernate-orm.*` options will be ignored.

**Comment by yrodiere** [comment]
> Okay, I'll update the docs

Done here: https://github.com/quarkusio/quarkus/pull/43240

I also tested that setting `jakarta.persistence.database-product-version` in `persistence.xml` will indeed work as expected. Though, as mentioned previously, this file does not support dynamic content (no `${myvar}`, no references to environment variables). It's plain JPA, not Quarkus config.

**Comment by shawkins** [comment]
Thanks for the follow up @yrodiere It looks like we won't need to use the workaround as h2 version 2.3.230 does not seem to exhibit the same problem.

**Comment by gsmet** [comment]
@shawkins do you think we should downgrade H2 for 3.15.0?

**Comment by shawkins** [comment]
> @shawkins do you think we should downgrade H2 for 3.15.0?

Probably. I'll open an upstream issue in H2. They should be able to confirm what is happening with 2.3.232.
