### ISSUE TITLE
Quarkus 3.14.3 - Security [SecurityIdentityAugmentor] - reactive - ContextNotActiveException

### ISSUE THREAD

**Issue by DudekJakub** [quarkusio/quarkus#43267]
### Describe the bug

Hello everyone.

Working with quarkus 3.14.3

I'm trying to implement my custom Augmentor as it is shown in this discussion:
[Zulip Chat Discussion](https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Quarkus.20Security.20.5BSecurityIdentityAugmentor.5D.20-.20reactive)

I'm talking there with **Sergey Beryozkin** and **Michal Vavrik**. 

Please check it for details. 

### How to Reproduce?

Everything is included in README file.

Kotlin reproducer version: [Kotlin-Security-Identity-Reproducer](https://github.com/DudekJakub/security-identity-reproducer)

Java reproducer version: [Java-Security-Identity-Reproducer](https://github.com/DudekJakub/security-identity-reproducer-java)

**Comment by geoand** [comment]
Also cc @michalvavrik

**Comment by michalvavrik** [comment]
> You added a link to a Zulip discussion, please make sure the description of the issue is comprehensive and doesn't require accessing Zulip
> 
> This message is automatically generated by a bot.

I think the issue description is alright, we requested this issue so that effort is tracked, but no need for c&p from Zulip everything. Thanks

**Comment by michalvavrik** [comment]
This is `quarkus-amazon-services`, they are executing this request  in a way they IMO shouldn't. You need to make sure that you continue on the same event loop as CDI context is attached to the Vert.x context dispatched for HTTP request.

- you need to use correct context, checkout https://quarkus.io/guides/duplicated-context#context-and-duplicated-context for docs if you need to

You need to make sure you emit request that runs this Amazon extension code on right context like this:

```
    @Override
    public Uni<SecurityIdentity> augment(SecurityIdentity identity, AuthenticationRequestContext context) {
        var vertxCtx = Vertx.currentContext();
        return testService.getUser()
            .emitOn(runnable -> vertxCtx.runOnContext(unused -> runnable.run()))
            .map(user -> {
```

You see what I did?  Just use `vertxCtx`. Use variant A because that one is correct. Activation of CDI request context that you do on `security.utils.TestService#getUser` is unnecessary and I suggest that you drop it unless you actually need it.

I have pushed working version here https://github.com/DudekJakub/security-identity-reproducer-java/compare/master...michalvavrik:security-identity-reproducer-java:master just in case you run into issues so that you can check it out. But you can ignore basically everything but this part that `emits`.

Cheers and have a good weekend @DudekJakub 

Closing as not _our_ bug. Please let this Quarkiverse extension know that they should investigate executors they use.

**Comment by sberyozkin** [comment]
Excellent, thanks fot the expert support here, @michalvavrik, it may be worth capturing it in a note for the security cusmization doc

Enjoy the weekend

**Comment by michalvavrik** [comment]
> it may be worth capturing it in a note for the security cusmization doc

Definitely, to give users as much info as possible. The thing is, this is not reproducable without that extension, but I didn't continue looking why, I just check that shared executor they used and figured that what I need is augmentation to continue on the same event loop context as the augmentation started. So, I am just not sure how to document it.

If I had to guess, this is issue in  `quarkus-amazon-services` not invoking the continuation in the proper context and normal users don't need to do that, because most clients just do that OOTB. But I assure you I am not an expert here :-)

**Comment by DudekJakub** [comment]
Thank you guys a lot. I will take a look at your solution @michalvavrik on monday. 

Cheers and good weekend to you too. :)
