### ISSUE TITLE
Quarkus Spring Data documentation should document newly supported interfaces and update existing examples

### ISSUE THREAD

**Issue by michalvavrik** [quarkusio/quarkus#43391]
### Describe the bug

Following https://github.com/quarkusio/quarkus/pull/40344

- 2 new interfaces are supported: `ListCrudRepository` and `ListPagingAndSortingRepository`. This has been mentioned in the migration guide https://github.com/quarkusio/quarkus/wiki/Migration-Guide-3.12#spring-compatibility-layer-aligned-with-spring-boot-3 but is completely omitted from https://quarkus.io/guides/spring-data-jpa#what-is-supported
  - IIUC this is a important because only supported features are those explicitly listed in documentation (AKA only support Spring features docs mentions, no others)
- I wonder whether examples should be updated as well. For example https://quarkus.io/guides/spring-data-rest#exposing-many-entities says `Replace the CrudRepository with PagingAndSortingRepository in the FruitsRepository` but won't this mean that previously explained operations https://quarkus.io/guides/spring-data-rest#define-the-repository like `given()
                .when().delete("/fruits/1")
                .then()
                .statusCode(204);` will stop working? I think you cannot just remove `CrudRepository`.

**Comment by aureamunoz** [comment]
Yes, absolutely, the guide needs to be aligned with the upgrade. The example [have been already aligned](https://github.com/quarkusio/quarkus-quickstarts/blob/e0ff62e3f56572c463104f5cf95e79af5ae4ae9c/spring-data-rest-quickstart/src/main/java/org/acme/spring/data/rest/FruitsRepository.java#L5) and is using the JpaRepository in order to have operation from both, CrudRepository and PageAndSortingRepository.

**Comment by geoand** [comment]
@aureamunoz do you plan to update the docs?

**Comment by aureamunoz** [comment]
Yes! I plan working on that asap. Later this week.
