### ISSUE TITLE
Keycloak devservice restarts with every update in devmode

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#43701]
### Describe the bug

We have just had Keycloak devservice moved into its own extension, and on `main`, it restarts even if none of its properties have changed. and the demo does not like that.
We probably need do manual property comparison now after Keycloak `DevServicesConfig` got migrated to `ConfigMapping` to have a finer grained control of the process  

### How to Reproduce?

Start for exampe `quarkus-quickstarts/security-openid-connect-quickstart`, note Keycloak has started. Change the code, see Keycloak loading again

**Comment by sberyozkin** [comment]
Hmm, let me close this one for now until I figure out what is going on

**Comment by sberyozkin** [comment]
Sorry for the noise, the reproducing sequence suggested above needs to be followed from a test call from OIDc Dev UI which causes Keycloak reload as well

**Comment by michalvavrik** [comment]
> Sorry for the noise, the reproducing sequence suggested above needs to be followed with a test call from OIDc Dev UI which causes Keycloak reload as well

I can reproduce it with 999-SNAPSHOT and I cannot reproduce it with 3.15.1. I checked and the issues is in the config mapping equals method.

> I think this needs to be prioritized as it will be quite painful for our users if I understood the problem correctly.

Cause of the issue is that `@ConfigMapping` doesn't have correctly implemented `equals` method. I can provide hotfix if we are in hurry (though we should have a time till 3.16 is released, right?).

Hello @radcortez , I read https://smallrye.io/smallrye-config/Main/config/mappings/#tostring-equals-hashcode and it says that `equals` method should be provided automatically. However it doesn't seem to be true. Or I read it wrong?

1. Here we have config mapping https://github.com/quarkusio/quarkus/blob/main/extensions/devservices/keycloak/src/main/java/io/quarkus/devservices/keycloak/KeycloakDevServicesConfig.java

2. We keep it between restarts and I can see it in the static volatile variable that previous config is kept, I also can see that values seem same between restarts

3. This equals returns false https://github.com/quarkusio/quarkus/blob/b779ee9aa7ef41b559e1954da3b52b52d511c071/extensions/devservices/keycloak/src/main/java/io/quarkus/devservices/keycloak/KeycloakDevServicesProcessor.java#L167

My question is, do I need to write equals myself to compare all the `@ConfigMapping` methods? I don't mind, but I'd suggest to tweak docs a bit, because it confuses me.

If you want to reproduce it, you run `quarkus-quickstarts/security-openid-connect-quickstart`, change any code (I for example added a new endpoint that I later called) and make a call to app (like with `curl`).

**Comment by michalvavrik** [comment]
I have found this test in the SmallRye Config https://github.com/smallrye/smallrye-config/blob/main/implementation/src/test/java/io/smallrye/config/ConfigMappingEqualsTest.java which tells me that my expectations are right. Maybe it's a bug? Please check @radcortez and if you think you cannot prioritize it, I'll provide workaround. Thanks

**Comment by michalvavrik** [comment]
Aaah, sorry for the fuss @radcortez , I found it. The issue is that https://github.com/quarkusio/quarkus/blob/main/core/runtime/src/main/java/io/quarkus/runtime/configuration/MemorySize.java doesn't have implemented equals method. This was added in this version https://github.com/quarkusio/quarkus/pull/43601 which is the reason why @sberyozkin cannot reproduce it with released version. There is no issue with the `@ConfigMapping`.

**Comment by michalvavrik** [comment]
I have opened https://github.com/quarkusio/quarkus/pull/43791, didn't write automated test though.

**Comment by sberyozkin** [comment]
Thanks @michalvavrik 👍
