### ISSUE TITLE
@PostConstruct method is not being called before other methods

### ISSUE THREAD

**Issue by dhoffer** [quarkusio/quarkus#43751]
### Describe the bug

Hi, we are upgrading a Quarkus 2.16.12 app to 3.15.1.  One problem we having is that the @PostConstruct method is not being called at all but the instance is put into service in an incomplete state as the @PostConstruct method is never called.  Did something change in Quarkus regarding how/when @PostConstruct works?

Note this seems to be the case for several beans we have configured for early startup e.g. 

`
@Unremovable
@Singleton
@Startup(1)
`
And in one case the class implements CredentialsProvider.

### Expected behavior

The @PostConstruct method should be called after injection is complete and before any methods are called.

### Actual behavior

The @PostConstruct method never gets called.

### Output of `java -version`

java 21.0.4 2024-07-16 LTS

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)

### Additional information

OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

**Comment by mkouba** [comment]
> But why does it even build if that is gone and replaced with jakarta.annotation.PostConstruct; ?

Most probably because you have the old `javax.annotation` artifact on the class path? I think that it's a dependency of some Maven resolver stuff (among other things).

We do have a check for some other common mistakes (including `@javax.inject.Inject` and `@javax.inject.Singleton`) but we don't have one for `@javax.annotation.PostConstruct`. And honestly I don't think we will be able to cover all similar use cases.

@manovotn @Ladicek Do you think it would make sense to add a check whether a class-based bean contains `javax.annotation.PostConstruct`/`javax.annotation.PreDestroy` in the `WrongAnnotationUsageProcessor#detect()` build step?

**Comment by Ladicek** [comment]
If that's easy to do, I'd add it.

**Comment by mkouba** [comment]
> If that's easy to do, I'd add it.

This is the simplest way where we fail the build if an application class contains a "wrong" annotation: https://github.com/quarkusio/quarkus/pull/43761/files#diff-975b33ab22c8fee9c639dd91ed9b6780f25addf4519677c7072c2ee5ccab7394R56-R58
