### ISSUE TITLE
@Overridable does not play well with @Record

### ISSUE THREAD

**Issue by gnodet** [quarkusio/quarkus#4479]
This may be a design decision, but when using `@Overridable` with `@Record`, we end up with an exception because there are multiple instances of a `SimpleBuildItem` and an exception is thrown.

**Comment by gsmet** [comment]
@dmlloyd ^

**Comment by dmlloyd** [comment]
Can you give an example?  Where are you putting the `@Overridable` annotation?

**Comment by gnodet** [comment]
See https://github.com/gnodet/quarkus-conditional-buildstep/tree/pb-overridable-record where the last commit makes the project fail when building.
See https://github.com/gnodet/quarkus-conditional-buildstep/commit/19675cbea0cc5ae1900cfea49efe0d1d474e2ea9

**Comment by dmlloyd** [comment]
Ah I see.  So the problem is that you're producing two things from your build step: one which is overridable, and one (the implicit generated bytecode) which is not.  You *should* be able to solve the problem by specifying `@Record(optional=true)`.  This should prevent the generated bytecode from being supplied unless the overridable item ends up being consumed.

**Comment by dmlloyd** [comment]
BTW that should be specified on both `@Record` annotations.

**Comment by dmlloyd** [comment]
Ignore stalebot.

I think the real issue here is a doc issue.  The recorder needs to be optional when producing overridable build items, and the docs should be enhanced accordingly.

**Comment by geoand** [comment]
Is this still an issue?

**Comment by geoand** [comment]
Closing for lack of feeback
