### ISSUE TITLE
Qute setLocale dynamically is not effective

### ISSUE THREAD

**Issue by boris-krassi** [quarkusio/quarkus#44803]
### Describe the bug

I use Qute templating with MessageBundle for localization. I am trying to set the locale dynamically, but this is not effective. However, I use `@Localized` annotation or `quarkus.default-locale` in `application.properties`, then it works fine.

Resource
```
@Path("/hello")
public class GreetingResource {

    @Inject
    Template hello;

    @Inject
    //@Localized("fi")
    CountryMessages translation;

    @GET
    @Path("")
    @Produces({MediaType.TEXT_HTML})
    public Response hello() {
        return Response.ok()
            .entity(
                hello.data("countries", translation).setLocale("fi").render())
            .type(MediaType.TEXT_HTML)
            .build();
    }
}
```

Template
```
<!DOCTYPE html>
<html>
<head>
    <title>Hello Qute</title>
</head>
<body>
<h1>Hello {countries.country}!</h1>
</body>
</html>
```

Interface for MessageBundle
```
@MessageBundle(value = "country")
public interface CountryMessages {
    String country();
}
```

messages/country.properties
```
country=England
```

messages/country_fi.properties
```
country=Finland
```

### Expected behavior

When setting setLocale("fi") it should print **Hello Finland!**

### Actual behavior

Prints **Hello England!**

### How to Reproduce?

I have produced this from standard REST Hello World
[source.zip](https://github.com/user-attachments/files/17947975/source.zip)

### Output of `java -version`

OpenJDK 64-Bit Temurin-21

### Quarkus version or git rev

3.15.2

### Build tool (ie. output of `mvnw --version` or `gradlew --version`)

maven 3.9.9

### Additional information

I also tried to setAttribute and older Quarkus versions 3.6 and 3.7

**Comment by mkouba** [comment]
This is not how it's supposed to work. 

If you need to obtain a localized message in a template then a _message bundle expression_ should be used, i.e. the message bundle name is used as a namespace followed by the message key. In your example the message bundle expression would look like: `{country:country}`, because of `@MessageBundle(value = "country")` and the key is defaulted from the method name. It might make more sense to use something like `@MessageBundle(value = "cm")` so that  the expr is `{cm:country}`.

If you inject a message bundle interface then a specific localization is injected, hence the `@Localized` qualifier. The injected interface has not way to reflect a `TemplateInstance` attribute.

**Comment by boris-krassi** [comment]
@mkouba many thanks for the fast answer! Now the difference between injecting a specific localization and dynamic localization is clear.

To help other developers, this works correctly:
```
@Path("/hello")
public class GreetingResource {

    @Inject
    Template hello;

    @GET
    @Path("")
    @Produces({MediaType.TEXT_HTML})
    public Response hello() {
        return Response.ok()
            .entity(
                hello.instance().setLocale("fi").render())
            .type(MediaType.TEXT_HTML)
            .build();
    }
}
```
and in the template:
```
<!DOCTYPE html>
<html>
<head>
    <title>Hello Qute</title>
</head>
<body>
<h1>Hello {country:country}!</h1>
</body>
</html>
```
And it prints **Hello Finland!**
