### ISSUE TITLE
Use the correct default executor to fire async CDI events

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#4701]
We're currently using `ForkJoinPool.commonPool()`.

@stuartwdouglas @dmlloyd @manovotn WDYT?

**Comment by dmlloyd** [comment]
Seems reasonable.

**Comment by mkouba** [comment]
> Seems reasonable.

Do you think that `ForkJoinPool.commonPool()` is reasonable?

**Comment by dmlloyd** [comment]
No I was responding to the title of the proposal, which is to use a better default executor, which seems reasonable.

I have mixed feelings about the `ForkJoinPool`.  On the one hand, it's largely invisible and just does its work in the background without interfering much (at run time at least).  On the other hand it creates yet more threads that the user has limited control over, and there's also really no way to defeat it.  :man_shrugging: 

I guess we should only use (or allow usage of) the `ForkJoinPool` for things that are actually fork-join or parallel stream based (i.e. user code which uses fork-join or parallel streams).  Our stuff should usually stick to our thread pools.

**Comment by manovotn** [comment]
>  Our stuff should usually stick to our thread pools.

This may be a little basic question, but how do I get hold of those thread pools? I vaguely recall that for MP CP we did this via some build item(`ExecutorBuildItem`?); is that the way to go, or can you grab it by some other means as well?

**Comment by dmlloyd** [comment]
`ExecutorBuildItem` is the way.  I imagine we should have some better CDI integration though, and we probably should be producing a scheduled executor too.

**Comment by mkouba** [comment]
Hm, except that `ExecutorBuildItem` is of course a RUNTIME_INIT construct and ArC is initialized during STATIC_INIT. So we'll probably have to use `ForkJoinPool.commonPool()` and switch to "default" executor at runtime?

**Comment by dmlloyd** [comment]
It depends on what kind of work you're doing I guess.  The challenge with starting threads during native-image static init is that you have to tear them down again before the init can be "done".  The only way to signal that is to delay exit of the static init block until all the work is finished and everything is torn down again (because we can't have threads hanging around or else native-image will get angry).

Maybe we need some real infrastructure around for this purpose?  It's a bit of a challenge because once we start talking about delaying the exit of static init, we start to risk hangs & deadlocks unless we're careful about how such things are organized.

**Comment by mkouba** [comment]
@dmlloyd But using `ForkJoinPool.commonPool()` during STATIC_INIT should be ok, or? TBH I don't think that async CDI events are frequently used and especially not in the integration code (which is mostly the CDI stuff run in STATIC_INIT). In other words, if using `ForkJoinPool.commonPool()` during STATIC_INIT is OK I wouldn't spend more time on this.
