### ISSUE TITLE
How to monitor health of Stream and Kafka connection?

### ISSUE THREAD

**Issue by FreifeldRoyi** [quarkusio/quarkus#4712]
I'm using an Emitter (SmallRye, not MP) to send messages to Kafka, and I want to know if the Stream and Kafka connection are alive and ok, how can I reflect that in the health endpoints? 
For example, If a Stream is closed (due to some uncaught exception), or the Kafka connection is not ready/healthy or closed, what should I add to the health endpoints to monitor that?

Thank you

**Comment by loicmathieu** [comment]
cc @lhauspie wanted to works on an health check for KafkaStream (#4793).

But as I understand, you only use `quarkus-kafka-client` extension.
I'm OK for a readiness check on KafkaStream as it requires some topics to be created. But I'm more concerned by a readiness check on a simple Kafka client because Kafka itself is fault tolerent:

- If I'm a consumer to a Kafka cluster, the consumer will wait for messages wether the broker is up or not so no need to set a readiness probe to down (think of the impact of a readiness probe on kubernetes)
- If I'm a producer to a Kafka cluster, even if the cluster is down the message can still be _send via producer.send()_ as the Kafka Java client will retain them untill the cluster is up and will send them after ...

So I will say OK to implements a KafkaStream readiness check but not OK (or not enabled by default) of a Kafka Client.

Maybe @gunnarmorling or @cescoffier have different opinions :)

**Comment by FreifeldRoyi** [comment]
I'm actually using the `quarkus-smallrye-reactive-messaging-kafka` and not directly using the kafka client.
Everything is reactive once I emit a message. So if the emitting stream is down (due to some exception) or if the kafka (reactive)-stream is down, the service becomes unhealthy.
I guess you're right that it's not an issue with Kafka, but a reactive issue.

**Comment by loicmathieu** [comment]
@FreifeldRoyi we can easily monitor the health of a Kafka cluster, but I'm not confident to put a health check DOWN if a Kafka broker is down because the Java Kafka Producer is resilient and can keep some messages (in memody I think) in a buffer and send them when the cluster is back. The same for a client, it will reconnect to the cluster when back. So if I implements a Kafka Healthcheck I would disabled it by default.

For a reactive-stream, it's more difficult, because it can generates exception in two cases:

- Your code generates an exception. This is your responsibility :)
- The reactive-stream generates an exception, this can of course be due to the cluster down, or some backpressure limits. Not sure we can create an health check for this. Maybe @cescoffier have an idea on this ?

**Comment by FreifeldRoyi** [comment]
Indeed it is my responsibility! But I'd rather let the container orchestrator kill and restart a DOWN instance, emit an alert from my monitoring system and not leave it up and running and hanging.

I already agreed that the code handling kafka behind the scenes is probably doing a good job reconnecting, but it's still a resource that needs to be checked for readiness.. If I can mark the instance as not ready when kafka connection is still not available or down, it might help discovering problem early on.

**Comment by FreifeldRoyi** [comment]
With the new version published, do I have any way to know if a reactive stream is down or not? 
@loicmathieu @cescoffier 

Thnx

**Comment by loicmathieu** [comment]
@FreifeldRoyi which new version? 

KafkaStream health check is targeted for Quarkus 1.1 (released end of month).
There will also be a Kafka health check, also targeted Quarkus 1.1

**Comment by FreifeldRoyi** [comment]
Version 1. But you already said that it will be released in 1.1 but that was the less important part. 
I'm more concerned about the reactive stream part. I would really like to know somehow that the Stream is still live and nothing made it crash.

**Comment by loicmathieu** [comment]
This will be delivered via #5125 that is under review. I hope it will be part of 1.1 but cannot guarantee it.

**Comment by loicmathieu** [comment]
Both Kafka and KafkaStream Health Check has been merged and will be part of 1.1.
Closing this issue.

**Comment by gunnarmorling** [comment]
Excellent, looking forward to seeing this in 1.1!

>
