### ISSUE TITLE
Documentation for quarkus.security.file / embedded not present in any guide

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4796]
While one can find in https://quarkus.io/guides/all-config `quarkus.security.users.file.enabled` / `quarkus.security.users.embedded.enabled` and friends. I could not find it in any security guide. We need the doc.

**Comment by gsmet** [comment]
It's in there: https://quarkus.io/guides/elytron-properties-guide.html

but the issue is that I think it wasn't added to the guide toc when it was first added. It's linked from the main security guide though.

**Comment by emmanuelbernard** [comment]
Right it's linked from here https://quarkus.io/guides/security-guide but it wasn't obvious I could go down.

**Comment by gsmet** [comment]
Yeah, for now, I included the generated ones where they were missing. For some of the guides, there is some more info, intro and so on and including the generated properties was losing information so I let it like that pending a better solution.

But sure, if Sergey can rework that, that would be nice.

**Comment by sberyozkin** [comment]
@gsmet @emmanuelbernard hi, I'm not sure I'll have time to improve beyond what Guillaume already did in time for 0.27.0, traveling back home tomorrow, these modules are new to me, so will need to catch up and I need to try to resolve a couple of  OIDC issues before 0.27.0 :-). If what Guillaume already did can provide an intermediate input then may be we can get it fixed in the next version which follows 0.27.0 ?

**Comment by sberyozkin** [comment]
I'll ping Guillaume a bit later, may be few obvious improvements can indeed be done quickly, I'm not just entirely sure about the scope. Stuart recommends adding TOC :-)

**Comment by FroMage** [comment]
#4760 added the config tables for file/embedded, so I think we're good with it?

**Comment by sberyozkin** [comment]
@FroMage This is nice :-), thanks for your help.
@gsmet, @emmanuelbernard - can this issue be closed now ? Or would you like some more updates ?
