### ISSUE TITLE
Offer page to run tests in live coding mode

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4872]
quarkus:dev could offer a /quarkus/tests page which a way to run all tests or just a single test.
This is no different from an IDE run except we would benefit from and already loaded Quarkus (possibly). 

A good use case is to appease test driven design people that feel like live coding is dangerous.

**Comment by loicmathieu** [comment]
Or we can have a quarkus:test that will launch the test suite and relaunch them each time a class changes. 
This is how a lot of JS framework do ...

**Comment by machi1990** [comment]
> Or we can have a quarkus:test that will launch the test suite and relaunch them each time a class changes.
> This is how a lot of JS framework do ...

I like the idea.  Or `mvn clean test -Dwatch` ?

**Comment by stuartwdouglas** [comment]
This links in with my 'developer console' idea, which is a local in browser developer tooling that can do things like this.

**Comment by gastaldi** [comment]
https://infinitest.github.io/ is a good plugin that does a similar job

**Comment by sdaschner** [comment]
How about adding both a flag (such as `-DhotTests`, `-DcontinuousTests`, `-DwatchTests`, etc.) to the Maven phase, as well as an interactive way, e.g. pressing `<Enter>`, to fire up both surefire & failsafe tests on demand.

The Open Liberty Plugin does it this way, and for me this way runs the tests quicker than in the IDE (due to initialization)

**Comment by stuartwdouglas** [comment]
We have continuous testing now, which has superseded this.
