### ISSUE TITLE
Offer missing extension advice upon Arc UnsatisfiedResolutionException

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#4918]
Here is a typical mistake a user makes: he forgets to add `quarkus-vertx` as a dependency leading to

```
﻿Caused by: javax.enterprise.inject.UnsatisfiedResolutionException: Unsatisfied dependency for type io.vertx.reactivex.core.Vertx and qualifiers [@Default]
	- java member: com.ziphii.promptpay.bulkpay.endpoints.NibssBulkPayService#vertx
	- declared on CLASS bean [types=[com.ziphii.promptpay.bulkpay.endpoints.NibssBulkPayService], qualifiers=[@Default, @Any], target=com.ziphii.promptpay.bulkpay.endpoints.NibssBulkPayService]
	at io.quarkus.arc.processor.Beans.resolveInjectionPoint(Beans.java:472)
	at io.quarkus.arc.processor.BeanInfo.init(BeanInfo.java:402)
	at io.quarkus.arc.processor.BeanDeployment.init(BeanDeployment.java:205)
	... 14 more
```

I propose, that we have a mapping of missing type to extension so that we can throw a meaningful error "Have added the quarkus-vertx extension in your pom.xml or Gradle project?". That would be a good usability improvement

This is not the first time I see people missing dependencies, and the ArC exception is quite intimidating and does not lead to the core of the problem. 

CC @FroMage @mkouba

**Comment by cescoffier** [comment]
Yes, it would definitely improve the devX.

**Comment by Sanne** [comment]
In early days I remember suggesting that rather than having a "runtime" module explicitly chosen, we'd add the respective companion jars automatically after inspecting the dependencies.

I don't remember why exactly we went for the current strategy; probably also related with the reticense of automatically adding dependencies. But maybe now we can evolve in to such direction?

Proposal: 
 - expect people to use our current model
 - when they are using X and X-runtime is missing, we log a warning and add X-runtime automatically

FYI while this might be tricky in Maven it's straight forward in both aether and gradle. Should be easy with the custom tooling we have grown so far too.

**Comment by FroMage** [comment]
Agreed with what @emmanuelbernard is proposing (I would need to think more about @Sanne's proposal). We can build an exhaustive list of produced CDI beans during build, and save it somewhere, and use this for the error messages.

This seems harder for 3rd-party extensions, though.

**Comment by emmanuelbernard** [comment]
@Sanne Yoour proposal would need some serious discussions, in particular since we are moving away from a pure 1-1 between extension and dependencies (I have security and HTTP in mind). In the example I had in mind, it would not have helped as the user did not have vertx in its dependencies, it assumed it was coming from the base HTTP dependency.

**Comment by mkouba** [comment]
Sounds like an interesting idea except that we would have to hardcode the mappings in the core/arc with the current model.

**Comment by emmanuelbernard** [comment]
@mkouba yep but I don't see that as too problematic.

**Comment by gastaldi** [comment]
Perhaps the Maven plugin could generate a mapping file during the build that could be consumed by ArC

**Comment by mkouba** [comment]
@emmanuelbernard hard-coded values on a wrong place usually prove to be problematic.

WRT @Sanne's idea - @kenfinnigan can have some ideas and comments as Thorntail extensions can do some "autodiscovery".

**Comment by kenfinnigan** [comment]
For Thorntail we implemented "auto discovery" by using a meta model for extensions/dependencies to register whichever API packages or configuration files would indicate that the dependency was needed. For example, javax.persistence -> JPA fraction, faces-config.xml -> JSF fraction, etc.

Then the build sucked the meta classes from each extension into the maven plugin for TT so that it had the information available when building user applications.

So it could be used to either auto discover which dependencies were needed if none were in the pom, or in the case to confirm that the correct dependencies are actually present

**Comment by Sanne** [comment]
just to clarify, the idea I posted above is not new and we already discussed it, and I was persuaded that it doesn't give us enough control.

So I'm not resurrecting the topic now to make it the new default; I think the current approach is working just fine. I'm just suggesting that when the extension for a component X is blatantly missing while we detect the X being on classpath, on top of a big far WARN we could also pull in the dependency, but keep the warning and suggest the user to go for the better solution (the status quo).

**Comment by emmanuelbernard** [comment]
Whatever it is, if we have if fast and without a factory heating the universe, I'm happy.

**Comment by emmanuelbernard** [comment]
But to me the maven specific solution is not OK, it has ot be generic. so this metadata collection could be added by extensions into the extension.json/yaml or do we need a separate metadat thing

**Comment by emmanuelbernard** [comment]
CC @maxandersen might need more metadata down the line (post 1.0)

**Comment by barrkel** [comment]
Independent of something as simple as a missing dependency, tools for analyzing UnsatisfiedResolutionException are not great.

I just upgraded from 0.23.2 to 0.27.0 and I'm getting `UnsatisfiedResolutionException` in my tests for `PrincipalProducer` from `smallrye-jwt`, which worked before the version bump. Don't pay too much mind to the specifics of my problem, but rather the tools at my disposal to diagnose it.

Bean resolution occurs at build time, so I can't use the debugger, my best weapon.

I have `quarkus.log.console.level=TRACE` in `application.properties`, but I get no interesting output on bean discovery.

I set `quarkus.log.category."io.quarkus.arc.producer".level=DEBUG` to check if the producer has been eliminated, but get no more output than before. In fact I doubt that I'm getting log messages at all, since surely lots of stuff is being pruned. (I'm using `mvn test` with `quarkus-maven-plugin` to run the tests.)

At this point I'm scratching my head. The DI failure is a black box and I can't see inside it, or crack it open. I can't get it to log interesting output, and I can't inspect what it has in memory when it's in flight.

IMO, any solution to DI debugging should start with something universal, which may be verbose and hard to decipher but can solve all problems, before narrowing in with approaches that give quick solutions to common problems.

**Comment by mkouba** [comment]
@barrkel for the record - `quarkus.log.category."io.quarkus.arc.**processor**".level=DEBUG` in `application.properties` only works for the dev mode. For normal build use `mvn -X` and grep "Unused" or "io.quarkus.arc".

**Comment by barrkel** [comment]
@mkouba FWIW my go-to technique for these kinds of issues is to download the JAR sources, add extra logging or pause points suitable for attaching a debugger, compile and install snapshot version in local repo, rewire dependencies to use my snapshot version, then iterate.

Inscrutable Arc and dev mode startup errors are probably the biggest risk factors before I unleash my spike on the rest of my dev team. The errors today aren't merely inscrutable; sometimes they don't contain enough information to address the problem. There's also no guide, at any level of abstraction, for debugging Arc resolution failures or dev-mode startup errors.

For example I just re-discovered and locally fixed the exception swallowing that's been fixed yesterday in this commit: https://github.com/quarkusio/quarkus/commit/c8c71bf23771fd8fbd3ece27d52dc64efc39bd90

**Comment by mkouba** [comment]
> The errors today aren't merely inscrutable...

Well, ArC is just a dependency injection based on CDI and its errors are very similar to other CDI implementations, ie. Weld. I'm not really sure what you mean with "inscrutable".

> There's also no guide, at any level of abstraction, for debugging Arc resolution failures.

That is true. Quarkus should improve in this area. Contributions are welcome! ;-)

**Comment by manovotn** [comment]
I think a lot of problems discussed here are now offset by users being able to start coding from archetypes (quickstarts for instance) that bring in the dependencies for them.
On top of that, there is now a sizeable chunk of information provided in SO, Zulip chats and GH issues/discussions that are google-able with some effort and can provide guidance in a lot of cases.

I also agree that hardcoded mappings ([mentioned above](https://github.com/quarkusio/quarkus/issues/4918#issuecomment-546864893)) are not a great idea as they are error prone with time as the code changes but the mappings might get stale. Not to mention there is so many extensions (quarkiverse included) that we can hardly provide a truly reliable advice from that alone.

Since this issue has now been stale for over two years with no progress I'm closing it. However, feel free to reopen and continue the discussion if you disagree.
