### ISSUE TITLE
Quarkus Environment

### ISSUE THREAD

**Issue by NetoDevel** [quarkusio/quarkus#4929]
**Quarkus Environment**

Do we have any way of indicating in which environment we are running our application?

**Configuration suggestion**
```properties
quarkus.profiles.active=dev
```

**Additional context**
get environment programmatically

```java
@Inject
Enviroment environment;
environment.getActiveProfiles()
```

**Comment by machi1990** [comment]
Hi, right now it is possible to do so using the `-Dquarkus.profile` system property or `QUARKUS_PROFILE` environment variable. 

And to retrieve the current profile programmatically you can do `ProfileManager.getActiveProfile()`.

**Comment by NetoDevel** [comment]
@machi1990,
Thanks for the answer.
Since there is already a feature for this I will close this issue.

**Comment by machi1990** [comment]
> In most of the applications I work with I usually need to make some validations so that certain things only run in testing environment.

What kind of validations do you have in mind? In the meantime, Quarkus supports to define profile specific configuration properties through `%profile.quarkus.....` e.g `%test.quarkus.datasource.driver=org.h2.Driver`

**Comment by NetoDevel** [comment]
@machi1990,
Imagine when startup the application I run a routine that looks for errors in integrating something.


I don't want this to run while I run my integration tests.

Programmatically I do an evaluating in which profile I am running so this routine does not run.

what you told me to use should works .. but it works if I pass as argument of my .jar or set in my ide and I believe the best solution would be that this setting had within the application in the case into application.properties

**Comment by machi1990** [comment]
> but it works if I pass as argument of my .jar or set in my ide and I believe the best solution would be that this setting had within the application in the case into application.properties

Indeed if you pass the `-Dquarkus.profile` property or use `QUARKUS_PROFILE ` env variable, `ProfileManager.getActiveProfile()` will return the custom profile. Otherwise, it will return default values depending on which environment you are running on:
1. `dev` - if you are in dev mode
2. `test` - if you are in test mode (except for native tests which run under the `prod`profile )
3. `prod` - if you are in production mode e.g launching via `.jar` file, a native executable

This is documented here - https://quarkus.io/guides/application-configuration-guide#configuration-profiles

**Comment by NetoDevel** [comment]
@machi1990, 
Ahh cool.
I will close this problem.
Thanks
