### ISSUE TITLE
Dedicated artefact for native-image substitutions

### ISSUE THREAD

**Issue by lburgazzoli** [quarkusio/quarkus#5091]
**Description**
An extension is now composed by a build artefact and a runtime one where the runtime one hosts eventual substitutions needed to patch java classes in order to be compiled and run in native mode. From a user point of view, the artefact that matter is the runtime one as the deployment one is automatically discovered and consumed by quarkus tooling.

This separation is ok for most of the time but sometimes a little bit more flexibility is needed.

As example, when the quarkus http layer was based on undertow, we had some issues on camel-quarkus as:
- undertow can be used also as a client by Apache Camel but by depending on quarkus-undertow for the substitutions, we had also the side effect to have an undertow server being started
- adding substitutions on Apache Camel side was a possibility but it would breaks the build in case the quarkus-undertow is on the classpath as substitutions clashes

As interim solution an additional artefact quarkus-undertow-common with substitutions only was added so we had the possibility to use it without the side effect of having a undertow server started.
 
**Implementation ideas**

Make each extension based on 3 artefacts:
- deployment
- runtime
- runtime-native

The `runtime-native` is an optional artefact that can be discovered and downloaded by the quarkus tooling as the `deployment` one (or added as transitive dependency of the `runtime`) so for the end user things do not change but if needed the `runtime-native` artefact can be consumed independently.

**Comment by dmlloyd** [comment]
I think having substitutions be a first-order concern is going to cause trouble & confusion.

In this case we probably want e.g. `quarkus-undertow(-server?)`, `quarkus-undertow-client` (maybe), and `quarkus-undertow-common` extensions.  That would solve the problem just as well; generally if you have a library that is multi-purpose then it should probably have multiple extensions to support it so that users can cherry pick the extensions they want and get a reasonable "auto on" no-configuration behavior.

Another thing worth mentioning is something from our early design meetings.  It isn't too hard to design extensions with a global on/off switch.  For example if I have a `quarkus-frobnicator` extension, I could define a `quarkus.frobnicator` property which defaults to `true`.  This also makes it easy for users to turn extensions on and off from the command line, which may be useful for testing and experimentation, e.g. `mvn test -Dquarkus.frobnicator=false # test without the frobnicator and see what happens`.

**Comment by lburgazzoli** [comment]
A "feature flag" would be more than enough.

The proposal to have an additional artefact was meant to avoid causing changes to existing extension but if that's not a huge concern, then I'm all for switch.

**Comment by Sanne** [comment]
It's tempting to have the subtitutions in a separate jar so to not need having such classes when e.g. there is no interest in native images. But they are often very small, I'd guess there is no significant space benefit other than satisfying a sense of OCD :)

Also agree with David that the root problem is likely just a lack of flexibility of the extension; there is likely always going to be a way forward by just evolving the extension.

One doubt I have is that if we see the need of adding more flags to extension very often, it's a dev overhead to have to wait for coordination across projects. I guess we'll see how often this is a real problem, if it ever becomes a real burden we could re-evaluate.

**Comment by Sanne** [comment]
Looks like we agreed to not do this, at least for now?

I'll close, we can re-open and re-evaluate as needed. Thanks!
