### ISSUE TITLE
MP JWT TCK RolesAllowedTest fails when run individually

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5172]
**Describe the bug**
Michal @michalszynkiewicz has discovered that `RolesAllowedTest.testNeesGroup1Mapping ` fails when `RolesAllowedTest` is run individually.

For the record, it passes when run individually in Thorntail

**Expected behavior**
The test always passes

**Comment by michalszynkiewicz** [comment]
@sberyozkin, turns out I was wrong.
The test is not executed at all when we run all the tests because it's in the `ee-security-optional` group. And we only run: https://github.com/quarkusio/quarkus/blob/849c28ef9940ac898173fbb4808d8c7b13b71fd5/tcks/microprofile-jwt/tck-base-suite.xml#L23-L32

The name `-optional` suggest that we don't need to pass it so it's probably okay that we don't.

Do you think we can close this issue?
