### ISSUE TITLE
microprofile annotation generates second parameter in UI

### ISSUE THREAD

**Issue by gintsgints** [quarkusio/quarkus#5241]
**Describe the bug**
When I execute next example:

```Java
    @GET
    @Path("{CaseNumber}")
    @Operation(summary = "Gets ClaimCase by it's CaseNumber")
    public ClmClaimCaseEntity getClaimCase(
            @Parameter(description = "ClaimCase number should be specified", required = true)
            @PathParam("CaseNumber") String number
    ) {
```

**Expected behavior**
I should get one username field in swager-ui.

**Actual behavior**
I get two fields for query instead

**Screenshots**
![image](https://user-images.githubusercontent.com/1847580/68275611-df40e580-0074-11ea-867a-21ed7123f6e3.png)

**Environment (please complete the following information):**
Java 1.8
Quarkus version: 0.22.0

**Comment by gsmet** [comment]
@gintsgints could you try with 0.28.1? There has been a whole lot of fixes in SmallRye OpenAPI since then.

**Comment by gsmet** [comment]
@EricWittmann does it ring a bell?

**Comment by gintsgints** [comment]
Yes. Works with latest 2.28.1 version. Thank you.

**Comment by EricWittmann** [comment]
@gsmet I suspect this is a new bug.  We should open something up in smallrye-open-api.  Very likely this specific case is not covered.  The case is where the `@Parameter` annotation is put directly on the Java method argument without a `name` property.  That SHOULD work because of course we could infer that the annotation goes with the argument.  But likely we aren't doing that.  

A temporary workaround until we fix this would be to add the `name` of the property in the `@Property` annotation, like this:

```java
@GET
@Path("{CaseNumber}")
@Operation(summary = "Gets ClaimCase by it's CaseNumber")
public ClmClaimCaseEntity getClaimCase(
        @Parameter(name="CaseNumber", description = "ClaimCase number should be specified", required = true)
        @PathParam("CaseNumber") String number
) {
```
