### ISSUE TITLE
quarkus-smallrye-jwt should provide JWT creation API

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#5341]
**Description**
The users should use `smallrye-jwt` API to easily create JWTs to test or use when self-issued tokens are acceptable

**Implementation ideas**
`smallrye-jwt` will provide it, see https://github.com/smallrye/smallrye-jwt/issues/137

**Comment by sberyozkin** [comment]
See https://github.com/smallrye/smallrye-jwt/pull/153

**Comment by sbeigel** [comment]
Great addition! But I think io.smallrye.jwt.build.impl.JwtProviderImpl (i.e. its no-args constructor) must be registered for reflection to be usable in native images:

`Caused by: io.smallrye.jwt.build.JwtException: JwtProvider io.smallrye.jwt.build.impl.JwtProviderImpl could not be instantiated: java.lang.InstantiationException: Type `io.smallrye.jwt.build.impl.JwtProviderImpl` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.
`

As a workaround, I added an entry in my reflection config file.

**Comment by patoessy** [comment]
Any documentation on this?

**Comment by patoessy** [comment]
Congratulations for this, and helping smallrye's contributors implement this feature. I want to update the guides on JWT please someone give me direction.

**Comment by sberyozkin** [comment]
@sbeigel it is a late comment, sorry, it has been fixed I believe in the latest releases.
@patoessy Hi, thanks, I still recall I promised to ping you to help with the docs, I've added a few, but I'm doing few more optimizations and once they are done and doc-ed I'll ping you for help to test  and check the docs, cheers

**Comment by patoessy** [comment]
Thanks. I will update once everything is ready. Nice work so far.
