### ISSUE TITLE
--initialize-at-build-time added with empty value

### ISSUE THREAD

**Issue by jkristof94** [quarkusio/quarkus#5480]
Is there a specific reason `--initialize-at-build-time` gets added every time with empty value to the native-image argument list? It comes from [here](https://github.com/quarkusio/quarkus/blob/master/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/NativeImageBuildStep.java#L175)

**Comment by emmanuelbernard** [comment]
We use the programmatic API to pass these informations, so we pass a much bigger command line virtually than what you see :)

**Comment by jkristof94** [comment]
Good to know, but it makes things confusing, to say the least. Is there any way to see what actually gets executed?

**Comment by dmlloyd** [comment]
It is not really possible because the native image compiler considers something called "features" which exist in the class path of what is being compiled, and there are tons of them (plus a few which we add as well).  They can do pretty much anything.  The command line is really a small subset of what actually happens in a native image build.

**Comment by jkristof94** [comment]
Thank you for the clarification! Would it make sense (and be possible) to remove that line from the command line output to reduce confusion?

**Comment by dmlloyd** [comment]
No, the command line that is printed is the one that is actually run in order to correctly produce the native image.  Removing the option would result in an incorrect/non-functional build.  The option is really present in the build.  What Emmanuel was alluding to is that the command line options do not completely describe what is happening in the build.  But they are still needed (in this case, the argument sets the default to "build time", and we use features to establish which classes are run time, overriding the default).

**Comment by gsmet** [comment]
Closing. This is how it should be.
