### ISSUE TITLE
Reduce down to a single Vert.x instance

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5593]
### Description
Having two instances of Vert.x running is a large source of bugs.

@FroMage has done some initial work.

### Analysis
_Links to analysis docs (E.g Design, Requirements, etc)_

### Tasks
- [ ] _Checklist of sub tasks goes here_

**Comment by FroMage** [comment]
I'm trying this on a rebased RESTEasy 4.5.0-SNAPSHOT, but it comes with jakarta.xml.bind apparently, which trips up our enforcer. @gsmet any idea how I should proceed?

**Comment by FroMage** [comment]
Depends on https://github.com/resteasy/Resteasy/pull/2170

**Comment by FroMage** [comment]
I've restarted this and implemented the right async writer stuff for quarkus (resteasy on vertx). This needs some tests, but also decisions.

ATM, this is implemented by:

- Adding a new `AsyncMessageBodyWriter` interface which is a subtype of the `JAX-RS `MessageBodyWriter` which supports writing to async streams. This means not every provider will support async writing. I can do most of the standard ones that RESTEasy or Quarkus provide, but some will require buffering because they're push-style rather than pull (Jackson for example).
- Adding a new `AsyncOutputStream` interface which is a subtype of `OutputStream` that the `HttpResponse` implementers can provide (servlet, vertx, netty and quarkus do). Others get a blocking `AsyncOutputStream` that actually calls blocking methods. Really not sure about this one.

ATM we do async writing if the writer supports it (`AsyncMessageBodyWriter`) and the output stream supports it (`AsyncOutputStream`), which pretty much means all the time in Quarkus.

I could do this only for async requests, but eventually we'll need to turn this on anyway even for blocking requests that run on the IO thread.

Now the big question is what should we do if we're on the IO thread but the writer does not support async IO? Custom user writer or one that we forgot to port.

@stuartwdouglas @patriot1burke any opinion?

**Comment by FroMage** [comment]
Also, not sure how to start showing my branch, because it requires a custom-built RESTEasy, so CI will never build. Opinions?

**Comment by patriot1burke** [comment]
My early benchmarks showed that buffering was significantly less performant than the blocking IO approach that currently exists.  This was a simple synchronous REST service hello world get service.  I'm guessing its because you're not using direct buffers and doing more memory allocations.  Don't know.  IMO, more in-depth benchmarks should be done to:

* Show that buffering doesn't hurt performance for the regular, most common JAX-RS service.
* Show that your solution actually improves performance for the async case

I have a resteasy branch that creates a new SPI

interface ExecuteBlocking {
   boolean isIoThread();
   void executeBlocking(Runnable runnable);
}

Code checks if Response implements this interface, if so, checks if ioThread, if so, it invokes executeBlocking.  I haven't had a chance to fully test it out yet.

**Comment by patriot1burke** [comment]
@FroMage Another problem with your approach is the SeeEventSink code.  It sits *around* response processing and works directly with the OutputStream to setup initial response and to flush between send events.  I don't see how buffering coudl work in this scenario as I do think we'd want to flush between sent events rather than sending them all at once.

**Comment by FroMage** [comment]
@patriot1burke so first I'm only back on this stupid issue because you ran away with your PR after I thought I had dodged the bullet by slipping you the damn task ;) If you have a working solution that is better than mine, once again by all means please push it and I'll be very happy to move on to another bug. 

I'm really not convinced my PR is the best way to move forward. It seems the right logical way to expose async IO to the writers, and it works for all server types, but it's some work. If your approach also works, and is more efficient, I'm all for it.

As for the buffering you mention, I'm really not sure what you're talking about. Are you talking about the buffering required by some `MessageBodyWriter` rewrites to async IO? If yes, plain text and jsonb already fully buffer before writing so :man_shrugging:…

> It sits around response processing and works directly with the OutputStream to setup initial response and to flush between send events. I don't see how buffering coudl work in this scenario as I do think we'd want to flush between sent events rather than sending them all at once.

Well, for SSE actually I think it's the most straightforward because the API is already in place in the spec to make each event wait for the previous one to have been sent. I don't see the issue there wrt flushing.

**Comment by FroMage** [comment]
FTR here's the quarkus side of the async-io branches: https://github.com/quarkusio/quarkus/compare/master...FroMage:resteasy-asyncio?expand=1

**Comment by patriot1burke** [comment]
Yup I suck, sorry...

I told you before I was worried about your approach because it doesn't fit with JAX-RS as interceptors assume i/o will be processed on the same thread call stack.

I also think that the benefits of your approach should be proven that they are actually more performant before we have to maintain it.  What's wrong with that?

As for SSE the API is there, but the implementation isn't.  Especially if you're not sending a content-type that doesn't have an async writer.

**Comment by stuartwdouglas** [comment]
So here is an alternate approach:

- Remove the exceptions for blocking IO from our output stream impls, and instead if a write is done that would block the IO thread we switch to buffering internally
- If the buffer gets past a threshold we spill over to disk. This will be slow but should not be something that happens regularly.

This could be the least bad option, as it does not require changes to marshallers, and most object RESTEasy returns will likely be small enough to buffer. It is also a generic solution that can be applied to anything that wants to do blocking IO from the IO thread.

**Comment by patriot1burke** [comment]
@stuartwdouglas Would still need an internal resteasy SPI to handle backpressure suppliers.  Probably not that ugly.

**Comment by stuartwdouglas** [comment]
Well you could avoid any need for backpressure by just spilling all the overflow onto disk (basically treating the disk as an effectively unlimited buffer), although I guess you still need something for the SSE case.

**Comment by patriot1burke** [comment]
Kinda feel like just handing off to a worker thread and blocking would be simpler, which is what I have in a branch right now.  With that case there is no heap buffering, or overflowing to disk and you'd always write to direct buffers.

**Comment by FroMage** [comment]
So, why again don't we have the same issue for reading data? Since reading is blocking in JAX-RS, if we're on the IO thread it will block just as well, no?

@patriot1burke note that my solution of using async IO does not do any more buffering than the blocking solution: all it does is make sure IO is queued when ready rather than block.

@stuartwdouglas honestly I've said from the start that I think it should be the framework's responsability to do all IO before (reading) and after (writing) the work is done, and decouple those from the work. By buffering both ends, unless super specific IO tasks are required, which we can force on a worker thread (blocking IO) or handle using async IO (SSE). If you say we should buffer I'm all for it.

**Comment by patriot1burke** [comment]
Shouldn't this queueing and disk dumping be done at the Vert.x level instead?

**Comment by FroMage** [comment]
@patriot1burke can you answer my questions?

If we're not going with fully buffering input/output, which is simpler than my PR, @vietj just suggested that I tweak my PR to still implement async IO but if we encounter a `MesageBodyWriter` which does not support async IO (user-provided for example, because the standard RESTEasy ones can all be adapted) we add an SPI that checks if we're allowed to block (worker thread) and if yes we do it old-style, but if we're not (we're on the IO thread, so the request must already be async) we delegate the blocking writing to a worker thread.

That should work in every case. There's no more buffering than the current implementation.

**Comment by FroMage** [comment]
Damnit. I thought I was close to being done.

I made it so we handle blocking and async writers differently based on the http backend.

- netty and vertx run async writers on the io thread, and blocking writers on a worker thread
- servlet runs everything on the current thread (provisions to be made for undertow having an io thread)

Here I'm talking about the resteasy-distribution backends, not the quarkus-resteasy-vertx backend we have in quarkus.

Except the resteasy-cache interceptors don't work, because they intercept around the blocking io write operation with a custom `ByteArrayOutputStream`, then read it to do caching (which is weird IMO because etags should be extracted from the entity being serialised before serialisation but whatever).

And that test runs on Netty, which is currently running on the IO thread (and has been forever, like the vertx backend) in a way that I'm pretty sure is flawed, because it pretends its async IO calls are blocking, when they're not and I'm also pretty sure that if you have a slow client netty and vertx will just stop accepting to buffer write calls since nobody is waiting for their completion, and we should not block the IO thread anyway.

Now, by fixing that and running blocking IO in a worker thread, and unblocking the IO thread, I'm now out of the caching filter before the writing has been done and it fumbles.

I can probably fix that caching filter to detect if the request has been suspended and in that case wait for it to be over, but I've a feeling this won't be the last filter to have issues.

I can decide to keep on ignoring that netty and vertx backends are async and run blocking writers on the IO thread, because they never actually block: they send write commands and never care when they're executed. But on quarkus I know @wburns fixed that issue by asking if the response buffers are full and actually blocking the current thread if it's the case, which can lead to blocking the IO thread again (remember this is in the case of a blocking writer, not the new async ones).

I'm not sure how to get out of that particular trap.

**Comment by FroMage** [comment]
BTW, I'm still waiting for an explanation why we don't have the same issue on input readers.

And now I'm wondering if we don't also have the issue on the resteasy-client side when it's running using vertx as its engine.

**Comment by patriot1burke** [comment]
@FroMage I'm not following you.  Are you saying that our current blocking worker thread model does not work?

**Comment by patriot1burke** [comment]
Also, I don't know what you're doing all this async writer work.  Unless you have one for Jackson I don't see the point.  IIRC, vert buffers Jackson marshalling, then writes it.  Am I wrong?  I'll get back to you on the input question.

**Comment by patriot1burke** [comment]
For input, I don't think its a problem because a) Resteasy+vertx and servlet start request processing on a worker thread and b) I don't see how input can get onto an io-thread:

https://github.com/resteasy/Resteasy/blob/5c2eff58ce072a7f17dda79ba4e76b69d6cd443f/resteasy-core/src/main/java/org/jboss/resteasy/core/MessageBodyParameterInjector.java#L133

The inject method only returns completed futures.

**Comment by patriot1burke** [comment]
FYI, the solution I'm trying out always switches to a worker thread and this switch happens before any response processing.

Also, the cache implementaiton is not weird.  Its creating etags from a hash of the marshalled response.

**Comment by FroMage** [comment]
> For input, I don't think its a problem because a) Resteasy+vertx and servlet start request processing on a worker thread and b) I don't see how input can get onto an io-thread:

OK so indeed as long as we're doing this we're good, but when we switch to running on the io thread later (which we want to do) it will stop working. ATM the vertx and netty backends (from the resteasy repo) are probably not fine, though, since they run on the io thread.

**Comment by FroMage** [comment]
> Also, the cache implementaiton is not weird. Its creating etags from a hash of the marshalled response.

Well usually we extract etags from the entity, not the serialised response.

**Comment by FroMage** [comment]
> Also, I don't know what you're doing all this async writer work. Unless you have one for Jackson I don't see the point. IIRC, vert buffers Jackson marshalling, then writes it. Am I wrong? 

Jackson has an async API, which vert.x uses, AFAIK.

**Comment by FroMage** [comment]
> Are you saying that our current blocking worker thread model does not work?

That model works. But it's not what the resteasy netty/vertx backends do: they both work on the io thread.

And the big picture is that we plan to run on the io thread in quarkus too as soon as we can determine that an endpoint is async. So I'm trying to make sure this solution goes in the right direction for that too.

**Comment by patriot1burke** [comment]
> > Also, the cache implementaiton is not weird. Its creating etags from a hash of the marshalled response.
> 
> Well usually we extract etags from the entity, not the serialised response.

Who's "we" and why is "we" better than me?  Without a hash of the output you could potentially get differing results from a load-balanced call.

**Comment by FroMage** [comment]
We as in implementors of REST calls that do caching based on etags, because in general it's the DB objects which have an etag-like column, or modified timestamp, that we can query without even loading the rest of the columns. If we do load the rest of the columns and get an entity, again we can look at its columns to determine if the response should be serialised and avoid serialisation entirely.

Here we're serialising for nothing, always. So it's always suboptimal. I understand it's probably better than nothing and probably we don't have automatic infra for the more optimal use-case (users have to write code), so it's still useful in some cases, but I don't think I'd ever use this if I want to enable caching.

But frankly, that's very much off-topic :-/

**Comment by patriot1burke** [comment]
> > For input, I don't think its a problem because a) Resteasy+vertx and servlet start request processing on a worker thread and b) I don't see how input can get onto an io-thread:
> 
> OK so indeed as long as we're doing this we're good, but when we switch to running on the io thread later (which we want to do) it will stop working. ATM the vertx and netty backends (from the resteasy repo) are probably not fine, though, since they run on the io thread.

I don't really care about geting the netty backend to work.  IMO, we should remove most/all of these backends and till people to use Quarkus.  The whole point of these backends was to create a more "lightweight" resteasy.

The vertx one I was going to move the quarkus code back to resteasy.

> We as in implementors of REST calls that do caching based on etags, because in general it's the DB objects which have an etag-like column, or modified timestamp, that we can query without even loading the rest of the columns. If we do load the rest of the columns and get an entity, again we can look at its columns to determine if the response should be serialised and avoid serialisation entirely.
> 
> Here we're serialising for nothing, always. So it's always suboptimal. I understand it's probably better than nothing and probably we don't have automatic infra for the more optimal use-case (users have to write code), so it's still useful in some cases, but I don't think I'd ever use this if I want to enable caching.
> 
> But frankly, that's very much off-topic :-/

It is not suboptimal, I just think you don't understand what's going on (btw, i didn't either until I read the docs again).  Its caching the response for ALL future gets from ANY client.  And etag generation can be overriden by setting the etag header yourself.

**Comment by patriot1burke** [comment]
BTW, I cannot find any docs (yet) that describe how to use Jackson async API with vertx.  All the vertx web json examples do buffering.
