### ISSUE TITLE
RESTEasy: Move more startup to build-time

### ISSUE THREAD

**Issue by paulrobinson** [quarkusio/quarkus#5603]
### Description
While RESTEasy's startup part being at runtime doesn't penalize us too much on native, I think it does penalize us possibly for RSS on JVM mode. The idea is to get someone to explore the work and possible gain.

### Analysis
_Links to analysis docs (E.g Design, Requirements, etc)_

### Tasks
- [ ] _Checklist of sub tasks goes here_

**Comment by emmanuelbernard** [comment]
The key conversation is identifying who can work on this (in knowledge and time) @dandreadis @n1hility @asoldano 
It will decide whether we start that work now or later.

**Comment by patriot1burke** [comment]
I did a bunch of work on this back in January.  Resteasy has the necessary hooks now.  I never submitted a PR because it actually generated a ton of initialization code. A lot. And was a lot more complicated than our current intialization.  Only static initialization times were improved and I didn't record memory footprint.  As it didn't remove any reflection and static init code exploded I worry that memory footprint would have went up.

**Comment by n1hility** [comment]
This is out of date with the work on RESTEasy Reactive
