### ISSUE TITLE
Support injecting a list of Spring beans

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5668]
Originally brought up by @tpenakov

**Comment by rquinio** [comment]
Is this about 
spring-DI way `@Inject List<MyBean>` vs CDI way @Inject javax.enterprise.inject.Instance<MyBean> ?

**Comment by tpenakov** [comment]
This is the code snipped that does not work in Spring DI module, bur works on Spring:
`@Autowired
List<BaseProcessor> processors;`

**Comment by geoand** [comment]
Yes, in Quarkus one can use `@Inject javax.enterprise.inject.Instance<MyBean>` while in Spring DI one can do: `@Autowired List<MyBean>`.

If possible we should provide support for the latter syntax.

**Comment by rquinio** [comment]
The behavior is a bit tricky since there can also be producers with return type `Collection<MyBean>` both in Spring DI and CDI already.

From my quick tests, Spring prefers injecting first the collection of matching `MyBean` beans, unless there are none - due to `@Named`, `@Qualifier` etc. -, in which case it then considers injecting any `Collection<MyBean>` bean.

CDI (Weld) only considers the `Collection<MyBean>` bean obviously.

Should it be a change in Arc (to have same defaulting logic as Spring), or rather spring-di extension to re-write the relevant `Collection<MyBean>` injections points to inject `javax.enterprise.inject.Instance<MyBean>` and extract the list instead - if that's even possible ?

**Comment by geoand** [comment]
@rquinio the second solution is mostlikely the way to go
