### ISSUE TITLE
Render required GraalVM version in generated Dockerfile for native

### ISSUE THREAD

**Issue by dodalovic** [quarkusio/quarkus#5744]
**Description**

Currently, when we generate new project, `Dockerfile` for native image looks something like: 

![image](https://user-images.githubusercontent.com/6358061/69549360-71178080-0f99-11ea-9ebd-713a5b582350.png)

It may be useful if we have somewhere in comments inside this file generated required GraalVM version

Maybe this information should be present somewhere on [project generator page](https://code.quarkus.io/) as well

Cheers

**Comment by gsmet** [comment]
Thanks for your suggestion.

I'm not sure it's a very good idea because it will duplicate the information and the information will be stale when you will upgrade Quarkus.

GraalVM version is whatever version Quarkus currently recommends. If you use the Docker build, it will be automatically the correct one. Otherwise, the requirements are here https://quarkus.io/guides/building-native-image and here https://quarkus.io/get-started/ .

I think a better answer to that will be to generate the Dockerfile during the build. I need to talk to Stuart about that.

That way, we could add the information to the Dockerfile when we build the application and it will be up to date.

**Comment by dodalovic** [comment]
@gsmet That sounds completely sane.

**Comment by geoand** [comment]
As per Guillaume's comment, closing in favor of https://github.com/quarkusio/quarkus/issues/21081
