### ISSUE TITLE
Interceptors don't run for beans created by producer methods.

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5785]
**Describe the bug**
I couldn't get the security interceptors to run for a bean that was produced by CDI Producer.

**Expected behavior**
Interceptors should run regardless of how the beans are created.

**To Reproduce**
In the `extensions/security/deployment` module, add the following classes to the test directory:

```
public class MyBean {

    @DenyAll
    public String forbidden() {
        return "shouldBeDenied";
    }
}
```
,
```
@ApplicationScoped
public class BeanProducer {

    @Produces
    public MyBean beanWithSecuredMethods() {
        return new MyBean();
    }
}
```

Then change `CDIAccessDefaultTest` to add:

```
    @Inject
    MyBean myBean;

   @Test
    public void test() {
        assertFailureFor(() -> myBean.forbidden(), UnauthorizedException.class, ANONYMOUS);
        assertFailureFor(() -> myBean.forbidden(), ForbiddenException.class, USER);
    }
```

Of course `MyBean.class` and `BeanProducer.class` need to be registered in Shrinkwrap.

When the proper changes are added to the test and the new method is run, the test fails, because no security interceptor is run.

**Comment by geoand** [comment]
cc @mkouba @manovotn @michalszynkiewicz

**Comment by mkouba** [comment]
> Interceptors should run regardless of how the beans are created.

Unfortunately, CDI interceptors are not associated with instances returned from the producer methods. See https://docs.jboss.org/cdi/spec/2.0/cdi-spec.html#binding_interceptor_to_bean: _"The set of interceptor bindings for a producer method is not used to associate interceptors with the return value of the producer method."_ And the reason is that we don't control the creation of the bean instance. Since CDI 2.0 it's possible to use the `InterceptionFactory` but 1) the factory must be used on the producer side, 2) we don't implement it yet in ArC (there is https://github.com/quarkusio/quarkus/issues/3532).

**Comment by geoand** [comment]
Thanks for the info @mkouba
