### ISSUE TITLE
changed application.properties not taken into account starting devmode

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/quarkus#5832]
`mvn quarkus:devmode` picks up .java changes but does not pick up changes to `application.properties` for that I need to explicitly do `mvn compile quarkus:devmode`.

I would expect it to be picked up if .java changes are OR that all "compilable" source changes will be ignored by `quarkus:devmode`

**Comment by jaikiran** [comment]
Hello Max,

I just gave this a try against upstream master and it works fine. I did `mvn quarkus:dev` and once it was up, I accessed a resource. Then I edited application.properties to update certain detail and then accessed the resource again. I could see the changed being picked up:

```
2019-11-28 18:37:57,093 INFO  [io.qua.dev] (vert.x-worker-thread-3) File change detected: quarkus-app/src/main/resources/application.properties
2019-11-28 18:37:57,114 INFO  [io.quarkus] (vert.x-worker-thread-3) Quarkus stopped in 0.017s
2019-11-28 18:37:57,572 INFO  [io.quarkus] (vert.x-worker-thread-3) Quarkus 999-SNAPSHOT started in 0.458s. Listening on: http://0.0.0.0:8080
2019-11-28 18:37:57,572 INFO  [io.quarkus] (vert.x-worker-thread-3) Profile dev activated. Live Coding activated.
2019-11-28 18:37:57,572 INFO  [io.quarkus] (vert.x-worker-thread-3) Installed features: [cdi, resteasy, smallrye-openapi, swagger-ui]
2019-11-28 18:37:57,573 INFO  [io.qua.dev] (vert.x-worker-thread-3) Hot replace total time: 0.482s
```
Which version of Quarkus is this and which OS?

**Comment by geoand** [comment]
@maxandersen if the changes were made to `application.properties` **before** you launched devmode they won't be picked up. That's to be expected

**Comment by stuartwdouglas** [comment]
I think this is the culprit: https://github.com/quarkusio/quarkus/blob/af7c75aa52905507ba327a35fcac7cdedf322f1d/devtools/maven/src/main/java/io/quarkus/maven/DevMojo.java#L229

Basically this checks if the initial compile was done by checking for the existance of the 'target/classes' dir and if not compiles.

This is super inconsistent, because it means that if you don't compile an empty project it will compile for you, but if you then run it a second time it will never auto compile when target/classes already exists. 

I am going to check to see if I can see a way to detect if the 'compile' plugin has actually run.

**Comment by gastaldi** [comment]
Like @jaikiran in https://github.com/quarkusio/quarkus/issues/5832#issuecomment-559488994,  tried to reproduce the error Max described but failed. It works without @stuartwdouglas' patch

**Comment by maxandersen** [comment]
> were made to `application.properties` **before** you launched devmode they won't be picked up. That's to be expected.

I assume you mean **after** launching devmode. changes to application.properties like http.port aren't taking any effect while running - its only seen when restarting. 

but im closing this as I can't now reproduce what I saw - that when changing url driver from h2 to postgres it was not picked up without compile - trying it today it seem to work.

**Comment by stuartwdouglas** [comment]
http.port will never work, as hot replacement is based on HTTP requests. I could make it work if we really want it but I don't really think it is worth it?

**Comment by jaikiran** [comment]
> http.port will never work, as hot replacement is based on HTTP requests. I could make it work if we really want it but I don't really think it is worth it?

@stuartwdouglas, The only reason I can think of why the user might have changed the value is probably because that port is already being used by some other process. In that case the dev mode startup itself would (should) fail and that would mean changing the port in the application.properties will actually be hot deployed. So I personally don't see any genuine use case where we might want to support changing this port after a successful dev mode startup.
But, maybe we should at least log a WARN if we do detect this change in port during hot deployment, so that at least users are aware that the new port isn't being used?
