### ISSUE TITLE
Restart Quarkus application after port change from application.properties

### ISSUE THREAD

**Issue by angelozerr** [quarkusio/quarkus#5864]
**Description**

I start my Quarkus application, the application runs in `8080` port (default port). I update the `application.properties` with `quarkus.http.port=9090`, it should be helpful that Quarkus application restart with the configured port. Today I need to stop the application and restart it manually.

**Implementation ideas**

quarkus-dev tracks class changed, why it could not track application.properties changed to restart the application with the configured port. I don't know if it's an hard task?

**Comment by jaikiran** [comment]
Unless I'm mistaken, I thought this was working as late as a few weeks back. Do you see any errors when you change the port and access some application resource?

**Comment by jaikiran** [comment]
Looking at the code, it appears that we bind to the changed port, only if the dev mode start had failed (for whatever reason) and the application.properties is changed to use a different port. If the startup was successful and then the application.properties is changed to use a different port, then the new port isn't used.

This doesn't look like an intentional decision, but I don't have full knowledge of this area. @stuartwdouglas, does this look like a bug? It's at least very inconsistent with the way we deal with hot deployment after a failed dev mode startup and a proper startup.

**Comment by stuartwdouglas** [comment]
It's intentional. Dev mode restart works on HTTP requests, so the server is deliberately not restarted. It would be possible to do this but it needs special handling and would be a fair bit of work to do properly, so I don't really think the extra effort is worth it.

**Comment by stuartwdouglas** [comment]
Pretty much every other property change will be picked up from application.properties, but not that one.

**Comment by geoand** [comment]
Closing as `won't fix` as this does seems to be a very rare complaint
