### ISSUE TITLE
provide qualified entityManager

### ISSUE THREAD

**Issue by nimo23** [quarkusio/quarkus#5876]
**Description**
In quarkus, we can (must) use

```
@Inject
EntityManager em;
```

instead of 

```
// already qualified injection
@PersistenceContext(unitName = "PU_TEST")
private EntityManager em;
```

`@Inject EntityManager em` works, but it shows the warning:

`No bean is eligible for injection to the injection point [JSR-365 §5.2.2]`

because it is not qualified. 

**Implementation ideas**
Would be nice if quarkus provides a qualified injection point of an `entityManager`. For example:

```
@Persistence
EntityManager em;
```

**Comment by knutwannheden** [comment]
This appears to be related to #2835 since examples like `@PersistenceContext(unitName = "PU_TEST")` hint at the use of multiple persistence units.

**Comment by knutwannheden** [comment]
According to the [documentation](https://quarkus.io/guides/hibernate-orm) a plain `@Inject EntityManager entityManager` should work without reservations. Does that indeed result in a warning in Quarkus?

**Comment by knutwannheden** [comment]
AFAICT the logic in `HibernateOrmProcessor#registerBeans()` should already make sure a provider gets registered so that the `EntityManager` and `EntityManagerFactory` can be injected without further qualifiers. So I think this issue can probably be closed.

https://github.com/quarkusio/quarkus/blob/1aa389074b1cc5eaceb007ce83eef4c4e86c0e77/extensions/hibernate-orm/deployment/src/main/java/io/quarkus/hibernate/orm/deployment/HibernateOrmProcessor.java#L509-L518
