### ISSUE TITLE
Improve interaction with web frameworks like react, angular etc

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#588]
@dreab8 was pointing to me that he worked on a project with Protean. It had classical Java backend and a React front end.
He wanted Protean to serve the front end content but having to put the react or angular directory structure under `META-INF/resources` is not convenient and would serve the whole project.
In his situation he had two top level projects. But we could envision a subproject of protean with the react structure possibly.

@dreab8 can you add more info on the pains you felt and how you think it could work.
@stuartwdouglas could you put down your ideas in this issue as well. You had some from last year on how to serve the front end as easily as possible.

**Comment by metacosm** [comment]
If I understand correctly, the issue is figuring out how to best bundle and serve static files created by an external tool (angular-cli, etc.) from Quarkus? Maybe I'm missing something here but why use Quarkus in this scenario? If it's because the backend is also developed using Quarkus, wouldn't it make more sense to develop the projects separately (and even deploy them in different pods) anyway? Presumably, there are better solutions to serve static files for a JS/TS frontend, are there?

**Comment by emmanuelbernard** [comment]
What you describe is a valid and clean architecture.
But for the not quite full on microservices person, an all in one app with quarkus:dev experience is really cool.

**Comment by emmanuelbernard** [comment]
Editing a UI screen + a Hibernate entity, REST endpoint hit save and look is what I'm looking for.

**Comment by klearchos** [comment]
Very good examples of what you describe can be generated with the help of JHipster.
It would be great for the Quarkus project to be integrated with the JHipster generator.

**Comment by edewit** [comment]
So either you put the front-end inside the quarkus project and let the maven front-end plugin generate the site, or you have a separate project and let npm tooling (or front-end plugin) put the output in the quarkus project. But for both of these solutions you would need the `quarkus:dev` command to also watch the target folder for changes, right? Does that sum it up?

**Comment by dhartford** [comment]
Actively reviewing a similar challenge where using a quarkus application that is in need of a UI, that based on any large/enterprise organization may mandate react+their styling / angular+their styling / some-other-nodejs-based-solution-specific-to-environment-working-in.

Having a 'developer joy' example that interacts with a nodejs-based UI (reactjs my preference), such as with the maven-front-end plugin and how to use quarkus:dev to watch/update on changes would be great, particularly for scenarios where the ideal would be an **_intuitive start-small-move-fast with a single project_** before getting buy-in to make it larger scale and break it out into separate projects with their own lifecycles (by project, I really mean repository, if its two maven reactor projects under a single parent that has a one-command-line devbuild, great).

**Comment by stuartwdouglas** [comment]
So most modern frontend web frameworks provide their own development server. We need to take advantage of this, as we also want to allow for hot reload in the web framework. This means there are two apprpaches we can use:

1) Map JAX-RS under a specific path (/api), then configure the frontend server to proxy /api to quarkus.
2) Add the ability to change the 'DefaultServlet' to a proxy servlet, that proxies requests to the frontend development server rather than serving static resources directly.

I think 1) is the way to go, as we can do this at the moment, so it is mostly just a case of documenting the workflow, and possibly adding some additional user friendliness (e.g. auto starting the dev server, auto redirecting to the correct port).

**Comment by nimo23** [comment]
How does quarkus treats the `src/main/resources/node_modules`-folder (which can have a vaste amount of data in different formats(js, css, html, txt)? Will it be scanned and included all over the time while (hot) compiling the project?

**Comment by edewit** [comment]
@nimo23 that is why I put organised [the frontend project](https://github.com/quarkusio/quarkus-quickstarts/pull/286) into 2 modules one for the frontend and one for the backend. That way only a `pom.xml` is needed extra in the frontend project (that also builds with the maven frontend plugin and copies the project into `src/main/resources/`) and using a proxy you can still to `npm start` and have hot replace

**Comment by nimo23** [comment]
@edewit So we need to watchers: one for quarkus:dev (server code) and the other for the frontend-code (for example, by webpack hot redeploy).

Is it possible to bind tasks by pom.xml to quarkus:dev to watch/rebuild the frontend-module also on any change?

**Comment by nimo23** [comment]
While developing, the frontend-code (react) is bound to the backend-code (quarkus) by a proxy. So every change on the frontend-code is rebuild by its _frontend-watcher_ while every change on the backend-code is rebuild by _quarkus:dev_. So there is no need to put the frontend-code in `src/main/resources/` on every change.

**Comment by edewit** [comment]
right it's not needed on every change to put the frontend-code in `src/main/resources` only when you do a maven production build will that be done.

**Comment by carldea** [comment]
> @dreab8 was pointing to me that he worked on a project with Protean. It had classical Java backend and a React front end.
> He wanted Protean to serve the front end content but having to put the react or angular directory structure under `META-INF/resources` is not convenient and would serve the whole project.
> In his situation he had two top level projects. But we could envision a subproject of protean with the react structure possibly.
> 
> @dreab8 can you add more info on the pains you felt and how you think it could work.
> @stuartwdouglas could you put down your ideas in this issue as well. You had some from last year on how to serve the front end as easily as possible.

In the npm/node world you don't want to watch files inside of the node_modules directory.

A popular thing I've seen in the React community is NextJS aka server-side rendering (different routing ability). You may be able to glean from their patterns and structure to get an idea. Maybe there should be an extension for each web framework (angular, reactjs(clientside rendering), nextjs/reactjs(serverside rendering) etc.)

I also heard the folk at GraalVM has a version of NodeJS having the GraalVM inside able to run Java code and Node/Npm(javascript) code.

But yea, I'm looking forward to this idea/ability. Decoupling is good, but this option just allows you to develop faster for small/medium projects.

**Comment by ia3andy** [comment]
btw we have a related blog article: https://quarkus.io/blog/quarkus-and-web-ui-development-mode/

**Comment by ia3andy** [comment]
For code.quarkus.io, we have a react frontend:
https://github.com/quarkusio/code.quarkus.io

1. The frontend is located in `src/main/frontend` as a standalone react app
2. We use the frontend maven plugin for the production build which is configured to copy the build to the quarkus static directory in the target folder (no watch): https://github.com/quarkusio/code.quarkus.io/blob/master/src/main/frontend/package.json#L37
3. For dev mode, we run 2 processes (quarkus:dev and react dev) using a Makefile: https://github.com/quarkusio/code.quarkus.io/blob/master/Makefile#L8

I think the dev mode could be improved by integrating it in the frontend maven plugin because it's the part responsible of dealing with yarn or npm.

Maybe we could have some kind of extension to make it easier and bind everything together?

**Comment by johnbanq** [comment]
Is it possible that we solve the problem by writing a small maven plugin that replaces the Makefile and spins up the servers for you at dev time?

**Comment by manusa** [comment]
Just for completeness, this weekend I finally managed to find the time to write yet another [blog post](https://blog.marcnuri.com/react-quarkus-integration-using-maven/) about SPA frontend and Quarkus backend integrations. This is an approach I've been using for years with other frameworks, but I haven't seen it documented anywhere.

The main issue with building the frontend into the `META-INF/resource` directory approach is that front-end routers won't work as expected. This means that if you access `http://localhost:8080/front-end/nested/path` your `index.html` file won't be found and your front-end application won't load.

> btw we have a related blog article: https://quarkus.io/blog/quarkus-and-web-ui-development-mode/

In Kabir's blog post, the issue is tackled using a [Servlet or a Filter](https://quarkus.io/blog/quarkus-and-web-ui-development-mode/#handle-angular-routes), which works great.

In [my case](https://blog.marcnuri.com/react-quarkus-integration-using-maven/), I'm just using a standard [JAX-RS endpoint definition](https://github.com/manusa/yakc/blob/6f89e826972a62689c5dfc537c68ecae26f3c70b/quickstarts/quarkus-dashboard/src/main/java/com/marcnuri/yakc/quickstarts/dashboard/GatewayResource.java#L62).It's a similar solution to that of the servlet/filter, but IMHO it allows more flexibility and control regarding the frontend build and assembly.

With respect to the frontend build, I'm using the **standard** Maven [resources](https://github.com/manusa/yakc/blob/6f89e826972a62689c5dfc537c68ecae26f3c70b/quickstarts/quarkus-dashboard/pom.xml#L62) and [exec](https://github.com/manusa/yakc/blob/6f89e826972a62689c5dfc537c68ecae26f3c70b/quickstarts/quarkus-dashboard/pom.xml#L87) plugin.



Regarding hot-reloading / Development mode, I find it quite easier running each application with its own dev server and configuring CORS in Quarkus. You can read more about this [in the article](https://blog.marcnuri.com/react-quarkus-integration-using-maven/) too.

**Comment by nimo23** [comment]
@edewit Why is https://github.com/edewit/quarkus-quickstarts/tree/react-example/react-rest not more available in https://github.com/quarkusio/quarkus-quickstarts?

**Comment by edewit** [comment]
@nimo23 it's an open PR https://github.com/quarkusio/quarkus-quickstarts/pull/286 leave a +1 on it ;)

**Comment by ia3andy** [comment]
Quinoa 1.0.0 has been released. We now have a elegant integrated way to deal with web framework:
https://github.com/quarkiverse/quarkus-quinoa

1.0.0 will soon be available on code.quarkus.io, until then you can just add the dependency.
