### ISSUE TITLE
Allow the easy instantiation of CDI beans

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#5955]
**Description**

I was wondering if it would make sense to make eager instantiation super easy for users via either an annotation (for per bean control) and / or a config property that would make bean instantation eager by default.

**Implementation ideas**

We could basically generate the necessary `void startup(@Observes StartupEvent event)` under the hood - or perhaps tie deeper into Arc to make this controllable.

**Comment by geoand** [comment]
cc @mkouba @manovotn

**Comment by manovotn** [comment]
Note that this annotation would only make sense for something like `@ApplicationScoped` or `@Singleton`. We would need to either document that, or log a warning if it's used in combination with others (which could be tricky given that you could add it via annotations transformer).

**Comment by gastaldi** [comment]
+1 for a `@Startup` annotation. In some classes writing an observer method just to initialize (which does nothing) during the startup is annoying

**Comment by manovotn** [comment]
Mostly, you shouldn't do that as it defeats the lazy init approach that Arc does. But I agree that from time to time, it is indeed handy. I am just scared people will toss that annotation on every bean out there :-)

What I am not so sure about is calling it `@Startup`; while it is familiar, it could be mixed up with [EJB startup](https://docs.oracle.com/javaee/7/api/javax/ejb/Startup.html) and then we'll see people trying to use that one instead. Maybe we could go with something like `@EagerInit`?

**Comment by geoand** [comment]
Or just plain `@Eager`?

We have so far in Quarkus provided a lot of such conveniences to users, so I think this would fit nicely in the general developer experience theme.

**Comment by gastaldi** [comment]
I wonder how can people use EJB's Startup if the EJB jars are not available in Quarkus?

I'm fine with any other name, just thought this would be more intuitive :)

**Comment by mkouba** [comment]
> Mostly, you shouldn't do that as it defeats the lazy init approach that Arc does

+1

The observer approach has also some advantages. For example, you can inject a `@Dependent` bean, use it in the observer and afterwards the bean is transparetnly destroyed.

@gastaldi You could be surprised ;-). For example, there was a bug in the `jakarta.interceptor-api` -> pom declared a dependency on `jakarta.ejb-api`. It should be fixed in the next version though: https://github.com/eclipse-ee4j/interceptor-api/commit/017aeb56849bbb448319aaf36df45a07ec54f451.

**Comment by mkouba** [comment]
Implementation note: the easiest solution from impl POV would be to introduce an interface, e.g. `StartupCallback` with default no-op `startup()` method and then in the [LifecycleEventRunner](https://github.com/quarkusio/quarkus/blob/master/extensions/arc/runtime/src/main/java/io/quarkus/arc/runtime/LifecycleEventRunner.java#L22-L24) iterate over all beans that implement this interface and invoke each of the beans.

**Comment by geoand** [comment]
@mkouba and maybe we can use a new annotation to transform the beans to add that interface to classes that are annotated?

**Comment by mkouba** [comment]
> and maybe we can use a new annotation to transform the beans to add that interface to classes that are annotated?

I'd personally try to avoid transformations if possible. Recently, I did some quick and dirty tests and it seems that transformations are pretty expensive.

**Comment by geoand** [comment]
Expensive in what way?

**Comment by mkouba** [comment]
Simple transformations are probably fine but complex transformations like the ones perfomed by hibernate take quite a lot of time. For example, the augmentation phase in `hibernate-orm-quickstart` takes approx. 2s on my machine. And if I do `mvn clean package -X -DskipTests | grep Finished | sort -nr -k 7` I can see that `ClassTransformingBuildStep#handleClassTransformation` takes ~ 560 ms and `HibernateOrmProcessor#enhancerDomainObjects" ~ 220 ms (and these two build steps cannot be processed in parallel). Of course, the measurement is not accurate at all. But still...

**Comment by geoand** [comment]
Gotcha thanks. We can always try it out and see what kind of effect it will have on performance

**Comment by nimo23** [comment]
Where there is a `@Startup`, there should also be a `@Shutdown` - then you will likely thinking of re-using the already established annotations of EJB:

```
@ApplicationScoped
@Startup
public class Starter  {

// replaces void onStart(@Observes StartupEvent ev)
@PostConstruct
private void postConstruct() {

}

// replaces void onStop(@Observes ShutdownEvent ev)
@PreDestroy
private void postConstruct() {

}

}
```

Btw, maybe quarkus can implement its own _light_ version of ejb which fit in the quarkus-world..because the concepts are already there..

**Comment by mkouba** [comment]
@nimo23 `@PostConstruct` and `@PreDestroy` are not EJB annotations and both callbacks are supported on CDI beans. Also both the application and singleton context are destroyed during the app shutdown. So any existing bean instance of a bean with the `@ApplicationScoped` or `@Singleton` scope is destroyed during shutdown. 

Currently, the following snippet works just fine:

```java
@ApplicationScoped
class Starter  {

  void onStart(@Observes StartupEvent ev) {} // make sure the bean is created during startup
 
  @PreDestroy
  void onStop() {
    // place the shutdown logic here
  }
}
```

**Comment by nimo23** [comment]
yes, `@PostConstruct` and `@PreDestroy` are CDI annotations. However, instead of annotating the bean with `@Startup` which calls automatically `@PostConstruct`, in quarkus I add the `@Startup` to a method, and when this method is called the bean also calls the `@PostConstruct` because the bean is instantiated. The same would go for a `@Shutdown` which destroys the bean and calls implicitly `@PreDestroy`. Why not using `@Startup` on class level ? With this `@PostConstruct` and `@PreDestroy` can be used for quarkus like `@Startup` and `@Shutdown`? In your example, you see no use of `@PostConstruct` but you use `@PreDestroy` to have something like a `@Shutdown`. Are there any benefits in having `@Startup` on the method level? In EJB we put the `@Startup` on the class level..

@ApplicationScoped
class Starter  {

  // @PostConstruct h
  void onStart(@Observes StartupEvent ev) {} // make sure the bean is created during startup
 
  @PreDestroy
  void onStop() {
    // place the shutdown logic here
  }
}

**Comment by mkouba** [comment]
> yes, @PostConstruct and @PreDestroy are CDI annotations.

Not really, those annotations come from `javax.annotation` and are supported by both EJB and CDI.

> Why not using @Startup on class level ?

That was the original intention of this issue. My point was that:
1. From impl POV it would be easier to add a callback interface 
2. Observers are well-defined in the CDI world and so we don't have to re-invent the wheel and handle all corner cases. For example, what happens if you declare the `@Startup` annotation on a bean for which the context (e.g. `@RequestScoped`) is not active during startup? Of course, we could clarify this in the javadoc but for observers everything is already there in the spec.

In any case, I'm not against a class-level annotation. I'm just trying to consider all possibilities ;-). 

> re-invent something like @DependsOn which already exist in the ejb world

I have to admit that I don't know the details but I'd like to avoid implementing this if possible. It could be very complex and error-prone.

**Comment by nimo23** [comment]
>Observers are well-defined 

yes, you are right. Using observers for `@Startup` makes sense.

>I'd like to avoid implementing this if possible

To be honest, I have never a need to use `@DependsOn` and I think it can be easily achieved by alternatives (such as a @Startup-method which simply calls a sequence of other methods.)

**Comment by nimo23** [comment]
>In any case, I'm not against a class-level annotation. I'm just trying to consider all possibilities

Maybe using cdi stereotype where

```
@Startup
class Starter{

}
```

is the same as  

```
@Startup
@ApplicationScoped
class Starter{

}
```

**Comment by mkouba** [comment]
For the record - a duplicate issue https://github.com/quarkusio/quarkus/issues/6864 was created by mistake. The comments contain some interesting ideas but we should continue the potential discussion here.
