### ISSUE TITLE
No UserPrincipal in SecurityContext with @PermitAll in test mode

### ISSUE THREAD

**Issue by Teg79** [quarkusio/quarkus#5994]
**Describe the bug**
A Rest method with a `@Context SecurityContext ctx` param works from Postman in Dev mode but in test mode it returns a null Principal

**Expected behavior**
The call to `ctx.getUserPrinipal()` must return the current logged username

**Actual behavior**
From tests `ctx.getUserPrinipal()` returns null

**To Reproduce**
1. Create a new project with security-properties-file extension
2. Modify the ExampleResource:
```
@Path("/hello")
public class ExampleResource {

    @GET
//    @RolesAllowed({"admin_role"})
    @PermitAll
    @Produces(MediaType.TEXT_PLAIN)
    public String hello(@Context SecurityContext ctx) {
        Principal caller = ctx.getUserPrincipal();
        return caller != null ? caller.getName() : "NO CALLER";
    }
}
```
3. Modify the ExampleResourceTest:
```
    @Test
    public void testHelloEndpoint() {
        given()
          .when()
                .auth().basic("admin", "admin")
                .get("/hello")
          .then()
             .statusCode(200)
             .body(is("admin"));
    }
```

**Configuration**
```properties
quarkus.security.users.embedded.enabled=true
quarkus.security.users.embedded.plain-text=true
quarkus.security.users.embedded.users.admin=admin
quarkus.security.users.embedded.roles.admin=admin_role
```

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
```Darwin PC153-2 19.0.0 Darwin Kernel Version 19.0.0: Wed Sep 25 20:18:50 PDT 2019; root:xnu-6153.11.26~2/RELEASE_X86_64 x86_64```
 - Output of `java -version`: 
```
openjdk version "11.0.5" 2019-10-15 LTS
OpenJDK Runtime Environment Corretto-11.0.5.10.1 (build 11.0.5+10-LTS)
OpenJDK 64-Bit Server VM Corretto-11.0.5.10.1 (build 11.0.5+10-LTS, mixed mode)
```
 - GraalVM version (if different from Java): NA
 - Quarkus version or git rev: 1.0.1.Final

**Additional context**
If we replace the @PermitAll with @RolesAllowed({"admin_role"}) the test is working, the user principal has the correct value

**Comment by geoand** [comment]
This turns out to be due to how REST Assured handles basic auth.

Basically the problem is that REST Assured does not send the authentication header unless it receives a challenge when used the way you show.
To force REST-Assured to always send the auth headers, you need to use something like:

```
given()
          .when()
                .auth().preemtive().basic("admin", "admin")
```

where I added **preemptive** to what you had. You can read more about this here: https://github.com/rest-assured/rest-assured/wiki/usage#preemptive-basic-authentication

Now to be honest I wasn't aware of this feature either by I only discovered it when testing the application using a request from postman and saw that everything worked.
My next step was to capture the HTTP traffic with Wireshark which indeed releaved the difference.

**Comment by Teg79** [comment]
Thanks a lot @geoand ! Now it works
Just a typo in your response, the method name is `preemptive()` ;)

**Comment by geoand** [comment]
Thanks @Teg79, that's what happens when I don't copy paste :P
