### ISSUE TITLE
Pass Kotlin compiler plugin options to dev mode in Gradle

### ISSUE THREAD

**Issue by gastaldi** [quarkusio/quarkus#6035]
> Looks good. Haven't fully tested yet, but does it work in Gradle?

Nope, it will require a lot of work to get it working in Gradle as well. That is because in Gradle we can't just read the configuration, we'll need to read the Kotlin Gradle plugin data. It should definitely be done when all the other Gradle improvements things are in place.

_Originally posted by @geoand in https://github.com/quarkusio/quarkus/pull/6030#issuecomment-563152467_

**Comment by geoand** [comment]
We are currently in favor of not go down this path, but instead of configuring the proper Kotlin plugins and making sure their configuration is propagated to the dev mode, we plan to extend the build class transformation that is already done in some parts of Quarkus.
The idea is that each extension knows what are the requirements for a class to be part of its domain (like being non-final or having a no-args constructor), thus each extension is responsible for making those transformations (if possible).
This would allow for a zero-config Kotlin experience irrespective of the build tool and the Quarkus mode (prod or dev) being used.

So I am going to close this issue.
