### ISSUE TITLE
Kafka Streams - Missing topic holds app execution but there is no warning

### ISSUE THREAD

**Issue by hguerrero** [quarkusio/quarkus#6088]
**Describe the bug**
(Describe the problem clearly and concisely.)
If topics are  declared in the application.properties, the admin client waits for them to be created to start running the kafka streams application. There is no message in console or log about this behavior.

**Expected behavior**
(Describe the expected behavior clearly and concisely.)
Should produce a WARN mentioning app can't start processing messages because topic is missing.

**Actual behavior**
(Describe the actual behavior clearly and concisely.)
App freezes without any feeback

**To Reproduce**
1. Add non existent topic to properties
2. Start kafka streams app
3. 

**Configuration**
```properties
# Add your application.properties here, if applicable.

```

**Screenshots**
(If applicable, add screenshots to help explain your problem.)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
 - Output of `java -version`: 
 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 

**Additional context**
(Add any other context about the problem here.)

**Comment by gunnarmorling** [comment]
A message is logged, but probably not shown due to the log level config, see [here](https://github.com/quarkusio/quarkus/blob/master/extensions/kafka-streams/runtime/src/main/java/io/quarkus/kafka/streams/runtime/KafkaStreamsTopologyManager.java#L145-L152). @hguerrero, could you enable DEBUG logging and confirm whether you see it? That said, it'd probably make more sense to log the await case on a higher level like WARN.

**Comment by hguerrero** [comment]
Yes, better to move it to WARN.

**Comment by rquinio** [comment]
Indeed if an application cannot start, it's a big deal - some log feedback is definitely missing.

It may be a bit spammy since it'll log up to once per second, and if topics are being created by an operator (e.g. Strimzi) as part of the first deployment, it may take a bit of time (10s-30s). But creating new topics doesn't happen every day.
