### ISSUE TITLE
1000 parallel requests get 65 seconds to finish. Rest easy resource load test.

### ISSUE THREAD

**Issue by Sergey80** [quarkusio/quarkus#6113]
**Describe the bug**
Not sure it is a bug or feature. But it is slow feature then :)
1000 parallel requests get 16 seconds to finish. Each request 1 seconds (simulation of http call). with @Timeout annotation
1000 parallel requests get 65 seconds to finish. Each request 1 seconds - without @Timeout annotation
Both 16 and 65 seconds is too slow.

**Expected behavior**
2-3 seconds to complete?

**Actual behavior**
Too slow.

**To Reproduce**
1. 
```
@Path("/performance")
public class PerformanceTestResource {

    @Timeout(20000)
    @GET
    @Path("/resource")
    @Produces(MediaType.APPLICATION_JSON)
    public Response performanceResource() {

        final String name = Thread.currentThread().getName();
        System.out.println(name);

        Single<Data> dataSingle = null;

                try {
                    dataSingle = Single.fromCallable(() -> {
                        final String name2 = Thread.currentThread().getName();
                        System.out.println(name2);
                        Thread.sleep(1000);
                        return new Data();
                    }).subscribeOn(Schedulers.io());

                } catch (Exception ex) {
                    int a = 1;
                }

        return Response.ok().entity(dataSingle.blockingGet()).build();
    }

}
```
2. https://github.com/Sergey80/rxjava2samples/blob/master/src/main/java/rxjava2/samples/LoadTestUtilSample.java for callPeriodically definition.
3. 

```
@QuarkusTest
public class PerformanceTestResourceTest {


        @Tag("load-test")
        @Test
        public void loadTest() throws InterruptedException {

            int CALL_N_TIMES = 1000;
            final long CALL_NIT_EVERY_MILLISECONDS = 10;

            final LoadTestMetricsData loadTestMetricsData = LoadTestUtils.callPeriodically(
                                                                                    this::callHttpEndpoint,
                                                                                    CALL_N_TIMES,
                                                                                    CALL_NIT_EVERY_MILLISECONDS
                                                                            );

            assertThat(loadTestMetricsData.responseList.size(), CoreMatchers.is(equalTo(Long.valueOf(CALL_N_TIMES).intValue())));

            long executionTime = loadTestMetricsData.duration.getSeconds();

            System.out.println("executionTime: " + executionTime + " seconds");

            assertThat(executionTime , allOf(greaterThanOrEqualTo(1L),lessThan(20L)));
        }
```

P.S. I tried to go more 'reactive' returning Single or CompletionStage to return from the responses - but this seems not yet ready (buggy on rest-easy side). So I go with simple .blockingGet()` and Response.

**Comment by psycho-ir** [comment]
Just to ensure I got your test correctly.
Due to the`Thread.sleep` Every request takes 1 second to return response, and given that you used `dataSingle.blockingGet()` the thread will be blocked. 

So your throughput should be the same as the # of working threads you have per second. 

If you expect to get the load test done in ~3 you should at least have 340 working threads? assuming 0 overhead for context switch and other stuff. 

Right? or I missed something?

**Comment by geoand** [comment]
cc @johnaohara

**Comment by johnaohara** [comment]
@Sergey80 

Some points to note;

1) The test is making blocking calls from the vert.x worker pool. The default pool size is 20, so that is the maximum number of parallel requests you could make without tuning the vert.x worker pool. The fastest this test could theoretically run is 50seconds, without tuning the worker thread pool.
2) `@Timeout` will be cancelling the request before it is complete, I can not see if you are validating the returned result, or just counting the fact that something has been returned (need the impl details of `this::callHttpEndpoint` to verify)
3) `Thread.sleep()` is being scheduled on Schedulers.io() (which can create an unbounded number of single-threaded executors). So each request is blocking 2 threads for 1second. This creates multiple context switches during a single rest api call.

If you expect this particular test to run in 1-2 seconds then you would need to set the worker thread pool to a maximum of 1000 (as each requests blocks for 1s). Even with 1000 worker threads, I doubt you see the expected response times because the test will spawn a minimum of 2000 threads (1000 worker threads and 1000 rxJava "io" threads).



Please could you provide details about your comment `P.S. I tried to go more 'reactive' returning Single or CompletionStage to return from the responses - but this seems not yet ready (buggy on rest-easy side). So I go with simple .blockingGet()` and Response.`?  What problems are you facing when you try to create a reactive endpoint? 

Please could you create a reproducer for this reactive issue? I think that is core issue.

**Comment by Sergey80** [comment]
Ok Thanks for replying. See the RX Java 2 way.

`   @Path("/performance")
public class PerformanceTestResource {

    //@Timeout(20000)
    @GET
    @Path("/resource")
    @Produces(MediaType.APPLICATION_JSON)
    public Single<Data> performanceResource() {

        final String name = Thread.currentThread().getName();

        System.out.println(name);
        System.out.println("name: " + name);

        return Single.fromCallable(() -> {

            final String name2 = Thread.currentThread().getName();
            System.out.println("name2: " + name2);

            Thread.sleep(1000);
            return new Data();
        });
    }

}`

pom.xml

```
    <!-- Automatic context propagation for RxJava2 -->
    <dependency>
      <groupId>io.smallrye</groupId>
      <artifactId>smallrye-context-propagation-propagators-rxjava2</artifactId>
    </dependency>
    <!--
    Required if you want transactions extended to the end of methods returning
    an RxJava2 type.
     -->
    <!-- Required if you return RxJava2 types from your REST endpoints -->
    <dependency>
      <groupId>org.jboss.resteasy</groupId>
      <artifactId>resteasy-rxjava2</artifactId>
    </dependency>
```

Then when run same test:

executionTime: 64 seconds

The output would be something like:

`vert.x-worker-thread-5
name: vert.x-worker-thread-5
vert.x-worker-thread-9
name: vert.x-worker-thread-9
name2: vert.x-worker-thread-9
name2: vert.x-worker-thread-5`

If I use:Schedulers.io()

`  return Single.fromCallable(() -> {
           ...
        }).subscribeOn(Schedulers.io());`

executionTime: 16 seconds

Seems regardless: whether I use explicitly blockingGet() or not, i get the same result.

I assume if I am not blocking it it would be around 2-3 seconds.

I there a way to fix/tweak this from this point?

Thanks.

**Comment by Sergey80** [comment]
it makes me think. maybe my test is wrong. the app may not be yet stated or not hot enough. i will double check. will test against native one. will let you know. but feel free to reply .. thanks.

**Comment by Sergey80** [comment]
no, still testing against native (it is up and "hot" in couple of "nano-seconds"). take 18 seconds.

**Comment by Sergey80** [comment]
Ok. Maybe it is me.
 In my callPeriodically(); i pass CALL_NIT_EVERY_MILLISECONDS = 10 milliseconds.
10 * 100 = 10 000 - + ten seconds just to add the requests.

This, I set it to 0.

And got my 6 seconds.

Still not 2-3 seconds. But 6.

**Comment by gsmet** [comment]
@johnaohara that makes me think: do we have documentation for tuning Quarkus for performances? The Vert.x pool is one element, there might be others and we certainly need that to be documented.

**Comment by Sergey80** [comment]
i will try to teak with that.
One more thing if I run 10 000 requests it fails with:

Exception in thread "main" java.lang.OutOfMemoryError: unable to create new native thread

now.

**Comment by Sergey80** [comment]
I guess will close that one for now.
Thanks for replies.

**Comment by Sergey80** [comment]
edited: post the 1 second example for 1k requests.
