### ISSUE TITLE
Add more config options for quarkus-logging-gelf

### ISSUE THREAD

**Issue by blsouthr** [quarkusio/quarkus#6336]
Currently, logging-gelf extension is not allowing to set facility and other options to log to graylog.
Please, consider add all possible settings to make it fully configurable

**Comment by loicmathieu** [comment]
@blsouthr we tend to limit the number of configuration options in Quarkus for the sake of simplicity. That's why I didn't add all possible configuration options in the first implementation. If we add a configuration we need to document it and maintain it (and it can be deleted some day and lead to compatibility issue).

I hardcoded the facility to `jbos-logmanager` because the facility field should define the name of the framework/component that send the log.

You can find here the list of all configuration fields: https://logging.paluch.biz/examples/jbossas7.html

Please, list the one you need.

**Comment by blsouthr** [comment]
@loicmathieu  Having more than one application logging to graylog, we identify them by facility and some fields. So we need at least 'facility' and 'additionalFields'. Not sure if any other will be ever needed.

**Comment by gsmet** [comment]
> If we add a configuration we need to document it

This is not exactly right if we properly use the generated documentation. But yes, better add the configuration knobs that are the most useful first.

The ones mentioned by @blsouthr make sense IMHO.

**Comment by machi1990** [comment]
+1 with @gsmet here. @blsouthr would be interested in contributing a patch to this area? It should be an easy patch and maybe @loicmathieu or myself would be willing to mentor.
