### ISSUE TITLE
Build-time validation of Qute templates

### ISSUE THREAD

**Issue by gunnarmorling** [quarkusio/quarkus#6391]
I was expecting that an invalid reference in a Qute template (e.g. typo in variable name) would raise an error upon `mvn clean package`, but that's not the case. Is this planned for the future?

**Comment by mkouba** [comment]
Expressions are only validated if "parameter declarations" are used in a template, see https://quarkus.io/guides/qute-reference#parameter-declarations for more information. Otherwise it wouldn't be possible e.g. to connect an expression with a type. In other words, a template without param declarations does not know anything about the data that will be available at runtime.

**Comment by gunnarmorling** [comment]
Here's an idea: how about collecting implicitly declared parameters by statically analysing the names passed to the `data()` method in the byte code? It wouldn't be 100% safe as names might be generated dynamically, but most of the times I'd expect this to be invoked with string literals that can be obtained quite easily from class files.

**Comment by mkouba** [comment]
Unfortunately, we don't have the tools (in quarkus API/jandex) to collect this information yet. And what's more important - a user can pass different objects as data for the same template. E.g. there could be a template `My name is {person.name}` and you can pass a `Person` POJO or a `javax.json.JsonObject` with a `data()` method. That's why parameter declarations are necessary if you need to validate the expressions.

**Comment by mkouba** [comment]
I'm closing this issue. Users are encouraged to leverage the [Type-safe Templates](https://quarkus.io/guides/qute-reference#typesafe_templates) to gain the requested functionality.
