### ISSUE TITLE
Centralized log management with graylog not working

### ISSUE THREAD

**Issue by viniciusfcf** [quarkusio/quarkus#6434]
**Describe the bug**
I followed guide steps, however all graylog messages are with error.

**Expected behavior**
Log messages available on http://localhost:9000/search

**Actual behavior**
Log are available in http://localhost:9000/system/indices/failures

**To Reproduce**
1. [Use graylog guide](https://quarkus.io/guides/centralized-log-management)
2. After access: http://localhost:8080/gelf-logging
3. All applications log are available in http://localhost:9000/system/indices/failures

**Configuration**
```properties
quarkus.log.handler.gelf.enabled=true
quarkus.log.handler.gelf.host=localhost
quarkus.log.handler.gelf.port=12201

```

**Screenshots**
![Captura de tela de 2020-01-06 21-29-13](https://user-images.githubusercontent.com/14058396/71859320-37c04d80-30cd-11ea-9570-a7b4f01de9d3.png)

**Environment (please complete the following information):**
 - Output of `uname -a` or `ver`: 
Linux vinicius-notebook 5.0.0-37-generic #40~18.04.1-Ubuntu SMP Thu Nov 14 12:06:39 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
 - Output of `java -version`: 
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-20191008104205.buildslave.jdk8u-src-tar--b07)
OpenJDK 64-Bit GraalVM CE 19.2.1 (build 25.232-b07-jvmci-19.2-b03, mixed mode)

 - GraalVM version (if different from Java): 
 - Quarkus version or git rev: 1.1.0.Final

**Additional context**
On my personal project, only logs from io.quarkus.flyway.FlywayProcessor are available on http://localhost:9000/search 

![Captura de tela de 2020-01-06 21-41-39](https://user-images.githubusercontent.com/14058396/71859359-5888a300-30cd-11ea-821f-9e3319274733.png)

--

**Comment by loicmathieu** [comment]
It seems that Graylog didn't correctly create the index in Elasticsearch as the Thread field is of type long but it should be a String.

Can you add to the issue :
- A screenshot of the detail of a working log
- The logs of your application from the console to have them in text

Also, do you have other log configuration option inside `application.properties` ?

Apparently, what happened is that the first message send to Graylog should have a Thread field that Elasticsearch discovers as a long instead of a String.
The automaticaly created index then have a mapping of long for the Thread field and when a String arrives it refuses it. 
I don't know how it can happens but you can find some information about it here: https://community.graylog.org/t/incompatible-index-mappings/5304

**Comment by viniciusfcf** [comment]
1. Started my dockers using: docker-compose -f graylog-docker-compose.yml up -d
1.1 [graylog-docker-compose.txt](https://github.com/quarkusio/quarkus/files/4030682/graylog-docker-compose.txt)
2. elasticsearch log:
[elasticsearch.log](https://github.com/quarkusio/quarkus/files/4030688/elasticsearch.log)
3. graylog mapping:
[elasticsearch-mapping.txt](https://github.com/quarkusio/quarkus/files/4030706/elasticsearch-mapping.txt)
4. Indexer Failures:
![Captura de tela de 2020-01-07 09-51-30](https://user-images.githubusercontent.com/14058396/71896759-5eb16a80-3133-11ea-9b66-9037946c33e7.png)
5. App Log: 
![Captura de tela de 2020-01-07 09-39-52](https://user-images.githubusercontent.com/14058396/71896775-68d36900-3133-11ea-94ae-f0273175eda4.png)

**Comment by loicmathieu** [comment]
So this is really a Graylog issue as your mapping has been created with `long` type instead of `String` and that can happens when the first log event is wrong or during some other Grayog operations: https://community.graylog.org/t/incompatible-index-mappings/5304

To try to understand what happened.

Can you give the content of the Elasticsearch index ?
This curl should do the trick
```
curl -H 'Content-Type: application/json' -X GET https://localhost:9200/graylog_0/_search?pretty
```

Can you provide a screenshot of the detail of a working log message from `io.quarkus.flyway.FlywayProcessor` (click on a log event it will expand) ?

Can you also try to destroy your cluster (or only the elasticsearch index) and try again ? This will create the index again from the first log event that you send to Graylog.

**Comment by viniciusfcf** [comment]
> So this is really a Graylog issue as your mapping has been created with `long` type instead of `String` and that can happens when the first log event is wrong or during some other Grayog operations: https://community.graylog.org/t/incompatible-index-mappings/5304
> 
> To try to understand what happened.
> 
> Can you give the content of the Elasticsearch index ?
> This curl should do the trick
> 
> ```
> curl -H 'Content-Type: application/json' -X GET https://localhost:9200/graylog_0/_search?pretty
> ```
File: 
[elasticsearch-index.txt](https://github.com/quarkusio/quarkus/files/4030976/elasticsearch-index.txt)

> Can you provide a screenshot of the detail of a working log message from `io.quarkus.flyway.FlywayProcessor` (click on a log event it will expand) ?
> 

![Captura de tela de 2020-01-07 12-56-44](https://user-images.githubusercontent.com/14058396/71908973-be1c7400-314d-11ea-825a-3e8a1b25b022.png)
![Captura de tela de 2020-01-07 12-55-48](https://user-images.githubusercontent.com/14058396/71908981-c2489180-314d-11ea-9304-996a8c746069.png)

> Can you also try to destroy your cluster (or only the elasticsearch index) and try again ? This will create the index again from the first log event that you send to Graylog.

Yes, I will do it after I provide you the right details abount FlywayProcessor problem.

**Comment by loicmathieu** [comment]
OK, it's a tricky one! The thread ID is used instead of the ThreadName because the thread that generates the event is no longuer available. It's a build thread.
So packaging the application and initializing the index from it will make the trick (native will also works as we have a substitution).
Or initializing the index from an application that didn't include Flyway as it's the flyway extension that creates log messages during the build, and those log messages generates the wrong index.

@dmlloyd long story short: there is a tricky issue where a log event created by Flyway during the build process in dev mode ends up having the TreadName the same as the ThreadID (in dev mode the substitution is not used so it uses JMX to find the ThreadName from the ID). If I recall correctly, build log events are replayed at runtime in dev mode, at this time the Thread that generates the event is no longuer available. I don't think there is an easy way to workaround the issue other than waiting for https://github.com/mp911de/logstash-gelf/pull/217 ?

**Comment by viniciusfcf** [comment]
After delete the wrong index, all work fine:
![Captura de tela de 2020-01-07 13-52-52](https://user-images.githubusercontent.com/14058396/71912875-19059980-3155-11ea-93ee-2788489594ab.png)
[elasticsearch-index-right.txt](https://github.com/quarkusio/quarkus/files/4031592/elasticsearch-index-right.txt)

**Comment by loicmathieu** [comment]
@viniciusfcf cool, but it remains a workaround as the issue is real.

**Comment by dmlloyd** [comment]
I can't think of another workaround offhand.

**Comment by loicmathieu** [comment]
@gsmet this is a dev mode only issue. It impact only Graylog (Logstash have predefined Elasticsearch templates, not sure for Fluentd) and under certain circumstances only (when a log event is generated during the build phase: this is the case for Flyway for exemple). There is an easy workaround (initialize the Graylog index with a run of the application from a JAR or a native package).

There will be a fix in the `loggin-gelf` library that should be delivered in late January (so it will certainly miss the 1.2 release).

Do you think we can wait untill then ?
Should I add a warning on the documentation guide about this possible issue ?
