### ISSUE TITLE
Panache second-level caching for @ManyToOne relations seem not to be working

### ISSUE THREAD

**Issue by marceloverdijk** [quarkusio/quarkus#6458]
Hi,

As discussed here https://groups.google.com/forum/#!topic/quarkus-dev/lqlQqGSqONs

I'm trying to implement second-level caching with Panache but `@ManyToOne` relations seem not to be cached.

E.g. when having Continent / Country entities likes:

@Entity
@Cacheable
public class Continent extends BasePanacheEntity {

    @Id
    public String id;
    public String code;
    public String name;
}

@Entity
@Cacheable
public class Country extends BasePanacheEntity {

    @Id
    public String id;
    public String alpha2Code;
    public String alpha3Code;
    public String name;

    @ManyToOne(fetch = FetchType.LAZY)
    // Note, also tried adding this: @Cache(usage = CacheConcurrencyStrategy.READ_ONLY)
    @JoinColumn(name = "continent_id")
    public Continent continent;
}

When I the first time query a `Country` and access the `Continent` the following queries are executed (as expected):

2020-01-07 19:01:34,772 DEBUG [com.foo.CountryDataFetcher] (executor-thread-1) Fetching type with id: netherlands
Hibernate: 
    select
        country0_.id as id1_4_0_,
        country0_.alpha2_code as alpha2_4_0_,
        country0_.alpha3_code as alpha3_4_0_,
        country0_.continent_id as continen4_4_0_,
        country0_.name as name5_4_0_ 
    from
        country country0_ 
    where
        country0_.id=?
Hibernate: 
    select
        continent0_.id as id1_3_0_,
        continent0_.code as code2_3_0_,
        continent0_.name as name3_3_0_ 
    from
        continent continent0_ 
    where
        continent0_.id=?

The next time it only executes:

2020-01-07 19:01:36,244 DEBUG [com.foo.CountryDataFetcher] (executor-thread-1) Fetching type with id: netherlands
Hibernate: 
    select
        continent0_.id as id1_3_0_,
        continent0_.code as code2_3_0_,
        continent0_.name as name3_3_0_ 
    from
        continent continent0_ 
    where
        continent0_.id=?

So the `Country` is cached, but the `Continent` not.

I also tried adding `@Cache(usage = CacheConcurrencyStrategy.READ_ONLY)` on the relation but that didn't make any difference.

My cache properties look like:

quarkus:
  hibernate-orm:
    cache:
      "com.foo.domain.Continent":
        expiration:
          max-idle: P365D
        memory:
          object-count: 10
      "com.foo.domain.Country":
        expiration:
          max-idle: P365D
        memory:
          object-count: 300
# Note, also tried adding this but without any effect
      "com.foo.domain.Country#continent":
        expiration:
          max-idle: P365D
        memory:
          object-count: 300

Maybe I'm doing something wrong or can these relations not be cached this way?
When I query the `Continent` directly as root object, then it is cached when I again query the same `Continent` as root object btw. But via the `Country` it still does the query.

I basically want to cache a lot of these kind of entities as they simple static reference data.
And many other entities refer to these entities, I don't want to either re-fetch them every time, nor use eager fetching.

**Comment by marceloverdijk** [comment]
@Sanne, I have created this sample https://github.com/marceloverdijk/quarkus-hibernate-caching
See the README.md for details.

**Comment by marceloverdijk** [comment]
@Sanne I also created a similar Spring Boot variant [here](https://github.com/marceloverdijk/spring-boot-hibernate-caching) and there the Hibernate second-level caching works as expected.

Do note that I had to add the `@org.hibernate.annotations.Cache` annotation on class level (for both `Continent` and `Country` to get it working.
I also added these to the Panache entities in my Quarkus demo project but there the `Continent` relation is re-queried from the database every time.

**Comment by marceloverdijk** [comment]
@Sanne is this something to be considered for `1.2`?

**Comment by Sanne** [comment]
I'm afraid it might be too late. Personally I'm travelling and couldn't
check this out yet, while the deadline for 1.2 is in just days..

**Comment by rsvoboda** [comment]
@Sanne, did you have chance to look into this area ?

**Comment by marceloverdijk** [comment]
Any update on this one? Probably won't make it in `1.4`? Will it be planned for ` 1.5` ?

**Comment by Sanne** [comment]
I'm sorry I couldn't look yet.  Promised some other reviews, but will try to check this out next.

**Comment by Sanne** [comment]
Apologies for the delay! Lockdown is severly affecting my IDE -able time :/

I started to look again; first thing I figured is that converting the project from not using Panache-enhanced entities but just a plain `EntityManager` it works fine.

**Comment by marceloverdijk** [comment]
No need to apologise @Sanne.  I'm anyway happy you are looking into it again. Staf safe and healthy!

**Comment by Sanne** [comment]
So the problem is that "Enhanced Proxies": it's a new feature in Hibernate ORM, which is enabled in Quarkus.

It seems to consistently bypasss the 2LC in `org.hibernate.persister.entity.AbstractEntityPersister#initializeEnhancedEntityUsedAsProxy`.  Since the specific trigger is a field read operation triggering the lazy load I wasn't seeing this in a vanilla ORM test - as the field read fashion is Panache specific. I'll see to get a fix in ORM.

**Comment by marceloverdijk** [comment]
Ths for sharing @Sanne! Good to know where the problem exists. Should we reference the Hibernate issue here so we can follow the progress?

**Comment by Sanne** [comment]
Right, I just wanted to be sure first. Now it's a confirmed problem and I'm working on a fix:
 - https://hibernate.atlassian.net/browse/HHH-14004

**Comment by marceloverdijk** [comment]
@Sanne This was introduced in Hibernate `5.4.14`? That could explain why it was working correctly in Spring project. Probably that version of Spring Boot was using another Hibernate version.

**Comment by Sanne** [comment]
> @Sanne This was introduced in Hibernate `5.4.14`? That could explain why it was working correctly in Spring project. Probably that version of Spring Boot was using another Hibernate version.

sorry, I missed the question. No the feature was introduced approximatley a year ago, but it needs to be enabled explicitly.

Let me share a bit of context.

While tuning is interesting, over the years Hibernate ORM has grown a massive amount of configuration properties; this is becoming not only a usability pain but also a maintenance problem as we need to test various features in combination with each others permutations. I'm therefore figthing hard to try reducing configuration knobs :)

Most often we introduce new features together with a kill switch for backwards compatibility reasons; sometimes to keep a novel experimental new idea from causing too many problems it will be turned off by default, unless you know the magic properties to set..

In Quarkus we can do higher automation of configuration because of the application analysis phase, and because of it being in the lucky position currently of focusing on new applications, we have the luxury to enable really cool stuff by default - and remove/hide the configuration knobs.

`Enhanced Proxies` is one such thing; it's now enabled by default in Quarkus as it has no drawbacks - other than being relatively less tested code, like you noticed.

In such cases though I prefer digging and fixing the problem rather than giving people the configuration property to turn it off; it's a battle to make sure the whole platform will work fine with least trouble, all pieces combined properly.

I hope that makes sense!

HHH-14004 was fixed; I'll leave this issue open as we need to release it and upgrade Quarkus.

**Comment by Sanne** [comment]
For reference, this is the feature:
 - https://in.relation.to/2019/07/30/bytecode-proxy/

It's transparently enabled in Quarkus, especially as people don't need to do anything to setup bytecode enhancement of entities at build time.

**Comment by marceloverdijk** [comment]
Np and thanks for the explanation @Sanne !

**Comment by rsvoboda** [comment]
@Sanne this looks pretty important, PR fixing this is component update, no test coverage on Quarkus side. I looked a bit to HHH side and found https://github.com/hibernate/hibernate-orm/commit/d96a6dc474b4764bbdd574e0d0cbd555c29941fe for test coverage.

Are there any specifics of Quarkus which would require test coverage here or it's fine to have coverage in Hibernate test-suite?

**Comment by Sanne** [comment]
I'd try to live with the Hibernate upstream tests as much as possible - there's no specific here other than Quarkus using that feature.

**Comment by rsvoboda** [comment]
Ok, thanks for confirmation
