### ISSUE TITLE
Add configuration converter for List<XYZ> or XYZ[]

### ISSUE THREAD

**Issue by hartimcwildfly** [quarkusio/quarkus#6628]
In some configs we use Map<String, XYZ> but we do not need the key of the map entry.
E.g. in the elytron ldap extension we have the following lines:
```
quarkus.security.ldap.identity-mapping.attribute-mappings."0".from=cn
quarkus.security.ldap.identity-mapping.attribute-mappings."0".filter=(member=uid={0})
quarkus.security.ldap.identity-mapping.attribute-mappings."0".filter-base-dn=ou=roles,ou=tool,o=YourCompany,c=DE
```
but using 
```
quarkus.security.ldap.identity-mapping.attribute-mappings.[0].from=cn
quarkus.security.ldap.identity-mapping.attribute-mappings.[0].filter=(member=uid={0})
quarkus.security.ldap.identity-mapping.attribute-mappings.[0].filter-base-dn=ou=roles,ou=tool,o=YourCompany,c=DE
```
would be sufficient.

**Comment by dmlloyd** [comment]
In general, using (sparse) arrays/lists in config in this way works out very poorly.  The user has no means to insert or remove values in higher priority configuration sources.  The configuration system can't easily probe the number of elements.

I would recommend named items for this case, like this:

```properties
# ...
quarkus.security.ldap.identity-mapping.attribute-mappings=myCnMapping,anotherMapping
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.from=cn
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.filter=(member=uid={0})
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.filter-base-dn=ou=roles,ou=tool,o=YourCompany,c=DE
# ...
```

This way each item can be specified, and the final list of items to use (and their order) can be established from a single property.

Alternatively, if the item list is particularly unpalatable, then an alternative would be for each named item to include a `priority` value and `enabled` flag like this:

```properties
# ...
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.enabled=true # the user doesn't actually have to specify this though; it would be the default
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.priority=100
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.from=cn
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.filter=(member=uid={0})
quarkus.security.ldap.identity-mapping.attribute-mappings.myCnMapping.filter-base-dn=ou=roles,ou=tool,o=YourCompany,c=DE
# ...
```

In this case you'd filter and sort the values before using them.  You'd need a policy for handling priority conflicts (e.g. reject it by printing an error message).  By putting ordering information in the value instead of the key, the user can easily override it.  By having an explicit name for each subconfiguration, you allow diagnostic messages to reference the items by name.

Does this make sense?

**Comment by radcortez** [comment]
This is already supported: https://quarkus.io/guides/config-reference#indexed-properties
