### ISSUE TITLE
Fetching credentials from Vault KV v2 fails

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#6739]
**Describe the bug**

I am trying to fetch credentials for DB from Vault KV v2 instead of v1.

I am executing the next Vault commands:

```
vault kv put secret/myapps/vault-service/db password=alex

cat <<EOF | vault policy write vault-service-policy -
path "secret/data/myapps/vault-service/*" {
  capabilities = ["read"]
}
EOF

vault auth enable userpass
vault write auth/userpass/users/alex password=alex policies=vault-service-policy
```

Then if I do  a `vault login ....` I can retrieve correctly the `secret/myapps/vault-service/db` but when I configure Quarkus to fetch the credentials to configure the datasource then I got:

```
Caused by: io.quarkus.vault.runtime.client.VaultClientException code=403 body={"errors":["1 error occurred:\n\t* permission denied\n\n"]}

	at io.quarkus.vault.runtime.client.OkHttpVaultClient.throwVaultException(OkHttpVaultClient.java:146)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.exec(OkHttpVaultClient.java:130)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.get(OkHttpVaultClient.java:124)
	at io.quarkus.vault.runtime.client.OkHttpVaultClient.getSecretV1(OkHttpVaultClient.java:74)
	at io.quarkus.vault.runtime.VaultKvManager.readSecret(VaultKvManager.java:28)
	at io.quarkus.vault.runtime.VaultCredentialsProvider.getCredentials(VaultCredentialsProvider.java:37)
	at io.quarkus.vault.runtime.VaultServiceProducer_ProducerMethod_createCredentialsProvider_760efe06b6852169ee62572bb780e1c741813f4b_ClientProxy.getCredentials(VaultServiceProducer_ProducerMethod_createCredentialsProvider_760efe06b6852169ee62572bb780e1c741813f4b_ClientProxy.zig:43)
```

If I run the same example but using the KV v1 then it works correctly.

Also if I change the `kv-path` to `secret/myapps/vault-service/db` I got: 

```
Caused by: io.quarkus.vault.VaultException: com.fasterxml.jackson.databind.exc.MismatchedInputException: Cannot deserialize instance of `java.lang.String` out of START_OBJECT token
 at [Source: (String)"{"request_id":"c4dda670-6886-15af-3867-fe70ae5fa676","lease_id":"","renewable":false,"lease_duration":0,"data":{"data":{"password":"alex"},"metadata":{"created_time":"2020-01-23T09:00:02.438243752Z","deletion_time":"","destroyed":false,"version":1}},"wrap_info":null,"warnings":null,"auth":null}
"; line: 1, column: 120] (through reference chain: io.quarkus.vault.runtime.client.dto.VaultKvSecretV1["data"]->java.util.LinkedHashMap["data"])
```

**Expected behavior**

KV v2 should work as v1

**Actual behavior**

Exception is thrown.

**Configuration**
```properties

quarkus.datasource.url=jdbc:postgresql://localhost:5432/mydatabase
quarkus.datasource.driver=org.postgresql.Driver
quarkus.datasource.username=alex
# <1>
quarkus.vault.credentials-provider.mydatabase.kv-path=myapps/vault-service/db
# <2>
quarkus.datasource.credentials-provider=mydatabase
# <3>
quarkus.vault.url=http://localhost:8200
quarkus.vault.authentication.userpass.username=alex
quarkus.vault.authentication.userpass.password=alex
```

To reproduce just follow the instructions of the guide but using KV v2 instead of KV v1.

cc// @vsevel

**Comment by sberyozkin** [comment]
Hi @lordofthejars looks like you need to set [this property](https://github.com/quarkusio/quarkus/blob/master/extensions/vault/runtime/src/main/java/io/quarkus/vault/runtime/config/VaultRuntimeConfig.java#L149), can you try please ?

**Comment by lordofthejars** [comment]
Ok it worked, thank you very much, my question now is: if default Vault  KV version is V2, why in Quarkus extension is v1?

**Comment by sberyozkin** [comment]
@lordofthejars great, thanks for a check. I don't know, sorry. But I agree the default one should be used. Perhaps we can switch it for `1.3.0` ? Please create a PR and CC Vincent as well. We can mention it in the release notes for 1.3.0

**Comment by vsevel** [comment]
> Hi @lordofthejars looks like you need to set this property as it affects this branch, can you try please ?

when working with kv v2, [kv-secret-engine-version](https://quarkus.io/guides/vault#quarkus-vault_quarkus.vault.kv-secret-engine-version) needs to be `2` (1 by default)

> Ok it worked, thank you very much, my question now is: if default Vault KV version is V2, why in Quarkus extension is v1?

@lordofthejars I defaulted to v1 in the config because when you enable the kv secret engine with no params, you end up with a v1 kv secret engine.

for instance try this on an unsealed vault:
```
vault secrets enable kv
vault secrets enable -version=1 -path=secret1 kv
vault secrets enable -version=2 -path=secret2 kv
```
you should get:
```
$ vault secrets list
Path          Type         Accessor              Description
----          ----         --------              -----------
cubbyhole/    cubbyhole    cubbyhole_88810ab0    per-token private secret storage
identity/     identity     identity_5cd81d3f     identity store
kv/           kv           kv_c2df76d2           n/a
secret1/      kv           kv_c3e029d4           n/a
secret2/      kv           kv_4d0f3bd1           n/a
```
now let's put some secrets in:
```
$ vault kv put kv/my-secret my-value=s3cr3t
Success! Data written to: kv/my-secret

$ vault kv put secret1/my-secret my-value=s3cr3t
Success! Data written to: secret1/my-secret

$ vault kv put secret2/my-secret my-value=s3cr3t
Key              Value
---              -----
created_time     2020-01-23T16:15:51.5202657Z
deletion_time    n/a
destroyed        false
version          1
```
you see that the output on the last command is different because it is versioned.
this means that the kv secret engine mounted at the default path `kv/` is a v1.

to make it more confusing, the default kv secret engine that is automatically created when working in dev mode is actually a v2 mounted at path `secret/`:
```
docker run --rm --cap-add=IPC_LOCK -e VAULT_ADDR=http://localhost:8200 -p 8200:8200 -d --name=dev-vault vault:1.2.2
```

so the version and the mount path are both different in those 2 use cases.
in quarkus, I ended up favoring v1 for the version (because it is what you get when you enable the engine with no `-version` arg) and `secret/` for the mount path, which is I think the historical default (I believe that in the old version, the kv secret engine did not need to be enabled; it would be created automatically by default at init time)

it would have been nice to have vault to be consistent about defaults.

now if you think something is more natural, we can definitely change the defaults (with a note on the breaking change in the release notes).

this subject was indirectly addressed in the [vault guide ](https://quarkus.io/guides/vault):
```
For simplicity reasons, we are going to use a kv secret engine version 1 (which is the default) mounted at path secret instead of the pre-configured kv version 2 available in dev mode
...
```

cc @sberyozkin

**Comment by sberyozkin** [comment]
Hi @vsevel - thanks for the informative feedback. Perhaps then a doc clarification can help, Alex @lordofthejars, would that work for you ?

**Comment by gsmet** [comment]
If v2 is the currently supported version (and not something experimental), my inclination would be to use v2, even if it requires some specific parameters.

**Comment by vsevel** [comment]
to summarize, right now we have:

 - `vault secrets enable kv`
   - version = 1
   - mount path = kv
 - dev mode
   - version = 2
   - mount path = secret
 - quarkus defaults
   - version = 1
   - mount path = secret

so we are talking about:
 - quarkus defaults
   - version = **2**
   - mount path = secret or kv? => I suggest keeping `secret` because that is what the examples are all showing in the different pages googled with keywords `vault tutorial policy`

so essentially we align with dev mode.
this will have the extra benefit of simpliying the vault guide, except for the policies that will need to include the `/data` element, as explained in the [hashicorp vault guide](https://www.vaultproject.io/docs/secrets/kv/kv-v2/#acl-rules).
and as said before we will need to get people's attention in the release nodes.

@gsmet @sberyozkin @lordofthejars everybody is fine with that change?
if so I will find time in feb. to deal with this.

**Comment by sberyozkin** [comment]
@vsevel thanks, makes sense IMHO
