### ISSUE TITLE
When using kotlin with mongo panache, the deserializer fails unless all the constructor parameters are declared as nullable or have a default value

### ISSUE THREAD

**Issue by TheVidAllMayThe** [quarkusio/quarkus#6742]
The title is pretty much self explanatory. When using a kotlin class that extends PanacheMongoEntity unless the fields are declared as nullable or have default values the deserialization when doing any find operation (e.g. listAll()) fails with the following error:
```
Caused by: org.bson.codecs.configuration.CodecConfigurationException: Cannot find a public constructor for 'ChargingInterval'.
	at org.bson.codecs.pojo.CreatorExecutable.checkHasAnExecutable(CreatorExecutable.java:140)
	at org.bson.codecs.pojo.CreatorExecutable.getInstance(CreatorExecutable.java:107)
	at org.bson.codecs.pojo.InstanceCreatorImpl.<init>(InstanceCreatorImpl.java:40)
	at org.bson.codecs.pojo.InstanceCreatorFactoryImpl.create(InstanceCreatorFactoryImpl.java:28)
	at org.bson.codecs.pojo.ClassModel.getInstanceCreator(ClassModel.java:71)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:120)
	at org.bson.codecs.pojo.PojoCodecImpl.decode(PojoCodecImpl.java:125)
	at org.bson.codecs.pojo.AutomaticPojoCodec.decode(AutomaticPojoCodec.java:37)
```

Sample failing class:
```
package io.biapower.services.chargingsessionservice.domain
import io.quarkus.mongodb.panache.PanacheMongoEntity
import java.time.Instant

data class SampleDataClass(
        var start: Instant = Instant.now(),
        var end: Instant,
        var num: Int = 0f
): PanacheMongoEntity()
```

Sample working class:
```
package io.biapower.services.chargingsessionservice.domain
import io.quarkus.mongodb.panache.PanacheMongoEntity
import java.time.Instant

data class SampleDataClass(
        var start: Instant = Instant.now(),
        var end: Instant = Instant.now(),
        var num: Int = 0
): PanacheMongoEntity()
```
or:
```
package io.biapower.services.chargingsessionservice.domain
import io.quarkus.mongodb.panache.PanacheMongoEntity
import java.time.Instant

data class SampleDataClass(
        var start: Instant = Instant.now(),
        var end: Instant? = null,
        var num: Int = 0
): PanacheMongoEntity()
```

**Comment by gsmet** [comment]
Thanks for the report! Could you create a small reproducer?

**Comment by geoand** [comment]
Like @gsmet says, a reproducer will go a long way to fix this. I am pretty sure I know what this is all about, but I would like to have a reproducer to make sure

**Comment by TheVidAllMayThe** [comment]
Turns out that declaring the fields as nullables is not enough, they have to have a mandatory default value (for nullable fields should be null). I'm attaching a small example. It has three endpoints:

localhost:8080/test-fail
localhost:8080/test-work1
localhost:8080/test-work2

[kotlin-mongo-error.zip](https://github.com/quarkusio/quarkus/files/4102911/kotlin-mongo-error.zip)

**Comment by geoand** [comment]
OK, this isn't what I thought (I thought the problem was in native mode). 
So I'll leave it to @loicmathieu but feel free to ping me if you want me to investigate

**Comment by loicmathieu** [comment]
@TheVidAllMayThe Kotlin data classes didn't have a default empty constructor, maybe this is where the issue comes from.

Can you try to add `@BsonCreator` to the Kotlin dataclass declaration to tell MongoDB to use the generated constructor ? 
https://mongodb.github.io/mongo-java-driver/3.12/bson/pojos/#annotations

I didn't find a lot of documentation about MongoDB and Kotlin, maybe we will need some extension functions to make it works ...

**Comment by TheVidAllMayThe** [comment]
@loicmathieu It didn't work.

```
data class SampleFailingDataClass @BsonCreator constructor (
        var sampleString: String = "",
        var sampleInteger: Int
): PanacheMongoEntity()
```
fails with:

```
2020-01-24 10:22:35,502 WARN  [org.bso.cod.pojo] (executor-thread-1) Cannot use 'SampleFailingDataClass' with the PojoCodec.: org.bson.codecs.configuration.CodecConfigurationException: Invalid @BsonCreator constructor in SampleFailingDataClass. All parameters in the @BsonCreator method / constructor must be annotated with a @BsonProperty.
	at org.bson.codecs.pojo.CreatorExecutable.getError(CreatorExecutable.java:145)
	at org.bson.codecs.pojo.CreatorExecutable.getError(CreatorExecutable.java:135)
	at 
.
.
.
```

and

```
data class SampleFailingDataClass @BsonCreator constructor (
        @BsonProperty var sampleString: String = "",
        @BsonProperty var sampleInteger: Int
): PanacheMongoEntity()
```

fails with:
```
2020-01-24 10:24:17,966 WARN  [org.bso.cod.pojo] (executor-thread-1) Cannot use 'SampleFailingDataClass' with the PojoCodec.: org.bson.codecs.configuration.CodecConfigurationException: Invalid @BsonCreator constructor in SampleFailingDataClass. Invalid Property type for ''. Expected class java.lang.String, found int.
	at org.bson.codecs.pojo.CreatorExecutable.getError(CreatorExecutable.java:145)
	at org.bson.codecs.pojo.CreatorExecutable.getError(CreatorExecutable.java:135)
	at org.bson.codecs.pojo.ConventionAnnotationImpl.processCreatorAnnotation(ConventionAnnotationImpl.java:194)
.
.
.
```

**Comment by TheVidAllMayThe** [comment]
> @TheVidAllMayThe Kotlin data classes didn't have a default empty constructor, maybe this is where the issue comes from.

And btw, I can confirm that the same issue happens with regular classes

**Comment by loicmathieu** [comment]
@TheVidAllMayThe the issue is with the MongoDB PojoCodec that we are using and Kotlin classes / dataclasses.

Maybe you can ask for help on the MongoDB community. It shold be reproducible without Quarkus ...

Meanwhile, you can create a codec for this class, we will automatically register it : https://quarkus.io/guides/mongodb#simplifying-mongodb-client-usage-using-bson-codec

I agree we need to do something to facilitate the usage of Kotlin with MongoDB with Panache, I will try to investigate more on it (but in two weeks from now at the earliest). Maybe @geoand have some idea on it also ?

**Comment by geoand** [comment]
I would also have to investigate to see what might be going on since I don't have any ideas off hand.

But same for me, I won't have enough spare time soon...

**Comment by loicmathieu** [comment]
@TheVidAllMayThe this is not a Quarkus MongoDB with Panache issue but it's a limitation of Kotlin dataclass with frameworks that needs an empty constructor. We use MongoDB automatic pojo codec to serialize to/from the database and it needs an empty constructor.

There is multiple way to fix the issue:

1. Add default values to all the field of your data class to generates an empty constructor. See this sentence from the Kotlin documentation :
> On the JVM, if the generated class needs to have a parameterless constructor, default values for all properties have to be specified (see Constructors).

2. Create a BSON Codec, it will be automatically registered by Quarkus and will be used instead of the automatic pojo codec: https://quarkus.io/guides/mongodb#simplifying-mongodb-client-usage-using-bson-codec

3. Use the `@BsonCreator` annotation to tell the MongoDB automatic pojo codec to use the Kotlin dataclass default constructor, in this case all fields needs to be annotated with `@BsonProperty`: https://mongodb.github.io/mongo-java-driver/3.12/bson/pojos/#supporting-pojos-without-no-args-constructors

Updating the `SampleFailingDataClass` with the `@BsonCreator` annotation make the sample application working.

```
data class SampleFailingDataClass @BsonCreator constructor (
        @BsonProperty("sampleString") var sampleString: String = "",
        @BsonProperty("sampleInteger") var sampleInteger: Int
): PanacheMongoEntity()
```

If it's OK, I propose to add a section on the MongoDB with Panache guide explaining how to use Kotlin dataclass with the MongoDB automatic pojo codec.

**Comment by TheVidAllMayThe** [comment]
@loicmathieu Thanks for the suggestions! The section in the guide would certainly be helpful!

**Comment by loicmathieu** [comment]
@TheVidAllMayThe when writing the documentation part (#6877 ) two questions arises. If you can try the following and provide feedback this would be great :

- Is the `@BsonCreator` approach works in native mode ?
- Did you try the Kotlin `no-arg` compiler plugin instead of using the `@BsonCreator`

**Comment by loicmathieu** [comment]
@gsmet @TheVidAllMayThe using the `no-arg` compiler plugin and the not mandatory `@MongoEntity` annotation (as the compiler plugin needs an anotation to target classes that needs a no-arg constructor) it works.

```kotlin
@MongoEntity
data class SampleFailingDataClass (
        var sampleString: String = "",
        var sampleInteger: Int
): PanacheMongoEntity()
```

I tested native mode and it works for both approach.

I will update the guide acordingly and close this issue.

**Comment by TheVidAllMayThe** [comment]
@loicmathieu Thank you so much. I've been meaning to try it out, but I've been pretty swamped. Glad to see that it works!
