### ISSUE TITLE
Log a warning if a user attempts to set a build-time property at runtime

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6823]
Current state: it's a no-op if a user attempts to set a build-time property by a system property or an env variable.

We should probably log a warning if a user attempts to set a quarkus BUILD_TIME property at runtime. The impl could be straightforward: (1) store the names of all build-time props in the generated config class and (2) when the app starts iterate over all quarkus-related system properties and env variables and log a warning for each match.

@dmlloyd @emmanuelbernard WDYT?

**Comment by dmlloyd** [comment]
The reason we did not do this is that the `application.properties` (including build properties) ends up in the application one way or another, and the build time property values are recorded as defaults.  So you'd always get a warning (because the properties are always present), unless the implementation were to only warn when the value is different than the expected value.

Since we record all the build time values for use as defaults, we could theoretically do it this way.

**Comment by mkouba** [comment]
Well, I was thinking of a pretty simple solution - just iterate over all system properties and env variables and iff they're from the quarkus namespace (`quarkus.` and `QUARKUS_`) and the property name matches a build-time property name (e.g. `-Dquarkus.datasource.health.enabled=false`) -> WARNING. Of course, this assumes that it's easy to obtain a list of built-time properties...

BTW it seems that https://quarkus.io/guides/all-config does not state whether the property could be overriden at runtime. @FroMage I believe that we should add this info?

**Comment by FroMage** [comment]
> BTW it seems that https://quarkus.io/guides/all-config does not state whether the property could be overriden at runtime. @FroMage I believe that we should add this info?

Do we have any build-time property that can be overriden at run-time? We already mark build/run properties (they have a different icon).

**Comment by mkouba** [comment]
@FroMage aha, I see. Well, I did not notice there is a different icon at all! And of course, a build-time property cannot be overriden at runtime...

**Comment by radcortez** [comment]
This was added in https://github.com/quarkusio/quarkus/pull/13154.
