### ISSUE TITLE
Document how to enable DEBUG logging for @QuarkusTest

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6831]
I've tried to set system properties in `applications.properties` and for the `maven-surefire-plugin` with no success.

**Comment by marc-christian-schulze** [comment]
Since it took me quiet a while to figure out how to configure the logging properly, here's how it works - at least for me ;)

First, configure your logging as described in the [Quarkus documentation](https://quarkus.io/guides/logging) inside your `src/main/resources/application.properties` file. This should already work, iff you start your packaged Quarkus application (jar or native-image).

However, when running a QuarkusTest you'll notice that your logging configuration is not picked up. To do so you need to configure your testing plugin for Maven or Gradle properly.

Maven (already [documented by Quarkus](https://quarkus.io/guides/getting-started-testing)):
```
<plugin>
    <artifactId>maven-surefire-plugin</artifactId>
    <version>${surefire-plugin.version}</version>
    <configuration>
       <systemProperties>
          <java.util.logging.manager>org.jboss.logmanager.LogManager</java.util.logging.manager>
       </systemProperties>
    </configuration>
</plugin>
```

Gradle (not (yet) documented by Quarkus):
```
test {
    systemProperty 'java.util.logging.manager', 'org.jboss.logmanager.LogManager'
}
```

**Comment by mkouba** [comment]
@marc-christian-schulze Thanks for you comment! I'll try it once again and if it works I'll send a PR with docs update.
