### ISSUE TITLE
ClassCastException in Qute BuiltinTemplateExtensions.map on a TreeMap with {#for entry in map.entrySet}

### ISSUE THREAD

**Issue by Maldivia** [quarkusio/quarkus#6870]
**Describe the bug**
BuiltinTemplateExtensions.map() tries to call map.get(String), which is not safe for a TreeMap with a Comparator, as it will try to cast the String to the expected type for the Comparator.
This results in an Internal Server Error due to ClassCastException.

**Expected behavior**
doing {#for entry in map.entrySet} should work equally well for a HashMap and a TreeMap (only the iteration order should differ).

**Actual behavior**
With a HashMap, {#for entry in map.entrySet} works as expected.
With a TreeMap (where key type is NOT a String), this results in an Internal Server Error due to ClassCastException.

**To Reproduce**
See gist for simple example of foo.html template and a FooResource.java class, and the output thereof
https://gist.github.com/Maldivia/de383ef75d2f29061aadcb4a1913754e

**Environment (please complete the following information):**
 - Quarkus version: 1.2.0.Final
 - Output of `java -version`: openjdk version "11.0.4" 2019-07-16

**Comment by gsmet** [comment]
@mkouba any progress on this one?

**Comment by mkouba** [comment]
So the problem here is that whenever we find an identifier that resolves to a map we do consider the next part of the expression a map key and try to lookup the value. Which of course does not make sense for `map.entrySet` but is very useful in many other use cases.

The optional restriction of `TreeMap` is something we didn't think about. We could catch the `ClassCastException`. It's quite ugly but I can't think of a better solution... WDYT?

**Comment by gsmet** [comment]
Can't you special case `entrySet`? (I haven't looked at the code)

**Comment by gsmet** [comment]
That being said, I wonder if the feature itself is a good idea.

**Comment by mkouba** [comment]
> Can't you special case entrySet? (I haven't looked at the code)

We could but the strategy is to always try `get()` before the special cases.

> That being said, I wonder if the feature itself is a good idea.

Well, the idea comes from the mustache/javascript world where an object is basically a collection of name-value pairs (speaking of properties). I personally like it because `Map.get()` is 90% what users do when working with maps in templates and so it's quite convenient.

**Comment by mkouba** [comment]
I've decided to align `BuiltinTemplateExtensions.map()` with `ValueResolvers.mapResolver()`, ie. add a special case for `entrySet()` and try `get()` last.
