### ISSUE TITLE
OIDC now always delegates to a thread pool

### ISSUE THREAD

**Issue by stuartwdouglas** [quarkusio/quarkus#6950]
Since the multi tenacy changes OIDC will now always delegate to a blocking thread pool:

https://github.com/quarkusio/quarkus/blob/3c2cb0d8afd39e60f5dfc1fe601a75f32f2a8b0b/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcIdentityProvider.java#L41

This has a negative performance impact, this should only delegate if required.

**Comment by pedroigor** [comment]
@stuartwdouglas We can fix that by checking whether or not the application is producing its own tenant configuration.

The reason why a thread pool is being used is that the configuration can be built in a blocking way.

**Comment by sberyozkin** [comment]
@pedroigor Do you mean `TenantConfigResolver` ?

**Comment by pedroigor** [comment]
@sberyozkin both `TenantConfigResolver` and `TenantResolver`.

**Comment by sberyozkin** [comment]
@pedroigor Thanks, with `TenantResolver`, `OAuth2Auth` have already been precalculated in the recorder per each tenant configuration available in the `application.properties`, and since the only thing that `TenantResolver` does is getting a tenant id out of `RoutingContext`, I'd say it is safe enough to relax around `TenantResolver` and only block if `TenantConfigResolver` is used.
What do you think ?
(We can also consider tweaking `TenantConfigResolver` now before it has been documented ?)

**Comment by pedroigor** [comment]
It is fine to check `TenantConfigResolver` only. I was more concerned about corner cases where the `TenantResolver` could potentially perform a more costly operation even though it just resolves the tenant identifier (e.g.: due to unknown reasons invoke some service to decide the tenant, etc).

Could you elaborate more about tweaking `TenantConfigResolver` ?

**Comment by sberyozkin** [comment]
@pedroigor Sure, see what you mean. I suppose it is more likely to happen with `TenantConfigResolver` which would load the config from DB...If we ever have a case of `TenantResolver` attempting to do something costly then we can always say that in this case you have to use `TenantConfigResolver`. We can even update `TenantResolver` javadocs now and say that `this provider must be non-blocking and only use RoutingContext to get the tenant id, TenantConfigResolver should be used if the tenant or configuration resolution is blocking`, something like that (unless TenantConfigResolver is made unblocking too)

> Could you elaborate more about tweaking TenantConfigResolver ?
Have it return `CompletableFuture<OidcTenantConfig>` ?

**Comment by pedroigor** [comment]
All makes sense. Will update things accordingly.

**Comment by pedroigor** [comment]
@sberyozkin Btw, in regards to changing `CompletableFuture<OidcTenantConfig>` from the main resolver. We only have access to `AuthenticationRequestContext.runBlocking(Supplier<SecurityIdentity> function)` so that we can run any blocking code. We need to do it differently, I would just add a `isBlocking` method to the `DefaultTenantConfigResolver` and check it when authenticating from `OidcIdentityProvider`.

Or do you see any other better option ?

**Comment by sberyozkin** [comment]
@pedroigor `DefaultTenantConfigResolver.isBlocking` makes sense :-)
