### ISSUE TITLE
Improve io.quarkus.arc.impl.Reflections.findX() performance

### ISSUE THREAD

**Issue by mkouba** [quarkusio/quarkus#6959]
As described in https://github.com/quarkusio/quarkus/pull/6922:

At runtime we need to find an appropriate `java.lang.reflect` construct for intercepted beans and beans with an injection point that resolves to a dependent bean that injects `InjectionPoint` metadata. The current implementation demonstrates a poor performance for class hierarchies where we need to iterate over subclasses and `NoSuchFieldException`/`NoSuchMethodException` exceptions are currently thrown.

A typical use case is a `@RequestScoped` resource with `@Transactional` and/or injecting `@ConfigProperty`.

Note that we canot get rid of the reflection because of interceptors API, e.g. `javax.interceptor.InvocationContext.getMethod()`.

We should consider two solutions:
1. Use caching
2. Switch to `Class.getDeclaredFields()` + iteration.

**Comment by gsmet** [comment]
Wouldn't you be able to resolve all this at bootstrap? At least populate a cache of what's needed?

**Comment by mkouba** [comment]
Do you mean inside the STATIC_INIT?

**Comment by gsmet** [comment]
Well, Paul was reporting the issue was at pure runtime so that we were still invoking this stuff when requesting the REST endpoints.

I would have thought that we could avoid doing that and collect all these informations when bootstrapping, be it at static init or runtime init (the former being better but if not possible we can live with it).

**Comment by mkouba** [comment]
> we were still invoking this stuff when requesting the REST endpoints

Yes, we do for `@RequestScoped` resources.

> I would have thought that we could avoid doing that and collect all these informations...

We could but I'd rather prefer the caching approach because some of the `java.lang.reflect` constructs don't have to be used at all, e.g. if you declare a resource that is never invoked.

Also collecting such info would be probably more complex and so we should probably try to optimize this (= collect the metadata during STATIC_INIT) post 1.3.

**Comment by nimo23** [comment]
Using` java.lang.invoke.MethodHandle/MethodType` instead of` java.lang.reflect `brings some performance benefits. Other approaches like https://github.com/Hervian/lambda-factory are based on `java.lang.invoke.LambdaMetafactory` **which are a lot faster than MethodHandle** (benchmark with example: https://www.optaplanner.org/blog/2018/01/09/JavaReflectionButMuchFaster.html).

However, creating those things at build time would be the fastest solution..

**Comment by nimo23** [comment]
@mkouba Would be nice if quarkus provides a layer (reflection utils) on top of `LambdaMetafactory` to handle all its reflections through this layer instead of `java.lang.reflect`.

**Comment by mkouba** [comment]
We can't use `MethodHandle` because it's not supported in GraalVM/substrateVM. 

Also we usually don't use the `java.lang.reflect` constructs to invoke methods but merely to allow users to access some parts of the interceptors/CDI API (see `InvocationContext.getMethod()` in the description).
