### ISSUE TITLE
Add health check for Vault

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#7007]
**Description**

Add health check for Vault.

**Implementation ideas**

Create a readiness health check that checks if Vault is up and running.

(I can provide a PR as I have implemented for my project)

**Comment by sberyozkin** [comment]
@lordofthejars Hi, do you think of integrating it with MP Health too ?

**Comment by lordofthejars** [comment]
Yes as the other quarkus extensions

**Comment by vsevel** [comment]
when config is retrieved from vault through the vault config source, it sounds to me that the application startup would actually fail (and crash the app) before the readiness check would be able to kick in I would think.
accepting to start without the vault means that the app should be able to do without its secrets for a little while until vault gets available, then fetch its secrets and become ready.
this puts some expectations on all modules that require secrets, such as the agroal datasource. in this case I am not 100% sure it is actually works. and I would not bet on it generally speaking.
so a default (may be better) option is to the app fail and get restarted by the orchestrator (e.g. k8s).
what do you think?
cc @sberyozkin

**Comment by lordofthejars** [comment]
Yes that's true but notice that readiness probe is called periodically not just at the beginning and if it fails K8s stops sending traffic to this instance. As you set at the beginning if there is no Vault the starting application will fail before the readiness probe, but what's happening if a user is using a dynamic secret? The secret is changed periodically so it means that the application must reconfigure periodically, if Vault is down (or not reachable from the pod) then this might lead to an application error (username or password is not valid but the app couldn't refresh it)then maybe it is better that k8s stops sending traffic to that instance as it might get some errors because of Vault access. Or the same if user configures a cache time for secrets (using Quarkus property) and the app need to refresh these values but no Vault instance is running.

So my point here is that it is not about starting time but also during running time that the error might occur.

Of course, I might be missing something.

**Comment by sberyozkin** [comment]
Hi @lordofthejars @vsevel, in OIDC we added a [connection delay property](https://github.com/quarkusio/quarkus/blob/master/extensions/oidc/runtime/src/main/java/io/quarkus/oidc/runtime/OidcRecorder.java#L82) to make sure that `OIDC` is not available then the extension will keep trying connecting to it for up to 2 mins.
Perhaps that can be done for the `Vault` extension to avoid some uncertainties ?

IMHO it would be interesting to start with integrating Vault with the rest of Quarkus Health Checks ecosystem :-) @lordofthejars Can you please open a PR for Vincent and others to have a look :-)

**Comment by vsevel** [comment]
if vault isn't there, it is going to be not there for everybody (the only extension is where one replica does not see the vault because of a firewall issue, but the other replicas do). so if your readiness probe fails on vault, this will make all your replicas offline, which will trigger monitoring alerts on your component, whereas there is nothing wrong with your app. typically if your app was doing 99% of its use cases without vault, it would be unfortunate to make it go offline, just because the vault is not reachable for some time. 
one approach is to build some resiliency in your app with a circuitbreaker and a default value or some caching, or fail that one use case if you cannot do without getting a very up to date confidential information. 
it might be interesting to have the option to add the vault connectivity as part of the readiness probe, but I would make it not activated by default.

**Comment by lordofthejars** [comment]
Sure I am not saying to enabled by default, but at least having it

**Comment by sberyozkin** [comment]
Hi @lordofthejars what is your plan around this issue ? Will I assign it to you ?

**Comment by lordofthejars** [comment]
Yes assign to me, maybe it will take some time but I'll do it for sure.

**Comment by sberyozkin** [comment]
@lordofthejars sure, will do, thanks

**Comment by vsevel** [comment]
hello @lordofthejars 
I was using `VaultSystemBackendEngine.healthStatus()` that you developed in the context of this PR.
my vault was in standby and unsealed, hence I got a `429` at the client level.
but from the quarkus vault api, I was expecting a `VaultHealthStatus` with the appropriate fields filled up. instead I got a `VaultClientException` with status 429.
actually, all results will end up throwing an exception, except the `200`.
is this the behavior you intended to provide? if so, we could question whether or not we need all of these fields on class `VaultHealthStatus`, since the only time we are going to have a `VaultHealthStatus` instance, is when initialized=true, sealed=false, ...
may be it is ok the keep the current behavior, but we should make it clearer in the javadoc that exceptions get returned when we have a status different from 200.
what do you think?

**Comment by lordofthejars** [comment]
It was a long time ago and I cannot remember right now sorry.
