### ISSUE TITLE
Integration between Vault extension and Vault Agent

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#7008]
**Description**

Integration between Vault extension and Vault Agent so injected secrets can be read easily.

**Implementation ideas**

Recently, Vault has created an agent that injects secrets directly into the container using an init and sidecar container. In short summary, the agent creates configuration files at `/vault/secrets` directory.

So, for example, could create several configuration files like:

```
/vault/secrets/hello.properties
/vault/secrets/db.properties
```

So the idea would be to provide a custom `ConfigSource` that is able to read all the files from `/vault/secrets` and expose the properties as any other Quarkus property.

@vsevel WDYT?

**Comment by vsevel** [comment]
my own understanding is that the vault agent is a very good solution when your technology does not support interacting with vault natively (e.g. quarkus before we created the vault extension). it is universal as any technology is capable of drawing config properties from a file, plus acts as a cache. you only have to make a local read on your config files if you want secrets hot reload.
I find it however to have the minor drawback of consuming resources (if you have 1000 quarkus microservices running in your cluster, you will end up with 1000 vault agents by your side), and the bigger drawback of placing all of your secrets on disk in your container. even if you use an empty dir with medium=Memory, it is an easy target for whoever is capable of opening a terminal in your container (cluster admins for instance). this puts a bigger burden on securing access to the cluster. it is true that any knowledgeable rotten cluster admin would be able to make the appropriate rest calls to vault to fetch your secrets even without the agent approach, but this is still a bit more difficult than doing a cat on /vault/secrets/db.properties.
for this reason alone, I would rather have my app technology to implement native support for vault if I can. and that is for that very reason that I developed the vault extension.
that said, if you want to use that approach because for instance it is easier to configure, or the caching works better than the extension (which is probably true), then it is valid, but I see this as outside the scope of the vault extension itself. don't you think?
cc @sberyozkin

**Comment by lordofthejars** [comment]
Well actually, my point is that we cannot control if user will choose vault agent or not, and since it is something specific to Vault, it should be Vault who provides this integration as well. I mean it is not something out of Vault, it is about Vault and Vault Agent how they mount secrets, so it is just provides an integration so the users can choose whatever they want to use the extension operations to get the secrets or mount them form the output of Vault agent.

At the end they are not a substitute but something that user can choose.

**Comment by sberyozkin** [comment]
Hi @lordofthejars Quarkus Vault extension already offers a `ConfigSource` which can support the injection of Vault secrets into some custom or even existing Quarkus secret properties (via indirection). This extension communicates directly with Vault. 
If I understand it correctly, `Vault Agent` can be used independently, it will fetch the Vault secrets, and in your case, will make them available in the container. You propose to have `ConfigSource` to make those secrets available to Quarkus.
I'm not sure right now how can Quarkus Vault help here ? These are secrets which Vault agent mounted, they came originally from Vault, but it could've been the secrets from somewhere else...So a generic ConfigSource configured with the arbitrary path to the mounted secrets files would work ? Sorry if I'm missing something.

Or Would you like some existing Quarkus Vault  integration like Agroal code be able to reuse those secrets ? I suspect providing a light-weight alternative which uses Vault SPI might work then...
 
Thanks

**Comment by lordofthejars** [comment]
You are right any ConfigSource that you can set the custom path might work.
But it should load all files of the dir as vault agent could mount more
than one.

**Comment by vsevel** [comment]
I still do not see the relationship with the vault extension
what would you develop in the extension to support effectively an approach based on a vault agent?
what we could need is a config source that can point to a dir, load all files and watch them for changes.
but I am not convinced that this should be the responsibility of the vault extension, as other sidecar containers could be working in a similar way. so this is not specific to vault.
don't we have this capability in MP config: watching a folder of properties files, and reloading them as needed? isn't it where we should look at?

**Comment by lordofthejars** [comment]
Vincent you are totally right, I think that an extension that implement a
watch would be great

**Comment by sberyozkin** [comment]
@lordofthejars Hi, are you OK if I close this issue ?

**Comment by lordofthejars** [comment]
Yes close it as I sent a PR to smallrye

**Comment by sberyozkin** [comment]
@lordofthejars great, thanks
