### ISSUE TITLE
Test that CDI beans in SmallRye Health are present

### ISSUE THREAD

**Issue by antoinesd** [quarkusio/quarkus#7030]
**Description**
Check that all expected CDI beans in SR Health are deployed once

**Comment by paulrobinson** [comment]
Thanks for opening this. Do you know if this is already covered by the MP TCK tests? We've now got agreement that we don't need to duplicate tests in Quarkus that are already covered by the MP TCK.

**Comment by paulrobinson** [comment]
Thanks for opening this. Do you know if this is already covered by the MP TCK tests? We've now got agreement that we don't need to duplicate tests in Quarkus that are already covered by the MP TCK.

**Comment by jmartisk** [comment]
By the way I noticed that SmallRye Health implementation module contains a `beans.xml` file: https://github.com/smallrye/smallrye-health/blob/master/implementation/src/main/resources/META-INF/beans.xml so that means all CDI beans from it are automatically picked up by Quarkus. I think this is generally a bad idea and can lead to beans being picked up when they are not needed. Beans should be enabled as-needed through an `AdditionalBeanBuildItem`, as most extensions do.

**Comment by jmartisk** [comment]
TCK tests, IIUC, verify the high level functionality (health reporting), CDI beans are a lower level component needed to achieve this, so I guess they don't really care what beans there are, but if there were important beans missing, then the health reporting would not work as expected, so the TCK tests would fail.

**Comment by xstefank** [comment]
TCK is not testing this.

@jmartisk this is not the right place to discuss SR in particular but remember that SR is not only used in Quarkus.
