### ISSUE TITLE
quarkus-logging-sentry and quarkus-undertow -  java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7407]
When using quarkus-logging-sentry and quarkus-undertow an app user gets `java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer`

```
[INFO] Running io.quarkus.qe.MyResourceTest
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 2.998 s <<< FAILURE! - in io.quarkus.qe.MyResourceTest
[ERROR] testHelloEndpoint  Time elapsed: 0.013 s  <<< ERROR!
java.lang.RuntimeException: java.lang.ExceptionInInitializerError
Caused by: java.lang.ExceptionInInitializerError
Caused by: java.lang.RuntimeException: Failed to start quarkus
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
Caused by: java.lang.RuntimeException: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
Caused by: java.lang.ClassCastException: io.sentry.servlet.SentryServletContainerInitializer cannot be cast to javax.servlet.ServletContainerInitializer
```

Reproducer:
```
rm -rf fooBar
mvn io.quarkus:quarkus-maven-plugin:999-SNAPSHOT:create \
    -DprojectGroupId=io.quarkus.qe \
    -DprojectArtifactId=fooBar \
    -DprojectVersion=1.0.0-SNAPSHOT \
    -DplatformArtifactId=quarkus-bom \
    -DclassName="io.quarkus.qe.MyResource" \
    -Dextensions="quarkus-logging-sentry,quarkus-undertow"
mvn -f fooBar/pom.xml clean verify
```

**Comment by geoand** [comment]
cc @ia3andy

**Comment by gsmet** [comment]
Looks like a class loader issue.

And there's a good chance it will break code.quarkus.io on upgrade so we really need a fix.

**Comment by ia3andy** [comment]
What Quarkus version?

**Comment by geoand** [comment]
I can take a look if needed (although not excited about what does look like a ClassLoader issue :))

**Comment by ia3andy** [comment]
@geoand I'll have a look and let u know if I have troobles ;-)

**Comment by rsvoboda** [comment]
> What Quarkus version?

master, see reproducer command

**Comment by ia3andy** [comment]
Looking in the code, I found a similar case for Spring which seems fixed by `BlacklistedServletContainerInitializerBuildItem`. Added this code to the Sentry recorder which fix the bug. 
```
 @BuildStep
    public BlacklistedServletContainerInitializerBuildItem blacklistServlet() {
        return new BlacklistedServletContainerInitializerBuildItem("io.sentry.servlet.SentryServletContainerInitializer");
    }
```

I think this is a good thing at the end because we had no control over this `SentryServletContainerInitializer ` which was always enabled. Now I need a way to add our own sentry servlet initializer managed by us to replace it :)

**Comment by geoand** [comment]
I probably added that Spring thing but I have no recollection of it 😂

**Comment by ia3andy** [comment]
@gsmet how urgent is it?

**Comment by ia3andy** [comment]
@stuartwdouglas I haven't found a good solution without reimplementing Sentry. I don't know why the app classloader doesn't include the `ServletRequestListener`. I've excluded `javax.servlet-api` to be sure it wasn't a conflict.

FYI this is a blocking problem since code.quarkus.io uses Undertow and Sentry together.
