### ISSUE TITLE
JAX-RS - Generate reflection declaration from MP OpenAPI schema definition

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#745]
It is possible to define the entity types via the MP OpenAPI annotations. Look for an example here:
https://openliberty.io/guides/microprofile-openapi.html#augmenting-the-existing-jax-rs-annotations-with-openapi-annotations

These entity types should be registered for reflection as they will probably be serialized at some point.

AFAICS, in `@Schema`, there is `implementation` but we should probably also take into account `oneOf` and friends.

See what we already do here: https://github.com/quarkusio/quarkus/blob/master/extensions/resteasy/deployment/src/main/java/io/quarkus/resteasy/deployment/ResteasyScanningProcessor.java#L517 .

**Comment by machi1990** [comment]
Hi @gsmet, the link is not longer available.

**Comment by gsmet** [comment]
@machi1990 fixed!

**Comment by machi1990** [comment]
Great, let me check the link and see if I can take this as my good-first issue.

**Comment by machi1990** [comment]
Hey @gsmet, I checked out the link and seem to have a slightly idea of whats need to be done. Before proceeding further, I wanted to create a draft PR so that you could check and tell me what you about the approach. My general idea [is](https://github.com/machi1990/quarkus/commit/2fee0fdcedaa01b72ddad3e49f14afff649f1f77): 
- Scan for SCHEMA annotation,
- For each annotation, look for implementation , not, oneOf, anyOf, allOf annotation values and generate a class corresponding class definition.  

WDYT?

**Comment by gsmet** [comment]
@machi1990 good work, you're on the right track.

I added some comments on your commit here: https://github.com/machi1990/quarkus/commit/2fee0fdcedaa01b72ddad3e49f14afff649f1f77 .

HTH.

**Comment by machi1990** [comment]
@gsmet  I have incorporated your suggestions and opened a [PR](https://github.com/machi1990/quarkus/pull/1) agains my fork.
