### ISSUE TITLE
Fix @Fallback issues of smallrye-fault-tolerance for Quarkus

### ISSUE THREAD

**Issue by rsvoboda** [quarkusio/quarkus#7529]
Fix `@Fallback` issues of smallrye-fault-tolerance for Quarkus, these issues were noticed with https://github.com/jboss-eap-qe/eap-microprofile-test-suite/ TS. @Ladicek I can't set you as assignee :/

 - https://github.com/smallrye/smallrye-fault-tolerance/issues/197
 - https://github.com/smallrye/smallrye-fault-tolerance/issues/198

Also some CDI extension changes were mentioned in https://quarkusio.zulipchat.com/#narrow/stream/191168-core-team/topic/smallrye-fault-tolerance.20-.20issues.20197.2F198/near/189576039

**Comment by Ladicek** [comment]
The issues mentioned here, together with https://github.com/smallrye/smallrye-fault-tolerance/issues/199, are fixed in SmallRye Fault Tolerance 4.1.1. The changes in the CDI extension were actually only in the interceptor code, so no changes in the Quarkus extension are needed. I'll submit a PR soon, waiting for the CI runs to finish on my fork.
