### ISSUE TITLE
Auto-generated docs for JibConfig not working properly

### ISSUE THREAD

**Issue by geoand** [quarkusio/quarkus#7743]
Same for S2iConfig and DockerConfig.

Basically although a file `quarkus-jib-jib-config.adoc` gets generated, there is no `quarkus-jib-config.adoc`

**Comment by geoand** [comment]
cc @gsmet

**Comment by gsmet** [comment]
So the `quarkus-jib-jib-config.adoc` should be generated. What I don't understand is why `quarkus-jib.adoc` is not.

@machi1990 could you have a look at that one?

**Comment by machi1990** [comment]
I'll need to have a look at this. Most probably after https://github.com/quarkusio/quarkus/issues/7745 and https://github.com/quarkusio/quarkus/issues/7746 ;-)

**Comment by gsmet** [comment]
Silly me.

The extensions are named `container-image-jib`... so that's what the centralized file is named. The other split files are based on config roots/groups/files and so on.

What we should use is:
* quarkus-container-image-docker.adoc 
* quarkus-container-image-jib.adoc
* quarkus-container-image-s2i.adoc

@geoand can you take care of it?

**Comment by machi1990** [comment]
Thanks @gsmet for having a look.

**Comment by geoand** [comment]
Ah, cool. Thanks for checking! I'll take care of it tonight
