### ISSUE TITLE
smallrye messaging Emitter transaction support

### ISSUE THREAD

**Issue by muratkarakas** [quarkusio/quarkus#7810]
**Is it possible to perform transactional  emitter.send() operation like below.**

`@ApplicationScoped
public class PostService {

    ObjectMapper mapper = new ObjectMapper();
     @Inject @Channel("post-create")
     Emitter<String> emitter;
     private Logger logger = LoggerFactory.getLogger(getClass());

    @Transactional(value = TxType.REQUIRED)
    public void createPost(Post post) throws JsonProcessingException {
        String payload = mapper.writeValueAsString(post);

         Post.persist(post);
         emitter.send(payload); 

         // emitter.send(payload);   this is the problem case
         // Post.persist(post);
    }
}`

If not possible what is the proper way of handling transactions in this situation. Currently I am putting the 

> emitter.send(payload);

  at the end of the method. But I need rollback for emitter message in some cases.

**Comment by drsarutobi8** [comment]
Hi, I have the sample question. Is there any way to do this?

**Comment by cescoffier** [comment]
I documented this in #19544:

```java
 @POST
 @Path("/fruits")
 @Transactional                                                      
 public CompletionStage<Void> storeAndSendToKafka(Fruit fruit) {    
        fruit.persist();
        return emitter.send(fruit);                                     
  }
```

**Comment by ahofmeister** [comment]
@cescoffier I have kind of the same problem, but in my case, I need to return the fruit (entity), which was persisted to the database. Is there any workaround?

**Comment by cescoffier** [comment]
@ahofmeister Just:

```java
 @POST
 @Path("/fruits")
 @Transactional                                                      
 public CompletionStage<Void> storeAndSendToKafka(Fruit fruit) {    
        fruit.persist();
        return emitter.send(fruit).thenApply(v -> fruit);
  }
```

**Comment by markuseckstein** [comment]
I couldn't figure out how I would do this if I can't send Pojo but a Message (with RecordHeaders, etc.). Then the send method doesn't return a CompletionStage and the docs about the ACK, NACK Suppliers of the Message are a bit unclear to me.
Anybody has an example how to do this when emitting a Message instance?

**Comment by jesantana** [comment]
I also stumbled into this use case, and after a lot of testing, it is worth clarifying that returning a `CompletionStage` does not rollback the emitter message as @muratkarakas wanted (at least in version 2.14.0) but just avoid closing the transaction before the message was acknowledged by Kafka and hence seeing the error `Enlisted connection used without active transaction`.

To workaround the message being "rollbacked" when there was a DB error on the transaction I had to use `persistAndFlush()` to force and inmediate write and hence fail before sending the message.

Also I noticed that returning and Uni from a MutinyEmitter instead of CompletionStage from an Emitter didn't avoid the error `Enlisted connection used without active transaction` so I think there must be some problem on the way MutinyEmitter finishes the Uni and acknowledge the message.
