### ISSUE TITLE
Infinispan Query dependencies should be included in the Infinispan client

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#804]
While keeping dependency trees small is a good idea, we shouldn't split extensions too fine-grainedly as that has an impact on usability.

Specifically the Infinispan Client guide currently explains that to use query an additional dependency needs to be added.

I think we should include such things by default, and possibly work to make them have minimal impact. 

"Minimal Impact" in an ideal world means they cost 0 bytes in native mode when unused, or something reasonably close to that.

Keeping them to "size zero" in JVM mode is obviously wishful thinking, but they shouldn't have too bad of an impact (as classes are lazily loaded); clearly it's a good time to have a critical look at their deps tree.

**Comment by karesti** [comment]
The dependency is mandatory even if you don't need query, it was not properly working on native, see https://github.com/quarkusio/quarkus/commit/587dfcd7f4d9c5921359eaaada95f8827108af1f#diff-b83041779974482399806b16cdac7068

This is explained as an issue to be corrected in the actual guide. @wburns what do you think about this issue? Should the dependency be removed even if not mandatory anymore?

**Comment by Sanne** [comment]
right @karesti the dependency is needed. I'm not suggesting to remove it, just to make sure that this has minimal overhead (possibly none at all) when it's not actually being used in practice.

> I think we should include such things by default, and possibly work to make them have minimal impact.

**Comment by karesti** [comment]
@Sanne I understand you point! Probably I've been not clear myself. My question was more about @wburns that has put in the documentation that we added it because now is actually needed for technical reasons in native, but that we will remove it when this will be corrected. Which is exactly the opposite - at my understanding - to what you are asking in this issue (that dependency should stay regardless of any technical issue). I'm more on this idea too (having the dependency, and if for any reason you don't need it at all and you want to remove it, then tell how to do it. Maybe with the new api and caching vs datagrid semantics we will actually solve "the problem", but the API won't be there super fast neither).

**Comment by karesti** [comment]
This is already done
