### ISSUE TITLE
security documentation index is hard to understand

### ISSUE THREAD

**Issue by Ladicek** [quarkusio/quarkus#8109]
**Description**
I'm trying to navigate the Quarkus security landscape, but it's hard. The documentation index is particularly unhelpful. Here's how it looks in the left column of https://quarkus.io/guides/:

- Using OpenID Connect to Protect JAX-RS Applications
- Protecting Web Applications Using OpenID Connect
- Supporting Multi-Tenancy in OpenID Connect Applications
- Using Keycloak to centralize your authorizations
- Using Security
- Using Vault
- Using Vault Transit Secret Engine
- Using JWT RBAC
- Using OAuth2 RBAC
- Using Security from JPA
- Using Security with JDBC Realm

Here are my objections:

1. The order is strange. Should it begin with "Using Security"? Putting Vault towards the end probably.
2. Link to `security-properties` is missing, even though it's available from the Security Guide.
3. Headings "Using OpenID Connect to Protect JAX-RS Applications" and "Protecting Web Applications Using OpenID Connect" are completely interchangeable. These guides must have better names, if they describe different things -- but to me, it seems they describe the exact same thing. In which case, only one guide should remain.

Here's what I would suggest:

- Using Security
- Using Security with .properties file
- Using Security with JPA
- Using Security with JDBC
- Using JWT RBAC
- Using OAuth2 RBAC
- Using OpenID Connect to Protect Web Applications
- Supporting Multi-Tenancy in OpenID Connect Applications
- Using Keycloak to centralize your authorizations
- Using Vault
- Using Vault Transit Secret Engine

**Comment by Ladicek** [comment]
WDYT @sberyozkin?

**Comment by sberyozkin** [comment]
Hi Ladislav, @Ladicek, sorry for a delay, some reorganizing may indeed help, FYI,

> Using OpenID Connect to Protect JAX-RS Applications
> Protecting Web Applications Using OpenID Connect

These point to the different modes in which `quarkus-oidc` can operate, 1st one - when OIDC `service` applications are run (HTTP Authorization has a bearer token), 2nd - when OIDC `web-app` applications are run (The user is redirected back to OIDC server, and then Quarkus will acquire a token itself). 
Multi-tenancy - is about combining these two, and Keycloak section - about OIDC `service` applications using KC to centralize the policies.

I think grouping `Security` section on top is a good idea as that all covers the fundamentals.
I guess it would in time be good to group OIDC/Vault indexes in their own index pages, until then may be a minor reordering around what you propose since we recommend to use OIDC end to end when possible:
```
- Using Security
- Using Security with .properties file
- Using Security with JPA
- Using Security with JDBC
- Using OpenID Connect to Protect Service Applications
- Using OpenID Connect to Protect Web Applications
- Using OpenID Connect Multi-Tenancy
- Using OpenID Connect and Keycloak to centralize authorizations
- Using JWT RBAC
- Using OAuth2 RBAC
- Using Vault
- Using Vault Transit Secret Engine
```
?

Thanks

CC @gsmet @stuartwdouglas

**Comment by Ladicek** [comment]
That makes sense to me, too. Thanks! :-)

**Comment by gsmet** [comment]
https://github.com/quarkusio/quarkus/pull/8144
https://github.com/quarkusio/quarkusio.github.io/pull/492

**Comment by gsmet** [comment]
I let you guys approve the PRs above :).

**Comment by sberyozkin** [comment]
Hi @Ladicek @gsmet thanks

**Comment by Ladicek** [comment]
Both PRs LGTM, thanks!

**Comment by Ladicek** [comment]
Closing, as both PRs have been merged.
