### ISSUE TITLE
Optional activation of Quarkus Security as JAX-RS filter

### ISSUE THREAD

**Issue by sberyozkin** [quarkusio/quarkus#8570]
**Description**
At the moment Quarkus Security is activated before a JAX-RS chain starts. The following issues are some of the issues that JAX-RS users may be seeing:
* They can't intercept Quarkus Security exceptions with `ExceptionMapper`
* Token auto-propagation which is free for MP RestClient is not possible

**Implementation ideas**
Activate Quarkus Security, when requested by the configuration property, as the very 1st prematch `JAX-RS ContainerRequestFilter`

CC @stuartwdouglas Hi Stuart not sure how feasible it is, and even if it is, if the complexity can be too high just to meet the above 2 cases, but lets talk a bit about it and see if it makes sense, thanks

**Comment by sberyozkin** [comment]
Hi Stuart @stuartwdouglas Can we discuss this option a bit more ? Without it we can't support the user provided custom JAX-RS exception mappers dealing with 401/403...Thanks

**Comment by stuartwdouglas** [comment]
Some of this already works, the rest can't really be done in a secure way.

Permission checks are done via CDI interceptors, so the failure is a normal exception that can be mapped as normal. If you want to map authentication failures as well as authorisation then you need to disable proactive auth, and then you can use an exception mapper for the resulting AuthenticationFailedException, as it will be generated from the interceptor rather than early in security handling.

What is the issue with token propagation?

**Comment by juandiii** [comment]
@stuartwdouglas Thanks for the tip! It's sound interesting about _proactive Authentication_!

**Comment by sberyozkin** [comment]
@stuartwdouglas This is cool, I'll give it a go and add a test a bit later on

**Comment by sberyozkin** [comment]
@stuartwdouglas 
> What is the issue with token propagation?
I'll need to check again, MP REST Client can auto-propagate the token, I thought, when I looked at it last time, it was not possible with the (proactive) approach, will check...

**Comment by stuartwdouglas** [comment]
The test for modifying the identity from a filter is here: https://github.com/quarkusio/quarkus/blob/70f8288021d7eea10f8e53d8cf22bef2cc924aef/extensions/resteasy/deployment/src/test/java/io/quarkus/resteasy/test/security/ReplaceIdentityLazyAuthRolesAllowedJaxRsTestCase.java#L17

**Comment by KaiHawai** [comment]
Hey Everybody, in the current quarkus (1.7.0) there is stillthe behaviour that you get an 500 instead of an 403 when the JWT Token has expired. Will there be a Fix coming??

**Comment by unhurried** [comment]
Can anybody share the status of this issue? There alredy exists [a guide](https://quarkus.io/guides/security-built-in-authentication#how-to-customize-authentication-exception-responses)  to disable proactive authentication, and I confirmed that I now can capture AuthenticationFailedException in both JAX-RS exception mappers and RESTEasy server exception mappers. (I tested with Quarkus 2.10.1.Final.)

I have an issue when trying to customize the authentication error responses with quarkus-smallrye-jwt in an exception mapper, that throws `java.lang.IllegalStateException: Response has already been written`. I assume there is something wrong with quarkus-smallrye-jwt and is going to seek a solution, but before that, I wanted to confirm if the quarkus part is already fixed to make sure I don't go to the wrong way.

**Comment by michalvavrik** [comment]
> I have an issue when trying to customize the authentication error responses with quarkus-smallrye-jwt in an exception mapper, that throws `java.lang.IllegalStateException: Response has already been written`. I assume there is something wrong with quarkus-smallrye-jwt and is going to seek a solution, but before that, I wanted to confirm if the quarkus part is already fixed to make sure I don't go to the wrong way.

fyi @unhurried - that's fixed in 2.14 (and current main)

**Comment by unhurried** [comment]
Just to share information. Thanks to the update from @michalvavrik, I tested the error handling for authentication errors in ExceptionMappers again. It turned out that authentication errors can be handled in JAX-RS ExceptionMappers in `2.14.0.CR1` version. All I did was to add a configuration `quarkus.http.auth.proactive=false` and ExceptionMappers for `UnauthorizedException` and `AuthenticaionFailedException` (both are under `io.quarkus.security` package).

My setup is basically quarkus-resteasy-reactive + quarkus-smallrye-jwt. You can find the project [here](https://github.com/unhurried/backend-example-quarkus/tree/v0.3.3-SNAPSHOT) in my repository.

**Comment by bgizdov** [comment]
It works for me as well for the UnauthorizedException and AuthenticationFailedException, even without setting quarkus.http.auth.proactive=false. I'm using Quarkus 2.16.6.Final.

**Comment by geoand** [comment]
@sberyozkin is this still an issue?

**Comment by michalvavrik** [comment]
> @sberyozkin is this still an issue?

IMHO we can do better because pre-match JAX-RS filter won't allow us to match invoked method and it won't allows us to run fully async auth. 

However I don't know about this point from description: _Token auto-propagation which is free for MP RestClient is not possible_. Also might be other points I am missing. @sberyozkin is that still an issue or maybe particular problems deserve separate ticket?

**Comment by michalvavrik** [comment]
I think what is described in this issue is implemented for all cases we wanted to address. Security exceptions can be handled with error handlers and exception mappers as documented. HttpSecuritPolicies can also be run by JAX-RS filter if `applies-to` is set. SecurityChecks are also run in filters etc. There is no issue for token propagation I am aware about. I'd suggest to open dedicated issue if you can see room for improvement.
