### ISSUE TITLE
CredentialsProvider beans should be made unremovable

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#8828]

**Comment by machi1990** [comment]
Is this issue related to https://github.com/quarkusio/quarkus/issues/8826?

**Comment by machi1990** [comment]
Asking because this seems to already being done in this build step https://github.com/quarkusio/quarkus/blob/master/extensions/vault/deployment/src/main/java/io/quarkus/vault/VaultProcessor.java#L59 but only for the vault extension. With the discussion you have on the other issue maybe the two can be done together by just having this build step in the deployment module of the new thingy ?
