### ISSUE TITLE
Add prometheus client extension

### ISSUE THREAD

**Issue by rmetzler** [quarkusio/quarkus#9398]
**Description**

please add https://github.com/prometheus/client_java

**Comment by rquinio** [comment]
@rmetzler I guess the use case is for someone using  [Prometheus client API](https://github.com/prometheus/client_java/tree/master/simpleclient/src/main/java/io/prometheus/client) to be able to see their existing metrics via the Quarkus /metrics endpoint, right ?

Some thoughts:
* since Prometheus client API is not annotation-based like microprofile-metrics and it's not a 1:1 API mapping, I guess built-time replacements is not an option ?
* create a bridge so that instead of using the internal Prometheus registry, it creates the metrics inside the microprofile/[smallrye-metrics](https://github.com/smallrye/smallrye-metrics) registry ?
* append the Prometheus registry metrics to the raw output of /metrics endpoint in quarkus-smallrye-metrics extension, if a Prometheus registry is detected ?

Also cf #6544 regarding Micrometer and https://github.com/ebullient/quarkus-micrometer-extension which has indirect Prometheus support via Micrometer.

**Comment by kenfinnigan** [comment]
Is the ask here to, abstractly, add a better API for registering metrics to be output?

**Comment by ebullient** [comment]
See #11180 for the Micrometer extension. The prometheus registry implementation used by micrometer is based on the prometheus client.

**Comment by ebullient** [comment]
The quarkus micrometer extension has been integrated into Quarkus core as of 1.8.0.Final.

Is there something else to this request, or can we close it?

**Comment by ebullient** [comment]
I recommend we close this. w/ micrometer extension, you can add (and obtain a direct reference to) a prometheus meter registry.. and from there can use prom client APIs directly if you choose.

**Comment by kenfinnigan** [comment]
+1
