### ISSUE TITLE
Support additional named reactive datasources

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#9606]
Right now, the reactive datasources (reactive-mysql-client and reactive-pg-client) do not suppord additional named datasources, which is a bit unfortunate considering they are sharing the configuration with the Agroal datasources.

We should support it and we can copy the patterns used for the Agroal datasources. Note that we don't need to support the legacy stuff for the additional named datasources as it's a new feature so let's just implement the new configuration pattern for them.

**Comment by anamarija** [comment]
Ok, I will start working on it. Thanks @gsmet

**Comment by gsmet** [comment]
Feel free to ping me if you need some guidance or have some questions, I will be happy to help.

**Comment by anamarija** [comment]
Sure, thanks.

**Comment by anamarija** [comment]
Going through the code and design decisions regarding common datasource configuration with reactive datasource pools, all the specific pooling implementation is inside the reactive driver extension. 
Is the idea to keep it this way and implement multiple datasource creation logic every time for each extension within it or is the intention to abstract the datasource pooling creation in a common layer and then specific implementations would provide their specific io.vertx.sqlclient.Pool implementation and add maybe a configurer  to apply implementation specific features.

What is the status with use of urls. It appeared  to me that it is deprecated throughout all datasources blocking|non blocking and that the use of properties is encouraged. Does this apply to the reactive datasources? Are the properties defined through the common datasource configuration enough?

**Comment by anamarija** [comment]
Another thing that popped into my mind was when you have the situations of multiple datasources. How do you know which one is reactive and which is blocking. Wouldn't it be a good approach to have a property on the datasource common to know which type of driver we are using for this specific datasource.

**Comment by gsmet** [comment]
So, the overall design is:
* you define a datasource
* it can be either reactive or JDBC or both depending on what you configure

Basically, it all depends if you have a `reactive.enabled` or `jdbc.enabled` defined to true for this datasource, true is the default.

The default behavior is that as soon as you have both a JDBC driver and a reactive driver in the classpath, both type of datasources will be created (or at least we will try to create them). In most cases, you will have only one of reactive or JDBC in the classpath so things will be smooth. And if you have both, you need to tweak things for each datasource `enabled` flags depending on what you want.

I think I would first try to implement it for one of the reactive driver. Then while doing it for the other, I would check if we can put a few things in the `reactive-datasource` common artifacts.

But I would keep the JDBC and Reactive separate for now (except for the parts that are already common).

**Comment by anamarija** [comment]
Hi,

I created an initial commit with the namedDataSource functionality, but I have some issues which I worked around but I should address them. Configuration clashes...
https://github.com/anamarija/quarkus/commit/f3d8c1662ec4831373c4c040e4a2b5afe25facb4

I created a small reproducer to test this behaviour.
https://github.com/anamarija/getting-started-reactive-crud.git

1. When I add  
@ConfigItem
    public OptionalInt maxSize = OptionalInt.empty();
I get the following classLoader error
`Caused by: java.lang.IllegalAccessError: class io.quarkus.deployment.steps.ReactivePgClientProcessor$build1800565150 tried to access private method 'void java.util.OptionalInt.<init>()' (io.quarkus.deployment.steps.ReactivePgClientProcessor$build1800565150 is in unnamed module of loader io.quarkus.bootstrap.classloading.QuarkusClassLoader @58e0d1ac; java.util.OptionalInt is in module java.base of loader 'bootstrap')
	at io.quarkus.deployment.steps.ReactivePgClientProcessor$build1800565150.deploy_0(ReactivePgClientProcessor$build1800565150.zig:113)
	at io.quarkus.deployment.steps.ReactivePgClientProcessor$build1800565150.deploy(ReactivePgClientProcessor$build1800565150.zig:36)
	at io.quarkus.runner.ApplicationImpl.doStart(ApplicationImpl.zig:322)`

After a test fails, reruning the extension build starts complaining about "No root found for" runtime and buildtime configurations. Is this something thats expected?

Could you take a look and get back to me on IM so that we could discuss this.

**Comment by anamarija** [comment]
Hi,
@gsmet can I try to tackle this issue again or is it already covered by someone else 😃

**Comment by geoand** [comment]
This is supported (albeit I don't know when it started to be supported).
See https://github.com/quarkusio/quarkus/blob/2.1.0.Final/extensions/reactive-mssql-client/deployment/src/test/java/io/quarkus/reactive/mssql/client/MultipleDataSourcesTest.java for an example of a relevant test
