### ISSUE TITLE
README.md does not show the current version in badges

### ISSUE THREAD

**Issue by lordofthejars** [quarkusio/quarkus#9672]
**Describe the bug**

README.md does not show the current version in badges. Currently we are in 1.4.2 but badge shows 1.3.3.Final

<img width="1020" alt="Screenshot 2020-05-29 at 05 09 41" src="https://user-images.githubusercontent.com/1517153/83216949-c01db880-a16a-11ea-84c3-75ea4409f069.png">

**Comment by geoand** [comment]
Good catch.

Let's update this when `1.5.0.Final` lands so we only have one update to do :)

@gsmet perhaps this step should be added as part of the release checklist?

**Comment by rquinio** [comment]
Based on https://shields.io/category/version it's possible to add `&sort=semver`
https://img.shields.io/github/v/release/quarkusio/quarkus?style=for-the-badge&sort=semver

Though Quarkus doesn't follow semver, so not sure if it could bug...

It currently returns 1.5.0.CR1, probably because it's not actually flagged as a pre-release in Github (there's a checkbox for that).

**Comment by gastaldi** [comment]
I think @rquinio's solution is feasible. Would you mind providing a PR?

**Comment by famod** [comment]
If the CR releases were published as "pre-releases" then you could also have them filtered out.

**Comment by famod** [comment]
I had a quick look: Currently the badge is targeting `maven-central`, not the GH releases page.
Unfortunately `maven-central` does not seem to provide `sort=semver`.
