### ISSUE TITLE
Building GraphQL quickstart generates warnings that should be avoided

### ISSUE THREAD

**Issue by gsmet** [quarkusio/quarkus#9753]
We shouldn't have these warnings when building a GraphQL application:

```
[WARNING] [io.quarkus.deployment.steps.ReflectiveHierarchyStep] Unable to properly register the hierarchy of the following classes for reflection as they are not in the Jandex index:
	- java.lang.Boolean
	- java.lang.Double
	- java.lang.Enum
	- java.lang.Integer
	- java.lang.Object
	- java.lang.String
	- java.time.LocalDate
	- java.util.List
Consider adding them to the index either by creating a Jandex index for your dependency via the Maven plugin, an empty META-INF/beans.xml or quarkus.index-dependency properties.");.
```

**Comment by cemnura** [comment]
I am looking into this.

@phillip-kruger  is aware.

**Comment by cemnura** [comment]
It appears as the ignorePredicate for the ReflectiveHierarchyBuildItem class implementation only
ignores `java.net` classes.  

https://github.com/quarkusio/quarkus/blob/29b123ee0d05eacfa2c391ab876788346f30d26b/extensions/smallrye-graphql/deployment/src/main/java/io/quarkus/smallrye/graphql/deployment/SmallRyeGraphQLProcessor.java#L490-L498

Changing the test method to include all classes starting with `java.` instead of `java.net` suppresses the warning log.

PR to suppress warning logs can be found in PR #10017.
