### ISSUE TITLE
Consider --install-exit-handlers (GraalVM 20.1)

### ISSUE THREAD

**Issue by emmanuelbernard** [quarkusio/quarkus#9795]
Should we use / enable `--install-exit-handlers` now that we have GraalVM 20.1?

**Comment by emmanuelbernard** [comment]
So I think @dmlloyd you said this would not help us to do this. Correct ?

**Comment by dmlloyd** [comment]
I think it probably doesn't help or hurt.  But I will say that if we use this option then when the user opts out of signal handling, we'll have to disable *both* this option *and* our own signal handler.

**Comment by Sanne** [comment]
This might be simpler to do now as we're moving to no longer suppor GraalVM 19. See #10838

**Comment by geoand** [comment]
@zakkak @galderz is this something we want, or should we close?

**Comment by zakkak** [comment]
I guess this issue suggests using GraalVM's `--install-exit-handlers` to register the `exitHandler` from https://github.com/quarkusio/quarkus/blob/3c3cb8d336117fd2382ccd98a58a9fa95ba60ce5/core/runtime/src/main/java/io/quarkus/runtime/ApplicationLifecycleManager.java#L293-L298

Since we will still want to register the `diagnosticsHandler` as well, I personally don't see what's the benefit of using `--install-exit-handlers`. IMO it would only complicate things by registering signal handlers in two places.

**Comment by zakkak** [comment]
Given tha lack of interest/feedback I am closing this as won't-fix. Feel free to re-open if you disagree.
