### ISSUE TITLE
Starting app in dev mode runs the Hibernate import.sql script multiple times

### ISSUE THREAD

**Issue by Sanne** [quarkusio/quarkus#987]
Having a trivial import script like 
```
INSERT INTO known_fruits(id, name) VALUES (1, 'Cherry')
INSERT INTO known_fruits(id, name) VALUES (2, 'Apple')
INSERT INTO known_fruits(id, name) VALUES (3, 'Banana')
```

this is a problem as it triggers duplicate key violations.

**Comment by stuartwdouglas** [comment]
This only happens if the script is named import.sql. In org.hibernate.tool.schema.internal.SchemaCreatorImpl#applyImportSources there are two settings, HBM2DDL_LOAD_SCRIPT_SOURCE which has no default, and HBM2DDL_IMPORT_FILES which defaults to import.sql.

As we explicitly set HBM2DDL_LOAD_SCRIPT_SOURCE to import.sql then both values are set to import.sql, so it gets imported twice.
