### ISSUE TITLE
Allow activation of multiple configuration profiles

### ISSUE THREAD

**Issue by famod** [quarkusio/quarkus#9895]
**Description**
I understand that currently a Quarkus config profile denotes an "environment".

But sometimes you want to resuse configuration bits but you cannot put them in the "common" block (properties without `%<profileName>` prefix).
E.g. in my current project we would like to toggle dev-mode between h2 (default) and postgres (also used in prod, but with slightly different config). We have some more dev specific settings like logging to a file (which we don't do in prod) etc.
In this scenario we have to duplicate many properties from `dev` to `dev-postgres` which violates the DRY principle and makes the config less readable.
(To make things worse we have multiple "layers" of config files in various submodules which are aggregated via a custom `ConfigSourceProvider`.)

It would come in handy if multiple profiles could be actived.

**Implementation ideas**
Allow profiles to be set in a comma separated way, e.g. `foo,bar` (`bar` would overwrite `foo`, Spring Boot style IIRC).

Fun fact (or better to say bug): As of 1.4.2.Final you _can_ set `-Dquarkus.profile=foo,bar` and Quarkus will happily report that it activated `foo,bar`, but nothing of the two profiles is taken into account.

**Comment by famod** [comment]
cc @harthorst & @tkalmar

**Comment by sebthom** [comment]
This is a much needed feature. We have a complex staging process with multiple environments per stage and need to mix/reuse profiles. We use multiple profiles with Spring Boot and now try to transition to Quarkus.

**Comment by kostacasa** [comment]
I agree that this would be useful for activating capabilities that are present in groups of environments. For example, stage, perf and prod might have aws vault a secret manager, it would be useful if this capability could be enabled as an additional profile designation for `aws`.

**Comment by famod** [comment]
@radcortez Do you think this can be done (rather easily)? Or would it require fundamental changes, maybe even to `smallrye-config`?

**Comment by radcortez** [comment]
To support it out of the box, yes do require a few changes, but since we added the latest release of SmallRye Config to Quarkus 1.6, extending config feature should be easier.

Profiles are now implemented using a built-in interceptor in SmallRye Config:
https://github.com/smallrye/smallrye-config/blob/master/implementation/src/main/java/io/smallrye/config/ProfileConfigSourceInterceptor.java

Anyone could implement their own ProfileInterceptor (that could look into as many profiles as required), following the docs here:
https://smallrye.io/docs/smallrye-config/interceptors/interceptors.html

So, if this is a requested feature, we could definite easily implement it. If you don't want to wait until it is done and available in a Quarkus release, you could implement your own.

**Comment by famod** [comment]
@radcortez Thanks a lot for this valuable information!

**Comment by radcortez** [comment]
@famod BTW if you want to support this OOTB, please open an issue in SmallRye Config :)

**Comment by famod** [comment]
> @famod BTW if you want to support this OOTB, please open an issue in SmallRye Config :)

I just did that: https://github.com/quarkusio/quarkus/issues/9895 Thanks again!

**Comment by sebthom** [comment]
@gsmet milestone of this issue is set to 1.9.1.Final and we are now at 1.10.5.Final. Has support for activating multiple profiles already been implemented?

**Comment by radcortez** [comment]
Hi @sebthom, there is a preliminary implementation available in SR Config, which you can use: https://smallrye.io/docs/smallrye-config/config/config.html#profiles.

This is not fully integrated in Quarkus yet, but should mostly work. We were discussing some different ideas regarding multiple profiles. Please check here: https://github.com/quarkusio/quarkus/pull/12841.

I tabled it for a while due to the MP Config 2.0 work, but I think I should be able to pick it again. Thanks!

**Comment by ia3andy** [comment]
@radcortez why is this completed?

**Comment by radcortez** [comment]
> @radcortez why is this completed?

We had some pushback in https://github.com/quarkusio/quarkus/pull/12841.

**Comment by famod** [comment]
TBH, I'd love to see the pushback being pushed back! 😉 

@ia3andy are you going to open a new issue?

**Comment by ia3andy** [comment]
I created https://github.com/quarkusio/quarkus/issues/27760
