### ISSUE TITLE
Improve Java 11 only integration tests handling

### ISSUE THREAD

**Issue by loicmathieu** [quarkusio/quarkus#9904]
**Description**
The new Google Cloud Platform integration tests cannot be build using Java 8, this mandates Java 11 to build Quarkus. The CI has been update to ignore those tests but when someone do a `mvn clean install` on the Quarkus repo with a Java 8 runtime it fails.

We need to overcome this and provides a clear way to handle this:
- Make Java 11 the minimal target to **build** Quarkus (Java 8 will still be able to run int)
- Create a profile to avoid running test that needs Java 11 on Java 8
- Make those test buildable on Java 8 (but not runnable)

**Comment by loicmathieu** [comment]
There may be an issue way to fix this via module inclusion in a specific profile: https://github.com/quarkusio/quarkus/pull/9897#issuecomment-641895100

**Comment by Sanne** [comment]
> Make those test buildable on Java 8 (but not runnable)

+1 please

We need to be able to run the full build on Java 8 too.

**Comment by gemmellr** [comment]
I was thinking my profile suggestion from above would be easiest to get the build working on 8, but something occurred to me while preparing a patch that may suggest otherwise, e.g getting the test module building on 8 but not running the tests.

If using a profile to stop the module running at all when on 8, then it also wont be picked up for re-versioning during the release process, which could lead to it being tagged with the wrong version and breaking future attempts to build the tag (even on 11, once the snapshots aren't compatible), unless @gsmet uses Java11 for that step to have it happen or instead did it manually somehow. Of course, needing to exclude the module on the command line to build with 8 currently would seem to effectively mean the same problem exists as things stand.

I do this 'optional non-deployed module' thing in another project but for very different reasons, and so I can just ensure the release process enables it while tagging in order to set the version. That wouldn't work here unless the module actually builds on 8, or the building can be no-op'ed and the check suppressed during release process to let it just change the version.

The enforcer check that stops things looks to be coming from the jboss parent so any enabling will fail it on 8 while the source/target is 11 it seems, though maybe the module could specifically override the execution somehow.

**Comment by gemmellr** [comment]
I'm only now realising that the module doesn't actually run automated tests. Given the source is 8-compatible, just making them build with 8 does seem like the easy fix in this case if it doesnt break anything where they run?
